### ISSUE TITLE
pdm update gives TypeError after successful lock

### ISSUE THREAD

**Issue by IsotropicTom** [pdm-project/pdm#1003]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

```🔒 Lock successful
Changes are written to pdm.lock.
Traceback (most recent call last):
  File "c:\users\tommoffat\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\tommoffat\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\TomMoffat\AppData\Local\Programs\Python\Python39\Scripts\pdm.exe\__main__.py", line 7, in <module>
  File "c:\users\tommoffat\appdata\local\programs\python\python39\lib\site-packages\pdm\core.py", line 233, in main
    return Core().main(args)
  File "c:\users\tommoffat\appdata\local\programs\python\python39\lib\site-packages\pdm\core.py", line 168, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "c:\users\tommoffat\appdata\local\programs\python\python39\lib\site-packages\pdm\core.py", line 163, in main
    f(options.project, options)
  File "c:\users\tommoffat\appdata\local\programs\python\python39\lib\site-packages\pdm\cli\commands\update.py", line 55, in handle
    actions.do_update(
  File "c:\users\tommoffat\appdata\local\programs\python\python39\lib\site-packages\pdm\cli\actions.py", line 330, in do_update
    do_sync(
  File "c:\users\tommoffat\appdata\local\programs\python\python39\lib\site-packages\pdm\cli\actions.py", line 179, in do_sync
    handler = project.core.synchronizer_class(
  File "c:\users\tommoffat\appdata\local\programs\python\python39\lib\site-packages\pdm\installers\synchronizers.py", line 97, in __init__
    self.working_set = environment.get_working_set()
  File "c:\users\tommoffat\appdata\local\programs\python\python39\lib\site-packages\pdm\models\environment.py", line 136, in get_working_set
    return WorkingSet([paths["platlib"], paths["purelib"]])
  File "c:\users\tommoffat\appdata\local\programs\python\python39\lib\site-packages\pdm\models\working_set.py", line 79, in __init__
    self._dist_map = {
  File "c:\users\tommoffat\appdata\local\programs\python\python39\lib\site-packages\pdm\models\working_set.py", line 80, in <dictcomp>
    normalize_name(dist.metadata["Name"]): dist
  File "c:\users\tommoffat\appdata\local\programs\python\python39\lib\site-packages\pdm\utils.py", line 487, in normalize_name
    return re.sub(r"[^A-Za-z0-9.]+", "-", name).lower()
  File "c:\users\tommoffat\appdata\local\programs\python\python39\lib\re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
```

## Steps to reproduce

Run `pdm update`

## Actual behavior

After successfully locking pdm.lock pdm gives `TypeError: expected string or bytes-like object`

## Expected behavior

pdm to update correctly

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.13.6
Python Interpreter: C:\Users\TomMoffat\AppData\Local\pdm\pdm\venvs\lens_arrangement_python-zKaSFVHn-3.9\Scripts\python.exe (3.9)
Project Root:       C:/Users/TomMoffat/Documents/programming/lens_arrangement_python
Project Packages:   C:\Users\TomMoffat\Documents\programming\lens_arrangement_python\__pypackages__\3.9
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.7",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19044",
  "python_full_version": "3.9.7",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "win32"
}
```

**Comment by chohner** [comment]
I seem to be running into the same issue on a clean project, only adding `streamlit`:

```
> pdm init
(...)
Changes are written to pyproject.toml.

> pdm add streamlit  -v
(...)
🔒 Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
Traceback (most recent call last):
  File "/Users/chohner/.local/bin/pdm", line 10, in <module>
    sys.exit(main())
  File "/Users/chohner/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/core.py", line 254, in main
    return Core().main(args)
  File "/Users/chohner/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/core.py", line 187, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/Users/chohner/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/core.py", line 182, in main
    f(options.project, options)
  File "/Users/chohner/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/cli/commands/add.py", line 58, in handle
    actions.do_add(
  File "/Users/chohner/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/cli/actions.py", line 289, in do_add
    do_sync(
  File "/Users/chohner/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/cli/actions.py", line 207, in do_sync
    handler = project.core.synchronizer_class(
  File "/Users/chohner/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 121, in __init__
    self.working_set = environment.get_working_set()
  File "/Users/chohner/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/models/environment.py", line 164, in get_working_set
    return WorkingSet([paths["platlib"], paths["purelib"]])
  File "/Users/chohner/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/models/working_set.py", line 71, in __init__
    self._dist_map = {
  File "/Users/chohner/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/models/working_set.py", line 72, in <dictcomp>
    normalize_name(dist.metadata["Name"]): dist
  File "/Users/chohner/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/utils.py", line 382, in normalize_name
    name = re.sub(r"[^A-Za-z0-9.]+", "-", name)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
```

My environment:
```pdm info && pdm info --env
PDM version:
  2.0.1
Python Interpreter:
  /usr/local/Caskroom/miniconda/base/bin/python (3.9)
Project Root:
  /Users/chohner/dev/tmp/pdm_debug
Project Packages:
  None
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.13",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "20.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 20.6.0: Tue Apr 19 21:04:45 PDT 2022; root:xnu-7195.141.29~1/RELEASE_X86_64",
  "python_full_version": "3.9.13",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "darwin"
}
```


Not sure how to find the investigate the offending package since streamlit pulls in a lot of dependencies:

```
[[package]]
name = "streamlit"
version = "1.11.0"
requires_python = ">=3.7"
summary = "The fastest way to build data apps in Python"
dependencies = [
    "altair>=3.2.0",
    "attrs>=16.0.0",
    "blinker>=1.0.0",
    "cachetools>=4.0",
    "click>=7.0",
    "gitpython!=3.1.19",
    "importlib-metadata>=1.4",
    "numpy",
    "packaging>=14.1",
    "pandas>=0.21.0",
    "pillow>=6.2.0",
    "protobuf<4,>=3.12",
    "pyarrow>=4.0",
    "pydeck>=0.1.dev5",
    "pympler>=0.9",
    "python-dateutil",
    "requests>=2.4",
    "rich>=10.11.0",
    "semver",
    "toml",
    "tornado>=5.0",
    "typing-extensions>=3.10.0.0",
    "tzlocal>=1.1",
    "validators>=0.2",
    "watchdog; platform_system != \"Darwin\"",
]
```
