### ISSUE TITLE
The installation of mysqlclient reported an error (resolved, show if it can help others).

### ISSUE THREAD

**Issue by ElTarget** [pdm-project/pdm#1022]
Just now, in the PDM environment, in order to use Django, I got an error when installing mysqlclient. Looking at the log, we can see "**OSError: mysql_config not found**", and "**Install mysqlclient 2.1.0 failed**". 
I found the reason, because my system is missing libmysqlclient-dev

So enter "**apt-get install libmysqlclient-dev**" in the terminal to install. Then do "**pdm add mysqlclient**". So all complete!

```
Adding packages to default dependencies: mysqlclienta
======== Start resolving requirements ========
  mysqlclient
  python>=3.8
  Adding requirement mysqlclient
	Found matching candidates:
	  <Candidate mysqlclient 2.1.0 from http://mirrors.cloud.aliyuncs.com/pypi/simple/mysqlclient/>
	  <Candidate mysqlclient 2.0.3 from http://mirrors.cloud.aliyuncs.com/pypi/simple/mysqlclient/>
	  <Candidate mysqlclient 2.0.2 from http://mirrors.cloud.aliyuncs.com/pypi/simple/mysqlclient/>
	  <Candidate mysqlclient 2.0.1 from http://mirrors.cloud.aliyuncs.com/pypi/simple/mysqlclient/>
	  <Candidate mysqlclient 2.0.0 from http://mirrors.cloud.aliyuncs.com/pypi/simple/mysqlclient/>
	  <Candidate mysqlclient 1.4.6 from http://mirrors.cloud.aliyuncs.com/pypi/simple/mysqlclient/>
	  <Candidate mysqlclient 1.4.5 from http://mirrors.cloud.aliyuncs.com/pypi/simple/mysqlclient/>
	  <Candidate mysqlclient 1.4.4 from http://mirrors.cloud.aliyuncs.com/pypi/simple/mysqlclient/>
	  <Candidate mysqlclient 1.4.3 from http://mirrors.cloud.aliyuncs.com/pypi/simple/mysqlclient/>
	  <Candidate mysqlclient 1.4.2.post1 from http://mirrors.cloud.aliyuncs.com/pypi/simple/mysqlclient/>
	  ... [83 more candidate(s)]
  Adding requirement python>=3.8
======== Starting round 0 ========
Resolving: new pin python >=3.8
======== Ending round 0 ========
======== Starting round 1 ========
Resolving: new pin mysqlclient 2.1.0
======== Ending round 1 ========
======== Starting round 2 ========
======== Resolution Result ========
Stable pins:
       python None
  mysqlclient 2.1.0
	Found matching candidates:
	  <Candidate mysqlclient 2.1.0 from http://mirrors.cloud.aliyuncs.com/pypi/simple/mysqlclient/>
🔒 Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
Synchronizing working set with lock file: 1 to add, 0 to update, 0 to remove
Preparing isolated env for PEP 517 build...
Building wheel for http://mirrors.cloud.aliyuncs.com/pypi/packages/de/79/d02be3cb942afda6c99ca207858847572e38146eb73a7c4bfe3bdf154626/mysqlclient-2.1.0.tar.gz#sha256=973235686f1b720536d417bf0a0d39b4ab3d5086b2b6ad5e6752393428c02b12 (from http://mirrors.cloud.aliyuncs.com/pypi/simple/mysqlclient/) (requires-python:>=3.5)
Looking in indexes: http://mirrors.cloud.aliyuncs.com/pypi/simple/
Collecting wheel
  Using cached http://mirrors.cloud.aliyuncs.com/pypi/packages/27/d6/003e593296a85fd6ed616ed962795b2f87709c3eee2bca4f6d0fe55c6d00/wheel-0.37.1-py2.py3-none-any.whl (35 kB)
Collecting setuptools>=40.8.0
  Using cached http://mirrors.cloud.aliyuncs.com/pypi/packages/0c/3c/548d361162702df85a0301f0cd0c47d05176b20bb086077a0fda740daf41/setuptools-62.0.0-py3-none-any.whl (1.1 MB)
Installing collected packages: wheel, setuptools
Successfully installed setuptools-62.0.0 wheel-0.37.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
/bin/sh: 1: mysql_config: not found
/bin/sh: 1: mariadb_config: not found
/bin/sh: 1: mysql_config: not found
mysql_config --version
mariadb_config --version
mysql_config --libs
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 363, in <module>
    main()
  File "/usr/local/python3/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 345, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/usr/local/python3/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/tmp/pdm-build-env-pxgzcsi6-shared/lib/python3.8/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
    return self._get_build_requires(
  File "/tmp/pdm-build-env-pxgzcsi6-shared/lib/python3.8/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
    self.run_setup()
  File "/tmp/pdm-build-env-pxgzcsi6-shared/lib/python3.8/site-packages/setuptools/build_meta.py", line 281, in run_setup
    super(_BuildMetaLegacyBackend,
  File "/tmp/pdm-build-env-pxgzcsi6-shared/lib/python3.8/site-packages/setuptools/build_meta.py", line 174, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 15, in <module>
    metadata, options = get_config()
  File "/tmp/pdm-build-t59axv1z/setup_posix.py", line 70, in get_config
    libs = mysql_config("libs")
  File "/tmp/pdm-build-t59axv1z/setup_posix.py", line 31, in mysql_config
    raise OSError("{} not found".format(_mysql_config_path))
OSError: mysql_config not found
Install mysqlclient 2.1.0 failed
Error occurs: 
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 185, in install_candidate
    self.manager.install(can)
  File "/usr/local/python3/lib/python3.8/site-packages/pdm/installers/manager.py", line 39, in install
    installer(prepared.build(), self.environment, prepared.direct_url())
  File "/usr/local/python3/lib/python3.8/site-packages/pdm/models/candidates.py", line 332, in build
    self.wheel = builder.build(build_dir, metadata_directory=self._metadata_dir)
  File "/usr/local/python3/lib/python3.8/site-packages/pdm/builders/wheel.py", line 26, in build
    requires = self._hook.get_requires_for_build_wheel(config_settings)
  File "/usr/local/python3/lib/python3.8/site-packages/pep517/wrappers.py", line 172, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "/usr/local/python3/lib/python3.8/site-packages/pep517/wrappers.py", line 322, in _call_hook
    self._subprocess_runner(
  File "/usr/local/python3/lib/python3.8/site-packages/pdm/builders/base.py", line 238, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
  File "/usr/local/python3/lib/python3.8/site-packages/pdm/builders/base.py", line 86, in log_subprocessor
    raise BuildError(
pdm.exceptions.BuildError: Call command ['/usr/local/python3/bin/python3.8', '/usr/local/python3/lib/python3.8/site-packages/pep517/in_process/_in_process.py', 'get_requires_for_build_wheel', '/tmp/tmp24__x8ro'] return non-zero status(1).
  Retry failed jobs
Preparing isolated env for PEP 517 build...
Reusing shared build env: /tmp/pdm-build-env-pxgzcsi6-shared
Building wheel for http://mirrors.cloud.aliyuncs.com/pypi/packages/de/79/d02be3cb942afda6c99ca207858847572e38146eb73a7c4bfe3bdf154626/mysqlclient-2.1.0.tar.gz#sha256=973235686f1b720536d417bf0a0d39b4ab3d5086b2b6ad5e6752393428c02b12 (from http://mirrors.cloud.aliyuncs.com/pypi/simple/mysqlclient/) (requires-python:>=3.5)
/bin/sh: 1: mysql_config: not found
/bin/sh: 1: mariadb_config: not found
/bin/sh: 1: mysql_config: not found
mysql_config --version
mariadb_config --version
mysql_config --libs
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 363, in <module>
    main()
  File "/usr/local/python3/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 345, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/usr/local/python3/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/tmp/pdm-build-env-pxgzcsi6-shared/lib/python3.8/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
    return self._get_build_requires(
  File "/tmp/pdm-build-env-pxgzcsi6-shared/lib/python3.8/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
    self.run_setup()
  File "/tmp/pdm-build-env-pxgzcsi6-shared/lib/python3.8/site-packages/setuptools/build_meta.py", line 281, in run_setup
    super(_BuildMetaLegacyBackend,
  File "/tmp/pdm-build-env-pxgzcsi6-shared/lib/python3.8/site-packages/setuptools/build_meta.py", line 174, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 15, in <module>
    metadata, options = get_config()
  File "/tmp/pdm-build-t59axv1z/setup_posix.py", line 70, in get_config
    libs = mysql_config("libs")
  File "/tmp/pdm-build-t59axv1z/setup_posix.py", line 31, in mysql_config
    raise OSError("{} not found".format(_mysql_config_path))
OSError: mysql_config not found
Install mysqlclient 2.1.0 failed
Error occurs: 
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 185, in install_candidate
    self.manager.install(can)
  File "/usr/local/python3/lib/python3.8/site-packages/pdm/installers/manager.py", line 39, in install
    installer(prepared.build(), self.environment, prepared.direct_url())
  File "/usr/local/python3/lib/python3.8/site-packages/pdm/models/candidates.py", line 332, in build
    self.wheel = builder.build(build_dir, metadata_directory=self._metadata_dir)
  File "/usr/local/python3/lib/python3.8/site-packages/pdm/builders/wheel.py", line 26, in build
    requires = self._hook.get_requires_for_build_wheel(config_settings)
  File "/usr/local/python3/lib/python3.8/site-packages/pep517/wrappers.py", line 172, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "/usr/local/python3/lib/python3.8/site-packages/pep517/wrappers.py", line 322, in _call_hook
    self._subprocess_runner(
  File "/usr/local/python3/lib/python3.8/site-packages/pdm/builders/base.py", line 238, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
  File "/usr/local/python3/lib/python3.8/site-packages/pdm/builders/base.py", line 86, in log_subprocessor
    raise BuildError(
pdm.exceptions.BuildError: Call command ['/usr/local/python3/bin/python3.8', '/usr/local/python3/lib/python3.8/site-packages/pep517/in_process/_in_process.py', 'get_requires_for_build_wheel', '/tmp/tmp8wf92t4o'] return non-zero status(1).

ERRORS:
add mysqlclient failed:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 185, in install_candidate
    self.manager.install(can)
  File "/usr/local/python3/lib/python3.8/site-packages/pdm/installers/manager.py", line 39, in install
    installer(prepared.build(), self.environment, prepared.direct_url())
  File "/usr/local/python3/lib/python3.8/site-packages/pdm/models/candidates.py", line 332, in build
    self.wheel = builder.build(build_dir, metadata_directory=self._metadata_dir)
  File "/usr/local/python3/lib/python3.8/site-packages/pdm/builders/wheel.py", line 26, in build
    requires = self._hook.get_requires_for_build_wheel(config_settings)
  File "/usr/local/python3/lib/python3.8/site-packages/pep517/wrappers.py", line 172, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "/usr/local/python3/lib/python3.8/site-packages/pep517/wrappers.py", line 322, in _call_hook
    self._subprocess_runner(
  File "/usr/local/python3/lib/python3.8/site-packages/pdm/builders/base.py", line 238, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
  File "/usr/local/python3/lib/python3.8/site-packages/pdm/builders/base.py", line 86, in log_subprocessor
    raise BuildError(
pdm.exceptions.BuildError: Call command ['/usr/local/python3/bin/python3.8', '/usr/local/python3/lib/python3.8/site-packages/pep517/in_process/_in_process.py', 'get_requires_for_build_wheel', '/tmp/tmp8wf92t4o'] return non-zero status(1).

Traceback (most recent call last):
  File "/usr/local/python3/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/usr/local/python3/lib/python3.8/site-packages/pdm/core.py", line 233, in main
    return Core().main(args)
  File "/usr/local/python3/lib/python3.8/site-packages/pdm/core.py", line 168, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/usr/local/python3/lib/python3.8/site-packages/pdm/core.py", line 163, in main
    f(options.project, options)
  File "/usr/local/python3/lib/python3.8/site-packages/pdm/cli/commands/add.py", line 53, in handle
    actions.do_add(
  File "/usr/local/python3/lib/python3.8/site-packages/pdm/cli/actions.py", line 245, in do_add
    do_sync(
  File "/usr/local/python3/lib/python3.8/site-packages/pdm/cli/actions.py", line 190, in do_sync
    handler.synchronize()
  File "/usr/local/python3/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 352, in synchronize
    raise InstallationError("Some package operations are not complete yet")
pdm.exceptions.InstallationError: Some package operations are not complete yet
```

**Comment by frostming** [comment]
This problem is not specific to PDM or mysqlclient, to compile a package that doesn't have a prebuilt wheel for the target system, all build requirements(headers and libs) should be met.

Closing this one, thank you.
