### ISSUE TITLE
macOS M1: `pdm run` results in `incompatible architecture (have 'arm64', need 'x86_64')`

### ISSUE THREAD

**Issue by Toreno96** [pdm-project/pdm#1030]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

I've installed PDM through `homebrew`:
```
brew info pdm
pdm: stable 1.14.0 (bottled), HEAD
Modern Python package manager with PEP 582 support
https://pdm.fming.dev
/opt/homebrew/Cellar/pdm/1.14.0 (1,772 files, 19.6MB) *
  Poured from bottle on 2022-04-09 at 15:16:41
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/pdm.rb
License: MIT
==> Dependencies
Required: python@3.10 ✔, six ✔
==> Options
--HEAD
        Install HEAD version
==> Caveats
Bash completion has been installed to:
  /opt/homebrew/etc/bash_completion.d
==> Analytics
install: 994 (30 days), 2,712 (90 days), 6,123 (365 days)
install-on-request: 991 (30 days), 2,708 (90 days), 6,120 (365 days)
build-error: 2 (30 days)
```
Now, for [this project](https://github.com/apptension/onetimepass/blob/7b220e0da0b4ed4432fa1f91856837fec6bf63d0/pyproject.toml), these commands

```shell
$ pdm sync
$ pdm -vv run otp
```
result in the error:
```shell
$ pdm -vv run otp
Traceback (most recent call last):
  File "/Users/dstasczak/development/projects/onetimepass/__pypackages__/3.10/bin/otp", line 5, in <module>
    from onetimepass.otp import otp
  File "/Users/dstasczak/development/projects/onetimepass/onetimepass/otp.py", line 13, in <module>
    import pydantic
ImportError: dlopen(/Users/dstasczak/development/projects/onetimepass/__pypackages__/3.10/lib/pydantic/__init__.cpython-310-darwin.so, 0x0002): tried: '/Users/dstasczak/development/projects/onetimepass/__pypackages__/3.10/lib/pydantic/__init__.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
```

While debugging, I found that:
```shell
$ pdm -vv run python -c 'import platform; print(platform.platform())'
macOS-10.16-x86_64-i386-64bit
```

While outside PDM I have:
```shell
$ uname -m
arm64
```

So it seems that PDM overrides the architecture or detects it incorrectly 🤔 

At the same time, if instead of PDM I use `setup.py`, it all works as expected:
```shell
$ python3.10 -m venv ven
$ . venv/bin/activate
$ pdm export -f setuppy >setup.py
$ pip install -e .
…
$ otp
Usage: otp [OPTIONS] COMMAND [ARGS]...
…
```

## Actual behavior

PDM detects invalid architecture on macOS M1, and then installs dependencies for this invalid architecture.

## Expected behavior

PDM detects correct architecture, installs all dependencies for the correct architecture, and then `pdm run otp` runs (pun unintended) successfully.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
$ pdm info && pdm info --env
PDM version:        1.14.0
Python Interpreter: /usr/local/Cellar/pdm/1.11.0/libexec/bin/python3.10 (3.10)
Project Root:       /Users/dstasczak/development/projects/onetimepass
Project Packages:   /Users/dstasczak/development/projects/onetimepass/__pypackages__/3.10
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.0",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "21.4.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000",
  "python_full_version": "3.10.0",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
`/usr/local/Cellar/pdm/1.11.0/libexec/bin/python3.10` is a x86_64 architecture python?

**Comment by frostming** [comment]
There seems to be an old installation of `pdm` at `/usr/local/Cellar/pdm/1.11.0`, can you remove it?

**Comment by Toreno96** [comment]
Oh, you're right. I've used [migration assistant](https://support.apple.com/en-us/HT204350) while moving stuff from the old MacBook to the new, M1 one; it probably moved also the old Python binary, and PDM was trying to use this one.

I've removed `.pdm.toml` and rerun `pdm sync`, and it all works now 🤦‍♂️ 

Thank you very much for your quick answer and help.
