### ISSUE TITLE
No module named 'pkg_resources' in third party library

### ISSUE THREAD

**Issue by SirMartin** [pdm-project/pdm#1045]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

I am trying to port a project running pip to pdm in my company, the problem is when I try to run some code it fails.

The fail is in an internal common library that uses [datadogs](https://www.datadoghq.com/) trace python library (https://github.com/DataDog/dd-trace-py/)

```bash
root@87fd607d4c7b:/code# pdm run -v mamba --format=documentation;
Traceback (most recent call last):
  File "/code/__pypackages__/3.9/bin/mamba", line 8, in <module>
    sys.exit(main())
  File "/code/__pypackages__/3.9/lib/mamba/cli.py", line 18, in main
    runner.run()
  File "/code/__pypackages__/3.9/lib/mamba/runners.py", line 29, in run
    modules = self.example_collector.modules()
  File "/code/__pypackages__/3.9/lib/mamba/example_collector.py", line 20, in modules
    with self._load_module_from(path) as module:
  File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/code/__pypackages__/3.9/lib/mamba/example_collector.py", line 52, in _load_module_from
    yield self._module_from_ast(name, path)
  File "/code/__pypackages__/3.9/lib/mamba/example_collector.py", line 70, in _module_from_ast
    exec(code, module.__dict__)
  File "spec/cli_spec.py", line 8, in <module>
    from minions.cli import main, run_service, OPERATION_FACTORIES
  File "/code/minions/cli.py", line 6, in <module>
    from common.logger import logger
  File "/code/__pypackages__/3.9/lib/common/logger.py", line 10, in <module>
    from ddtrace.helpers import get_correlation_ids
  File "/code/__pypackages__/3.9/lib/ddtrace/__init__.py", line 1, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

I read it in an old issue here, and I suppose that I don't have to change the backend, but I don't understand why is the issue. I don't have a lot of experience in python, but I cannot find more information

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
root@87fd607d4c7b:/code# pdm info
PDM version:        1.14.0
Python Interpreter: /usr/local/bin/python (3.9)
Project Root:       /code
Project Packages:   /code/__pypackages__/3.9
root@87fd607d4c7b:/code# pdm info --env
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.7",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.16.15-76051615-generic",
  "platform_system": "Linux",
  "platform_version": "#202203161444~1647964027~21.10~e706226 SMP PREEMPT Tue Mar 22 17",
  "python_full_version": "3.9.7",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}


```

**Comment by SirMartin** [comment]
Thanks a lot, that makes a lot of sense, and it works!
