### ISSUE TITLE
pdm.exceptions.InvalidPyVersion: Invalid Python interpreter for python 3.7.4

### ISSUE THREAD

**Issue by dev590t** [pdm-project/pdm#1065]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

Can't switch interpreter to python 3.7
## Steps to reproduce

```
$ pdm use /gnu/store/fq2wyi5v55gs1bslkxapr70kx76jw7wx-profile/bin/python3.7 -v
Traceback (most recent call last):
  File "/home/dev_1/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/dev_1/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/core.py", line 233, in main
    return Core().main(args)
  File "/home/dev_1/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/core.py", line 168, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/home/dev_1/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/core.py", line 163, in main
    f(options.project, options)
  File "/home/dev_1/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/cli/commands/use.py", line 29, in handle
    actions.do_use(
  File "/home/dev_1/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/cli/actions.py", line 580, in do_use
    found_interpreters = list(dict.fromkeys(project.find_interpreters(python)))
  File "/home/dev_1/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/project/core.py", line 617, in find_interpreters
    yield PythonInfo.from_path(python)
  File "/home/dev_1/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/models/python.py", line 27, in from_path
    raise InvalidPyVersion(f"Invalid Python interpreter: {path}")
pdm.exceptions.InvalidPyVersion: Invalid Python interpreter: /gnu/store/d7jmr2sd8lmlsghnnal13rn1i4c22xff-python-3.7.4/bin/python3.7
```
## Additional information
- Python interpreter valid
```
$ /gnu/store/d7jmr2sd8lmlsghnnal13rn1i4c22xff-python-3.7.4/bin/python3.7 -c "import platform; print(platform.python_version())"
3.7.4
```
- requires-python = ">=3.7" in pyproject.toml
## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.14.0
Python Interpreter: /home/dev_1/.local/share/pdm/venv/bin/python (3.8)
Project Root:       /mnt/linuxProgram/workspace/test_dir
Project Packages:   /mnt/linuxProgram/workspace/test_dir/__pypackages__/3.8

PDM 1.14.0 is installed, while 1.14.1 is available.
Please run $ /home/dev_1/.local/share/pdm/venv/bin/python -m pip install -U pdm to upgrade.
Run $ pdm config check_update false to disable the check.
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.2",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.9.3-gnu",
  "platform_system": "Linux",
  "platform_version": "#1 SMP 1",
  "python_full_version": "3.8.2",
  "platform_python_implementation": "CPython",
  "python_version": "3.8",
  "sys_platform": "linux"
}

PDM 1.14.0 is installed, while 1.14.1 is available.
Please run $ /home/dev_1/.local/share/pdm/venv/bin/python -m pip install -U pdm to upgrade.
Run $ pdm config check_update false to disable the check.
```

**Comment by dev590t** [comment]
I have update pdm into 1.14.1, that is a more detailled error message:
```
$ pdm use /gnu/store/fq2wyi5v55gs1bslkxapr70kx76jw7wx-profile/bin/python3.7 -vv
Traceback (most recent call last):
  File "/home/dev_1/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/dev_1/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/core.py", line 233, in main
    return Core().main(args)
  File "/home/dev_1/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/core.py", line 168, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/home/dev_1/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/core.py", line 163, in main
    f(options.project, options)
  File "/home/dev_1/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/cli/commands/use.py", line 29, in handle
    actions.do_use(
  File "/home/dev_1/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/cli/actions.py", line 601, in do_use
    matching_interperters = list(filter(version_matcher, found_interpreters))
  File "/home/dev_1/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/cli/actions.py", line 573, in version_matcher
    return project.python_requires.contains(str(py_version.version), True)
  File "/home/dev_1/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/models/python.py", line 48, in version
    return self._py_ver.version
  File "/home/dev_1/.local/share/pdm/venv/lib/python3.8/site-packages/findpython/python.py", line 62, in version
    self._version = self._get_version()
  File "/home/dev_1/.local/share/pdm/venv/lib/python3.8/site-packages/findpython/python.py", line 161, in _get_version
    version = self._run_script(script, timeout=GET_VERSION_TIMEOUT).strip()
  File "/home/dev_1/.local/share/pdm/venv/lib/python3.8/site-packages/findpython/python.py", line 177, in _run_script
    return subprocess.check_output(
  File "/home/dev_1/.guix-profile/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/dev_1/.guix-profile/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/gnu/store/d7jmr2sd8lmlsghnnal13rn1i4c22xff-python-3.7.4/bin/python3.7', '-c', 'import platform; print(platform.python_version())']' died with <Signals.SIGSEGV: 11>.
$ /gnu/store/d7jmr2sd8lmlsghnnal13rn1i4c22xff-python-3.7.4/bin/python3.7 -c 'import platform; print(platform.python_version())'
3.7.4
```

That is strange that the command fails when it is python that execute it, but success when I execute directly in shell

**Comment by dev590t** [comment]
The issue is from my LD_LIBRARY_PATH. problem solved
