### ISSUE TITLE
How do add private repository (gitlab) without putting keys in plaintext in pyproject.toml

### ISSUE THREAD

**Issue by cheog** [pdm-project/pdm#1077]
I work for a company that's trying to switch to pdm. We use gitlabs python repository. How do we add dependencies on packages within those repositories without having our tokens in plaintext in the pyproject.toml file? It seems like PDM follows poetrys lead in some ways. I was able to add my repo via putting the following in pyproject.toml

```
[[tool.pdm.source]]
name = "repo"
url = "https://gitlab.company.net/api/v4/groups/42/-/packages/pypi/simple"
verify_ssl = true
```

Then I used `pdm add -v whatever` and it allowed me to log in (username: `__token__`, password: `<gitlab token>`). However, it wasn't able to find the package. Furthermore, despite me allowing it to use my keychain, it asks me to put in my password again if I run the same command.

**Comment by cye18** [comment]
You can wrap your gitlab token in ${}, as described in the [document](https://pdm.fming.dev/usage/dependency/#environment-variables-expansion). Except that, it's just the same steps should you use pip

**Comment by cheog** [comment]
I went and double checked Gitlab and found that the url had been wrong. I also changed the pyproject to use environment variables like you suggested.
```
[[tool.pdm.source]]
name = "repo"
url = "https://__token__:${GITLAB_TOKEN}@gitlab.company.net/api/v4/projects/22/packages/pypi/simple"
verify_ssl = true
```
That fixed the verification problem. Thank you!
However, I'm still unable to install packages from the repo.
Here's the full output of `pdm add -v internal-package`

```
/opt/homebrew/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Adding packages to default dependencies: internal-package
======== Start resolving requirements ========
  black>=22.3.0
  pre-commit>=2.19.0
  pytest>=7.1.2
  pytest-sugar>=0.9.4
  pytest-mock>=3.7.0
  pytest-xdist>=2.5.0
  moto>=3.1.8
  networkx>=2.8
  numpy>=1.22.3
  pandas>=1.4.2
  pyspark>=3.2.1
  py4j>=0.10.9.3
  internal-package
  python>=3.8
  Adding requirement black>=22.3.0
	Found matching candidates:
	 <Candidate black 22.3.0 from https://pypi.org/simple/black/>
  Adding requirement pre-commit>=2.19.0
	Found matching candidates:
	 <Candidate pre-commit 2.19.0 from https://pypi.org/simple/pre-commit/>
  Adding requirement pytest>=7.1.2
	Found matching candidates:
	 <Candidate pytest 7.1.2 from https://pypi.org/simple/pytest/>
  Adding requirement pytest-sugar>=0.9.4
	Found matching candidates:
	 <Candidate pytest-sugar 0.9.4 from https://pypi.org/simple/pytest-sugar/>
  Adding requirement pytest-mock>=3.7.0
	Found matching candidates:
	 <Candidate pytest-mock 3.7.0 from https://pypi.org/simple/pytest-mock/>
  Adding requirement pytest-xdist>=2.5.0
	Found matching candidates:
	 <Candidate pytest-xdist 2.5.0 from https://pypi.org/simple/pytest-xdist/>
  Adding requirement moto>=3.1.8
	Found matching candidates:
	 <Candidate moto 3.1.8 from https://pypi.org/simple/moto/>
  Adding requirement networkx>=2.8
	Found matching candidates:
	 <Candidate networkx 2.8 from https://pypi.org/simple/networkx/>
  Adding requirement numpy>=1.22.3
	Found matching candidates:
	 <Candidate numpy 1.22.3 from https://pypi.org/simple/numpy/>
  Adding requirement pandas>=1.4.2
	Found matching candidates:
	 <Candidate pandas 1.4.2 from https://pypi.org/simple/pandas/>
  Adding requirement pyspark>=3.2.1
	Found matching candidates:
	 <Candidate pyspark 3.2.1 from https://pypi.org/simple/pyspark/>
  Adding requirement py4j>=0.10.9.3
	Found matching candidates:
	 <Candidate py4j 0.10.9.5 from https://pypi.org/simple/py4j/>
	 <Candidate py4j 0.10.9.4 from https://pypi.org/simple/py4j/>
	 <Candidate py4j 0.10.9.3 from https://pypi.org/simple/py4j/>
  Adding requirement internal-package
Traceback (most recent call last):
  File "/Users/me/Library/Python/3.10/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/Users/me/Library/Python/3.10/lib/python/site-packages/pdm/core.py", line 233, in main
    return Core().main(args)
  File "/Users/me/Library/Python/3.10/lib/python/site-packages/pdm/core.py", line 168, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/Users/me/Library/Python/3.10/lib/python/site-packages/pdm/core.py", line 163, in main
    f(options.project, options)
  File "/Users/me/Library/Python/3.10/lib/python/site-packages/pdm/cli/commands/add.py", line 53, in handle
    actions.do_add(
  File "/Users/me/Library/Python/3.10/lib/python/site-packages/pdm/cli/actions.py", line 256, in do_add
    resolved = do_lock(project, strategy, tracked_names, reqs, dry_run=dry_run)
  File "/Users/me/Library/Python/3.10/lib/python/site-packages/pdm/cli/actions.py", line 95, in do_lock
    mapping, dependencies = resolve(
  File "/Users/me/Library/Python/3.10/lib/python/site-packages/pdm/resolver/core.py", line 31, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "/Users/me/Library/Python/3.10/lib/python/site-packages/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/Users/me/Library/Python/3.10/lib/python/site-packages/resolvelib/resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/Users/me/Library/Python/3.10/lib/python/site-packages/resolvelib/resolvers.py", line 168, in _add_to_criteria
    candidates=build_iter_view(matches),
  File "/Users/me/Library/Python/3.10/lib/python/site-packages/resolvelib/structs.py", line 164, in build_iter_view
    matches = list(matches)
  File "/Users/me/Library/Python/3.10/lib/python/site-packages/pdm/resolver/providers.py", line 237, in find_matches
    yield from super().find_matches(identifier, requirements, incompatibilities)
  File "/Users/me/Library/Python/3.10/lib/python/site-packages/pdm/resolver/providers.py", line 145, in find_matches
    candidates = self._find_candidates(reqs[0])
  File "/Users/me/Library/Python/3.10/lib/python/site-packages/pdm/resolver/providers.py", line 128, in _find_candidates
    return self.repository.find_candidates(
  File "/Users/me/Library/Python/3.10/lib/python/site-packages/pdm/models/repositories.py", line 106, in find_candidates
    self._find_candidates(requirement),
  File "/Users/me/Library/Python/3.10/lib/python/site-packages/pdm/models/repositories.py", line 295, in _find_candidates
    raise CandidateNotFound(
pdm.exceptions.CandidateNotFound: Unable to find candidates for internal-package. There may exist some issues with the package name or network condition.
```

**Comment by cheog** [comment]
Yes. Thanks for taking the time to help by the way.

**Comment by cheog** [comment]
Okay I finally solved it. I didn't have the right permissions on the token. Turns out, despite the fact that I was reading from a private registry, I needed `read_api` permissions. Even giving `read_registry` + `read_repository` + `read_user` permissions still gave me errors. Thanks for helping :)
