### ISSUE TITLE
python 3.11

### ISSUE THREAD

**Issue by mybigman** [pdm-project/pdm#1086]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

```fish
> pdm add fastapi -v
Adding packages to default dependencies: fastapi
Traceback (most recent call last):
  File "/home/champ/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/champ/.local/share/pdm/venv/lib64/python3.10/site-packages/pdm/core.py", line 233, in main
    return Core().main(args)
  File "/home/champ/.local/share/pdm/venv/lib64/python3.10/site-packages/pdm/core.py", line 168, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/home/champ/.local/share/pdm/venv/lib64/python3.10/site-packages/pdm/core.py", line 163, in main
    f(options.project, options)
  File "/home/champ/.local/share/pdm/venv/lib64/python3.10/site-packages/pdm/cli/commands/add.py", line 53, in handle
    actions.do_add(
  File "/home/champ/.local/share/pdm/venv/lib64/python3.10/site-packages/pdm/cli/actions.py", line 256, in do_add
    resolved = do_lock(project, strategy, tracked_names, reqs, dry_run=dry_run)
  File "/home/champ/.local/share/pdm/venv/lib64/python3.10/site-packages/pdm/cli/actions.py", line 80, in do_lock
    provider = project.get_provider(strategy, tracked_names)
  File "/home/champ/.local/share/pdm/venv/lib64/python3.10/site-packages/pdm/project/core.py", line 383, in get_provider
    repository = self.get_repository(cls=self.core.repository_class)
  File "/home/champ/.local/share/pdm/venv/lib64/python3.10/site-packages/pdm/project/core.py", line 350, in get_repository
    return cls(sources, self.environment)
  File "/home/champ/.local/share/pdm/venv/lib64/python3.10/site-packages/pdm/project/core.py", line 243, in environment
    self._environment = self.get_environment()
  File "/home/champ/.local/share/pdm/venv/lib64/python3.10/site-packages/pdm/project/core.py", line 238, in get_environment
    return Environment(self)
  File "/home/champ/.local/share/pdm/venv/lib64/python3.10/site-packages/pdm/models/environment.py", line 76, in __init__
    self.interpreter = project.python
  File "/home/champ/.local/share/pdm/venv/lib64/python3.10/site-packages/pdm/project/core.py", line 172, in python
    self._python = self.resolve_interpreter()
  File "/home/champ/.local/share/pdm/venv/lib64/python3.10/site-packages/pdm/project/core.py", line 219, in resolve_interpreter
    raise NoPythonVersion(
pdm.exceptions.NoPythonVersion: No Python that satisfies >=3.11 is found on the system.
```

## Steps to reproduce
```fish
> pdm init
Creating a pyproject.toml for PDM...
Please enter the Python interpreter to use
0. /usr/bin/python3.11 (3.11)
1. /usr/bin/python3.10 (3.10)
2. /home/champ/.local/share/pdm/venv/bin/python (3.10)
Please select: [0]: 0
Using Python interpreter: /usr/bin/python3.11 (3.11)
Is the project a library that will be uploaded to PyPI? [y/N]:
License(SPDX name) [MIT]:
Author name []:
Author email []:
Python requires('*' to allow any) [>=3.11]:
Changes are written to pyproject.toml.
```

## Actual behavior

Package fails to install

## Expected behavior

To install package

## Environment Information

```fish
# Paste the output of `pdm info && pdm info --env` below:
> pdm info && pdm info --env
[NoPythonVersion]: No Python that satisfies >=3.11 is found on the system.
Add '-v' to see the detailed traceback
```

**Comment by frostming** [comment]
Try using the absolute path to python 3.11 since you are using a prerelease

**Comment by mybigman** [comment]
@frostming  - Sorry, where am I specifying the path?

**Comment by frostming** [comment]
`pdm use <path_to_python>`

**Comment by mybigman** [comment]
that works... thanks.
