### ISSUE TITLE
--editable fails to add dep

### ISSUE THREAD

**Issue by drewp** [pdm-project/pdm#1090]
Maybe something's wrong with my dep, but this error is no good:

```
I inserted this into pdb/builders/editable.py for more logging:

            print(f'{type(self._hook)=} {dir(self._hook)=}')

✨ dash(pts/3):~/projects/light9% pdm add -v -e ../../../../../my/proj/rdfdb 
Adding packages to default dependencies: -e file:///my/proj/rdfdb#egg=rdfdb
...
  Adding requirement -e file:///my/proj/rdfdb#egg=rdfdb
Preparing isolated env for PEP 517 build...
Collecting pdm-pep517>=0.12.0
  Using cached pdm_pep517-0.12.5-py3-none-any.whl (303 kB)
Installing collected packages: pdm-pep517
Successfully installed pdm-pep517-0.12.5
type(self._hook)=<class 'pep517.wrappers.Pep517HookCaller'> dir(self._hook)=['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_call_hook', '_subprocess_runner', 'backend_path', 'build_backend', 'build_sdist', 'build_wheel', 'get_requires_for_build_sdist', 'get_requires_for_build_wheel', 'prepare_metadata_for_build_wheel', 'python_executable', 'source_dir', 'subprocess_runner']
Traceback (most recent call last):
  File "/home/drewp/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/drewp/.local/lib/python3.9/site-packages/pdm/core.py", line 232, in main
    return Core().main(args)
  File "/home/drewp/.local/lib/python3.9/site-packages/pdm/core.py", line 167, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/home/drewp/.local/lib/python3.9/site-packages/pdm/core.py", line 162, in main
    f(options.project, options)
  File "/home/drewp/.local/lib/python3.9/site-packages/pdm/cli/commands/add.py", line 55, in handle
    actions.do_add(
  File "/home/drewp/.local/lib/python3.9/site-packages/pdm/cli/actions.py", line 256, in do_add
    resolved = do_lock(project, strategy, tracked_names, reqs, dry_run=dry_run)
  File "/home/drewp/.local/lib/python3.9/site-packages/pdm/cli/actions.py", line 95, in do_lock
    mapping, dependencies = resolve(
  File "/home/drewp/.local/lib/python3.9/site-packages/pdm/resolver/core.py", line 31, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "/home/drewp/.local/lib/python3.9/site-packages/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/drewp/.local/lib/python3.9/site-packages/resolvelib/resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/home/drewp/.local/lib/python3.9/site-packages/resolvelib/resolvers.py", line 168, in _add_to_criteria
    candidates=build_iter_view(matches),
  File "/home/drewp/.local/lib/python3.9/site-packages/resolvelib/structs.py", line 164, in build_iter_view
    matches = list(matches)
  File "/home/drewp/.local/lib/python3.9/site-packages/pdm/resolver/providers.py", line 237, in find_matches
    yield from super().find_matches(identifier, requirements, incompatibilities)
  File "/home/drewp/.local/lib/python3.9/site-packages/pdm/resolver/providers.py", line 145, in find_matches
    candidates = self._find_candidates(reqs[0])
  File "/home/drewp/.local/lib/python3.9/site-packages/pdm/resolver/providers.py", line 125, in _find_candidates
    can.prepare(self.repository.environment).prepare_metadata()
  File "/home/drewp/.local/lib/python3.9/site-packages/pdm/models/candidates.py", line 397, in prepare_metadata
    self._metadata_dir = builder(
  File "/home/drewp/.local/lib/python3.9/site-packages/pdm/builders/editable.py", line 34, in prepare_metadata
    requires = self._hook.get_requires_for_build_editable(config_settings)
AttributeError: 'Pep517HookCaller' object has no attribute 'get_requires_for_build_editable'
```
This dep adds fine without the `-e`:

```
pdm add -v  ../../../../../my/proj/rdfdb
...

🎉 All complete!


✨ dash(pts/3):~/projects/light9% grep rdfdb pyproject.toml 
    "rdfdb @ file:///my/proj/rdfdb",
✨ dash(pts/3):~/projects/light9% grep rdfdb pdm.lock      
name = "rdfdb"
path = "../../../../../my/proj/rdfdb"
✨ dash(pts/3):~/projects/light9% grep -C10 rdfdb pdm.lock 
[[package]]
name = "rdfdb"
version = "0.22.0"
requires_python = ">=3.9"
path = "../../../../../my/proj/rdfdb"
summary = "UNKNOWN"
dependencies = [
    "asyncinotify>=2.0.2",
    "autobahn",
    "prometheus-client>=0.13.1",
    "rdflib",
    "starlette-exporter>=0.12.0",
]
```

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:

✨ dash(pts/4):~/projects/light9% pdm info
PDM version:        1.15.0
Python Interpreter: /usr/bin/python3.9 (3.9)
Project Root:       /home/drewp/own/proj/light9
Project Packages:   /home/drewp/own/proj/light9/__pypackages__/3.9
✨ dash(pts/4):~/projects/light9% pdm info --env
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.9",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.13.0-41-generic",
  "platform_system": "Linux",
  "platform_version": "#46-Ubuntu SMP Thu Apr 14 20:06:04 UTC 2022",
  "python_full_version": "3.9.9",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
The API was added to `pep517` in `0.11.0` and PDM's dependency specifies `pep517 >= 0.11.0`, but you seems to have an older version of that package installed.

**Comment by drewp** [comment]
Ew, I thought I was ok:
```
✨ dash(pts/7):~/projects/light9% pip list
Package                 Version
----------------------- -------------------------------
...
pdm                     1.15.0
pdm-bump                0.4.0
pdm-pep517              0.12.5
pep440-version-utils    0.3.0
pep517                  0.12.0
```
but pdm picks up a different copy:
```
✨ dash(pts/7):~/projects/light9% cat ~/.local/bin/pdm
#!/usr/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
from pdm.core import main

import pep517
print(f'{__file__=} {pep517.__file__=} {pep517.__version__=}')

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())

✨ dash(pts/7):~/projects/light9% pdm -V              
__file__='/home/drewp/.local/bin/pdm' pep517.__file__='/usr/share/python-wheels/pep517-0.9.1-py2.py3-none-any.whl/pep517/__init__.py' pep517.__version__='0.9.1'
Python Development Master (PDM), version 1.15.0
```

I don't know why the load priorities were like that, but I see what to fix. I leave this message here mostly as search bait in case this happens to other people.

**Comment by frostming** [comment]
Oh, you must be using the debian system pip inside PDM, which changes the package search path and those bundled wheels always take precedence.

Try an isolated installation method. If you have installed pdm into the user site. Try reinstalling pip:

```
pip install --user -I pip
```
That's why I recommend isolated installation.
