### ISSUE TITLE
Support using setup.py to install editable package whose metadata contains non-ASCII characters on Windows

### ISSUE THREAD

**Issue by FossenWang** [pdm-project/pdm#1102]
## Is your feature request related to a problem? Please describe.
This issue only happens on Windows.

When install editable package whose metadata contains non-ASCII characters on Windows, the installation will fail.

Example:
info
```
PS C:\Projects\Fossen\test-pdm\main-package> pdm info
PDM version:        1.15.0
Python Interpreter: C:\Program Files\Python310\python.exe (3.10)
Project Root:       C:/Projects/Fossen/test-pdm/main-package
Project Packages:   C:\Projects\Fossen\test-pdm\main-package\__pypackages__\3.10
```
structure
```
test-pdm
  - editable-package
    - hello
      - __init__.py
    - setup.py
  - main-package
    - __pypackages__
    - .pdm.toml
    - pdm.lock
    - pyproject.toml
```
hello/\_\_init\_\_.py
```
print('hello')
```
setup.py
where contains non-ASCII characters in description field
```
from setuptools import setup
setup(
    name='hello',
    version='0.1.0',
    description='非ASCII字符 non-ASCII characters',
    packages=['hello'],
    install_requires=[],
    python_requires=">=3.10",
)
```
pyproject.toml
```
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "", email = ""},
]
dependencies = [
    "-e file:///C:/Projects/Fossen/test-pdm/editable-package#egg=hello",
]
requires-python = ">=3.10"
license = {text = ""}

[tool.pdm]

[build-system]
requires = ["pdm-pep517>=0.12.0"]
build-backend = "pdm.pep517.api"
```
install
`$env:PYTHONUTF8=0` ensure not using utf-8 by default.
```
PS C:\Projects\Fossen\test-pdm\main-package> $env:PYTHONUTF8=0
PS C:\Projects\Fossen\test-pdm\main-package> pdm install        
Synchronizing working set with lock file: 1 to add, 0 to update, 0 to remove

Install hello 0.1.0 failed
  See C:\Users\fosse\AppData\Local\Temp\pdm-install-p5lhfwa8.log for detailed debug log.
  [BuildError]: Call command ['C:/Program Files/Python310/python.exe', 'C:\\Users\\fosse\\.local\\pipx\\venvs\\pdm\\lib\\site-packages\\pep517\\in_process\\_in_process.py', 'build_editable', 'C:\\Users\\fosse\\AppData\\Local\\Temp\\tmpufj_c1xd'] return non-zero status(1).
  Add '-v' to see the detailed traceback
```
log
```
Preparing isolated env for PEP 517 build...
Reusing shared build env: C:\Users\fosse\AppData\Local\Temp\pdm-build-env-l7bwuibl-shared
Building wheel for file:///C:/Projects/Fossen/test-pdm/editable-package#egg=hello
running editable_wheel
running dist_info
creating C:\Users\fosse\AppData\Local\Temp\pdm-wheel-epk38jkt\tmp1g5xaw1n\hello.egg-info
writing C:\Users\fosse\AppData\Local\Temp\pdm-wheel-epk38jkt\tmp1g5xaw1n\hello.egg-info\PKG-INFO
writing dependency_links to C:\Users\fosse\AppData\Local\Temp\pdm-wheel-epk38jkt\tmp1g5xaw1n\hello.egg-info\dependency_links.txt
writing top-level names to C:\Users\fosse\AppData\Local\Temp\pdm-wheel-epk38jkt\tmp1g5xaw1n\hello.egg-info\top_level.txt
writing manifest file 'C:\Users\fosse\AppData\Local\Temp\pdm-wheel-epk38jkt\tmp1g5xaw1n\hello.egg-info\SOURCES.txt'
reading manifest file 'C:\Users\fosse\AppData\Local\Temp\pdm-wheel-epk38jkt\tmp1g5xaw1n\hello.egg-info\SOURCES.txt'
writing manifest file 'C:\Users\fosse\AppData\Local\Temp\pdm-wheel-epk38jkt\tmp1g5xaw1n\hello.egg-info\SOURCES.txt'
creating 'C:\Users\fosse\AppData\Local\Temp\pdm-wheel-epk38jkt\tmp1g5xaw1n\hello.dist-info'
running build_ext
Traceback (most recent call last):
  File "C:\Users\fosse\.local\pipx\venvs\pdm\lib\site-packages\pep517\in_process\_in_process.py", line 364, in <module>
    main()
  File "C:\Users\fosse\.local\pipx\venvs\pdm\lib\site-packages\pep517\in_process\_in_process.py", line 346, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "C:\Users\fosse\.local\pipx\venvs\pdm\lib\site-packages\pep517\in_process\_in_process.py", line 284, in build_editable
    return hook(wheel_directory, config_settings, metadata_directory)
  File "C:\Users\fosse\AppData\Local\Temp\pdm-build-env-l7bwuibl-shared\Lib\site-packages\setuptools_pep660\__init__.py", line 11, in build_editable
    return setuptools.build_meta._BACKEND._build_with_temp_dir(
  File "C:\Users\fosse\AppData\Local\Temp\pdm-build-env-l7bwuibl-shared\Lib\site-packages\setuptools\build_meta.py", line 229, in _build_with_temp_dir
    self.run_setup()
  File "C:\Users\fosse\AppData\Local\Temp\pdm-build-env-l7bwuibl-shared\Lib\site-packages\setuptools\build_meta.py", line 174, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 4, in <module>
    setup(
  File "C:\Users\fosse\AppData\Local\Temp\pdm-build-env-l7bwuibl-shared\Lib\site-packages\setuptools\__init__.py", line 155, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\fosse\AppData\Local\Temp\pdm-build-env-l7bwuibl-shared\Lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
    return run_commands(dist)
  File "C:\Users\fosse\AppData\Local\Temp\pdm-build-env-l7bwuibl-shared\Lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
    dist.run_commands()
  File "C:\Users\fosse\AppData\Local\Temp\pdm-build-env-l7bwuibl-shared\Lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "C:\Users\fosse\AppData\Local\Temp\pdm-build-env-l7bwuibl-shared\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
    cmd_obj.run()
  File "C:\Users\fosse\AppData\Local\Temp\pdm-build-env-l7bwuibl-shared\Lib\site-packages\setuptools_pep660\editable_wheel.py", line 34, in run
    self.build_editable_wheel()
  File "C:\Users\fosse\AppData\Local\Temp\pdm-build-env-l7bwuibl-shared\Lib\site-packages\setuptools_pep660\editable_wheel.py", line 109, in build_editable_wheel
    metadata.read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0xac in position 70: illegal multibyte sequence
Error occurs
Traceback (most recent call last):
  File "C:\Users\fosse\.local\pipx\venvs\pdm\lib\site-packages\pdm\termui.py", line 200, in logging
    yield logger
  File "C:\Users\fosse\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\synchronizers.py", line 356, in synchronize
    handlers[kind](key)
  File "C:\Users\fosse\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\synchronizers.py", line 207, in install_candidate
    self.manager.install(can)
  File "C:\Users\fosse\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\manager.py", line 39, in install
    installer(prepared.build(), self.environment, prepared.direct_url())
  File "C:\Users\fosse\.local\pipx\venvs\pdm\lib\site-packages\pdm\models\candidates.py", line 331, in build
    self.wheel = builder.build(build_dir, metadata_directory=self._metadata_dir)
  File "C:\Users\fosse\.local\pipx\venvs\pdm\lib\site-packages\pdm\builders\editable.py", line 60, in build
    filename = self._hook.build_editable(
  File "C:\Users\fosse\.local\pipx\venvs\pdm\lib\site-packages\pep517\wrappers.py", line 261, in build_editable
    return self._call_hook('build_editable', {
  File "C:\Users\fosse\.local\pipx\venvs\pdm\lib\site-packages\pep517\wrappers.py", line 322, in _call_hook
    self._subprocess_runner(
  File "C:\Users\fosse\.local\pipx\venvs\pdm\lib\site-packages\pdm\builders\base.py", line 239, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
  File "C:\Users\fosse\.local\pipx\venvs\pdm\lib\site-packages\pdm\builders\base.py", line 87, in log_subprocessor
    raise BuildError(
pdm.exceptions.BuildError: Call command ['C:/Program Files/Python310/python.exe', 'C:\\Users\\fosse\\.local\\pipx\\venvs\\pdm\\lib\\site-packages\\pep517\\in_process\\_in_process.py', 'build_editable', 'C:\\Users\\fosse\\AppData\\Local\\Temp\\tmpufj_c1xd'] return non-zero status(1).
```

## Explanation
After I read the source code, I find that this maybe not a bug of pdm, it's setuptools_pep660.
(Should I create issue at setuptools_pep660 rather than pdm? But setuptools_pep660 sims like inactive.)
The primary cause is that Windows uses legacy encoding (e.g. cp1252, cp932, etc...) as system encoding.
This article explain in detail: [Python: Use the UTF-8 mode on Windows!](https://dev.to/methane/python-use-utf-8-mode-on-windows-212i)

setuptools_pep660 will raise error when reading metadata file contains non-ASCII characters with wrong default encoding cp936, not utf-8.

default encoding
```
PS C:\Projects\Fossen\test-pdm\main-package> python -c 'import locale; print(locale.getpreferredencoding())'
cp936
```
code raised error
```
setuptools_pep660\editable_wheel.py", line 109, in build_editable_wheel
    metadata.read(),
```

## Describe the solution you'd like

In Python >= 3.7, simply set env variable `$env:PYTHONUTF8=1` to enable utf-8 mode.

But in Python <= 3.6, there is no such an elegant way, i only found an unpretty solution:
Put a `.pth` file in any folds in `sys.path`, for example
venv/Lib/site-packages/_default_encoding.pth
```
import _locale; _locale._getdefaultlocale = (lambda *args: ['en_US', 'utf-8'])
```
Obviously, this is not a good solution for everyone.

Dose anybody have a good solution?

**Comment by frostming** [comment]
Fixed by https://github.com/frostming/setuptools_pep660/releases/tag/0.1.4
