### ISSUE TITLE
Unable to install pyqt

### ISSUE THREAD

**Issue by Ch1enC** [pdm-project/pdm#1113]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

```
# .pdm.toml

[python]
path = "C:\\Users\\bc0f6\\.pyenv\\pyenv-win\\shims\\python.bat"
```

```
# pyproject.toml

[project]
...
dependencies = []
requires-python = ">=3.10"
license = {text = "MIT"}

[tool.pdm]

[build-system]
requires = ["pdm-pep517>=0.12.0"]
build-backend = "pdm.pep517.api"
```
```bash
$ pdm add pyqt6-qt6 -v
```

## Actual behavior

While installing pyqt6, everything works fine except the installing of pyqt6-qt6 always fail.
Similar failure also happens when trying to install pyqt5. In that case, pyqt5-qt5 will fail to install.

```bash
Adding packages to default dependencies: pyqt6-qt6
======== Start resolving requirements ========
  pyqt6-qt6
  python>=3.10
  Adding requirement pyqt6-qt6
        Found matching candidates:
          <Candidate pyqt6-qt6 6.3.0 from https://pypi.org/simple/pyqt6-qt6/>
          <Candidate pyqt6-qt6 6.2.4 from https://pypi.org/simple/pyqt6-qt6/>
          <Candidate pyqt6-qt6 6.2.3 from https://pypi.org/simple/pyqt6-qt6/>
          <Candidate pyqt6-qt6 6.2.2 from https://pypi.org/simple/pyqt6-qt6/>
          <Candidate pyqt6-qt6 6.2.1 from https://pypi.org/simple/pyqt6-qt6/>
          <Candidate pyqt6-qt6 6.2.0 from https://pypi.org/simple/pyqt6-qt6/>
          <Candidate pyqt6-qt6 6.1.3 from https://pypi.org/simple/pyqt6-qt6/>
          <Candidate pyqt6-qt6 6.1.2 from https://pypi.org/simple/pyqt6-qt6/>
          <Candidate pyqt6-qt6 6.1.1 from https://pypi.org/simple/pyqt6-qt6/>
          <Candidate pyqt6-qt6 6.1.0 from https://pypi.org/simple/pyqt6-qt6/>
          ... [29 more candidate(s)]
  Adding requirement python>=3.10
======== Starting round 0 ========
Resolving: new pin python >=3.10
======== Ending round 0 ========
======== Starting round 1 ========
Resolving: new pin pyqt6-qt6 6.3.0
======== Ending round 1 ========
======== Starting round 2 ========
======== Resolution Result ========
Stable pins:
     python None
  pyqt6-qt6 6.3.0
        Found matching candidates:
          <Candidate pyqt6-qt6 6.3.0 from https://pypi.org/simple/pyqt6-qt6/>
🔒 Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
Synchronizing working set with lock file: 1 to add, 0 to update, 0 to remove

Install pyqt6-qt6 6.3.0 failed
Error occurs:
Traceback (most recent call last):
  File "C:\Users\bc0f6\.pyenv\pyenv-win\versions\3.10.4\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\bc0f6\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\synchronizers.py", line 207, in install_candidate
    self.manager.install(can)
  File "C:\Users\bc0f6\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\manager.py", line 39, in install
    installer(prepared.build(), self.environment, prepared.direct_url())
  File "C:\Users\bc0f6\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\installers.py", line 185, in install_wheel
    _install_wheel(
  File "C:\Users\bc0f6\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\installers.py", line 279, in _install_wheel
    install(source, destination, additional_metadata=additional_metadata or {})
  File "C:\Users\bc0f6\.local\pipx\venvs\pdm\lib\site-packages\installer\_core.py", line 96, in install
    for record_elements, stream, is_executable in source.get_contents():
  File "C:\Users\bc0f6\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\installers.py", line 131, in get_contents
    for element in super().get_contents():
  File "C:\Users\bc0f6\.local\pipx\venvs\pdm\lib\site-packages\installer\sources.py", line 158, in get_contents
    assert record is not None, "In {}, {} is not mentioned in RECORD".format(
AssertionError: In C:\Users\bc0f6\AppData\Local\Temp\pip-unpack-auaq74q1\PyQt6_Qt6-6.3.0-py3-none-win_amd64.whl, PyQt6_Qt6-6.3.0.dist-info/RECORD is not mentioned in RECORD
  Retry failed jobs
Install pyqt6-qt6 6.3.0 failed
Error occurs:
Traceback (most recent call last):
  File "C:\Users\bc0f6\.pyenv\pyenv-win\versions\3.10.4\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\bc0f6\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\synchronizers.py", line 207, in install_candidate
    self.manager.install(can)
  File "C:\Users\bc0f6\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\manager.py", line 39, in install
    installer(prepared.build(), self.environment, prepared.direct_url())
  File "C:\Users\bc0f6\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\installers.py", line 185, in install_wheel
    _install_wheel(
  File "C:\Users\bc0f6\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\installers.py", line 279, in _install_wheel
    install(source, destination, additional_metadata=additional_metadata or {})
  File "C:\Users\bc0f6\.local\pipx\venvs\pdm\lib\site-packages\installer\_core.py", line 96, in install
    for record_elements, stream, is_executable in source.get_contents():
  File "C:\Users\bc0f6\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\installers.py", line 131, in get_contents
    for element in super().get_contents():
  File "C:\Users\bc0f6\.local\pipx\venvs\pdm\lib\site-packages\installer\sources.py", line 158, in get_contents
    assert record is not None, "In {}, {} is not mentioned in RECORD".format(
AssertionError: In C:\Users\bc0f6\AppData\Local\Temp\pip-unpack-auaq74q1\PyQt6_Qt6-6.3.0-py3-none-win_amd64.whl, PyQt6_Qt6-6.3.0.dist-info/RECORD is not mentioned in RECORD

ERRORS:
add pyqt6-qt6 failed:
Traceback (most recent call last):
  File "C:\Users\bc0f6\.pyenv\pyenv-win\versions\3.10.4\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\bc0f6\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\synchronizers.py", line 207, in install_candidate
    self.manager.install(can)
  File "C:\Users\bc0f6\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\manager.py", line 39, in install
    installer(prepared.build(), self.environment, prepared.direct_url())
  File "C:\Users\bc0f6\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\installers.py", line 185, in install_wheel
    _install_wheel(
  File "C:\Users\bc0f6\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\installers.py", line 279, in _install_wheel
    install(source, destination, additional_metadata=additional_metadata or {})
  File "C:\Users\bc0f6\.local\pipx\venvs\pdm\lib\site-packages\installer\_core.py", line 96, in install
    for record_elements, stream, is_executable in source.get_contents():
  File "C:\Users\bc0f6\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\installers.py", line 131, in get_contents
    for element in super().get_contents():
  File "C:\Users\bc0f6\.local\pipx\venvs\pdm\lib\site-packages\installer\sources.py", line 158, in get_contents
    assert record is not None, "In {}, {} is not mentioned in RECORD".format(
AssertionError: In C:\Users\bc0f6\AppData\Local\Temp\pip-unpack-auaq74q1\PyQt6_Qt6-6.3.0-py3-none-win_amd64.whl, PyQt6_Qt6-6.3.0.dist-info/RECORD is not mentioned in RECORD

Traceback (most recent call last):
  File "C:\Users\bc0f6\.pyenv\pyenv-win\versions\3.10.4\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\bc0f6\.pyenv\pyenv-win\versions\3.10.4\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\users\bc0f6\.local\bin\pdm.exe\__main__.py", line 7, in <module>
  File "C:\Users\bc0f6\.local\pipx\venvs\pdm\lib\site-packages\pdm\core.py", line 232, in main
    return Core().main(args)
  File "C:\Users\bc0f6\.local\pipx\venvs\pdm\lib\site-packages\pdm\core.py", line 167, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "C:\Users\bc0f6\.local\pipx\venvs\pdm\lib\site-packages\pdm\core.py", line 162, in main
    f(options.project, options)
  File "C:\Users\bc0f6\.local\pipx\venvs\pdm\lib\site-packages\pdm\cli\commands\add.py", line 55, in handle
    actions.do_add(
  File "C:\Users\bc0f6\.local\pipx\venvs\pdm\lib\site-packages\pdm\cli\actions.py", line 268, in do_add
    do_sync(
  File "C:\Users\bc0f6\.local\pipx\venvs\pdm\lib\site-packages\pdm\cli\actions.py", line 209, in do_sync
    handler.synchronize()
  File "C:\Users\bc0f6\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\synchronizers.py", line 374, in synchronize
    raise InstallationError("Some package operations are not complete yet")
pdm.exceptions.InstallationError: Some package operations are not complete yet
```

## Expected behavior

pyqt6-qt6 should be installed properly.

## Environment Information

```bash
PDM version:        1.15.1
Python Interpreter: C:\Users\bc0f6\.pyenv\pyenv-win\versions\3.10.4\python.exe (3.10)
Project Root:       E:/Codes/Python/test
Project Packages:   E:\Codes\Python\test\__pypackages__\3.10
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.4",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.22000",
  "python_full_version": "3.10.4",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "win32"
}
```

**Comment by Ch1enC** [comment]
I'm not very familiar with python, but could it be caused by the wired backslash I just found in the RECORD file in the Windows version of pyqt6-qt6 wheel?

```
...
PyQt6_Qt6-6.3.0.dist-info/LICENSE,sha256=IATuPvgoKoX329A136z2PPA9VpU3vAhlX_6xQOo2ccU,44738
PyQt6_Qt6-6.3.0.dist-info/METADATA,sha256=BsMXWXI9sZtPt1ajhgLZ4CbA2lLcASc1_D2k4-AYtXk,551
PyQt6_Qt6-6.3.0.dist-info/WHEEL,sha256=HvbHOnfIIFGyPVIOEbfOdnEmUOBRPrAzrHWhdC-8b8M,95
PyQt6_Qt6-6.3.0.dist-info\RECORD,,
```

**Comment by frostming** [comment]
> but could it be caused by this wired backslash I just found in the RECORD file in the Windows version of pyqt6-qt6 wheel

Absolutely, [PEP 376 explicitly states that](https://peps.python.org/pep-0376/#:~:text=Each%20record%20is,local%20platform%20separator)

> Each record is composed of three elements:
>
> - the file’s path
> - a ‘/’-separated path, relative to the base location, if the file is under the base location.
> - a ‘/’-separated path, relative to the base location, if the file is under the installation prefix AND if the base location is a subpath of the installation prefix.
> - an absolute path, using the local platform separator
