### ISSUE TITLE
Installation or building: TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by hacker-DOM** [pdm-project/pdm#1123]
Hi there,

thank you for this excellent tool!

For some reason I am running into the following error:

```
~.../project ✭ ᐅ pdm install -v
All packages are synced to date, nothing to do.

Installing the project as an editable package...
Preparing isolated env for PEP 517 build...
Install project 1.0.0 failed
Traceback (most recent call last):
  File "~/Library/Application Support/pdm/venv/lib/python3.8/site-packages/pdm/builders/base.py", line 172, in __init__
    spec = tomli.load(f)
  File ".../project/__pypackages__/3.8/lib/tomli/_parser.py", line 67, in load
    return loads(s, parse_float=parse_float)
  File ".../project/__pypackages__/3.8/lib/tomli/_parser.py", line 75, in loads
    src = s.replace("\r\n", "\n")
TypeError: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "~/.local/bin/pdm", line 10, in <module>
    sys.exit(main())
  File "~/Library/Application Support/pdm/venv/lib/python3.8/site-packages/pdm/core.py", line 232, in main
    return Core().main(args)
  File "~/Library/Application Support/pdm/venv/lib/python3.8/site-packages/pdm/core.py", line 167, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "~/Library/Application Support/pdm/venv/lib/python3.8/site-packages/pdm/core.py", line 162, in main
    f(options.project, options)
  File "~/Library/Application Support/pdm/venv/lib/python3.8/site-packages/pdm/cli/commands/install.py", line 50, in handle
    actions.do_sync(
  File "~/Library/Application Support/pdm/venv/lib/python3.8/site-packages/pdm/cli/actions.py", line 209, in do_sync
    handler.synchronize()
  File "~/Library/Application Support/pdm/venv/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 389, in synchronize
    self.install_candidate(self_key)
  File "~/Library/Application Support/pdm/venv/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 207, in install_candidate
    self.manager.install(can)
  File "~/Library/Application Support/pdm/venv/lib/python3.8/site-packages/pdm/installers/manager.py", line 39, in install
    installer(prepared.build(), self.environment, prepared.direct_url())
  File "~/Library/Application Support/pdm/venv/lib/python3.8/site-packages/pdm/models/candidates.py", line 326, in build
    builder = builder_cls(self.ireq.unpacked_source_directory, self.environment)
  File "~/Library/Application Support/pdm/venv/lib/python3.8/site-packages/pdm/builders/editable.py", line 21, in __init__
    super().__init__(src_dir, environment)
  File "~/Library/Application Support/pdm/venv/lib/python3.8/site-packages/pdm/builders/base.py", line 176, in __init__
    raise BuildError(e) from e
pdm.exceptions.BuildError: a bytes-like object is required, not 'str'
```

## Environment Information

```
PDM version:        1.15.1
Python Interpreter: ~/.pyenv/versions/3.8.12/bin/python3 (3.8)
Project Root:       .../project
Project Packages:   .../project/__pypackages__/3.8
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.12",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "21.4.0",
  "platform_system": "Darwin",
  "platform_version": "...",
  "python_full_version": "3.8.12",
  "platform_python_implementation": "CPython",
  "python_version": "3.8",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
It is a TOML parsing error, can you paste the content of `pyproject.toml`? Or you can check it first yourself.
