### ISSUE TITLE
pdm add (ModuleNotFoundError: No module named 'setuptools')

### ISSUE THREAD

**Issue by vitidev** [pdm-project/pdm#1158]
- [✅  ] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

pdm init
pdm add moviepy

## Actual behavior
 
    $ pdm add moviepy -v
    Adding packages to default dependencies: moviepy
    ======== Start resolving requirements ========
      moviepy
      python>=3.10
      Adding requirement moviepy
            Found matching candidates:
              <Candidate moviepy 1.0.3 from https://pypi.org/simple/moviepy/>
              <Candidate moviepy 1.0.2 from https://pypi.org/simple/moviepy/>
              <Candidate moviepy 1.0.1 from https://pypi.org/simple/moviepy/>
              <Candidate moviepy 1.0.0 from https://pypi.org/simple/moviepy/>
              <Candidate moviepy 0.2.3.5 from https://pypi.org/simple/moviepy/>
              <Candidate moviepy 0.2.3.4 from https://pypi.org/simple/moviepy/>
              <Candidate moviepy 0.2.3.3 from https://pypi.org/simple/moviepy/>
              <Candidate moviepy 0.2.3.2 from https://pypi.org/simple/moviepy/>
              <Candidate moviepy 0.2.3.1 from https://pypi.org/simple/moviepy/>
              <Candidate moviepy 0.2.2.13 from https://pypi.org/simple/moviepy/>
              ... [72 more candidate(s)]
      Adding requirement python>=3.10
    ======== Starting round 0 ========
    Resolving: new pin python >=3.10
    Pinning: python None
    ======== Ending round 0 ========
    ======== Starting round 1 ========
    Preparing isolated env for PEP 517 build...
    Collecting wheel
      Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
    Collecting setuptools>=40.8.0
      Using cached setuptools-62.6.0-py3-none-any.whl (1.2 MB)
    Installing collected packages: wheel, setuptools
    Successfully installed setuptools-62.6.0 wheel-0.37.1
    Traceback (most recent call last):
      File "/home/user/.local/bin/pdm", line 8, in <module>
        sys.exit(main())
      File "/home/user/.local/lib/python3.10/site-packages/pdm/core.py", line 232, in main
        return Core().main(args)
      File "/home/user/.local/lib/python3.10/site-packages/pdm/core.py", line 167, in main
        raise cast(Exception, err).with_traceback(traceback)
      File "/home/user/.local/lib/python3.10/site-packages/pdm/core.py", line 162, in main
        f(options.project, options)
      File "/home/user/.local/lib/python3.10/site-packages/pdm/cli/commands/add.py", line 55, in handle
        actions.do_add(
      File "/home/user/.local/lib/python3.10/site-packages/pdm/cli/actions.py", line 256, in do_add
        resolved = do_lock(project, strategy, tracked_names, reqs, dry_run=dry_run)
      File "/home/user/.local/lib/python3.10/site-packages/pdm/cli/actions.py", line 95, in do_lock
        mapping, dependencies = resolve(
      File "/home/user/.local/lib/python3.10/site-packages/pdm/resolver/core.py", line 31, in resolve
        result = resolver.resolve(requirements, max_rounds)
      File "/home/user/.local/lib/python3.10/site-packages/resolvelib/resolvers.py", line 481, in resolve
        state = resolution.resolve(requirements, max_rounds=max_rounds)
      File "/home/user/.local/lib/python3.10/site-packages/resolvelib/resolvers.py", line 373, in resolve
        failure_causes = self._attempt_to_pin_criterion(name)
      File "/home/user/.local/lib/python3.10/site-packages/resolvelib/resolvers.py", line 213, in _attempt_to_pin_criterion
        criteria = self._get_updated_criteria(candidate)
      File "/home/user/.local/lib/python3.10/site-packages/resolvelib/resolvers.py", line 203, in _get_updated_criteria
        for requirement in self._p.get_dependencies(candidate=candidate):
      File "/home/user/.local/lib/python3.10/site-packages/pdm/resolver/providers.py", line 172, in get_dependencies
        deps, requires_python, _ = self.repository.get_dependencies(candidate)
      File "/home/user/.local/lib/python3.10/site-packages/pdm/models/repositories.py", line 70, in get_dependencies
        requirements, requires_python, summary = getter(candidate)
      File "/home/user/.local/lib/python3.10/site-packages/pdm/models/repositories.py", line 35, in wrapper
        result = func(self, candidate)
      File "/home/user/.local/lib/python3.10/site-packages/pdm/models/repositories.py", line 190, in _get_dependencies_from_metadata
        deps = prepared.get_dependencies_from_metadata()
      File "/home/user/.local/lib/python3.10/site-packages/pdm/models/candidates.py", line 427, in get_dependencies_from_metadata
        self.req.project_name, self.metadata.requires or [], extras  # type: ignore
      File "/home/user/.local/lib/python3.10/site-packages/pdm/models/candidates.py", line 420, in metadata
        self._metadata = self.prepare_metadata()
      File "/home/user/.local/lib/python3.10/site-packages/pdm/models/candidates.py", line 399, in prepare_metadata
        ).prepare_metadata(metadir_parent)
      File "/home/user/.local/lib/python3.10/site-packages/pdm/builders/wheel.py", line 14, in prepare_metadata
        requires = self._hook.get_requires_for_build_wheel(config_settings)
      File "/home/user/.local/lib/python3.10/site-packages/pep517/wrappers.py", line 172, in get_requires_for_build_wheel
        return self._call_hook('get_requires_for_build_wheel', {
      File "/home/user/.local/lib/python3.10/site-packages/pep517/wrappers.py", line 332, in _call_hook
        raise BackendUnavailable(data.get('traceback', ''))
    pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
      File "/home/user/.local/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 89, in _build_backend
        obj = import_module(mod_path)
      File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
      File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'setuptools'

## Expected behavior

package installed successfully

## Environment Information

Ubuntu 20.04

    $  pdm info && pdm info --env
    PDM version:        1.15.3
    Python Interpreter: /usr/bin/python3.10 (3.10)
    Project Root:       /home/user/t2
    Project Packages:   /home/user/t2/__pypackages__/3.10
    {
      "implementation_name": "cpython",
      "implementation_version": "3.10.5",
      "os_name": "posix",
      "platform_machine": "x86_64",
      "platform_release": "5.4.0-113-generic",
      "platform_system": "Linux",
      "platform_version": "#127-Ubuntu SMP Wed May 18 14:30:56 UTC 2022",
      "python_full_version": "3.10.5",
      "platform_python_implementation": "CPython",
      "python_version": "3.10",
      "sys_platform": "linux"
    }

This issue is related to [this one](https://github.com/pdm-project/pdm/issues/1014). But I do not understand how to install package.
I also tried like this

    [build-system]
    requires = [
        "wheel", "setuptools>=42,<61"
    ]
    build-backend = "setuptools_pep660"

with no success

**Comment by frostming** [comment]
More information is needed, would you run the following in `/usr/bin/python3.10` ?
```python
import sysconfig
print(sysconfig.get_default_scheme())
print(sysconfig.get_preferred_scheme('prefix'))
print(sysconfig.get_paths())
print(sysconfig.get_paths(sysconfig.get_preferred_scheme('prefix')))
```

**Comment by abersheeran** [comment]
I have the same issue in my Ubuntu18.04 docker container. After reinstall the newest python3.10, pip and pdm, solved it.

**Comment by frostming** [comment]
```python
print(sysconfig.get_path('purelib', 'venv'))
```

It may be different from the above paths

**Comment by vitidev** [comment]
> ```python
> print(sysconfig.get_path('purelib', 'venv'))
> ```

     /usr/lib/python3.10/site-packages

**Comment by frostming** [comment]
> > ```python
> > print(sysconfig.get_path('purelib', 'venv'))
> > ```
> 
> ```
>  /usr/lib/python3.10/site-packages
> ```

Oops
