### ISSUE TITLE
Local package install fails on Python 3.6

### ISSUE THREAD

**Issue by menzenski** [pdm-project/pdm#1164]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

Mac OS X, with PDM installed via Homebrew.

I am using https://github.com/pyenv/pyenv to manage Python versions per project and am using Python 3.6.7 in the project here. (So, `pyenv install 3.6.7` to install python and then `pyenv local 3.6.7` or `pyenv shell 3.6.7` to use it in this project).

I have added a minimal working example here: https://github.com/menzenski/pdm-mwe. Here is the `pyproject.toml`:

```toml
[project]
name = "pdm_mwe"
version = "0.1.0"
description = ""
authors = [
    { name = "Matt Menzenski", email = "test@example.com" },
]
dependencies = [
]
requires-python = ">=3.6.2"

[project.urls]
Homepage = "https://github.com/menzenski/pdm-mwe"

[project.optional-dependencies]
[tool.pdm]

[tool.pdm.scripts]

[tool.pdm.dev-dependencies]

[build-system]
requires = ["pdm-pep517>=0.12.0"]
build-backend = "pdm.pep517.api"
```

## Actual behavior

The installation of my local package fails. The PDM logs include the line `No matching distribution found for pdm-pep517>=0.12.0 (from -r /var/folders/8p/ss0np8217fldcxw5f5dqws480000gp/T/pdm-build-reqs-ej_04y7n.txt (line 1))`. 

## Expected behavior

I expect that PDM will install this package successfully - per [the PDM documentation](https://pdm.fming.dev/latest/#installation) , "There is no restriction about what Python version your project is using, but installing PDM itself needs Python 3.7+." 

## Environment Information

```shell
$ pdm info 
PDM version:        1.15.2
Python Interpreter: /Users/matt/.pyenv/versions/3.6.7/bin/python3 (3.6)
Project Root:       /Users/matt/dev/pdm-mwe
Project Packages:   /Users/matt/dev/pdm-mwe/__pypackages__/3.6
```

```shell
$ pdm info --env
{
  "implementation_name": "cpython",
  "implementation_version": "3.6.7",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "19.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64",
  "python_full_version": "3.6.7",
  "platform_python_implementation": "CPython",
  "python_version": "3.6",
  "sys_platform": "darwin"
}
```

Output of running `pdm install -v`:

```
pdm install -v
All packages are synced to date, nothing to do.

Installing the project as an editable package...
Preparing isolated env for PEP 517 build...
Building wheel for file:///Users/matt/dev/pdm-mwe#egg=pdm-mwe
Collecting pdm-pep517>=0.12.0 (from -r /var/folders/8p/ss0np8217fldcxw5f5dqws480000gp/T/pdm-build-reqs-bv_31w6u.txt (line 1))
  Could not find a version that satisfies the requirement pdm-pep517>=0.12.0 (from -r /var/folders/8p/ss0np8217fldcxw5f5dqws480000gp/T/pdm-build-reqs-bv_31w6u.txt (line 1)) (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.2.0, 0.2.1, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.4.0, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.5.6, 0.5.7, 0.5.8, 0.5.9, 0.5.10, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.8.0, 0.8.1, 0.8.3, 0.8.4, 0.8.5, 0.8.6, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.10.0, 0.10.1, 0.10.2)
No matching distribution found for pdm-pep517>=0.12.0 (from -r /var/folders/8p/ss0np8217fldcxw5f5dqws480000gp/T/pdm-build-reqs-bv_31w6u.txt (line 1))
You are using pip version 10.0.1, however version 21.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Install pdm_mwe 0.1.0 failed
Traceback (most recent call last):
  File "/usr/local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/usr/local/Cellar/pdm/1.15.2/libexec/lib/python3.10/site-packages/pdm/core.py", line 232, in main
    return Core().main(args)
  File "/usr/local/Cellar/pdm/1.15.2/libexec/lib/python3.10/site-packages/pdm/core.py", line 167, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/usr/local/Cellar/pdm/1.15.2/libexec/lib/python3.10/site-packages/pdm/core.py", line 162, in main
    f(options.project, options)
  File "/usr/local/Cellar/pdm/1.15.2/libexec/lib/python3.10/site-packages/pdm/cli/commands/install.py", line 50, in handle
    actions.do_sync(
  File "/usr/local/Cellar/pdm/1.15.2/libexec/lib/python3.10/site-packages/pdm/cli/actions.py", line 209, in do_sync
    handler.synchronize()
  File "/usr/local/Cellar/pdm/1.15.2/libexec/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 389, in synchronize
    self.install_candidate(self_key)
  File "/usr/local/Cellar/pdm/1.15.2/libexec/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 207, in install_candidate
    self.manager.install(can)
  File "/usr/local/Cellar/pdm/1.15.2/libexec/lib/python3.10/site-packages/pdm/installers/manager.py", line 39, in install
    installer(prepared.build(), self.environment, prepared.direct_url())
  File "/usr/local/Cellar/pdm/1.15.2/libexec/lib/python3.10/site-packages/pdm/models/candidates.py", line 331, in build
    self.wheel = builder.build(build_dir, metadata_directory=self._metadata_dir)
  File "/usr/local/Cellar/pdm/1.15.2/libexec/lib/python3.10/site-packages/pdm/builders/editable.py", line 49, in build
    self.install(self._requires, shared=True)
  File "/usr/local/Cellar/pdm/1.15.2/libexec/lib/python3.10/site-packages/pdm/builders/base.py", line 285, in install
    self.subprocess_runner(cmd, isolated=False)
  File "/usr/local/Cellar/pdm/1.15.2/libexec/lib/python3.10/site-packages/pdm/builders/base.py", line 246, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
  File "/usr/local/Cellar/pdm/1.15.2/libexec/lib/python3.10/site-packages/pdm/builders/base.py", line 87, in log_subprocessor
    raise BuildError(
pdm.exceptions.BuildError: Call command ['/Users/matt/.pyenv/versions/3.6.7/bin/python3', '-Esm', 'pip', 'install', '--isolated', '--ignore-installed', '--prefix', '/var/folders/8p/ss0np8217fldcxw5f5dqws480000gp/T/pdm-build-env-m10tb0_8-shared', '--index-url', 'https://pypi.org/simple', '-r', '/var/folders/8p/ss0np8217fldcxw5f5dqws480000gp/T/pdm-build-reqs-bv_31w6u.txt'] return non-zero status(1).
```

I get the same behavior in GitHub actions using https://github.com/pdm-project/setup-pdm with Python version 3.6.7 as well.

**Comment by frostming** [comment]
There is no restriction about what Python version your project is using, but with conditions.

The backend you are using must support Python 3.6, but `pdm-pep517` isn't. Most modern build backends have dropped the support of Python <3.7. You can try [flit-core](https://pypi.org/project/flit-core) instead, PDM can work with it. The other parts of `pyproject.toml` doesn't need change.

**Comment by menzenski** [comment]
I would love to get off 3.6 but I'm limited by AWS Glue support.

Thank you for the flit-core info - that works great!
