### ISSUE TITLE
Tilde (~) version specification not supported

### ISSUE THREAD

**Issue by mgzenitech** [pdm-project/pdm#1201]
- [ ] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

```toml
[project]
requires-python = "~3.9.7"
```

## Actual behavior

```sh
➜  infra-terraform git:(pdm) ✗ pdm show -v
Traceback (most recent call last):
  File "/home/mariusg/.pyenv/versions/3.9.9/lib/python3.9/site-packages/pip/_vendor/packaging/specifiers.py", line 652, in __init__
    parsed.add(Specifier(specifier))
  File "/home/mariusg/.pyenv/versions/3.9.9/lib/python3.9/site-packages/pip/_vendor/packaging/specifiers.py", line 105, in __init__
    raise InvalidSpecifier(f"Invalid specifier: '{spec}'")
pip._vendor.packaging.specifiers.InvalidSpecifier: Invalid specifier: '~ 3.9.7'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mariusg/.pyenv/versions/3.9.9/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/mariusg/.local/lib/python3.9/site-packages/pdm/core.py", line 232, in main
    return Core().main(args)
  File "/home/mariusg/.local/lib/python3.9/site-packages/pdm/core.py", line 167, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/home/mariusg/.local/lib/python3.9/site-packages/pdm/core.py", line 162, in main
    f(options.project, options)
  File "/home/mariusg/.local/lib/python3.9/site-packages/pdm/cli/commands/show.py", line 67, in handle
    installed = project.environment.get_working_set().get(package)
  File "/home/mariusg/.local/lib/python3.9/site-packages/pdm/project/core.py", line 256, in environment
    self._environment = self.get_environment()
  File "/home/mariusg/.local/lib/python3.9/site-packages/pdm/project/core.py", line 251, in get_environment
    return Environment(self)
  File "/home/mariusg/.local/lib/python3.9/site-packages/pdm/models/environment.py", line 74, in __init__
    self.python_requires = project.python_requires
  File "/home/mariusg/.local/lib/python3.9/site-packages/pdm/project/core.py", line 265, in python_requires
    return PySpecSet(self.meta.requires_python)
  File "/home/mariusg/.local/lib/python3.9/site-packages/pdm/models/specifiers.py", line 63, in __init__
    super().__init__(version_str)
  File "/home/mariusg/.pyenv/versions/3.9.9/lib/python3.9/site-packages/pip/_vendor/packaging/specifiers.py", line 654, in __init__
    parsed.add(LegacySpecifier(specifier))
  File "/home/mariusg/.pyenv/versions/3.9.9/lib/python3.9/site-packages/pip/_vendor/packaging/specifiers.py", line 271, in __init__
    super().__init__(spec, prereleases)
  File "/home/mariusg/.pyenv/versions/3.9.9/lib/python3.9/site-packages/pip/_vendor/packaging/specifiers.py", line 105, in __init__
    raise InvalidSpecifier(f"Invalid specifier: '{spec}'")
pip._vendor.packaging.specifiers.InvalidSpecifier: Invalid specifier: '~ 3.9.7'
```

## Expected behavior

Successfully check if python is >=3.9.7 and < 3.10.0

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
➜  infra-terraform git:(pdm) ✗ pdm info && pdm info --env 
[InvalidSpecifier]: Invalid specifier: '~3.9.7'
Add '-v' to see the detailed traceback
```

**Comment by frostming** [comment]
Read the [PEP 440](https://peps.python.org/pep-0440/#version-specifiers) specification, it should be `~=`
