### ISSUE TITLE
2.0.0b2. RECORD is not mentioned in RECORD

### ISSUE THREAD

**Issue by vitidev** [pdm-project/pdm#1223]
- [x ] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

The error will only occur once after `pdm init`

    $ pdm init
      ....
    $ pdm add -v pyqt5-qt5
    Adding packages to default dependencies: pyqt5-qt5
    pdm.termui: ======== Start resolving requirements ========
    pdm.termui:   pyqt5-qt5
    pdm.termui:   python>=3.10
    pdm.termui:   Adding requirement pyqt5-qt5
    pdm.termui:   Adding requirement python>=3.10
    pdm.termui: ======== Starting round 0 ========
    pdm.termui: Pinning: python None
    pdm.termui: ======== Ending round 0 ========
    pdm.termui: ======== Starting round 1 ========
    pdm.termui: Pinning: pyqt5-qt5 5.15.2
    pdm.termui: ======== Ending round 1 ========
    pdm.termui: ======== Starting round 2 ========
    pdm.termui: ======== Resolution Result ========
    pdm.termui: Stable pins:
    pdm.termui:      python None
    pdm.termui:   pyqt5-qt5 5.15.2
      Lock successful
    Changes are written to pdm.lock.
    Changes are written to pyproject.toml.
    Synchronizing working set with lock file: 1 to add, 0 to update, 0 to remove

    unearth: Downloading <Link https://files.pythonhosted.org/packages/37/97/5d3b222b924fa2ed4c2488925155cd0b03fd5d09ee1cfcf7c553c11c9f66/PyQt5_Qt5-5.15.2-py3-none-win_amd64.whl (from None)> to U:\Temp\pdm-build-sdhkdq7y\PyQt5_Qt5-5.15.2-py3-none-win_amd64.whl
      x Install pyqt5-qt5 5.15.2 failed
    pdm.termui: Error occurs:
    Traceback (most recent call last):
      File "C:\Python\lib\concurrent\futures\thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
      File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\synchronizers.py", line 217, in install_candidate
        self.manager.install(can)
      File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\manager.py", line 39, in install
        installer(str(prepared.build()), self.environment, prepared.direct_url())
      File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\installers.py", line 185, in install_wheel
        _install_wheel(
      File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\installers.py", line 279, in _install_wheel
        install(source, destination, additional_metadata=additional_metadata or {})
      File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\installer\_core.py", line 96, in install
        for record_elements, stream, is_executable in source.get_contents():
      File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\installers.py", line 131, in get_contents
        for element in super().get_contents():
      File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\installer\sources.py", line 158, in get_contents
        assert record is not None, "In {}, {} is not mentioned in RECORD".format(
    AssertionError: In U:\Temp\pdm-build-sdhkdq7y\PyQt5_Qt5-5.15.2-py3-none-win_amd64.whl, PyQt5_Qt5-5.15.2.dist-info/RECORD is not mentioned in RECORD
    Retry failed jobs
      x Install pyqt5-qt5 5.15.2 failed
    pdm.termui: Error occurs:
    Traceback (most recent call last):
      File "C:\Python\lib\concurrent\futures\thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
      File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\synchronizers.py", line 217, in install_candidate
        self.manager.install(can)
      File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\manager.py", line 39, in install
        installer(str(prepared.build()), self.environment, prepared.direct_url())
      File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\installers.py", line 185, in install_wheel
        _install_wheel(
      File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\installers.py", line 279, in _install_wheel
        install(source, destination, additional_metadata=additional_metadata or {})
      File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\installer\_core.py", line 96, in install
        for record_elements, stream, is_executable in source.get_contents():
      File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\installers.py", line 131, in get_contents
        for element in super().get_contents():
      File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\installer\sources.py", line 158, in get_contents
        assert record is not None, "In {}, {} is not mentioned in RECORD".format(
    AssertionError: In U:\Temp\pdm-build-sdhkdq7y\PyQt5_Qt5-5.15.2-py3-none-win_amd64.whl, PyQt5_Qt5-5.15.2.dist-info/RECORD is not mentioned in RECORD
    Traceback (most recent call last):
      File "C:\Python\lib\runpy.py", line 196, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "C:\Python\lib\runpy.py", line 86, in _run_code
        exec(code, run_globals)
      File "c:\users\user\.local\bin\pdm.exe\__main__.py", line 7, in <module>
      File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\pdm\core.py", line 256, in main
        return Core().main(args)
      File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\pdm\core.py", line 189, in main
        raise cast(Exception, err).with_traceback(traceback)
      File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\pdm\core.py", line 184, in main
        f(options.project, options)
      File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\pdm\cli\commands\add.py", line 58, in handle
        actions.do_add(
      File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\pdm\cli\actions.py", line 288, in do_add
        do_sync(
      File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\pdm\cli\actions.py", line 218, in do_sync
        handler.synchronize()
      File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\synchronizers.py", line 402, in synchronize
        raise InstallationError("Some package operations are not complete yet")
    pdm.exceptions.InstallationError: Some package operations are not complete yet
repeat command. Everything is OK

    $ pdm add -v pyqt5-qt5 -v
    Adding packages to default dependencies: pyqt5-qt5
    pdm.termui: ======== Start resolving requirements ========
    pdm.termui:   pyqt5-qt5
    pdm.termui:   python>=3.10
    pdm.termui:   Adding requirement pyqt5-qt5
    unearth: Collecting links from https://pypi.org/simple/pyqt5-qt5/
    unearth: Found index url https://pypi.org/simple
    pdm.termui:     Found matching candidates:
    pdm.termui:       <Candidate pyqt5-qt5 5.15.2 from https://pypi.org/simple/pyqt5-qt5/>
    pdm.termui:   Adding requirement python>=3.10
    pdm.termui: ======== Starting round 0 ========
    pdm.termui:     Found matching candidates:
    pdm.termui:       <Candidate pyqt5-qt5 5.15.2 from https://pypi.org/simple/pyqt5-qt5/>
    pdm.termui: Pinning: python None
    pdm.termui: ======== Ending round 0 ========
    pdm.termui: ======== Starting round 1 ========
    pdm.termui:     Found matching candidates:
    pdm.termui:       <Candidate pyqt5-qt5 5.15.2 from https://pypi.org/simple/pyqt5-qt5/>
    pdm.termui:     Found matching candidates:
    pdm.termui:       <Candidate pyqt5-qt5 5.15.2 from https://pypi.org/simple/pyqt5-qt5/>
    pdm.termui: Pinning: pyqt5-qt5 5.15.2
    pdm.termui: ======== Ending round 1 ========
    pdm.termui: ======== Starting round 2 ========
    pdm.termui: ======== Resolution Result ========
    pdm.termui: Stable pins:
    pdm.termui:      python None
    pdm.termui:   pyqt5-qt5 5.15.2
    unearth: Collecting links from https://pypi.org/simple/pyqt5-qt5/
    unearth: Found index url https://pypi.org/simple
    pdm.termui:     Found matching candidates:
    pdm.termui:       <Candidate pyqt5-qt5 5.15.2 from https://pypi.org/simple/pyqt5-qt5/>
      Lock successful
    Changes are written to pdm.lock.
    Changes are written to pyproject.toml.
    All packages are synced to date, nothing to do.
    
Then you can delete pyqt5-qt5 and reinstall and there will be no errors

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
    pdm info && pdm info --env
    PDM version:
      2.0.0b2
    Python Interpreter:
      C:\Python\python.exe (3.10)
    Project Root:
      z:/333
    Project Packages:
      z:\333\__pypackages__\3.10
    {
      "implementation_name": "cpython",
      "implementation_version": "3.10.5",
      "os_name": "nt",
      "platform_machine": "AMD64",
      "platform_release": "10",
      "platform_system": "Windows",
      "platform_version": "10.0.19044",
      "python_full_version": "3.10.5",
      "platform_python_implementation": "CPython",
      "python_version": "3.10",
      "sys_platform": "win32"
    }
```

**Comment by frostming** [comment]
> Then you can delete pyqt5-qt5 and reinstall and there will be no errors

Yeah but I think the installation isn't complete. This is an issue of the pyqt5 package not including the RECORD file correctly, and can't be resolved in PDM side.

**Comment by vitidev** [comment]
@frostming 
>Yeah but I think the installation isn't complete

All the necessary files at this moment are placed in the lib. Then the assert is triggered (which is apparently not present in pip, so it is install without errors)

But why is the repeating pdm command is successful? Why doesn't the assertion throw an error the second time? Why the installation process is non-deterministic?

**Comment by frostming** [comment]
> All the necessary files at this moment are placed in the lib

Not really, the `<package>-<version>.dist-info/RECORD` is absent, but at that point all other files are ready.

> But why is the repeating pdm command is successful

Because at the second time, PDM thinks the package is already installed, by checking the existence of `<package>-<version>.dist-info/` and won't try installing again(if it tries, it can find the `RECORD` file can't be installed).

**Comment by vitidev** [comment]
@frostming 
><package>-<version>.dist-info/RECORD is absent

As I understand pdm is looking for `PyQt5_Qt5-5.15.2.dist-info/RECORD` in `RECORD`
but there is `PyQt5_Qt5-5.15.2.dist-info\RECORD,,`

Does pdm work with paths as is? Maybe add a slash fix or use os.path.normpath?
