### ISSUE TITLE
`pdm sync`: ModuleNotFoundError: No module named 'setuptools'

### ISSUE THREAD

**Issue by icexin** [pdm-project/pdm#1238]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

run `pdm sync`

## Actual behavior

``` bash
pdm.termui: Traceback (most recent call last):
pdm.termui:   File "/home/bingxin.fan/sdk-python/setup.py", line 3, in <module>
pdm.termui:     from setuptools import setup
pdm.termui: ModuleNotFoundError: No module named 'setuptools'
pdm.termui: /tmp/pdm-build-env-_b26g862-shared/lib/python3.8/site-packages/pdm/pep517/base.py:295: PDMWarning: 'license-expression' is missing
pdm.termui:   "license": meta.license_expression,
pdm.termui: Traceback (most recent call last):
pdm.termui:   File "/tmp/pdm-build-env-_b26g862-shared/lib/python3.8/site-packages/pdm/pep517/editable.py", line 88, in _build
pdm.termui:     subprocess.check_call(build_args)
pdm.termui:   File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
pdm.termui:     raise CalledProcessError(retcode, cmd)
pdm.termui: subprocess.CalledProcessError: Command '['/usr/bin/python3.8', '/home/bingxin.fan/sdk-python/setup.py', 'build_ext', '--inplace']' returned non-zero exit status 1.
pdm.termui: 
pdm.termui: During handling of the above exception, another exception occurred:
pdm.termui: 
pdm.termui: Traceback (most recent call last):
pdm.termui:   File "/home/bingxin.fan/.local/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 363, in <module>
pdm.termui:     main()
pdm.termui:   File "/home/bingxin.fan/.local/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 345, in main
pdm.termui:     json_out['return_val'] = hook(**hook_input['kwargs'])
pdm.termui:   File "/home/bingxin.fan/.local/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 283, in build_editable
pdm.termui:     return hook(wheel_directory, config_settings, metadata_directory)
pdm.termui:   File "/tmp/pdm-build-env-_b26g862-shared/lib/python3.8/site-packages/pdm/pep517/api.py", line 101, in build_editable
pdm.termui:     return Path(builder.build(wheel_directory)).name
pdm.termui:   File "/tmp/pdm-build-env-_b26g862-shared/lib/python3.8/site-packages/pdm/pep517/wheel.py", line 77, in build
pdm.termui:     self._build(zip_file)
pdm.termui:   File "/tmp/pdm-build-env-_b26g862-shared/lib/python3.8/site-packages/pdm/pep517/editable.py", line 90, in _build
pdm.termui:     raise BuildError(f"Error occurs when running {build_args}:\n{e}")
pdm.termui: pdm.pep517.exceptions.BuildError: Error occurs when running ['/usr/bin/python3.8', '/home/bingxin.fan/sdk-python/setup.py', 'build_ext', '--inplace']:
pdm.termui: Command '['/usr/bin/python3.8', '/home/bingxin.fan/sdk-python/setup.py', 'build_ext', '--inplace']' returned non-zero exit status 1.
```

## Expected behavior

The `pdm sync` runs successfully.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:

$ pdm info

PDM version:
  2.0.0
Python Interpreter:
  /usr/bin/python3.8 (3.8)
Project Root:
  /home/bingxin.fan/sdk-python
Project Packages:
  /home/bingxin.fan/sdk-python/__pypackages__/3.8

$ pdm info --env

{
  "implementation_name": "cpython",
  "implementation_version": "3.8.10",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.4.0-77-shopee-generic",
  "platform_system": "Linux",
  "platform_version": "#86+3 SMP Fri Oct 22 11:37:43 +08 2021",
  "python_full_version": "3.8.10",
  "platform_python_implementation": "CPython",
  "python_version": "3.8",
  "sys_platform": "linux"
}

```

The `build` section of `pyproject.toml`:

```
[tool.pdm.build]
setup-script = "cmake.py"
run-setuptools = false
is-purelib = true
```

I'm wondering why the `setuptools` be called.

**Comment by frostming** [comment]
Can you show the full log with `pdm sync -v`?

**Comment by frostming** [comment]
Why it pulls so many build requirements, can you show the `[build-system]` table of `pyproject.toml`?

**Comment by frostming** [comment]
You shouldn't use `pdm >= 2.0.0`,  but instead `pdm-pep517 >= 1.0.0`

**Comment by icexin** [comment]
I've change to `pdm-pep517 >= 1.0.0`, but got the same error.

**Comment by frostming** [comment]
I can't reproduce it, can you provide an example?

**Comment by icexin** [comment]
sure. I will try to build a minimal reproducible project.

**Comment by icexin** [comment]
@frostming Here is the repo which can reproduce the error. https://github.com/icexin/pdm-cpp
