### ISSUE TITLE
pdm was failed to follow pypiserver fallback redirection

### ISSUE THREAD

**Issue by leemars** [pdm-project/pdm#1252]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

```bash
docker run --rm -p 8123:8080 pypiserver/pypiserver:latest run --fallback-url https://mirrors.aliyun.com/pypi/simple
pdm init
pdm config -l pypi.url http://localhost:8123/simple/ 
pdm add requests
```

## Actual behavior

```
Adding packages to default dependencies: requests
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   requests
pdm.termui:   python>=3.9
pdm.termui:   Adding requirement requests
pdm.termui:   Adding requirement python>=3.9
pdm.termui: ======== Starting round 0 ========
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
unearth: Downloading <Link http://localhost:8123/packages/ca/91/6d9b8ccacd0412c08820f72cebaa4f0c0441b5cda699c90f618b6f8a1b42/requests-2.28.1-py3-none-any.whl (from None)> to /var/folders/g2/h_68tc5j77zf7tsmhsrff6hw0000gn/T/pdm-build-pd13qmsn/requests-2.28.1-py3-none-any.whl
Traceback (most recent call last):
  File "/opt/homebrew/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/Cellar/pdm/2.0.2/libexec/lib/python3.10/site-packages/pdm/core.py", line 254, in main
    return Core().main(args)
  File "/opt/homebrew/Cellar/pdm/2.0.2/libexec/lib/python3.10/site-packages/pdm/core.py", line 187, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/opt/homebrew/Cellar/pdm/2.0.2/libexec/lib/python3.10/site-packages/pdm/core.py", line 182, in main
    f(options.project, options)
  File "/opt/homebrew/Cellar/pdm/2.0.2/libexec/lib/python3.10/site-packages/pdm/cli/commands/add.py", line 58, in handle
    actions.do_add(
  File "/opt/homebrew/Cellar/pdm/2.0.2/libexec/lib/python3.10/site-packages/pdm/cli/actions.py", line 277, in do_add
    resolved = do_lock(
  File "/opt/homebrew/Cellar/pdm/2.0.2/libexec/lib/python3.10/site-packages/pdm/cli/actions.py", line 100, in do_lock
    mapping, dependencies = resolve(
  File "/opt/homebrew/Cellar/pdm/2.0.2/libexec/lib/python3.10/site-packages/pdm/resolver/core.py", line 31, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "/opt/homebrew/Cellar/pdm/2.0.2/libexec/lib/python3.10/site-packages/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/opt/homebrew/Cellar/pdm/2.0.2/libexec/lib/python3.10/site-packages/resolvelib/resolvers.py", line 373, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/opt/homebrew/Cellar/pdm/2.0.2/libexec/lib/python3.10/site-packages/resolvelib/resolvers.py", line 213, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "/opt/homebrew/Cellar/pdm/2.0.2/libexec/lib/python3.10/site-packages/resolvelib/resolvers.py", line 203, in _get_updated_criteria
    for requirement in self._p.get_dependencies(candidate=candidate):
  File "/opt/homebrew/Cellar/pdm/2.0.2/libexec/lib/python3.10/site-packages/pdm/resolver/providers.py", line 180, in get_dependencies
    deps, requires_python, _ = self.repository.get_dependencies(candidate)
  File "/opt/homebrew/Cellar/pdm/2.0.2/libexec/lib/python3.10/site-packages/pdm/models/repositories.py", line 70, in get_dependencies
    requirements, requires_python, summary = getter(candidate)
  File "/opt/homebrew/Cellar/pdm/2.0.2/libexec/lib/python3.10/site-packages/pdm/models/repositories.py", line 35, in wrapper
    result = func(self, candidate)
  File "/opt/homebrew/Cellar/pdm/2.0.2/libexec/lib/python3.10/site-packages/pdm/models/repositories.py", line 217, in _get_dependencies_from_metadata
    deps = prepared.get_dependencies_from_metadata()
  File "/opt/homebrew/Cellar/pdm/2.0.2/libexec/lib/python3.10/site-packages/pdm/models/candidates.py", line 478, in get_dependencies_from_metadata
    self.req.project_name, self.metadata.requires or [], extras  # type: ignore
  File "/opt/homebrew/Cellar/pdm/2.0.2/libexec/lib/python3.10/site-packages/pdm/models/candidates.py", line 462, in metadata
    result = self.prepare_metadata()
  File "/opt/homebrew/Cellar/pdm/2.0.2/libexec/lib/python3.10/site-packages/pdm/models/candidates.py", line 406, in prepare_metadata
    self.obtain(allow_all=True)
  File "/opt/homebrew/Cellar/pdm/2.0.2/libexec/lib/python3.10/site-packages/pdm/models/candidates.py", line 396, in obtain
    result = finder.download_and_unpack(
  File "/opt/homebrew/Cellar/pdm/2.0.2/libexec/lib/python3.10/site-packages/unearth/finder.py", line 363, in download_and_unpack
    file = unpack_link(
  File "/opt/homebrew/Cellar/pdm/2.0.2/libexec/lib/python3.10/site-packages/unearth/preparer.py", line 304, in unpack_link
    raise UnpackError(f"Download failed: {e}") from None
unearth.errors.UnpackError: Download failed: 404 Client Error: Not Found for url: http://localhost:8123/packages/ca/91/6d9b8ccacd0412c08820f72cebaa4f0c0441b5cda699c90f618b6f8a1b42/requests-2.28.1-py3-none-any.whl#sha256=8fefa2a1a1365bf5520aac41836fbee479da67864514bdb821f31ce07ce65349
```

## Expected behavior

pdm should use the url after following the pypiserver fallback redirection, instead of the origin one.

```
$ curl http://localhost:8123/simple/requests/ -v                                                                        
*   Trying 127.0.0.1:8123...
* Connected to localhost (127.0.0.1) port 8123 (#0)
> GET /simple/requests/ HTTP/1.1
> Host: localhost:8123
> User-Agent: curl/7.79.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 303 See Other
< Content-Length: 0
< Content-Type: text/html; charset=UTF-8
< Date: Thu, 21 Jul 2022 07:03:11 GMT
< Location: https://mirrors.aliyun.com/pypi/simple/requests/
< Server: waitress
<
* Connection #0 to host localhost left intact
```

## Environment Information

```bash
PDM version:
  2.0.2
Python Interpreter:
  /Users/leemars/Workspace/tmp/pdm/.venv/bin/python (3.9)
Project Root:
  /Users/leemars/Workspace/tmp/pdm
Project Packages:
  None

{
  "implementation_name": "cpython",
  "implementation_version": "3.9.12",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "21.5.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022;
root:xnu-8020.121.3~4/RELEASE_ARM64_T6000",
  "python_full_version": "3.9.12",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
Upgrade the version of `unearth`
