### ISSUE TITLE
pdm breaks down because pip 22.2 removed html5lib 

### ISSUE THREAD

**Issue by viing937** [pdm-project/pdm#1261]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

pip 22.2 removed html5lib.
This is its [changelog](https://pip.pypa.io/en/stable/news/#vendored-libraries). 

```
pip3 install -U pip setuptools wheel pdm==1.15.4
pdm sync --prod
```

## Actual behavior

```
#15 79.39 Traceback (most recent call last):
#15 79.39   File "/usr/local/bin/pdm", line 5, in <module>
#15 79.39     from pdm.core import main
#15 79.39   File "/usr/local/lib/python3.7/site-packages/pdm/__init__.py", line 5, in <module>
#15 79.39     from pdm.cli.commands.base import BaseCommand
#15 79.39   File "/usr/local/lib/python3.7/site-packages/pdm/cli/commands/base.py", line 6, in <module>
#15 79.39     from pdm.cli.utils import PdmFormatter
#15 79.39   File "/usr/local/lib/python3.7/site-packages/pdm/cli/utils.py", line 30, in <module>
#15 79.39     from pdm.formats import FORMATS
#15 79.39   File "/usr/local/lib/python3.7/site-packages/pdm/formats/__init__.py", line 8, in <module>
#15 79.39     from pdm.formats import flit, legacy, pipfile, poetry, requirements, setup_py
#15 79.39   File "/usr/local/lib/python3.7/site-packages/pdm/formats/flit.py", line 18, in <module>
#15 79.39     from pdm.project import Project
#15 79.39   File "/usr/local/lib/python3.7/site-packages/pdm/project/__init__.py", line 2, in <module>
#15 79.39     from pdm.project.core import Project  # noqa
#15 79.39   File "/usr/local/lib/python3.7/site-packages/pdm/project/core.py", line 24, in <module>
#15 79.39     from pdm.models.repositories import BaseRepository, LockedRepository, PyPIRepository
#15 79.39   File "/usr/local/lib/python3.7/site-packages/pdm/models/repositories.py", line 9, in <module>
#15 79.39     from pip._vendor.html5lib import parse
#15 79.39 ModuleNotFoundError: No module named 'pip._vendor.html5lib'
```

## Expected behavior

I Know pdm 2.0 does not use pip anymore, but is there a proper way to lock pip version under 22.2 for pdm 1.x？

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:

```

**Comment by frostming** [comment]
You can set the upper bound yourself: `pipx inject pdm "pip<22.2"`
