### ISSUE TITLE
Key "url" does not exist.

### ISSUE THREAD

**Issue by cye18** [pdm-project/pdm#1265]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

I have `pyproject.toml` and `pdm.lock` that work well with PDM 1.15 in a git repo. I clone it to a new machine and install PDM 2.0.3. I run `pdm sync`. It detects `__pypackages__` and uses PEP 582 mode, but returns an error.

```
$pdm sync
Lock file version is not compatible with PDM, installation may fail
⠙ Resolving packages from lockfile...__pypackages__ is detected, using the PEP 582 mode
See /tmp/pdm-install-resolve-78und0n3.log for detailed debug log.
[NonExistentKey]: 'Key "url" does not exist.'
Add '-v' to see the detailed traceback
```

## Actual behavior

```
pdm sync -v
Lock file version is not compatible with PDM, installation may fail
Traceback (most recent call last):
  File "/home/ds/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/ds/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/core.py", line 254, in main
    return Core().main(args)
  File "/home/ds/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/core.py", line 187, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/home/ds/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/core.py", line 182, in main
    f(options.project, options)
  File "/home/ds/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/cli/commands/sync.py", line 36, in handle
    actions.do_sync(
  File "/home/ds/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/cli/actions.py", line 202, in do_sync
    candidates = resolve_candidates_from_lockfile(project, requirements)
  File "/home/ds/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/cli/actions.py", line 143, in resolve_candidates_from_lockfile
    provider = project.get_provider(for_install=True)
  File "/home/ds/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/project/core.py", line 464, in get_provider
    locked_repository = self.locked_repository
  File "/home/ds/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/project/core.py", line 426, in locked_repository
    return LockedRepository(lockfile, self.sources, self.environment)
  File "/home/ds/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/models/repositories.py", line 372, in __init__
    self._read_lockfile(lockfile)
  File "/home/ds/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/models/repositories.py", line 401, in _read_lockfile
    self.file_hashes[tuple(key.split(None, 1))] = {  # type: ignore
  File "/home/ds/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/models/repositories.py", line 402, in <dictcomp>
    Link(item["url"]): item["hash"] for item in hashes
  File "/home/ds/.local/share/pdm/venv/lib/python3.8/site-packages/tomlkit/container.py", line 608, in __getitem__
    raise NonExistentKey(key)
```

## Expected behavior

In my understanding `pdm.lock` generated with PDM 1.x should work with PDM 2.0+, but it says "Lock file version is not compatible with PDM, installation may fail". It's expected to install the dependencies in `__pypackages__` without the error.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.0.3
Python Interpreter:
  /usr/bin/python3.8 (3.8)
Project Root:
  /home/ds/projects/enterprise-ulm/02_modeling
Project Packages:
  /home/ds/projects/enterprise-ulm/02_modeling/__pypackages__/3.8
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.10",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.4.0-1040-gcp",
  "platform_system": "Linux",
  "platform_version": "#43-Ubuntu SMP Fri Mar 19 17:49:48 UTC 2021",
  "python_full_version": "3.8.10",
  "platform_python_implementation": "CPython",
  "python_version": "3.8",
  "sys_platform": "linux"
}
```

Thanks for your help!

**Comment by frostming** [comment]
See the first line

Lock file version is not compatible with PDM, installation may fail

If you run pdm install, it will upgrade the lock file for you

**Comment by cye18** [comment]
I tried `PDM install`. It indeed updated the lock file. Some packages are updated to newer versions and it works.

I'm just trying to understand why the lock file that worked well in the past stops working. Is it because my PDM is updated to 2.0? Technically the lock file is a resolution PDM 1.15 found, and the versions should be still compatible regardless of PDM version.

Thank you very much ☺️

**Comment by frostming** [comment]
> Technically the lock file is a resolution PDM 1.15 found, and the versions should be still compatible regardless of PDM version.

There is no such guarentee, the lock file is also versioned, and there is an upgrade in 2.0. but no worry pdm install will regenerate for you

**Comment by frostming** [comment]
try pdm lock --refresh as well, it should keep the pinned versions

**Comment by blueyed** [comment]
Note: manually forcing `strategy = "reuse"` with the install action still updates already locked versions when re-generating the lock file.  This looks like a bug, or is it due to the lock file not being used at all on purpose?

**Comment by cye18** [comment]
`pdm lock --refresh` gives the same 'Key "url" does not exist.' error.

```
$ pdm lock --refresh -v
Traceback (most recent call last):
  File "/home/ds/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/ds/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/core.py", line 254, in main
    return Core().main(args)
  File "/home/ds/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/core.py", line 187, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/home/ds/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/core.py", line 182, in main
    f(options.project, options)
  File "/home/ds/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/cli/commands/lock.py", line 27, in handle
    actions.do_lock(
  File "/home/ds/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/cli/actions.py", line 68, in do_lock
    locked_repo = project.locked_repository
  File "/home/ds/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/project/core.py", line 426, in locked_repository
    return LockedRepository(lockfile, self.sources, self.environment)
  File "/home/ds/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/models/repositories.py", line 372, in __init__
    self._read_lockfile(lockfile)
  File "/home/ds/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/models/repositories.py", line 401, in _read_lockfile
    self.file_hashes[tuple(key.split(None, 1))] = {  # type: ignore
  File "/home/ds/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/models/repositories.py", line 402, in <dictcomp>
    Link(item["url"]): item["hash"] for item in hashes
  File "/home/ds/.local/share/pdm/venv/lib/python3.8/site-packages/tomlkit/container.py", line 608, in __getitem__
    raise NonExistentKey(key)
tomlkit.exceptions.NonExistentKey: 'Key "url" does not exist.'
```

What is the key "url"?

**Comment by cye18** [comment]
I realized the "url" is introduced in 2.0 

https://github.com/pdm-project/pdm/blob/2.0.3/pdm/models/repositories.py#L402

I think that kind of answers my question -- the lock file generated by PDM 1.x could not be compatible with PDM 2.0.

I would run `pdm install` in this case.

Thank you!

**Comment by frostming** [comment]
> Note: manually forcing `strategy = "reuse"` with the install action still updates already locked versions when re-generating the lock file.  This looks like a bug, or is it due to the lock file not being used at all on purpose?

When there is a major bump on the version, there isn't any guarantee that the locked versions could be "reused", so we always ignore the lock file in this case.

**Comment by cye18** [comment]
I think #1273 is a better version of my question. Thanks. ❤️
