### ISSUE TITLE
PDM install --dev stopped working on 2.0.2

### ISSUE THREAD

**Issue by lyz-code** [pdm-project/pdm#1288]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

```bash
git clone https://github.com/lyz-code/yamlfix
cd yamlfix
pdm install --dev -v
```

## Actual behavior

The command failed with the next error:

```
Detected inside an active virtualenv /tmp/tmp.EnJKyK0cOr/env, reuse it.
Traceback (most recent call last):
  File "~/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "~/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/core.py", line 254, in main
    return Core().main(args)
  File "~/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/core.py", line 187, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "~/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/core.py", line 182, in main
    f(options.project, options)
  File "~/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/cli/commands/install.py", line 61,
 in handle
    actions.do_sync(
  File "~/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/cli/actions.py", line 202, in do_s
ync
    candidates = resolve_candidates_from_lockfile(project, requirements)
  File "~/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/cli/actions.py", line 145, in reso
lve_candidates_from_lockfile
    mapping, *_ = resolve(
  File "~/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/resolver/core.py", line 31, in res
olve
    result = resolver.resolve(requirements, max_rounds)
  File "~/.local/share/pdm/venv/lib/python3.9/site-packages/resolvelib/resolvers.py", line 481, in
 resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "~/.local/share/pdm/venv/lib/python3.9/site-packages/resolvelib/resolvers.py", line 373, in
 resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "~/.local/share/pdm/venv/lib/python3.9/site-packages/resolvelib/resolvers.py", line 213, in
 _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "~/.local/share/pdm/venv/lib/python3.9/site-packages/resolvelib/resolvers.py", line 203, in
 _get_updated_criteria
    for requirement in self._p.get_dependencies(candidate=candidate):
  File "~/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/resolver/providers.py", line 180,
in get_dependencies
    deps, requires_python, _ = self.repository.get_dependencies(candidate)
  File "~/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/models/repositories.py", line 420,
 in get_dependencies
    reqs, python, summary = super().get_dependencies(candidate)
  File "~/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/models/repositories.py", line 70,
in get_dependencies
    requirements, requires_python, summary = getter(candidate)
  File "~/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/models/repositories.py", line 412,
 in _get_dependencies_from_lockfile
    return self.candidate_info[self._identify_candidate(candidate)]
KeyError: ('yamlfix', '1.0.0', None, False)
```

## Expected behavior

`pdm  install --dev` works as expected.

## Environment Information

```bash
PDM version:
  2.0.2
Python Interpreter:
  /tmp/tmp.EnJKyK0cOr/env/bin/python (3.9)
Project Root:
  /tmp/tmp.EnJKyK0cOr/yamlfix
Project Packages:
  None
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.10",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "4.19.0-5-amd64",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Debian 4.19.37-5+deb10u1 (2019-07-19)",
  "python_full_version": "3.9.10",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

I've also tried with 2.0.3 and 2.1.0.

**Comment by frostming** [comment]
Can you show the pyproject.toml and pdm.lock, you should always assume the others can't reproduce.

**Comment by lyz-code** [comment]
Hi @frostming thanks for you quick answer. I thought that the steps under `Steps to reproduce` in the description were the easiest way to reproduce the issue. I can add the steps to create a temporal directory, and a virtualenv if you want to the `Steps to reproduce`, or if you explain me what else is missing I'm happy to provide it.

Here are the requested files:

* [pyproject.toml](https://github.com/lyz-code/yamlfix/blob/main/pyproject.toml)
* [pdm.lock](https://github.com/lyz-code/yamlfix/blob/main/pdm.lock)

**Comment by frostming** [comment]
Hi, the problem is you add self as a dependency: https://github.com/lyz-code/yamlfix/blob/e614bb440fd6def2f3c32bb6ff6f44c235cf0e47/pyproject.toml#L125

Is it a mistake or do you have any rationale behind this?

**Comment by lyz-code** [comment]
It is a mistake, thanks for pointing it out and sorry for wasting your time :(
