### ISSUE TITLE
Git not found trying to make pdm lock

### ISSUE THREAD

**Issue by SirMartin** [pdm-project/pdm#1298]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

I am trying to make a docker-compose that launches the pdm lock command inside to generate in this container the lock file. My dependencies include some libraries from git.

## Actual behavior

When pdm lock tries to add one of the git repositories, it crashes, because it cannot find the "git" folder

```bash
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   common @ git+https://${GITHUB_PIP_TOKEN}@github.com/xxxx/ccccc.git@8b2455656c448dac6bc5076c50bb02daebfd538c
pdm.termui:   liba@ git+https://${GITHUB_PIP_TOKEN}@github.com/xxxx/xxx.git@58dd7d72b497719e9bdd7fc01b46bf466fe85716
pdm.termui:   setuptools>=62.1.0
pdm.termui:   flake8==5.0.3
pdm.termui:   python>=3.9
pdm.termui:   Adding requirement common @ git+https://${GITHUB_PIP_TOKEN}@github.com/xxxx/ccccc.git@8b2455656c448dac6bc5076c50bb02daebfd538c
unearth: Cloning https://***@github.com/xxxx/ccccc.git (revision: 8b2455656c448dac6bc5076c50bb02daebfd538c) to /tmp/pdm-build-69irab15
Traceback (most recent call last):
  File "/usr/local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/pdm/core.py", line 254, in main
    return Core().main(args)
  File "/usr/local/lib/python3.9/site-packages/pdm/core.py", line 187, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/usr/local/lib/python3.9/site-packages/pdm/core.py", line 182, in main
    f(options.project, options)
  File "/usr/local/lib/python3.9/site-packages/pdm/cli/commands/lock.py", line 27, in handle
    actions.do_lock(
  File "/usr/local/lib/python3.9/site-packages/pdm/cli/actions.py", line 100, in do_lock
    mapping, dependencies = resolve(
  File "/usr/local/lib/python3.9/site-packages/pdm/resolver/core.py", line 30, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "/usr/local/lib/python3.9/site-packages/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/local/lib/python3.9/site-packages/resolvelib/resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/usr/local/lib/python3.9/site-packages/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/usr/local/lib/python3.9/site-packages/resolvelib/structs.py", line 126, in __bool__
    next(self._factory())
  File "/usr/local/lib/python3.9/site-packages/pdm/resolver/providers.py", line 146, in matches_gen
    candidates = self._find_candidates(reqs[0])
  File "/usr/local/lib/python3.9/site-packages/pdm/resolver/providers.py", line 125, in _find_candidates
    can.prepare(self.repository.environment).metadata
  File "/usr/local/lib/python3.9/site-packages/pdm/models/candidates.py", line 472, in metadata
    result = self.prepare_metadata()
  File "/usr/local/lib/python3.9/site-packages/pdm/models/candidates.py", line 415, in prepare_metadata
    self.obtain(allow_all=True)
  File "/usr/local/lib/python3.9/site-packages/pdm/models/candidates.py", line 405, in obtain
    result = finder.download_and_unpack(
  File "/usr/local/lib/python3.9/site-packages/unearth/finder.py", line 356, in download_and_unpack
    file = unpack_link(
  File "/usr/local/lib/python3.9/site-packages/unearth/preparer.py", line 282, in unpack_link
    backend.fetch(link, location)
  File "/usr/local/lib/python3.9/site-packages/unearth/vcs/base.py", line 145, in fetch
    return self.fetch_new(location, url, rev, args)
  File "/usr/local/lib/python3.9/site-packages/unearth/vcs/git.py", line 44, in fetch_new
    if self.get_git_version() >= (2, 17):
  File "/usr/local/lib/python3.9/site-packages/unearth/vcs/git.py", line 22, in get_git_version
    result = self.run_command(["version"], stdout_only=True, log_output=False)
  File "/usr/local/lib/python3.9/site-packages/unearth/vcs/base.py", line 64, in run_command
    result = subprocess.run(
  File "/usr/local/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git'
ERROR: 1
make: *** [Makefile:102: pdm-lock] Error 1
```

## Expected behavior

The pdm lock command would be executed without any issue.

The problem only happens inside the container, and also only if it contains git repositories. It works locally, or in a standard docker container with and without git repositories, and also worked in the docker-compose without any git repository.

I also tried to install git (via apt-get) in the container with no effect.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.1.0
Python Interpreter:
  /usr/local/bin/python (3.9)
Project Root:
  /code
Project Packages:
  /code/__pypackages__/3.9

{
  "implementation_name": "cpython",
  "implementation_version": "3.9.7",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.17.15-76051715-generic",
  "platform_system": "Linux",
  "platform_version": "#202206141358~1655919116~22.04~1db9e34 SMP PREEMPT Wed 
Jun 22 19",
  "python_full_version": "3.9.7",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}



```

**Comment by frostming** [comment]
> I also tried to install git (via apt-get) in the container with no effect.

That should have fixed the issue. Can you provide a Dockerfile to reproduce what you said?

**Comment by SirMartin** [comment]
Sorry, my fault. I was removing unnecessary stuff from the docker file to send it to you, and just found, that I used this command to install it:

`apt-get install git` and didn't install anything. 

I just add it **-y** flag `apt-get install -y git` and it works fine.

Sorry for waste your time.
