### ISSUE TITLE
pdm import Pipfile raise exception: unexpected keyword argument "index"

### ISSUE THREAD

**Issue by Half9000** [pdm-project/pdm#1314]
- [Y] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce
`pdm import Pipfile`

## Actual behavior
```bash
#pdm import Pipfile -v
Traceback (most recent call last):
  File "/usr/local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/root/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/core.py", line 254, in main
    return Core().main(args)
  File "/root/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/core.py", line 187, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/root/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/core.py", line 182, in main
    f(options.project, options)
  File "/root/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/cli/commands/import_cmd.py", line 35, in handle
    do_import(project, options.filename, options.format, options)
  File "/root/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/cli/actions.py", line 718, in do_import
    project_data, settings = FORMATS[key].convert(project, filename, options)
  File "/root/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/formats/pipfile.py", line 61, in convert
    [
  File "/root/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/formats/pipfile.py", line 62, in <listcomp>
    convert_pipfile_requirement(k, req)
  File "/root/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/formats/pipfile.py", line 37, in convert_pipfile_requirement
    return Requirement.from_req_dict(name, req).as_line()
  File "/root/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/models/requirements.py", line 188, in from_req_dict
    return NamedRequirement.create(name=name, **req_dict)
  File "/root/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/models/requirements.py", line 151, in create
    return cls(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'index'
```

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.0.3
Python Interpreter:
  /data/test/.venv/bin/python (3.8)
Project Root:
  /data/test
Project Packages:
  None
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.6",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.4.119-19-0009.1",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Sun Jan 23 23:20:30 CST 2022",
  "python_full_version": "3.8.6",
  "platform_python_implementation": "CPython",
  "python_version": "3.8",
  "sys_platform": "linux"
}
```

## Example Pipfile
```toml
[[source]]
url = "https://mirrors.tencent.com/pypi/simple/"
verify_ssl = true
name = "pypi"

[[source]]
url = "https://mirrors.private.com/repository/pypi/simple"
verify_ssl = true
name = "mirrorsprivatet"

[packages]
requests = "*"
notfound = {version = ">=0.3.11", index = "mirrorsprivatet"}

[requires]
python_version = "3.8"
```

**Comment by frostming** [comment]
Remove that `index` settings and all will be fine.
