### ISSUE TITLE
PDM add torchaudio errored 

### ISSUE THREAD

**Issue by shaozi** [pdm-project/pdm#1321]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

Created an empty project with python 3.10 and did a `pdm add torchaudio`. It failed with pdm.exceptions.CandidateNotFound. But if I run `pdm run pip install torchaudio` it worked.

output:

```
jingshaochen@Jingshaos-MacBook-Pro pdm-test % pdm add -v torchaudio
Adding packages to default dependencies: torchaudio
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   torchaudio
pdm.termui:   python>=3.10
pdm.termui:   Adding requirement torchaudio
pdm.termui:   Adding requirement python>=3.10
pdm.termui: ======== Starting round 0 ========
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
pdm.termui:   Adding requirement torch(from torchaudio 0.12.1)
pdm.termui: Pinning: torchaudio 0.12.1
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
pdm.termui:   Adding requirement typing-extensions(from torch 1.12.1)
pdm.termui: Pinning: torch 1.12.1
pdm.termui: ======== Ending round 2 ========
pdm.termui: ======== Starting round 3 ========
pdm.termui: Pinning: typing-extensions 4.3.0
pdm.termui: ======== Ending round 3 ========
pdm.termui: ======== Starting round 4 ========
pdm.termui: ======== Resolution Result ========
pdm.termui: Stable pins:
pdm.termui:              python None
pdm.termui:          torchaudio 0.12.1
pdm.termui:               torch 1.12.1
pdm.termui:   typing-extensions 4.3.0
🔒 Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
Synchronizing working set with lock file: 1 to add, 0 to update, 0 to remove

  ✖ Install torchaudio 0.12.1 failed
pdm.termui: Error occurs:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/Cellar/pdm/2.1.1/libexec/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 217, in install_candidate
    self.manager.install(can)
  File "/usr/local/Cellar/pdm/2.1.1/libexec/lib/python3.10/site-packages/pdm/installers/manager.py", line 39, in install
    installer(str(prepared.build()), self.environment, prepared.direct_url())
  File "/usr/local/Cellar/pdm/2.1.1/libexec/lib/python3.10/site-packages/pdm/models/candidates.py", line 349, in build
    self.obtain(allow_all=False)
  File "/usr/local/Cellar/pdm/2.1.1/libexec/lib/python3.10/site-packages/pdm/models/candidates.py", line 401, in obtain
    raise CandidateNotFound(
pdm.exceptions.CandidateNotFound: No candidate is found for `torchaudio` that matches the environment or hashes
Retry failed jobs
  ✖ Install torchaudio 0.12.1 failed
pdm.termui: Error occurs:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/Cellar/pdm/2.1.1/libexec/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 217, in install_candidate
    self.manager.install(can)
  File "/usr/local/Cellar/pdm/2.1.1/libexec/lib/python3.10/site-packages/pdm/installers/manager.py", line 39, in install
    installer(str(prepared.build()), self.environment, prepared.direct_url())
  File "/usr/local/Cellar/pdm/2.1.1/libexec/lib/python3.10/site-packages/pdm/models/candidates.py", line 349, in build
    self.obtain(allow_all=False)
  File "/usr/local/Cellar/pdm/2.1.1/libexec/lib/python3.10/site-packages/pdm/models/candidates.py", line 401, in obtain
    raise CandidateNotFound(
pdm.exceptions.CandidateNotFound: No candidate is found for `torchaudio` that matches the environment or hashes
Traceback (most recent call last):
  File "/usr/local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/usr/local/Cellar/pdm/2.1.1/libexec/lib/python3.10/site-packages/pdm/core.py", line 254, in main
    return Core().main(args)
  File "/usr/local/Cellar/pdm/2.1.1/libexec/lib/python3.10/site-packages/pdm/core.py", line 187, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/usr/local/Cellar/pdm/2.1.1/libexec/lib/python3.10/site-packages/pdm/core.py", line 182, in main
    f(options.project, options)
  File "/usr/local/Cellar/pdm/2.1.1/libexec/lib/python3.10/site-packages/pdm/cli/commands/add.py", line 58, in handle
    actions.do_add(
  File "/usr/local/Cellar/pdm/2.1.1/libexec/lib/python3.10/site-packages/pdm/cli/actions.py", line 290, in do_add
    do_sync(
  File "/usr/local/Cellar/pdm/2.1.1/libexec/lib/python3.10/site-packages/pdm/cli/actions.py", line 220, in do_sync
    handler.synchronize()
  File "/usr/local/Cellar/pdm/2.1.1/libexec/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 402, in synchronize
    raise InstallationError("Some package operations are not complete yet")
pdm.exceptions.InstallationError: Some package operations are not complete yet
```

pip actually worked:

```
jingshaochen@Jingshaos-MacBook-Pro pdm-test % pdm run pip install torchaudio
Collecting torchaudio
  Using cached torchaudio-0.12.0-cp310-cp310-macosx_10_15_x86_64.whl (3.1 MB)
Collecting torch==1.12.0
  Using cached torch-1.12.0-cp310-none-macosx_10_9_x86_64.whl (133.6 MB)
Requirement already satisfied: typing-extensions in /usr/local/Cellar/pdm/2.1.1/libexec/lib/python3.10/site-packages (from torch==1.12.0->torchaudio) (4.3.0)
Installing collected packages: torch, torchaudio
  Attempting uninstall: torch
    Found existing installation: torch 1.12.1
    Uninstalling torch-1.12.1:
      Successfully uninstalled torch-1.12.1
Successfully installed torch-1.12.0 torchaudio-0.12.0

[notice] A new release of pip available: 22.1.2 -> 22.2.2
[notice] To update, run: pip install --upgrade pip
```

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.1.1
Python Interpreter:
  /usr/local/Cellar/pdm/2.1.1/libexec/bin/python3.10 (3.10)
Project Root:
  /Users/jingshaochen/Downloads/pdm-test
Project Packages:
  None
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.6",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "21.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:25 PDT 2022; root:xnu-8020.140.41~1/RELEASE_X86_64",
  "python_full_version": "3.10.6",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
You are on MacOS intel, but torchaudio 0.12.1 [doesn't provide an installable wheel for your platform](https://pypi.org/project/torchaudio/0.12.1/#files).
You should manually restrict the version to `<0.12.1`.

`pip` doesn't do cross-version and cross-platform resolution so it finds `0.12.0` correctly.
