### ISSUE TITLE
Missing hash and url metadata information when add package from file server location on first run

### ISSUE THREAD

**Issue by siobz** [pdm-project/pdm#1325]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Install a package (*.whl file)  from a file server with path given in [[tool.pdm.source]] section of  pyproject.toml file.

`pdm add ams-rw-multimeter`
check pdm.lock file
`pdm add peltier `
check pdm.lock file 

## Actual behavior

If a package (*.whl)  is installed from a file server the hash and url are not saved in the [metadata] section of pdm.lock file.

The file server is given in the pyproject.toml file :

```
[[tool.pdm.source]]
url = "//fsrwdata/intrwp/projects/Labor/Libraries/Pyhton_Wheels"
name = "localcache"
type = "index-url"
```

After installing a second package from the same location the hash is added, but the newly installed package has no hash.

```
]
"ams-rw-multimeter 0.1.dev25+g9fda1e8" = [
    {url = "file://fsrwdata/intrwp/projects/Labor/Libraries/Pyhton_Wheels/ams_rw_multimeter-0.1.dev25%2Bg9fda1e8-py3-none-any.whl", hash = "sha256:d1c108701d861a6504ced69d977c6c9a203a99c16c1e6642b97cf95eb495bfdf"},
]
```

The peltier package hash and url are missing.

The behavior for adding a package from pypi.org is correct.
`pdm add test_test_test`

Results in following entry. 

```
"test-test-test 0.2.0" = [
    {url = "https://files.pythonhosted.org/packages/21/e0/8a04b4488fb2b1275a95027a4e5eb1a1574a1a826716a9ea85fb405c3c82/test_test_test-0.2.0.tar.gz", hash = "sha256:103e858a38186e78fc35c12cad43a3854c12981943d02162d4edba030517c5c8"},
    {url = "https://files.pythonhosted.org/packages/2f/e0/f6748b5eaf66b8ecf9c7db7c7b6da23fec52106759d02bf0bcbb8f4c8b06/test_test_test-0.2.0-py3-none-any.whl", hash = "sha256:a2d29c8af44173691e267a0e5230da71fce407923a36f8e09fd00007380853c6"},
]
```
All commands run without any failure.

```
C:\local_git_repos\pdm_test2>pdm add ams_rw_multimeter
Adding packages to default dependencies: ams-rw-multimeter
  Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
Synchronizing working set with lock file: 2 to add, 0 to update, 0 to remove

  v Install ams-rw-ams-rw-visa2ethernet 0.1.dev4+g28fe1cb successful
  v Install ams-rw-multimeter 0.1.dev25+g9fda1e8 successful

  All complete!


C:\local_git_repos\pdm_test2>pdm add peltier
Adding packages to default dependencies: peltier
  Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
Synchronizing working set with lock file: 3 to add, 0 to update, 0 to remove

  v Install typing 3.7.4.3 successful
  v Install peltier 0.1.dev44+gd092481 successful
  v Install ams-helper 0.1.dev45+g13a47bc.d20200813 successful

  All complete!
```

## Expected behavior

I would expect the [metadata] section should be updated on the first run. 

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
C:\local_git_repos\pdm_test2>pdm info && pdm info --env
PDM version:
  2.1.2
Python Interpreter:
  C:\local_git_repos\pdm_test2\.venv\Scripts\python.exe (3.10)
Project Root:
  C:/local_git_repos/pdm_test2
Project Packages:
  None
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.0",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.22000",
  "python_full_version": "3.10.0",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "win32"
}

C:\local_git_repos\pdm_test2>

```

**Comment by frostming** [comment]
Can you try to narrow the root cause by controlling the changed part?

- Try a public `find_links` source, install a then install b
- Try a private `index` source, install a then install b

Also try different a and b packages

BTW, `index-url` isn't a valid type, it must be either `index` or `find_links`

**Comment by siobz** [comment]
I tried `find_links`and `index` in configuration in the pyproject.toml. 

With `find_links` it has the same behavior as with `index-url`. With `index` I get a failure that i not understand and not find anything in Google. 

I only install one package for this test, as the missing meta information was already visible.

You find the logs here:

First test:
```
[[tool.pdm.source]]
url = "//fsrwdata/intrwp/projects/Labor/Libraries/Pyhton_Wheels"
name = "localcache"
type = "find_links"
```

```
C:\local_git_repos\pdm_test5>pdm add ams_rw_multimeter
Adding packages to default dependencies: ams-rw-multimeter
  Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
All packages are synced to date, nothing to do.

  All complete!
```

Second test:

```
[[tool.pdm.source]]
url = "//fsrwdata/intrwp/projects/Labor/Libraries/Pyhton_Wheels"
name = "localcache"
type = "index"
```

```
C:\local_git_repos\pdm_test5>pdm add fluke_1523
Adding packages to default dependencies: fluke-1523
See C:\Users\SB401~1.HER\AppData\Local\Temp\pdm-lock-5un7lomv.log for detailed debug log.
[CandidateNotFound]: Unable to find candidates for fluke-1523. There may exist some issues with the package name or
network condition.
Add '-v' to see the detailed traceback

C:\local_git_repos\pdm_test5>pdm add fluke_1523 -v
Adding packages to default dependencies: fluke-1523
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   ipython>=8.4.0
pdm.termui:   pandas>=1.4.3
pdm.termui:   ams-rw-multimeter>=0.1.dev25+g9fda1e8
pdm.termui:   fluke-1523
pdm.termui:   python>=3.10
pdm.termui:   Adding requirement ipython>=8.4.0
pdm.termui:   Adding requirement pandas>=1.4.3
pdm.termui:   Adding requirement ams-rw-multimeter>=0.1.dev25+g9fda1e8
pdm.termui:   Adding requirement fluke-1523
unearth: Skip https://pypi.org/simple/fluke-1523/ because of Client Error(404): Not Found.
unearth: Skip //fsrwdata/intrwp/projects/Labor/Libraries/Pyhton_Wheels/fluke-1523/ for not being trusted, please add it to `trusted_hosts` list
Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\users\s.herz\.local\bin\pdm.exe\__main__.py", line 7, in <module>
  File "C:\Users\S.Herz\.local\pipx\venvs\pdm\lib\site-packages\pdm\core.py", line 254, in main
    return Core().main(args)
  File "C:\Users\S.Herz\.local\pipx\venvs\pdm\lib\site-packages\pdm\core.py", line 187, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "C:\Users\S.Herz\.local\pipx\venvs\pdm\lib\site-packages\pdm\core.py", line 182, in main
    f(options.project, options)
  File "C:\Users\S.Herz\.local\pipx\venvs\pdm\lib\site-packages\pdm\cli\commands\add.py", line 58, in handle
    actions.do_add(
  File "C:\Users\S.Herz\.local\pipx\venvs\pdm\lib\site-packages\pdm\cli\actions.py", line 279, in do_add
    resolved = do_lock(
  File "C:\Users\S.Herz\.local\pipx\venvs\pdm\lib\site-packages\pdm\cli\actions.py", line 101, in do_lock
    mapping, dependencies = resolve(
  File "C:\Users\S.Herz\.local\pipx\venvs\pdm\lib\site-packages\pdm\resolver\core.py", line 30, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "C:\Users\S.Herz\.local\pipx\venvs\pdm\lib\site-packages\resolvelib\resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\S.Herz\.local\pipx\venvs\pdm\lib\site-packages\resolvelib\resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "C:\Users\S.Herz\.local\pipx\venvs\pdm\lib\site-packages\resolvelib\resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "C:\Users\S.Herz\.local\pipx\venvs\pdm\lib\site-packages\resolvelib\structs.py", line 126, in __bool__
    next(self._factory())
  File "C:\Users\S.Herz\.local\pipx\venvs\pdm\lib\site-packages\pdm\resolver\providers.py", line 252, in matches_gen
    yield from super_find()
  File "C:\Users\S.Herz\.local\pipx\venvs\pdm\lib\site-packages\pdm\resolver\providers.py", line 146, in matches_gen
    candidates = self._find_candidates(reqs[0])
  File "C:\Users\S.Herz\.local\pipx\venvs\pdm\lib\site-packages\pdm\resolver\providers.py", line 128, in _find_candidates
    return self.repository.find_candidates(
  File "C:\Users\S.Herz\.local\pipx\venvs\pdm\lib\site-packages\pdm\models\repositories.py", line 139, in find_candidates
    cans = list(self._find_candidates(requirement))
  File "C:\Users\S.Herz\.local\pipx\venvs\pdm\lib\site-packages\pdm\models\repositories.py", line 327, in _find_candidates
    raise CandidateNotFound(
pdm.exceptions.CandidateNotFound: Unable to find candidates for fluke-1523. There may exist some issues with the package name or network condition.
```

**Comment by siobz** [comment]
I was able to solve the error in the second test by giving the version number (following a tip from a colleague). 

```
C:\local_git_repos\pdm_test5>pdm add fluke_1523==0.1.dev3+g3990b09
Adding packages to default dependencies: fluke-1523==0.1.dev3+g3990b09
  Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
All packages are synced to date, nothing to do.

  All complete!
```

**Comment by franzhaas** [comment]
I tried to reproduce the issue.

I started with pyproject.toml and pdm.toml, but no lock file and no __pypackages__. Using wheels in a directory, similar to what siobz does.

I execute
>>> pdm lock
a pdm.lock file, with *missing* paths and hashes is created
I execute 
>>> pdm lock --refresh
a pdm.lock file *including* paths and hashes is created
I execute
>>> pdm sync
i get a __pypackages__ directory

I use pdm 2.1.2

@siobz can you reproduce my observation?

**Comment by siobz** [comment]
I can confirm that a in my procedure when I run `pdm lock --refresh` command after installing package **a**, adds the missing metadata in the lock file.

**Comment by franzhaas** [comment]
I modified the function do_lock in the file actions.py.:
```
        else:
            data = format_lockfile(project, mapping, dependencies)
            project.write_lockfile(data, write=not dry_run)
            hooks.try_emit("post_lock", resolution=mapping, dry_run=dry_run)
            if len(data["metadata"]["files"].items()) == len(data["package"]):
                ui.echo(f"{termui.Emoji.LOCK} Lock successful")
            else:
                ui.echo(f"{termui.Emoji.LOCK} Lock partly successful... relocking")
                mapping = do_lock( project, strategy, tracked_names, requirements, dry_run, True, hooks)
    return mapping
```
And this solves our issue. @frostming  I did not provide a PR with this as I do not think that this is a good solution. I just hope that it helps in finding a good solution, or helps in the meantime...

**Comment by frostming** [comment]
I used a local served file directory and can't reproduce the issue, can you complete the URL with the scheme and try again?

**Comment by franzhaas** [comment]
@frostming yes, this works for me. Have you tried without http? accessing the file system directly?

**Comment by frostming** [comment]
> @frostming yes, this works for me. Maybe it is related to file system vs http access?

Yes, `file://` can reproduce it

**Comment by franzhaas** [comment]
Thanks a lot!
