### ISSUE TITLE
pyscipopt  install failed

### ISSUE THREAD

**Issue by Euraxluo** [pdm-project/pdm#1326]
## Environment Information
WINDOWS

```bash
# Paste the output of `pdm info && pdm info --env` below:
pdm add pyscipopt -v
```

output:
```pytb
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
pdm.termui:   Adding requirement wheel(from pyscipopt 4.2.0)
pdm.termui: Pinning: pyscipopt 4.2.0
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
pdm.termui: Pinning: wheel 0.37.1
pdm.termui: ======== Ending round 2 ========
pdm.termui: ======== Starting round 3 ========
pdm.termui: ======== Resolution Result ========
pdm.termui: Stable pins:
pdm.termui:      python None
pdm.termui:   pyscipopt 4.2.0
pdm.termui:       wheel 0.37.1
🔒 Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
Synchronizing working set with lock file: 1 to add, 0 to update, 0 to remove

unearth: Downloading <Link https://files.pythonhosted.org/packages/1c/0a/47d81ada5d00285ba1f7ab1443624e7cdce7a1e620510129e832eaa9b789/PySCIPOpt-4.2.0.tar.gz (from None)> to C:\Users\Administrator\AppData\Local\Temp\pdm-download-5s43v40e\PySCIPOpt-4.2.0.tar.gz
pdm.termui: Preparing isolated env for PEP 517 build...
pdm.termui: Saving wheel to cache: <Link https://files.pythonhosted.org/packages/1c/0a/47d81ada5d00285ba1f7ab1443624e7cdce7a1e620510129e832eaa9b789/PySCIPOpt-4.2.0.tar.gz (from None)>
pdm.termui: Running PEP 517 backend to build a wheel for <Link https://files.pythonhosted.org/packages/1c/0a/47d81ada5d00285ba1f7ab1443624e7cdce7a1e620510129e832eaa9b789/PySCIPOpt-4.2.0.tar.gz (from None)>
pdm.termui: Using pip 22.2.2 from C:\ProgramData\Anaconda3\lib\site-packages\pip (python 3.9)
pdm.termui: Looking in indexes: https://pypi.org/simple, https://pypi.tuna.tsinghua.edu.cn/simple
pdm.termui: Collecting wheel
pdm.termui:   Using cached https://pypi.tuna.tsinghua.edu.cn/packages/27/d6/003e593296a85fd6ed616ed962795b2f87709c3eee2bca4f6d0fe55c6d00/wheel-0.37.1-py2.py3-none-any.whl (35 kB)
pdm.termui: Collecting setuptools>=40.8.0
pdm.termui:   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/18/1e/7cd4bf0d0c4e109595b5e69621f72c4e01079c533ccb94003dfe361c62ea/setuptools-65.1.0-py3-none-any.whl (1.2 MB)
pdm.termui:      ---------------------------------------- 1.2/1.2 MB 841.3 kB/s eta 0:00:00
pdm.termui: Installing collected packages: wheel, setuptools
pdm.termui:   Creating C:\Users\Administrator\AppData\Local\Temp\pdm-build-env-6tk869yr-shared\Scripts
pdm.termui: ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pdm.termui: spyder 5.1.5 requires pyqt5<5.13, which is not installed.
pdm.termui: spyder 5.1.5 requires pyqtwebengine<5.13, which is not installed.
pdm.termui: conda-repo-cli 1.0.4 requires pathlib, which is not installed.
pdm.termui: anaconda-project 0.10.1 requires ruamel-yaml, which is not installed.
pdm.termui: numba 0.54.1 requires numpy<1.21,>=1.17, but you have numpy 1.22.3 which is incompatible.
pdm.termui: astroid 2.6.6 requires wrapt<1.13,>=1.11, but you have wrapt 1.14.0 which is incompatible.
pdm.termui: Successfully installed setuptools-65.1.0 wheel-0.37.1
pdm.termui: Assuming that SCIP is installed globally, because SCIPOPTDIR is undefined.
pdm.termui: 
pdm.termui: running egg_info
pdm.termui: writing PySCIPOpt.egg-info\PKG-INFO
pdm.termui: writing dependency_links to PySCIPOpt.egg-info\dependency_links.txt
pdm.termui: writing requirements to PySCIPOpt.egg-info\requires.txt
pdm.termui: writing top-level names to PySCIPOpt.egg-info\top_level.txt
pdm.termui: reading manifest file 'PySCIPOpt.egg-info\SOURCES.txt'
pdm.termui: adding license file 'LICENSE'
pdm.termui: writing manifest file 'PySCIPOpt.egg-info\SOURCES.txt'
pdm.termui: Assuming that SCIP is installed globally, because SCIPOPTDIR is undefined.
pdm.termui: 
pdm.termui: running bdist_wheel
pdm.termui: running build
pdm.termui: running build_py
pdm.termui: creating build
pdm.termui: creating build\lib.win-amd64-cpython-39
pdm.termui: creating build\lib.win-amd64-cpython-39\pyscipopt
pdm.termui: copying src\pyscipopt\Multidict.py -> build\lib.win-amd64-cpython-39\pyscipopt
pdm.termui: copying src\pyscipopt\__init__.py -> build\lib.win-amd64-cpython-39\pyscipopt
pdm.termui: copying src\pyscipopt\scip.pyx -> build\lib.win-amd64-cpython-39\pyscipopt
pdm.termui: copying src\pyscipopt\scip.pxd -> build\lib.win-amd64-cpython-39\pyscipopt
pdm.termui: copying src\pyscipopt\benders.pxi -> build\lib.win-amd64-cpython-39\pyscipopt
pdm.termui: copying src\pyscipopt\benderscut.pxi -> build\lib.win-amd64-cpython-39\pyscipopt
pdm.termui: copying src\pyscipopt\branchrule.pxi -> build\lib.win-amd64-cpython-39\pyscipopt
pdm.termui: copying src\pyscipopt\conshdlr.pxi -> build\lib.win-amd64-cpython-39\pyscipopt
pdm.termui: copying src\pyscipopt\cutsel.pxi -> build\lib.win-amd64-cpython-39\pyscipopt
pdm.termui: copying src\pyscipopt\event.pxi -> build\lib.win-amd64-cpython-39\pyscipopt
pdm.termui: copying src\pyscipopt\expr.pxi -> build\lib.win-amd64-cpython-39\pyscipopt
pdm.termui: copying src\pyscipopt\heuristic.pxi -> build\lib.win-amd64-cpython-39\pyscipopt
pdm.termui: copying src\pyscipopt\lp.pxi -> build\lib.win-amd64-cpython-39\pyscipopt
pdm.termui: copying src\pyscipopt\nodesel.pxi -> build\lib.win-amd64-cpython-39\pyscipopt
pdm.termui: copying src\pyscipopt\presol.pxi -> build\lib.win-amd64-cpython-39\pyscipopt
pdm.termui: copying src\pyscipopt\pricer.pxi -> build\lib.win-amd64-cpython-39\pyscipopt
pdm.termui: copying src\pyscipopt\propagator.pxi -> build\lib.win-amd64-cpython-39\pyscipopt
pdm.termui: copying src\pyscipopt\reader.pxi -> build\lib.win-amd64-cpython-39\pyscipopt
pdm.termui: copying src\pyscipopt\relax.pxi -> build\lib.win-amd64-cpython-39\pyscipopt
pdm.termui: copying src\pyscipopt\sepa.pxi -> build\lib.win-amd64-cpython-39\pyscipopt
pdm.termui: running build_ext
pdm.termui: building 'pyscipopt.scip' extension
pdm.termui: creating build\temp.win-amd64-cpython-39
pdm.termui: creating build\temp.win-amd64-cpython-39\Release
pdm.termui: creating build\temp.win-amd64-cpython-39\Release\src
pdm.termui: creating build\temp.win-amd64-cpython-39\Release\src\pyscipopt
pdm.termui: "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -I. -IC:\ProgramData\Anaconda3\include -IC:\ProgramData\Anaconda3\Include "-IC:\Progr
am Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86
)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" /Tcsrc\pyscipopt\scip.c /Fobuild\temp.win-amd64-cpython-39\Release\src\pyscipopt\scip.obj
pdm.termui: scip.c
pdm.termui: src\pyscipopt\scip.c(710): fatal error C1083: �޷��򿪰����ļ�: ��scip/scip.h��: No such fil e or directory
pdm.termui: error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  ✖ Install pyscipopt 4.2.0 failed
pdm.termui: Error occurs: 
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\Project\quantum-vrp\.venv\lib\site-packages\pdm\installers\synchronizers.py", line 217, in install_candidate
    self.manager.install(can)
  File "D:\Project\quantum-vrp\.venv\lib\site-packages\pdm\installers\manager.py", line 39, in install
    installer(str(prepared.build()), self.environment, prepared.direct_url())
  File "D:\Project\quantum-vrp\.venv\lib\site-packages\pdm\models\candidates.py", line 374, in build
    builder.build(build_dir, metadata_directory=self._metadata_dir)
  File "D:\Project\quantum-vrp\.venv\lib\site-packages\pdm\builders\wheel.py", line 28, in build
    filename = self._hook.build_wheel(out_dir, config_settings, metadata_directory)
  File "D:\Project\quantum-vrp\.venv\lib\site-packages\pep517\wrappers.py", line 209, in build_wheel
    return self._call_hook('build_wheel', {
  File "D:\Project\quantum-vrp\.venv\lib\site-packages\pep517\wrappers.py", line 309, in _call_hook
    self._subprocess_runner(
  File "D:\Project\quantum-vrp\.venv\lib\site-packages\pdm\builders\base.py", line 245, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
  File "D:\Project\quantum-vrp\.venv\lib\site-packages\pdm\builders\base.py", line 84, in log_subprocessor
    raise BuildError(
pdm.exceptions.BuildError: Call command ['C:/ProgramData/Anaconda3/python.exe', 'D:\\Project\\quantum-vrp\\.venv\\lib\\site-packages\\pep517\\in_process\\_in_process.py', 'build_wheel', 'C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmpmp6n2a17'] return non-zero status(1). Make sure the package is PEP 517-compliant, or you can add `--no-isolation` to the command.
Retry failed jobs
pdm.termui: Preparing isolated env for PEP 517 build...
pdm.termui: Saving wheel to cache: <Link https://files.pythonhosted.org/packages/1c/0a/47d81ada5d00285ba1f7ab1443624e7cdce7a1e620510129e832eaa9b789/PySCIPOpt-4.2.0.tar.gz (from None)>
pdm.termui: Running PEP 517 backend to build a wheel for <Link https://files.pythonhosted.org/packages/1c/0a/47d81ada5d00285ba1f7ab1443624e7cdce7a1e620510129e832eaa9b789/PySCIPOpt-4.2.0.tar.gz (from None)>
pdm.termui: Assuming that SCIP is installed globally, because SCIPOPTDIR is undefined.
pdm.termui: 
pdm.termui: running egg_info
pdm.termui: writing PySCIPOpt.egg-info\PKG-INFO
pdm.termui: writing dependency_links to PySCIPOpt.egg-info\dependency_links.txt
pdm.termui: writing requirements to PySCIPOpt.egg-info\requires.txt
pdm.termui: writing top-level names to PySCIPOpt.egg-info\top_level.txt
pdm.termui: reading manifest file 'PySCIPOpt.egg-info\SOURCES.txt'
pdm.termui: adding license file 'LICENSE'
pdm.termui: writing manifest file 'PySCIPOpt.egg-info\SOURCES.txt'
pdm.termui: Assuming that SCIP is installed globally, because SCIPOPTDIR is undefined.
pdm.termui: 
pdm.termui: running bdist_wheel
pdm.termui: running build
pdm.termui: running build_py
pdm.termui: running build_ext
pdm.termui: building 'pyscipopt.scip' extension
pdm.termui: "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -I. -IC:\ProgramData\Anaconda3\include -IC:\ProgramData\Anaconda3\Include "-IC:\Progr
am Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86
)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" /Tcsrc\pyscipopt\scip.c /Fobuild\temp.win-amd64-cpython-39\Release\src\pyscipopt\scip.obj
pdm.termui: scip.c
pdm.termui: src\pyscipopt\scip.c(710): fatal error C1083: �޷��򿪰����ļ�: ��scip/scip.h��: No such fil e or directory
pdm.termui: error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  ✖ Install pyscipopt 4.2.0 failed
pdm.termui: Error occurs: 
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\Project\quantum-vrp\.venv\lib\site-packages\pdm\installers\synchronizers.py", line 217, in install_candidate
    self.manager.install(can)
  File "D:\Project\quantum-vrp\.venv\lib\site-packages\pdm\installers\manager.py", line 39, in install
    installer(str(prepared.build()), self.environment, prepared.direct_url())
  File "D:\Project\quantum-vrp\.venv\lib\site-packages\pdm\models\candidates.py", line 374, in build
    builder.build(build_dir, metadata_directory=self._metadata_dir)
  File "D:\Project\quantum-vrp\.venv\lib\site-packages\pdm\builders\wheel.py", line 28, in build
    filename = self._hook.build_wheel(out_dir, config_settings, metadata_directory)
  File "D:\Project\quantum-vrp\.venv\lib\site-packages\pep517\wrappers.py", line 209, in build_wheel
    return self._call_hook('build_wheel', {
  File "D:\Project\quantum-vrp\.venv\lib\site-packages\pep517\wrappers.py", line 309, in _call_hook
    self._subprocess_runner(
  File "D:\Project\quantum-vrp\.venv\lib\site-packages\pdm\builders\base.py", line 245, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
  File "D:\Project\quantum-vrp\.venv\lib\site-packages\pdm\builders\base.py", line 84, in log_subprocessor
    raise BuildError(
pdm.exceptions.BuildError: Call command ['C:/ProgramData/Anaconda3/python.exe', 'D:\\Project\\quantum-vrp\\.venv\\lib\\site-packages\\pep517\\in_process\\_in_process.py', 'build_wheel', 'C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmps4d8ykcj'] return non-zero status(1). Make sure the package is PEP 517-compliant, or you can add `--no-isolation` to the command.
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Project\quantum-vrp\.venv\Scripts\pdm.exe\__main__.py", line 7, in <module>
  File "D:\Project\quantum-vrp\.venv\lib\site-packages\pdm\core.py", line 254, in main
    return Core().main(args)
  File "D:\Project\quantum-vrp\.venv\lib\site-packages\pdm\core.py", line 187, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "D:\Project\quantum-vrp\.venv\lib\site-packages\pdm\core.py", line 182, in main
    f(options.project, options)
  File "D:\Project\quantum-vrp\.venv\lib\site-packages\pdm\cli\commands\add.py", line 58, in handle
    actions.do_add(
  File "D:\Project\quantum-vrp\.venv\lib\site-packages\pdm\cli\actions.py", line 292, in do_add
    do_sync(
  File "D:\Project\quantum-vrp\.venv\lib\site-packages\pdm\cli\actions.py", line 220, in do_sync
    handler.synchronize()
  File "D:\Project\quantum-vrp\.venv\lib\site-packages\pdm\installers\synchronizers.py", line 402, in synchronize
    raise InstallationError("Some package operations are not complete yet")
pdm.exceptions.InstallationError: Some package operations are not complete yet  
```

**Comment by pawamoy** [comment]
Did you follow the install instructions? https://github.com/scipopt/PySCIPOpt/blob/master/INSTALL.md#installation-from-pypi

**Comment by Euraxluo** [comment]
ok but when i use `conda install -c conda-force pyscipopt`，that is success

**Comment by Euraxluo** [comment]
I'm sure it's not available


I will create a dependent manager project that uses Conda installation dependencies

docker:python3.9 
```
 /root/.local/bin/pdm add -G opt pyscipopt -v
Adding packages to opt dependencies: pyscipopt
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   pyscipopt
pdm.termui:   python>=3.9
pdm.termui:   Adding requirement pyscipopt
pdm.termui:   Adding requirement python>=3.9
pdm.termui: ======== Starting round 0 ========
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
pdm.termui:   Adding requirement wheel(from pyscipopt 4.2.0)
pdm.termui: Pinning: pyscipopt 4.2.0
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
pdm.termui: Pinning: wheel 0.37.1
pdm.termui: ======== Ending round 2 ========
pdm.termui: ======== Starting round 3 ========
pdm.termui: ======== Resolution Result ========
pdm.termui: Stable pins:
pdm.termui:      python None
pdm.termui:   pyscipopt 4.2.0
pdm.termui:       wheel 0.37.1
🔒 Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
Synchronizing working set with lock file: 1 to add, 0 to update, 0 to remove

unearth: Downloading <Link https://files.pythonhosted.org/packages/1c/0a/47d81ada5d00285ba1f7ab1443624e7cdce7a1e620510129e832eaa9b789/PySCIPOpt-4.2.0.tar.gz (from None)> to /tmp/pdm-download-swwta_ju/PySCIPOpt-4.2.0.tar.gz
pdm.termui: Preparing isolated env for PEP 517 build...
pdm.termui: Saving wheel to cache: <Link https://files.pythonhosted.org/packages/1c/0a/47d81ada5d00285ba1f7ab1443624e7cdce7a1e620510129e832eaa9b789/PySCIPOpt-4.2.0.tar.gz (from None)>
pdm.termui: Running PEP 517 backend to build a wheel for <Link https://files.pythonhosted.org/packages/1c/0a/47d81ada5d00285ba1f7ab1443624e7cdce7a1e620510129e832eaa9b789/PySCIPOpt-4.2.0.tar.gz (from None)>
pdm.termui: Using pip 22.2.2 from /root/.local/share/pdm/venv/lib/python3.9/site-packages/pip (python 3.9)
pdm.termui: Collecting setuptools>=40.8.0
pdm.termui:   Using cached setuptools-65.1.0-py3-none-any.whl (1.2 MB)
pdm.termui: Collecting wheel
pdm.termui:   Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
pdm.termui: Installing collected packages: wheel, setuptools
pdm.termui:   Creating /tmp/pdm-build-env-9imqx3rq-shared/bin
pdm.termui:   changing mode of /tmp/pdm-build-env-9imqx3rq-shared/bin/wheel to 755
pdm.termui: Successfully installed setuptools-65.1.0 wheel-0.37.1
pdm.termui: Assuming that SCIP is installed globally, because SCIPOPTDIR is undefined.
pdm.termui:
pdm.termui: running egg_info
pdm.termui: writing PySCIPOpt.egg-info/PKG-INFO
pdm.termui: writing dependency_links to PySCIPOpt.egg-info/dependency_links.txt
pdm.termui: writing requirements to PySCIPOpt.egg-info/requires.txt
pdm.termui: writing top-level names to PySCIPOpt.egg-info/top_level.txt
pdm.termui: reading manifest file 'PySCIPOpt.egg-info/SOURCES.txt'
pdm.termui: adding license file 'LICENSE'
pdm.termui: writing manifest file 'PySCIPOpt.egg-info/SOURCES.txt'
pdm.termui: Assuming that SCIP is installed globally, because SCIPOPTDIR is undefined.
pdm.termui:
pdm.termui: running bdist_wheel
pdm.termui: running build
pdm.termui: running build_py
pdm.termui: creating build
pdm.termui: creating build/lib.linux-x86_64-cpython-39
pdm.termui: creating build/lib.linux-x86_64-cpython-39/pyscipopt
pdm.termui: copying src/pyscipopt/Multidict.py -> build/lib.linux-x86_64-cpython-39/pyscipopt
pdm.termui: copying src/pyscipopt/__init__.py -> build/lib.linux-x86_64-cpython-39/pyscipopt
pdm.termui: copying src/pyscipopt/scip.pyx -> build/lib.linux-x86_64-cpython-39/pyscipopt
pdm.termui: copying src/pyscipopt/scip.pxd -> build/lib.linux-x86_64-cpython-39/pyscipopt
pdm.termui: copying src/pyscipopt/conshdlr.pxi -> build/lib.linux-x86_64-cpython-39/pyscipopt
pdm.termui: copying src/pyscipopt/benderscut.pxi -> build/lib.linux-x86_64-cpython-39/pyscipopt
pdm.termui: copying src/pyscipopt/expr.pxi -> build/lib.linux-x86_64-cpython-39/pyscipopt
pdm.termui: copying src/pyscipopt/reader.pxi -> build/lib.linux-x86_64-cpython-39/pyscipopt
pdm.termui: copying src/pyscipopt/propagator.pxi -> build/lib.linux-x86_64-cpython-39/pyscipopt
pdm.termui: copying src/pyscipopt/branchrule.pxi -> build/lib.linux-x86_64-cpython-39/pyscipopt
pdm.termui: copying src/pyscipopt/presol.pxi -> build/lib.linux-x86_64-cpython-39/pyscipopt
pdm.termui: copying src/pyscipopt/benders.pxi -> build/lib.linux-x86_64-cpython-39/pyscipopt
pdm.termui: copying src/pyscipopt/event.pxi -> build/lib.linux-x86_64-cpython-39/pyscipopt
pdm.termui: copying src/pyscipopt/lp.pxi -> build/lib.linux-x86_64-cpython-39/pyscipopt
pdm.termui: copying src/pyscipopt/pricer.pxi -> build/lib.linux-x86_64-cpython-39/pyscipopt
pdm.termui: copying src/pyscipopt/cutsel.pxi -> build/lib.linux-x86_64-cpython-39/pyscipopt
pdm.termui: copying src/pyscipopt/relax.pxi -> build/lib.linux-x86_64-cpython-39/pyscipopt
pdm.termui: copying src/pyscipopt/nodesel.pxi -> build/lib.linux-x86_64-cpython-39/pyscipopt
pdm.termui: copying src/pyscipopt/sepa.pxi -> build/lib.linux-x86_64-cpython-39/pyscipopt
pdm.termui: copying src/pyscipopt/heuristic.pxi -> build/lib.linux-x86_64-cpython-39/pyscipopt
pdm.termui: running build_ext
pdm.termui: building 'pyscipopt.scip' extension
pdm.termui: creating build/temp.linux-x86_64-cpython-39
pdm.termui: creating build/temp.linux-x86_64-cpython-39/src
pdm.termui: creating build/temp.linux-x86_64-cpython-39/src/pyscipopt
pdm.termui: gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I. -I/root/.local/share/pdm/venv/include -I/usr/local/include/python3.9 -c src/pyscipopt/scip.c -o build/temp.linux-x86_64-cpython-39/src/pyscipopt/scip.o
pdm.termui: src/pyscipopt/scip.c:710:10: fatal error: scip/scip.h: No such file or directory
pdm.termui:   710 | #include "scip/scip.h"
pdm.termui:       |          ^~~~~~~~~~~~~
pdm.termui: compilation terminated.
pdm.termui: error: command '/usr/bin/gcc' failed with exit code 1
  ✖ Install pyscipopt 4.2.0 failed
pdm.termui: Error occurs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 217, in install_candidate
    self.manager.install(can)
  File "/root/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/manager.py", line 39, in install
    installer(str(prepared.build()), self.environment, prepared.direct_url())
  File "/root/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/models/candidates.py", line 374, in build
    builder.build(build_dir, metadata_directory=self._metadata_dir)
  File "/root/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/builders/wheel.py", line 28, in build
    filename = self._hook.build_wheel(out_dir, config_settings, metadata_directory)
  File "/root/.local/share/pdm/venv/lib/python3.9/site-packages/pep517/wrappers.py", line 209, in build_wheel
    return self._call_hook('build_wheel', {
  File "/root/.local/share/pdm/venv/lib/python3.9/site-packages/pep517/wrappers.py", line 309, in _call_hook
    self._subprocess_runner(
  File "/root/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/builders/base.py", line 245, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
  File "/root/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/builders/base.py", line 84, in log_subprocessor
    raise BuildError(
pdm.exceptions.BuildError: Call command ['/root/.local/share/pdm/venv/bin/python', '/root/.local/share/pdm/venv/lib/python3.9/site-packages/pep517/in_process/_in_process.py', 'build_wheel', '/tmp/tmpzziyx_i8'] return non-zero status(1). Make sure the package is PEP 517-compliant, or you can add `--no-isolation` to the command.
Retry failed jobs
pdm.termui: Preparing isolated env for PEP 517 build...
pdm.termui: Saving wheel to cache: <Link https://files.pythonhosted.org/packages/1c/0a/47d81ada5d00285ba1f7ab1443624e7cdce7a1e620510129e832eaa9b789/PySCIPOpt-4.2.0.tar.gz (from None)>
pdm.termui: Running PEP 517 backend to build a wheel for <Link https://files.pythonhosted.org/packages/1c/0a/47d81ada5d00285ba1f7ab1443624e7cdce7a1e620510129e832eaa9b789/PySCIPOpt-4.2.0.tar.gz (from None)>
pdm.termui: Assuming that SCIP is installed globally, because SCIPOPTDIR is undefined.
pdm.termui:
pdm.termui: running egg_info
pdm.termui: writing PySCIPOpt.egg-info/PKG-INFO
pdm.termui: writing dependency_links to PySCIPOpt.egg-info/dependency_links.txt
pdm.termui: writing requirements to PySCIPOpt.egg-info/requires.txt
pdm.termui: writing top-level names to PySCIPOpt.egg-info/top_level.txt
pdm.termui: reading manifest file 'PySCIPOpt.egg-info/SOURCES.txt'
pdm.termui: adding license file 'LICENSE'
pdm.termui: writing manifest file 'PySCIPOpt.egg-info/SOURCES.txt'
pdm.termui: Assuming that SCIP is installed globally, because SCIPOPTDIR is undefined.
pdm.termui:
pdm.termui: running bdist_wheel
pdm.termui: running build
pdm.termui: running build_py
pdm.termui: running build_ext
pdm.termui: building 'pyscipopt.scip' extension
pdm.termui: gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I. -I/root/.local/share/pdm/venv/include -I/usr/local/include/python3.9 -c src/pyscipopt/scip.c -o build/temp.linux-x86_64-cpython-39/src/pyscipopt/scip.o
pdm.termui: src/pyscipopt/scip.c:710:10: fatal error: scip/scip.h: No such file or directory
pdm.termui:   710 | #include "scip/scip.h"
pdm.termui:       |          ^~~~~~~~~~~~~
pdm.termui: compilation terminated.
pdm.termui: error: command '/usr/bin/gcc' failed with exit code 1
  ✖ Install pyscipopt 4.2.0 failed
pdm.termui: Error occurs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 217, in install_candidate
    self.manager.install(can)
  File "/root/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/manager.py", line 39, in install
    installer(str(prepared.build()), self.environment, prepared.direct_url())
  File "/root/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/models/candidates.py", line 374, in build
    builder.build(build_dir, metadata_directory=self._metadata_dir)
  File "/root/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/builders/wheel.py", line 28, in build
    filename = self._hook.build_wheel(out_dir, config_settings, metadata_directory)
  File "/root/.local/share/pdm/venv/lib/python3.9/site-packages/pep517/wrappers.py", line 209, in build_wheel
    return self._call_hook('build_wheel', {
  File "/root/.local/share/pdm/venv/lib/python3.9/site-packages/pep517/wrappers.py", line 309, in _call_hook
    self._subprocess_runner(
  File "/root/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/builders/base.py", line 245, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
  File "/root/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/builders/base.py", line 84, in log_subprocessor
    raise BuildError(
pdm.exceptions.BuildError: Call command ['/root/.local/share/pdm/venv/bin/python', '/root/.local/share/pdm/venv/lib/python3.9/site-packages/pep517/in_process/_in_process.py', 'build_wheel', '/tmp/tmpzpfqt4e2'] return non-zero status(1). Make sure the package is PEP 517-compliant, or you can add `--no-isolation` to the command.
Traceback (most recent call last):
  File "/root/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/root/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/core.py", line 254, in main
    return Core().main(args)
  File "/root/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/core.py", line 187, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/root/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/core.py", line 182, in main
    f(options.project, options)
  File "/root/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/cli/commands/add.py", line 58, in handle
    actions.do_add(
  File "/root/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/cli/actions.py", line 292, in do_add
    do_sync(
  File "/root/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/cli/actions.py", line 220, in do_sync
    handler.synchronize()
  File "/root/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 402, in synchronize
    raise InstallationError("Some package operations are not complete yet")
pdm.exceptions.InstallationError: Some package operations are not complete yet
```

**Comment by pawamoy** [comment]
What I meant is: did you actually install the requirements? https://github.com/scipopt/PySCIPOpt/blob/master/INSTALL.md#requirements
If the SCIP Optimization Suite is not install, you won't be able to compile pyscipopt.
