### ISSUE TITLE
Possible pdm dependency downgrading bug

### ISSUE THREAD

**Issue by warsaw** [pdm-project/pdm#1335]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

I'm trying to land a [PR for flufl.i18n](https://gitlab.com/warsaw/flufl.i18n/-/merge_requests/30) but the `tox -e docs` [environment is failing](https://gitlab.com/warsaw/flufl.i18n/-/jobs/2918626040).  I don't know for sure why this is happening, but I do see a strange downgrading of `certifi` in the verbose output, which is the first package to fail.  All the other tox environments pass no problem.  On a local development macOS, everything succeeds, but the failure in my CI is in a Docker [image we build](https://gitlab.com/python-devs/ci-images/container_registry/48153) with all the active versions of Python (based on Ubuntu 20.04).   I can't tell if the problem is the Docker image, PDM, my PR's lock file or something else.  Apologies in advance if this is not PDM's problem.

## Steps to reproduce

```bash
$ docker pull registry.gitlab.com/python-devs/ci-images:active
$ docker run -it registry.gitlab.com/python-devs/ci-images:active
# inside the docker image
$ git clone https://gitlab.com/warsaw/flufl.i18n.git
$ cd flufl.i18n
$ git switch cleanup
$ tox -e docs
```

Attached is the log file.  Note that running `tox` from the `main` branch instead of `cleanup` and everything works fine.

## Actual behavior

Crash downgrading `certify` during `tox -e docs`

## Expected behavior

`tox -e docs` passes on the `cleanup` branch just like on the `main` branch.

## Environment Information

```bash
runner@eff525ed0b3b:~/flufl.i18n$ .tox/docs/bin/pdm info && .tox/docs/bin/pdm info --env
Traceback (most recent call last):
  File "/home/runner/flufl.i18n/.tox/docs/bin/pdm", line 5, in <module>
    from pdm.core import main
  File "/home/runner/flufl.i18n/.tox/docs/lib/python3.10/site-packages/pdm/__init__.py", line 7, in <module>
    from pdm.cli.commands.base import BaseCommand as _BaseCommand
  File "/home/runner/flufl.i18n/.tox/docs/lib/python3.10/site-packages/pdm/cli/commands/base.py", line 6, in <module>
    from pdm.cli.utils import PdmFormatter
  File "/home/runner/flufl.i18n/.tox/docs/lib/python3.10/site-packages/pdm/cli/utils.py", line 31, in <module>
    from pdm.formats import FORMATS
  File "/home/runner/flufl.i18n/.tox/docs/lib/python3.10/site-packages/pdm/formats/__init__.py", line 8, in <module>
    from pdm.formats import flit, pipfile, poetry, requirements, setup_py
  File "/home/runner/flufl.i18n/.tox/docs/lib/python3.10/site-packages/pdm/formats/flit.py", line 17, in <module>
    from pdm.project import Project
  File "/home/runner/flufl.i18n/.tox/docs/lib/python3.10/site-packages/pdm/project/__init__.py", line 2, in <module>
    from pdm.project.core import Project  # noqa
  File "/home/runner/flufl.i18n/.tox/docs/lib/python3.10/site-packages/pdm/project/core.py", line 21, in <module>
    from pdm.models.caches import CandidateInfoCache, HashCache, WheelCache
  File "/home/runner/flufl.i18n/.tox/docs/lib/python3.10/site-packages/pdm/models/caches.py", line 11, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

However, if I run `tox -e docs --notest` and then the above commands I get:

```bash
runner@1726a1d1e355:~/flufl.i18n$ .tox/docs/bin/pdm info && .tox/docs/bin/pdm info --env
python.use_venv is on, creating a virtualenv for this project...
Virtualenv is created successfully at /home/runner/flufl.i18n/.venv
PDM version:
  2.1.2
Python Interpreter:
  /home/runner/flufl.i18n/.venv/bin/python (3.12)
Project Root:
  /home/runner/flufl.i18n
Project Packages:
  None
{
  "implementation_name": "cpython",
  "implementation_version": "3.12.0a0",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.10.104-linuxkit",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Thu Mar 17 17:08:06 UTC 2022",
  "python_full_version": "3.12.0a0",
  "platform_python_implementation": "CPython",
  "python_version": "3.12",
  "sys_platform": "linux"
}
```

There are things I don't understand above that info as well, namely that the Python implementation version is 3.12.0a0.  Yes, `/usr/local/bin/python3.12` exists because the Docker image builds Python from the latest git HEAD on `main`, but I don't think that actually corresponds to the version of Python that `.tox/docs/bin/pdm` uses.  For one thing, `.venv` only gets created when I run the `pdm info` command.  For another thing `.tox/docs/bin/pdm` shebang line says `#!/home/runner/flufl.i18n/.tox/docs/bin/python` and *that* Python is:

```bash
$ /home/runner/flufl.i18n/.tox/docs/bin/python -V
Python 3.10.6
```

so I don't think it's a Python version problem.  (Aside: there seems to be no way to control `pdm config` side effect of calling `pdm venv` which is what creates the `.venv` directory.  And I have no idea how to tell PDM to use a Python < 3.12 when creating its venv.)

Final bit of strangeness I don't understand.  Let's say I *don't* switch to the `cleanup` branch after doing the `git clone`, but instead do things in this order:

```bash
$ tox -e docs
# this succeeds; the next line is required because building the docs modifies the pdm.lock file
$ git checkout pdm.lock
$ git switch cleanup
$ tox -e docs
# this now succeeds
```

I think I've done about as much sleuthing as I can think of at the moment.  Hopefully this report is helpful in reproducing the problem!

**Comment by warsaw** [comment]
I have some more data.  I noticed that `flufl.enum` was passing where `flufl.i18n` was failing but both had very similar `pyproject.toml` files, especially in the `[tools.pdm-dev-dependencies]docs` section, and yet they were giving me different versions of `setuptools`.

Inside `flufl.i18n` (failing), `pdm list --graph` gives me:

```
blue 0.9.1 [ required: Any ]
├── black 22.1.0 [ required: ==22.1.0 ]
│   ├── click 8.1.0 [ required: >=8.0.0 ]
│   ├── mypy-extensions 0.4.3 [ required: >=0.4.3 ]
│   ├── pathspec 0.9.0 [ required: >=0.9.0 ]
│   ├── platformdirs 2.5.2 [ required: >=2 ]
│   └── tomli 1.2.3 [ required: >=1.1.0 ]
└── flake8 4.0.1 [ required: <5.0.0,>=3.8 ]
    ├── mccabe 0.6.1 [ required: <0.7.0,>=0.6.0 ]
    ├── pycodestyle 2.8.0 [ required: <2.9.0,>=2.8.0 ]
    └── pyflakes 2.4.0 [ required: <2.5.0,>=2.4.0 ]
diff-cover 6.5.1 [ required: Any ]
├── chardet 4.0.0 [ required: >=3.0.0 ]
├── jinja2 3.1.1 [ required: >=2.7.1 ]
│   └── markupsafe 2.1.1 [ required: >=2.0 ]
├── pluggy 1.0.0 [ required: <2,>=0.13.1 ]
└── pygments 2.11.2 [ required: <3.0.0,>=2.9.0 ]
flufl.i18n 4.1 [ Not required ]
└── atpublic 3.0.1 [ required: >=2.3 ]
furo 2022.6.21 [ required: Any ]
├── beautifulsoup4 4.10.0 [ required: Any ]
│   └── soupsieve 2.3.1 [ required: >1.2 ]
├── pygments 2.11.2 [ required: Any ]
├── sphinx 4.3.2 [ required: <6.0,>=4.0 ]
│   ├── alabaster 0.7.12 [ required: <0.8,>=0.7 ]
│   ├── babel 2.9.1 [ required: >=1.3 ]
│   │   └── pytz 2022.1 [ required: >=2015.7 ]
│   ├── docutils 0.17.1 [ required: <0.18,>=0.14 ]
│   ├── imagesize 1.3.0 [ required: Any ]
│   ├── jinja2 3.1.1 [ required: >=2.3 ]
│   │   └── markupsafe 2.1.1 [ required: >=2.0 ]
│   ├── packaging 21.3 [ required: Any ]
│   │   └── pyparsing 3.0.7 [ required: !=3.0.5,>=2.0.2 ]
│   ├── pygments 2.11.2 [ required: >=2.0 ]
│   ├── requests 2.27.1 [ required: >=2.5.0 ]
│   │   ├── certifi 2021.10.8 [ required: >=2017.4.17 ]
│   │   ├── charset-normalizer 2.0.12 [ required: ~=2.0.0 ]
│   │   ├── idna 3.3 [ required: <4,>=2.5 ]
│   │   └── urllib3 1.26.9 [ required: <1.27,>=1.21.1 ]
│   ├── setuptools 61.2.0 [ required: Any ]
│   ├── snowballstemmer 2.2.0 [ required: >=1.1 ]
│   ├── sphinxcontrib-applehelp 1.0.2 [ required: Any ]
│   ├── sphinxcontrib-devhelp 1.0.2 [ required: Any ]
│   ├── sphinxcontrib-htmlhelp 2.0.0 [ required: >=2.0.0 ]
│   ├── sphinxcontrib-jsmath 1.0.1 [ required: Any ]
│   ├── sphinxcontrib-qthelp 1.0.3 [ required: Any ]
│   └── sphinxcontrib-serializinghtml 1.1.5 [ required: >=1.1.5 ]
└── sphinx-basic-ng 0.0.1a12 [ required: Any ]
    └── sphinx 4.3.2 [ required: <6.0,>=4.0 ]
        ├── alabaster 0.7.12 [ required: <0.8,>=0.7 ]
        ├── babel 2.9.1 [ required: >=1.3 ]
        │   └── pytz 2022.1 [ required: >=2015.7 ]
        ├── docutils 0.17.1 [ required: <0.18,>=0.14 ]
        ├── imagesize 1.3.0 [ required: Any ]
        ├── jinja2 3.1.1 [ required: >=2.3 ]
        │   └── markupsafe 2.1.1 [ required: >=2.0 ]
        ├── packaging 21.3 [ required: Any ]
        │   └── pyparsing 3.0.7 [ required: !=3.0.5,>=2.0.2 ]
        ├── pygments 2.11.2 [ required: >=2.0 ]
        ├── requests 2.27.1 [ required: >=2.5.0 ]
        │   ├── certifi 2021.10.8 [ required: >=2017.4.17 ]
        │   ├── charset-normalizer 2.0.12 [ required: ~=2.0.0 ]
        │   ├── idna 3.3 [ required: <4,>=2.5 ]
        │   └── urllib3 1.26.9 [ required: <1.27,>=1.21.1 ]
        ├── setuptools 61.2.0 [ required: Any ]
        ├── snowballstemmer 2.2.0 [ required: >=1.1 ]
        ├── sphinxcontrib-applehelp 1.0.2 [ required: Any ]
        ├── sphinxcontrib-devhelp 1.0.2 [ required: Any ]
        ├── sphinxcontrib-htmlhelp 2.0.0 [ required: >=2.0.0 ]
        ├── sphinxcontrib-jsmath 1.0.1 [ required: Any ]
        ├── sphinxcontrib-qthelp 1.0.3 [ required: Any ]
        └── sphinxcontrib-serializinghtml 1.1.5 [ required: >=1.1.5 ]
isort 5.10.1 [ required: Any ]
mypy 0.971 [ required: Any ]
├── mypy-extensions 0.4.3 [ required: >=0.4.3 ]
├── tomli 1.2.3 [ required: >=1.1.0 ]
└── typing-extensions 4.3.0 [ required: >=3.10 ]
pytest-cov 3.0.0 [ required: Any ]
├── coverage[toml] 6.4.4 [ required: >=5.2.1 ]
│   └── tomli 1.2.3 [ required: Any ]
└── pytest 7.1.2 [ required: >=4.6 ]
    ├── attrs 21.4.0 [ required: >=19.2.0 ]
    ├── iniconfig 1.1.1 [ required: Any ]
    ├── packaging 21.3 [ required: Any ]
    │   └── pyparsing 3.0.7 [ required: !=3.0.5,>=2.0.2 ]
    ├── pluggy 1.0.0 [ required: <2.0,>=0.12 ]
    ├── py 1.11.0 [ required: >=1.8.2 ]
    └── tomli 1.2.3 [ required: >=1.0.0 ]
sphinx-autodoc-typehints 1.17.1 [ required: Any ]
└── sphinx 4.3.2 [ required: >=4 ]
    ├── alabaster 0.7.12 [ required: <0.8,>=0.7 ]
    ├── babel 2.9.1 [ required: >=1.3 ]
    │   └── pytz 2022.1 [ required: >=2015.7 ]
    ├── docutils 0.17.1 [ required: <0.18,>=0.14 ]
    ├── imagesize 1.3.0 [ required: Any ]
    ├── jinja2 3.1.1 [ required: >=2.3 ]
    │   └── markupsafe 2.1.1 [ required: >=2.0 ]
    ├── packaging 21.3 [ required: Any ]
    │   └── pyparsing 3.0.7 [ required: !=3.0.5,>=2.0.2 ]
    ├── pygments 2.11.2 [ required: >=2.0 ]
    ├── requests 2.27.1 [ required: >=2.5.0 ]
    │   ├── certifi 2021.10.8 [ required: >=2017.4.17 ]
    │   ├── charset-normalizer 2.0.12 [ required: ~=2.0.0 ]
    │   ├── idna 3.3 [ required: <4,>=2.5 ]
    │   └── urllib3 1.26.9 [ required: <1.27,>=1.21.1 ]
    ├── setuptools 61.2.0 [ required: Any ]
    ├── snowballstemmer 2.2.0 [ required: >=1.1 ]
    ├── sphinxcontrib-applehelp 1.0.2 [ required: Any ]
    ├── sphinxcontrib-devhelp 1.0.2 [ required: Any ]
    ├── sphinxcontrib-htmlhelp 2.0.0 [ required: >=2.0.0 ]
    ├── sphinxcontrib-jsmath 1.0.1 [ required: Any ]
    ├── sphinxcontrib-qthelp 1.0.3 [ required: Any ]
    └── sphinxcontrib-serializinghtml 1.1.5 [ required: >=1.1.5 ]
sybil 3.0.1 [ required: Any ]
```

Inside `flufl.enum` (succeeding), `pdm list --graph` gives me:

```
blue 0.9.1 [ required: Any ]
├── black 22.1.0 [ required: ==22.1.0 ]
│   ├── click 8.1.3 [ required: >=8.0.0 ]
│   ├── mypy-extensions 0.4.3 [ required: >=0.4.3 ]
│   ├── pathspec 0.9.0 [ required: >=0.9.0 ]
│   ├── platformdirs 2.5.2 [ required: >=2 ]
│   └── tomli 2.0.1 [ required: >=1.1.0 ]
└── flake8 4.0.1 [ required: <5.0.0,>=3.8 ]
    ├── mccabe 0.6.1 [ required: <0.7.0,>=0.6.0 ]
    ├── pycodestyle 2.8.0 [ required: <2.9.0,>=2.8.0 ]
    └── pyflakes 2.4.0 [ required: <2.5.0,>=2.4.0 ]
diff-cover 6.5.1 [ required: Any ]
├── chardet 5.0.0 [ required: >=3.0.0 ]
├── jinja2 3.1.2 [ required: >=2.7.1 ]
│   └── markupsafe 2.1.1 [ required: >=2.0 ]
├── pluggy 1.0.0 [ required: <2,>=0.13.1 ]
└── pygments 2.12.0 [ required: <3.0.0,>=2.9.0 ]
flufl.enum 5.0 [ Not required ]
└── atpublic 3.0.1 [ required: Any ]
furo 2022.6.21 [ required: Any ]
├── beautifulsoup4 4.11.1 [ required: Any ]
│   └── soupsieve 2.3.2.post1 [ required: >1.2 ]
├── pygments 2.12.0 [ required: Any ]
├── sphinx 4.3.2 [ required: <6.0,>=4.0 ]
│   ├── alabaster 0.7.12 [ required: <0.8,>=0.7 ]
│   ├── babel 2.10.3 [ required: >=1.3 ]
│   │   └── pytz 2022.1 [ required: >=2015.7 ]
│   ├── docutils 0.17.1 [ required: <0.18,>=0.14 ]
│   ├── imagesize 1.4.1 [ required: Any ]
│   ├── jinja2 3.1.2 [ required: >=2.3 ]
│   │   └── markupsafe 2.1.1 [ required: >=2.0 ]
│   ├── packaging 21.3 [ required: Any ]
│   │   └── pyparsing 3.0.9 [ required: !=3.0.5,>=2.0.2 ]
│   ├── pygments 2.12.0 [ required: >=2.0 ]
│   ├── requests 2.28.1 [ required: >=2.5.0 ]
│   │   ├── certifi 2022.6.15 [ required: >=2017.4.17 ]
│   │   ├── charset-normalizer 2.1.0 [ required: <3,>=2 ]
│   │   ├── idna 3.3 [ required: <4,>=2.5 ]
│   │   └── urllib3 1.26.10 [ required: <1.27,>=1.21.1 ]
│   ├── setuptools 63.2.0 [ required: Any ]
│   ├── snowballstemmer 2.2.0 [ required: >=1.1 ]
│   ├── sphinxcontrib-applehelp 1.0.2 [ required: Any ]
│   ├── sphinxcontrib-devhelp 1.0.2 [ required: Any ]
│   ├── sphinxcontrib-htmlhelp 2.0.0 [ required: >=2.0.0 ]
│   ├── sphinxcontrib-jsmath 1.0.1 [ required: Any ]
│   ├── sphinxcontrib-qthelp 1.0.3 [ required: Any ]
│   └── sphinxcontrib-serializinghtml 1.1.5 [ required: >=1.1.5 ]
└── sphinx-basic-ng 0.0.1a12 [ required: Any ]
    └── sphinx 4.3.2 [ required: <6.0,>=4.0 ]
        ├── alabaster 0.7.12 [ required: <0.8,>=0.7 ]
        ├── babel 2.10.3 [ required: >=1.3 ]
        │   └── pytz 2022.1 [ required: >=2015.7 ]
        ├── docutils 0.17.1 [ required: <0.18,>=0.14 ]
        ├── imagesize 1.4.1 [ required: Any ]
        ├── jinja2 3.1.2 [ required: >=2.3 ]
        │   └── markupsafe 2.1.1 [ required: >=2.0 ]
        ├── packaging 21.3 [ required: Any ]
        │   └── pyparsing 3.0.9 [ required: !=3.0.5,>=2.0.2 ]
        ├── pygments 2.12.0 [ required: >=2.0 ]
        ├── requests 2.28.1 [ required: >=2.5.0 ]
        │   ├── certifi 2022.6.15 [ required: >=2017.4.17 ]
        │   ├── charset-normalizer 2.1.0 [ required: <3,>=2 ]
        │   ├── idna 3.3 [ required: <4,>=2.5 ]
        │   └── urllib3 1.26.10 [ required: <1.27,>=1.21.1 ]
        ├── setuptools 63.2.0 [ required: Any ]
        ├── snowballstemmer 2.2.0 [ required: >=1.1 ]
        ├── sphinxcontrib-applehelp 1.0.2 [ required: Any ]
        ├── sphinxcontrib-devhelp 1.0.2 [ required: Any ]
        ├── sphinxcontrib-htmlhelp 2.0.0 [ required: >=2.0.0 ]
        ├── sphinxcontrib-jsmath 1.0.1 [ required: Any ]
        ├── sphinxcontrib-qthelp 1.0.3 [ required: Any ]
        └── sphinxcontrib-serializinghtml 1.1.5 [ required: >=1.1.5 ]
isort 5.10.1 [ required: Any ]
mypy 0.971 [ required: Any ]
├── mypy-extensions 0.4.3 [ required: >=0.4.3 ]
├── tomli 2.0.1 [ required: >=1.1.0 ]
└── typing-extensions 4.3.0 [ required: >=3.10 ]
pytest-cov 3.0.0 [ required: Any ]
├── coverage[toml] 6.4.4 [ required: >=5.2.1 ]
│   └── tomli 2.0.1 [ required: Any ]
└── pytest 7.1.2 [ required: >=4.6 ]
    ├── attrs 21.4.0 [ required: >=19.2.0 ]
    ├── iniconfig 1.1.1 [ required: Any ]
    ├── packaging 21.3 [ required: Any ]
    │   └── pyparsing 3.0.9 [ required: !=3.0.5,>=2.0.2 ]
    ├── pluggy 1.0.0 [ required: <2.0,>=0.12 ]
    ├── py 1.11.0 [ required: >=1.8.2 ]
    └── tomli 2.0.1 [ required: >=1.0.0 ]
sphinx-autodoc-typehints 1.17.1 [ required: Any ]
└── sphinx 4.3.2 [ required: >=4 ]
    ├── alabaster 0.7.12 [ required: <0.8,>=0.7 ]
    ├── babel 2.10.3 [ required: >=1.3 ]
    │   └── pytz 2022.1 [ required: >=2015.7 ]
    ├── docutils 0.17.1 [ required: <0.18,>=0.14 ]
    ├── imagesize 1.4.1 [ required: Any ]
    ├── jinja2 3.1.2 [ required: >=2.3 ]
    │   └── markupsafe 2.1.1 [ required: >=2.0 ]
    ├── packaging 21.3 [ required: Any ]
    │   └── pyparsing 3.0.9 [ required: !=3.0.5,>=2.0.2 ]
    ├── pygments 2.12.0 [ required: >=2.0 ]
    ├── requests 2.28.1 [ required: >=2.5.0 ]
    │   ├── certifi 2022.6.15 [ required: >=2017.4.17 ]
    │   ├── charset-normalizer 2.1.0 [ required: <3,>=2 ]
    │   ├── idna 3.3 [ required: <4,>=2.5 ]
    │   └── urllib3 1.26.10 [ required: <1.27,>=1.21.1 ]
    ├── setuptools 63.2.0 [ required: Any ]
    ├── snowballstemmer 2.2.0 [ required: >=1.1 ]
    ├── sphinxcontrib-applehelp 1.0.2 [ required: Any ]
    ├── sphinxcontrib-devhelp 1.0.2 [ required: Any ]
    ├── sphinxcontrib-htmlhelp 2.0.0 [ required: >=2.0.0 ]
    ├── sphinxcontrib-jsmath 1.0.1 [ required: Any ]
    ├── sphinxcontrib-qthelp 1.0.3 [ required: Any ]
    └── sphinxcontrib-serializinghtml 1.1.5 [ required: >=1.1.5 ]
sybil 3.0.1 [ required: Any ]
```

Notice the divergence under the `furo 2022.6.21` dependency, especially in `beautifulsoup`, and inside `sphinx`, the `setuptools` versions (61.2.0 in the failing case, 63.2.0 in the succeeding case).

This was pretty curious until I read about [update strategies](https://pdm.fming.dev/latest/usage/dependency/#about-update-strategy) and noticed that `--update-reuse` was the default.  I wonder if I just needed to `--update-eager` to get everything locked on the latest upstream dependency versions.

Once I did this and pushed new MRs for both projects ([flufl.enum](https://gitlab.com/warsaw/flufl.enum/-/jobs/2931426258) and [flufl.i18n](https://gitlab.com/warsaw/flufl.i18n/-/jobs/2931425237)), both jobs ran to successfull completion.  As it turns out, both pulled `setuptools` to 65.3.0.

So maybe this is all working as expected, but I think at least it's pretty confusing.  Maybe `--update-eager` should be the default?  Maybe PDM should warn when `--update-reuse` (the default) could end up downgrading dependencies.  Maybe there should be a mode that displays what eager updates would give relative to reuse?

I'm not totally sure what the resolution of this is.  Seems like it's a confusing UX problem, and hopefully at least someone else running into this problem will find this ticket and give it a try.   I am unblocked now.

(FWIW, I haven't tried `--update-all`.)

**Comment by frostming** [comment]
I recommend you install PDM outside of the tox env instead of inside. This way the dependencies of PDM won't conflict with the project dependencies.

Also, the`reuse` strategy is preferred because it is the least destructive strategy -- only updating what is demanded and keeping others untouched.

**Comment by warsaw** [comment]
> This way the dependencies of PDM won't conflict with the project dependencies.

Interesting.  I hadn't thought about pdm's dependencies getting in the way.  That makes sense though!

> I recommend you install PDM outside of the tox env instead of inside. 

Actually, I do.  But I also put them in the venvs for convenience.  FTR, you need to you put this in your `tox.ini` `[testenv]` section:

`allowlist_externals = pdm`

> Also, thereuse strategy is preferred because it is the least destructive strategy -- only updating what is demanded and keeping others untouched.

Thanks.

I appreciate the response @frostming.  Closing this ticket.
