### ISSUE TITLE
editables not installed

### ISSUE THREAD

**Issue by pawamoy** [pdm-project/pdm#1344]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

```bash
git clone https://github.com/pawamoy/markdown-exec
cd markdown-exec
pdm use -f python3.8  # or python3.9
pdm lock
pdm install
pdm run mkdocs serve
```

PDM config in pyproject.toml:

```toml
[tool.pdm]
version = {source = "scm"}

[tool.pdm.build]
package-dir = "src"
editable-backend = "editables"
```

## Actual behavior

Getting `ModuleNotFoundError: No module named 'editables'` errors. Since `editables` is not installed, my project is not made available to Python, and further commands fail with `ModuleNotFoundError: No module named 'markdown_exec'`.

Note: it happens in CI as well (
https://github.com/pawamoy/markdown-exec/runs/8058594950?check_suite_focus=true) so this kinda eliminates a possible misconfiguration on my side I think?

## Expected behavior

editables should be installed, whatever the selected Python version is?

## Environment Information

```console
% pdm info && pdm info --env
Error processing line 1 of /media/data/dev/markdown-exec/__pypackages__/3.9/lib/markdown_exec.pth:

  Traceback (most recent call last):
    File "/home/pawamoy/.basher-packages/pyenv/pyenv/versions/3.9.9/lib/python3.9/site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "/media/data/dev/markdown-exec/__pypackages__/3.9/lib/__editables_markdown_exec.py", line 1, in <module>
      from editables.redirector import RedirectingFinder as F
  ModuleNotFoundError: No module named 'editables'

Remainder of file ignored
PDM version:
  2.1.2
Python Interpreter:
  /home/pawamoy/.basher-packages/pyenv/pyenv/versions/3.8.13/bin/python3.8 (3.8)
Project Root:
  /media/data/dev/markdown-exec
Project Packages:
  /media/data/dev/markdown-exec/__pypackages__/3.8
Error processing line 1 of /media/data/dev/markdown-exec/__pypackages__/3.9/lib/markdown_exec.pth:

  Traceback (most recent call last):
    File "/home/pawamoy/.basher-packages/pyenv/pyenv/versions/3.9.9/lib/python3.9/site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "/media/data/dev/markdown-exec/__pypackages__/3.9/lib/__editables_markdown_exec.py", line 1, in <module>
      from editables.redirector import RedirectingFinder as F
  ModuleNotFoundError: No module named 'editables'

Remainder of file ignored
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.13",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.19.4-arch1-1",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT_DYNAMIC Thu, 25 Aug 2022 17:31:12 +0000",
  "python_full_version": "3.8.13",
  "platform_python_implementation": "CPython",
  "python_version": "3.8",
  "sys_platform": "linux"
}
```

**Comment by pawamoy** [comment]
Thank you very much @frostming, your work is amazing.
