### ISSUE TITLE
Show problematic package name and version in logs on resolution errors

### ISSUE THREAD

**Issue by pawamoy** [pdm-project/pdm#1353]
## Is your feature request related to a problem? Please describe.

Yes. I'm currently getting a `pip._vendor.packaging.specifiers.InvalidSpecifier: Invalid specifier: 'impossible'` (PDM 1.x) or `packaging.specifiers.InvalidSpecifier: Invalid specifier: 'impossible'` (PDM 2.x). 
Obviously not PDM's fault, but the absence of library name makes it hard to resolve the issue on our side.

Full logs:

<details><summary>click to expand</summary>

```
pdm.termui: ======== Starting round 3 ========
pdm.termui:     Found matching candidates:
pdm.termui:       <Candidate freezegun 1.2.2 from https://private-index/simple/freezegun/>
pdm.termui:       <Candidate freezegun 1.2.1 from https://private-index/simple/freezegun/>
pdm.termui:       <Candidate freezegun 1.2.0 from https://private-index/simple/freezegun/>
pdm.termui:       <Candidate freezegun 1.1.0 from https://private-index/simple/freezegun/>
pdm.termui:       <Candidate freezegun 1.0.0 from https://private-index/simple/freezegun/>
pdm.termui:       <Candidate freezegun 0.3.15 from https://private-index/simple/freezegun/>
pdm.termui:       <Candidate freezegun 0.3.14 from https://private-index/simple/freezegun/>
pdm.termui:       <Candidate freezegun 0.3.13 from https://private-index/simple/freezegun/>
pdm.termui:       <Candidate freezegun 0.3.12 from https://private-index/simple/freezegun/>
pdm.termui:       <Candidate freezegun 0.3.11 from https://private-index/simple/freezegun/>
pdm.termui:       ... [70 more candidate(s)]
pdm.termui:     Found matching candidates:
pdm.termui:       <Candidate mock 4.0.3 from https://private-index/simple/mock/>
pdm.termui:       <Candidate mock 4.0.2 from https://private-index/simple/mock/>
pdm.termui:       <Candidate mock 4.0.1 from https://private-index/simple/mock/>
pdm.termui:       <Candidate mock 4.0.0 from https://private-index/simple/mock/>
pdm.termui:       <Candidate mock 3.0.5 from https://private-index/simple/mock/>
pdm.termui:     Found matching candidates:
pdm.termui:       <Candidate responses 0.21.0 from https://private-index/simple/responses/>
pdm.termui:       <Candidate responses 0.20.0 from https://private-index/simple/responses/>
pdm.termui:       <Candidate responses 0.19.0 from https://private-index/simple/responses/>
pdm.termui:       <Candidate responses 0.18.0 from https://private-index/simple/responses/>
pdm.termui:       <Candidate responses 0.17.0 from https://private-index/simple/responses/>
pdm.termui:       <Candidate responses 0.16.0 from https://private-index/simple/responses/>
pdm.termui:       <Candidate responses 0.15.0 from https://private-index/simple/responses/>
pdm.termui:       <Candidate responses 0.14.0 from https://private-index/simple/responses/>
pdm.termui:       <Candidate responses 0.13.4 from https://private-index/simple/responses/>
pdm.termui:       <Candidate responses 0.13.3 from https://private-index/simple/responses/>
pdm.termui:       ... [76 more candidate(s)]
pdm.termui:     Found matching candidates:
pdm.termui:       <Candidate pytest 7.1.2 from https://private-index/simple/pytest/>
pdm.termui:       <Candidate pytest 7.1.1 from https://private-index/simple/pytest/>
pdm.termui:       <Candidate pytest 7.1.0 from https://private-index/simple/pytest/>
pdm.termui:       <Candidate pytest 7.0.1 from https://private-index/simple/pytest/>
pdm.termui:       <Candidate pytest 7.0.0 from https://private-index/simple/pytest/>
pdm.termui:       <Candidate pytest 6.2.5 from https://private-index/simple/pytest/>
pdm.termui:       <Candidate pytest 6.2.4 from https://private-index/simple/pytest/>
pdm.termui:       <Candidate pytest 6.2.3 from https://private-index/simple/pytest/>
pdm.termui:       <Candidate pytest 6.2.2 from https://private-index/simple/pytest/>
pdm.termui:       <Candidate pytest 6.2.1 from https://private-index/simple/pytest/>
pdm.termui:       ... [263 more candidate(s)]
pdm.termui:     Found matching candidates:
pdm.termui:       <Candidate pytest-cov 3.0.0 from https://private-index/simple/pytest-cov/>
pdm.termui:       <Candidate pytest-cov 2.12.1 from https://private-index/simple/pytest-cov/>
pdm.termui:       <Candidate pytest-cov 2.12.0 from https://private-index/simple/pytest-cov/>
pdm.termui:       <Candidate pytest-cov 2.11.1 from https://private-index/simple/pytest-cov/>
pdm.termui:       <Candidate pytest-cov 2.11.0 from https://private-index/simple/pytest-cov/>
pdm.termui:       <Candidate pytest-cov 2.10.1 from https://private-index/simple/pytest-cov/>
pdm.termui:       <Candidate pytest-cov 2.10.0 from https://private-index/simple/pytest-cov/>
pdm.termui:       <Candidate pytest-cov 2.9.0 from https://private-index/simple/pytest-cov/>
pdm.termui:       <Candidate pytest-cov 2.8.1 from https://private-index/simple/pytest-cov/>
pdm.termui:       <Candidate pytest-cov 2.8.0 from https://private-index/simple/pytest-cov/>
pdm.termui:       ... [56 more candidate(s)]
pdm.termui:     Found matching candidates:
pdm.termui:       <Candidate backports.functools-lru-cache 1.6.4 from https://private-index/simple/backports-functools-lru-cache/>
pdm.termui:     Found matching candidates:
pdm.termui:       <Candidate beautifulsoup4 4.11.1 from https://private-index/simple/beautifulsoup4/>
pdm.termui:     Found matching candidates:
pdm.termui:       <Candidate bs4 0.0.1 from https://private-index/simple/bs4/>
pdm.termui:     Found matching candidates:
pdm.termui:       <Candidate certifi 2022.6.15 from https://private-index/simple/certifi/>
pdm.termui:     Found matching candidates:
pdm.termui:       <Candidate cffi 1.15.1 from https://private-index/simple/cffi/>
pdm.termui:     Found matching candidates:
pdm.termui:       <Candidate chardet 4.0.0 from https://private-index/simple/chardet/>
pdm.termui:     Found matching candidates:
pdm.termui:       <Candidate charset-normalizer 2.0.12 from https://private-index/simple/charset-normalizer/>
pdm.termui:     Found matching candidates:
pdm.termui:       <Candidate contextvars 2.4 from https://private-index/simple/contextvars/>
pdm.termui:     Found matching candidates:
pdm.termui:       <Candidate cryptography 37.0.4 from https://private-index/simple/cryptography/>
pdm.termui:     Found matching candidates:
pdm.termui:       <Candidate decorator 5.1.1 from https://private-index/simple/decorator/>
pdm.termui:     Found matching candidates:
pdm.termui:       <Candidate Django 1.11.29 from https://private-index/simple/django/>
pdm.termui:     Found matching candidates:
pdm.termui:       <Candidate django-jenkins 0.110.0 from https://private-index/simple/django-jenkins/>
pdm.termui:     Found matching candidates:
pdm.termui:       <Candidate djangorestframework 3.11.2 from https://private-index/simple/djangorestframework/>
pdm.termui:     Found matching candidates:
pdm.termui:       <Candidate enum34 1.1.10 from https://private-index/simple/enum34/>
pdm.termui:     Found matching candidates:
pdm.termui:       <Candidate future 0.18.2 from https://private-index/simple/future/>
pdm.termui:     Found matching candidates:
pdm.termui:       <Candidate idna 3.3 from https://private-index/simple/idna/>
pdm.termui:     Found matching candidates:
pdm.termui:       <Candidate immutables 0.18 from https://private-index/simple/immutables/>
pdm.termui:     Found matching candidates:
pdm.termui:       <Candidate ipaddress 1.0.23 from https://private-index/simple/ipaddress/>
pdm.termui:     Found matching candidates:
pdm.termui:       <Candidate PyContracts 1.8.12 from https://private-index/simple/pycontracts/>
pdm.termui:     Found matching candidates:
pdm.termui:       <Candidate pycparser 2.21 from https://private-index/simple/pycparser/>
pdm.termui:     Found matching candidates:
pdm.termui:       <Candidate pyOpenSSL 22.0.0 from https://private-index/simple/pyopenssl/>
pdm.termui:     Found matching candidates:
pdm.termui:       <Candidate pyparsing 3.0.9 from https://private-index/simple/pyparsing/>
pdm.termui:     Found matching candidates:
pdm.termui:       <Candidate pytz 2022.1 from https://private-index/simple/pytz/>
pdm.termui:     Found matching candidates:
pdm.termui:       <Candidate PyYAML 6.0 from https://private-index/simple/pyyaml/>
pdm.termui:     Found matching candidates:
pdm.termui:       <Candidate requests 2.27.1 from https://private-index/simple/requests/>
pdm.termui:     Found matching candidates:
pdm.termui:       <Candidate six 1.16.0 from https://private-index/simple/six/>
pdm.termui:     Found matching candidates:
pdm.termui:       <Candidate soupsieve 2.3.2.post1 from https://private-index/simple/soupsieve/>
pdm.termui:     Found matching candidates:
pdm.termui:       <Candidate typing 3.10.0.0 from https://private-index/simple/typing/>
pdm.termui:     Found matching candidates:
pdm.termui:       <Candidate typing-extensions 4.1.1 from https://private-index/simple/typing-extensions/>
pdm.termui:     Found matching candidates:
pdm.termui:       <Candidate urllib3 1.26.11 from https://private-index/simple/urllib3/>
pdm.termui:     Found matching candidates:
pdm.termui:       <Candidate backports.functools-lru-cache 1.6.4 from https://private-index/simple/backports-functools-lru-cache/>
Traceback (most recent call last):
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/packaging/specifiers.py", line 634, in __init__
    parsed.add(Specifier(specifier))
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/packaging/specifiers.py", line 98, in __init__
    raise InvalidSpecifier(f"Invalid specifier: '{spec}'")
packaging.specifiers.InvalidSpecifier: Invalid specifier: 'impossible'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/core.py", line 254, in main
    return Core().main(args)
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/core.py", line 187, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/core.py", line 182, in main
    f(options.project, options)
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/cli/commands/lock.py", line 27, in handle
    actions.do_lock(
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/cli/actions.py", line 101, in do_lock
    mapping, dependencies = resolve(
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/resolver/core.py", line 30, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/resolvelib/resolvers.py", line 373, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/resolvelib/resolvers.py", line 213, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/resolvelib/resolvers.py", line 203, in _get_updated_criteria
    for requirement in self._p.get_dependencies(candidate=candidate):
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/resolver/providers.py", line 205, in get_dependencies
    if not requires_python.is_superset(new_requires_python):
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/models/specifiers.py", line 340, in is_superset
    other = type(self)(str(other))
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/models/specifiers.py", line 63, in __init__
    super().__init__(version_str)
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/packaging/specifiers.py", line 636, in __init__
    parsed.add(LegacySpecifier(specifier))
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/packaging/specifiers.py", line 253, in __init__
    super().__init__(spec, prereleases)
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/packaging/specifiers.py", line 98, in __init__
    raise InvalidSpecifier(f"Invalid specifier: '{spec}'")
packaging.specifiers.InvalidSpecifier: Invalid specifier: 'impossible'
```

</details>

## Describe the solution you'd like

If possible, I'd like to see the name and version of the problematic package, so I can open an issue on their tracker.
Maybe it's the last one displayed: `backports.functools-lru-cache 1.6.4`? I couldn't find any `impossible` spec in this package.

## Alternative solution

Ignore such problematic packages and skip to the next ones?

**Comment by pawamoy** [comment]
Update: I've been able to confirm `backports.functools-lru-cache` is the culprit, by removing dependencies from pyproject.toml. Removing it makes the lock pass. I'll check again this package in version 1.6.4 🤔

**Comment by frostming** [comment]
You reached a point that it shouldn't have: https://github.com/pdm-project/pdm/blob/224663a601548108daac947531442b4af56a9747/src/pdm/resolver/providers.py#L202-L207

Where `new_requires_python` is an [impossible python range](https://github.com/pdm-project/pdm/blob/224663a601548108daac947531442b4af56a9747/src/pdm/models/specifiers.py#L421), which means there is no overlap between the project `requires-python` and the `python_version = ...` marker of the dependency. In this case the dependency is meaningless and should be removed.

**Comment by pawamoy** [comment]
Oh, I see, that's indeed a legacy project for which I'm trying to resolve libs through PDM. I'll clean up the dependencies. Thank you for your time.
