### ISSUE TITLE
PDM install crashes installing dependencies globally

### ISSUE THREAD

**Issue by SirMartin** [pdm-project/pdm#1388]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

I am trying to run in a docker container and install the packages globally (using the **-g** flag)

If I try exactly the same commands without the -g it works perfectly, and installs everything in the container.

`pdm install -g --prod -p /python_engine --check`

But a lot of packages fails when I use the **-g** flag.

## Actual behavior

If we add the **-g** flag and runs exactly this command, the process crashes. (`pdm install -g --prod -p /python_engine --check`)

Here is one of the log errors from pdm install: [pdm-install-9ylc74ji.log](https://github.com/pdm-project/pdm/files/9584099/pdm-install-9ylc74ji.log)

But if instead of it just runs the same install command but without the **-g** works fine.

## Environment Information

If I try to run the info commands or any command after the crash, I got this crash.

```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/compat.py", line 11, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pdm", line 5, in <module>
    from pdm.core import main
  File "/usr/local/lib/python3.9/site-packages/pdm/__init__.py", line 7, in <module>
    from pdm.cli.commands.base import BaseCommand as _BaseCommand
  File "/usr/local/lib/python3.9/site-packages/pdm/cli/commands/base.py", line 6, in <module>
    from pdm.cli.utils import PdmFormatter
  File "/usr/local/lib/python3.9/site-packages/pdm/cli/utils.py", line 31, in <module>
    from pdm.formats import FORMATS
  File "/usr/local/lib/python3.9/site-packages/pdm/formats/__init__.py", line 8, in <module>
    from pdm.formats import flit, pipfile, poetry, requirements, setup_py
  File "/usr/local/lib/python3.9/site-packages/pdm/formats/flit.py", line 17, in <module>
    from pdm.project import Project
  File "/usr/local/lib/python3.9/site-packages/pdm/project/__init__.py", line 2, in <module>
    from pdm.project.core import Project  # noqa
  File "/usr/local/lib/python3.9/site-packages/pdm/project/core.py", line 21, in <module>
    from pdm.models.caches import CandidateInfoCache, HashCache, WheelCache
  File "/usr/local/lib/python3.9/site-packages/pdm/models/caches.py", line 11, in <module>
    import requests
  File "/usr/local/lib/python3.9/site-packages/requests/__init__.py", line 45, in <module>
    from .exceptions import RequestsDependencyWarning
  File "/usr/local/lib/python3.9/site-packages/requests/exceptions.py", line 9, in <module>
    from .compat import JSONDecodeError as CompatJSONDecodeError
  File "/usr/local/lib/python3.9/site-packages/requests/compat.py", line 13, in <module>
    import charset_normalizer as chardet
ModuleNotFoundError: No module named 'charset_normalizer'
```

Before the crash and any installation
```bash
PDM version:
  2.1.3
Python Interpreter:
  /usr/local/bin/python (3.9)
Project Root:
  /code
Project Packages:
  /code/__pypackages__/3.9

{
  "implementation_name": "cpython",
  "implementation_version": "3.9.7",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.18.10-76051810-generic",
  "platform_system": "Linux",
  "platform_version": "#202207071639~1659403207~22.04~cb5f582 SMP PREEMPT_DYNAMIC Tue A",
  "python_full_version": "3.9.7",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
There are conflicts between the packages you want to install and the packages required by PDM. This will likely happen if you didn't install PDM as an isolated app, which is not recommended. Try one of the recommended installation methods in the documentation.

**Comment by SirMartin** [comment]
I tested and works fine. Thanks.
