### ISSUE TITLE
PDM install fails on project with `project.entry-points`.

### ISSUE THREAD

**Issue by AvlWx2014** [pdm-project/pdm#1391]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

In `pyproject.toml` add an entrypoint that includes just the module e.g.

[project.entry-points."optional.group"]
"name" = "package.sub_package.module"

Then attempt to install your project in editable mode from the project root directory:

```bash
pdm add -de ./
pdm sync -v
```

## Actual behavior
`pdm sync` fails to install the project.

Traceback from `pdm sync -v`:

```text
  ✖ Install contcert 0.1.0 failed
Traceback (most recent call last):
  File "/home/rsmit/.asdf/installs/pdm/2.1.4/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/rsmit/.asdf/installs/pdm/2.1.4/venv/lib/python3.10/site-packages/pdm/core.py", line 254, in main
    return Core().main(args)
  File "/home/rsmit/.asdf/installs/pdm/2.1.4/venv/lib/python3.10/site-packages/pdm/core.py", line 187, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/home/rsmit/.asdf/installs/pdm/2.1.4/venv/lib/python3.10/site-packages/pdm/core.py", line 182, in main
    f(options.project, options)
  File "/home/rsmit/.asdf/installs/pdm/2.1.4/venv/lib/python3.10/site-packages/pdm/cli/commands/sync.py", line 36, in handle
    actions.do_sync(
  File "/home/rsmit/.asdf/installs/pdm/2.1.4/venv/lib/python3.10/site-packages/pdm/cli/actions.py", line 219, in do_sync
    handler.synchronize()
  File "/home/rsmit/.asdf/installs/pdm/2.1.4/venv/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 426, in synchronize
    self.install_candidate(self_key, progress)
  File "/home/rsmit/.asdf/installs/pdm/2.1.4/venv/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 225, in install_candidate
    self.manager.install(can)
  File "/home/rsmit/.asdf/installs/pdm/2.1.4/venv/lib/python3.10/site-packages/pdm/installers/manager.py", line 39, in install
    installer(str(prepared.build()), self.environment, prepared.direct_url())
  File "/home/rsmit/.asdf/installs/pdm/2.1.4/venv/lib/python3.10/site-packages/pdm/installers/installers.py", line 185, in install_wheel
    _install_wheel(
  File "/home/rsmit/.asdf/installs/pdm/2.1.4/venv/lib/python3.10/site-packages/pdm/installers/installers.py", line 279, in _install_wheel
    install(source, destination, additional_metadata=additional_metadata or {})
  File "/home/rsmit/.asdf/installs/pdm/2.1.4/venv/lib/python3.10/site-packages/installer/_core.py", line 86, in install
    for name, module, attr, section in parse_entrypoints(entrypoints_text):
  File "/home/rsmit/.asdf/installs/pdm/2.1.4/venv/lib/python3.10/site-packages/installer/utils.py", line 221, in parse_entrypoints
    assert match
AssertionError
```

## Expected behavior
`pdm sync` successfully installs my project in editable mode, including all entry-points from `project.scripts` and `project.entry-points`.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.1.4
Python Interpreter:
  /home/rsmit/repos/gitlab-cee/contcert/.venv/bin/python (3.9)
Project Root:
  /home/rsmit/repos/gitlab-cee/contcert
Project Packages:
  None
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.12",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "4.18.0-372.19.1.el8_6.x86_64",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Mon Jul 18 11:14:02 EDT 2022",
  "python_full_version": "3.9.12",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

## Additional Information
After following links to the offending line in the traceback I found this from PDM's dependency `installer`:

```python
match = _ENTRYPOINT_REGEX.match(value)
assert match  # <-- where the error above is raised
```

where `_ENTRYPOINT_REGEX` is defined as:

```python
# Adapted from https://github.com/python/importlib_metadata/blob/v3.4.0/importlib_metadata/__init__.py#L90  # noqa
_ENTRYPOINT_REGEX = re.compile(
    r"""
    (?P<module>[\w.]+)\s*
    (:\s*(?P<attrs>[\w.]+))\s*
    (?P<extras>\[.*\])?\s*$
    """,
    re.VERBOSE | re.UNICODE,
)
```

The issue appears to be that the `attrs` group is not optional according to this regular expression. [Entry points](https://setuptools.pypa.io/en/latest/userguide/entry_point.html#entry-points-syntax) can be defined using just `package_or_module`, but this regular expression requires `package_or_module:object` in order to match. 

Since the issue is with the code for `installer` I'd like to understand what you all think is the best approach here. The change should just be adding a missing `?` to the regular expression above (i.e. `(:\s*(?P<attrs>[\w.]+))?\s*`), but then this will fail a few lines later:

```python
# from installer/utils.py
attrs = match.group("attrs")
assert attrs is not None
```

It seems that to solve this `installer` will need a bit of a refactor - is it possible we can solve this in `pdm` in a different way? Maybe use `importlib` instead of `installer`?

**Comment by frostming** [comment]
Thanks for catching this, but `importlib` can't be a replacement of `installer`, we'd better propose a fix in `installer`.

**Comment by frostming** [comment]
`installer` actually allows optional attrs in `entry-points` group, but refuses them in `*_scripts`. As you can see, the parser only applies to the mentioned groups: https://github.com/pypa/installer/blob/70ae05bb25c66e621064f2c031a04ac1192be30b/src/installer/utils.py#L219-L220

[The packaging guide](https://packaging.python.org/en/latest/specifications/entry-points/#:~:text=Two%20groups%20of,command%20is%20run.) also implies this. I don't think there is anything wrong herer.

**Comment by AvlWx2014** [comment]
Sad - it looks like I messed something up somewhere on my first pass. I'm a recent convert from pipenv, so I'm still working out the kinks between the two. 

I deleted my venv and pyproject.toml this morning and started fresh and now it looks like everything is working as expected. Sorry for the noise in your issues box, thanks for this awesome tool!
