### ISSUE TITLE
OSError on pdm run

### ISSUE THREAD

**Issue by EvanHsieh0415** [pdm-project/pdm#1398]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

when I use `pdm run ./src/main.py`
it throw OSError
![image](https://user-images.githubusercontent.com/74277414/192151437-d70cd1c2-8495-4e01-86d0-3ee9dda02d3a.png)
```bash
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\users\evan9\.local\bin\pdm.exe\__main__.py", line 7, in <module>
  File "C:\Users\evan9\.local\pipx\venvs\pdm\lib\site-packages\pdm\core.py", line 254, in main
    return Core().main(args)
  File "C:\Users\evan9\.local\pipx\venvs\pdm\lib\site-packages\pdm\core.py", line 187, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "C:\Users\evan9\.local\pipx\venvs\pdm\lib\site-packages\pdm\core.py", line 182, in main
    f(options.project, options)
  File "C:\Users\evan9\.local\pipx\venvs\pdm\lib\site-packages\pdm\cli\commands\run.py", line 356, in handle
    exit_code = runner.run(options.command, options.args)
  File "C:\Users\evan9\.local\pipx\venvs\pdm\lib\site-packages\pdm\cli\commands\run.py", line 291, in run
    return self._run_process(
  File "C:\Users\evan9\.local\pipx\venvs\pdm\lib\site-packages\pdm\cli\commands\run.py", line 207, in _run_process
    process = subprocess.Popen(
  File "C:\Program Files\Python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python310\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 不是有效的 Win32 應用程式。
```

## Actual behavior

run `pdm run ./src/main.py`

## Expected behavior

Success run python file

## Environment Information

```bash
PDM version:
  2.1.4
Python Interpreter:
  D:\github\EvanHsieh0415\mouse bot\.venv\Scripts\python.exe (3.10)
Project Root:
  D:/github/EvanHsieh0415/mouse bot
Project Packages:
  None
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.6",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19044",
  "python_full_version": "3.10.6",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "win32"
}
```

**Comment by pawamoy** [comment]
Try running `pdm run python src/main.py`

**Comment by EvanHsieh0415** [comment]
fix, thx
~~but why~~

**Comment by pawamoy** [comment]
Sorry for the short answer, I'm on mobile. My guess as for why passing `./src/main.py` directly does not work is because it's not executable? Did you set the exec bit on that file?

**Comment by frostming** [comment]
`./src/main.py` itself isn't executable, you can run it via double-click or in cmd because it is associated with a program that can execute it, Python specifically in this case. I don't know much about the mechanism but I guess it's shell magic. Because it works with `shell=True` but not otherwise.

```python
import subprocess

subprocess.run(['./src/main.py'])  # Error!
subprocess.run('./src/main.py', shell=True)  # Success
