### ISSUE TITLE
can't run commands when using install cache

### ISSUE THREAD

**Issue by davidism** [pdm-project/pdm#1407]
Enable the `install.cache` config, remove an existing virtualenv, run `pdm sync`, then try to run a command, like `pdm run tox`. Any command defined as an entry point will raise an `ImportError`. Commands work when not using the cache. `install.cache_method pth` does not change the behavior, it fails regardless of link type.

```
$ pdm config install.cache true
$ pdm venv remove -y in-project
$ pdm sync

$ pdm run tox
Traceback (most recent call last):
  File "/home/david/Projects/flask-sqlalchemy/.venv/bin/tox", line 5, in <module>
    from tox import cmdline
ImportError: cannot import name 'cmdline' from 'tox' (unknown location)

$ pdm run pre-commit
Traceback (most recent call last):
  File "/home/david/Projects/flask-sqlalchemy/.venv/bin/pre-commit", line 5, in <module>
    from pre_commit.main import main
ModuleNotFoundError: No module named 'pre_commit.main'

$ pdm run flask
Traceback (most recent call last):
  File "/home/david/Projects/flask-sqlalchemy/.venv/bin/flask", line 5, in <module>
    from flask.cli import main
ModuleNotFoundError: No module named 'flask.cli'
```

```
$ pdm info && pdm info --env
PDM version:
  2.1.4
Python Interpreter:
  /home/david/Projects/flask-sqlalchemy/.venv/bin/python (3.10)
Project Root:
  /home/david/Projects/flask-sqlalchemy
Project Packages:
  None
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.7",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.19.11-arch1-1",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT_DYNAMIC Sat, 24 Sep 2022 18:24:15 +0000",
  "python_full_version": "3.10.7",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
I can't reproduce with the exact steps you provided, please make sure the paths the packages symlink to are valid and actually contain files in it.

**Comment by davidism** [comment]
For some reason, the items in the cache are empty:

```
$ cd .venv/lib/python3.10/site-packages
$ ls -Fl      
total 80K
lrwxrwxrwx 1 david david   66 Sep 28 20:46 click -> /home/david/.cache/pdm/packages/click-8.1.3-py3-none-any/lib/click/
drwxr-xr-x 2 david david 4.0K Sep 28 20:46 click-8.1.3.dist-info/
lrwxrwxrwx 1 david david   76 Sep 28 20:46 dotenv -> /home/david/.cache/pdm/packages/python_dotenv-0.21.0-py3-none-any/lib/dotenv/
lrwxrwxrwx 1 david david   66 Sep 28 20:46 flask -> /home/david/.cache/pdm/packages/Flask-2.2.2-py3-none-any/lib/flask/
drwxr-xr-x 2 david david 4.0K Sep 28 20:46 Flask-2.2.2.dist-info/
lrwxrwxrwx 1 david david   80 Sep 28 20:46 itsdangerous -> /home/david/.cache/pdm/packages/itsdangerous-2.1.2-py3-none-any/lib/itsdangerous/
drwxr-xr-x 2 david david 4.0K Sep 28 20:46 itsdangerous-2.1.2.dist-info/
lrwxrwxrwx 1 david david   68 Sep 28 20:46 jinja2 -> /home/david/.cache/pdm/packages/Jinja2-3.1.2-py3-none-any/lib/jinja2/
drwxr-xr-x 2 david david 4.0K Sep 28 20:46 Jinja2-3.1.2.dist-info/
lrwxrwxrwx 1 david david  118 Sep 28 20:46 markupsafe -> /home/david/.cache/pdm/packages/MarkupSafe-2.1.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64/lib/markupsafe/
drwxr-xr-x 2 david david 4.0K Sep 28 20:46 MarkupSafe-2.1.1.dist-info/
drwxr-xr-x 2 david david 4.0K Sep 28 20:46 __pycache__/
drwxr-xr-x 2 david david 4.0K Sep 28 20:46 python_dotenv-0.21.0.dist-info/
lrwxrwxrwx 1 david david   89 Sep 28 20:46 watchdog -> /home/david/.cache/pdm/packages/watchdog-2.1.9-py3-none-manylinux2014_x86_64/lib/watchdog/
drwxr-xr-x 2 david david 4.0K Sep 28 20:46 watchdog-2.1.9.dist-info/
lrwxrwxrwx 1 david david   72 Sep 28 20:46 werkzeug -> /home/david/.cache/pdm/packages/Werkzeug-2.2.2-py3-none-any/lib/werkzeug/
drwxr-xr-x 2 david david 4.0K Sep 28 20:46 Werkzeug-2.2.2.dist-info/
-rw-r--r-- 1 david david   18 Sep 28 20:46 _virtualenv.pth
-rw-r--r-- 1 david david 5.6K Sep 28 20:46 _virtualenv.py
```

```
$ cd flask
$ ls -R
.:
json  __pycache__

./json:
__pycache__

./json/__pycache__:

./__pycache__:
```

It seems like it attempted to unpack the wheel, created the folders, but all the files are missing.

I cleared the cache with `pdm cache clear`, removed the venv, then ran `pdm sync` again, and the same thing happened.

**Comment by frostming** [comment]
The caching is just normal installations, can you share a dockerfile to reproduce it locally?

**Comment by davidism** [comment]
I tried creating a dockerfile, but it works correctly there.

```dockerfile
FROM python:3.10
WORKDIR /project
RUN pip install -U pdm virtualenv pip setuptools wheel
RUN pdm config install.cache true
RUN pdm init -n
# this is the only way I can get pdm to create a venv after init
RUN pdm config -l -d python.path
RUN pdm add flask
CMD ["pdm", "run", "flask"]
```

I know the cache should be normal, but for some reason it's just empty folders. Is there anything else I can do to diagnose this? As far as I know I have a standard Linux setup, nothing weird.

**Comment by frostming** [comment]
> Is there anything else I can do to diagnose this?

Adding `-v` option might help.

> `# this is the only way I can get pdm to create a venv after init`

This was fixed in the main branch

**Comment by davidism** [comment]
Well, I have no idea what happened, but after multiple days of it producing an empty cache, I tried it again this morning to give you the `-v` output and it all worked.
