### ISSUE TITLE
Not clear why this is a version conflict

### ISSUE THREAD

**Issue by nottrobin** [pdm-project/pdm#1416]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

After running `pdm install` for the first time on a project with an existing `requirements.txt`, I get the following:

> Unable to find a resolution for flask
> because of the following conflicts:
>  Flask>=1.0.2 (from <Candidate canonicalwebteam.discourse 5.0.1 from https://pypi.org/simple/canonicalwebteam-discourse/>)
>  flask (from <Candidate canonicalwebteam.blog 6.4.0 from https://pypi.org/simple/canonicalwebteam-blog/>)
>  flask==1.1.2 (from <Candidate canonicalwebteam.flask-base 1.0.5 from https://pypi.org/simple/canonicalwebteam-flask-base/>)

I'm very happy to believe that there is a conflict between these versions that `pip` never picked up on, and I'm very happy to address it.

However in this case I don't understand why there's a conflict - surely [Flask v1.1.2](https://pypi.org/project/Flask/1.1.2/) would satisfy all of the above requirements?

<details>
<summary>Full output of `pdm install -v`</summary>

```console
$ pdm install -v
Lock file does not exist
Updating the lock file...
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   canonicalwebteam.flask-base==1.0.5
pdm.termui:   canonicalwebteam.http==1.0.3
pdm.termui:   canonicalwebteam.blog==6.4.0
pdm.termui:   canonicalwebteam.search==1.2.7
pdm.termui:   canonicalwebteam.templatefinder==1.0.0
pdm.termui:   canonicalwebteam.image-template==1.3.1
pdm.termui:   canonicalwebteam.discourse==5.0.1
pdm.termui:   python-dateutil==2.8.2
pdm.termui:   pytz==2020.5
pdm.termui:   maxminddb-geolite2==2018.703
pdm.termui:   Flask-OpenID==1.3.0
pdm.termui:   feedgen==0.9.0
pdm.termui:   feedparser==6.0.8
pdm.termui:   pymacaroons==0.13.0
pdm.termui:   pybreaker==0.7.0
pdm.termui:   Flask-WTF==0.15.1
pdm.termui:   requests==2.27.0
pdm.termui:   sqlalchemy==1.3.23
pdm.termui:   marshmallow==3.14.1
pdm.termui:   mistune==0.8.4
pdm.termui:   psycopg2-binary==2.9.3
pdm.termui:   pyyaml==5.4.1
pdm.termui:   ubuntu-release-info==21.1
pdm.termui:   launchpadlib==1.10.15.1
pdm.termui:   macaroonbakery==1.3.1
pdm.termui:   sortedcontainers==2.4.0
pdm.termui:   vcrpy-unittest==0.1.7
pdm.termui:   webargs==7.0.1
pdm.termui:   jinja2==3.0.3
pdm.termui:   python
pdm.termui:   Adding requirement canonicalwebteam.flask-base==1.0.5
pdm.termui:   Adding requirement canonicalwebteam.http==1.0.3
pdm.termui:   Adding requirement canonicalwebteam.blog==6.4.0
pdm.termui:   Adding requirement canonicalwebteam.search==1.2.7
pdm.termui:   Adding requirement canonicalwebteam.templatefinder==1.0.0
pdm.termui:   Adding requirement canonicalwebteam.image-template==1.3.1
pdm.termui:   Adding requirement canonicalwebteam.discourse==5.0.1
pdm.termui:   Adding requirement python-dateutil==2.8.2
pdm.termui:   Adding requirement pytz==2020.5
pdm.termui:   Adding requirement maxminddb-geolite2==2018.703
pdm.termui:   Adding requirement Flask-OpenID==1.3.0
pdm.termui:   Adding requirement feedgen==0.9.0
pdm.termui:   Adding requirement feedparser==6.0.8
pdm.termui:   Adding requirement pymacaroons==0.13.0
pdm.termui:   Adding requirement pybreaker==0.7.0
pdm.termui:   Adding requirement Flask-WTF==0.15.1
pdm.termui:   Adding requirement requests==2.27.0
pdm.termui:   Adding requirement sqlalchemy==1.3.23
pdm.termui:   Adding requirement marshmallow==3.14.1
pdm.termui:   Adding requirement mistune==0.8.4
pdm.termui:   Adding requirement psycopg2-binary==2.9.3
pdm.termui:   Adding requirement pyyaml==5.4.1
pdm.termui:   Adding requirement ubuntu-release-info==21.1
pdm.termui:   Adding requirement launchpadlib==1.10.15.1
pdm.termui:   Adding requirement macaroonbakery==1.3.1
pdm.termui:   Adding requirement sortedcontainers==2.4.0
pdm.termui:   Adding requirement vcrpy-unittest==0.1.7
pdm.termui:   Adding requirement webargs==7.0.1
pdm.termui:   Adding requirement jinja2==3.0.3
pdm.termui:   Adding requirement python
pdm.termui: ======== Starting round 0 ========
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
pdm.termui:   Adding requirement flask(from canonicalwebteam.blog 6.4.0)
pdm.termui:   Adding requirement feedgen(from canonicalwebteam.blog 6.4.0)
pdm.termui:   Adding requirement requests(from canonicalwebteam.blog 6.4.0)
pdm.termui:   Adding requirement beautifulsoup4(from canonicalwebteam.blog 6.4.0)
pdm.termui:   Adding requirement canonicalwebteam.image-template(from canonicalwebteam.blog 6.4.0)
pdm.termui: Pinning: canonicalwebteam.blog 6.4.0
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
pdm.termui:   Adding requirement Flask>=1.0.2(from canonicalwebteam.discourse 5.0.1)
pdm.termui:   Adding requirement beautifulsoup4(from canonicalwebteam.discourse 5.0.1)
pdm.termui:   Adding requirement humanize(from canonicalwebteam.discourse 5.0.1)
pdm.termui:   Adding requirement python-dateutil(from canonicalwebteam.discourse 5.0.1)
pdm.termui:   Adding requirement validators(from canonicalwebteam.discourse 5.0.1)
pdm.termui: Pinning: canonicalwebteam.discourse 5.0.1
pdm.termui: ======== Ending round 2 ========
pdm.termui: ======== Starting round 3 ========
pdm.termui:   Adding requirement canonicalwebteam.yaml-responses[flask]<2,>=1(from canonicalwebteam.flask-base 1.0.5)
pdm.termui:   Adding requirement flask==1.1.2(from canonicalwebteam.flask-base 1.0.5)
pdm.termui:   Adding requirement canonicalwebteam.yaml-responses[flask]<2,>=1(from canonicalwebteam.flask-base 1.0.5)
pdm.termui:   Adding requirement flask==1.1.2(from canonicalwebteam.flask-base 1.0.5)
pdm.termui: Conflicts detected: 
  flask (from <Candidate canonicalwebteam.blog 6.4.0 from https://pypi.org/simple/canonicalwebteam-blog/>)
  Flask>=1.0.2 (from <Candidate canonicalwebteam.discourse 5.0.1 from https://pypi.org/simple/canonicalwebteam-discourse/>)
  flask==1.1.2 (from <Candidate canonicalwebteam.flask-base 1.0.5 from https://pypi.org/simple/canonicalwebteam-flask-base/>)
  flask (from <Candidate canonicalwebteam.blog 6.4.0 from https://pypi.org/simple/canonicalwebteam-blog/>)
  Flask>=1.0.2 (from <Candidate canonicalwebteam.discourse 5.0.1 from https://pypi.org/simple/canonicalwebteam-discourse/>)
  flask==1.1.2 (from <Candidate canonicalwebteam.flask-base 1.0.5 from https://pypi.org/simple/canonicalwebteam-flask-base/>)
pdm.termui: Candidate rejected: canonicalwebteam.discourse 5.0.1
pdm.termui: Candidate rejected: canonicalwebteam.blog 6.4.0
pdm.termui: Candidate rejected: python None
🔒 Lock failed
Unable to find a resolution for flask
because of the following conflicts:
  Flask>=1.0.2 (from <Candidate canonicalwebteam.discourse 5.0.1 from https://pypi.org/simple/canonicalwebteam-discourse/>)
  flask (from <Candidate canonicalwebteam.blog 6.4.0 from https://pypi.org/simple/canonicalwebteam-blog/>)
  flask==1.1.2 (from <Candidate canonicalwebteam.flask-base 1.0.5 from https://pypi.org/simple/canonicalwebteam-flask-base/>)
To fix this, you could loosen the dependency version constraints in pyproject.toml. See https://pdm.fming.dev/latest/usage/dependency//#solve-the-locking-failure for more details.
Traceback (most recent call last):
  File "/home/robin/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/robin/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/core.py", line 254, in main
    return Core().main(args)
  File "/home/robin/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/core.py", line 187, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/home/robin/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/core.py", line 182, in main
    f(options.project, options)
  File "/home/robin/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/cli/commands/install.py", line 57, in handle
    actions.do_lock(
  File "/home/robin/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/cli/actions.py", line 120, in do_lock
    raise ResolutionImpossible("Unable to find a resolution") from None
resolvelib.resolvers.ResolutionImpossible: Unable to find a resolution
```

</details>

<details>
<summary>requirements.txt contents</summary>

```
canonicalwebteam.flask-base==1.0.5
canonicalwebteam.http==1.0.3
canonicalwebteam.blog==6.4.0
canonicalwebteam.search==1.2.7
canonicalwebteam.templatefinder==1.0.0
canonicalwebteam.image-template==1.3.1
canonicalwebteam.discourse==5.0.1
python-dateutil==2.8.2
pytz==2020.5
maxminddb-geolite2==2018.703
Flask-OpenID==1.3.0
feedgen==0.9.0
feedparser==6.0.8
pymacaroons==0.13.0
pybreaker==0.7.0
Flask-WTF==0.15.1
requests==2.27.0
sqlalchemy==1.3.23
marshmallow==3.14.1
mistune==0.8.4
psycopg2-binary==2.9.3
pyyaml==5.4.1
ubuntu-release-info==21.1
launchpadlib==1.10.15.1
macaroonbakery==1.3.1
sortedcontainers==2.4.0
vcrpy-unittest==0.1.7
webargs==7.0.1
jinja2==3.0.3
```

</details>

**Comment by SmileyChris** [comment]
I pasted your requirements into `/tmp/pdm-test/requirements.txt` and ran the following. Everything ran fine!

```
/tmp/pdm-test> pdm init                                                                                                                                                                                                                                                        Creating a pyproject.toml for PDM...
Please enter the Python interpreter to use
0. /usr/bin/python3 (3.10)
1. /usr/bin/python (3.10)
2. /usr/bin/python3.10 (3.10)
3. /home/chris/.asdf/installs/python/3.9.7/bin/python3.9 (3.9)
4. /home/chris/.pyenv/versions/3.9.7/bin/python3.9 (3.9)
5. /home/chris/.pyenv/versions/3.8.12/bin/python3.8 (3.8)
6. /home/chris/.pyenv/versions/3.7.12/bin/python3.7m (3.7)
7. /home/chris/.pyenv/versions/3.7.12/bin/python3.7 (3.7)
8. /home/chris/.pyenv/versions/3.6.15/bin/python3.6m (3.6)
9. /home/chris/.pyenv/versions/3.6.15/bin/python3.6 (3.6)
10. /home/chris/.local/pipx/venvs/pdm/bin/python (3.10)
Please select (0): 
Using Python interpreter: /usr/bin/python3 (3.10)
Would you like to create a virtualenv with /usr/bin/python3? [y/n] (y): 
Virtualenv is created successfully at /tmp/pdm-test/.venv
Is the project a library that will be uploaded to PyPI [y/n] (n): 
License(SPDX name) (MIT): 
Author name (Chris Beaven): 
Author email (smileychris@gmail.com): 
Python requires('*' to allow any) (>=3.10): 
Changes are written to pyproject.toml.
Found following files from other formats that you may import:
0. /tmp/pdm-test/requirements.txt (requirements)
1. don't do anything, I will import later.
Please select: 0
Changes are written to pyproject.toml.

PDM 2.1.3 is installed, while 2.1.4 is available.
Please run `pipx upgrade pdm` to upgrade.
Run `pdm config check_update false` to disable the check.


/tmp/pdm-test> pdm lock                                                                                                                                                                                                                                                  🔒 Lock successful
Changes are written to pdm.lock.

PDM 2.1.3 is installed, while 2.1.4 is available.
Please run `pipx upgrade pdm` to upgrade.
Run `pdm config check_update false` to disable the check.


/tmp/pdm-test> pipx upgrade pdm                                                                                                                                                                                                                                       upgraded package pdm from 2.1.3 to 2.1.5 (location: /home/chris/.local/pipx/venvs/pdm)


/tmp/pdm-test> pdm lock                                                                                                                                                                                                                                                        🔒 Lock successful
Changes are written to pdm.lock.


/tmp/pdm-test> pdm install                                                                                                                                                                                                                                               Synchronizing working set with lock file: 101 to add, 0 to update, 0 to remove

  ✔ Install setuptools 65.4.1 successful
  ✔ Install blinker 1.5 successful
  ✔ Install async-timeout 4.0.2 successful
  ✔ Install beautifulsoup4 4.11.1 successful
  ✔ Install cachecontrol 0.12.11 successful
  ✔ Install canonicalwebteam.blog 6.4.0 successful
  ✔ Install bleach 5.0.1 successful
  ✔ Install canonicalwebteam.discourse 5.0.1 successful
  ✔ Install canonicalwebteam.flask-base 1.0.5 successful
  ✔ Install canonicalwebteam.http 1.0.3 successful
  ✔ Install canonicalwebteam.image-template 1.3.1 successful
  ✔ Install canonicalwebteam.search 1.2.7 successful
  ✔ Install canonicalwebteam.templatefinder 1.0.0 successful
  ✔ Install canonicalwebteam.yaml-responses 1.2.0 successful
  ✔ Install certifi 2022.9.24 successful
  ✔ Install charset-normalizer 2.0.12 successful
  ✔ Install click 8.1.3 successful
  ✔ Install decorator 5.1.1 successful
  ✔ Install cffi 1.15.1 successful
  ✔ Install defusedxml 0.7.1 successful
  ✔ Install deprecated 1.2.13 successful
  ✔ Install distro 1.7.0 successful
  ✔ Install feedparser 6.0.8 successful
  ✔ Install flask 1.1.2 successful
  ✔ Install flask-openid 1.3.0 successful
  ✔ Install flask-wtf 0.15.1 successful
  ✔ Install freezegun 1.2.2 successful
  ✔ Install cryptography 38.0.1 successful
  ✔ Install greenlet 1.1.2 successful
  ✔ Install gunicorn 20.1.0 successful
  ✔ Install httplib2 0.20.4 successful
  ✔ Install gevent 21.12.0 successful
  ✔ Install humanize 4.4.0 successful
  ✔ Install idna 3.4 successful
  ✔ Install itsdangerous 1.1.0 successful
  ✔ Install jaraco.classes 3.2.3 successful
  ✔ Install jeepney 0.8.0 successful
  ✔ Install jinja2 3.0.3 successful
  ✔ Install keyring 23.9.3 successful
  ✔ Install launchpadlib 1.10.15.1 successful
  ✔ Install feedgen 0.9.0 successful
  ✔ Install httpretty 1.1.4 successful
  ✔ Install lockfile 0.12.2 successful
  ✔ Install future 0.16.0 successful
  ✔ Install lazr.uri 1.0.6 successful
  ✔ Install markupsafe 2.0.1 successful
  ✔ Install marshmallow 3.14.1 successful
  ✔ Install lxml 4.9.1 successful
  ✔ Install lazr.restfulclient 0.14.4 successful
  ✔ Install mistune 0.8.4 successful
  ✔ Install macaroonbakery 1.3.1 successful
  ✔ Install more-itertools 8.14.0 successful
  ✔ Install msgpack 1.0.4 successful
  ✔ Install multidict 6.0.2 successful
  ✔ Install oauthlib 3.2.1 successful
  ✔ Install packaging 21.3 successful
  ✔ Install prometheus-client 0.7.1 successful
  ✔ Install mockredispy 2.9.3 successful
  ✔ Install protobuf 3.20.3 successful
  ✔ Install maxminddb 2.2.0 successful
  ✔ Install pycparser 2.21 successful
  ✔ Install pymacaroons 0.13.0 successful
  ✔ Install psycopg2-binary 2.9.3 successful
  ✔ Install pynacl 1.5.0 successful
  ✔ Install pyparsing 3.0.9 successful
  ✔ Install pyrfc3339 1.1 successful
  ✔ Install python-dateutil 2.8.2 successful
  ✔ Install python-frontmatter 1.0.0 successful
  ✔ Install python3-openid 3.2.0 successful
  ✔ Install pytz 2020.5 successful
  ✔ Install raven 6.10.0 successful
  ✔ Install redis 4.3.4 successful
  ✔ Install pybreaker 0.7.0 successful
  ✔ Install requests 2.27.0 successful
  ✔ Install secretstorage 3.3.3 successful
  ✔ Install six 1.16.0 successful
  ✔ Install sortedcontainers 2.4.0 successful
  ✔ Install soupsieve 2.3.2.post1 successful
  ✔ Install sgmllib3k 1.0.0 successful
  ✔ Install statsd 3.3.0 successful
  ✔ Install talisker 0.19.0 successful
  ✔ Install ua-parser 0.16.1 successful
  ✔ Install ubuntu-release-info 21.1 successful
  ✔ Install urllib3 1.26.12 successful
  ✔ Install user-agents 2.2.0 successful
  ✔ Install validators 0.20.0 successful
  ✔ Install vcrpy 4.2.1 successful
  ✔ Install vcrpy-unittest 0.1.7 successful
  ✔ Install wadllib 1.3.6 successful
  ✔ Install webargs 7.0.1 successful
  ✔ Install webencodings 0.5.1 successful
  ✔ Install werkzeug 1.0.1 successful
  ✔ Install wrapt 1.14.1 successful
  ✔ Install wtforms 3.0.1 successful
  ✔ Install yamlloader 1.1.0 successful
  ✔ Install yarl 1.8.1 successful
  ✔ Install maxminddb-geolite2 2018.703 successful
  ✔ Install zope.event 4.5.0 successful
  ✔ Install sqlalchemy 1.3.23 successful
  ✔ Install zope.interface 5.4.0 successful
  ✔ Install pyyaml 5.4.1 successful

🎉 All complete!
```

**Comment by frostming** [comment]
@nottrobin you may fail to include a `requires-python` in `pyproject.toml`

**Comment by frostming** [comment]
>Although I don't understand why this is. I would have assumed that not setting `requires-python` just means that I want it to try to use whatever version of Python is available

Correct, but `flask==1.1.2` can't be installed on an arbitrary Python version assumed by the metadata, so it is rejected. You add `requires-python` to tell PDM "hey, I will never use Python < 3.7", then `flask==1.1.2` becomes eligible.

**Comment by nottrobin** [comment]
> Correct, but `flask==1.1.2` can't be installed on an arbitrary Python version assumed by the metadata, so it is rejected. You add `requires-python` to tell PDM "hey, I will never use Python < 3.7", then `flask==1.1.2` becomes eligible.

I get that logic, but it seems like a very weird decision to me. I don't have an "arbitrary" version of Python, I have the version of Python that I have, which `pdm` can tell is `3.10`. It seems incredibly obtuse of `pdm` to refuse to install something that could definitely be installed (and would be installed by other tools) based on some hypothetical situation that doesn't currently exist.

> @frostming: It is always recommended to run pdm init on a project without pyproject.toml.

If that's the case then `pdm install` should show me an error when there's no `pyproject.toml` (ideally with a message explaining that I need to run `pdm init` first). If `pdm install` goes ahead and tries to generate the `pyproject.toml` from my `requirements.txt` without complaining, then that forms part of its formal interface, part of its contract with the user, and it should aim to succeed to the best of its ability.

**Comment by pawamoy** [comment]
I guess PDM could indeed abort with an error earlier when `requires-python` isn't set.

**Comment by frostming** [comment]
> based on some hypothetical situation that doesn't currently exist.

It doesn't currently exist, but it *may* exist. `pdm.lock` is made to be shared with different people and environments. It is meaningless to generate a lock file that is only eligible for your current environment, while tools like `pip` do that. You can't assume what python version will be used by end users unless you tell them. `requires-python` acts as an install-time requirement or deploy guideline.

**Comment by nottrobin** [comment]
> @frostming: It doesn't currently exist, but it may exist. pdm.lock is made to be shared with different people and environments. It is meaningless to generate a lock file that is only eligible for your current environment, while tools like pip do that. You can't assume what python version will be used by end users unless you tell them. requires-python acts as an install-time requirement or deploy guideline.

Ah I see. Yes this is fair enough. In which case, as @pawamoy says, it would be nice if the error message could explain that possibility.

**Comment by nottrobin** [comment]
Actually, given this requirement to generate a reliable lockfile from a `requirements.txt` that doesn't give any Python version constraints, I can think of 2 behaviours PDM could have as it attempts to generate `pyproject.toml` which are probably more helpful than just complaining that `requires-python` doesn't exist:

1. Infer the version constraints from what it can find out about the packages in `requirements.txt` (I don't know to what extent this is possible, but since PDM was able to know that there existed a hypothetical version of Python where my dependencies couldn't be installed, doesn't that mean it must know what version of Python it *would* succeed with?)
2. Interactively ask the user to specify the Python version constraints (perhaps suggesting `>={current version}` as the default)

**Comment by nottrobin** [comment]
Nice work thanks @frostming !
