### ISSUE TITLE
Adding some dependencies to a project can override pdm's dependencies

### ISSUE THREAD

**Issue by joeblackwaslike** [pdm-project/pdm#1425]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce
1. Create a new project with default options `pdm init`
2. Add quart as a dependency: `pdm add quart`
3. Try to install: `pdm install`, or try to add another dependency: `pdm add aiocache`, or try to run help: `pdm --help`.

## Actual behavior
```zsh
$ pdm add aiocache
```
```
Traceback (most recent call last):
  File "/Users/joeblack/.local/bin/pdm", line 10, in <module>
    sys.exit(main())
  File "/Users/joeblack/Library/Application Support/pdm/venv/lib/python3.7/site-packages/pdm/core.py", line 254, in main
    return Core().main(args)
  File "/Users/joeblack/Library/Application Support/pdm/venv/lib/python3.7/site-packages/pdm/core.py", line 55, in __init__
    self.load_plugins()
  File "/Users/joeblack/Library/Application Support/pdm/venv/lib/python3.7/site-packages/pdm/core.py", line 240, in load_plugins
    entry_points.get("pdm", []), entry_points.get("pdm.plugin", [])
AttributeError: 'EntryPoints' object has no attribute 'get'
```

Looking at the pdm.lock file I can see the following transitive dependency:
```toml
[[package]]
name = "importlib-metadata"
version = "5.0.0"
requires_python = ">=3.7"
summary = "Read metadata from Python packages"
dependencies = [
    "typing-extensions>=3.6.4; python_version < \"3.8\"",
    "zipp>=0.5",
]
```
I do believe the root cause of this issue is that pdm is now pulling in this different version of importlib_metadata.  I would also say because of this, that this issue is probably only reproducible on python 3.7 since this is a backport package of python 3.8 behavior.

I decided to edit the core.py file seen above in the stacktrace to add some fault tolerance to it, and was successful.  Now `pdm install`, `pdm add aiocache`, and `pdm --help` are all successful.

Here is the original faulty code in core.py:
```python
for plugin in itertools.chain(
    entry_points.get("pdm", []), entry_points.get("pdm.plugin", [])
):
```

Here is the version with a fallback behavior:
```python
try:
    plugins = itertools.chain(
        entry_points.get("pdm", []), entry_points.get("pdm.plugin", [])
    )
except AttributeError:
    plugins = itertools.chain(
        entry_points.select(group="pdm"), entry_points.select(group="pdm.plugin")
    )
for plugin in plugins:
```

## Expected behavior

I would have expected the following:

```zsh
$ pdm install
All packages are synced to date, nothing to do.

🎉 All complete!
```

```zsh
$ pdm add aiocache
Adding packages to default dependencies: aiocache
🔒 Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
All packages are synced to date, nothing to do.

🎉 All complete!
```

```zsh
$ pdm --help
Usage: pdm [-h] [-V] [-c CONFIG] [-v] [-I] [--pep582 [SHELL]]
           {add,build,cache,completion,config,export,import,info,init,install,list,lock,plugin,publish,remove,run,search,show,sync,update,use,venv}
           ...

    ____  ____  __  ___
   / __ \/ __ \/  |/  /
  / /_/ / / / / /|_/ /
 / ____/ /_/ / /  / /
/_/   /_____/_/  /_/

Commands:
  {add,build,cache,completion,config,export,import,info,init,install,list,lock,plugin,publish,remove,run,search,show,sync,update,use,venv}
    add
...
```

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.1.5
Python Interpreter:
  /Users/joeblack/.pyenv/versions/3.7.13/bin/python (3.7)
Project Root:
  /Users/joeblack/projects/github/magiclabs/magic-auth-pocs/joeblackwaslike/aiocache_poc
Project Packages:
  /Users/joeblack/projects/github/magiclabs/magic-auth-pocs/joeblackwaslike/aiocache_poc/__pypackages__/3.7
```
```json
{
  "implementation_name": "cpython",
  "implementation_version": "3.7.13",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "21.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000",
  "python_full_version": "3.7.13",
  "platform_python_implementation": "CPython",
  "python_version": "3.7",
  "sys_platform": "darwin"
}
```

**Comment by lecardozo** [comment]
I guess this is the expected behavior when having PDM installed in the same environment used by your project. 🤔  You could overcome this limitation by running PDM in an isolated environment (either using pipx or some of the other methods listed [here](https://pdm.fming.dev/latest/#recommended-installation-method))

**Comment by frostming** [comment]
Same issue reported: #849
