### ISSUE TITLE
Unhandled SSLError during project initialization

### ISSUE THREAD

**Issue by gryznar** [pdm-project/pdm#1446]
- [ x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

Initialize environment via `pdm init` with self-signed certificate

## Actual behavior

```python
Traceback (most recent call last):
  File "C:\Users\gr29906\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\gr29906\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\gr29906\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\gr29906\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\gr29906\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\Users\gr29906\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\gr29906\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\gr29906\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1070, in _create
    self.do_handshake()
  File "C:\Users\gr29906\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gr29906\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\gr29906\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "C:\Users\gr29906\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "C:\Users\gr29906\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "C:\Users\gr29906\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\gr29906\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pdm/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CER
TIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gr29906\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\gr29906\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\gr29906\AppData\Local\Programs\Python\Python310\Scripts\pdm.exe\__main__.py", line 7, in <module>
  File "C:\Users\gr29906\AppData\Local\Programs\Python\Python310\lib\site-packages\pdm\core.py", line 254, in main
    return Core().main(args)
  File "C:\Users\gr29906\AppData\Local\Programs\Python\Python310\lib\site-packages\pdm\core.py", line 201, in main
    check_update(options.project)
  File "C:\Users\gr29906\AppData\Local\Programs\Python\Python310\lib\site-packages\pdm\cli\actions.py", line 899, in check_update
    latest_version = get_latest_version(project)
  File "C:\Users\gr29906\AppData\Local\Programs\Python\Python310\lib\site-packages\pdm\cli\actions.py", line 875, in get_latest_version
    candidate = finder.find_best_match("pdm").best
  File "C:\Users\gr29906\AppData\Local\Programs\Python\Python310\lib\site-packages\unearth\finder.py", line 316, in find_best_match
    candidates = list(
  File "C:\Users\gr29906\AppData\Local\Programs\Python\Python310\lib\site-packages\unearth\finder.py", line 258, in _find_packages_from_requirement
    yield from self._find_packages(requirement.name, allow_yanked, hashes)
  File "C:\Users\gr29906\AppData\Local\Programs\Python\Python310\lib\site-packages\unearth\finder.py", line 216, in _find_packages
    yield from self._evaluate_links(
  File "C:\Users\gr29906\AppData\Local\Programs\Python\Python310\lib\site-packages\unearth\collector.py", line 86, in collect_links_from_location
    yield from _collect_links_from_html(session, location)
  File "C:\Users\gr29906\AppData\Local\Programs\Python\Python310\lib\site-packages\unearth\collector.py", line 104, in _collect_links_from_html
    page = fetch_page(session, location)
  File "C:\Users\gr29906\AppData\Local\Programs\Python\Python310\lib\site-packages\unearth\collector.py", line 94, in fetch_page
    resp = _get_html_response(session, location)
  File "C:\Users\gr29906\AppData\Local\Programs\Python\Python310\lib\site-packages\unearth\collector.py", line 118, in _get_html_response
    resp = session.get(
  File "C:\Users\gr29906\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "C:\Users\gr29906\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\gr29906\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\gr29906\AppData\Local\Programs\Python\Python310\lib\site-packages\cachecontrol\adapter.py", line 57, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "C:\Users\gr29906\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pdm/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFI
CATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))
```

## Expected behavior

Error should be handled or if it is not possible directly, there should be tips for user how to solve this problem on his own.

**Comment by frostming** [comment]
PDM doesn't handle such errors in the lower-level dependencies because it is not expected in PDM. In fact, it may happen in any program that uses `requests` or `urllib3`. Just google it for the solution.

**Comment by pawamoy** [comment]
You could also try to set `pdm config check_update false` before running `pdm init`.
