### ISSUE TITLE
pdm install fails with huge dependency

### ISSUE THREAD

**Issue by kayhuba** [pdm-project/pdm#1525]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

NOTE: The dependency below will try and download a file of ~2.3GB size.

## Steps to reproduce

Given the following `pyproject.toml`:

```
[project]
name = "pdm-issue"
version = "0.0.1"
description = "Issue in PDM when loading huge dependencies like pytorch with cuda"
dependencies = [
    "torch==1.13.0+cu117",
]
requires-python = ">=3.10"
license = {text = "MIT"}

[[tool.pdm.source]]
url = "https://download.pytorch.org/whl/cu117"
verify_ssl = true
name = "pytorch_cuda"

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"
```

Execute `pdm install`

## Actual behavior

On first `pdm install` it fails with the following Traceback:
```PowerShell
(.venv) PS C:\Users\Kay\dev\code\python\pdm-issue> pdm install -v
Lock file does not exist
Updating the lock file...
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   torch==1.13.0+cu117
pdm.termui:   python>=3.10
pdm.termui:   Adding requirement torch==1.13.0+cu117
pdm.termui:   Adding requirement python>=3.10
pdm.termui: ======== Starting round 0 ========
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
unearth: Downloading <Link https://download.pytorch.org/whl/cu117/torch-1.13.0%2Bcu117-cp310-cp310-win_amd64.whl (from None)> to C:\Users\Kay\AppData\Local\Temp\pdm-build-c70qvn0x\torch-1.13.0+cu117-cp310-cp310-win_amd64.whl
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm.exe\__main__.py", line 7, in <module>
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\pdm\core.py", line 258, in main
    return Core().main(args)
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\pdm\core.py", line 190, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\pdm\core.py", line 185, in main
    f(project, options)
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\pdm\cli\commands\install.py", line 58, in handle
    actions.do_lock(
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\pdm\cli\actions.py", line 99, in do_lock
    mapping, dependencies = resolve(
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\pdm\resolver\core.py", line 30, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\resolvelib\resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\resolvelib\resolvers.py", line 373, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\resolvelib\resolvers.py", line 213, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\resolvelib\resolvers.py", line 203, in _get_updated_criteria
    for requirement in self._p.get_dependencies(candidate=candidate):
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\pdm\resolver\providers.py", line 187, in get_dependencies
    deps, requires_python, _ = self.repository.get_dependencies(candidate)
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\pdm\models\repositories.py", line 78, in get_dependencies
    requirements, requires_python, summary = getter(candidate)
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\pdm\models\repositories.py", line 35, in wrapper
    result = func(self, candidate)
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\pdm\models\repositories.py", line 235, in _get_dependencies_from_metadata
    deps = prepared.get_dependencies_from_metadata()
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\pdm\models\candidates.py", line 521, in get_dependencies_from_metadata
    self.req.project_name, self.metadata.requires or [], extras  # type: ignore
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\pdm\models\candidates.py", line 505, in metadata
    result = self.prepare_metadata()
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\pdm\models\candidates.py", line 440, in prepare_metadata
    self.obtain(allow_all=True)
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\pdm\models\candidates.py", line 430, in obtain
    result = finder.download_and_unpack(
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\unearth\finder.py", line 356, in download_and_unpack
    file = unpack_link(
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\unearth\preparer.py", line 307, in unpack_link
    for chunk in resp.iter_content(chunk_size=READ_CHUNK_SIZE):
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\requests\models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\urllib3\response.py", line 627, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\urllib3\response.py", line 566, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\urllib3\response.py", line 532, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
    self._close()
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\cachecontrol\filewrapper.py", line 76, in _close
    self.__callback(result)
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\cachecontrol\controller.py", line 353, in cache_response
    self._cache_set(cache_url, request, response, body, expires_time)
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\cachecontrol\controller.py", line 274, in _cache_set
    self.serializer.dumps(request, response, body),
Project Root:
  C:/Users/Kay/dev/code/python/pdm-issue
Project Packages:
  None
```

A second time executed it yields a `MemoryError`:

```PowerShell
(.venv) PS C:\Users\Kay\dev\code\python\pdm-issue> pdm install -v            
Lock file does not exist
Updating the lock file...
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   torch==1.13.0+cu117                   
pdm.termui:   python>=3.10                          
pdm.termui:   Adding requirement torch==1.13.0+cu117
pdm.termui:   Adding requirement python>=3.10
pdm.termui: ======== Starting round 0 ========
pdm.termui: Pinning: python None              
pdm.termui: ======== Ending round 0 ========  
pdm.termui: ======== Starting round 1 ========
unearth: Downloading <Link https://download.pytorch.org/whl/cu117/torch-1.13.0%2Bcu117-cp310-cp310-win_amd64.whl (from None)> to C:\Users\Kay\AppData\Local\Temp\pdm-build-9673vhda\torch-1.13.0+cu117-cp310-cp310-win_amd64.whl
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,                                                                                                          
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code           
    exec(code, run_globals)                                                                                                                             
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm.exe\__main__.py", line 7, in <module>                                                      
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\pdm\core.py", line 258, in main                                     
    return Core().main(args)                                                                                                                            
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\pdm\core.py", line 190, in main                                     
    raise cast(Exception, err).with_traceback(traceback)
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\pdm\core.py", line 185, in main
    f(project, options)
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\pdm\cli\commands\install.py", line 58, in handle
    actions.do_lock(
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\pdm\cli\actions.py", line 99, in do_lock
    mapping, dependencies = resolve(
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\pdm\resolver\core.py", line 30, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\resolvelib\resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\resolvelib\resolvers.py", line 373, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\resolvelib\resolvers.py", line 213, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\resolvelib\resolvers.py", line 203, in _get_updated_criteria
    for requirement in self._p.get_dependencies(candidate=candidate):
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\pdm\resolver\providers.py", line 187, in get_dependencies
    deps, requires_python, _ = self.repository.get_dependencies(candidate)
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\pdm\models\repositories.py", line 78, in get_dependencies
    requirements, requires_python, summary = getter(candidate)
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\pdm\models\repositories.py", line 35, in wrapper
    result = func(self, candidate)
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\pdm\models\repositories.py", line 235, in _get_dependencies_from_metadata
    deps = prepared.get_dependencies_from_metadata()
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\pdm\models\candidates.py", line 521, in get_dependencies_from_metadata
    self.req.project_name, self.metadata.requires or [], extras  # type: ignore
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\pdm\models\candidates.py", line 505, in metadata
    result = self.prepare_metadata()
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\pdm\models\candidates.py", line 440, in prepare_metadata
    self.obtain(allow_all=True)
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\pdm\models\candidates.py", line 430, in obtain
    result = finder.download_and_unpack(
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\unearth\finder.py", line 356, in download_and_unpack
    file = unpack_link(
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\unearth\preparer.py", line 307, in unpack_link
    for chunk in resp.iter_content(chunk_size=READ_CHUNK_SIZE):
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\requests\models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\urllib3\response.py", line 627, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\urllib3\response.py", line 566, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\urllib3\response.py", line 532, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\cachecontrol\filewrapper.py", line 96, in read
    self._close()
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\cachecontrol\filewrapper.py", line 76, in _close
    self.__callback(result)
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\cachecontrol\controller.py", line 353, in cache_response
    self._cache_set(cache_url, request, response, body, expires_time)
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\cachecontrol\controller.py", line 274, in _cache_set
    self.serializer.dumps(request, response, body),
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\cachecontrol\serialize.py", line 70, in dumps
    return b",".join([b"cc=4", msgpack.dumps(data, use_bin_type=True)])
  File "C:\Users\Kay\AppData\Local\Microsoft\WindowsApps\pdm\venv\lib\site-packages\msgpack\__init__.py", line 38, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack\_packer.pyx", line 294, in msgpack._cmsgpack.Packer.pack
  File "msgpack\_packer.pyx", line 300, in msgpack._cmsgpack.Packer.pack
  File "msgpack\_packer.pyx", line 297, in msgpack._cmsgpack.Packer.pack
  File "msgpack\_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack\_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
MemoryError
```

## Expected behavior

Dependency is downloaded and installed

## Environment Information

```PowerShell
# Paste the output of `pdm info && pdm info --env` below:
(.venv) PS C:\Users\Kay\dev\code\python\pdm-issue> pdm info
PDM version:
  2.2.1
Python Interpreter:
  C:\Users\Kay\dev\code\python\pdm-issue\.venv\Scripts\python.EXE (3.10)
Project Root:
  C:/Users/Kay/dev/code/python/pdm-issue
Project Packages:
  None

(.venv) PS C:\Users\Kay\dev\code\python\pdm-issue> pdm info --env            
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.8",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19044",
  "python_full_version": "3.10.8",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "win32"
}
```

Machine has `64GB` physical RAM installed.

**Comment by frostming** [comment]
I didn't reproduce it on my 32G ram machine

**Comment by Matthieu-LAURENT39** [comment]
I could reproduce the issue, and i think it has to do with the fact PDM will always write to /tmp/, which on most Linux system means it will write to RAM.
When installing huge packages, it means every package ends up being stored in RAM.
This can get especially bad after a few failed installs, since PDM doesn't clean up the old install folders, so you end up out of RAM very fast.
