### ISSUE TITLE
Project install fails when a branch with pyproject.toml file is specified as a dependency

### ISSUE THREAD

**Issue by denver-lloyd** [pdm-project/pdm#1559]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

I am trying to install a repository from git that requires another git repository as a dependency. I have created two dummy repos for replicating the issue I am observing. 

**Repo 1:** 

https://github.com/denver-lloyd/validation_utility

this repo installs the environment just fine and has no issues.

**Repo 2:**

https://github.com/denver-lloyd/register_api

this repo has repo1 as a dependency and the lock file builds just fine, but the environment will not install with the following error:

```
resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=VcsRequirement(name=None, marker=None, extras=None, specifier=None, editable=False, prerelease=False, url='git+https://gittf.ams-osram.info/cis_validation/validation_utility.git', path=None, subdirectory=None, vcs='git', ref='main', revision=None), parent=None)]
```

It is not clear why this would occur when comparing the two pyroject.toml files.
**steps to reproduce:**

`git pull https://github.com/denver-lloyd/register_api`

`cd register_api`

`pdm install -v`

## Actual behavior

```
C:\workspace1\register_api>pdm install -v
Lock file does not exist
Updating the lock file...
Virtualenv C:\workspace1\register_api\.venv is reused.
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   git+https://github.com/denver-lloyd/validation_utility.git@main
pdm.termui:   pytest
pdm.termui:   python>=3.8
pdm.termui:   Adding requirement git+https://github.com/denver-lloyd/validation_utility.git@main
unearth: Cloning https://github.com/denver-lloyd/validation_utility.git (revision: main) to C:\Users\dlly\AppData\Local\Temp\pdm-build-y_2xtz00
unearth: Resolved https://github.com/denver-lloyd/validation_utility.git to commit f4e314cc1ae1a574ad163642d6225612d44742b7
pdm.termui:   Adding requirement pytest
pdm.termui:   Adding requirement python>=3.8
pdm.termui: ======== Starting round 0 ========
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
pdm.termui: Pinning: validation_utility 0.2.0a0
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
pdm.termui:   Adding requirement attrs>=19.2.0(from pytest 7.2.0)
pdm.termui:   Adding requirement iniconfig(from pytest 7.2.0)
pdm.termui:   Adding requirement packaging(from pytest 7.2.0)
pdm.termui:   Adding requirement pluggy<2.0,>=0.12(from pytest 7.2.0)
pdm.termui:   Adding requirement exceptiongroup>=1.0.0rc8; python_version < "3.11"(from pytest 7.2.0)
pdm.termui:   Adding requirement tomli>=1.0.0; python_version < "3.11"(from pytest 7.2.0)
pdm.termui:   Adding requirement colorama; sys_platform == "win32"(from pytest 7.2.0)
pdm.termui: Pinning: pytest 7.2.0
pdm.termui: ======== Ending round 2 ========
pdm.termui: ======== Starting round 3 ========
pdm.termui: Pinning: pluggy 1.0.0
pdm.termui: ======== Ending round 3 ========
pdm.termui: ======== Starting round 4 ========
pdm.termui: Pinning: attrs 22.1.0
pdm.termui: ======== Ending round 4 ========
pdm.termui: ======== Starting round 5 ========
pdm.termui: Pinning: exceptiongroup 1.0.4
pdm.termui: ======== Ending round 5 ========
pdm.termui: ======== Starting round 6 ========
pdm.termui: Pinning: tomli 2.0.1
pdm.termui: ======== Ending round 6 ========
pdm.termui: ======== Starting round 7 ========
pdm.termui: Pinning: colorama 0.4.6
pdm.termui: ======== Ending round 7 ========
pdm.termui: ======== Starting round 8 ========
pdm.termui: Pinning: iniconfig 1.1.1
pdm.termui: ======== Ending round 8 ========
pdm.termui: ======== Starting round 9 ========
pdm.termui: Pinning: packaging 22.0
pdm.termui: ======== Ending round 9 ========
pdm.termui: ======== Starting round 10 ========
pdm.termui: ======== Resolution Result ========
pdm.termui: Stable pins:
pdm.termui:               python None
pdm.termui:   :empty:idimKbEqSqw git+https://github.com/denver-lloyd/validation_utility.git@f4e314cc1ae1a574ad163642d6225612d44742b7
pdm.termui:               pytest 7.2.0
pdm.termui:               pluggy 1.0.0
pdm.termui:                attrs 22.1.0
pdm.termui:       exceptiongroup 1.0.4
pdm.termui:                tomli 2.0.1
pdm.termui:             colorama 0.4.6
pdm.termui:            iniconfig 1.1.1
pdm.termui:            packaging 22.0
🔒 Lock successful
Changes are written to pdm.lock.
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\resolvelib\resolvers.py", line 372, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "C:\Anaconda3\lib\site-packages\resolvelib\resolvers.py", line 173, in _add_to_criteria
    raise RequirementsConflicted(criterion)
resolvelib.resolvers.RequirementsConflicted: Requirements conflict: VcsRequirement(name=None, marker=None, extras=None, specifier=None, editable=False, prerelease=False, url='git+https://github.com/denver-lloyd/validation_utility.git', path=None, subdirectory=None, vcs='git', ref='main', revision=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\Scripts\pdm.exe\__main__.py", line 7, in <module>
  File "C:\Anaconda3\lib\site-packages\pdm\core.py", line 258, in main
    return Core().main(args)
  File "C:\Anaconda3\lib\site-packages\pdm\core.py", line 190, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "C:\Anaconda3\lib\site-packages\pdm\core.py", line 185, in main
    f(project, options)
  File "C:\Anaconda3\lib\site-packages\pdm\cli\commands\install.py", line 62, in handle
    actions.do_sync(
  File "C:\Anaconda3\lib\site-packages\pdm\cli\actions.py", line 197, in do_sync
    candidates = resolve_candidates_from_lockfile(project, requirements)
  File "C:\Anaconda3\lib\site-packages\pdm\cli\actions.py", line 140, in resolve_candidates_from_lockfile
    mapping, *_ = resolve(
  File "C:\Anaconda3\lib\site-packages\pdm\resolver\core.py", line 35, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "C:\Anaconda3\lib\site-packages\resolvelib\resolvers.py", line 521, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Anaconda3\lib\site-packages\resolvelib\resolvers.py", line 374, in resolve
    raise ResolutionImpossible(e.criterion.information)
resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=VcsRequirement(name=None, marker=None, extras=None, specifier=None, editable=False, prerelease=False, url='git+https://github.com/denver-lloyd/validation_utility.git', path=None, subdirectory=None, vcs='git', ref='main', revision=None), parent=None)]
```

## Expected behavior

```
C:\workspace1\validation_utility>pdm install
Lock file does not exist
Updating the lock file...
python.use_venv is on, creating a virtualenv for this project...
Virtualenv is created successfully at C:\workspace1\validation_utility\.venv
🔒 Lock successful
Changes are written to pdm.lock.
Synchronizing working set with lock file: 8 to add, 0 to update, 0 to remove

  ✔ Install iniconfig 1.1.1 successful
  ✔ Install colorama 0.4.6 successful
  ✔ Install pluggy 1.0.0 successful
  ✔ Install tomli 2.0.1 successful
  ✔ Install packaging 22.0 successful
  ✔ Install exceptiongroup 1.0.4 successful
  ✔ Install attrs 22.1.0 successful
  ✔ Install pytest 7.2.0 successful
Installing the project as an editable package...
  ✔ Install validation_utility 0.2.0a0 successful

🎉 All complete!
```

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:

PDM version:
  2.3.1
Python Interpreter:
  C:\workspace1\register_api\.venv\Scripts\python.exe (3.9)
Project Root:
  C:/workspace1/register_api
Project Packages:
  None
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.7",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19044",
  "python_full_version": "3.9.7",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "win32"
}

```

**Comment by frostming** [comment]
`git+https://github.com/denver-lloyd/validation_utility.git@main` isn't a valid [PEP 508] requirement string, the name part is missing, change it to:

```
validation-utility @ git+https://github.com/denver-lloyd/validation_utility.git@main
```

**Comment by denver-lloyd** [comment]
Thank you for the quick feedback and help, much appreciated.

Best,
Denver
