### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by tintinthong** [pdm-project/pdm#1565]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

I upgraded pdm to 2.3.2 but can't seem to install

```
[project]
name = "cardpay-reward-indexer"
version = "0.1.0"
description = ""
authors = [
    {name = "tintinthong", email = "justin.thong@cardstack.com"},
]
dependencies = [
    "schedule>=1.1.0",
    "pydantic>=1.9.1",
    "cloudpathlib[s3]>=0.9.0",
    "pyarrow>=8.0.0",
    "eth-abi>=2.1.1",
    "requests>=2.28.0",
    "hexbytes>=0.2.2",
    "sqlalchemy>=1.4.37",
    "psycopg2>=2.9.3",
    "eth-hash[pycryptodome]>=0.3.2",
    "sentry-sdk>=1.5.12",
    "web3>=5.29.2",
]
requires-python = ">=3.9"
license = {text = "MIT"}
[project.optional-dependencies]

[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "pytest>=7.1.2",
    "isort>=5.10.1",
    "black>=22.3.0",
    "flake8>=4.0.1",
]

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

[tool.pdm.scripts]
main = "python -m cardpay_reward_indexer.main"
check_sync = "python -m scripts.check_sync"
```

```
pdm install -d
```

## Actual behavior

```
pdm.termui: ======== Starting round 30 ========
pdm.termui:   Adding requirement aiohttp<4,>=3.7.4.post0(from web3 5.31.3)
pdm.termui:   Adding requirement eth-abi<3.0.0,>=2.2.0(from web3 5.31.3)
pdm.termui:   Adding requirement eth-account<0.6.0,>=0.5.9(from web3 5.31.3)
pdm.termui:   Adding requirement eth-hash[pycryptodome]<1.0.0,>=0.2.0(from web3 5.31.3)
pdm.termui:   Adding requirement eth-rlp<0.3(from web3 5.31.3)
pdm.termui:   Adding requirement eth-typing<3.0.0,>=2.0.0(from web3 5.31.3)
pdm.termui:   Adding requirement eth-utils<2.0.0,>=1.9.5(from web3 5.31.3)
pdm.termui:   Adding requirement hexbytes<1.0.0,>=0.1.0(from web3 5.31.3)
pdm.termui:   Adding requirement ipfshttpclient==0.8.0a2(from web3 5.31.3)
pdm.termui:   Adding requirement jsonschema<5,>=3.2.0(from web3 5.31.3)
pdm.termui:   Adding requirement lru-dict<2.0.0,>=1.1.6(from web3 5.31.3)
pdm.termui:   Adding requirement protobuf==3.19.5(from web3 5.31.3)
pdm.termui:   Adding requirement requests<3.0.0,>=2.16.0(from web3 5.31.3)
pdm.termui:   Adding requirement websockets<10,>=9.1(from web3 5.31.3)
pdm.termui:   Adding requirement pywin32>=223; platform_system == "Windows"(from web3 5.31.3)
pdm.termui:   Adding requirement b''(from web3 5.31.3)
Traceback (most recent call last):
  File "/opt/homebrew/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.3.2/libexec/lib/python3.11/site-packages/pdm/core.py", line 258, in main
    return Core().main(args)
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.3.2/libexec/lib/python3.11/site-packages/pdm/core.py", line 190, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/opt/homebrew/Cellar/pdm/2.3.2/libexec/lib/python3.11/site-packages/pdm/core.py", line 185, in main
    f(project, options)
  File "/opt/homebrew/Cellar/pdm/2.3.2/libexec/lib/python3.11/site-packages/pdm/cli/commands/install.py", line 58, in handle
    actions.do_lock(
  File "/opt/homebrew/Cellar/pdm/2.3.2/libexec/lib/python3.11/site-packages/pdm/cli/actions.py", line 95, in do_lock
    mapping, dependencies = resolve(
                            ^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.3.2/libexec/lib/python3.11/site-packages/pdm/resolver/core.py", line 35, in resolve
    result = resolver.resolve(requirements, max_rounds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.3.2/libexec/lib/python3.11/site-packages/resolvelib/resolvers.py", line 521, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.3.2/libexec/lib/python3.11/site-packages/resolvelib/resolvers.py", line 402, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.3.2/libexec/lib/python3.11/site-packages/resolvelib/resolvers.py", line 238, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.3.2/libexec/lib/python3.11/site-packages/resolvelib/resolvers.py", line 229, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "/opt/homebrew/Cellar/pdm/2.3.2/libexec/lib/python3.11/site-packages/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/opt/homebrew/Cellar/pdm/2.3.2/libexec/lib/python3.11/site-packages/resolvelib/structs.py", line 127, in __bool__
    next(iter(self))
         ^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.3.2/libexec/lib/python3.11/site-packages/resolvelib/structs.py", line 136, in __iter__
    self._factory() if self._iterable is None else self._iterable
    ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.3.2/libexec/lib/python3.11/site-packages/pdm/resolver/providers.py", line 150, in matches_gen
    candidates = self._find_candidates(reqs[0])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.3.2/libexec/lib/python3.11/site-packages/pdm/resolver/providers.py", line 127, in _find_candidates
    can = make_candidate(requirement)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.3.2/libexec/lib/python3.11/site-packages/pdm/models/candidates.py", line 623, in make_candidate
    return Candidate(req, name, version, link)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.3.2/libexec/lib/python3.11/site-packages/pdm/models/candidates.py", line 142, in __init__
    link = req.as_file_link()  # type: ignore
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.3.2/libexec/lib/python3.11/site-packages/pdm/models/requirements.py", line 325, in as_file_link
    return Link(url)
           ^^^^^^^^^
  File "<string>", line 7, in __init__
  File "/opt/homebrew/Cellar/pdm/2.3.2/libexec/lib/python3.11/site-packages/unearth/link.py", line 48, in __post_init__
    if self.url.startswith(vcs_prefixes):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: a bytes-like object is required, not 'str'
```

## Expected behavior

Installation succesful

## Environment Information

```bash
PDM version:
  2.3.2
Python Interpreter:
  /opt/homebrew/opt/python@3.10/bin/python3.10 (3.10)
Project Root:
  /Users/tintinthong/Github/cardstack/packages/cardpay-reward-indexer
Project Packages:
  /Users/tintinthong/Github/cardstack/packages/cardpay-reward-indexer/__pypackages__/3.10
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.8",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "21.2.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 21.2.0: Sun Nov 28 20:29:10 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T8101",
  "python_full_version": "3.10.8",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
Same reason as https://github.com/pdm-project/pdm/issues/1556 and #1564  and for the workaround please see discussion https://github.com/pdm-project/pdm/issues/1558
