### ISSUE TITLE
Strange error when upgrading to 2.3.3

### ISSUE THREAD

**Issue by pgjones** [pdm-project/pdm#1572]
I'm running the following in a docker container as a non-root user,
```
pdm run -v hypercorn --config hypercorn.toml backend.run:app
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/nonexistent/.config/pdm/pep582'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/nonexistent/.config/pdm'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/nonexistent/.config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ve/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/ve/lib/python3.10/site-packages/pdm/core.py", line 258, in main
    return Core().main(args)
  File "/ve/lib/python3.10/site-packages/pdm/core.py", line 190, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/ve/lib/python3.10/site-packages/pdm/core.py", line 185, in main
    f(project, options)
  File "/ve/lib/python3.10/site-packages/pdm/cli/commands/run.py", line 391, in handle
    exit_code = runner.run(options.command, options.args)
  File "/ve/lib/python3.10/site-packages/pdm/cli/commands/run.py", line 324, in run
    return self._run_process(
  File "/ve/lib/python3.10/site-packages/pdm/cli/commands/run.py", line 167, in _run_process
    pythonpath = [get_pep582_path(project)] + [
  File "/ve/lib/python3.10/site-packages/pdm/cli/utils.py", line 735, in get_pep582_path
    script_dir.mkdir(parents=True, exist_ok=True)
  File "/usr/local/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/local/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/local/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/local/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/nonexistent'
$ ls /nonexistent
ls: cannot access '/nonexistent': No such file or directory
```
before 2.3.3 (with 2.3.2) this worked. I'm not sure what is going wrong here - any pointers?

**Comment by frostming** [comment]
Yes, it is caused by #1567. PDM tries to write the PEP 582 sitecustomize.py file into a user config directory. While in your exact case the home dir doesn't exist and isn't writable.

**Comment by pgjones** [comment]
Is the location PDM tries to write the PEP 582 sitecustomize.py file customisable?

**Comment by frostming** [comment]
Yes: 
```
 -c CONFIG, --config CONFIG
                        Specify another config file path(env var: PDM_CONFIG_FILE)
```
