### ISSUE TITLE
Problem resolving package that requires `python>=3.8,<3.11`

### ISSUE THREAD

**Issue by c6p** [pdm-project/pdm#1579]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

`pdm init` with python 3.10, `pdm add pyportfolioopt` will add 1.5.2. Then try to manually pin above 1.5.4:
```toml
[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
]
dependencies = [
    "pyportfolioopt>=1.5.4",
]
requires-python = ">=3.10"
license = {text = "MIT"}

```

## Actual behavior
It does not work `python>=3.8,<3.11` conflicts with `python>=3.10`. Trying to set `requires-python` to `3.8` or `3.9` or `3.10.4` does not work too.

Resolves to pyportfolioopt=1.5.2 which requires `python >=3.6.1,<4.0.0 `

```
❯ pdm update -v  
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   pyportfolioopt>=1.5.4
pdm.termui:   python>=3.10
pdm.termui:   Adding requirement pyportfolioopt>=1.5.4
pdm.termui:   Adding requirement python>=3.10
pdm.termui: ======== Starting round 0 ========
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
pdm.termui:   Adding requirement cvxpy<2.0.0,>=1.1.10(from pyportfolioopt 1.5.4)
pdm.termui:   Adding requirement numpy<2.0.0,>=1.22.4(from pyportfolioopt 1.5.4)
pdm.termui:   Adding requirement pandas>=0.19(from pyportfolioopt 1.5.4)
pdm.termui:   Adding requirement scipy<2.0,>=1.3(from pyportfolioopt 1.5.4)
pdm.termui:   Adding requirement python>=3.8,<3.11(from pyportfolioopt 1.5.4)
pdm.termui: Candidate rejected: pyportfolioopt@1.5.4 because it introduces a new requirement python>=3.8,<3.11 that conflicts with other requirements:
    python>=3.10 (from project)
pdm.termui:   Adding requirement cvxpy<2.0.0,>=1.1.10(from pyportfolioopt 1.5.4)
pdm.termui:   Adding requirement numpy<2.0.0,>=1.22.4(from pyportfolioopt 1.5.4)
pdm.termui:   Adding requirement pandas>=0.19(from pyportfolioopt 1.5.4)
pdm.termui:   Adding requirement scipy<2.0,>=1.3(from pyportfolioopt 1.5.4)
pdm.termui:   Adding requirement python>=3.8,<3.11(from pyportfolioopt 1.5.4)
pdm.termui: Candidate rejected: pyportfolioopt@1.5.4 because it introduces a new requirement python>=3.8,<3.11 that conflicts with other requirements:
    python>=3.10 (from project)
pdm.termui: Conflicts detected:
  python>=3.10 (from project)
  python>=3.8,<3.11 (from pyportfolioopt@1.5.4)
  python>=3.10 (from project)
  python>=3.8,<3.11 (from pyportfolioopt@1.5.4)
🔒 Lock failed
Unable to find a resolution because the following dependencies don't work on all Python versions defined by the project's `requires-python`: >=3.10.
  python>=3.8,<3.11 (from <Candidate pyportfolioopt@1.5.4 from https://pypi.org/simple/pyportfolioopt/>)
To fix this, you can change the value of `requires-python` in pyproject.toml.
Traceback (most recent call last):
  File "C:\Users\can\.pyenv\pyenv-win\versions\3.10.4\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\can\.pyenv\pyenv-win\versions\3.10.4\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\can\.pyenv\pyenv-win\versions\3.10.4\Scripts\pdm.exe\__main__.py", line 7, in <module>
  File "C:\Users\can\.pyenv\pyenv-win\versions\3.10.4\lib\site-packages\pdm\core.py", line 258, in main
    return Core().main(args)
  File "C:\Users\can\.pyenv\pyenv-win\versions\3.10.4\lib\site-packages\pdm\core.py", line 190, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "C:\Users\can\.pyenv\pyenv-win\versions\3.10.4\lib\site-packages\pdm\core.py", line 185, in main
    f(project, options)
  File "C:\Users\can\.pyenv\pyenv-win\versions\3.10.4\lib\site-packages\pdm\cli\commands\update.py", line 60, in handle
    actions.do_update(
  File "C:\Users\can\.pyenv\pyenv-win\versions\3.10.4\lib\site-packages\pdm\cli\actions.py", line 383, in do_update
    resolved = do_lock(
  File "C:\Users\can\.pyenv\pyenv-win\versions\3.10.4\lib\site-packages\pdm\cli\actions.py", line 114, in do_lock
    raise ResolutionImpossible("Unable to find a resolution") from None
resolvelib.resolvers.ResolutionImpossible: Unable to find a resolution
'int' is not recognized as an internal or external command,
operable program or batch file.
```

## Expected behavior

There shouldn't be any conflicts, since `3.8 <= 3.10 < 3.11`.

## Environment Information

```bash
PDM version:
  2.3.3
Python Interpreter:
  C:\Users\can\.pyenv\pyenv-win\versions\3.10.4\python.exe (3.10)
Project Root:
  C:/Users/can/Desktop/t
Project Packages:
  C:\Users\can\Desktop\t\__pypackages__\3.10
'platform' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by pawamoy** [comment]
The dependency claims to not be compatible with Python 3.11, while your project claims to be compatible this with. This is seen as an incompatibility by PDM which ensures the dependencies can be installed on every version of Python your project claims to support. The Python 4 upper bound is ignored I think, for practical reasons.

2 solutions: add a 3.11 upper bound to your project, or ask the maintainers of the dependency to remove theirs.

**Comment by c6p** [comment]
Thanks, @pawamoy. My understanding of  `requires-python` was wrong. A 3.11 upper bound has fixed the issue.
