### ISSUE TITLE
Unclear error when using dynamic version

### ISSUE THREAD

**Issue by neimad1985** [pdm-project/pdm#1591]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

- Install pdm v2.3.3 with python v3.11.1
- Paste the following in a **pyproject.toml** file:
```toml
[project]
name = "testpdm"
dynamic = ["version"]
requires-python = ">=3.11"

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

[tool.pdm]
```
- Execute the command:
```
pdm build -v
```
## Actual behavior

You will get the following error:
```
Building sdist...
pdm.termui: Preparing isolated env for PEP 517 build...
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   pdm-pep517
pdm.termui:   python>=3.11.1,<3.11.2
pdm.termui:   Adding requirement pdm-pep517
pdm.termui:   Adding requirement python>=3.11.1,<3.11.2
pdm.termui: ======== Starting round 0 ========
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
pdm.termui: Pinning: pdm-pep517 1.0.6
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
pdm.termui: ======== Resolution Result ========
pdm.termui: Stable pins:
pdm.termui:       python None
pdm.termui:   pdm-pep517 1.0.6
pdm.termui: Installing pdm-pep517 1.0.6
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/71/2a/ae8abd6ebb76edd97e0c3dc3e61913df438c17e44a9aed05fd2073bb800f/pdm_pep517-1.0.6-py3-none-any.whl (from None)>
pdm.termui: /tmp/pdm-build-env-a7dyn42b-shared/lib/python3.11/site-packages/pdm/pep517/sdist.py:53: PDMWarning: No license files are matched with glob patterns ['LICENSES/*', 'LICEN[CS]E*', 'COPYING*', 'NOTICE*', 'AUTHORS*'].
pdm.termui:   super()._find_files_iter(for_sdist), self.find_license_files()
pdm.termui: Traceback (most recent call last):
pdm.termui:   File "/home/neimad/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
pdm.termui:     main()
pdm.termui:   File "/home/neimad/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
pdm.termui:     json_out['return_val'] = hook(**hook_input['kwargs'])
pdm.termui:                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pdm.termui:   File "/home/neimad/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 304, in build_sdist
pdm.termui:     return backend.build_sdist(sdist_directory, config_settings)
pdm.termui:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pdm.termui:   File "/tmp/pdm-build-env-a7dyn42b-shared/lib/python3.11/site-packages/pdm/pep517/api.py", line 84, in build_sdist
pdm.termui:     return Path(builder.build(sdist_directory)).name
pdm.termui:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pdm.termui:   File "/tmp/pdm-build-env-a7dyn42b-shared/lib/python3.11/site-packages/pdm/pep517/sdist.py", line 72, in build
pdm.termui:     self._add_pyproject(tar, tar_dir)
pdm.termui:   File "/tmp/pdm-build-env-a7dyn42b-shared/lib/python3.11/site-packages/pdm/pep517/sdist.py", line 107, in _add_pyproject
pdm.termui:     tomli_w.dump(pyproject, bio)
pdm.termui:   File "/tmp/pdm-build-env-a7dyn42b-shared/lib/python3.11/site-packages/pdm/pep517/_vendor/tomli_w/_writer.py", line 33, in dump
pdm.termui:     for chunk in gen_table_chunks(__obj, ctx, name=""):
pdm.termui:   File "/tmp/pdm-build-env-a7dyn42b-shared/lib/python3.11/site-packages/pdm/pep517/_vendor/tomli_w/_writer.py", line 82, in gen_table_chunks
pdm.termui:     yield from gen_table_chunks(v, ctx, name=display_name, inside_aot=in_aot)
pdm.termui:   File "/tmp/pdm-build-env-a7dyn42b-shared/lib/python3.11/site-packages/pdm/pep517/_vendor/tomli_w/_writer.py", line 73, in gen_table_chunks
pdm.termui:     yield f"{format_key_part(k)} = {format_literal(v, ctx)}\n"
pdm.termui:                                     ^^^^^^^^^^^^^^^^^^^^^^
pdm.termui:   File "/tmp/pdm-build-env-a7dyn42b-shared/lib/python3.11/site-packages/pdm/pep517/_vendor/tomli_w/_writer.py", line 102, in format_literal
pdm.termui:     raise TypeError(f"Object of type {type(obj)} is not TOML serializable")
pdm.termui: TypeError: Object of type <class 'NoneType'> is not TOML serializable
Traceback (most recent call last):
  File "/home/neimad/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/neimad/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 258, in main
    return Core().main(args)
           ^^^^^^^^^^^^^^^^^
  File "/home/neimad/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 190, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/home/neimad/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 185, in main
    f(project, options)
  File "/home/neimad/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/cli/commands/build.py", line 66, in handle
    actions.do_build(
  File "/home/neimad/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/cli/actions.py", line 503, in do_build
    loc = SdistBuilder(project.root, project.environment).build(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neimad/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/builders/sdist.py", line 21, in build
    filename = self._hook.build_sdist(out_dir, config_settings)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neimad/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pyproject_hooks/_impl.py", line 292, in build_sdist
    return self._call_hook('build_sdist', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neimad/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pyproject_hooks/_impl.py", line 311, in _call_hook
    self._subprocess_runner(
  File "/home/neimad/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/builders/base.py", line 261, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/neimad/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/builders/base.py", line 107, in log_subprocessor
    raise build_error(e) from None
pdm.exceptions.BuildError: Build backend raised error: Showing the last 10 lines of the build output:
  File "/tmp/pdm-build-env-a7dyn42b-shared/lib/python3.11/site-packages/pdm/pep517/_vendor/tomli_w/_writer.py", line 33, in dump
    for chunk in gen_table_chunks(__obj, ctx, name=""):
  File "/tmp/pdm-build-env-a7dyn42b-shared/lib/python3.11/site-packages/pdm/pep517/_vendor/tomli_w/_writer.py", line 82, in gen_table_chunks
    yield from gen_table_chunks(v, ctx, name=display_name, inside_aot=in_aot)
  File "/tmp/pdm-build-env-a7dyn42b-shared/lib/python3.11/site-packages/pdm/pep517/_vendor/tomli_w/_writer.py", line 73, in gen_table_chunks
    yield f"{format_key_part(k)} = {format_literal(v, ctx)}\n"
                                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/pdm-build-env-a7dyn42b-shared/lib/python3.11/site-packages/pdm/pep517/_vendor/tomli_w/_writer.py", line 102, in format_literal
    raise TypeError(f"Object of type {type(obj)} is not TOML serializable")
TypeError: Object of type <class 'NoneType'> is not TOML serializable
```

Getting an error is totally normal here because I intentionally left the **[tool.pdm]** section empty.
I should have filled it this way, to test dynamic versioning:
```toml
[tool.pdm]
version = { source = "scm" }
```

The problem for me here is that the error output is unclear. It is difficult to guess what the error is about by reading the stack trace.

If for example I intentionally omitted the **project.name** property I would get this kind of error:
```
...
  File "/tmp/pdm-build-env-hmrxq6jw-shared/lib/python3.11/site-packages/pdm/pep517/validator.py", line 85, in validate_pep621
    raise PEP621ValidationError(validator.errors)
pdm.pep517.exceptions.PEP621ValidationError: {'name': ['required field']}
```

Here the error is clearly more understandable. We know that there is a problem with the **name** field. It would be better to have an even more precise error informing us that the problem comes from the **project.name** field, but anyway, we at least have something that gives us a clue.

In the case of the dynamic version field, we are clueless.

## Expected behavior

It would be nice to have a more verbose error in this case.

## Environment Information

```bash
PDM version:
  2.3.3
Python Interpreter:
  /home/neimad/tmp/testpdm/.venv/bin/python (3.11)
Project Root:
  /home/neimad/tmp/testpdm
Project Packages:
  None

PDM 2.3.3 is installed, while 2.3.4 is available.
Please run `pdm self update` to upgrade.
Run `pdm config check_update false` to disable the check.
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.1",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.4.0-135-generic",
  "platform_system": "Linux",
  "platform_version": "#152-Ubuntu SMP Wed Nov 23 20:19:22 UTC 2022",
  "python_full_version": "3.11.1",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "linux"
}

PDM 2.3.3 is installed, while 2.3.4 is available.
Please run `pdm self update` to upgrade.
Run `pdm config check_update false` to disable the check.
```

**Comment by neimad1985** [comment]
I just noticed that I was lagging with pdm v2.3.3, so I installed version v2.3.4.
The problem is the same.
And by the way, thanks for this lib, it's really nice :)
