### ISSUE TITLE
pdm installation kaleido error, use pip installation can be installed normally

### ISSUE THREAD

**Issue by banduoba** [pdm-project/pdm#1592]
- [ ] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce
pdm add kaleido -v

## Actual behavior
```bash
pdm.termui: Removing distribution None
  ✖ Update kaleido None -> 0.2.1.post1 failed
pdm.termui: Error occurs: 
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 265, in update_candidate
    self.manager.install(can)
  File "/usr/local/lib/python3.10/site-packages/pdm/installers/manager.py", line 39, in install
    installer(str(prepared.build()), self.environment, prepared.direct_url())
  File "/usr/local/lib/python3.10/site-packages/pdm/models/candidates.py", line 359, in build
    self.obtain(allow_all=False)
  File "/usr/local/lib/python3.10/site-packages/pdm/models/candidates.py", line 411, in obtain
    raise CandidateNotFound(
pdm.exceptions.CandidateNotFound: No candidate is found for `kaleido` that matches the environment or hashes
Traceback (most recent call last):
  File "/usr/local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/pdm/core.py", line 259, in main
    return Core().main(args)
  File "/usr/local/lib/python3.10/site-packages/pdm/core.py", line 191, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/usr/local/lib/python3.10/site-packages/pdm/core.py", line 186, in main
    f(project, options)
  File "/usr/local/lib/python3.10/site-packages/pdm/cli/commands/add.py", line 58, in handle
    actions.do_add(
  File "/usr/local/lib/python3.10/site-packages/pdm/cli/actions.py", line 297, in do_add
    do_sync(
  File "/usr/local/lib/python3.10/site-packages/pdm/cli/actions.py", line 213, in do_sync
    handler.synchronize()
  File "/usr/local/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 423, in synchronize
    raise InstallationError("Some package operations are not complete yet")
pdm.exceptions.InstallationError: Some package operations are not complete yet
```

## Expected behavior
installed success

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.3.4
Python Interpreter:
  /Users/libai/Documents/workspace/workOther/.venv/bin/python (3.9)
Project Root:
  /Users/libai/Documents/workspace/workOther
Project Packages:
  None
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.15",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "19.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 19.6.0: Tue Jun 21 21:18:39 PDT 2022; root:xnu-6153.141.66~1/RELEASE_X86_64",
  "python_full_version": "3.9.15",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "darwin"
}

```

**Comment by banduoba** [comment]
经过各种查询资料,发现了解决方法:可以这么来解决:`pdm run pip kaleido ` 这样安装之后可以正常安装了,查询了下很多人遇到类似情况,希望官方可以给出解决方案

**Comment by frostming** [comment]
Just skip [0.2.1post1](https://pypi.org/project/kaleido/0.2.1.post1/#files) because it is an incomplete release.

**Comment by banduoba** [comment]
Thank you,I use `pdm add kaleido==0.2.1` install success.
