### ISSUE TITLE
`pdm self update` UnicodeDecodeError

### ISSUE THREAD

**Issue by Bing-su** [pdm-project/pdm#1602]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

These encoding errors I've experienced so far have been because I'm using Korean Windows. I think this error might be for a similar reason.

on Korean Windows 11
```sh
pdm self update -v
```

## Actual behavior

```py
(base)
Administrator in ~
❯ pdm self update -v
Running pip command: ['install', '--upgrade', 'pdm==2.3.4']
Traceback (most recent call last):
  File "C:\Users\dowon\AppData\Roaming\pdm\venv\lib\site-packages\pdm\cli\commands\self_cmd.py", line 266, in handle
  File "C:\Users\dowon\AppData\Roaming\pdm\venv\lib\site-packages\pdm\cli\commands\self_cmd.py", line 41, in run_pip
  File "C:\Users\dowon\miniconda3\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\dowon\miniconda3\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\dowon\\AppData\\Roaming\\pdm\\venv\\Scripts\\python.exe', '-Esm', 'pip', '-v', 'install', '--upgrade', 'pdm==2.3.4']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dowon\miniconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\dowon\miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\users\dowon\appdata\roaming\python\scripts\pdm.exe\__main__.py", line 7, in <module>
  File "C:\Users\dowon\AppData\Roaming\pdm\venv\lib\site-packages\pdm\core.py", line 258, in main
  File "C:\Users\dowon\AppData\Roaming\pdm\venv\lib\site-packages\pdm\core.py", line 190, in main
  File "C:\Users\dowon\AppData\Roaming\pdm\venv\lib\site-packages\pdm\core.py", line 185, in main
  File "C:\Users\dowon\AppData\Roaming\pdm\venv\lib\site-packages\pdm\cli\commands\self_cmd.py", line 270, in handle
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb4 in position 7811: invalid start byte
(base)
Administrator in ~ took 4s
❯ pdm -v
Traceback (most recent call last):
  File "C:\Users\dowon\miniconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\dowon\miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\users\dowon\appdata\roaming\python\scripts\pdm.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'pdm.core'
```

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
# Reinstall PDM and run
❯ pdm info --env
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.8",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.22621",
  "python_full_version": "3.10.8",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "win32"
}
```

```sh
❯ pdm info
PDM version:
  2.3.4
Python Interpreter:
  C:\Users\dowon\miniconda3\envs\remopy\python.EXE (3.10)
Project Root:
  D:/repos/remopy
Project Packages:
  None
```

**Comment by frostming** [comment]
The command `C:\Users\dowon\AppData\Roaming\pdm\venv\Scripts\python.exe -Esm pip -v install --upgrade pdm==2.3.4` runs failed but the outputs are swallowed because it contains non-UTF8 characters.

Can you re-install the pdm 2.3.3 version and run the command in the terminal manually?

**Comment by frostming** [comment]
@Bing-su Can you help verify if the fixing approach in #1605 works?

**Comment by Bing-su** [comment]
```py
def run_pip(project: Project, args: list[str]) -> subprocess.CompletedProcess[str]:
    env = BareEnvironment(project)
    project.environment = env
    run_args = env.pip_command + args
    if sys.platform == "win32":
        shell = True
        run_args = " ".join(shlex.quote(arg) for arg in run_args)
    else:
        shell = False
    print(f"{run_args = }")
    return subprocess.run(
        run_args,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        shell=shell,
        check=True,
        text=True,
    )
```
```sh
❯ pdm self update
run_args = "'C:\\Users\\dowon\\AppData\\Roaming\\pdm\\venv\\Scripts\\python.exe' -Esm pip install --upgrade pdm==2.3.4"
Installing version 2.3.4 failed:
파일 이름, 디렉터리 이름 또는 볼륨 레이블 구문이 잘못되었습니다.
```

```sh
❯ 'C:\\Users\\dowon\\AppData\\Roaming\\pdm\\venv\\Scripts\\python.exe' -Esm pip install --upgrade pdm==2.3.4
위치 줄:1 문자:70
+ ... dowon\\AppData\\Roaming\\pdm\\venv\\Scripts\\python.exe' -Esm pip ins ...
+                                                              ~~~~
식 또는 문에서 예기치 않은 '-Esm' 토큰입니다.
위치 줄:1 문자:75
+ ... n\\AppData\\Roaming\\pdm\\venv\\Scripts\\python.exe' -Esm pip install ...
+                                                               ~~~
식 또는 문에서 예기치 않은 'pip' 토큰입니다.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken
```

remove single quote
```sh
❯ C:\\Users\\dowon\\AppData\\Roaming\\pdm\\venv\\Scripts\\python.exe -Esm pip install --upgrade pdm==2.3.4
Collecting pdm==2.3.4
  Using cached pdm-2.3.4-py3-none-any.whl (198 kB)
Requirement already satisfied: requests-toolbelt in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from pdm==2.3.4) (0.10.1)
Requirement already satisfied: importlib-metadata>=3.6 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from pdm==2.3.4) (6.0.0)
Requirement already satisfied: rich>=12.3.0 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from pdm==2.3.4) (13.0.1)
Requirement already satisfied: unearth>=0.7 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from pdm==2.3.4) (0.7.2)
Requirement already satisfied: cachecontrol[filecache]>=0.12.11 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from pdm==2.3.4) (0.12.11)
Requirement already satisfied: findpython>=0.2.2 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from pdm==2.3.4) (0.2.2)
Requirement already satisfied: python-dotenv>=0.15 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from pdm==2.3.4) (0.21.0)
Requirement already satisfied: shellingham>=1.3.2 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from pdm==2.3.4) (1.5.0.post1)
Requirement already satisfied: tomli>=1.1.0 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from pdm==2.3.4) (2.0.1)
Requirement already satisfied: virtualenv>=20 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from pdm==2.3.4) (20.17.1)
Requirement already satisfied: blinker in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from pdm==2.3.4) (1.5)
Requirement already satisfied: platformdirs in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from pdm==2.3.4) (2.6.2)
Requirement already satisfied: tomlkit<1,>=0.11.1 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from pdm==2.3.4) (0.11.6)
Requirement already satisfied: packaging!=22.0,>=20.9 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from pdm==2.3.4) (23.0)
Requirement already satisfied: resolvelib<0.10,>=0.9 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from pdm==2.3.4) (0.9.0)
Requirement already satisfied: certifi in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from pdm==2.3.4) (2022.12.7)
Requirement already satisfied: installer<0.7,>=0.6 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from pdm==2.3.4) (0.6.0)
Requirement already satisfied: pyproject-hooks in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from pdm==2.3.4) (1.0.0)
Requirement already satisfied: requests in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from cachecontrol[filecache]>=0.12.11->pdm==2.3.4) (2.28.1)
Requirement already satisfied: msgpack>=0.5.2 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from cachecontrol[filecache]>=0.12.11->pdm==2.3.4) (1.0.4)
Requirement already satisfied: lockfile>=0.9 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from cachecontrol[filecache]>=0.12.11->pdm==2.3.4) (0.12.2)
Requirement already satisfied: zipp>=0.5 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from importlib-metadata>=3.6->pdm==2.3.4) (3.11.0)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from rich>=12.3.0->pdm==2.3.4) (0.9.1)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from rich>=12.3.0->pdm==2.3.4) (2.14.0)
Requirement already satisfied: filelock<4,>=3.4.1 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from virtualenv>=20->pdm==2.3.4) (3.9.0)
Requirement already satisfied: distlib<1,>=0.3.6 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from virtualenv>=20->pdm==2.3.4) (0.3.6)
Requirement already satisfied: idna<4,>=2.5 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from requests->cachecontrol[filecache]>=0.12.11->pdm==2.3.4) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from requests->cachecontrol[filecache]>=0.12.11->pdm==2.3.4) (1.26.13)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from requests->cachecontrol[filecache]>=0.12.11->pdm==2.3.4) (2.1.1)
Installing collected packages: pdm
  Attempting uninstall: pdm
    Found existing installation: pdm 2.3.5.dev10+g6783730
    Uninstalling pdm-2.3.5.dev10+g6783730:
      Successfully uninstalled pdm-2.3.5.dev10+g6783730
Successfully installed pdm-2.3.4
```

fix `run_args`:
```py
    if sys.platform == "win32":
        shell = True
        run_args = " ".join(arg if i == 0 else shlex.quote(arg) for i, arg in enumerate(run_args))
```

then update.
```sh
pdm on  fix/1602 [!] via 🐍 v3.9.15
❯ pdm self update -v
Running pip command: ['install', '--upgrade', 'pdm==2.3.4']
Installing version 2.3.4 failed:
Using pip 22.3.1 from C:\Users\dowon\AppData\Roaming\pdm\venv\lib\site-packages\pip (python 3.9)
Collecting pdm==2.3.4
  Using cached pdm-2.3.4-py3-none-any.whl (198 kB)
Requirement already satisfied: tomlkit<1,>=0.11.1 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from
pdm==2.3.4) (0.11.6)
Requirement already satisfied: requests-toolbelt in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from
pdm==2.3.4) (0.10.1)
Requirement already satisfied: tomli>=1.1.0 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from
pdm==2.3.4) (2.0.1)
Requirement already satisfied: shellingham>=1.3.2 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from
pdm==2.3.4) (1.5.0.post1)
Requirement already satisfied: resolvelib<0.10,>=0.9 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from
pdm==2.3.4) (0.9.0)
Requirement already satisfied: importlib-metadata>=3.6 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages
(from pdm==2.3.4) (6.0.0)
Requirement already satisfied: findpython>=0.2.2 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from
pdm==2.3.4) (0.2.2)
Requirement already satisfied: unearth>=0.7 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from
pdm==2.3.4) (0.7.2)
Requirement already satisfied: installer<0.7,>=0.6 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from
pdm==2.3.4) (0.6.0)
Requirement already satisfied: packaging!=22.0,>=20.9 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from
pdm==2.3.4) (23.0)
Requirement already satisfied: platformdirs in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from
pdm==2.3.4) (2.6.2)
Requirement already satisfied: virtualenv>=20 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from
pdm==2.3.4) (20.17.1)
Requirement already satisfied: rich>=12.3.0 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from
pdm==2.3.4) (13.0.1)
Requirement already satisfied: cachecontrol>=0.12.11 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from
pdm==2.3.4) (0.12.11)
Requirement already satisfied: pyproject-hooks in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from
pdm==2.3.4) (1.0.0)
Requirement already satisfied: python-dotenv>=0.15 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from
pdm==2.3.4) (0.21.0)
Requirement already satisfied: certifi in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from pdm==2.3.4)
(2022.12.7)
Requirement already satisfied: blinker in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from pdm==2.3.4)
(1.5)
Requirement already satisfied: msgpack>=0.5.2 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from
cachecontrol>=0.12.11->pdm==2.3.4) (1.0.4)
Requirement already satisfied: requests in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from
cachecontrol>=0.12.11->pdm==2.3.4) (2.28.1)
Requirement already satisfied: lockfile>=0.9 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from
cachecontrol>=0.12.11->pdm==2.3.4) (0.12.2)
Requirement already satisfied: zipp>=0.5 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from
importlib-metadata>=3.6->pdm==2.3.4) (3.11.0)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from
rich>=12.3.0->pdm==2.3.4) (2.14.0)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages
(from rich>=12.3.0->pdm==2.3.4) (0.9.1)
Requirement already satisfied: distlib<1,>=0.3.6 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from
virtualenv>=20->pdm==2.3.4) (0.3.6)
Requirement already satisfied: filelock<4,>=3.4.1 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from
virtualenv>=20->pdm==2.3.4) (3.9.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from
requests->cachecontrol>=0.12.11->pdm==2.3.4) (1.26.13)
Requirement already satisfied: idna<4,>=2.5 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages (from
requests->cachecontrol>=0.12.11->pdm==2.3.4) (3.4)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages
(from requests->cachecontrol>=0.12.11->pdm==2.3.4) (2.1.1)
Installing collected packages: pdm
  Attempting uninstall: pdm
    Found existing installation: pdm 2.3.5.dev10+g6783730
    Uninstalling pdm-2.3.5.dev10+g6783730:
      Removing file or directory
c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages\pdm-2.3.5.dev10+g6783730.dist-info\
      Removing file or directory c:\users\dowon\appdata\roaming\pdm\venv\lib\site-packages\pdm\
ERROR: Could not install packages due to an OSError.
Check the permissions.
Traceback (most recent call last):
  File "C:\Users\dowon\miniconda3\lib\shutil.py", line 825, in move
    os.rename(src, real_dst)
PermissionError: [WinError 32] 다른 프로세스가 파일을 사용 중이기 때문에 프로세스가 액세스 할 수 없습니다:
'c:\\users\\dowon\\appdata\\roaming\\pdm\\venv\\scripts\\pdm.exe' ->
'C:\\Users\\dowon\\AppData\\Local\\Temp\\pip-uninstall-0xuxaaoe\\pdm.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dowon\AppData\Roaming\pdm\venv\lib\site-packages\pip\_internal\commands\install.py", line 494, in run
    installed = install_given_reqs(
  File "C:\Users\dowon\AppData\Roaming\pdm\venv\lib\site-packages\pip\_internal\req\__init__.py", line 68, in
install_given_reqs
    uninstalled_pathset = requirement.uninstall(auto_confirm=True)
  File "C:\Users\dowon\AppData\Roaming\pdm\venv\lib\site-packages\pip\_internal\req\req_install.py", line 660, in
uninstall
    uninstalled_pathset.remove(auto_confirm, verbose)
  File "C:\Users\dowon\AppData\Roaming\pdm\venv\lib\site-packages\pip\_internal\req\req_uninstall.py", line 373, in
remove
    moved.stash(path)
  File "C:\Users\dowon\AppData\Roaming\pdm\venv\lib\site-packages\pip\_internal\req\req_uninstall.py", line 271, in
stash
    renames(path, new_path)
  File "C:\Users\dowon\AppData\Roaming\pdm\venv\lib\site-packages\pip\_internal\utils\misc.py", line 311, in renames
    shutil.move(old, new)
  File "C:\Users\dowon\miniconda3\lib\shutil.py", line 846, in move
    os.unlink(src)
PermissionError: [WinError 32] 다른 프로세스가 파일을 사용 중이기 때문에 프로세스가 액세스 할 수 없습니다:
'c:\\users\\dowon\\appdata\\roaming\\pdm\\venv\\scripts\\pdm.exe'
```

same process error...

**Comment by frostming** [comment]
It seems to be caused by a limit on Windows that the process can't delete the file it is running. But what is weird, it run without any problem on my Powershell+Windows.

**Comment by frostming** [comment]
Oh, I know, I am using a pipx installation so the executable is a hard link to the original one, so deleting works fine because they are not the same. As a workaround, you can do the same to your installation(or switch to a pipx installation). I will change the installation script to fix this.

**Comment by Bing-su** [comment]
Thanks for resolving the issue 😸

I installed pdm by windows scripts ↓
```powershell
(Invoke-WebRequest -Uri https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py -UseBasicParsing).Content | python -
```

```powershell
# powershell
❯ Get-Command pdm

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     pdm.exe                                            0.0.0.0    c:\users\dowon\appdata\roaming\python\scripts\pdm.exe

Administrator in ~
❯ python -c "import os; print(os.path.islink(r'c:\users\dowon\appdata\roaming\python\scripts\pdm.exe'))"
True

Administrator in ~
❯ python -c "from pathlib import Path; print(Path(r'c:\users\dowon\appdata\roaming\python\scripts\pdm.exe').resolve())"
C:\Users\dowon\AppData\Roaming\pdm\venv\Scripts\pdm.exe
```
