### ISSUE TITLE
`pdm add git+ssh` notably slower and/or fails compared to `pdm add git+https`

### ISSUE THREAD

**Issue by baggiponte** [pdm-project/pdm#1603]
I am using `git+https` and `git+ssh` to install a private package that I am developing and I noticed that installing with `https` is noticeably faster. I thought this was partly because cloning over SSH might be slower, but 

### `git+https` (12 seconds)

```bash
mkdir test
cd test
pdm init
pdm add git+https://<...>
```

<details>
<summary>log</summary>

```
pdm add git+https://github.com/WeAreFutura/futura-aws -v
Adding packages to default dependencies: git+https://github.com/WeAreFutura/futura-aws
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   git+https://github.com/WeAreFutura/futura-aws
pdm.termui:   python>=3.10
pdm.termui:   Adding requirement git+https://github.com/WeAreFutura/futura-aws
unearth.vcs.git: Cloning https://github.com/WeAreFutura/futura-aws to /var/folders/xw/p6xpq66x3hdcd0cl909cl_0m0000gn/T/pdm-build-qbqu690b
unearth.vcs.git: Resolved https://github.com/WeAreFutura/futura-aws to commit 78a12a0ad72ebb545bf96dd0ce441d5a0e163098
pdm.termui: Running PEP 517 backend to get metadata for <Link git+https://github.com/WeAreFutura/futura-aws (from None)>
pdm.termui: Preparing isolated env for PEP 517 build...
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   pdm-pep517>=1.0
pdm.termui:   python>=3.10.8,<3.10.9
pdm.termui:   Adding requirement pdm-pep517>=1.0
pdm.termui:   Adding requirement python>=3.10.8,<3.10.9
pdm.termui: ======== Starting round 0 ========
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/71/2a/ae8abd6ebb76edd97e0c3dc3e61913df438c17e44a9aed05fd2073bb800f/pdm_pep517-1.0.6-py3-none-any.whl (from None)>
pdm.termui: Pinning: pdm-pep517 1.0.6
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
pdm.termui: ======== Resolution Result ========
pdm.termui: Stable pins:
pdm.termui:       python None
pdm.termui:   pdm-pep517 1.0.6
pdm.termui: Installing pdm-pep517 1.0.6
pdm.termui: /var/folders/xw/p6xpq66x3hdcd0cl909cl_0m0000gn/T/pdm-build-env-a4rc26x3-shared/lib/python3.10/site-packages/pdm/pep517/base.py:384: PDMWarning: 'license' is missing
pdm.termui:   if meta.license_expression:
pdm.termui: /var/folders/xw/p6xpq66x3hdcd0cl909cl_0m0000gn/T/pdm-build-env-a4rc26x3-shared/lib/python3.10/site-packages/pdm/pep517/api.py:51: PDMWarning: No license files are matched with glob patterns ['LICENSES/*', 'LICEN[CS]E*', 'COPYING*', 'NOTICE*', 'AUTHORS*'].
pdm.termui:   for license_file in builder.find_license_files():
pdm.termui:   Adding requirement python>=3.10
pdm.termui: ======== Starting round 0 ========
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
pdm.termui:   Adding requirement boto3>=1.26.41(from futura-aws 0.1.0)
pdm.termui:   Adding requirement python-dotenv>=0.21.0(from futura-aws 0.1.0)
pdm.termui: Pinning: futura-aws 0.1.0
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/32/37/c97b200809674e3009cddc4970eeb9215f7fc8c56a75301c3acf71da470b/boto3-1.26.45-py3-none-any.whl (from None)>
pdm.termui:   Adding requirement botocore<1.30.0,>=1.29.45(from boto3 1.26.45)
pdm.termui:   Adding requirement jmespath<2.0.0,>=0.7.1(from boto3 1.26.45)
pdm.termui:   Adding requirement s3transfer<0.7.0,>=0.6.0(from boto3 1.26.45)
pdm.termui: Pinning: boto3 1.26.45
pdm.termui: ======== Ending round 2 ========
pdm.termui: ======== Starting round 3 ========
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/2d/10/ff4f2f5b2a420fd09e1331d63cc87cf4367c5745c0a4ce99cea92b1cbacb/python_dotenv-0.21.0-py3-none-any.whl (from None)>
pdm.termui: Pinning: python-dotenv 0.21.0
pdm.termui: ======== Ending round 3 ========
pdm.termui: ======== Starting round 4 ========
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/0c/a6/f523263c0cc7c0dd53fb9a41b45536d7ac2953ebbbf456a5b02bdeac0580/botocore-1.29.45-py3-none-any.whl (from None)>
pdm.termui:   Adding requirement jmespath<2.0.0,>=0.7.1(from botocore 1.29.45)
pdm.termui:   Adding requirement python-dateutil<3.0.0,>=2.1(from botocore 1.29.45)
pdm.termui:   Adding requirement urllib3<1.27,>=1.25.4(from botocore 1.29.45)
pdm.termui: Pinning: botocore 1.29.45
pdm.termui: ======== Ending round 4 ========
pdm.termui: ======== Starting round 5 ========
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/31/b4/b9b800c45527aadd64d5b442f9b932b00648617eb5d63d2c7a6587b7cafc/jmespath-1.0.1-py3-none-any.whl (from None)>
pdm.termui: Pinning: jmespath 1.0.1
pdm.termui: ======== Ending round 5 ========
pdm.termui: ======== Starting round 6 ========
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/5e/c6/af903b5fab3f9b5b1e883f49a770066314c6dcceb589cf938d48c89556c1/s3transfer-0.6.0-py3-none-any.whl (from None)>
pdm.termui:   Adding requirement botocore<2.0a.0,>=1.12.36(from s3transfer 0.6.0)
pdm.termui: Pinning: s3transfer 0.6.0
pdm.termui: ======== Ending round 6 ========
pdm.termui: ======== Starting round 7 ========
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/36/7a/87837f39d0296e723bb9b62bbb257d0355c7f6128853c78955f57342a56d/python_dateutil-2.8.2-py2.py3-none-any.whl (from None)>
pdm.termui:   Adding requirement six>=1.5(from python-dateutil 2.8.2)
pdm.termui: Pinning: python-dateutil 2.8.2
pdm.termui: ======== Ending round 7 ========
pdm.termui: ======== Starting round 8 ========
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/65/0c/cc6644eaa594585e5875f46f3c83ee8762b647b51fc5b0fb253a242df2dc/urllib3-1.26.13-py2.py3-none-any.whl (from None)>
pdm.termui: Pinning: urllib3 1.26.13
pdm.termui: ======== Ending round 8 ========
pdm.termui: ======== Starting round 9 ========
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl (from None)>
pdm.termui: Pinning: six 1.16.0
pdm.termui: ======== Ending round 9 ========
pdm.termui: ======== Starting round 10 ========
pdm.termui: ======== Resolution Result ========
pdm.termui: Stable pins:
pdm.termui:               python None
pdm.termui:   :empty:2BdltwxWFWQ git+https://github.com/WeAreFutura/futura-aws@78a12a0ad72ebb545bf96dd0ce441d5a0e163098
pdm.termui:                boto3 1.26.45
pdm.termui:        python-dotenv 0.21.0
pdm.termui:             botocore 1.29.45
pdm.termui:             jmespath 1.0.1
pdm.termui:           s3transfer 0.6.0
pdm.termui:      python-dateutil 2.8.2
pdm.termui:              urllib3 1.26.13
pdm.termui:                  six 1.16.0
🔒 Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
Synchronizing working set with lock file: 9 to add, 0 to update, 0 to remove

unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/32/37/c97b200809674e3009cddc4970eeb9215f7fc8c56a75301c3acf71da470b/boto3-1.26.45-py3-none-any.whl (from None)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/0c/a6/f523263c0cc7c0dd53fb9a41b45536d7ac2953ebbbf456a5b02bdeac0580/botocore-1.29.45-py3-none-any.whl (from None)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/31/b4/b9b800c45527aadd64d5b442f9b932b00648617eb5d63d2c7a6587b7cafc/jmespath-1.0.1-py3-none-any.whl (from None)>
unearth.vcs.git: Cloning https://github.com/WeAreFutura/futura-aws (revision: 78a12a0ad72ebb545bf96dd0ce441d5a0e163098) to /var/folders/xw/p6xpq66x3hdcd0cl909cl_0m0000gn/T/pdm-build-emqub9wv
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/5e/c6/af903b5fab3f9b5b1e883f49a770066314c6dcceb589cf938d48c89556c1/s3transfer-0.6.0-py3-none-any.whl (from None)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl (from None)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/2d/10/ff4f2f5b2a420fd09e1331d63cc87cf4367c5745c0a4ce99cea92b1cbacb/python_dotenv-0.21.0-py3-none-any.whl (from None)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/36/7a/87837f39d0296e723bb9b62bbb257d0355c7f6128853c78955f57342a56d/python_dateutil-2.8.2-py2.py3-none-any.whl (from None)>
  ✔ Install six 1.16.0 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/65/0c/cc6644eaa594585e5875f46f3c83ee8762b647b51fc5b0fb253a242df2dc/urllib3-1.26.13-py2.py3-none-any.whl (from None)>
  ✔ Install jmespath 1.0.1 successful
  ✔ Install s3transfer 0.6.0 successful
  ✔ Install python-dotenv 0.21.0 successful
  ✔ Install boto3 1.26.45 successful
  ✔ Install python-dateutil 2.8.2 successful
  ✔ Install urllib3 1.26.13 successful
  ✔ Install botocore 1.29.45 successful
unearth.vcs.git: Resolved https://github.com/WeAreFutura/futura-aws to commit 78a12a0ad72ebb545bf96dd0ce441d5a0e163098
pdm.termui: Preparing isolated env for PEP 517 build...
pdm.termui: Saving wheel to cache: <Link git+https://github.com/WeAreFutura/futura-aws@78a12a0ad72ebb545bf96dd0ce441d5a0e163098 (from None)>
pdm.termui: Running PEP 517 backend to build a wheel for <Link git+https://github.com/WeAreFutura/futura-aws@78a12a0ad72ebb545bf96dd0ce441d5a0e163098 (from None)>
pdm.termui: /var/folders/xw/p6xpq66x3hdcd0cl909cl_0m0000gn/T/pdm-build-env-a4rc26x3-shared/lib/python3.10/site-packages/pdm/pep517/base.py:384: PDMWarning: 'license' is missing
pdm.termui:   if meta.license_expression:
pdm.termui: /var/folders/xw/p6xpq66x3hdcd0cl909cl_0m0000gn/T/pdm-build-env-a4rc26x3-shared/lib/python3.10/site-packages/pdm/pep517/wheel.py:236: PDMWarning: No license files are matched with glob patterns ['LICENSES/*', 'LICEN[CS]E*', 'COPYING*', 'NOTICE*', 'AUTHORS*'].
pdm.termui:   for license_file in self.find_license_files():
pdm.termui:  - Adding futura_aws/__init__.py
pdm.termui:  - Adding futura_aws/exceptions.py
pdm.termui:  - Adding futura_aws/py.typed
pdm.termui:  - Adding futura_aws/s3.py
pdm.termui:  - Adding futura_aws/types.py
pdm.termui:  - Adding futura_aws-0.1.0.dist-info/WHEEL
pdm.termui:  - Adding futura_aws-0.1.0.dist-info/METADATA
  ✔ Install futura-aws 0.1.0 successful

🎉 All complete!
```

</details>

### With `git+ssh` (3 minutes and 58s)

```bash
mkdir test2
cd test2
pdm init
pdm add git+ssh://<...>
```

<details>
<summary>log</summary>

```
pdm add git+ssh://git@github.com/WeAreFutura/futura-aws -v
Adding packages to default dependencies: git+ssh://git@github.com/WeAreFutura/futura-aws
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   git+ssh://git@github.com/WeAreFutura/futura-aws
pdm.termui:   python>=3.10
pdm.termui:   Adding requirement git+ssh://git@github.com/WeAreFutura/futura-aws
unearth.vcs.git: Cloning ssh://***@github.com/WeAreFutura/futura-aws to /var/folders/xw/p6xpq66x3hdcd0cl909cl_0m0000gn/T/pdm-build-krk05l6h
unearth.vcs.git: Resolved ssh://***@github.com/WeAreFutura/futura-aws to commit 78a12a0ad72ebb545bf96dd0ce441d5a0e163098
pdm.termui: Running PEP 517 backend to get metadata for <Link git+ssh://***@github.com/WeAreFutura/futura-aws (from None)>
pdm.termui: Preparing isolated env for PEP 517 build...
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   pdm-pep517>=1.0
pdm.termui:   python>=3.10.8,<3.10.9
pdm.termui:   Adding requirement pdm-pep517>=1.0
pdm.termui:   Adding requirement python>=3.10.8,<3.10.9
pdm.termui: ======== Starting round 0 ========
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/71/2a/ae8abd6ebb76edd97e0c3dc3e61913df438c17e44a9aed05fd2073bb800f/pdm_pep517-1.0.6-py3-none-any.whl (from None)>
pdm.termui: Pinning: pdm-pep517 1.0.6
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
pdm.termui: ======== Resolution Result ========
pdm.termui: Stable pins:
pdm.termui:       python None
pdm.termui:   pdm-pep517 1.0.6
pdm.termui: Installing pdm-pep517 1.0.6
pdm.termui: /var/folders/xw/p6xpq66x3hdcd0cl909cl_0m0000gn/T/pdm-build-env-bkyeufbg-shared/lib/python3.10/site-packages/pdm/pep517/base.py:384: PDMWarning: 'license' is missing
pdm.termui:   if meta.license_expression:
pdm.termui: /var/folders/xw/p6xpq66x3hdcd0cl909cl_0m0000gn/T/pdm-build-env-bkyeufbg-shared/lib/python3.10/site-packages/pdm/pep517/api.py:51: PDMWarning: No license files are matched with glob patterns ['LICENSES/*', 'LICEN[CS]E*', 'COPYING*', 'NOTICE*', 'AUTHORS*'].
pdm.termui:   for license_file in builder.find_license_files():
pdm.termui:   Adding requirement python>=3.10
pdm.termui: ======== Starting round 0 ========
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
pdm.termui:   Adding requirement boto3>=1.26.41(from futura-aws 0.1.0)
pdm.termui:   Adding requirement python-dotenv>=0.21.0(from futura-aws 0.1.0)
pdm.termui: Pinning: futura-aws 0.1.0
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
pdm.termui:   Adding requirement botocore<1.30.0,>=1.29.45(from boto3 1.26.45)
pdm.termui:   Adding requirement jmespath<2.0.0,>=0.7.1(from boto3 1.26.45)
pdm.termui:   Adding requirement s3transfer<0.7.0,>=0.6.0(from boto3 1.26.45)
pdm.termui: Pinning: boto3 1.26.45
pdm.termui: ======== Ending round 2 ========
pdm.termui: ======== Starting round 3 ========
pdm.termui: Pinning: python-dotenv 0.21.0
pdm.termui: ======== Ending round 3 ========
pdm.termui: ======== Starting round 4 ========
pdm.termui:   Adding requirement jmespath<2.0.0,>=0.7.1(from botocore 1.29.45)
pdm.termui:   Adding requirement python-dateutil<3.0.0,>=2.1(from botocore 1.29.45)
pdm.termui:   Adding requirement urllib3<1.27,>=1.25.4(from botocore 1.29.45)
pdm.termui: Pinning: botocore 1.29.45
pdm.termui: ======== Ending round 4 ========
pdm.termui: ======== Starting round 5 ========
pdm.termui: Pinning: jmespath 1.0.1
pdm.termui: ======== Ending round 5 ========
pdm.termui: ======== Starting round 6 ========
pdm.termui:   Adding requirement botocore<2.0a.0,>=1.12.36(from s3transfer 0.6.0)
pdm.termui: Pinning: s3transfer 0.6.0
pdm.termui: ======== Ending round 6 ========
pdm.termui: ======== Starting round 7 ========
pdm.termui:   Adding requirement six>=1.5(from python-dateutil 2.8.2)
pdm.termui: Pinning: python-dateutil 2.8.2
pdm.termui: ======== Ending round 7 ========
pdm.termui: ======== Starting round 8 ========
pdm.termui: Pinning: urllib3 1.26.13
pdm.termui: ======== Ending round 8 ========
pdm.termui: ======== Starting round 9 ========
pdm.termui: Pinning: six 1.16.0
pdm.termui: ======== Ending round 9 ========
pdm.termui: ======== Starting round 10 ========
pdm.termui: ======== Resolution Result ========
pdm.termui: Stable pins:
pdm.termui:               python None
pdm.termui:   :empty:6TNItPZdNQ0 git+ssh://git@github.com/WeAreFutura/futura-aws@78a12a0ad72ebb545bf96dd0ce441d5a0e163098
pdm.termui:                boto3 1.26.45
pdm.termui:        python-dotenv 0.21.0
pdm.termui:             botocore 1.29.45
pdm.termui:             jmespath 1.0.1
pdm.termui:           s3transfer 0.6.0
pdm.termui:      python-dateutil 2.8.2
pdm.termui:              urllib3 1.26.13
pdm.termui:                  six 1.16.0
🔒 Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
Synchronizing working set with lock file: 9 to add, 0 to update, 0 to remove

unearth.vcs.git: Cloning ssh://***@github.com/WeAreFutura/futura-aws (revision: 78a12a0ad72ebb545bf96dd0ce441d5a0e163098) to /var/folders/xw/p6xpq66x3hdcd0cl909cl_0m0000gn/T/pdm-build-9t46uxgq
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl (from None)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/2d/10/ff4f2f5b2a420fd09e1331d63cc87cf4367c5745c0a4ce99cea92b1cbacb/python_dotenv-0.21.0-py3-none-any.whl (from None)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/5e/c6/af903b5fab3f9b5b1e883f49a770066314c6dcceb589cf938d48c89556c1/s3transfer-0.6.0-py3-none-any.whl (from None)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/36/7a/87837f39d0296e723bb9b62bbb257d0355c7f6128853c78955f57342a56d/python_dateutil-2.8.2-py2.py3-none-any.whl (from None)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/31/b4/b9b800c45527aadd64d5b442f9b932b00648617eb5d63d2c7a6587b7cafc/jmespath-1.0.1-py3-none-any.whl (from None)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/32/37/c97b200809674e3009cddc4970eeb9215f7fc8c56a75301c3acf71da470b/boto3-1.26.45-py3-none-any.whl (from None)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/0c/a6/f523263c0cc7c0dd53fb9a41b45536d7ac2953ebbbf456a5b02bdeac0580/botocore-1.29.45-py3-none-any.whl (from None)>
  ✔ Install six 1.16.0 successful
  ✔ Install python-dotenv 0.21.0 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/65/0c/cc6644eaa594585e5875f46f3c83ee8762b647b51fc5b0fb253a242df2dc/urllib3-1.26.13-py2.py3-none-any.whl (from None)>
  ✔ Install jmespath 1.0.1 successful
  ✔ Install s3transfer 0.6.0 successful
  ✔ Install python-dateutil 2.8.2 successful
  ✔ Install boto3 1.26.45 successful
  ✔ Install urllib3 1.26.13 successful
  ✔ Install botocore 1.29.45 successful
  ✖ Install futura-aws 0.1.0 failed
pdm.termui: Error occurs:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/lucabaggi/.local/share/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 236, in install_candidate
    self.manager.install(can)
  File "/Users/lucabaggi/.local/share/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/installers/manager.py", line 39, in install
    installer(str(prepared.build()), self.environment, prepared.direct_url())
  File "/Users/lucabaggi/.local/share/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/models/candidates.py", line 359, in build
    self.obtain(allow_all=False)
  File "/Users/lucabaggi/.local/share/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/models/candidates.py", line 428, in obtain
    result = finder.download_and_unpack(
  File "/Users/lucabaggi/.local/share/pipx/venvs/pdm/lib/python3.10/site-packages/unearth/finder.py", line 356, in download_and_unpack
    file = unpack_link(
  File "/Users/lucabaggi/.local/share/pipx/venvs/pdm/lib/python3.10/site-packages/unearth/preparer.py", line 283, in unpack_link
    backend.fetch(link, location)
  File "/Users/lucabaggi/.local/share/pipx/venvs/pdm/lib/python3.10/site-packages/unearth/vcs/base.py", line 145, in fetch
    return self.fetch_new(location, url, rev, args)
  File "/Users/lucabaggi/.local/share/pipx/venvs/pdm/lib/python3.10/site-packages/unearth/vcs/git.py", line 48, in fetch_new
    self.run_command(
  File "/Users/lucabaggi/.local/share/pipx/venvs/pdm/lib/python3.10/site-packages/unearth/vcs/base.py", line 78, in run_command
    raise UnpackError(e.output) from None
unearth.errors.UnpackError: Cloning into '/var/folders/xw/p6xpq66x3hdcd0cl909cl_0m0000gn/T/pdm-build-9t46uxgq'...
ssh: connect to host github.com port 22: Operation timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Retry failed jobs
unearth.vcs.git: Cloning ssh://***@github.com/WeAreFutura/futura-aws (revision: 78a12a0ad72ebb545bf96dd0ce441d5a0e163098) to /var/folders/xw/p6xpq66x3hdcd0cl909cl_0m0000gn/T/pdm-build-oghqmgua
unearth.vcs.git: Resolved ssh://***@github.com/WeAreFutura/futura-aws to commit 78a12a0ad72ebb545bf96dd0ce441d5a0e163098
pdm.termui: Preparing isolated env for PEP 517 build...
pdm.termui: Saving wheel to cache: <Link git+ssh://***@github.com/WeAreFutura/futura-aws@78a12a0ad72ebb545bf96dd0ce441d5a0e163098 (from None)>
pdm.termui: Running PEP 517 backend to build a wheel for <Link git+ssh://***@github.com/WeAreFutura/futura-aws@78a12a0ad72ebb545bf96dd0ce441d5a0e163098 (from None)>
pdm.termui: /var/folders/xw/p6xpq66x3hdcd0cl909cl_0m0000gn/T/pdm-build-env-bkyeufbg-shared/lib/python3.10/site-packages/pdm/pep517/base.py:384: PDMWarning: 'license' is missing
pdm.termui:   if meta.license_expression:
pdm.termui: /var/folders/xw/p6xpq66x3hdcd0cl909cl_0m0000gn/T/pdm-build-env-bkyeufbg-shared/lib/python3.10/site-packages/pdm/pep517/wheel.py:236: PDMWarning: No license files are matched with glob patterns ['LICENSES/*', 'LICEN[CS]E*', 'COPYING*', 'NOTICE*', 'AUTHORS*'].
pdm.termui:   for license_file in self.find_license_files():
pdm.termui:  - Adding futura_aws/__init__.py
pdm.termui:  - Adding futura_aws/exceptions.py
pdm.termui:  - Adding futura_aws/py.typed
pdm.termui:  - Adding futura_aws/s3.py
pdm.termui:  - Adding futura_aws/types.py
pdm.termui:  - Adding futura_aws-0.1.0.dist-info/WHEEL
pdm.termui:  - Adding futura_aws-0.1.0.dist-info/METADATA
  ✔ Install futura-aws 0.1.0 successful

🎉 All complete!```
</details>

### `pip` and `https` (2s)

```bash
mkdir test3
cd test3
pyenv local 3.10.8
python -m venv .venv
source .venv/bin/activate
pip install git+https://<...>
```

<details>
<summary>log</summary>

```
pip install git+https://github.com/WeAreFutura/futura-aws.git
Collecting git+https://github.com/WeAreFutura/futura-aws.git
  Cloning https://github.com/WeAreFutura/futura-aws.git to /private/var/folders/xw/p6xpq66x3hdcd0cl909cl_0m0000gn/T/pip-req-build-a91y95aq
  Running command git clone --filter=blob:none --quiet https://github.com/WeAreFutura/futura-aws.git /private/var/folders/xw/p6xpq66x3hdcd0cl909cl_0m0000gn/T/pip-req-build-a91y95aq
  Resolved https://github.com/WeAreFutura/futura-aws.git to commit 78a12a0ad72ebb545bf96dd0ce441d5a0e163098
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting python-dotenv>=0.21.0
  Using cached python_dotenv-0.21.0-py3-none-any.whl (18 kB)
Collecting boto3>=1.26.41
  Using cached boto3-1.26.45-py3-none-any.whl (132 kB)
Collecting s3transfer<0.7.0,>=0.6.0
  Using cached s3transfer-0.6.0-py3-none-any.whl (79 kB)
Collecting jmespath<2.0.0,>=0.7.1
  Using cached jmespath-1.0.1-py3-none-any.whl (20 kB)
Collecting botocore<1.30.0,>=1.29.45
  Using cached botocore-1.29.45-py3-none-any.whl (10.3 MB)
Collecting python-dateutil<3.0.0,>=2.1
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting urllib3<1.27,>=1.25.4
  Using cached urllib3-1.26.13-py2.py3-none-any.whl (140 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Building wheels for collected packages: futura-aws
  Building wheel for futura-aws (pyproject.toml) ... done
  Created wheel for futura-aws: filename=futura_aws-0.1.0-py3-none-any.whl size=7286 sha256=b8da379e8139affbe905ba412a3f9cde38d65233f57e0541934ccdeca01f9943
  Stored in directory: /private/var/folders/xw/p6xpq66x3hdcd0cl909cl_0m0000gn/T/pip-ephem-wheel-cache-d3_57dje/wheels/00/59/34/bbfc8dc11ad75d059c68f8736e80828fbb9474748f6e8502a4
Successfully built futura-aws
Installing collected packages: urllib3, six, python-dotenv, jmespath, python-dateutil, botocore, s3transfer, boto3, futura-aws
Successfully installed boto3-1.26.45 botocore-1.29.45 futura-aws-0.1.0 jmespath-1.0.1 python-dateutil-2.8.2 python-dotenv-0.21.0 s3transfer-0.6.0 six-1.16.0 urllib3-1.26.13
```

</details>

### `pip` and `ssh` (2s)

```bash
mkdir test4
cd test4
pyenv local 3.10.8
python -m venv .venv
source .venv/bin/activate
pip install git+ssh://<...>
```

<details>
<summary>log</summary>

```
pip install git+ssh://git@github.com/WeAreFutura/futura-aws
Collecting git+ssh://****@github.com/WeAreFutura/futura-aws
  Cloning ssh://****@github.com/WeAreFutura/futura-aws to /private/var/folders/xw/p6xpq66x3hdcd0cl909cl_0m0000gn/T/pip-req-build-r6_6ml3q
  Running command git clone --filter=blob:none --quiet 'ssh://****@github.com/WeAreFutura/futura-aws' /private/var/folders/xw/p6xpq66x3hdcd0cl909cl_0m0000gn/T/pip-req-build-r6_6ml3q
  Resolved ssh://****@github.com/WeAreFutura/futura-aws to commit 78a12a0ad72ebb545bf96dd0ce441d5a0e163098
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting boto3>=1.26.41
  Using cached boto3-1.26.45-py3-none-any.whl (132 kB)
Collecting python-dotenv>=0.21.0
  Using cached python_dotenv-0.21.0-py3-none-any.whl (18 kB)
Collecting jmespath<2.0.0,>=0.7.1
  Using cached jmespath-1.0.1-py3-none-any.whl (20 kB)
Collecting s3transfer<0.7.0,>=0.6.0
  Using cached s3transfer-0.6.0-py3-none-any.whl (79 kB)
Collecting botocore<1.30.0,>=1.29.45
  Using cached botocore-1.29.45-py3-none-any.whl (10.3 MB)
Collecting python-dateutil<3.0.0,>=2.1
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting urllib3<1.27,>=1.25.4
  Using cached urllib3-1.26.13-py2.py3-none-any.whl (140 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Building wheels for collected packages: futura-aws
  Building wheel for futura-aws (pyproject.toml) ... done
  Created wheel for futura-aws: filename=futura_aws-0.1.0-py3-none-any.whl size=7286 sha256=b8da379e8139affbe905ba412a3f9cde38d65233f57e0541934ccdeca01f9943
  Stored in directory: /private/var/folders/xw/p6xpq66x3hdcd0cl909cl_0m0000gn/T/pip-ephem-wheel-cache-rg5rm52o/wheels/72/da/fa/732f6fea0fadb39141d48f319f3ddb8d0a3467fb087a403845
Successfully built futura-aws
Installing collected packages: urllib3, six, python-dotenv, jmespath, python-dateutil, botocore, s3transfer, boto3, futura-aws
Successfully installed boto3-1.26.45 botocore-1.29.45 futura-aws-0.1.0 jmespath-1.0.1 python-dateutil-2.8.2 python-dotenv-0.21.0 s3transfer-0.6.0 six-1.16.0 urllib3-1.26.13
```

</details>

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.3.4
Python Interpreter:
  /Users/lucabaggi/Documents/dev/test2/.venv/bin/python (3.10)
Project Root:
  /Users/lucabaggi/Documents/dev/test2
Project Packages:
  None
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.8",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "21.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:05 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8101",
  "python_full_version": "3.10.8",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
It is usually the case if the HTTP is run behind a proxy but SSH isn't. But I don't think there is anything we can do on PDM side.

**Comment by pawamoy** [comment]
Yep, we see `ssh: connect to host github.com port 22: Operation timed out` in the logs: if it sometimes fail, sometimes succeeds, that's most probably network effects (for example capricious proxy as mentioned by @frostming).

The time out failure also explains why it's slower.

**Comment by baggiponte** [comment]
wow faster than lighting! Thank you both. I was a bit puzzled because I also tried the comparison using `pip + venv` and both with https and ssh it takes just 2 seconds.
