### ISSUE TITLE
PDM ignores tool.pdm.source directive pointing to local folder and still tries to source from PyPI

### ISSUE THREAD

**Issue by sdiop** [pdm-project/pdm#1608]
- [ x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce
in pyproject.toml:

[[tool.pdm.source]]
url = "file:///Users/Shared/PythonPackages"
name = "local"
type = "find_links"

add a .whl (numpy-1.24.1-cp311-cp311-macosx_11_0_arm64.whl) file to above folder

then issue command: pdm add numpy -v

## Actual behavior

I disconnet the internet connect the issue the following command and PDM does not access the target folder to pull numpy instead tries to connect to PyPI.org (which is unreachable).

➜ pdm add numpy -v
Adding packages to default dependencies: numpy
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   black>=22.12.0
pdm.termui:   requests>=2.28.1
pdm.termui:   fastapi>=0.89.0
pdm.termui:   pyffmpeg>=2.4.2.13
pdm.termui:   numpy
pdm.termui:   pytest>=7.2.0
pdm.termui:   python>=3.11
pdm.termui:   Adding requirement black>=22.12.0
pdm.termui:   Adding requirement requests>=2.28.1
pdm.termui:   Adding requirement fastapi>=0.89.0
pdm.termui:   Adding requirement pyffmpeg>=2.4.2.13
pdm.termui:   Adding requirement numpy
Traceback (most recent call last):
  File "/Users/username/Library/Application Support/pdm/venv/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/Library/Application Support/pdm/venv/lib/python3.11/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/.pyenv/versions/3.11.1/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/username/Library/Application Support/pdm/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/username/Library/Application Support/pdm/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/username/Library/Application Support/pdm/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/username/Library/Application Support/pdm/venv/lib/python3.11/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/Users/username/Library/Application Support/pdm/venv/lib/python3.11/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x10503e910>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/username/Library/Application Support/pdm/venv/lib/python3.11/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/username/Library/Application Support/pdm/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/username/Library/Application Support/pdm/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/username/Library/Application Support/pdm/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  [Previous line repeated 2 more times]
  File "/Users/username/Library/Application Support/pdm/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/username/Library/Application Support/pdm/venv/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/numpy/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10503e910>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/username/.local/bin/pdm", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/username/Library/Application Support/pdm/venv/lib/python3.11/site-packages/pdm/core.py", line 259, in main
    return Core().main(args)
           ^^^^^^^^^^^^^^^^^
  File "/Users/username/Library/Application Support/pdm/venv/lib/python3.11/site-packages/pdm/core.py", line 191, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/Users/username/Library/Application Support/pdm/venv/lib/python3.11/site-packages/pdm/core.py", line 186, in main
    f(project, options)
  File "/Users/username/Library/Application Support/pdm/venv/lib/python3.11/site-packages/pdm/cli/commands/add.py", line 58, in handle
    actions.do_add(
  File "/Users/username/Library/Application Support/pdm/venv/lib/python3.11/site-packages/pdm/cli/actions.py", line 284, in do_add
    resolved = do_lock(
               ^^^^^^^^
  File "/Users/username/Library/Application Support/pdm/venv/lib/python3.11/site-packages/pdm/cli/actions.py", line 94, in do_lock
    mapping, dependencies = resolve(
                            ^^^^^^^^
  File "/Users/username/Library/Application Support/pdm/venv/lib/python3.11/site-packages/pdm/resolver/core.py", line 35, in resolve
    result = resolver.resolve(requirements, max_rounds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/Library/Application Support/pdm/venv/lib/python3.11/site-packages/resolvelib/resolvers.py", line 521, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/Library/Application Support/pdm/venv/lib/python3.11/site-packages/resolvelib/resolvers.py", line 372, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/Users/username/Library/Application Support/pdm/venv/lib/python3.11/site-packages/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/Users/username/Library/Application Support/pdm/venv/lib/python3.11/site-packages/resolvelib/structs.py", line 127, in __bool__
    next(iter(self))
  File "/Users/username/Library/Application Support/pdm/venv/lib/python3.11/site-packages/pdm/resolver/providers.py", line 261, in matches_gen
    yield from super_find()
               ^^^^^^^^^^^^
  File "/Users/username/Library/Application Support/pdm/venv/lib/python3.11/site-packages/pdm/resolver/providers.py", line 150, in matches_gen
    candidates = self._find_candidates(reqs[0])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/Library/Application Support/pdm/venv/lib/python3.11/site-packages/pdm/resolver/providers.py", line 132, in _find_candidates
    return self.repository.find_candidates(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/Library/Application Support/pdm/venv/lib/python3.11/site-packages/pdm/models/repositories.py", line 150, in find_candidates
    cans = list(self._find_candidates(requirement))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/Library/Application Support/pdm/venv/lib/python3.11/site-packages/pdm/models/repositories.py", line 338, in _find_candidates
    for c in finder.find_all_packages(requirement.project_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/Library/Application Support/pdm/venv/lib/python3.11/site-packages/unearth/finder.py", line 243, in find_all_packages
    return sorted(
           ^^^^^^^
  File "/Users/username/Library/Application Support/pdm/venv/lib/python3.11/site-packages/unearth/finder.py", line 218, in _find_packages
    yield from self._evaluate_links(
  File "/Users/username/Library/Application Support/pdm/venv/lib/python3.11/site-packages/unearth/collector.py", line 133, in collect_links_from_location
    yield from _collect_links_from_index(session, location)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/Library/Application Support/pdm/venv/lib/python3.11/site-packages/unearth/collector.py", line 153, in _collect_links_from_index
    page = fetch_page(session, location)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/Library/Application Support/pdm/venv/lib/python3.11/site-packages/unearth/collector.py", line 140, in fetch_page
    resp = _get_html_response(session, location)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/Library/Application Support/pdm/venv/lib/python3.11/site-packages/unearth/collector.py", line 175, in _get_html_response
    resp = session.get(
           ^^^^^^^^^^^^
  File "/Users/username/Library/Application Support/pdm/venv/lib/python3.11/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/Library/Application Support/pdm/venv/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/Library/Application Support/pdm/venv/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/Library/Application Support/pdm/venv/lib/python3.11/site-packages/cachecontrol/adapter.py", line 57, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/Library/Application Support/pdm/venv/lib/python3.11/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/numpy/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10503e910>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

## Expected behavior
the targted local folder should have been accessed and the numpy.whl file present in the targeted folder should have been installed by PDM

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:

```
PDM version:
2.3.4
Python Interpreter:
/Users/username/.pyenv/versions/3.11.1/bin/python3.11 (3.11)
Project Root:
/Users/username/DV/pdmhow
Project Packages:
/Users/username/DV/pdmhow/pypackages/3.11
{
"implementation_name": "cpython",
"implementation_version": "3.11.1",
"os_name": "posix",
"platform_machine": "arm64",
"platform_release": "22.2.0",
"platform_system": "Darwin",
"platform_version": "Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022;
root:xnu-8792.61.2~4/RELEASE_ARM64_T6000",
"python_full_version": "3.11.1",
"platform_python_implementation": "CPython",
"python_version": "3.11",
"sys_platform": "darwin"
}

**Comment by frostming** [comment]
Closing: https://github.com/pdm-project/pdm/issues/1607#issuecomment-1376569979
