### ISSUE TITLE
pdm crashes with python build from source

### ISSUE THREAD

**Issue by ssbarnea** [pdm-project/pdm#1631]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Build python from source, using pyenv to install a `-dev` edition suck `3.11-dev` should suffice.
## Actual behavior

```
Traceback (most recent call last):
  File "/Users/ssbarnea/.pyenv/versions/3.11-dev/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/ssbarnea/.pyenv/versions/3.11-dev/lib/python3.11/site-packages/pdm/core.py", line 259, in main
    return Core().main(args)
           ^^^^^^^^^^^^^^^^^
  File "/Users/ssbarnea/.pyenv/versions/3.11-dev/lib/python3.11/site-packages/pdm/core.py", line 205, in main
    check_update(project)
  File "/Users/ssbarnea/.pyenv/versions/3.11-dev/lib/python3.11/site-packages/pdm/cli/actions.py", line 862, in check_update
    latest_version = get_latest_version(project)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ssbarnea/.pyenv/versions/3.11-dev/lib/python3.11/site-packages/pdm/cli/actions.py", line 848, in get_latest_version
    latest_version = get_latest_pdm_version_from_pypi(project)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ssbarnea/.pyenv/versions/3.11-dev/lib/python3.11/site-packages/pdm/cli/actions.py", line 830, in get_latest_pdm_version_from_pypi
    with environment.get_finder([project.default_source]) as finder:
  File "/Users/ssbarnea/.pyenv/versions/3.11-dev/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/Users/ssbarnea/.pyenv/versions/3.11-dev/lib/python3.11/site-packages/pdm/models/environment.py", line 166, in get_finder
    target_python=self.target_python,
                  ^^^^^^^^^^^^^^^^^^
  File "/Users/ssbarnea/.pyenv/versions/3.11-dev/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/Users/ssbarnea/.pyenv/versions/3.11-dev/lib/python3.11/site-packages/pdm/models/environment.py", line 116, in target_python
    python_version = self.interpreter.version_tuple
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ssbarnea/.pyenv/versions/3.11-dev/lib/python3.11/site-packages/pdm/models/python.py", line 64, in version_tuple
    return (self.major, self.minor, self.micro)
            ^^^^^^^^^^
  File "/Users/ssbarnea/.pyenv/versions/3.11-dev/lib/python3.11/site-packages/pdm/models/python.py", line 52, in major
    return self._py_ver.major
           ^^^^^^^^^^^^^^^^^^
  File "/Users/ssbarnea/.pyenv/versions/3.11-dev/lib/python3.11/site-packages/findpython/python.py", line 71, in major
    return self.version.major
           ^^^^^^^^^^^^
  File "/Users/ssbarnea/.pyenv/versions/3.11-dev/lib/python3.11/site-packages/findpython/python.py", line 65, in version
    self._version = self._get_version()
                    ^^^^^^^^^^^^^^^^^^^
  File "/Users/ssbarnea/.pyenv/versions/3.11-dev/lib/python3.11/site-packages/findpython/python.py", line 165, in _get_version
    return Version(version)
           ^^^^^^^^^^^^^^^^
  File "/Users/ssbarnea/.pyenv/versions/3.11-dev/lib/python3.11/site-packages/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '3.11.0+'
make: *** [check] Error 1
```

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
N/A due to crash, but installed latest using pip

$ python3 --version
Python 3.11.0+
```

Apparently the bug is caused by https://github.com/frostming/findpython/issues/12 but the fact that it was not addressed in more than 3 months makes me wonder about how safe is to add pdm as a project dependency.

**Comment by frostming** [comment]
> Apparently the bug is caused by [frostming/findpython#12](https://github.com/frostming/findpython/issues/12) but the fact that it was not addressed in more than 3 months makes me wonder about how safe is to add pdm as a project dependency.

It is not clear how we should fix the issue, the version parser and the version range depend on `packaging` which doesn't support the version as such.

**Comment by ssbarnea** [comment]
Duplicate of #1510
