### ISSUE TITLE
PDM build fails if README.md is saved with UTF-16 LE encoding

### ISSUE THREAD

**Issue by morfinPL** [pdm-project/pdm#1638]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

1. Save your `README.md` with `UTF-16 LE` encoding - can be done quickly with VS code.
2. Run `pdm build`.

## Actual behavior

Building of sdist fails with:
```bash
D:\Projects\private\SOME_PROJECT>pdm build -v
Building sdist...
pdm.termui: Preparing isolated env for PEP 517 build...
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   pdm-pep517>=1.0
pdm.termui:   python>=3.11.1,<3.11.2
pdm.termui:   Adding requirement pdm-pep517>=1.0
pdm.termui:   Adding requirement python>=3.11.1,<3.11.2
pdm.termui: ======== Starting round 0 ========
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
pdm.termui: Pinning: pdm-pep517 1.0.6
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
pdm.termui: ======== Resolution Result ========
pdm.termui: Stable pins:
pdm.termui:       python None
pdm.termui:   pdm-pep517 1.0.6
pdm.termui: Installing pdm-pep517 1.0.6
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/71/2a/ae8abd6ebb76edd97e0c3dc3e61913df438c17e44a9aed05fd2073bb800f/pdm_pep517-1.0.6-py3-none-any.whl (from https://pypi.org/simple/pdm-pep517/)>   
pdm.termui: C:\Users\SOME_USER\AppData\Local\Temp\pdm-build-env-rvnphp3x-shared\Lib\site-packages\pdm\pep517\sdist.py:53: PDMWarning: No license files are matched with glob patterns ['LICENSES/*', 'LICEN[CS]E*', 'COPYING*', 'NOTICE*', 'AUTHORS*'].
pdm.termui:   super()._find_files_iter(for_sdist), self.find_license_files()
pdm.termui:  - Adding ...
pdm.termui:  - Adding pyproject.toml
pdm.termui:  - Adding README.md
pdm.termui: Traceback (most recent call last):
pdm.termui:   File "C:\Users\SOME_USER\AppData\Roaming\pdm\venv\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 354, in <module>
pdm.termui:     main()
pdm.termui:   File "C:\Users\SOME_USER\AppData\Roaming\pdm\venv\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 336, in main
pdm.termui:     json_out['return_val'] = hook(**hook_input['kwargs'])
pdm.termui:                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pdm.termui:   File "C:\Users\SOME_USER\AppData\Roaming\pdm\venv\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 305, in build_sdist
pdm.termui:     return backend.build_sdist(sdist_directory, config_settings)
pdm.termui:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pdm.termui:   File "C:\Users\SOME_USER\AppData\Local\Temp\pdm-build-env-rvnphp3x-shared\Lib\site-packages\pdm\pep517\api.py", line 84, in build_sdist
pdm.termui:     return Path(builder.build(sdist_directory)).name
pdm.termui:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pdm.termui:   File "C:\Users\SOME_USER\AppData\Local\Temp\pdm-build-env-rvnphp3x-shared\Lib\site-packages\pdm\pep517\sdist.py", line 82, in build
pdm.termui:     pkg_info = self.format_pkginfo(False).encode("utf-8")
pdm.termui:                ^^^^^^^^^^^^^^^^^^^^^^^^^^
pdm.termui:   File "C:\Users\SOME_USER\AppData\Local\Temp\pdm-build-env-rvnphp3x-shared\Lib\site-packages\pdm\pep517\base.py", line 431, in format_pkginfo
pdm.termui:     if meta.long_description:
pdm.termui:        ^^^^^^^^^^^^^^^^^^^^^
pdm.termui:   File "C:\Users\SOME_USER\AppData\Local\Temp\pdm-build-env-rvnphp3x-shared\Lib\site-packages\pdm\pep517\metadata.py", line 40, in __get__
pdm.termui:     rv = self.fget(instance, rv)
pdm.termui:          ^^^^^^^^^^^^^^^^^^^^^^^
pdm.termui:   File "C:\Users\SOME_USER\AppData\Local\Temp\pdm-build-env-rvnphp3x-shared\Lib\site-packages\pdm\pep517\metadata.py", line 89, in _get_readme_content
pdm.termui:     return Path(value).read_text(encoding=self.DEFAULT_ENCODING)
pdm.termui:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pdm.termui:   File "C:\Users\SOME_USER\.pyenv\pyenv-win\versions\3.11.1\Lib\pathlib.py", line 1059, in read_text
pdm.termui:     return f.read()
pdm.termui:            ^^^^^^^^
pdm.termui:   File "<frozen codecs>", line 322, in decode
pdm.termui: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\SOME_USER\AppData\Roaming\Python\Scripts\pdm.exe\__main__.py", line 7, in <module>      
  File "C:\Users\SOME_USER\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\core.py", line 259, in main    
    return Core().main(args)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\SOME_USER\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\core.py", line 191, in main    
    raise cast(Exception, err).with_traceback(traceback)
  File "C:\Users\SOME_USER\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\core.py", line 186, in main    
    f(project, options)
  File "C:\Users\SOME_USER\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\cli\commands\build.py", line 66, in handle
    actions.do_build(
  File "C:\Users\SOME_USER\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\cli\actions.py", line 506, in do_build
    loc = SdistBuilder(project.root, project.environment).build(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SOME_USER\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\builders\sdist.py", line 21, in build
    filename = self._hook.build_sdist(out_dir, config_settings)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SOME_USER\AppData\Roaming\pdm\venv\Lib\site-packages\pyproject_hooks\_impl.py", line 292, in build_sdist
    return self._call_hook('build_sdist', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SOME_USER\AppData\Roaming\pdm\venv\Lib\site-packages\pyproject_hooks\_impl.py", line 311, in _call_hook
    self._subprocess_runner(
  File "C:\Users\SOME_USER\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\builders\base.py", line 261, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SOME_USER\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\builders\base.py", line 107, in log_subprocessor
    raise build_error(e) from None
pdm.exceptions.BuildError: Build backend raised error: Showing the last 10 lines of the build output:
    rv = self.fget(instance, rv)
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SOME_USER\AppData\Local\Temp\pdm-build-env-rvnphp3x-shared\Lib\site-packages\pdm\pep517\metadata.py", line 89, in _get_readme_content
    return Path(value).read_text(encoding=self.DEFAULT_ENCODING)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SOME_USER\.pyenv\pyenv-win\versions\3.11.1\Lib\pathlib.py", line 1059, in read_text     
    return f.read()
           ^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

D:\Projects\private\SOME_PROJECT>
```

You can achieve the same result with the command `pdm build --no-sdist`, then the wheel build fails. It also fails for all available build systems.

## Expected behavior

Everything works after changing the encoding to `UTF8` or `Central European ISO`. It would be nice to warn in such cases about supported encodings or mention somewhere in docs that encoding of files can be the root of the issue. I had this issue when I tested first project with `pdm`, it was almost a dealbreaker. I have no idea why I had this `UTF-16 LE`.

## Environment Information

```bash
D:\Projects\private\SOME_PROJECT>pdm info     
PDM version:
  2.4.0
Python Interpreter:
  D:\Projects\private\SOME_PROJECT\.venv\Scripts\python.exe (3.11)
Project Root:
  D:/Projects/private/SOME_PROJECT
Project Packages:
  None
D:\Projects\private\SOME_PROJECT>pdm info --env
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.1",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19045",
  "python_full_version": "3.11.1",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "win32"
}

```

**Comment by frostming** [comment]
I don't think PDM is doing anything wrong reading the [specification of PEP 621](https://peps.python.org/pep-0621/#readme). Closing this.

**Comment by morfinPL** [comment]
You're right, thanks for pointing that out! 😄
