### ISSUE TITLE
Self update always failing on Windows

### ISSUE THREAD

**Issue by rn4n** [pdm-project/pdm#1642]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

- Install the previous version (I'm using the 2.3.4) of pdm and execute any command, i.e `pdm init`
- Wait for the upgrade message after the command execution.
- Run the `pdm self update` command.

## Actual behavior

After run the command, this error is shown:

```
pdm self update
[UnicodeDecodeError]: 'utf-8' codec can't decode byte 0xe1 in position 4725: invalid continuation byte
Add '-v' to see the detailed traceback
```
After this, pdm is broken:
```
> pdm -v
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Me\AppData\Local\Programs\Python\Python311\Scripts\pdm.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'pdm.core'
```
Running the `self update` with `-v` flag:

```
pdm self update -v
Running pip command: ['install', '--upgrade', 'pdm==2.4.0']
Traceback (most recent call last):
  File "C:\Users\Me\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\cli\commands\self_cmd.py", line 265, in handle
  File "C:\Users\Me\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\cli\commands\self_cmd.py", line 41, in run_pip
  File "C:\Users\Me\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Me\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\Me\\AppData\\Local\\Programs\\Python\\Python311\\python.exe', '-Esm', 'pip', '-v', 'install', '--upgrade', 'pdm==2.4.0']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Me\AppData\Local\Programs\Python\Python311\Scripts\pdm.exe\__main__.py", line 7, in <module>
  File "C:\Users\Me\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\core.py", line 259, in main
  File "C:\Users\Me\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\core.py", line 191, in main
  File "C:\Users\Me\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\core.py", line 186, in main
  File "C:\Users\Me\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\cli\commands\self_cmd.py", line 269, in handle
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 7512: invalid continuation byte
```
Executed using cmd and Powershell, in user mode and administrator mode, in both the error occurs.

## Expected behavior

I expected pdm to update without any errors.

## Environment Information

```
> pdm info
PDM version:
  2.3.4
Python Interpreter:
  C:\Users\Me\Desktop\next\ibank\.venv\Scripts\python.exe (3.11)
Project Root:
  C:/Users/Me/Desktop/repositories
Project Packages:
  None

PDM 2.3.4 is installed, while 2.4.0 is available.
Please run `pdm self update` to upgrade.
Run `pdm config check_update false` to disable the check.
```

```
> pdm info --env
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.1",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.22621",
  "python_full_version": "3.11.1",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "win32"
}

PDM 2.3.4 is installed, while 2.4.0 is available.
Please run `pdm self update` to upgrade.
Run `pdm config check_update false` to disable the check.
```

**Comment by frostming** [comment]
Duplicate with #1602, please upgrade to 2.4.0 manually
