### ISSUE TITLE
AttributeError in pdm add in venv mode

### ISSUE THREAD

**Issue by eltoder** [pdm-project/pdm#1671]
## Steps to reproduce

```bash
mkdir proj && cd proj
pdm init  # make sure to select venv mode
pdm add matplotlib
```

## Actual behavior

Produces an error:
```
Error processing line 1 of /home/elt/code/pdm/.venv/lib/python3.10/site-packages/matplotlib-3.6.3-py3.10-nspkg.pth:

  Traceback (most recent call last):
    File "/usr/lib/python3.10/site.py", line 192, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 568, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored
Error processing line 1 of /home/elt/code/pdm/.venv/lib/python3.10/site-packages/matplotlib-3.6.3-py3.10-nspkg.pth:

  Traceback (most recent call last):
    File "/usr/lib/python3.10/site.py", line 192, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 568, in module_from_spec
```

The command still succeeds, however the package is not installed and importing it fails. This may be considered a separate bug.

## Expected behavior

I expect matplotlib to be installed successfully. Installing the same package in PEP 582 mode works as expected.

## Environment Information

```bash
PDM version:
  2.4.2
Python Interpreter:
  /home/elt/code/pdm/.venv/bin/python (3.10)
Project Root:
  /home/elt/code/pdm
Project Packages:
  None
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.6",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.15.79.1-microsoft-standard-WSL2",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Wed Nov 23 01:01:46 UTC 2022",
  "python_full_version": "3.10.6",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "linux"
}
```

I also reproduced this in Debian 11 with python 3.10 and 3.11.

**Comment by eltoder** [comment]
<details>
  <summary>Full output of pdm add</summary>
  ```
$ pdm add -v matplotlib
Adding packages to default dependencies: matplotlib
STATUS: Resolving dependencies
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   matplotlib
pdm.termui:   python>=3.10
pdm.termui:   Adding requirement matplotlib
pdm.termui:   Adding requirement python>=3.10
pdm.termui: ======== Starting round 0 ========
STATUS: Resolving: new pin python>=3.10
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
pdm.termui:   Adding requirement contourpy>=1.0.1(from matplotlib 3.6.3)
pdm.termui:   Adding requirement cycler>=0.10(from matplotlib 3.6.3)
pdm.termui:   Adding requirement fonttools>=4.22.0(from matplotlib 3.6.3)
pdm.termui:   Adding requirement kiwisolver>=1.0.1(from matplotlib 3.6.3)
pdm.termui:   Adding requirement numpy>=1.19(from matplotlib 3.6.3)
pdm.termui:   Adding requirement packaging>=20.0(from matplotlib 3.6.3)
pdm.termui:   Adding requirement pillow>=6.2.0(from matplotlib 3.6.3)
pdm.termui:   Adding requirement pyparsing>=2.2.1(from matplotlib 3.6.3)
pdm.termui:   Adding requirement python-dateutil>=2.7(from matplotlib 3.6.3)
STATUS: Resolving: new pin matplotlib 3.6.3
pdm.termui: Pinning: matplotlib 3.6.3
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
pdm.termui:   Adding requirement numpy>=1.16(from contourpy 1.0.7)
STATUS: Resolving: new pin contourpy 1.0.7
pdm.termui: Pinning: contourpy 1.0.7
pdm.termui: ======== Ending round 2 ========
pdm.termui: ======== Starting round 3 ========
STATUS: Resolving: new pin numpy 1.24.1
pdm.termui: Pinning: numpy 1.24.1
pdm.termui: ======== Ending round 3 ========
pdm.termui: ======== Starting round 4 ========
STATUS: Resolving: new pin cycler 0.11.0
pdm.termui: Pinning: cycler 0.11.0
pdm.termui: ======== Ending round 4 ========
pdm.termui: ======== Starting round 5 ========
STATUS: Resolving: new pin fonttools 4.38.0
pdm.termui: Pinning: fonttools 4.38.0
pdm.termui: ======== Ending round 5 ========
pdm.termui: ======== Starting round 6 ========
STATUS: Resolving: new pin kiwisolver 1.4.4
pdm.termui: Pinning: kiwisolver 1.4.4
pdm.termui: ======== Ending round 6 ========
pdm.termui: ======== Starting round 7 ========
STATUS: Resolving: new pin packaging 23.0
pdm.termui: Pinning: packaging 23.0
pdm.termui: ======== Ending round 7 ========
pdm.termui: ======== Starting round 8 ========
STATUS: Resolving: new pin pillow 9.4.0
pdm.termui: Pinning: pillow 9.4.0
pdm.termui: ======== Ending round 8 ========
pdm.termui: ======== Starting round 9 ========
STATUS: Resolving: new pin pyparsing 3.0.9
pdm.termui: Pinning: pyparsing 3.0.9
pdm.termui: ======== Ending round 9 ========
pdm.termui: ======== Starting round 10 ========
pdm.termui:   Adding requirement six>=1.5(from python-dateutil 2.8.2)
STATUS: Resolving: new pin python-dateutil 2.8.2
pdm.termui: Pinning: python-dateutil 2.8.2
pdm.termui: ======== Ending round 10 ========
pdm.termui: ======== Starting round 11 ========
STATUS: Resolving: new pin six 1.16.0
pdm.termui: Pinning: six 1.16.0
pdm.termui: ======== Ending round 11 ========
pdm.termui: ======== Starting round 12 ========
pdm.termui: ======== Resolution Result ========
pdm.termui: Stable pins:
pdm.termui:            python None
pdm.termui:        matplotlib 3.6.3
pdm.termui:         contourpy 1.0.7
pdm.termui:             numpy 1.24.1
pdm.termui:            cycler 0.11.0
pdm.termui:         fonttools 4.38.0
pdm.termui:        kiwisolver 1.4.4
pdm.termui:         packaging 23.0
pdm.termui:            pillow 9.4.0
pdm.termui:         pyparsing 3.0.9
pdm.termui:   python-dateutil 2.8.2
pdm.termui:               six 1.16.0
STATUS: Fetching hashes for resolved packages...
pdm.termui: Fetching hashes for matplotlib@3.6.3
pdm.termui: Fetching hashes for contourpy@1.0.7
pdm.termui: Fetching hashes for numpy@1.24.1
pdm.termui: Fetching hashes for cycler@0.11.0
pdm.termui: Fetching hashes for fonttools@4.38.0
pdm.termui: Fetching hashes for kiwisolver@1.4.4
pdm.termui: Fetching hashes for packaging@23.0
pdm.termui: Fetching hashes for pillow@9.4.0
pdm.termui: Fetching hashes for pyparsing@3.0.9
pdm.termui: Fetching hashes for python-dateutil@2.8.2
pdm.termui: Fetching hashes for six@1.16.0
🔒 Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
STATUS: Resolving packages from lockfile...
STATUS: Fetching hashes for resolved packages...
pdm.termui: Fetching hashes for matplotlib@3.6.3
pdm.termui: Fetching hashes for contourpy@1.0.7
pdm.termui: Fetching hashes for numpy@1.24.1
pdm.termui: Fetching hashes for cycler@0.11.0
pdm.termui: Fetching hashes for packaging@23.0
pdm.termui: Fetching hashes for kiwisolver@1.4.4
pdm.termui: Fetching hashes for python-dateutil@2.8.2
pdm.termui: Fetching hashes for pillow@9.4.0
pdm.termui: Fetching hashes for pyparsing@3.0.9
pdm.termui: Fetching hashes for six@1.16.0
pdm.termui: Fetching hashes for fonttools@4.38.0
Synchronizing working set with lock file: 11 to add, 0 to update, 0 to remove

unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/5c/f9/695d6bedebd747e5eb0fe8fad57b72fdf25411273a39791cde838d5a8f51/cycler-0.11.0-py3-none-any.whl (from None)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/ec/59/5eac40e348a7bf803cea221bcd27f74a49cb81667b400fdfbb680e86e7bb/contourpy-1.0.7-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (from None)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/ed/35/a31aed2993e398f6b09a790a181a7927eb14610ee8bbf02dc14d31677f1c/packaging-23.0-py3-none-any.whl (from None)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/e3/d9/e9bae85e84737e76ebbcbea13607236da0c0699baed0ae4f1151b728a608/fonttools-4.38.0-py3-none-any.whl (from None)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/79/0f/5cc4ca3df66c49817944b9a1c7343ba70aefffc868ddf651d7839cc5dffd/kiwisolver-1.4.4-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (from None)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/40/d1/b646804eb150a94c76abc54576ea885f71030bab6c541ccb9594db5da64a/Pillow-9.4.0-cp310-cp310-manylinux_2_28_x86_64.whl (from None)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/44/15/4225ce5758885913338c8bf2bf2cad8bd00691fdcfea85147450a4eb495d/matplotlib-3.6.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (from None)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/3d/17/2cc40e1ed44f37b0bab7d62e0c6ba88362da23f48e52833ffdd1b9dfc220/numpy-1.24.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (from None)>
  ✔ Install cycler 0.11.0 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/6c/10/a7d0fa5baea8fe7b50f448ab742f26f52b80bfca85ac2be9d35cdd9a3246/pyparsing-3.0.9-py3-none-any.whl (from None)>
  ✔ Install packaging 23.0 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/36/7a/87837f39d0296e723bb9b62bbb257d0355c7f6128853c78955f57342a56d/python_dateutil-2.8.2-py2.py3-none-any.whl (from None)>
  ✔ Install contourpy 1.0.7 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl (from None)>
  ✔ Install pyparsing 3.0.9 successful
  ✔ Install six 1.16.0 successful
  ✔ Install python-dateutil 2.8.2 successful
  ✔ Install kiwisolver 1.4.4 successful
Error processing line 1 of /home/elt/code/pdm/proj/.venv/lib/python3.10/site-packages/matplotlib-3.6.3-py3.10-nspkg.pth:

  Traceback (most recent call last):
    File "/usr/lib/python3.10/site.py", line 192, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 568, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored
Error processing line 1 of /home/elt/code/pdm/proj/.venv/lib/python3.10/site-packages/matplotlib-3.6.3-py3.10-nspkg.pth:

  Traceback (most recent call last):
    File "/usr/lib/python3.10/site.py", line 192, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 568, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored
  ✔ Install pillow 9.4.0 successful
  ✔ Install fonttools 4.38.0 successful
  ✔ Install matplotlib 3.6.3 successful
  ✔ Install numpy 1.24.1 successful

🎉 All complete!
  ```
</details>

**Comment by frostming** [comment]
Can't reproduce locally. 

Here is the content of `matplotlib-3.6.3`:

```python
iimport sys, types, os
has_mfs = sys.version_info > (3, 5)
p = os.path.join(sys._getframe(1).f_locals['sitedir'], *('mpl_toolkits',))
importlib = has_mfs and __import__('importlib.util')
has_mfs and __import__('importlib.machinery')
m = has_mfs and sys.modules.setdefault('mpl_toolkits', importlib.util.module_from_spec(importlib.machinery.PathFinder.find_spec('mpl_toolkits', [os.path.dirname(p)])))
m = m or sys.modules.setdefault('mpl_toolkits', types.ModuleType('mpl_toolkits'))
mp = (m or []) and m.__dict__.setdefault('__path__',[])
(p not in mp) and mp.append(p)
```

And the error occurs at:

```python
importlib.util.module_from_spec(importlib.machinery.PathFinder.find_spec('mpl_toolkits', [os.path.dirname(p)])))
```

It should be a problem of race condition with parallel installation: the file is trying to find `mpl_toolkit` module while it might not be installed at this point.

Turn off `install.parallel` would fix it but basically this error can be ignored.
```

**Comment by eltoder** [comment]
@frostming You are right, setting `install.parallel` to false fixes the issue. However, both python.use_venv and install.parallel are true by default, which gives a bad first-time user experience on one of the most widely used python packages. This is a shame, because pdm is otherwise pretty awesome.

It sounds like the problem can be avoided if the pth file is only copied after the rest of the installation is done. Do you think that's possible?

**Comment by mpekurin** [comment]
I can confirm the issue exists with the default settings.

<details><summary><code>pdm add -v matplotlib</code> output</summary>
<p>

```
Adding packages to default dependencies: matplotlib
STATUS: Resolving dependencies
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   matplotlib
pdm.termui:   python>=3.10
pdm.termui:   Adding requirement matplotlib
pdm.termui:   Adding requirement python>=3.10
pdm.termui: ======== Starting round 0 ========
STATUS: Resolving: new pin python>=3.10
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
pdm.termui:   Adding requirement contourpy>=1.0.1(from matplotlib 3.7.1)
pdm.termui:   Adding requirement cycler>=0.10(from matplotlib 3.7.1)
pdm.termui:   Adding requirement fonttools>=4.22.0(from matplotlib 3.7.1)
pdm.termui:   Adding requirement kiwisolver>=1.0.1(from matplotlib 3.7.1)
pdm.termui:   Adding requirement numpy>=1.20(from matplotlib 3.7.1)
pdm.termui:   Adding requirement packaging>=20.0(from matplotlib 3.7.1)
pdm.termui:   Adding requirement pillow>=6.2.0(from matplotlib 3.7.1)
pdm.termui:   Adding requirement pyparsing>=2.3.1(from matplotlib 3.7.1)
pdm.termui:   Adding requirement python-dateutil>=2.7(from matplotlib 3.7.1)
STATUS: Resolving: new pin matplotlib 3.7.1
pdm.termui: Pinning: matplotlib 3.7.1
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
pdm.termui:   Adding requirement numpy>=1.16(from contourpy 1.0.7)
STATUS: Resolving: new pin contourpy 1.0.7
pdm.termui: Pinning: contourpy 1.0.7
pdm.termui: ======== Ending round 2 ========
pdm.termui: ======== Starting round 3 ========
STATUS: Resolving: new pin numpy 1.24.2
pdm.termui: Pinning: numpy 1.24.2
pdm.termui: ======== Ending round 3 ========
pdm.termui: ======== Starting round 4 ========
STATUS: Resolving: new pin cycler 0.11.0
pdm.termui: Pinning: cycler 0.11.0
pdm.termui: ======== Ending round 4 ========
pdm.termui: ======== Starting round 5 ========
STATUS: Resolving: new pin fonttools 4.39.2
pdm.termui: Pinning: fonttools 4.39.2
pdm.termui: ======== Ending round 5 ========
pdm.termui: ======== Starting round 6 ========
STATUS: Resolving: new pin kiwisolver 1.4.4
pdm.termui: Pinning: kiwisolver 1.4.4
pdm.termui: ======== Ending round 6 ========
pdm.termui: ======== Starting round 7 ========
STATUS: Resolving: new pin packaging 23.0
pdm.termui: Pinning: packaging 23.0
pdm.termui: ======== Ending round 7 ========
pdm.termui: ======== Starting round 8 ========
STATUS: Resolving: new pin pillow 9.4.0
pdm.termui: Pinning: pillow 9.4.0
pdm.termui: ======== Ending round 8 ========
pdm.termui: ======== Starting round 9 ========
STATUS: Resolving: new pin pyparsing 3.0.9
pdm.termui: Pinning: pyparsing 3.0.9
pdm.termui: ======== Ending round 9 ========
pdm.termui: ======== Starting round 10 ========
pdm.termui:   Adding requirement six>=1.5(from python-dateutil 2.8.2)
STATUS: Resolving: new pin python-dateutil 2.8.2
pdm.termui: Pinning: python-dateutil 2.8.2
pdm.termui: ======== Ending round 10 ========
pdm.termui: ======== Starting round 11 ========
STATUS: Resolving: new pin six 1.16.0
pdm.termui: Pinning: six 1.16.0
pdm.termui: ======== Ending round 11 ========
pdm.termui: ======== Starting round 12 ========
pdm.termui: ======== Resolution Result ========
pdm.termui: Stable pins:
pdm.termui:            python None
pdm.termui:        matplotlib 3.7.1
pdm.termui:         contourpy 1.0.7
pdm.termui:             numpy 1.24.2
pdm.termui:            cycler 0.11.0
pdm.termui:         fonttools 4.39.2
pdm.termui:        kiwisolver 1.4.4
pdm.termui:         packaging 23.0
pdm.termui:            pillow 9.4.0
pdm.termui:         pyparsing 3.0.9
pdm.termui:   python-dateutil 2.8.2
pdm.termui:               six 1.16.0
STATUS: Fetching hashes for resolved packages...
pdm.termui: Fetching hashes for matplotlib@3.7.1
pdm.termui: Fetching hashes for contourpy@1.0.7
pdm.termui: Fetching hashes for numpy@1.24.2
pdm.termui: Fetching hashes for cycler@0.11.0
pdm.termui: Fetching hashes for fonttools@4.39.2
pdm.termui: Fetching hashes for kiwisolver@1.4.4
pdm.termui: Fetching hashes for packaging@23.0
pdm.termui: Fetching hashes for pillow@9.4.0
pdm.termui: Fetching hashes for pyparsing@3.0.9
pdm.termui: Fetching hashes for python-dateutil@2.8.2
pdm.termui: Fetching hashes for six@1.16.0
🔒 Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
STATUS: Resolving packages from lockfile...
STATUS: Fetching hashes for resolved packages...
pdm.termui: Fetching hashes for matplotlib@3.7.1
pdm.termui: Fetching hashes for contourpy@1.0.7
pdm.termui: Fetching hashes for cycler@0.11.0
pdm.termui: Fetching hashes for numpy@1.24.2
pdm.termui: Fetching hashes for fonttools@4.39.2
pdm.termui: Fetching hashes for kiwisolver@1.4.4
pdm.termui: Fetching hashes for pyparsing@3.0.9
pdm.termui: Fetching hashes for pillow@9.4.0
pdm.termui: Fetching hashes for python-dateutil@2.8.2
pdm.termui: Fetching hashes for packaging@23.0
pdm.termui: Fetching hashes for six@1.16.0
Synchronizing working set with lock file: 11 to add, 0 to update, 0 to remove

unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/0c/e6/77183fd874c8f6162a1c8f3b91a96ad910d10aef010a51a4db8c2f96f3dd/fonttools-4.39.2-py3-none-any.whl (from None)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/b6/b8/6894c9e851f7442ebbc054537f56021c9ebc0691799ac4b92e380f3a2712/contourpy-1.0.7-cp310-cp310-win_amd64.whl (from None)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/5c/f9/695d6bedebd747e5eb0fe8fad57b72fdf25411273a39791cde838d5a8f51/cycler-0.11.0-py3-none-any.whl (from None)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/68/20/2ce1186ef4edf47281faf58f6dd72a1fcd2be1fc66514bd2d220097bdcd1/kiwisolver-1.4.4-cp310-cp310-win_amd64.whl (from None)>
  ✔ Install contourpy 1.0.7 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/07/76/fde990f131450f08eb06e50814b98d347b14d7916c0ec31cba0a65a9be2b/matplotlib-3.7.1-cp310-cp310-win_amd64.whl (from None)>
  ✔ Install kiwisolver 1.4.4 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/fa/df/53e8c0c8ccecf360b827a3d2b1b6060644c635c3149a9d6415a6fe4ccf44/numpy-1.24.2-cp310-cp310-win_amd64.whl (from None)>
  ✔ Install cycler 0.11.0 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/ed/35/a31aed2993e398f6b09a790a181a7927eb14610ee8bbf02dc14d31677f1c/packaging-23.0-py3-none-any.whl (from None)>
  ✔ Install packaging 23.0 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/5e/7c/293136a5171800001be33c21a51daaca68fae954b543e2c015a6bb81a716/Pillow-9.4.0-cp310-cp310-win_amd64.whl (from None)>
  ✔ Install fonttools 4.39.2 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/6c/10/a7d0fa5baea8fe7b50f448ab742f26f52b80bfca85ac2be9d35cdd9a3246/pyparsing-3.0.9-py3-none-any.whl (from None)>
Error processing line 1 of C:\Users\mpekurin\Downloads\test\.venv\lib\site-packages\matplotlib-3.7.1-py3.10-nspkg.pth:

Error processing line 1 of C:\Users\mpekurin\Downloads\test\.venv\lib\site-packages\matplotlib-3.7.1-py3.10-nspkg.pth:

Error processing line 1 of C:\Users\mpekurin\Downloads\test\.venv\lib\site-packages\matplotlib-3.7.1-py3.10-nspkg.pth:

  Traceback (most recent call last):
    File "c:\users\mpekurin\appdata\local\programs\python\python310\lib\site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 568, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored
Error processing line 1 of C:\Users\mpekurin\Downloads\test\.venv\lib\site-packages\matplotlib-3.7.1-py3.10-nspkg.pth:

  Traceback (most recent call last):
    File "c:\users\mpekurin\appdata\local\programs\python\python310\lib\site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 568, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored
  Traceback (most recent call last):
    File "c:\users\mpekurin\appdata\local\programs\python\python310\lib\site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 568, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored
  Traceback (most recent call last):
    File "c:\users\mpekurin\appdata\local\programs\python\python310\lib\site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ✔ Install matplotlib 3.7.1 successful
    File "<frozen importlib._bootstrap>", line 568, in module_from_spec
  ✔ Install pyparsing 3.0.9 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/36/7a/87837f39d0296e723bb9b62bbb257d0355c7f6128853c78955f57342a56d/python_dateutil-2.8.2-py2.py3-none-any.whl (from None)>
  AttributeError: 'NoneType' object has no attribute 'loader'
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl (from None)>

Remainder of file ignored
  ✔ Install pillow 9.4.0 successful
  ✔ Install python-dateutil 2.8.2 successful
  ✔ Install six 1.16.0 successful
  ✔ Install numpy 1.24.2 successful

🎉 All complete!
```

</p>
</details>
