### ISSUE TITLE
pdm fails when local version part is specified

### ISSUE THREAD

**Issue by dsully** [pdm-project/pdm#1703]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce
Run `pdm install -v` with the following `pyproject.toml`:

```
[project]
dependencies = [ "torch>=1.31.1+cu117" ]
name = "test"
requires-python = ">=3.10"
version = "1.0.0"

[build-system]
build-backend = "pdm.pep517.api"
requires = [ "pdm-pep517>=1.0.0" ]

[[tool.pdm.source]]
type = "index"
url = "https://download.pytorch.org/whl/cu117/"
name = "torch"
```

## Actual behavior
```
$ pdm install -v
Lock file does not exist
Updating the lock file...
Inside an active virtualenv /Users/dsully/.direnv/python-3.10.2, reusing it.
STATUS: Resolving dependencies
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   b''
pdm.termui:   python>=3.10
pdm.termui:   Adding requirement b''
Traceback (most recent call last):
  File "/Users/dsully/.direnv/python-3.10.2/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/Users/dsully/.direnv/python-3.10.2/lib/python3.10/site-packages/pdm/core.py", line 259, in main
    return Core().main(args)
  File "/Users/dsully/.direnv/python-3.10.2/lib/python3.10/site-packages/pdm/core.py", line 191, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/Users/dsully/.direnv/python-3.10.2/lib/python3.10/site-packages/pdm/core.py", line 186, in main
    f(project, options)
  File "/Users/dsully/.direnv/python-3.10.2/lib/python3.10/site-packages/pdm/cli/commands/install.py", line 58, in handle
    actions.do_lock(
  File "/Users/dsully/.direnv/python-3.10.2/lib/python3.10/site-packages/pdm/cli/actions.py", line 96, in do_lock
    mapping, dependencies = resolve(
  File "/Users/dsully/.direnv/python-3.10.2/lib/python3.10/site-packages/pdm/resolver/core.py", line 35, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "/Users/dsully/.direnv/python-3.10.2/lib/python3.10/site-packages/resolvelib/resolvers.py", line 521, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/Users/dsully/.direnv/python-3.10.2/lib/python3.10/site-packages/resolvelib/resolvers.py", line 372, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/Users/dsully/.direnv/python-3.10.2/lib/python3.10/site-packages/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/Users/dsully/.direnv/python-3.10.2/lib/python3.10/site-packages/resolvelib/structs.py", line 127, in __bool__
    next(iter(self))
  File "/Users/dsully/.direnv/python-3.10.2/lib/python3.10/site-packages/resolvelib/structs.py", line 136, in __iter__
    self._factory() if self._iterable is None else self._iterable
  File "/Users/dsully/.direnv/python-3.10.2/lib/python3.10/site-packages/pdm/resolver/providers.py", line 150, in matches_gen
    candidates = self._find_candidates(reqs[0])
  File "/Users/dsully/.direnv/python-3.10.2/lib/python3.10/site-packages/pdm/resolver/providers.py", line 127, in _find_candidates
    can = make_candidate(requirement)
  File "/Users/dsully/.direnv/python-3.10.2/lib/python3.10/site-packages/pdm/models/candidates.py", line 629, in make_candidate
    return Candidate(req, name, version, link)
  File "/Users/dsully/.direnv/python-3.10.2/lib/python3.10/site-packages/pdm/models/candidates.py", line 147, in __init__
    link = req.as_file_link()  # type: ignore
  File "/Users/dsully/.direnv/python-3.10.2/lib/python3.10/site-packages/pdm/models/requirements.py", line 324, in as_file_link
    return Link(url)
  File "<string>", line 9, in __init__
  File "/Users/dsully/.direnv/python-3.10.2/lib/python3.10/site-packages/unearth/link.py", line 54, in __post_init__
    if self.url.startswith(vcs_prefixes):
TypeError: a bytes-like object is required, not 'str'
```

## Expected behavior

pdm installs torch properly, using the `local` version part (`cu117`).

`packaging.version.Version` properly parses this according to PEP-440 & PEP-508:

```
$ python3
Python 3.10.2 (main, Feb  4 2022, 17:30:41) [Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from packaging.version import Version
>>> Version("1.13.1+cu117")
<Version('1.13.1+cu117')>
>>>
```

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
$ pdm info && pdm info --env
Inside an active virtualenv /Users/dsully/.direnv/python-3.10.2, reusing it.
PDM version:
  2.4.5
Python Interpreter:
  /Users/dsully/.direnv/python-3.10.2/bin/python (3.10)
Project Root:
  /Users/dsully
Project Packages:
  None
Inside an active virtualenv /Users/dsully/.direnv/python-3.10.2, reusing it.
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.2",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "22.3.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 22.3.0: Thu Jan  5 20:53:49 PST 2023; root:xnu-8792.81.2~2/RELEASE_X86_64",
  "python_full_version": "3.10.2",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
You can simply fix this by dropping the local version part from the specifier, it isn't allowed by PEP 440.

```python
>>> from packaging.requirements import Requirement
>>> Requirement('foo>=1.0+cu112')
Traceback (most recent call last):
  File "/Users/fming/wkspace/github/pdm/venv/lib/python3.10/site-packages/packaging/requirements.py", line 35, in __init__
    parsed = parse_requirement(requirement_string)
  File "/Users/fming/wkspace/github/pdm/venv/lib/python3.10/site-packages/packaging/_parser.py", line 64, in parse_requirement
    return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
  File "/Users/fming/wkspace/github/pdm/venv/lib/python3.10/site-packages/packaging/_parser.py", line 82, in _parse_requirement
    url, specifier, marker = _parse_requirement_details(tokenizer)
  File "/Users/fming/wkspace/github/pdm/venv/lib/python3.10/site-packages/packaging/_parser.py", line 126, in _parse_requirement_details
    marker = _parse_requirement_marker(
  File "/Users/fming/wkspace/github/pdm/venv/lib/python3.10/site-packages/packaging/_parser.py", line 147, in _parse_requirement_marker
    tokenizer.raise_syntax_error(
  File "/Users/fming/wkspace/github/pdm/venv/lib/python3.10/site-packages/packaging/_tokenizer.py", line 163, in raise_syntax_error
    raise ParserSyntaxError(
packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after version specifier)
    foo>=1.0+cu112
       ~~~~~^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/fming/wkspace/github/pdm/venv/lib/python3.10/site-packages/packaging/requirements.py", line 37, in __init__
    raise InvalidRequirement(str(e)) from e
packaging.requirements.InvalidRequirement: Expected end or semicolon (after version specifier)
    foo>=1.0+cu112
       ~~~~~^
```

**Comment by dsully** [comment]
Hi @frostming - it is supported by PEP-440: https://peps.python.org/pep-0440/#local-version-identifiers

And required by anything using pytorch.

Cc: @warsaw

**Comment by frostming** [comment]
@dsully you misunderstood me, the local version is supported as a version string, but not supported in a comparison specifier.

**Comment by dsully** [comment]
I see. What's the correct way to specify that combination then? I assume they need to be broken apart?

**Comment by frostming** [comment]
@dsully As I said, just drop it, it doesn't change the meaning of the specifier.

**Comment by frostming** [comment]
@warsaw the prefix matching is under the **version matching** category(`==` comparison`), where local versions are *allowed but ignored*. However, in the order comparisons below it(`>`, `>=`, `<`, `<=`) there is an explicit statement:

> Local version identifiers are NOT permitted in this version specifier.

**Comment by warsaw** [comment]
Thanks for the clarification @frostming.  That still begs the question about the traceback though.
