### ISSUE TITLE
AssertionError when script in bin is a binary file

### ISSUE THREAD

**Issue by pawamoy** [pdm-project/pdm#1709]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Install PDM 2.4.5, `use` a particular Python interpreter then use another one:

```console
% pdm use -v -f python3.10
Using the last selection, add '-i' to ignore it.
Using Python interpreter: /home/pawamoy/.basher-packages/pyenv/pyenv/shims/python3.10 (3.10)

% cat .pdm.toml           
[python]
path = "/home/pawamoy/.basher-packages/pyenv/pyenv/shims/python3.10"

% pdm use -v -f python3.9 
Using the last selection, add '-i' to ignore it.
Using Python interpreter: /home/pawamoy/.basher-packages/pyenv/pyenv/shims/python3.9 (3.9)
Updating executable scripts...
Traceback (most recent call last):
  File "/home/pawamoy/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 259, in main
    return Core().main(args)
           ^^^^^^^^^^^^^^^^^
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 191, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 186, in main
    f(project, options)
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/cli/commands/use.py", line 32, in handle
    actions.do_use(
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/cli/actions.py", line 666, in do_use
    project.environment.update_shebangs(selected_python.executable.as_posix())
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/models/environment.py", line 226, in update_shebangs
    child.write_bytes(_replace_shebang(child.read_bytes(), new_shebang))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/models/environment.py", line 68, in _replace_shebang
    assert match is not None
AssertionError
```
## Actual behavior

AssertionError

## Expected behavior

No AssertionError :rocket: 

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.4.5
Python Interpreter:
  /home/pawamoy/.basher-packages/pyenv/pyenv/versions/3.9.15/bin/python3.9 (3.9)
Project Root:
  /media/data/dev/duty
Project Packages:
  /media/data/dev/duty/__pypackages__/3.9
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.15",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.1.11-arch1-1",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT_DYNAMIC Thu, 09 Feb 2023 20:06:08 +0000",
  "python_full_version": "3.9.15",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

**Comment by pawamoy** [comment]
Hmmmm, actually it seems to happen on 2.4.4 as well :thinking: 
I'm investigating.

**Comment by pawamoy** [comment]
I *just* added [ruff](https://github.com/charliermarsh/ruff) as a dependency, and the exec that ends in `__pypackages__/M.m/bin` is a binary file, maybe that's the cause?

**Comment by pawamoy** [comment]
Yep, sure enough, if I remove the `ruff` exec, everything works fine again.

**Comment by pawamoy** [comment]
We could either use [this snippet](https://stackoverflow.com/a/7392391/3451029) to check if the file is a binary, and not try to update the shebang, or simply catch the AssertionError one layer above. Can send a PR, let me know :slightly_smiling_face:

**Comment by frostming** [comment]
> We could either use [this snippet](https://stackoverflow.com/a/7392391/3451029) to check if the file is a binary, and not try to update the shebang, or simply catch the AssertionError one layer above. Can send a PR, let me know 🙂

This snippet doesn't work on Windows `.exe` wrappers, where the shebang line is following a launcher binary.
You can change to `_replace_shebing(path, new_path)` and ignore the case if match is None.
