### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by olbitset** [pdm-project/pdm#1731]
After searching for the history of the relevant issues, I found that similar problems were mentioned and discussed in https://github.com/pdm-project/pdm/issues/1556 and https://github.com/pdm-project/pdm/issues/1565, and solved in version 2.3.3. Someone else faced same issue in version 2.4.2 https://github.com/pdm-project/pdm/issues/1668.

## Steps to reproduce

`pdm add IxNetwork -v` 

## Actual behavior

```bash
Adding packages to default dependencies: IxNetwork
STATUS: Resolving dependencies
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   backports.ssl>=0.0.9
pdm.termui:   pyopenssl>=23.0.0
pdm.termui:   requests>=2.28.2
pdm.termui:   websocket-client>=1.5.1
pdm.termui:   backports.ssl-match-hostname>=3.7.0.1
pdm.termui:   IxNetwork
pdm.termui:   python>=3.11
pdm.termui:   Adding requirement backports.ssl>=0.0.9
pdm.termui:   Adding requirement pyopenssl>=23.0.0
pdm.termui:   Adding requirement requests>=2.28.2
pdm.termui:   Adding requirement websocket-client>=1.5.1
pdm.termui:   Adding requirement backports.ssl-match-hostname>=3.7.0.1
pdm.termui:   Adding requirement IxNetwork
pdm.termui:   Adding requirement python>=3.11
pdm.termui: ======== Starting round 0 ========
STATUS: Resolving: new pin python>=3.11
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
STATUS: Resolving: new pin backports.ssl 0.0.9
pdm.termui: Pinning: backports.ssl 0.0.9
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
STATUS: Resolving: new pin backports.ssl-match-hostname 3.7.0.1
pdm.termui: Pinning: backports.ssl-match-hostname 3.7.0.1
pdm.termui: ======== Ending round 2 ========
pdm.termui: ======== Starting round 3 ========
pdm.termui:   Adding requirement cryptography<40,>=38.0.0(from pyopenssl 23.0.0)
STATUS: Resolving: new pin pyopenssl 23.0.0
pdm.termui: Pinning: pyopenssl 23.0.0
pdm.termui: ======== Ending round 3 ========
pdm.termui: ======== Starting round 4 ========
pdm.termui:   Adding requirement charset-normalizer<4,>=2(from requests 2.28.2)
pdm.termui:   Adding requirement idna<4,>=2.5(from requests 2.28.2)
pdm.termui:   Adding requirement urllib3<1.27,>=1.21.1(from requests 2.28.2)
pdm.termui:   Adding requirement certifi>=2017.4.17(from requests 2.28.2)
STATUS: Resolving: new pin requests 2.28.2
pdm.termui: Pinning: requests 2.28.2
pdm.termui: ======== Ending round 4 ========
pdm.termui: ======== Starting round 5 ========
STATUS: Resolving: new pin websocket-client 1.5.1
pdm.termui: Pinning: websocket-client 1.5.1
pdm.termui: ======== Ending round 5 ========
pdm.termui: ======== Starting round 6 ========
pdm.termui:   Adding requirement b''(from IxNetwork 9.0.1915.16)
Traceback (most recent call last):
  File "/opt/homebrew/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.4.6/libexec/lib/python3.11/site-packages/pdm/core.py", line 247, in main
    return Core().main(args)
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.4.6/libexec/lib/python3.11/site-packages/pdm/core.py", line 181, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/opt/homebrew/Cellar/pdm/2.4.6/libexec/lib/python3.11/site-packages/pdm/core.py", line 176, in main
    f(project, options)
  File "/opt/homebrew/Cellar/pdm/2.4.6/libexec/lib/python3.11/site-packages/pdm/cli/commands/add.py", line 57, in handle
    actions.do_add(
  File "/opt/homebrew/Cellar/pdm/2.4.6/libexec/lib/python3.11/site-packages/pdm/cli/actions.py", line 271, in do_add
    resolved = do_lock(project, strategy, tracked_names, reqs, dry_run=dry_run, hooks=hooks)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.4.6/libexec/lib/python3.11/site-packages/pdm/cli/actions.py", line 94, in do_lock
    mapping, dependencies = resolve(
                            ^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.4.6/libexec/lib/python3.11/site-packages/pdm/resolver/core.py", line 35, in resolve
    result = resolver.resolve(requirements, max_rounds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.4.6/libexec/lib/python3.11/site-packages/resolvelib/resolvers.py", line 521, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.4.6/libexec/lib/python3.11/site-packages/resolvelib/resolvers.py", line 402, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.4.6/libexec/lib/python3.11/site-packages/resolvelib/resolvers.py", line 238, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.4.6/libexec/lib/python3.11/site-packages/resolvelib/resolvers.py", line 229, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "/opt/homebrew/Cellar/pdm/2.4.6/libexec/lib/python3.11/site-packages/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/opt/homebrew/Cellar/pdm/2.4.6/libexec/lib/python3.11/site-packages/resolvelib/structs.py", line 127, in __bool__
    next(iter(self))
  File "/opt/homebrew/Cellar/pdm/2.4.6/libexec/lib/python3.11/site-packages/pdm/resolver/providers.py", line 240, in matches_gen
    yield from super_find()
               ^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.4.6/libexec/lib/python3.11/site-packages/pdm/resolver/providers.py", line 138, in matches_gen
    candidates = self._find_candidates(reqs[0])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.4.6/libexec/lib/python3.11/site-packages/pdm/resolver/providers.py", line 117, in _find_candidates
    can = make_candidate(requirement)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.4.6/libexec/lib/python3.11/site-packages/pdm/models/candidates.py", line 592, in make_candidate
    return Candidate(req, name, version, link)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.4.6/libexec/lib/python3.11/site-packages/pdm/models/candidates.py", line 147, in __init__
    link = req.as_file_link()  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.4.6/libexec/lib/python3.11/site-packages/pdm/models/requirements.py", line 318, in as_file_link
    return Link(url)
           ^^^^^^^^^
  File "<string>", line 9, in __init__
  File "/opt/homebrew/Cellar/pdm/2.4.6/libexec/lib/python3.11/site-packages/unearth/link.py", line 54, in __post_init__
    if self.url.startswith(vcs_prefixes):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: a bytes-like object is required, not 'str'
```

## Expected behavior

Successful installation.

## Environment Information

```bash
PDM version:
  2.4.6
Python Interpreter:
  /opt/homebrew/opt/python@3.11/bin/python3.11 (3.11)
Project Root:
  /Users/xxxxxx/code/test
Project Packages:
  /Users/xxxxxx/code/test/__pypackages__/3.11
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.2",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "22.3.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000",
  "python_full_version": "3.11.2",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "darwin"
}
```

**Comment by bland328** [comment]
Using `pdm  2.4.6`, I'm also running into this, but under Slackware instead of macOS.

**Comment by frostming** [comment]
It is caused by a malformed requirement string: https://github.com/ixiacom/ixnetwork-api-py/blob/2ed71d52dd210a2d08250256c3b198a9c7c67dca/setup.py#L44-L45

Not PDM's bug

**Comment by olbitset** [comment]
Thanks and I noticed that there is an PR for this: https://github.com/ixiacom/ixnetwork-api-py/pull/5

**Comment by petre-renware** [comment]
yes, indeed. The most probably in `pyproject.toml` file in any dependencies key/entry, there is a comma (`,`) after last element, comma that must be removed as in Python looping in a list and after ok ast e ok element is a comma, the for loop will find an empty (that `b''`) element after last intended one...

**Comment by pawamoy** [comment]
I don't think that's true, TOML supports trailing commas, just like Python.
