### ISSUE TITLE
`pdm run --list` raises `AttributeError: 'str' object has no attribute 'value'`

### ISSUE THREAD

**Issue by Xdynix** [pdm-project/pdm#1783]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Setup PDM:

```bash
mkdir test
cd test
pdm init
# Answer the questions.
```

Add the following script definitation to `pyproject.toml`. Referring to the document [here](https://pdm.fming.dev/latest/usage/scripts/#cmd:~:text=specify%20the%20command%20as%20an%20array%20instead%20of%20a%20string).

```toml
[tool.pdm.scripts]
pip-ver = { cmd = ["pip", "--version"], help = "print pip version" }
```

And execute `pdm run -v --list`.

## Actual behavior

The following error message is given:

```bash
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Me\.local\bin\pdm.exe\__main__.py", line 7, in <module>
  File "C:\Users\Me\.local\pipx\venvs\pdm\Lib\site-packages\pdm\core.py", line 247, in main
    return Core().main(args)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Me\.local\pipx\venvs\pdm\Lib\site-packages\pdm\core.py", line 181, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "C:\Users\Me\.local\pipx\venvs\pdm\Lib\site-packages\pdm\core.py", line 176, in main
    f(project, options)
  File "C:\Users\Me\.local\pipx\venvs\pdm\Lib\site-packages\pdm\cli\commands\run.py", line 346, in handle
    return runner.show_list()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Me\.local\pipx\venvs\pdm\Lib\site-packages\pdm\cli\commands\run.py", line 309, in show_list
    task.short_description,
    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Me\.local\pipx\venvs\pdm\Lib\site-packages\pdm\cli\commands\run.py", line 74, in short_description
    lines = [line.strip() for line in str(self.args).splitlines() if line.strip()]
                                      ^^^^^^^^^^^^^^
  File "C:\Users\Me\.local\pipx\venvs\pdm\Lib\site-packages\tomlkit\items.py", line 1415, in __str__
    return str([v.value.value for v in self._iter_items() if v.value is not None])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Me\.local\pipx\venvs\pdm\Lib\site-packages\tomlkit\items.py", line 1415, in <listcomp>
    return str([v.value.value for v in self._iter_items() if v.value is not None])
                ^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'value'
```

## Expected behavior

It should print a table like:

```bash
╭─────────┬──────┬───────────────────╮
│ Name    │ Type │ Description       │
├─────────┼──────┼───────────────────┤
│ pip-ver │ cmd  │ print pip version │
╰─────────┴──────┴───────────────────╯
```

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.4.9
Python Interpreter:
  C:\Python311\python.EXE (3.11)
Project Root:
  D:/test
Project Packages:
  D:\test\__pypackages__\3.11
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.2",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19045",
  "python_full_version": "3.11.2",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "win32"
}
```

---

I know it will work fine if I write the command as a string (`cmd = "pip --version"`). But for long commands, it is more readable to write them as an array with newlines and comments added.

**Comment by frostming** [comment]
This is an issue in `tomlkit` and should be fixed in the next release: https://github.com/sdispater/tomlkit/pull/277
