### ISSUE TITLE
pdm cannot install asyncmy

### ISSUE THREAD

**Issue by RicarTang** [pdm-project/pdm#1818]
- [ ] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce
```
PS E:\pdm_test> pdm add asyncmy
Adding packages to default dependencies: asyncmy
🔒 Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
Synchronizing working set with lock file: 1 to add, 0 to update, 0 to remove

  ✖ Install asyncmy 0.2.7 failed
Retry failed jobs
  ✖ Install asyncmy 0.2.7 failed

ERRORS:
add asyncmy failed:
Traceback (most recent call last):
  File "C:\Users\BFChainer\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\BFChainer\AppData\Local\Programs\Python\Python310\lib\site-packages\pdm\installers\synchronizers.py",
line 233, in install_candidate
    self.manager.install(can)
  File "C:\Users\BFChainer\AppData\Local\Programs\Python\Python310\lib\site-packages\pdm\installers\manager.py", line
33, in install
    installer(str(prepared.build()), self.environment, prepared.direct_url())
  File "C:\Users\BFChainer\AppData\Local\Programs\Python\Python310\lib\site-packages\pdm\installers\installers.py", line
170, in install_wheel
    _install_wheel(wheel=wheel, destination=destination, additional_metadata=additional_metadata)
  File "C:\Users\BFChainer\AppData\Local\Programs\Python\Python310\lib\site-packages\pdm\installers\installers.py", line
254, in _install_wheel
    install(source, destination, additional_metadata=additional_metadata or {})
  File "C:\Users\BFChainer\AppData\Local\Programs\Python\Python310\lib\site-packages\installer\_core.py", line 96, in
install
    for record_elements, stream, is_executable in source.get_contents():
  File "C:\Users\BFChainer\AppData\Local\Programs\Python\Python310\lib\site-packages\pdm\installers\installers.py", line
126, in get_contents
    for element in super().get_contents():
  File "C:\Users\BFChainer\AppData\Local\Programs\Python\Python310\lib\site-packages\installer\sources.py", line 158, in
get_contents
    assert record is not None, "In {}, {} is not mentioned in RECORD".format(
AssertionError: In C:\Users\BFCHAI~1\AppData\Local\Temp\pdm-build-jmgq55ka\asyncmy-0.2.7-cp310-cp310-win_amd64.whl,
asyncmy/__init__.py is not mentioned in RECORD

See C:\Users\BFCHAI~1\AppData\Local\Temp\pdm-install-_rq9pu1h.log for detailed debug log.
[InstallationError]: Some package operations are not complete yet
Add '-v' to see the detailed traceback
```

## Environment Information
```
PS E:\pdm_test> pdm info --env
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.3",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.18363",
  "python_full_version": "3.10.3",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "win32"
}

PDM 2.4.9 is installed, while 2.5.0b0 is available.
Please run `pdm self update` to upgrade.
Run `pdm config check_update false` to disable the check.
```
```bash
# Paste the output of `pdm info && pdm info --env` below:

```

**Comment by frostming** [comment]
Upgrade to the latest prerelease `2.5.0b0` please

**Comment by RicarTang** [comment]
> Upgrade to the latest prerelease `2.5.0b0` please
I don't know how to update it, pdm self update failed, and I see the latest version of pypi.org is 2.4.9

**Comment by frostming** [comment]
> pdm self update failed

`pdm self update --pre` and paste the error if it fails. It seems you installed with the global pip, then `python -m pip install -U --pre pdm` would work.



> I see the latest version of pypi.org is 2.4.9

The prerelease versions won't be shown on the default page, view them in the "Releases" tab.

**Comment by RicarTang** [comment]
@frostming Ok, I directly used python -m pip install pdm==2.5.0b0 to successfully install

**Comment by RicarTang** [comment]
@frostming Thank you. It was successfully upgraded

**Comment by KingMichaelPark** [comment]
This still happens on 2.5.3 for me does it for you @RicarTang?
