### ISSUE TITLE
Regression: updating shebang in binary files

### ISSUE THREAD

**Issue by pawamoy** [pdm-project/pdm#1827]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Issue

PR https://github.com/pdm-project/pdm/pull/1710 was overwritten by commit https://github.com/pdm-project/pdm/commit/146daa2fb13630ee9108f9b17642824cfa6ee237.

## Actual behavior

```python
% pdm use -f python3.9 -v 
Using the last selection, add '-i' to ignore it.
Using Python interpreter: /home/pawamoy/.basher-packages/pyenv/pyenv/shims/python3.9 (3.9)
Using __pypackages__ because non-venv Python is used.
Updating executable scripts...
Traceback (most recent call last):
  File "/home/pawamoy/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 255, in main
    return Core().main(args)
           ^^^^^^^^^^^^^^^^^
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 193, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 188, in main
    self.handle(project, options)
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 154, in handle
    command.handle(project, options)
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/cli/commands/use.py", line 31, in handle
    actions.do_use(
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/cli/actions.py", line 666, in do_use
    project.environment.update_shebangs(selected_python.executable.as_posix())
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/environments/local.py", line 94, in update_shebangs
    child.write_bytes(_replace_shebang(child.read_bytes(), new_shebang))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/environments/local.py", line 45, in _replace_shebang
    assert match is not None
AssertionError
```

## Expected behavior

No error.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.5.1
Python Interpreter:
  /home/pawamoy/.basher-packages/pyenv/pyenv/versions/3.9.15/bin/python3.9 (3.9)
Project Root:
  /media/data/dev/griffe
Local Packages:
  /media/data/dev/griffe/__pypackages__/3.9
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.15",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.2.10-arch1-1",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT_DYNAMIC Fri, 07 Apr 2023 02:10:43 +0000",
  "python_full_version": "3.9.15",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

**Comment by pawamoy** [comment]
Thanks @frostming :slightly_smiling_face:
