### ISSUE TITLE
Self-referential dependencies cause a TypeError

### ISSUE THREAD

**Issue by hynek** [pdm-project/pdm#1830]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

So I'm not sure if the PDM has this feature, but either way it shouldn't crash with a `TypeError: a bytes-like object is required, not 'str'`.

I wanted to play with the new `--venv` feature and tried the following:

```toml
[tool.pdm.dev-dependencies]
tests = [
    "coverage",
    "pytest-deadfixtures",
    "pytest-icdiff",
    "pytest",
    "webtest",
]
dev = [
    ".[tests]",
    "ruff",
    # ...
]
```

## Actual behavior

<details>

```
pdm.termui:   Adding requirement pw-reset[tests] @ b''
Traceback (most recent call last):
  File "/Users/hynek/.local/bin-intel/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/hynek/.local/pipx-intel/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 255, in main
    return Core().main(args)
           ^^^^^^^^^^^^^^^^^
  File "/Users/hynek/.local/pipx-intel/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 193, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/Users/hynek/.local/pipx-intel/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 188, in main
    self.handle(project, options)
  File "/Users/hynek/.local/pipx-intel/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 154, in handle
    command.handle(project, options)
  File "/Users/hynek/.local/pipx-intel/venvs/pdm/lib/python3.11/site-packages/pdm/cli/commands/update.py", line 62, in handle
    actions.do_update(
  File "/Users/hynek/.local/pipx-intel/venvs/pdm/lib/python3.11/site-packages/pdm/cli/actions.py", line 377, in do_update
    resolved = do_lock(
               ^^^^^^^^
  File "/Users/hynek/.local/pipx-intel/venvs/pdm/lib/python3.11/site-packages/pdm/cli/actions.py", line 98, in do_lock
    mapping, dependencies = resolve(
                            ^^^^^^^^
  File "/Users/hynek/.local/pipx-intel/venvs/pdm/lib/python3.11/site-packages/pdm/resolver/core.py", line 35, in resolve
    result = resolver.resolve(requirements, max_rounds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hynek/.local/pipx-intel/venvs/pdm/lib/python3.11/site-packages/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hynek/.local/pipx-intel/venvs/pdm/lib/python3.11/site-packages/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/Users/hynek/.local/pipx-intel/venvs/pdm/lib/python3.11/site-packages/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "/Users/hynek/.local/pipx-intel/venvs/pdm/lib/python3.11/site-packages/resolvelib/structs.py", line 127, in __bool__
    next(iter(self))
         ^^^^^^^^^^
  File "/Users/hynek/.local/pipx-intel/venvs/pdm/lib/python3.11/site-packages/resolvelib/structs.py", line 136, in __iter__
    self._factory() if self._iterable is None else self._iterable
    ^^^^^^^^^^^^^^^
  File "/Users/hynek/.local/pipx-intel/venvs/pdm/lib/python3.11/site-packages/pdm/resolver/providers.py", line 139, in matches_gen
    candidates = self._find_candidates(reqs[0])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hynek/.local/pipx-intel/venvs/pdm/lib/python3.11/site-packages/pdm/resolver/providers.py", line 118, in _find_candidates
    can = make_candidate(requirement)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hynek/.local/pipx-intel/venvs/pdm/lib/python3.11/site-packages/pdm/models/candidates.py", line 592, in make_candidate
    return Candidate(req, name, version, link)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hynek/.local/pipx-intel/venvs/pdm/lib/python3.11/site-packages/pdm/models/candidates.py", line 147, in __init__
    link = cast(Link, req.as_file_link())  # type: ignore[attr-defined]
                      ^^^^^^^^^^^^^^^^^^
  File "/Users/hynek/.local/pipx-intel/venvs/pdm/lib/python3.11/site-packages/pdm/models/requirements.py", line 318, in as_file_link
    return Link(url)
           ^^^^^^^^^
  File "<string>", line 9, in __init__
  File "/Users/hynek/.local/pipx-intel/venvs/pdm/lib/python3.11/site-packages/unearth/link.py", line 54, in __post_init__
    if self.url.startswith(vcs_prefixes):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: a bytes-like object is required, not 'str'
```

</details>

## Expected behavior

Either:

1. an error telling me that self-referential dependencies aren't supported yet
2. or no error and `dev` becoming `tests + ["ruff"]`

Obviously, I would prefer 2. 😇

## Environment Information

```console
❯ pdm info
PDM version:
  2.5.2
Python Interpreter:
  /Users/hynek/Work/pw-reset/.venv/bin/python (3.11)
Project Root:
  /Users/hynek/Work/pw-reset
Local Packages:
❯ pdm info --env
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.3",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "22.4.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:58 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6020",
  "python_full_version": "3.11.3",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
The requirements are parsed as PEP 508 strings, so `.[tests]` isn't a valid specification. Reference self with the project name please: `<project_name>[tests]`.

**Comment by frostming** [comment]
> Would it be realistic to make that work too?

I don't think it's necessary, because it is no more effort than adding a `-G test` option when testing.
