### ISSUE TITLE
2.5.2: test_build_distributions fails

### ISSUE THREAD

**Issue by dvzrv** [pdm-project/pdm#1831]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Hi! When trying to package 2.5.2 for Arch Linux I run into a failing test (`test_build_distributions`).
The pdm-backend package is devendored (see https://github.com/pdm-project/pdm-backend/issues/163) which seems largely unproblematic (see https://github.com/pdm-project/pdm-backend/issues/164).

I build and try to test as follows:

```
python -m build --wheel --no-isolation
local site_packages=$(python -c "import site; print(site.getsitepackages()[0])")
python -m installer --destdir=test_dir dist/*.whl
export PYTHONPATH="test_dir/$site_packages:$PYTHONPATH"
pytest -vv
```

## Actual behavior

Judging from the log output, this seems to have overlap with https://github.com/pdm-project/pdm-backend/issues/163.

```
=================================== FAILURES ===================================
___________________________ test_build_distributions ___________________________

tmp_path = PosixPath('/tmp/pytest-of-builduser/pytest-0/test_build_distributions0')
core = <pdm.core.Core object at 0x7faec6144370>

    @pytest.mark.usefixtures("project_no_init", "local_finder")
    def test_build_distributions(tmp_path, core):
        project = core.create_project()
>       actions.do_build(project, dest=tmp_path.as_posix())

tests/cli/test_others.py:14:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
test_dir/usr/lib/python3.10/site-packages/pdm/cli/actions.py:493: in do_build
    loc = SdistBuilder(project.root, project.environment).build(dest, config_settings)
test_dir/usr/lib/python3.10/site-packages/pdm/builders/sdist.py:21: in build
    filename = self._hook.build_sdist(out_dir, config_settings)
/usr/lib/python3.10/site-packages/pyproject_hooks/_impl.py:292: in build_sdist
    return self._call_hook('build_sdist', {
/usr/lib/python3.10/site-packages/pyproject_hooks/_impl.py:311: in _call_hook
    self._subprocess_runner(
test_dir/usr/lib/python3.10/site-packages/pdm/builders/base.py:257: in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cmd = ['/usr/bin/python', '/usr/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py', 'build_sdist', '/tmp/tmp5cclt4bg']
cwd = '/build/python-pdm/src/pdm-2.5.2'
extra_environ = {'PATH': '/tmp/pdm-build-env-tahhmfcn-overlay/bin:/tmp/pytest-of-builduser/pytest-0/pdm-test-env0/bin:/usr/local/sbin:....10/site-packages:/build/python-pdm/src/pdm-2.5.2/__pypackages__/3.10/lib:test_dir//usr/lib/python3.10/site-packages:'}

    def log_subprocessor(
        cmd: list[str],
        cwd: str | Path | None = None,
        extra_environ: dict[str, str] | None = None,
    ) -> None:
        env = os.environ.copy()
        if extra_environ:
            env.update(extra_environ)
        outstream = LoggerWrapper(logger, logging.INFO)
        try:
            subprocess.check_call(
                cmd,
                cwd=cwd,
                env=env,
                stdout=outstream.fileno(),
                stderr=subprocess.STDOUT,
            )
        except subprocess.CalledProcessError as e:
            e.output = outstream._output_buffer
>           raise build_error(e) from None
E           pdm.exceptions.BuildError: Build backend raised error: Showing the last 10 lines of the build output:
E               self.generate_func_code_block(definition_item, self._variable, self._variable_name, clear_variables=True)
E             File "/tmp/pytest-of-builduser/pytest-0/pdm-test-env0/lib/python3.10/site-packages/pdm/backend/_vendor/validate_pyproject/_vendor/fastjsonschema/generator.py", line 155, in generate_func_code_block
E               count = self._generate_func_code_block(definition)
E             File "/tmp/pytest-of-builduser/pytest-0/pdm-test-env0/lib/python3.10/site-packages/pdm/backend/_vendor/validate_pyproject/_vendor/fastjsonschema/draft06.py", line 35, in _generate_func_code_block
E               self.run_generate_functions(definition)
E             File "/tmp/pytest-of-builduser/pytest-0/pdm-test-env0/lib/python3.10/site-packages/pdm/backend/_vendor/validate_pyproject/_vendor/fastjsonschema/generator.py", line 177, in run_generate_functions
E               func()
E             File "/tmp/pytest-of-builduser/pytest-0/pdm-test-env0/lib/python3.10/site-packages/pdm/backend/_vendor/validate_pyproject/_vendor/fastjsonschema/draft04.py", line 277, in generate_format
E               raise JsonSchemaDefinitionException('Unknown format: {}'.format(format_))
E           pdm.backend._vendor.validate_pyproject._vendor.fastjsonschema.exceptions.JsonSchemaDefinitionException: Unknown format: pep561-stub-name

test_dir/usr/lib/python3.10/site-packages/pdm/builders/base.py:107: BuildError
---------------------------- Captured stdout setup -----------------------------
Changes are written to pyproject.toml.
----------------------------- Captured stdout call -----------------------------
Building sdist...
----------------------------- Captured stderr call -----------------------------
See /tmp/pdm-build-zu6nsa2g.log for detailed debug log.
------------------------------ Captured log call -------------------------------
INFO     pdm.termui:base.py:188 Preparing isolated env for PEP 517 build...
INFO     pdm.termui:base.py:60 Traceback (most recent call last):
INFO     pdm.termui:base.py:60   File "/usr/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
INFO     pdm.termui:base.py:60     main()
INFO     pdm.termui:base.py:60   File "/usr/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
INFO     pdm.termui:base.py:60     json_out['return_val'] = hook(**hook_input['kwargs'])
INFO     pdm.termui:base.py:60   File "/usr/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 304, in build_sdist
INFO     pdm.termui:base.py:60     return backend.build_sdist(sdist_directory, config_settings)
INFO     pdm.termui:base.py:60   File "/tmp/pytest-of-builduser/pytest-0/pdm-test-env0/lib/python3.10/site-packages/pdm/backend/__init__.py", line 65, in build_sdist
INFO     pdm.termui:base.py:60     with SdistBuilder(Path.cwd(), config_settings) as builder:
INFO     pdm.termui:base.py:60   File "/tmp/pytest-of-builduser/pytest-0/pdm-test-env0/lib/python3.10/site-packages/pdm/backend/base.py", line 99, in __init__
INFO     pdm.termui:base.py:60     self.config = Config.from_pyproject(self.location)
INFO     pdm.termui:base.py:60   File "/tmp/pytest-of-builduser/pytest-0/pdm-test-env0/lib/python3.10/site-packages/pdm/backend/config.py", line 70, in from_pyproject
INFO     pdm.termui:base.py:60     return cls(root, data)
INFO     pdm.termui:base.py:60   File "/tmp/pytest-of-builduser/pytest-0/pdm-test-env0/lib/python3.10/site-packages/pdm/backend/config.py", line 37, in __init__
INFO     pdm.termui:base.py:60     self.validate(data)
INFO     pdm.termui:base.py:60   File "/tmp/pytest-of-builduser/pytest-0/pdm-test-env0/lib/python3.10/site-packages/pdm/backend/config.py", line 54, in validate
INFO     pdm.termui:base.py:60     validator(data)
INFO     pdm.termui:base.py:60   File "/tmp/pytest-of-builduser/pytest-0/pdm-test-env0/lib/python3.10/site-packages/pdm/backend/_vendor/validate_pyproject/api.py", line 244, in __call__
INFO     pdm.termui:base.py:60     compiled = FJS.compile(self.schema, self.handlers, dict(self.formats))
INFO     pdm.termui:base.py:60   File "/tmp/pytest-of-builduser/pytest-0/pdm-test-env0/lib/python3.10/site-packages/pdm/backend/_vendor/validate_pyproject/_vendor/fastjsonschema/__init__.py", line 178, in compile
INFO     pdm.termui:base.py:60     global_state = code_generator.global_state
INFO     pdm.termui:base.py:60   File "/tmp/pytest-of-builduser/pytest-0/pdm-test-env0/lib/python3.10/site-packages/pdm/backend/_vendor/validate_pyproject/_vendor/fastjsonschema/draft04.py", line 72, in global_state
INFO     pdm.termui:base.py:60     res = super().global_state
INFO     pdm.termui:base.py:60   File "/tmp/pytest-of-builduser/pytest-0/pdm-test-env0/lib/python3.10/site-packages/pdm/backend/_vendor/validate_pyproject/_vendor/fastjsonschema/generator.py", line 81, in global_state
INFO     pdm.termui:base.py:60     self._generate_func_code()
INFO     pdm.termui:base.py:60   File "/tmp/pytest-of-builduser/pytest-0/pdm-test-env0/lib/python3.10/site-packages/pdm/backend/_vendor/validate_pyproject/_vendor/fastjsonschema/generator.py", line 116, in _generate_func_code
INFO     pdm.termui:base.py:60     self.generate_func_code()
INFO     pdm.termui:base.py:60   File "/tmp/pytest-of-builduser/pytest-0/pdm-test-env0/lib/python3.10/site-packages/pdm/backend/_vendor/validate_pyproject/_vendor/fastjsonschema/generator.py", line 130, in generate_func_code
INFO     pdm.termui:base.py:60     self.generate_validation_function(uri, name)
INFO     pdm.termui:base.py:60   File "/tmp/pytest-of-builduser/pytest-0/pdm-test-env0/lib/python3.10/site-packages/pdm/backend/_vendor/validate_pyproject/_vendor/fastjsonschema/generator.py", line 140, in generate_validation_function
INFO     pdm.termui:base.py:60     self.generate_func_code_block(definition, 'data', 'data', clear_variables=True)
INFO     pdm.termui:base.py:60   File "/tmp/pytest-of-builduser/pytest-0/pdm-test-env0/lib/python3.10/site-packages/pdm/backend/_vendor/validate_pyproject/_vendor/fastjsonschema/generator.py", line 155, in generate_func_code_block
INFO     pdm.termui:base.py:60     count = self._generate_func_code_block(definition)
INFO     pdm.termui:base.py:60   File "/tmp/pytest-of-builduser/pytest-0/pdm-test-env0/lib/python3.10/site-packages/pdm/backend/_vendor/validate_pyproject/_vendor/fastjsonschema/draft06.py", line 35, in _generate_func_code_block
INFO     pdm.termui:base.py:60     self.run_generate_functions(definition)
INFO     pdm.termui:base.py:60   File "/tmp/pytest-of-builduser/pytest-0/pdm-test-env0/lib/python3.10/site-packages/pdm/backend/_vendor/validate_pyproject/_vendor/fastjsonschema/generator.py", line 177, in run_generate_functions
INFO     pdm.termui:base.py:60     func()
INFO     pdm.termui:base.py:60   File "/tmp/pytest-of-builduser/pytest-0/pdm-test-env0/lib/python3.10/site-packages/pdm/backend/_vendor/validate_pyproject/_vendor/fastjsonschema/draft04.py", line 156, in generate_any_of
INFO     pdm.termui:base.py:60     self.generate_func_code_block(definition_item, self._variable, self._variable_name, clear_variables=True)
INFO     pdm.termui:base.py:60   File "/tmp/pytest-of-builduser/pytest-0/pdm-test-env0/lib/python3.10/site-packages/pdm/backend/_vendor/validate_pyproject/_vendor/fastjsonschema/generator.py", line 155, in generate_func_code_block
INFO     pdm.termui:base.py:60     count = self._generate_func_code_block(definition)
INFO     pdm.termui:base.py:60   File "/tmp/pytest-of-builduser/pytest-0/pdm-test-env0/lib/python3.10/site-packages/pdm/backend/_vendor/validate_pyproject/_vendor/fastjsonschema/draft06.py", line 35, in _generate_func_code_block
INFO     pdm.termui:base.py:60     self.run_generate_functions(definition)
INFO     pdm.termui:base.py:60   File "/tmp/pytest-of-builduser/pytest-0/pdm-test-env0/lib/python3.10/site-packages/pdm/backend/_vendor/validate_pyproject/_vendor/fastjsonschema/generator.py", line 177, in run_generate_functions
INFO     pdm.termui:base.py:60     func()
INFO     pdm.termui:base.py:60   File "/tmp/pytest-of-builduser/pytest-0/pdm-test-env0/lib/python3.10/site-packages/pdm/backend/_vendor/validate_pyproject/_vendor/fastjsonschema/draft04.py", line 277, in generate_format
INFO     pdm.termui:base.py:60     raise JsonSchemaDefinitionException('Unknown format: {}'.format(format_))
INFO     pdm.termui:base.py:60 pdm.backend._vendor.validate_pyproject._vendor.fastjsonschema.exceptions.JsonSchemaDefinitionException: Unknown format: pep561-stub-name
ERROR    pdm.termui:termui.py:239 Error occurs
Traceback (most recent call last):
  File "/build/python-pdm/src/pdm-2.5.2/test_dir/usr/lib/python3.10/site-packages/pdm/termui.py", line 236, in logging
    yield logger
  File "/build/python-pdm/src/pdm-2.5.2/test_dir/usr/lib/python3.10/site-packages/pdm/cli/actions.py", line 493, in do_build
    loc = SdistBuilder(project.root, project.environment).build(dest, config_settings)
  File "/build/python-pdm/src/pdm-2.5.2/test_dir/usr/lib/python3.10/site-packages/pdm/builders/sdist.py", line 21, in build
    filename = self._hook.build_sdist(out_dir, config_settings)
  File "/usr/lib/python3.10/site-packages/pyproject_hooks/_impl.py", line 292, in build_sdist
    return self._call_hook('build_sdist', {
  File "/usr/lib/python3.10/site-packages/pyproject_hooks/_impl.py", line 311, in _call_hook
    self._subprocess_runner(
  File "/build/python-pdm/src/pdm-2.5.2/test_dir/usr/lib/python3.10/site-packages/pdm/builders/base.py", line 257, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
  File "/build/python-pdm/src/pdm-2.5.2/test_dir/usr/lib/python3.10/site-packages/pdm/builders/base.py", line 107, in log_subprocessor
    raise build_error(e) from None
pdm.exceptions.BuildError: Build backend raised error: Showing the last 10 lines of the build output:
    self.generate_func_code_block(definition_item, self._variable, self._variable_name, clear_variables=True)
  File "/tmp/pytest-of-builduser/pytest-0/pdm-test-env0/lib/python3.10/site-packages/pdm/backend/_vendor/validate_pyproject/_vendor/fastjsonschema/generator.py", line 155, in generate_func_code_block
    count = self._generate_func_code_block(definition)
  File "/tmp/pytest-of-builduser/pytest-0/pdm-test-env0/lib/python3.10/site-packages/pdm/backend/_vendor/validate_pyproject/_vendor/fastjsonschema/draft06.py", line 35, in _generate_func_code_block
    self.run_generate_functions(definition)
  File "/tmp/pytest-of-builduser/pytest-0/pdm-test-env0/lib/python3.10/site-packages/pdm/backend/_vendor/validate_pyproject/_vendor/fastjsonschema/generator.py", line 177, in run_generate_functions
    func()
  File "/tmp/pytest-of-builduser/pytest-0/pdm-test-env0/lib/python3.10/site-packages/pdm/backend/_vendor/validate_pyproject/_vendor/fastjsonschema/draft04.py", line 277, in generate_format
    raise JsonSchemaDefinitionException('Unknown format: {}'.format(format_))
pdm.backend._vendor.validate_pyproject._vendor.fastjsonschema.exceptions.JsonSchemaDefinitionException: Unknown format: pep561-stub-name
=============================== warnings summary ===============================
tests/test_integration.py:25
  /build/python-pdm/src/pdm-2.5.2/tests/test_integration.py:25: PytestUnknownMarkWarning: Unknown pytest.mark.flaky - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    @pytest.mark.flaky(reruns=3)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
XFAIL tests/models/test_candidates.py::test_parse_abnormal_specifiers - packaging 22 no longer supports legacy specifiers
FAILED tests/cli/test_others.py::test_build_distributions - pdm.exceptions.BuildError: Build backend raised error: Showing the last 10 lines of the build output:
    self.generate_func_code_block(definition_item, self._variable, self._variable_name, clear_variables=True)
  File "/tmp/pytest-of-builduser/pytest-0/pdm-test-env0/lib/python3.10/site-packages/pdm/backend/_vendor/validate_pyproject/_vendor/fastjsonschema/generator.py", line 155, in generate_func_code_block
    count = self._generate_func_code_block(definition)
  File "/tmp/pytest-of-builduser/pytest-0/pdm-test-env0/lib/python3.10/site-packages/pdm/backend/_vendor/validate_pyproject/_vendor/fastjsonschema/draft06.py", line 35, in _generate_func_code_block
    self.run_generate_functions(definition)
  File "/tmp/pytest-of-builduser/pytest-0/pdm-test-env0/lib/python3.10/site-packages/pdm/backend/_vendor/validate_pyproject/_vendor/fastjsonschema/generator.py", line 177, in run_generate_functions
    func()
  File "/tmp/pytest-of-builduser/pytest-0/pdm-test-env0/lib/python3.10/site-packages/pdm/backend/_vendor/validate_pyproject/_vendor/fastjsonschema/draft04.py", line 277, in generate_format
    raise JsonSchemaDefinitionException('Unknown format: {}'.format(format_))
pdm.backend._vendor.validate_pyproject._vendor.fastjsonschema.exceptions.JsonSchemaDefinitionException: Unknown format: pep561-stub-name
======= 1 failed, 649 passed, 1 xfailed, 1 warning in 143.50s (0:02:23) ========
```

[python-pdm-2.5.2-1-x86_64-build.log](https://github.com/pdm-project/pdm/files/11203806/python-pdm-2.5.2-1-x86_64-build.log)
[python-pdm-2.5.2-1-x86_64-check.log](https://github.com/pdm-project/pdm/files/11203807/python-pdm-2.5.2-1-x86_64-check.log)

## Expected behavior

All tests pass.

## Environment Information

n/a

**Comment by dvzrv** [comment]
@frostming can you please elaborate on why this is closed as "not planned" and what the suggested fix/ context is?

Providing useful bug reports with logs and background info takes considerable amounts of time which stands in stark contrast to just closing the ticket without any comment.
(currently I can't test whether this test still fails and needs to be ignored still as it also suffers from #2107)

**Comment by dvzrv** [comment]
Anyways, with 2.8.1 this issue is definitely gone.
