### ISSUE TITLE
Plugin API change in 2.5: command has to have `name` attribute

### ISSUE THREAD

**Issue by tgolsson** [pdm-project/pdm#1843]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

I know it's not "in the guide" but it looks like there was an undocumented breaking change in the plugin API between 2.5 beta and release. Probably unintentional, too. The torch plugin uses subcommands, and the command "value" used to be a string but now it's required to be a thing having a "name". I've solved it like below in order to be compatible with both 2.3, 2.4 and 2.5. Both the first behave the same way.

Here's the diff I did it using classes for it:
https://github.com/EmbarkStudios/pdm-plugin-torch/commit/94fde8b9089dc11a88c4e6a93b0b22df93de5924
Otherwise it fails with
```
Traceback (most recent call last):
  File "/home/ts/.local/bin/pdm25", line 8, in <module>
    sys.exit(main())
  File "/home/ts/.local/pipx/venvs/pdm25/lib/python3.10/site-packages/pdm/core.py", line 269, in main
    return Core().main(args)
  File "/home/ts/.local/pipx/venvs/pdm25/lib/python3.10/site-packages/pdm/core.py", line 203, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/home/ts/.local/pipx/venvs/pdm25/lib/python3.10/site-packages/pdm/core.py", line 198, in main
    self.handle(project, options)
  File "/home/ts/.local/pipx/venvs/pdm25/lib/python3.10/site-packages/pdm/core.py", line 147, in handle
    "pre_invoke", command=command.name if command else None, options=options
AttributeError: 'str' object has no attribute 'name'
```

I don't think this is the intended workflow; but it was the *easiest* solution. If I use the main command there; then `options.command` is always `torch` and it all falls apart.

## Environment Information

```bash
✦ ❯ pdm25 info && pdm25 info --env
WARNING: The following problems are found in your project:
  project-config: python.path config needs to be moved to .pdm-python and .pdm.toml needs to be renamed to pdm.toml
Run pdm fix to fix all or pdm fix <name> to fix individual problem.
PDM version:
  2.5.3
Python Interpreter:
  /usr/bin/python3.9 (3.9)
Project Root:
  /home/ts/Repositories/pdm-plugin-torch
Local Packages:
  /home/ts/Repositories/pdm-plugin-torch/__pypackages__/3.9
WARNING: The following problems are found in your project:
  project-config: python.path config needs to be moved to .pdm-python and .pdm.toml needs to be renamed to pdm.toml
Run pdm fix to fix all or pdm fix <name> to fix individual problem.
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.16",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.15.90.1-microsoft-standard-WSL2",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Fri Jan 27 02:56:13 UTC 2023",
  "python_full_version": "3.9.16",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
Oh yeah, it is due to the change that `options.command` is reserved for referencing to the command object. However in your previous version `command` will be a string.
