### ISSUE TITLE
can't install airspeed package due to hash mismatch 

### ISSUE THREAD

**Issue by cvgaviao** [pdm-project/pdm#1876]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce
pdm init
pdm add airspeed --save-compatible

I'm using pdm pointing to a pypi proxy repository created by Artifactory. 

## Actual behavior

The add command failed due a hash mismatch error. Also interestingly, the `pip install airspeed` have worked. 

```
C:\Users\cristianoga\git-code\my-python-common>pdm add -v airspeed --save-compatible --venv 
In virtual environment: C:\Users\cristianoga\git-code\my-python-common\.venv
Adding packages to default dependencies: airspeed
STATUS: Resolving dependencies
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   memory-profiler~=0.61
pdm.termui:   airspeed
pdm.termui:   python>=3.9
pdm.termui:   Adding requirement memory-profiler~=0.61
pdm.termui:   Adding requirement airspeed
pdm.termui:   Adding requirement python>=3.9
pdm.termui: ======== Starting round 0 ========
unearth.preparer: Using cached <Link https://artifactory.mycloud.intranatixis.com/artifactory/api/pypi/python-proxy-pypi/packages/packages/b3/23/812b8
ffea500acfa38463c291e85e78f7270e80be9d669fd79055ff2606b/airspeed-0.5.20.tar.gz (from https://artifactory.mycloud.intranatixis.com/artifactory/api/pypi
/python-proxy-pypi/simple/airspeed/)>
Traceback (most recent call last):
  File "C:\Users\cristianoga\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\cristianoga\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\cristianoga\AppData\Local\Programs\Python\Python39\Scripts\pdm.exe\__main__.py", line 7, in <module>
  File "C:\Users\cristianoga\AppData\Local\Programs\Python\Python39\lib\site-packages\pdm\core.py", line 255, in main
    return Core().main(args)
  File "C:\Users\cristianoga\AppData\Local\Programs\Python\Python39\lib\site-packages\pdm\core.py", line 193, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "C:\Users\cristianoga\AppData\Local\Programs\Python\Python39\lib\site-packages\pdm\core.py", line 188, in main
    self.handle(project, options)
  File "C:\Users\cristianoga\AppData\Local\Programs\Python\Python39\lib\site-packages\pdm\core.py", line 154, in handle
    command.handle(project, options)
  File "C:\Users\cristianoga\AppData\Local\Programs\Python\Python39\lib\site-packages\pdm\cli\commands\add.py", line 60, in handle
    actions.do_add(
  File "C:\Users\cristianoga\AppData\Local\Programs\Python\Python39\lib\site-packages\pdm\cli\actions.py", line 280, in do_add
    resolved = do_lock(
  File "C:\Users\cristianoga\AppData\Local\Programs\Python\Python39\lib\site-packages\pdm\cli\actions.py", line 98, in do_lock
    mapping, dependencies = resolve(
  File "C:\Users\cristianoga\AppData\Local\Programs\Python\Python39\lib\site-packages\pdm\resolver\core.py", line 35, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "C:\Users\cristianoga\AppData\Local\Programs\Python\Python39\lib\site-packages\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\cristianoga\AppData\Local\Programs\Python\Python39\lib\site-packages\resolvelib\resolvers.py", line 426, in resolve
    name = min(unsatisfied_names, key=self._get_preference)
  File "C:\Users\cristianoga\AppData\Local\Programs\Python\Python39\lib\site-packages\resolvelib\resolvers.py", line 203, in _get_preference
    return self._p.get_preference(
  File "C:\Users\cristianoga\AppData\Local\Programs\Python\Python39\lib\site-packages\pdm\resolver\providers.py", line 84, in get_preference
    is_backtrack_cause = any(dep.identify() in backtrack_identifiers for dep in self.get_dependencies(candidate))
  File "C:\Users\cristianoga\AppData\Local\Programs\Python\Python39\lib\site-packages\pdm\resolver\providers.py", line 176, in get_dependencies       
    deps, requires_python, _ = self.repository.get_dependencies(candidate)
  File "C:\Users\cristianoga\AppData\Local\Programs\Python\Python39\lib\site-packages\pdm\models\repositories.py", line 82, in get_dependencies       
    requirements, requires_python, summary = getter(candidate)
  File "C:\Users\cristianoga\AppData\Local\Programs\Python\Python39\lib\site-packages\pdm\models\repositories.py", line 41, in wrapper
    result = func(self, candidate)
  File "C:\Users\cristianoga\AppData\Local\Programs\Python\Python39\lib\site-packages\pdm\models\repositories.py", line 213, in _get_dependencies_from
_metadata
    deps = prepared.get_dependencies_from_metadata()
  File "C:\Users\cristianoga\AppData\Local\Programs\Python\Python39\lib\site-packages\pdm\models\candidates.py", line 512, in get_dependencies_from_me
tadata
    self.req.project_name, self.metadata.requires or [], extras  # type: ignore[arg-type]
  File "C:\Users\cristianoga\AppData\Local\Programs\Python\Python39\lib\site-packages\pdm\models\candidates.py", line 498, in metadata
    result = self.prepare_metadata()
  File "C:\Users\cristianoga\AppData\Local\Programs\Python\Python39\lib\site-packages\pdm\models\candidates.py", line 427, in prepare_metadata
    self.obtain(allow_all=True)
  File "C:\Users\cristianoga\AppData\Local\Programs\Python\Python39\lib\site-packages\pdm\models\candidates.py", line 419, in obtain
    result = finder.download_and_unpack(self.link, build_dir, download_dir, hash_options)
  File "C:\Users\cristianoga\AppData\Local\Programs\Python\Python39\lib\site-packages\unearth\finder.py", line 391, in download_and_unpack
    file = unpack_link(
  File "C:\Users\cristianoga\AppData\Local\Programs\Python\Python39\lib\site-packages\unearth\preparer.py", line 315, in unpack_link
    validator.validate()
  File "C:\Users\cristianoga\AppData\Local\Programs\Python\Python39\lib\site-packages\unearth\preparer.py", line 113, in validate
    raise HashMismatchError(self.package_link, self.allowed, gots)
unearth.errors.HashMismatchError: Hash mismatch for https://artifactory.mycloud.intranatixis.com/artifactory/api/pypi/python-proxy-pypi/packages/packa
ges/b3/23/812b8ffea500acfa38463c291e85e78f7270e80be9d669fd79055ff2606b/airspeed-0.5.20.tar.gz:
Expected(sha256): f9d8e1042aaebca9c304b7d14662fbd30a83d7a00cd9a7b7ca5c45c280adf058
  Actual(sha256): fe55166b25f2dd62acc8887a912c47f59f8575e3f64c5452893acbe4db4f30e8

```
## Expected behavior

I expected it be added to my project as normal.

## Environment Information

```bash
C:\Users\cristianoga\git-code\my-python-common>pdm info && pdm info --env
PDM version:
  2.5.3
Python Interpreter:
  C:\Users\cristianoga\git-code\my-python-common\.venv\Scripts\python.EXE (3.9)
Project Root:
  C:/Users/cristianoga/git-code/my-python-common
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.9.13",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19044",
  "python_full_version": "3.9.13",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "win32"
}


```

**Comment by cvgaviao** [comment]
Well, I've tested in my personal machine and I was able to install it. The problem seems to be on the my company's Artifactory proxy :(
