### ISSUE TITLE
ModuleNotFoundError: No module named 'setuptools.build_meta'

### ISSUE THREAD

**Issue by johannesrave** [pdm-project/pdm#1940]
- [+] I have searched the issue tracker and believe that this is not a duplicate.

I'm not actually sure I'm using `pdm` correctly, especially when setting the build-system. In any case I get this error which I haven't been able to resolve. I was able to install the project using `pipenv` in another of my WSL distros.

## Steps to reproduce

```
> git clone git@github.com:oobabooga/text-generation-webui.git
> cd text-generation-webui
```
remove last line from `requirements.txt` because of a parsing error that i wasn't able to solve (throwing out a windows-only-package)
```
> pdm init
> pdm import requirements.txt
```

```
> bat -p pyproject.toml

[project]
name = ""
version = ""
description = ""
authors = [
    {name = ", email = "*"},
]

dependencies = [
    "accelerate==0.19.0", 
    "colorama", 
    "datasets", 
    "flexgen==0.1.7", 
    "gradio-client==0.2.5", 
    "gradio==3.31.0", 
    "markdown", 
    "numpy", 
    "pandas", 
    "Pillow>=9.5.0", 
    "pyyaml", 
    "requests", 
    "rwkv==0.7.3", 
    "safetensors==0.3.1", 
    "sentencepiece", 
    "tqdm", 
    "transformers==4.29.1",
    "git+https://github.com/huggingface/peft",
    "bitsandbytes==0.38.1; platform_system != \"Windows\"", 
    "llama-cpp-python==0.1.50; platform_system != \"Windows\""
]

requires-python = ">=3.11"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
```

create an in-project venv, using a python 3.11.3 interpreter created via `pyenv`
```
> pdm install
```

at some point after running into the error i used `pdm run python -m ensurepip` because i had interpreted the infobox under https://pdm.fming.dev/latest/usage/project/#import-the-project-from-other-package-managers . 

## Actual behavior

```
> pdm install -v
Lock file does not exist
Updating the lock file...
STATUS: Resolving dependencies
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   accelerate==0.19.0
pdm.termui:   colorama
pdm.termui:   datasets
pdm.termui:   flexgen==0.1.7
pdm.termui:   gradio-client==0.2.5
pdm.termui:   gradio==3.31.0
pdm.termui:   markdown
pdm.termui:   numpy
pdm.termui:   pandas
pdm.termui:   Pillow>=9.5.0
pdm.termui:   pyyaml
pdm.termui:   requests
pdm.termui:   rwkv==0.7.3
pdm.termui:   safetensors==0.3.1
pdm.termui:   sentencepiece
pdm.termui:   tqdm
pdm.termui:   git+https://github.com/huggingface/peft
pdm.termui:   transformers==4.29.1
pdm.termui:   bitsandbytes==0.38.1; platform_system != "Windows"
pdm.termui:   llama-cpp-python==0.1.50; platform_system != "Windows"
pdm.termui:   python>=3.11
pdm.termui:   Adding requirement accelerate==0.19.0
pdm.termui:   Adding requirement colorama
pdm.termui:   Adding requirement datasets
pdm.termui:   Adding requirement flexgen==0.1.7
pdm.termui:   Adding requirement gradio-client==0.2.5
pdm.termui:   Adding requirement gradio==3.31.0
pdm.termui:   Adding requirement markdown
pdm.termui:   Adding requirement numpy
pdm.termui:   Adding requirement pandas
pdm.termui:   Adding requirement Pillow>=9.5.0
pdm.termui:   Adding requirement pyyaml
pdm.termui:   Adding requirement requests
pdm.termui:   Adding requirement rwkv==0.7.3
pdm.termui:   Adding requirement safetensors==0.3.1
pdm.termui:   Adding requirement sentencepiece
pdm.termui:   Adding requirement tqdm
pdm.termui:   Adding requirement git+https://github.com/huggingface/peft
unearth.vcs.git: Cloning https://github.com/huggingface/peft to /tmp/pdm-build-4vgw9jwi
unearth.vcs.git: Resolved https://github.com/huggingface/peft to commit 4fd374e80d670781c0d82c96ce94d1215ff23306
pdm.termui: Failed to parse pyproject.toml
pdm.termui: Running PEP 517 backend to get metadata for <Link git+https://github.com/huggingface/peft (from None)>
pdm.termui: Preparing isolated env for PEP 517 build...
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   wheel
pdm.termui:   setuptools>=40.8.0
pdm.termui:   python>=3.11.3,<3.11.4
pdm.termui:   Adding requirement wheel
pdm.termui:   Adding requirement setuptools>=40.8.0
pdm.termui:   Adding requirement python>=3.11.3,<3.11.4
pdm.termui: ======== Starting round 0 ========
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
pdm.termui: Pinning: setuptools 67.7.2
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
pdm.termui: Pinning: wheel 0.40.0
pdm.termui: ======== Ending round 2 ========
pdm.termui: ======== Starting round 3 ========
pdm.termui: ======== Resolution Result ========
pdm.termui: Stable pins:
pdm.termui:       python None
pdm.termui:   setuptools 67.7.2
pdm.termui:        wheel 0.40.0
pdm.termui: Installing setuptools@67.7.2...
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/2f/8c/f336a966d4097c7cef6fc699b2ecb83b5fb63fd698198c1b5c7905a74f0f/setuptools-67.7.2-py3-none-any.whl (from https://pypi.org/simple/setuptools/)>
pdm.termui: Installing wheel@0.40.0...
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/61/86/cc8d1ff2ca31a312a25a708c891cf9facbad4eae493b3872638db6785eb5/wheel-0.40.0-py3-none-any.whl (from https://pypi.org/simple/wheel/)>
pdm.termui: Synchronization complete.
Traceback (most recent call last):
  File "/home/johannesrave/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/johannesrave/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/core.py", line 268, in main
    return Core().main(args)
  File "/home/johannesrave/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/core.py", line 192, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/home/johannesrave/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/core.py", line 187, in main
    self.handle(project, options)
  File "/home/johannesrave/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/core.py", line 153, in handle
    command.handle(project, options)
  File "/home/johannesrave/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/cli/commands/install.py", line 82, in handle
    actions.do_lock(
  File "/home/johannesrave/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/cli/actions.py", line 104, in do_lock
    mapping, dependencies = resolve(
  File "/home/johannesrave/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/resolver/core.py", line 35, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "/home/johannesrave/.local/share/pdm/venv/lib/python3.10/site-packages/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/johannesrave/.local/share/pdm/venv/lib/python3.10/site-packages/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/home/johannesrave/.local/share/pdm/venv/lib/python3.10/site-packages/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "/home/johannesrave/.local/share/pdm/venv/lib/python3.10/site-packages/resolvelib/structs.py", line 127, in __bool__
    next(iter(self))
  File "/home/johannesrave/.local/share/pdm/venv/lib/python3.10/site-packages/resolvelib/structs.py", line 136, in __iter__
    self._factory() if self._iterable is None else self._iterable
  File "/home/johannesrave/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/resolver/providers.py", line 145, in matches_gen
    candidates = self._find_candidates(reqs[0])
  File "/home/johannesrave/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/resolver/providers.py", line 121, in _find_candidates
    can.prepare(self.repository.environment).metadata
  File "/home/johannesrave/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/models/candidates.py", line 496, in metadata
    result = self.prepare_metadata()
  File "/home/johannesrave/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/models/candidates.py", line 479, in prepare_metadata
    self._metadata_dir = builder(self._unpacked_dir, self.environment).prepare_metadata(metadir_parent)
  File "/home/johannesrave/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/builders/wheel.py", line 14, in prepare_metadata
    requires = self._hook.get_requires_for_build_wheel(config_settings)
  File "/home/johannesrave/.local/share/pdm/venv/lib/python3.10/site-packages/pyproject_hooks/_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "/home/johannesrave/.local/share/pdm/venv/lib/python3.10/site-packages/pyproject_hooks/_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "/home/johannesrave/.local/share/pdm/venv/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannesrave/.pyenv/versions/3.11.3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'setuptools.build_meta'
```

addendum: ``python -c "import setuptools.build_meta"` alone in the project dir does NOT throw an error. i think the only python on my system by now that does not have setuptools installed is the pdm isolated environment... if i understood that correctly.

EDIT: I have tried to narrow down the problem, and I think it only occurs when installing gradio and llama-cpp-python

## Expected behavior

`pdm install` installs all dependencies, no error occurs, or a helpful message tells me where the problem actually comes from.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.6.1
Python Interpreter:
  /home/johannesrave/ml/text-generation-webui/.venv/bin/python (3.11)
Project Root:
  /home/johannesrave/ml/text-generation-webui
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.11.3",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.15.90.1-microsoft-standard-WSL2",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Fri Jan 27 02:56:13 UTC 2023",
  "python_full_version": "3.11.3",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "linux"
}
```

# I tried:
- switching out the build-backend in the `pyproject.toml` for 
```
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
```
- installing setuptools to the python 3.11.3 venv using `pip`

**Comment by frostming** [comment]
I tried and can't get the same error. Did you set any env var starting with `PYTHON*` or `PDM*`?

**Comment by johannesrave** [comment]
thank you very much for trying it out!
i didn't set anything that i know of, and 
```
> printenv | grep PYTHON
> printenv | grep PDM
```
yield nothing either. i can confirm though that if i remove gradio, lllama-cpp-python and peft from the dependencies, then `pdm install` succeeds - i assume these deps are built from source. the project won't run obviously, but at least it narrows the problem space.
the python 3.10 mentioned in the stacktrace is probably the one that pdm is using, and the 3.11 is the one from the venv. that one definitely has setuptools installed. the oobabooga/text-generation-webui README talks about installing with conda, but i didn't want to use that on this fresh ubuntu - i was trying to set it up freshly just using pyenv and pdm.

do you have any idea (from the log maybe) where this could be coming from at all? what else can i try to find out more?
again, thanks for looking into it!

**Comment by johannesrave** [comment]
sorry, i can't reproduce this anymore either. i have tried restarting, recreating the repo with a new venv, and to uninstall setuptools and wheel from my interpreter and this particular error doesn't occur anymore. 
unfortunately, i'm having a different error for the same packages that were problematic here, namely `llama-cpp-python`, `ffmpy` and `` 
The new error is
```
pdm.exceptions.BuildError: Build backend raised error: Module 'wheel.bdist_wheel' is missing, please make sure it is specified in the 'build-system.requires' section. If it is not possible, add it to the project and use '--no-isolation' option.
```
After some trials and error and checking out the repos of those projects, I could build wheels from them independently.
I assume now that they don't provide all needed info for `pdm` in their respective setup.py and pyproject.toml... this at least is easy to recreate. Just init a new project and `pdm add ffmpy`.

I can create a new issues for this... but I don't think it's a `pdm` problem? conda can build the original project however, so it'd be cool if it "just worked" with pdm as well.

Sorry if this isn't very helpful, I spent a lot of time trying to get this to run but I'm still disoriented.
