### ISSUE TITLE
JSONDecodeError? (no content in response)

### ISSUE THREAD

**Issue by pawamoy** [pdm-project/pdm#1981]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

Hey, I'm getting these surprising errors while trying to lock dependencies.

I thought at first it was because I had a self-hosted pypi server in extra urls, but even after I removed it, I still get these errors.

I've updated all dependencies and tried a few older ones, to no avail.

## Steps to reproduce

```console
% pdm lock -v
STATUS: Resolving dependencies
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   pypi-insiders[docs,duty,quality,security,typing]
pdm.termui:   ruff>=0.0.246
pdm.termui:   platformdirs>=3.5
pdm.termui:   safety>=2
pdm.termui:   mypy>=0.910
pdm.termui:   types-markdown>=3.3
pdm.termui:   types-pyyaml>=6.0
pdm.termui:   types-toml>=0.10
pdm.termui:   pytest>=6.2
pdm.termui:   pytest-cov>=3.0
pdm.termui:   pytest-randomly>=3.10
pdm.termui:   pytest-xdist>=2.4
pdm.termui:   duty>=0.10
pdm.termui:   black>=23.1
pdm.termui:   markdown-callouts>=0.2
pdm.termui:   markdown-exec>=0.5
pdm.termui:   mkdocs>=1.3
pdm.termui:   mkdocs-coverage>=0.2
pdm.termui:   mkdocs-gen-files>=0.3
pdm.termui:   mkdocs-git-committers-plugin-2>=1.1
pdm.termui:   mkdocs-literate-nav>=0.4
pdm.termui:   mkdocs-material>=7.3
pdm.termui:   mkdocs-minify-plugin>=0.6.4
pdm.termui:   mkdocstrings[python]>=0.18
pdm.termui:   toml>=0.10
pdm.termui:   pypi-insiders[duty,tests]
pdm.termui:   black>=23.1
pdm.termui:   blacken-docs>=1.13
pdm.termui:   git-changelog>=1.0
pdm.termui:   python>=3.7
pdm.termui:   Adding requirement pypi-insiders[docs,duty,quality,security,typing]
unearth.preparer: The file . is a local directory, use it directly
pdm.termui: Running PEP 517 backend to get metadata for <Link file:///home/pawamoy/data/dev/insiders/pypi-insiders (from None)>
pdm.termui: Preparing isolated env for PEP 517 build...
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   pdm-backend
pdm.termui:   python>=3.11,<3.11.1
pdm.termui:   Adding requirement pdm-backend
pdm.termui:   Adding requirement python>=3.11,<3.11.1
pdm.termui: ======== Starting round 0 ========
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
pdm.termui: Pinning: pdm-backend 2.0.7
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
pdm.termui: ======== Resolution Result ========
pdm.termui: Stable pins:
pdm.termui:        python None
pdm.termui:   pdm-backend 2.0.7
pdm.termui: Installing pdm-backend@2.0.7...
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/53/65/ba05eaf97e06d9939992dfb6e7d9c54e9577d483b39485f9be9d498770b6/pdm_backend-2.0.7-py3-none-any.whl (from https://pypi.org/simple/pdm-backend/)>
pdm.termui: Synchronization complete.
pdm.termui:   Adding requirement ruff>=0.0.246
Traceback (most recent call last):
  File "/home/pawamoy/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 289, in main
    return Core().main(args)
           ^^^^^^^^^^^^^^^^^
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 207, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 202, in main
    self.handle(project, options)
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 157, in handle
    command.handle(project, options)
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/cli/commands/lock.py", line 61, in handle
    actions.do_lock(
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/cli/actions.py", line 99, in do_lock
    mapping, dependencies = resolve(
                            ^^^^^^^^
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/resolver/core.py", line 35, in resolve
    result = resolver.resolve(requirements, max_rounds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/resolvelib/structs.py", line 127, in __bool__
    next(iter(self))
         ^^^^^^^^^^
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/resolvelib/structs.py", line 136, in __iter__
    self._factory() if self._iterable is None else self._iterable
    ^^^^^^^^^^^^^^^
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/resolver/providers.py", line 145, in matches_gen
    candidates = self._find_candidates(reqs[0])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/resolver/providers.py", line 124, in _find_candidates
    return self.repository.find_candidates(requirement, requirement.prerelease or self.allow_prereleases)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/models/repositories.py", line 154, in find_candidates
    cans = LazySequence(self._find_candidates(requirement))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/models/repositories.py", line 354, in _find_candidates
    for c in finder.find_all_packages(requirement.project_name, allow_yanked=requirement.is_pinned)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/unearth/finder.py", line 281, in find_all_packages
    return LazySequence(self._find_packages(package_name, allow_yanked, hashes))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/unearth/finder.py", line 263, in _find_packages
    return sorted(all_packages, key=self._sort_key, reverse=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/unearth/collector.py", line 133, in collect_links_from_location
    yield from _collect_links_from_index(session, location)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/unearth/collector.py", line 153, in _collect_links_from_index
    page = fetch_page(session, location)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/unearth/collector.py", line 140, in fetch_page
    resp = _get_html_response(session, location)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/unearth/collector.py", line 175, in _get_html_response
    resp = session.get(
           ^^^^^^^^^^^^
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/requests/sessions.py", line 747, in send
    r.content
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/requests/models.py", line 899, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/requests/models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read, 411360 more expected)', IncompleteRead(0 bytes read, 411360 more expected))
```

Before that one I had this:

```console
 pdm lock -v                
STATUS: Resolving dependencies
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   black>=23.1
pdm.termui:   markdown-callouts>=0.2
pdm.termui:   markdown-exec>=0.5
pdm.termui:   mkdocs>=1.3
pdm.termui:   mkdocs-coverage>=0.2
pdm.termui:   mkdocs-gen-files>=0.3
pdm.termui:   mkdocs-git-committers-plugin-2>=1.1
pdm.termui:   mkdocs-literate-nav>=0.4
pdm.termui:   mkdocs-material>=7.3
pdm.termui:   mkdocs-minify-plugin>=0.6.4
pdm.termui:   mkdocstrings[python]>=0.18
pdm.termui:   toml>=0.10
pdm.termui:   ruff>=0.0.246
pdm.termui:   mypy>=0.910
pdm.termui:   types-markdown>=3.3
pdm.termui:   types-pyyaml>=6.0
pdm.termui:   types-toml>=0.10
pdm.termui:   pytest>=6.2
pdm.termui:   pytest-cov>=3.0
pdm.termui:   pytest-randomly>=3.10
pdm.termui:   pytest-xdist>=2.4
pdm.termui:   safety>=2
pdm.termui:   pypi-insiders[duty,tests]
pdm.termui:   duty>=0.10
pdm.termui:   pypi-insiders[docs,duty,quality,security,typing]
pdm.termui:   black>=23.1
pdm.termui:   blacken-docs>=1.13
pdm.termui:   git-changelog>=1.0
pdm.termui:   platformdirs>=3.5
pdm.termui:   python>=3.7
pdm.termui:   Adding requirement black>=23.1
pdm.termui:   Adding requirement markdown-callouts>=0.2
pdm.termui:   Adding requirement markdown-exec>=0.5
pdm.termui:   Adding requirement mkdocs>=1.3
pdm.termui:   Adding requirement mkdocs-coverage>=0.2
pdm.termui:   Adding requirement mkdocs-gen-files>=0.3
pdm.termui:   Adding requirement mkdocs-git-committers-plugin-2>=1.1
pdm.termui:   Adding requirement mkdocs-literate-nav>=0.4
pdm.termui:   Adding requirement mkdocs-material>=7.3
pdm.termui:   Adding requirement mkdocs-minify-plugin>=0.6.4
pdm.termui:   Adding requirement mkdocstrings[python]>=0.18
pdm.termui:   Adding requirement toml>=0.10
pdm.termui:   Adding requirement ruff>=0.0.246
pdm.termui:   Adding requirement mypy>=0.910
pdm.termui:   Adding requirement types-markdown>=3.3
pdm.termui:   Adding requirement types-pyyaml>=6.0
pdm.termui:   Adding requirement types-toml>=0.10
pdm.termui:   Adding requirement pytest>=6.2
pdm.termui:   Adding requirement pytest-cov>=3.0
pdm.termui:   Adding requirement pytest-randomly>=3.10
pdm.termui:   Adding requirement pytest-xdist>=2.4
pdm.termui:   Adding requirement safety>=2
pdm.termui:   Adding requirement pypi-insiders[duty,tests]
unearth.preparer: The file . is a local directory, use it directly
pdm.termui: Running PEP 517 backend to get metadata for <Link file:///home/pawamoy/data/dev/insiders/pypi-insiders (from None)>
pdm.termui: Preparing isolated env for PEP 517 build...
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   pdm-backend
pdm.termui:   python>=3.11,<3.11.1
pdm.termui:   Adding requirement pdm-backend
pdm.termui:   Adding requirement python>=3.11,<3.11.1
pdm.termui: ======== Starting round 0 ========
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
pdm.termui: Pinning: pdm-backend 2.0.7
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
pdm.termui: ======== Resolution Result ========
pdm.termui: Stable pins:
pdm.termui:        python None
pdm.termui:   pdm-backend 2.0.7
pdm.termui: Installing pdm-backend@2.0.7...
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/53/65/ba05eaf97e06d9939992dfb6e7d9c54e9577d483b39485f9be9d498770b6/pdm_backend-2.0.7-py3-none-any.whl (from https://pypi.org/simple/pdm-backend/)>
pdm.termui: Synchronization complete.
pdm.termui:   Adding requirement duty>=0.10
pdm.termui:   Adding requirement pypi-insiders[docs,duty,quality,security,typing]
unearth.preparer: The file . is a local directory, use it directly
pdm.termui: Running PEP 517 backend to get metadata for <Link file:///home/pawamoy/data/dev/insiders/pypi-insiders (from None)>
pdm.termui: Preparing isolated env for PEP 517 build...
pdm.termui:   Adding requirement black>=23.1
pdm.termui:   Adding requirement blacken-docs>=1.13
pdm.termui:   Adding requirement git-changelog>=1.0
pdm.termui:   Adding requirement platformdirs>=3.5
Traceback (most recent call last):
  File "/home/pawamoy/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 289, in main
    return Core().main(args)
           ^^^^^^^^^^^^^^^^^
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 207, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 202, in main
    self.handle(project, options)
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 157, in handle
    command.handle(project, options)
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/cli/commands/lock.py", line 61, in handle
    actions.do_lock(
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/cli/actions.py", line 99, in do_lock
    mapping, dependencies = resolve(
                            ^^^^^^^^
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/resolver/core.py", line 35, in resolve
    result = resolver.resolve(requirements, max_rounds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/resolvelib/structs.py", line 127, in __bool__
    next(iter(self))
         ^^^^^^^^^^
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/resolvelib/structs.py", line 136, in __iter__
    self._factory() if self._iterable is None else self._iterable
    ^^^^^^^^^^^^^^^
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/resolver/providers.py", line 145, in matches_gen
    candidates = self._find_candidates(reqs[0])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/resolver/providers.py", line 124, in _find_candidates
    return self.repository.find_candidates(requirement, requirement.prerelease or self.allow_prereleases)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/models/repositories.py", line 150, in find_candidates
    cans = LazySequence(self._find_candidates(requirement))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/models/repositories.py", line 350, in _find_candidates
    for c in finder.find_all_packages(requirement.project_name, allow_yanked=requirement.is_pinned)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/unearth/finder.py", line 281, in find_all_packages
    return LazySequence(self._find_packages(package_name, allow_yanked, hashes))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/unearth/finder.py", line 263, in _find_packages
    return sorted(all_packages, key=self._sort_key, reverse=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/unearth/collector.py", line 133, in collect_links_from_location
    yield from _collect_links_from_index(session, location)
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.11/site-packages/unearth/collector.py", line 83, in parse_json_response
    data = json.loads(page.content)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pawamoy/.basher-packages/pyenv/pyenv/versions/3.11.0/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pawamoy/.basher-packages/pyenv/pyenv/versions/3.11.0/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pawamoy/.basher-packages/pyenv/pyenv/versions/3.11.0/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

...which seems similar: no content in the response or something.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.7.1
Python Interpreter:
  /home/pawamoy/.basher-packages/pyenv/pyenv/versions/3.11.0/bin/python3 (3.11)
Project Root:
  /home/pawamoy/data/dev/insiders/pypi-insiders
Local Packages:
  /home/pawamoy/data/dev/insiders/pypi-insiders/__pypackages__/3.11
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.0",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.3.5-arch1-1",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT_DYNAMIC Tue, 30 May 2023 13:44:01 +0000",
  "python_full_version": "3.11.0",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "linux"
}
```

```console
% pipx runpip pdm freeze
blinker==1.6.2
CacheControl==0.13.0
certifi==2023.5.7
charset-normalizer==3.1.0
distlib==0.3.6
filelock==3.12.0
findpython==0.2.5
idna==3.4
installer==0.7.0
markdown-it-py==2.2.0
mdurl==0.1.2
msgpack==1.0.5
packaging==23.1
pdm==2.7.1
platformdirs==3.5.1
Pygments==2.15.1
pyproject_hooks==1.0.0
python-dotenv==1.0.0
requests==2.31.0
requests-toolbelt==1.0.0
resolvelib==1.0.1
rich==13.4.1
shellingham==1.5.0.post1
tomlkit==0.11.8
unearth==0.9.1
urllib3==2.0.2
virtualenv==20.23.0
```

**Comment by pawamoy** [comment]
It seems to happen after the first `Adding requirement...` line every time.

**Comment by frostming** [comment]
Sorry, it's due to the cache change #1971

**Comment by frostming** [comment]
Due to the cache broken issue, I have yanked 2.7.1. And we will work on making the cache change more smooth in the next release.

**Comment by baggiponte** [comment]
Hi, sorry to bump this again after closing the issue - I am experiencing the same problem with 2.7.0. Fortunately cleaning the cache solves the problem! Perhaps it would suffice to add a warning upon updating?

**Comment by tgolsson** [comment]
Just noticed this :( Sorry for all the trouble folks. I was going back and forth between lots of versions and had no issues with the cache breaking as long as I started from an old non-split cache (i.e, older version) -- I guess I just got lucky, or I'd cleared it by accident at some point and had a better initial state.
