### ISSUE TITLE
Install without readme

### ISSUE THREAD

**Issue by mjlabe** [pdm-project/pdm#1990]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

toml:
```
[project]
name = "my-module"
version = "0.1.0"
description = "Model"
authors = [
    {name = "Me", email = "me@me.com"},
]

readme = "README.md"
license = {text = "None"}
requires-python = ">=3.9,<3.10"

dependencies = [
    "joblib==1.2.0",
    "numpy==1.23.4",
]
```

Dockerfile:
```
FROM python:3.9.17-slim-bullseye

WORKDIR /lib

RUN apt-get update && apt-get install gcc -y

# Install pdm to install the release libraries.
RUN pip install pdm

COPY pdm.lock /lib/pdm.lock
COPY pyproject.toml /lib/pyproject.toml
## Install all of the release libraries.
RUN pdm sync -v --prod --no-editable
## RUN pdm sync also tried without flags
```

Error output:
```
#12 160.1   ✖ Install my-module 0.1.0 failed
#12 160.1 
#12 160.1 Traceback (most recent call last):
#12 160.1   File "/usr/local/bin/pdm", line 8, in <module>
#12 160.1     sys.exit(main())
#12 160.1   File "/usr/local/lib/python3.9/site-packages/pdm/core.py", line 289, in main
#12 160.1     return Core().main(args)
#12 160.1   File "/usr/local/lib/python3.9/site-packages/pdm/core.py", line 207, in main
#12 160.1     raise cast(Exception, err).with_traceback(traceback) from None
#12 160.1   File "/usr/local/lib/python3.9/site-packages/pdm/core.py", line 202, in main
#12 160.1     self.handle(project, options)
#12 160.1   File "/usr/local/lib/python3.9/site-packages/pdm/core.py", line 157, in handle
#12 160.1     command.handle(project, options)
#12 160.1   File "/usr/local/lib/python3.9/site-packages/pdm/cli/commands/sync.py", line 43, in handle
#12 160.1     actions.do_sync(
#12 160.1   File "/usr/local/lib/python3.9/site-packages/pdm/cli/actions.py", line 214, in do_sync
#12 160.1     synchronizer.synchronize()
#12 160.1   File "/usr/local/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 454, in synchronize
#12 160.1     self.install_candidate(self_key, progress)
#12 160.1   File "/usr/local/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 275, in install_candidate
#12 160.1     self.manager.install(can)
#12 160.1   File "/usr/local/lib/python3.9/site-packages/pdm/installers/manager.py", line 33, in install
#12 160.1     installer(str(prepared.build()), self.environment, prepared.direct_url())
#12 160.1   File "/usr/local/lib/python3.9/site-packages/pdm/models/candidates.py", line 389, in build
#12 160.1     self.wheel = Path(builder.build(build_dir, metadata_directory=self._metadata_dir))
#12 160.1   File "/usr/local/lib/python3.9/site-packages/pdm/builders/wheel.py", line 26, in build
#12 160.1     requires = self._hook.get_requires_for_build_wheel(config_settings)
#12 160.1   File "/usr/local/lib/python3.9/site-packages/pyproject_hooks/_impl.py", line 166, in get_requires_for_build_wheel
#12 160.1     return self._call_hook('get_requires_for_build_wheel', {
#12 160.1   File "/usr/local/lib/python3.9/site-packages/pyproject_hooks/_impl.py", line 311, in _call_hook
#12 160.1     self._subprocess_runner(
#12 160.1   File "/usr/local/lib/python3.9/site-packages/pdm/builders/base.py", line 260, in subprocess_runner
#12 160.1     return log_subprocessor(cmd, cwd, extra_environ=env)
#12 160.1   File "/usr/local/lib/python3.9/site-packages/pdm/builders/base.py", line 107, in log_subprocessor
#12 160.1     raise build_error(e) from None
#12 160.1 pdm.exceptions.BuildError: Build backend raised error: Showing the last 10 lines of the build output:
#12 160.1     super().__init__(location, config_settings)
#12 160.1   File "/tmp/pdm-build-env-8eubxsoc-shared/lib/python3.9/site-packages/pdm/backend/base.py", line 99, in __init__
#12 160.1     self.config = Config.from_pyproject(self.location)
#12 160.1   File "/tmp/pdm-build-env-8eubxsoc-shared/lib/python3.9/site-packages/pdm/backend/config.py", line 77, in from_pyproject
#12 160.1     return cls(root, data)
#12 160.1   File "/tmp/pdm-build-env-8eubxsoc-shared/lib/python3.9/site-packages/pdm/backend/config.py", line 44, in __init__
#12 160.1     self.validate(data, root)
#12 160.1   File "/tmp/pdm-build-env-8eubxsoc-shared/lib/python3.9/site-packages/pdm/backend/config.py", line 63, in validate
#12 160.1     raise ValidationError(e.args[0], e.key) from e
#12 160.1 pdm.backend.exceptions.ValidationError: project.license.file: Readme file not found (`README.md`)
#12 ERROR: executor failed running [/bin/sh -c pdm sync -v --prod --no-editable]: exit code: 1
```

## Actual behavior

Cannot install without readme

## Expected behavior

Install without readme.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.17",
  "os_name": "posix",
  "platform_machine": "aarch64",
  "platform_release": "5.10.76-linuxkit",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT Mon Nov 8 11:22:26 UTC 2021",
  "python_full_version": "3.9.17",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}

```

**Comment by frostming** [comment]
I don't understand but why not leave the `readme = "README.md"` out when you don't have one?

**Comment by mjlabe** [comment]
I have one but I don't want or need it in the Docker image. For production, I only copy over source code, not misc files like a readme. Noted.

**Comment by mjlabe** [comment]
What is the purpose of it being required to install packages?

**Comment by frostming** [comment]
> What is the purpose of it being required to install packages?

It is not required, you are free to exclude that field in `pyproject.toml` I don't get what you are confusing here.

**Comment by pawamoy** [comment]
@mjlabe it is required because it is referenced in pyproject.toml. The readme field is used to build the long description of the package metadata. If the referenced file isn't found, PDM tells you so by erroring out. Silently ignoring the long description would not be a good idea. So, yes, you have to copy the readme in your Docker image to build the package within it :)
