### ISSUE TITLE
pdm fails to install

### ISSUE THREAD

**Issue by kwigley** [pdm-project/pdm#2003]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

download and run install script, I discovered this when installing pdm in github actions using `pdm-project/setup-pdm`

## Actual behavior

```bash
$ curl -sSL https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py | python3 -
Traceback (most recent call last):
  File "<stdin>", line 454, in <module>
  File "<stdin>", line 439, in main
  File "<string>", line 9, in __init__
  File "<stdin>", line 196, in __post_init__
  File "<stdin>", line 217, in _get_latest_version
  File "<stdin>", line 217, in <setcomp>
AttributeError: 'list' object has no attribute 'get'
```

## Expected behavior
successful installation :)

## Environment Information
N/A
```bash
# Paste the output of `pdm info && pdm info --env` below:

```

**Comment by kwigley** [comment]
fixed by https://github.com/pdm-project/pdm/commit/16a137f5a5ef4a90b05b1b5e3f00a84542e5fa77! 👍
