### ISSUE TITLE
pdm sync TypeError: expected string or bytes-like object, got 'NoneType'

### ISSUE THREAD

**Issue by vvanglro** [pdm-project/pdm#2075]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce
There is no problem in executing sync for the first time after locking, but an error will be reported when executing sync again later.
```sh
pdm lock
pdm sync
pdm sync  # error
```

## Actual behavior

```sh
STATUS: Resolving packages from lockfile...
STATUS: Fetching hashes for resolved packages...
Traceback (most recent call last):
  File "/opt/homebrew/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.7.4/libexec/lib/python3.11/site-packages/pdm/core.py", line 289, in main
    return Core().main(args)
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.7.4/libexec/lib/python3.11/site-packages/pdm/core.py", line 207, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/opt/homebrew/Cellar/pdm/2.7.4/libexec/lib/python3.11/site-packages/pdm/core.py", line 202, in main
    self.handle(project, options)
  File "/opt/homebrew/Cellar/pdm/2.7.4/libexec/lib/python3.11/site-packages/pdm/core.py", line 157, in handle
    command.handle(project, options)
  File "/opt/homebrew/Cellar/pdm/2.7.4/libexec/lib/python3.11/site-packages/pdm/cli/commands/sync.py", line 43, in handle
    actions.do_sync(
  File "/opt/homebrew/Cellar/pdm/2.7.4/libexec/lib/python3.11/site-packages/pdm/cli/actions.py", line 190, in do_sync
    synchronizer = project.core.synchronizer_class(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.7.4/libexec/lib/python3.11/site-packages/pdm/installers/synchronizers.py", line 131, in __init__
    self.working_set = environment.get_working_set()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.7.4/libexec/lib/python3.11/site-packages/pdm/environments/base.py", line 148, in get_working_set
    return WorkingSet([paths["platlib"], paths["purelib"]])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.7.4/libexec/lib/python3.11/site-packages/pdm/models/working_set.py", line 66, in __init__
    self._dist_map = {normalize_name(dist.metadata["Name"]): dist for dist in distributions(path=paths)}
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.7.4/libexec/lib/python3.11/site-packages/pdm/models/working_set.py", line 66, in <dictcomp>
    self._dist_map = {normalize_name(dist.metadata["Name"]): dist for dist in distributions(path=paths)}
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.7.4/libexec/lib/python3.11/site-packages/pdm/utils.py", line 339, in normalize_name
    name = re.sub(r"[^A-Za-z0-9]+", "-", name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/__init__.py", line 185, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'

```

## Environment Information

```bash
PDM version:
  2.7.4
Python Interpreter:
  /Users/hulk/miniforge3/envs/cfpy38/bin/python (3.8)
Project Root:
  /Users/hulk/code/github/cf_clearance
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.16",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "22.5.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000",
  "python_full_version": "3.8.16",
  "platform_python_implementation": "CPython",
  "python_version": "3.8",
  "sys_platform": "darwin"
}


```

**Comment by vvanglro** [comment]
https://github.com/pdm-project/pdm/blob/main/src/pdm/models/working_set.py#L66
```py
self._dist_map = {normalize_name(dist.metadata["Name"]): dist for dist in distributions(path=paths)
                  if dist.metadata["Name"]}
```
I will solve it after adding judgment here, But why does `None` appear here?

**Comment by frostming** [comment]
It seems to be reproducible with a conda env. The installation metadata there are not standard.

**Comment by vvanglro** [comment]
The second question, there are duplicate paths in paths, can we `set` them here?

![image](https://github.com/pdm-project/pdm/assets/43594924/94e57fb6-1654-45d5-94b8-f64325588ad4)

**Comment by frostming** [comment]
> The second question, there are duplicate paths in paths, can we `set` them here?
> I can PR to solve these problems.

SGTM, appreciate it.

**Comment by vvanglro** [comment]
Remarks about incomplete uninstallation of package information, It is convenient for people who encounter the same problem to troubleshoot in the future.

Related question link: [#9129](https://github.com/pypa/pip/issues/9129) [#10357](https://github.com/conda/conda/issues/10357)
