### ISSUE TITLE
Failed to detect selinux python bindings

### ISSUE THREAD

**Issue by dfang** [pdm-project/pdm#2085]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

see pyproject.toml and pdm version in **Environment Information** section, it should be enough to reproduce,  this error occurs on **centos 7**

## Actual behavior

```
$ molecule 
Traceback (most recent call last):
  File "/home/deploy/ansible-role-rtx/.venv/bin/ansible-config", line 5, in <module>
    from ansible.cli.config import main
  File "/home/deploy/ansible-role-rtx/.venv/lib/python3.10/site-packages/ansible/cli/__init__.py", line 102, in <module>
    from ansible.module_utils.common.file import is_executable
  File "/home/deploy/ansible-role-rtx/.venv/lib/python3.10/site-packages/ansible/module_utils/common/file.py", line 18, in <module>
    import selinux  # pylint: disable=unused-import
  File "/home/deploy/ansible-role-rtx/.venv/lib/python3.10/site-packages/selinux/__init__.py", line 106, in <module>
    check_system_sitepackages()
  File "/home/deploy/ansible-role-rtx/.venv/lib/python3.10/site-packages/selinux/__init__.py", line 102, in check_system_sitepackages
    raise Exception(
Exception: Failed to detect selinux python bindings at ['/home/deploy/.local/share/rtx/installs/python/3.10.11/lib/python3.10/site-packages']
Traceback (most recent call last):
  File "/home/deploy/ansible-role-rtx/.venv/bin/molecule", line 5, in <module>
    from molecule.__main__ import main
  File "/home/deploy/ansible-role-rtx/.venv/lib/python3.10/site-packages/molecule/__main__.py", line 22, in <module>
    from molecule.shell import main
  File "/home/deploy/ansible-role-rtx/.venv/lib/python3.10/site-packages/molecule/shell.py", line 29, in <module>
    from molecule import command, logger
  File "/home/deploy/ansible-role-rtx/.venv/lib/python3.10/site-packages/molecule/command/__init__.py", line 27, in <module>
    from molecule.command import base  # noqa
  File "/home/deploy/ansible-role-rtx/.venv/lib/python3.10/site-packages/molecule/command/base.py", line 33, in <module>
    import molecule.scenarios
  File "/home/deploy/ansible-role-rtx/.venv/lib/python3.10/site-packages/molecule/scenarios.py", line 23, in <module>
    from molecule import util
  File "/home/deploy/ansible-role-rtx/.venv/lib/python3.10/site-packages/molecule/util.py", line 40, in <module>
    from molecule.app import app
  File "/home/deploy/ansible-role-rtx/.venv/lib/python3.10/site-packages/molecule/app.py", line 13, in <module>
    app = App()
  File "/home/deploy/ansible-role-rtx/.venv/lib/python3.10/site-packages/molecule/app.py", line 10, in __init__
    self.runtime = Runtime(isolated=True)
  File "/home/deploy/ansible-role-rtx/.venv/lib/python3.10/site-packages/ansible_compat/runtime.py", line 201, in __init__
    self.config = AnsibleConfig()
  File "/home/deploy/ansible-role-rtx/.venv/lib/python3.10/site-packages/ansible_compat/config.py", line 424, in __init__
    config_dump = subprocess.check_output(
  File "/home/deploy/.local/share/rtx/installs/python/3.10.12/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/deploy/.local/share/rtx/installs/python/3.10.12/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ansible-config', 'dump']' returned non-zero exit status 1.
```
## Expected behavior

run `molecule` will output help messages, it works on ubuntu but not on centos 7

## Environment Information

```bash
$ cat pyproject.toml 

[project]
name = ""
version = ""
description = ""
authors = []
dependencies = [
    "molecule>=5.0.1",
    "molecule-plugins[docker]>=23.4.1",
    "ansible-core>=2.15.0",
    "selinux>=0.3.0",
]
requires-python = ">=3.10"
license = {text = "MIT"}

$ pdm info
PDM version:
  2.7.4
Python Interpreter:
  /home/ubuntu/ansible-role-rtx/.venv/bin/python (3.10)
Project Root:
  /home/ubuntu/ansible-role-rtx
Local Packages:
```

Related issue:

https://github.com/pdm-project/pdm/discussions/663

https://github.com/pycontribs/selinux/issues/22

https://stackoverflow.com/questions/63173955/aborting-target-uses-selinux-but-python-bindings-libselinux-python-arent-ins

**Comment by frostming** [comment]
I don't think it is something fixable on PDM side, nor can I reproduce it on `centos:7` image(but on ARM). Moreover, I personally don't have enough energy debugging such platform-specific problems.

**Comment by dfang** [comment]
never mind. i will never use centos 7 again.  :(
