### ISSUE TITLE
Could not manage PDM to use windows trust store

### ISSUE THREAD

**Issue by g0di** [pdm-project/pdm#2088]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

I'm working on a company windows machine which is behind a proxy and having some self signed certificates. The company is also providing his own pypi repository through Artifactory which I already configured successfully using the following config

```bash
$ pdm config pypi.url "https://artifactory.fake.company:15443/artifactory/api/pypi/eoc-pypi/simple"
$ pdm config pypi.verify_ssl false
```
>This configuration is actually working

However, I would prefer to keep SSL verification so I found from doc that I could just run `pdm self add truststore` and it should use the Windows certificate store properly.

However, whenever I try to install a dependency it ends up with a SSLCertVerificationError. It feels like the `truststore` package is having no effect at all.
>After having set back `pypi.verify_ssl` to `True`

PDM config
```
Site/default configuration (C:\ProgramData\pdm\pdm\config.toml):
build_isolation = True
cache_dir = C:\Users\TBEBGOD\AppData\Local\pdm\pdm\Cache
check_update = True
global_project.fallback = False
global_project.fallback_verbose = True
global_project.path = C:\Users\TBEBGOD\AppData\Local\pdm\pdm\global-project
global_project.user_site = False
install.cache = False
install.cache_method = symlink
install.parallel = True
project_max_depth = 5
pypi.ignore_stored_index = False
pypi.json_api = False
pypi.url = https://pypi.org/simple
pypi.verify_ssl = True
python.use_pyenv = True
python.use_venv = True
strategy.resolve_max_rounds = 10000
strategy.save = minimum
strategy.update = reuse
theme.error = red
theme.info = blue
theme.primary = cyan
theme.req = bold green
theme.success = green
theme.warning = yellow
venv.backend = virtualenv
venv.in_project = True
venv.location = C:\Users\TBEBGOD\AppData\Local\pdm\pdm\venvs
venv.prompt = {project_name}-{python_version}
venv.with_pip = False

Home configuration (C:\Users\TBEBGOD\AppData\Local\pdm\pdm\config.toml):
install.cache = True
pypi.url = https://artifactory.fake.company:15443/artifactory/api/pypi/eoc-pypi/simple

Project configuration (C:\Users\TBEBGOD\Developement\MyRepo\pdm.toml):
```

## Steps to reproduce

Create an empty project with pdm
```bash
pdm init
```
>I'm assuming PDM is already installed

Set the config to use artifactory
```bash
pdm config pypi.url "https://artifactory.fake.company.com:15443/artifactory/api/pypi/eoc-pypi/simple"
```

Add `truststore` package
```bash
pdm self add truststore
```

Try to add the dependency
```bash
pdm add -v fastapi
```

Note that I'm not sure how you're supposed to reproduce this situation which requires an artifactory and a machine having self signed certificates behind a proxy...

## Actual behavior

The `add` commnd ends with following error
```
Adding packages to default dependencies: fastapi
STATUS: Resolving dependencies
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   fastapi
pdm.termui:   python>=3.10
pdm.termui:   Adding requirement fastapi
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\TBEBGOD\AppData\Local\Programs\Python\Python311\Scripts\pdm.exe\__main__.py", line 7, in <module>
  File "C:\Users\TBEBGOD\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\core.py", line 289, in main
    return Core().main(args)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\TBEBGOD\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\core.py", line 207, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "C:\Users\TBEBGOD\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\core.py", line 202, in main
    self.handle(project, options)
  File "C:\Users\TBEBGOD\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\core.py", line 157, in handle
    command.handle(project, options)
  File "C:\Users\TBEBGOD\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\cli\commands\add.py", line 67, in handle
    self.do_add(
  File "C:\Users\TBEBGOD\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\cli\commands\add.py", line 159, in do_add
    resolved = do_lock(
               ^^^^^^^^
  File "C:\Users\TBEBGOD\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\cli\actions.py", line 88, in do_lock
    mapping, dependencies = resolve(
                            ^^^^^^^^
  File "C:\Users\TBEBGOD\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\resolver\core.py", line 35, in resolve
    result = resolver.resolve(requirements, max_rounds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TBEBGOD\AppData\Local\Programs\Python\Python311\Lib\site-packages\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TBEBGOD\AppData\Local\Programs\Python\Python311\Lib\site-packages\resolvelib\resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "C:\Users\TBEBGOD\AppData\Local\Programs\Python\Python311\Lib\site-packages\resolvelib\resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "C:\Users\TBEBGOD\AppData\Local\Programs\Python\Python311\Lib\site-packages\resolvelib\structs.py", line 127, in __bool__
    next(iter(self))
  File "C:\Users\TBEBGOD\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\resolver\providers.py", line 247, in matches_gen
    yield from super_find()
               ^^^^^^^^^^^^
  File "C:\Users\TBEBGOD\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\resolver\providers.py", line 145, in matches_gen
    candidates = self._find_candidates(reqs[0])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TBEBGOD\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\resolver\providers.py", line 124, in _find_candidates
    return self.repository.find_candidates(requirement, requirement.prerelease or self.allow_prereleases)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TBEBGOD\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\models\repositories.py", line 154, in find_candidates
    cans = LazySequence(self._find_candidates(requirement))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TBEBGOD\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\models\repositories.py", line 354, in _find_candidates
    for c in finder.find_all_packages(requirement.project_name, allow_yanked=requirement.is_pinned)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TBEBGOD\AppData\Local\Programs\Python\Python311\Lib\site-packages\unearth\finder.py", line 281, in find_all_packages
    return LazySequence(self._find_packages(package_name, allow_yanked, hashes))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TBEBGOD\AppData\Local\Programs\Python\Python311\Lib\site-packages\unearth\finder.py", line 263, in _find_packages
    return sorted(all_packages, key=self._sort_key, reverse=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TBEBGOD\AppData\Local\Programs\Python\Python311\Lib\site-packages\unearth\collector.py", line 133, in collect_links_from_location
    yield from _collect_links_from_index(session, location)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TBEBGOD\AppData\Local\Programs\Python\Python311\Lib\site-packages\unearth\collector.py", line 153, in _collect_links_from_index
    page = fetch_page(session, location)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TBEBGOD\AppData\Local\Programs\Python\Python311\Lib\site-packages\unearth\collector.py", line 140, in fetch_page
    resp = _get_html_response(session, location)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TBEBGOD\AppData\Local\Programs\Python\Python311\Lib\site-packages\unearth\collector.py", line 175, in _get_html_response
    resp = session.get(
           ^^^^^^^^^^^^
  File "C:\Users\TBEBGOD\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TBEBGOD\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TBEBGOD\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TBEBGOD\AppData\Local\Programs\Python\Python311\Lib\site-packages\cachecontrol\adapter.py", line 76, in send
    resp = super().send(request, stream, timeout, verify, cert, proxies)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TBEBGOD\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='artifactory.fake.company.com', port=15443): Max retries exceeded with url: /artifactory/api/pypi/eoc-pypi/simple/fastapi/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)')))
```

## Expected behavior

The package is added and installed successfully. I'm not sure however if I've done things the right way

## Environment Information
Note that PDM is installed through pip on my Python 3.11 site packages. 

```bash
PDM version:
  2.7.4
Python Interpreter:
  C:\Users\TBEBGOD\Developement\temp\.venv\Scripts\python.exe (3.10)
Project Root:
  C:/Users/TBEBGOD/Developement/temp
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.10.11",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19044",
  "python_full_version": "3.10.11",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "win32"
}
```

**Comment by frostming** [comment]
Truststore feature is supported on 2.8.0. I don't understand this report.
