### ISSUE TITLE
pdm run not work as expected

### ISSUE THREAD

**Issue by dfang** [pdm-project/pdm#2094]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Actual behavior

```
λ cat pyproject.toml

[project]
name = ""
version = ""
description = ""
authors = []
dependencies = [
    "molecule>=5.0.1",
    "molecule-plugins[docker]>=23.4.1",
    "ansible-core>=2.15.0",
    "selinux>=0.3.0",
]
requires-python = ">=3.10"
license = {text = "MIT"}

[tool.pdm.dev-dependencies]
dev = [
    "ansible-lint>=6.16.2",
    "yamllint>=1.32.0",
]

# https://github.com/pdm-project/pdm/issues/1575
# https://pdm.fming.dev/latest/usage/config/#override-the-resolved-package-versions
[tool.pdm.resolution.overrides]
will-not-work-on-windows-try-from-wsl-instead = "0.1.0"

# https://pdm.fming.dev/latest/usage/scripts/
[tool.pdm.scripts]
yamllint = "yamllint ."
ansible-lint = "ansible-lint --write=all --show-relpath"
lint = {composite = ["ansible-lint", "yamllint"]}
```

```
$ pdm run lint

Traceback (most recent call last):
  File "/home/ubuntu/ansible-role-rtx/.venv/bin/ansible-lint", line 8, in <module>
    sys.exit(_run_cli_entrypoint())
  File "/home/ubuntu/ansible-role-rtx/.venv/lib/python3.10/site-packages/ansiblelint/__main__.py", line 310, in _run_cli_entrypoint
    sys.exit(main(sys.argv))
  File "/home/ubuntu/ansible-role-rtx/.venv/lib/python3.10/site-packages/ansiblelint/__main__.py", line 301, in main
    return app.report_outcome(result, mark_as_success=mark_as_success)
  File "/home/ubuntu/ansible-role-rtx/.venv/lib/python3.10/site-packages/ansiblelint/app.py", line 230, in report_outcome
    self.report_summary(
  File "/home/ubuntu/ansible-role-rtx/.venv/lib/python3.10/site-packages/ansiblelint/app.py", line 337, in report_summary
    version_warning = get_version_warning()
  File "/home/ubuntu/ansible-role-rtx/.venv/lib/python3.10/site-packages/ansiblelint/config.py", line 302, in get_version_warning
    pip = guess_install_method()
  File "/home/ubuntu/ansible-role-rtx/.venv/lib/python3.10/site-packages/ansiblelint/config.py", line 223, in guess_install_method
    from pip._internal.metadata import get_default_environment
ModuleNotFoundError: No module named 'pip'
```

## Expected behavior

`pdm run` can run packages from dev group dependencies

## Environment Information

```bash
$ python -V
Python 3.10.12

$ pdm -V
PDM, version 2.7.4

$ pdm info
PDM version:
  2.7.4
Python Interpreter:
  /home/ubuntu/ansible-role-rtx/.venv/bin/python (3.10)
Project Root:
  /home/ubuntu/ansible-role-rtx
Local Packages:


$ pdm info --env
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.12",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.15.0-76-generic",
  "platform_system": "Linux",
  "platform_version": "#83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023",
  "python_full_version": "3.10.12",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "linux"
}

```

**Comment by pawamoy** [comment]
Ansible Lint uses pip but does not declare it as a dependency: they use setuptools as a build backend and list dependencies in https://github.com/ansible/ansible-lint/blob/main/.config/requirements.in.

Try to open an issue there, PDM is not responsible :slightly_smiling_face:

**Comment by dfang** [comment]
got it why pdm run not work as expected. But what do you mean by “can add the dependency to pip in your own project”?

add pip to tool.pdm.dev-dependencies like `pdm add --dev pip` ?

**Comment by pawamoy** [comment]
In the same group as ansible-lint yes.
