### ISSUE TITLE
zipapp version handling issue...

### ISSUE THREAD

**Issue by franzhaas** [pdm-project/pdm#2097]
- [x ] I have searched the issue tracker and believe that this is not a duplicate.

I am using pdm packed with packer as a zipapp. This used to work up to and including pdm 2.6.1. starting with 2.7.0 it does not work for me anymore, due to a version handling issue.:

pdm.exe pack -m pdm.core:main  -o pdm.pyz
py pdm.pyz

  File "C:\Python311\Lib\importlib\metadata\__init__.py", line 991, in version
    return distribution(distribution_name).version
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\importlib\metadata\__init__.py", line 964, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\importlib\metadata\__init__.py", line 561, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for pdm

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "xxxxxxxxx\pdm.pyz\__main__.py", line 2, in <module>
  File "xxxxxxxxx\pdm.pyz\pdm\core.py", line 22, in <module>
  File "xxxxxxxxx\pdm.pyz\pdm\__version__.py", line 11, in <module>
  File "xxxxxxxxx\pdm.pyz\pdm\__version__.py", line 8, in read_version
  File "xxxxxxxxx\pdm.pyz\pdm\compat.py", line 22, in resources_read_text
  File "C:\Python311\Lib\zipfile.py", line 2393, in open
    raise FileNotFoundError(self)
FileNotFoundError: xxxxxxxxxxx\pdm.pyz/pdm/models/VERSION

---------------

any ideas?

**Comment by franzhaas** [comment]
Hi thanks a lot for pointing me to the CI job, the way it is done in the CI job works for me as well. (my problem is solved)

I looked at the job and I do believe the difference between the tested and working solution and my issue is.:

The working solution.:

checks out pdm
install the pdm which was just checked out
uses this installed pdm to pack the pdm which was just checked out


whereas my broken approach does this.:
use pipx installed pdm 2.7.4 
use a project which has the plugin "pdm-packer" already added to the project
"pdm add pdm"

When I try to pack this I end up with a broken pdm zipapp.

Thanks for pointing me to the tested version. This works in my environment as well. So my problem is solved.

Thanks again, 
Franz
