### ISSUE TITLE
CandidateNotFound when pdm add package from git with extra

### ISSUE THREAD

**Issue by PushUpek** [pdm-project/pdm#2133]
- [ x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

```
pdm add -v git+https://github.com/tortoise/tortoise-orm.git@develop#egg=tortoise-orm[asyncpg]
Adding packages to default dependencies: tortoise-orm @ git+https://github.com/tortoise/tortoise-orm.git@develop
STATUS: Resolving dependencies
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   sanic>=22.3.1
pdm.termui:   sanic-jwt>=1.7.0
pdm.termui:   bcrypt>=3.2.0
pdm.termui:   aiobotocore>=2.2.0
pdm.termui:   alembic>=1.7.7
pdm.termui:   psycopg2-binary>=2.9.3
pdm.termui:   aio-pika>=7.1.2
pdm.termui:   motor>=2.5.1
pdm.termui:   aiohttp>=3.8.1
pdm.termui:   pymongo>=3.12.3
pdm.termui:   typing-extensions>=4.2.0
pdm.termui:   py-zabbix>=1.1.7
pdm.termui:   psutil>=5.9.0
pdm.termui:   pytz>=2022.1
pdm.termui:   asn1>=2.5.0
pdm.termui:   ujson>=5.2.0
pdm.termui:   defusedxml>=0.7.1
pdm.termui:   ecpy>=1.2.5
pdm.termui:   sanic-ext>=22.3.0
pdm.termui:   pydantic>=1.9.0
pdm.termui:   tortoise-orm[asyncpg] @ git+https://github.com/tortoise/tortoise-orm.git@develop
pdm.termui:   httpx>=0.22.0
pdm.termui:   redis[hiredis]>=4.3.4
pdm.termui:   aiofiles>=22.1.0
pdm.termui:   aiokafka>=0.8.1
pdm.termui:   gps-events>=0.3.0
pdm.termui:   pytest>=7.1.1
pdm.termui:   coverage<6.4
pdm.termui:   coverage[toml]<6.4
pdm.termui:   pytest-cov>=3.0.0
pdm.termui:   blue>=0.8.0
pdm.termui:   mypy>=0.942
pdm.termui:   pytest-asyncio>=0.18.3
pdm.termui:   pytest-watch>=4.2.0
pdm.termui:   pytest-benchmark>=3.4.1
pdm.termui:   sanic-testing>=22.3.0
pdm.termui:   types-ujson>=5.5.0
pdm.termui:   types-pytz>=2022.2.1.0
pdm.termui:   types-aiofiles>=22.1.0
pdm.termui:   ruff>=0.0.239
pdm.termui:   types-redis>=4.5.1.4
pdm.termui:   amqp-mock>=0.4.0
pdm.termui:   mockupdb>=1.8.1
pdm.termui:   memray>=1.8.1
pdm.termui:   python>=3.11
pdm.termui:   Adding requirement sanic>=22.3.1
pdm.termui:   Adding requirement sanic-jwt>=1.7.0
pdm.termui:   Adding requirement bcrypt>=3.2.0
pdm.termui:   Adding requirement aiobotocore>=2.2.0
pdm.termui:   Adding requirement alembic>=1.7.7
pdm.termui:   Adding requirement psycopg2-binary>=2.9.3
pdm.termui:   Adding requirement aio-pika>=7.1.2
pdm.termui:   Adding requirement motor>=2.5.1
pdm.termui:   Adding requirement aiohttp>=3.8.1
pdm.termui:   Adding requirement pymongo>=3.12.3
pdm.termui:   Adding requirement typing-extensions>=4.2.0
pdm.termui:   Adding requirement py-zabbix>=1.1.7
pdm.termui:   Adding requirement psutil>=5.9.0
pdm.termui:   Adding requirement pytz>=2022.1
pdm.termui:   Adding requirement asn1>=2.5.0
pdm.termui:   Adding requirement ujson>=5.2.0
pdm.termui:   Adding requirement defusedxml>=0.7.1
pdm.termui:   Adding requirement ecpy>=1.2.5
pdm.termui:   Adding requirement sanic-ext>=22.3.0
pdm.termui:   Adding requirement pydantic>=1.9.0
pdm.termui:   Adding requirement tortoise-orm[asyncpg] @ git+https://github.com/tortoise/tortoise-orm.git@develop
pdm.termui:   Adding requirement httpx>=0.22.0
pdm.termui:   Adding requirement redis[hiredis]>=4.3.4
pdm.termui:   Adding requirement aiofiles>=22.1.0
pdm.termui:   Adding requirement aiokafka>=0.8.1
pdm.termui:   Adding requirement gps-events>=0.3.0
pdm.termui:   Adding requirement pytest>=7.1.1
pdm.termui:   Adding requirement coverage<6.4
pdm.termui:   Adding requirement coverage[toml]<6.4
pdm.termui:   Adding requirement pytest-cov>=3.0.0
pdm.termui:   Adding requirement blue>=0.8.0
pdm.termui:   Adding requirement mypy>=0.942
pdm.termui:   Adding requirement pytest-asyncio>=0.18.3
pdm.termui:   Adding requirement pytest-watch>=4.2.0
pdm.termui:   Adding requirement pytest-benchmark>=3.4.1
pdm.termui:   Adding requirement sanic-testing>=22.3.0
pdm.termui:   Adding requirement types-ujson>=5.5.0
pdm.termui:   Adding requirement types-pytz>=2022.2.1.0
pdm.termui:   Adding requirement types-aiofiles>=22.1.0
pdm.termui:   Adding requirement ruff>=0.0.239
pdm.termui:   Adding requirement types-redis>=4.5.1.4
pdm.termui:   Adding requirement amqp-mock>=0.4.0
pdm.termui:   Adding requirement mockupdb>=1.8.1
pdm.termui:   Adding requirement memray>=1.8.1
pdm.termui:   Adding requirement python>=3.11
pdm.termui: ======== Starting round 0 ========
unearth.vcs.git: Cloning https://github.com/tortoise/tortoise-orm.git (revision: develop) to /var/folders/6h/_gthf_zx42nfsbf3hdktfc7w0000gn/T/pdm-build-07axn8cw
unearth.vcs.git: Resolved https://github.com/tortoise/tortoise-orm.git to commit 0c81200bbaa3f407c5dce9e6ae34894899eef0dc
STATUS: Resolving: new pin python>=3.11
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
pdm.termui:   Adding requirement asyncpgNone(from tortoise-orm 0.20.0)
unearth.collector: Failed to collect links from https://***@gitlab.addsecure-st.com/api/v4/groups/371/-/packages/pypi/simple/asyncpgnone/: Client Error(404): Not Found
Traceback (most recent call last):
  File "/Users/pushupek/.local/bin/pdm", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/pushupek/Library/Application Support/pdm/venv/lib/python3.11/site-packages/pdm/core.py", line 290, in main
    return Core().main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pushupek/Library/Application Support/pdm/venv/lib/python3.11/site-packages/pdm/core.py", line 208, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/Users/pushupek/Library/Application Support/pdm/venv/lib/python3.11/site-packages/pdm/core.py", line 203, in main
    self.handle(project, options)
  File "/Users/pushupek/Library/Application Support/pdm/venv/lib/python3.11/site-packages/pdm/core.py", line 157, in handle
    command.handle(project, options)
  File "/Users/pushupek/Library/Application Support/pdm/venv/lib/python3.11/site-packages/pdm/cli/commands/add.py", line 67, in handle
    self.do_add(
  File "/Users/pushupek/Library/Application Support/pdm/venv/lib/python3.11/site-packages/pdm/cli/commands/add.py", line 159, in do_add
    resolved = do_lock(
               ^^^^^^^^
  File "/Users/pushupek/Library/Application Support/pdm/venv/lib/python3.11/site-packages/pdm/cli/actions.py", line 96, in do_lock
    mapping, dependencies = resolve(
                            ^^^^^^^^
  File "/Users/pushupek/Library/Application Support/pdm/venv/lib/python3.11/site-packages/pdm/resolver/core.py", line 36, in resolve
    result = resolver.resolve(requirements, max_rounds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pushupek/Library/Application Support/pdm/venv/lib/python3.11/site-packages/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pushupek/Library/Application Support/pdm/venv/lib/python3.11/site-packages/resolvelib/resolvers.py", line 427, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pushupek/Library/Application Support/pdm/venv/lib/python3.11/site-packages/resolvelib/resolvers.py", line 239, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pushupek/Library/Application Support/pdm/venv/lib/python3.11/site-packages/resolvelib/resolvers.py", line 230, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "/Users/pushupek/Library/Application Support/pdm/venv/lib/python3.11/site-packages/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "/Users/pushupek/Library/Application Support/pdm/venv/lib/python3.11/site-packages/resolvelib/structs.py", line 127, in __bool__
    next(iter(self))
  File "/Users/pushupek/Library/Application Support/pdm/venv/lib/python3.11/site-packages/pdm/resolver/providers.py", line 248, in matches_gen
    yield from super_find()
               ^^^^^^^^^^^^
  File "/Users/pushupek/Library/Application Support/pdm/venv/lib/python3.11/site-packages/pdm/resolver/providers.py", line 146, in matches_gen
    candidates = self._find_candidates(reqs[0])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pushupek/Library/Application Support/pdm/venv/lib/python3.11/site-packages/pdm/resolver/providers.py", line 125, in _find_candidates
    return self.repository.find_candidates(requirement, requirement.prerelease or self.allow_prereleases)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pushupek/Library/Application Support/pdm/venv/lib/python3.11/site-packages/pdm/models/repositories.py", line 154, in find_candidates
    cans = LazySequence(self._find_candidates(requirement))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pushupek/Library/Application Support/pdm/venv/lib/python3.11/site-packages/pdm/models/repositories.py", line 363, in _find_candidates
    raise CandidateNotFound(
pdm.exceptions.CandidateNotFound: Unable to find candidates for asyncpgNone. There may exist some issues with the package name or network condition.

```

**Comment by frostming** [comment]
Closed by #2135
