### ISSUE TITLE
Override of indirect dependency version breaks auto-sync

### ISSUE THREAD

**Issue by mikenerone** [pdm-project/pdm#2148]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

I've only seen this crop up with an override that affects an indirect dependency, so you need two sibling project directories to set this up. The specific dependencies I chose here are just examples - I've confirmed that the bug manifests in this situation with different dependencies. I've also confirmed that it happens when the interim dependency is coming from a package index instead of a local directory.

`dep-needing-old-urllib3/pyproject.toml`:
```toml
[project]
name = "dep-needing-old-urllib3"
version = "0.1.0"
description = ""
dependencies = [
    "urllib3==1.26.16",  # An intentionally older version of urllib3.
]
requires-python = ">=3.11"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
```

`proj-needing-dep/pyproject.toml`:
```toml
[project]
dependencies = [
    "dep-needing-old-urllib3 @ file:///${PROJECT_ROOT}/../dep-needing-old-urllib3",
]
requires-python = ">=3.11"

[tool.pdm.resolution.overrides]
urllib3 = ">=2.0.0"  # Note: an exact version specifier produces the bug, as well.
```
The `cd proj-needing-dep` and `pdm install` (which also creates `pdm.lock`).

That completes the setup. Here's the step that produces the error:
```shell
pdm add pycowsay
```
## Actual behavior
```
❯ pdm add -v pycowsay
Adding packages to default dependencies: pycowsay
STATUS: Resolving dependencies
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   dep-needing-old-urllib3 @ file:///${PROJECT_ROOT}/../dep-needing-old-urllib3
pdm.termui:   pycowsay
pdm.termui:   python>=3.11
pdm.termui:   Adding requirement dep-needing-old-urllib3 @ file:///${PROJECT_ROOT}/../dep-needing-old-urllib3
pdm.termui:   Adding requirement pycowsay
pdm.termui:   Adding requirement python>=3.11
pdm.termui: ======== Starting round 0 ========
unearth.preparer: The file /Users/mikenerone/w/dep-needing-old-urllib3 is a local directory, use it directly
STATUS: Resolving: new pin python>=3.11
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
pdm.termui:   Adding requirement urllib3==1.26.16(from dep-needing-old-urllib3 0.1.0)
STATUS: Resolving: new pin dep-needing-old-urllib3 0.1.0
pdm.termui: Pinning: dep-needing-old-urllib3 0.1.0
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
STATUS: Resolving: new pin pycowsay 0.0.0.1
pdm.termui: Pinning: pycowsay 0.0.0.1
pdm.termui: ======== Ending round 2 ========
pdm.termui: ======== Starting round 3 ========
STATUS: Resolving: new pin urllib3 2.0.4
pdm.termui: Pinning: urllib3 2.0.4
pdm.termui: ======== Ending round 3 ========
pdm.termui: ======== Starting round 4 ========
pdm.termui: ======== Resolution Result ========
pdm.termui: Stable pins:
pdm.termui:                    python None
pdm.termui:   dep-needing-old-urllib3 file:///Users/mikenerone/w/dep-needing-old-urllib3
pdm.termui:                  pycowsay 0.0.0.1
pdm.termui:                   urllib3 2.0.4
STATUS: Fetching hashes for resolved packages...
pdm.termui: Fetching hashes for pycowsay@0.0.0.1
🔒 Lock successful
Changes are written to pyproject.toml.
STATUS: Resolving packages from lockfile...
STATUS: Fetching hashes for resolved packages...
Synchronizing working set with lock file: 1 to add, 1 to update, 0 to remove

unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/ee/a6/8fb6d569c59e0e3622f10ae39594cbc57f8e5f36517291e221bd156002ef/pycowsay-0.0.0.1-py3-none-any.whl (from https://pypi.org/simple/pycowsay/)>
  ✔ Install pycowsay 0.0.0.1 successful
pdm.termui: Removing distribution urllib3
  ✖ Update urllib3 2.0.4 -> 2.0.4 failed
pdm.termui: Error occurs:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mikenerone/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/installers/synchronizers.py", line 298, in update_candidate
    self.manager.install(can)
  File "/Users/mikenerone/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/installers/manager.py", line 33, in install
    installer(str(prepared.build()), self.environment, prepared.direct_url())
                  ^^^^^^^^^^^^^^^^
  File "/Users/mikenerone/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/models/candidates.py", line 379, in build
    self.obtain(allow_all=False)
  File "/Users/mikenerone/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/models/candidates.py", line 420, in obtain
    raise CandidateNotFound(
pdm.exceptions.CandidateNotFound: No candidate is found for `urllib3` that matches the environment or hashes
Retry failed jobs
pdm.termui: Removing distribution None
  ✖ Update urllib3 None -> 2.0.4 failed
pdm.termui: Error occurs:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mikenerone/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/installers/synchronizers.py", line 298, in update_candidate
    self.manager.install(can)
  File "/Users/mikenerone/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/installers/manager.py", line 33, in install
    installer(str(prepared.build()), self.environment, prepared.direct_url())
                  ^^^^^^^^^^^^^^^^
  File "/Users/mikenerone/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/models/candidates.py", line 379, in build
    self.obtain(allow_all=False)
  File "/Users/mikenerone/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/models/candidates.py", line 420, in obtain
    raise CandidateNotFound(
pdm.exceptions.CandidateNotFound: No candidate is found for `urllib3` that matches the environment or hashes
Traceback (most recent call last):
  File "/Users/mikenerone/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/mikenerone/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 290, in main
    return Core().main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mikenerone/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 208, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/Users/mikenerone/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 203, in main
    self.handle(project, options)
  File "/Users/mikenerone/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 157, in handle
    command.handle(project, options)
  File "/Users/mikenerone/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/cli/commands/add.py", line 67, in handle
    self.do_add(
  File "/Users/mikenerone/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/cli/commands/add.py", line 178, in do_add
    do_sync(
  File "/Users/mikenerone/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/cli/actions.py", line 213, in do_sync
    synchronizer.synchronize()
  File "/Users/mikenerone/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/installers/synchronizers.py", line 445, in synchronize
    raise InstallationError("Some package operations are not complete yet")
pdm.exceptions.InstallationError: Some package operations are not complete yet
```
Note the two separate `✖ Update urllib3 ...` lines, both very strange, in the output. 

Fortunately, the lock file write actually succeeds, so the easy workaround is to simply `pdm sync` manually to correctly restore the package that got removed during the attempted automatic sync.

## Expected behavior
`urllib3==2.0.4` was already installed and shouldn't have been touched. The only action should have been `✔ Install pycowsay 0.0.0.1 successful` with no error.

## Environment Information

```bash
❯ pdm info
PDM version:
  2.8.1
Python Interpreter:
  /Users/mikenerone/w/proj-needing-dep/.venv/bin/python (3.11)
Project Root:
  /Users/mikenerone/w/proj-needing-dep
Local Packages:

❯ pdm info --env
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.4",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "22.5.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000",
  "python_full_version": "3.11.4",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
Already fixed on main
