### ISSUE TITLE
Removing dev dependency uninstall the project as well

### ISSUE THREAD

**Issue by g0di** [pdm-project/pdm#2150]
Hello,

I encountered a *weird* behavior recently while removing one of my project development dependency which actually also uninstalled/removed my project itself from the virtual environment. This caused my absolute imports to not working anymore, in particular for my unit tests.
>Note that I'm not 100% sure if this is a bug or an expected behavior. If it is, I could not find any related documentation

- [X ] I have searched the issue tracker and believe that this is not a duplicate.

### Create a new library project through `pdm init`. 
```bash
$ pdm init
Creating a pyproject.toml for PDM...
Please enter the Python interpreter to use
...
9. C:\Users\TBEBGOD\.pyenv\pyenv-win\versions\3.11.4\python.exe (3.11)
...
Please select (0): 9
Would you like to create a virtualenv with C:\Users\TBEBGOD\.pyenv\pyenv-win\versions\3.11.4\python.exe? [y/n] (y): y
Cleaning existing target directory C:\Users\TBEBGOD\Developement\tmp\.venv
Virtualenv is created successfully at C:\Users\TBEBGOD\Developement\tmp\.venv
Is the project a library that is installable?
If yes, we will need to ask a few more questions to include the project name and build backend [y/n] (n): y
Project name (tmp): my-project
Project version (0.1.0): 0.1.0
Project description (): 
Which build backend to use?
0. pdm-backend
1. setuptools
2. flit-core
3. hatchling
4. pdm-pep517
Please select (0): 0
License(SPDX name) (MIT): 
Author name (Benoit Godard): 
Author email (benoit.godard@some-mail.com): 
Python requires('*' to allow any) (>=3.11): 
Project is initialized successfully
```
### Add a prod and dev dependencies
```bash
$ pdm add flask
Adding packages to default dependencies: flask
  Lock successful
Changes are written to pyproject.toml.
Synchronizing working set with lock file: 6 to add, 0 to update, 0 to remove

  v Install itsdangerous 2.1.2 successful
  v Install flask 2.3.2 successful
  v Install blinker 1.6.2 successful
  v Install jinja2 3.1.2 successful
  v Install markupsafe 2.1.3 successful
  v Install werkzeug 2.3.6 successful
Installing the project as an editable package...
  v Install my-project 0.1.0 successful

  All complete!
```
>Notice the project itself has been installed `Installing the project as an editable package...  v Install my-project 0.1.0 successful`

```bash
$ pdm add -d black
Adding packages to dev dev-dependencies: black
  Lock successful
Changes are written to pyproject.toml.
Synchronizing working set with lock file: 5 to add, 0 to update, 0 to remove

  v Install mypy-extensions 1.0.0 successful
  v Install packaging 23.1 successful
  v Install black 23.7.0 successful
  v Install pathspec 0.11.2 successful
  v Install platformdirs 3.10.0 successful

  All complete!
```

### Uninstall a dev dependency
```bash
$ pdm remove -d black
Removing packages from dev dev-dependencies: black
Changes are written to pyproject.toml.
  Lock successful
Changes are written to pdm.lock.
Synchronizing working set with lock file: 0 to add, 0 to update, 6 to remove

  v Remove my-project 0.1.0+editable successful
  v Remove mypy-extensions 1.0.0 successful
  v Remove black 23.7.0 successful
  v Remove packaging 23.1 successful
  v Remove platformdirs 3.10.0 successful
  v Remove pathspec 0.11.2 successful

  All complete!
```
>Notice the uninstall the project itself `v Remove my-project 0.1.0+editable successful`

### Check you can import the project
```bash
$ pdm run python -c "import my_project"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'my_project'
```

## Actual behavior

Removing a development dependency from a project installed as an editable package cause the removal of the project itself from the virtual environment.  This cause the project to not be importable anymore and all absolute imports in the code to fail when running tests using a tool like pytest with src-layout.
>Note that this is not the case when removing a prod dependency.

## Expected behavior

I 'm expecting that the project itself is not uninstalled/removed from the virtual environment when removing a development dependency.

## Environment Information

```bash
PDM version:
  2.8.2
Python Interpreter:
  C:\Users\TBEBGOD\Developement\tmp\.venv\Scripts\python.exe (3.11)
Project Root:
  C:/Users/TBEBGOD/Developement/tmp
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.11.4",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19044",
  "python_full_version": "3.11.4",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "win32"
}
```

**Comment by drunkwcodes** [comment]
I removed `semantic-version` but `pdm` also remove other unrelated packages.

Can it adjust to only remove the specified package?

```
pdm remove semantic-version
Removing packages from default dependencies: semantic-version
Changes are written to pyproject.toml.
🔒 Lock successful                                                                                                                                        
Changes are written to pdm.lock.
Synchronizing working set with lock file: 16 to add, 1 to update, 7 to remove                                                                             

  ✔ Remove casefy 0.1.7 successful
  ✔ Remove pyserde 0.12.2 successful
  ✔ Remove semantic-version 2.10.0 successful
  ✔ Remove tomli-w 1.0.0 successful
  ✔ Remove mashumaro 3.9 successful
  ✔ Remove typing-inspect 0.9.0 successful
  ✔ Remove mups 0.1.0+editable successful
  ✔ Install mergedeep 1.3.4 successful
  ✔ Install ghp-import 2.1.0 successful
  ✔ Install mkdocs-material-extensions 1.1.1 successful
  ✔ Install markdown 3.4.4 successful
  ✔ Install mkdocs-autorefs 0.5.0 successful
  ✔ Install griffe 0.32.3 successful
  ✔ Update click-default-group 1.2.2 -> 1.2.4 successful
  ✔ Install mkdocstrings 0.22.0 successful
  ✔ Install python-dateutil 2.8.2 successful
  ✔ Install pyyaml-env-tag 0.1 successful
  ✔ Install mkdocs 1.5.2 successful
  ✔ Install mkdocstrings-python 1.3.0 successful
  ✔ Install pymdown-extensions 10.1 successful
  ✔ Install pyyaml 6.0.1 successful
  ✔ Install watchdog 3.0.0 successful
  ✔ Install regex 2023.8.8 successful
  ✔ Install mkdocs-material 9.1.21 successful
Installing the project as an editable package...
  ✔ Update mojo-muse 0.1.0+editable -> 0.1.0 successful

🎉 All complete!


```

**Comment by frostming** [comment]
> other unrelated packages

There shouldn't be unrelated packages from PDM's point of view. They should be specified in `pyproject.toml` and PDM won't remove them.

**Comment by drunkwcodes** [comment]
Ok. I got it. But I installed `mups` by this method.
https://github.com/drunkwcodes/mojopi

It didn't add in dependencies for me. What file path should I use to write toml by myself? Absolute path? Or path with `file://` scheme?

**Comment by frostming** [comment]
> Ok. I got it. But I installed `mups` by this method. https://github.com/drunkwcodes/mojopi
> 
> It didn't add in dependencies for me. What file path should I use to write toml by myself? Absolute path? Or path with `file://` scheme?

That is a weird setup, those two packages don't know each other. Why not install as a git dependency?

```
pdm add "mups @ ssh://git@github.com/drunkwcodes/mups.git"
```

This way the mups package and its dependencies will be locked

**Comment by drunkwcodes** [comment]
@frostming Thank you for your input. I appreciate your suggestion and I will definitely consider using it.

**Comment by drunkwcodes** [comment]
Oops.

I met a problem when using git dependency.

```
PS C:\Users\drunk\projects\mojopi> pdm add "mups @ ssh://git@github.com/drunkwcodes/mups.git" -v
Adding packages to default dependencies: mups @ ssh://git@github.com/drunkwcodes/mups.git
STATUS: Resolving dependencies
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   pytest>=7.3.1
pdm.termui:   pylint>=2.17.4
pdm.termui:   black[jupyter]>=23.7.0
pdm.termui:   ipython>=8.14.0
pdm.termui:   requests>=2.31.0
pdm.termui:   requests-toolbelt>=1.0.0
pdm.termui:   towncrier>=23.6.0
pdm.termui:   coverage>=7.2.7
pdm.termui:   ruff>=0.0.282
pdm.termui:   flask>=2.3.2
pdm.termui:   flask-admin>=1.6.1
pdm.termui:   peewee>=3.16.2
pdm.termui:   wtf-peewee>=3.0.4
pdm.termui:   bcrypt>=4.0.1
pdm.termui:   flask-login>=0.6.2
pdm.termui:   tomlkit>=0.11.8
pdm.termui:   readme-renderer[md]>=40.0
pdm.termui:   resolvelib>=1.0.1
pdm.termui:   flask-restx>=1.1.0
pdm.termui:   jsonschema==4.17.3
pdm.termui:   mups @ ssh://git@github.com/drunkwcodes/mups.git
pdm.termui:   python>=3.9
pdm.termui:   Adding requirement pytest>=7.3.1
pdm.termui:   Adding requirement pylint>=2.17.4
pdm.termui:   Adding requirement black[jupyter]>=23.7.0
pdm.termui:   Adding requirement ipython>=8.14.0
pdm.termui:   Adding requirement requests>=2.31.0
pdm.termui:   Adding requirement requests-toolbelt>=1.0.0
pdm.termui:   Adding requirement towncrier>=23.6.0
pdm.termui:   Adding requirement coverage>=7.2.7
pdm.termui:   Adding requirement ruff>=0.0.282
pdm.termui:   Adding requirement flask>=2.3.2
pdm.termui:   Adding requirement flask-admin>=1.6.1
pdm.termui:   Adding requirement peewee>=3.16.2
pdm.termui:   Adding requirement wtf-peewee>=3.0.4
pdm.termui:   Adding requirement bcrypt>=4.0.1
pdm.termui:   Adding requirement flask-login>=0.6.2
pdm.termui:   Adding requirement tomlkit>=0.11.8
pdm.termui:   Adding requirement readme-renderer[md]>=40.0
pdm.termui:   Adding requirement resolvelib>=1.0.1
pdm.termui:   Adding requirement flask-restx>=1.1.0
pdm.termui:   Adding requirement jsonschema==4.17.3
pdm.termui:   Adding requirement mups @ ssh://git@github.com/drunkwcodes/mups.git
pdm.termui:   Adding requirement python>=3.9
pdm.termui: ======== Starting round 0 ========
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\drunk\AppData\Local\Programs\Python\Python311\Scripts\pdm.exe\__main__.py", line 7, in <module>
  File "C:\Users\drunk\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\core.py", line 290, in main
    return Core().main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drunk\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\core.py", line 208, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "C:\Users\drunk\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\core.py", line 203, in main
    self.handle(project, options)
  File "C:\Users\drunk\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\core.py", line 157, in handle
    command.handle(project, options)
  File "C:\Users\drunk\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\cli\commands\add.py", line 67, in handle
    self.do_add(
  File "C:\Users\drunk\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\cli\commands\add.py", line 159, in do_add
    resolved = do_lock(
               ^^^^^^^^
  File "C:\Users\drunk\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\cli\actions.py", line 96, in do_lock
    mapping, dependencies = resolve(
                            ^^^^^^^^
  File "C:\Users\drunk\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\resolver\core.py", line 36, in resolve
    result = resolver.resolve(requirements, max_rounds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drunk\AppData\Local\Programs\Python\Python311\Lib\site-packages\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drunk\AppData\Local\Programs\Python\Python311\Lib\site-packages\resolvelib\resolvers.py", line 426, in resolve
    name = min(unsatisfied_names, key=self._get_preference)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drunk\AppData\Local\Programs\Python\Python311\Lib\site-packages\resolvelib\resolvers.py", line 203, in _get_preference
    return self._p.get_preference(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drunk\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\resolver\providers.py", line 86, in get_preference
    is_backtrack_cause = any(dep.identify() in backtrack_identifiers for dep in self.get_dependencies(candidate))
                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drunk\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\resolver\providers.py", line 186, in get_dependencies
    deps, requires_python, _ = self.repository.get_dependencies(candidate)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drunk\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\models\repositories.py", line 85, in get_dependencies
    requirements, requires_python, summary = getter(candidate)
                                             ^^^^^^^^^^^^^^^^^
  File "C:\Users\drunk\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\models\repositories.py", line 44, in wrapper
    result = func(self, candidate)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drunk\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\models\repositories.py", line 219, in _get_dependencies_from_metadata
    deps = prepared.get_dependencies_from_metadata()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drunk\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\models\candidates.py", line 578, in get_dependencies_from_metadata   
    self.req.project_name, self.metadata.requires or [], extras  # type: ignore[arg-type]
                           ^^^^^^^^^^^^^
  File "C:\Users\drunk\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\models\candidates.py", line 564, in metadata
    result = self.prepare_metadata()
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drunk\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\models\candidates.py", line 466, in prepare_metadata
    self._unpack(validate_hashes=False)
  File "C:\Users\drunk\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\models\candidates.py", line 445, in _unpack
    result = finder.download_and_unpack(self.link, build_dir, download_dir, hash_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drunk\AppData\Local\Programs\Python\Python311\Lib\site-packages\unearth\finder.py", line 408, in download_and_unpack
    file = unpack_link(
           ^^^^^^^^^^^^
  File "C:\Users\drunk\AppData\Local\Programs\Python\Python311\Lib\site-packages\unearth\preparer.py", line 300, in unpack_link
    resp = session.get(link.normalized, stream=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drunk\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drunk\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drunk\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 697, in send
    adapter = self.get_adapter(url=request.url)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drunk\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 794, in get_adapter
    raise InvalidSchema(f"No connection adapters were found for {url!r}")
requests.exceptions.InvalidSchema: No connection adapters were found for 'ssh://github.com/drunkwcodes/mups.git'
```

**Comment by frostming** [comment]
Oh, the url is missing the `git+` part, fixed my last comment

**Comment by drunkwcodes** [comment]
@frostming Thanks. It works. I updated my `pyproject.toml` and README.

**Comment by drunkwcodes** [comment]
Oh boy, the installation failed in my github workflow.
The unearth vcs module will crash in the [workflow](https://github.com/drunkwcodes/mojopi/actions/runs/5915007688/job/16040856779)!

```
Retry failed jobs
  ✖ Install mups 0.1.0 failed

ERRORS:
add mups failed:
See /tmp/pdm-install-k1zn23_0.log for detailed debug log.
[InstallationError]: Some package operations are not complete yet
Traceback (most recent call last):
  File 
"/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/concurrent/futures/threa
d.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File 
"/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/pdm/instal
lers/synchronizers.py", line 277, in install_candidate
    self.manager.install(can)
  File 
"/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/pdm/instal
lers/manager.py", line 33, in install
    installer(str(prepared.build()), self.environment, prepared.direct_url())
  File 
"/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/pdm/models
/candidates.py", line 379, in build
    self.obtain(allow_all=False)
  File 
"/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/pdm/models
/candidates.py", line 431, in obtain
    self._unpack(validate_hashes=not allow_all)
  File 
"/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/pdm/models
/candidates.py", line 445, in _unpack
    result = finder.download_and_unpack(self.link, build_dir, download_dir, 
hash_options)
  File 
"/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/unearth/fi
nder.py", line 408, in download_and_unpack
    file = unpack_link(
  File 
"/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/unearth/pr
eparer.py", line 283, in unpack_link
    backend.fetch(link, location)
  File 
"/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/unearth/vc
s/base.py", line 145, in fetch
    return self.fetch_new(location, url, rev, args)
  File 
"/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/unearth/vc
s/git.py", line 50, in fetch_new
    self.run_command(
  File 
"/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/unearth/vc
s/base.py", line 78, in run_command
    raise UnpackError(e.output) from None
unearth.errors.UnpackError: git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by frostming** [comment]
Do you configure the git pubkey in CI? Or change it to http URL:

```
mups @ git+https://github.com/drunkwcodes/mups.git
```

**Comment by drunkwcodes** [comment]
@frostming I can not configure the git ssh key in CI. So I change protocol to http. Then it works. Thanks.
If you can configure the git ssh key in CI, please teach me.
