### ISSUE TITLE
Can not initialize a PDM project with `--copier`

### ISSUE THREAD

**Issue by g0di** [pdm-project/pdm#2177]
- [X ] I have searched the issue tracker and believe that this is not a duplicate.

Lastly I wanted to initialize a PDM project using a `copier` template, unfortunately it did  not went as expected

## Steps to reproduce

- Get PDM installed
- Add `copier`, `pdm self add copier`
- Create a new project to init in, `mkdir my-project && cd my-project`
- Init a project using `copier` with the command shown on the documentation `pdm init --copier gh:pawamoy/copier-pdm`

## Actual behavior

The last commands exit with non zero error code and no project is initialized
```
$ pdm init -v --copier gh:pawamoy/copier-pdm
Creating a pyproject.toml for PDM...
Unknown sub-command 'C:\Users\TBEBGOD\Developement\tmp'
------
copier-pdm 8.1.0

Create a new project from a template.

Docs in https://copier.readthedocs.io/

WARNING! Use only trusted project templates, as they might execute code with the same level of access as your user.


Usage:
    copier-pdm [SWITCHES] [SUBCOMMAND [SWITCHES]] args...

Hidden-switches:
    -h, --help         Prints this help message and quits
    --help-all         Prints help messages of all sub-commands and quits
    -v, --version      Prints the program's version and quits

Sub-commands:
    copy               Copy from a template source to a destination.; see 'copier-pdm copy --help' for more info
    recopy             Recopy a subproject from its original template; see 'copier-pdm recopy --help' for more info
    update             Update a subproject from its original template; see 'copier-pdm update --help' for more info
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\TBEBGOD\.local\bin\pdm.exe\__main__.py", line 7, in <module>
  File "C:\Users\TBEBGOD\.local\pipx\venvs\pdm\Lib\site-packages\pdm\core.py", line 290, in main
    return Core().main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TBEBGOD\.local\pipx\venvs\pdm\Lib\site-packages\pdm\core.py", line 208, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "C:\Users\TBEBGOD\.local\pipx\venvs\pdm\Lib\site-packages\pdm\core.py", line 203, in main
    self.handle(project, options)
  File "C:\Users\TBEBGOD\.local\pipx\venvs\pdm\Lib\site-packages\pdm\core.py", line 157, in handle
    command.handle(project, options)
  File "C:\Users\TBEBGOD\.local\pipx\venvs\pdm\Lib\site-packages\pdm\cli\commands\init.py", line 243, in handle
    self.do_init(project, options=options)
  File "C:\Users\TBEBGOD\.local\pipx\venvs\pdm\Lib\site-packages\pdm\cli\commands\init.py", line 33, in do_init
    self._init_copier(project, options)
  File "C:\Users\TBEBGOD\.local\pipx\venvs\pdm\Lib\site-packages\pdm\cli\commands\init.py", line 53, in _init_copier
    raise RuntimeError("Copier exited with non-zero status code")
RuntimeError: Copier exited with non-zero status code
```
>Note that the folder `C:\Users\TBEBGOD\Developement\tmp` refers to the one from which I ran the command

Fun fact, I firstly tried to run the following
```
$ pdm init --copier gh:pawamoy/copier-pdm -v
Creating a pyproject.toml for PDM...
copier-pdm 8.1.0
Project is initialized successfully
```

As you can see, passing the `-v` flag after `--copier` made the command succeeded, however, it actually did nothing (my directory was still empty)

## Expected behavior

Initializing a PDM project through `copier` properly copy and initializes the specified template in the current directory

## Environment Information

```bash
$ pdm info --global && pdm info --env --global
PDM version:
  2.8.2
Python Interpreter:
  C:\Users\TBEBGOD\.pyenv\pyenv-win\versions\3.11.4\python3.exe (3.11)
Project Root:
  C:/Users/TBEBGOD/AppData/Local/pdm/pdm/global-project
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.11.4",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19044",
  "python_full_version": "3.11.4",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "win32"
}
```
>Note I passed `--global` flag because there is obviously no PDM project ATM

As the issue might come from compatibility reasons between pdm and copier, here is the version of copier I used
```bash
$ pdm self list | grep copier
Installed packages:
copier                 8.1.0       A library for rendering project templates.
```

## Additional information
I've tried to downgrade copier from version 8 to 7 to check if this was an issue with latest copier version. It did not work as well but I got a different error this time

```bash
$ pdm self add "copier<8"
...
$ pdm init -v --copier gh:pawamoy/copier-pdm
Creating a pyproject.toml for PDM...
Updating is only supported in git-tracked subprojects.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\TBEBGOD\.local\bin\pdm.exe\__main__.py", line 7, in <module>
  File "C:\Users\TBEBGOD\.local\pipx\venvs\pdm\Lib\site-packages\pdm\core.py", line 290, in main
    return Core().main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TBEBGOD\.local\pipx\venvs\pdm\Lib\site-packages\pdm\core.py", line 208, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "C:\Users\TBEBGOD\.local\pipx\venvs\pdm\Lib\site-packages\pdm\core.py", line 203, in main
    self.handle(project, options)
  File "C:\Users\TBEBGOD\.local\pipx\venvs\pdm\Lib\site-packages\pdm\core.py", line 157, in handle
    command.handle(project, options)
  File "C:\Users\TBEBGOD\.local\pipx\venvs\pdm\Lib\site-packages\pdm\cli\commands\init.py", line 243, in handle
    self.do_init(project, options=options)
  File "C:\Users\TBEBGOD\.local\pipx\venvs\pdm\Lib\site-packages\pdm\cli\commands\init.py", line 33, in do_init
    self._init_copier(project, options)
  File "C:\Users\TBEBGOD\.local\pipx\venvs\pdm\Lib\site-packages\pdm\cli\commands\init.py", line 53, in _init_copier
    raise RuntimeError("Copier exited with non-zero status code")
RuntimeError: Copier exited with non-zero status code
```

**Comment by frostming** [comment]
The copier 8.0.0 has introduced some breaking change, will fix it.
