### ISSUE TITLE
build-requires: unrecognized build dependency (torch) when installing tinycudann

### ISSUE THREAD

**Issue by mjlbach** [pdm-project/pdm#2202]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

Note: this is related to https://github.com/pdm-project/pdm/issues/913, but I followed the instruction in https://github.com/pdm-project/pdm/issues/913#issuecomment-1041125497 and am still getting the issue:

## Steps to reproduce

1. Create the following pyproject.toml
```
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Michael Lingelbach", email = "redacted"},
]
dependencies = [
    "torch>=2.0.1",
    "tinycudann @ git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend", "torch>=1.13.1"]
build-backend = "pdm.backend"

[[tool.pdm.source]]
type = "find_links"
url = "https://download.pytorch.org/whl/cu118/torch_stable.html"
name = "torch"
```

2. `pdm install -v`

## Actual behavior

```
❯ pdm install -v
STATUS: Resolving packages from lockfile...
STATUS: Fetching hashes for resolved packages...
Synchronizing working set with lock file: 1 to add, 0 to update, 0 to remove

unearth.vcs.git: Cloning https://github.com/NVlabs/tiny-cuda-nn/ (revision: 6f018a9cd1b369bcb247e1d539968db8e48b2b3f) to /tmp/pdm-build-dewt4tec
unearth.vcs.git: Resolved https://github.com/NVlabs/tiny-cuda-nn/ to commit 6f018a9cd1b369bcb247e1d539968db8e48b2b3f
pdm.termui: Preparing isolated env for PEP 517 build...
pdm.termui: Saving wheel to cache: <Link git+https://github.com/NVlabs/tiny-cuda-nn/@6f018a9cd1b369bcb247e1d539968db8e48b2b3f (from None)>
pdm.termui: Running PEP 517 backend to build a wheel for <Link git+https://github.com/NVlabs/tiny-cuda-nn/@6f018a9cd1b369bcb247e1d539968db8e48b2b3f (from None)>
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   setuptools>=40.8.0
pdm.termui:   wheel
pdm.termui:   python>=3.10.12,<3.10.13
pdm.termui:   Adding requirement setuptools>=40.8.0
pdm.termui:   Adding requirement wheel
pdm.termui:   Adding requirement python>=3.10.12,<3.10.13
pdm.termui: ======== Starting round 0 ========
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
pdm.termui: Pinning: setuptools 68.1.2
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
pdm.termui: Pinning: wheel 0.41.2
pdm.termui: ======== Ending round 2 ========
pdm.termui: ======== Starting round 3 ========
pdm.termui: ======== Resolution Result ========
pdm.termui: Stable pins:
pdm.termui:       python None
pdm.termui:   setuptools 68.1.2
pdm.termui:        wheel 0.41.2
pdm.termui: Installing setuptools@68.1.2...
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/4f/ab/0bcfebdfc3bfa8554b2b2c97a555569c4c1ebc74ea288741ea8326c51906/setuptools-68.1.2-py3-none-any.whl (from https://pypi.org/simple/setuptools/)>
pdm.termui: Installing wheel@0.41.2...
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/b8/8b/31273bf66016be6ad22bb7345c37ff350276cfd46e389a0c2ac5da9d9073/wheel-0.41.2-py3-none-any.whl (from https://pypi.org/simple/wheel/)>
pdm.termui: Synchronization complete.
pdm.termui: <string>:5: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
pdm.termui: Traceback (most recent call last):
pdm.termui:   File "/home/michael/.local/share/pdm/venv/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
pdm.termui:     main()
pdm.termui:   File "/home/michael/.local/share/pdm/venv/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
pdm.termui:     json_out['return_val'] = hook(**hook_input['kwargs'])
pdm.termui:   File "/home/michael/.local/share/pdm/venv/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
pdm.termui:     return hook(config_settings)
pdm.termui:   File "/tmp/pdm-build-env-he4lxk8v-shared/lib/python3.10/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
pdm.termui:     return self._get_build_requires(config_settings, requirements=['wheel'])
pdm.termui:   File "/tmp/pdm-build-env-he4lxk8v-shared/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
pdm.termui:     self.run_setup()
pdm.termui:   File "/tmp/pdm-build-env-he4lxk8v-shared/lib/python3.10/site-packages/setuptools/build_meta.py", line 507, in run_setup
pdm.termui:     super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
pdm.termui:   File "/tmp/pdm-build-env-he4lxk8v-shared/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in run_setup
pdm.termui:     exec(code, locals())
pdm.termui:   File "<string>", line 9, in <module>
pdm.termui: ModuleNotFoundError: No module named 'torch'
  ✖ Install tinycudann 0.0.0 failed
pdm.termui: Error occurs:
Traceback (most recent call last):
  File "/home/michael/mambaforge/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/michael/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 277, in install_candidate
    self.manager.install(can)
  File "/home/michael/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/installers/manager.py", line 33, in install
    installer(str(prepared.build()), self.environment, prepared.direct_url())
  File "/home/michael/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/models/candidates.py", line 393, in build
    self.wheel = Path(builder.build(build_dir, metadata_directory=self._metadata_dir))
  File "/home/michael/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/builders/wheel.py", line 26, in build
    requires = self._hook.get_requires_for_build_wheel(config_settings)
  File "/home/michael/.local/share/pdm/venv/lib/python3.10/site-packages/pyproject_hooks/_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "/home/michael/.local/share/pdm/venv/lib/python3.10/site-packages/pyproject_hooks/_impl.py", line 311, in _call_hook
    self._subprocess_runner(
  File "/home/michael/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/builders/base.py", line 260, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
  File "/home/michael/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/builders/base.py", line 107, in log_subprocessor
    raise build_error(e) from None
pdm.exceptions.BuildError: Build backend raised error: Module 'torch' is missing, please make sure it is specified in the 'build-system.requires' section. If it is not possible, add it to the project and use '--no-isolation' option.
Showing the last 10 lines of the build output:
  File "/tmp/pdm-build-env-he4lxk8v-shared/lib/python3.10/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
  File "/tmp/pdm-build-env-he4lxk8v-shared/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
    self.run_setup()
  File "/tmp/pdm-build-env-he4lxk8v-shared/lib/python3.10/site-packages/setuptools/build_meta.py", line 507, in run_setup
    super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
  File "/tmp/pdm-build-env-he4lxk8v-shared/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in run_setup
    exec(code, locals())
  File "<string>", line 9, in <module>
ModuleNotFoundError: No module named 'torch'
Retry failed jobs
pdm.termui: Preparing isolated env for PEP 517 build...
pdm.termui: Saving wheel to cache: <Link git+https://github.com/NVlabs/tiny-cuda-nn/@6f018a9cd1b369bcb247e1d539968db8e48b2b3f (from None)>
pdm.termui: Running PEP 517 backend to build a wheel for <Link git+https://github.com/NVlabs/tiny-cuda-nn/@6f018a9cd1b369bcb247e1d539968db8e48b2b3f (from None)>
pdm.termui: <string>:5: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
pdm.termui: Traceback (most recent call last):
pdm.termui:   File "/home/michael/.local/share/pdm/venv/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
pdm.termui:     main()
pdm.termui:   File "/home/michael/.local/share/pdm/venv/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
pdm.termui:     json_out['return_val'] = hook(**hook_input['kwargs'])
pdm.termui:   File "/home/michael/.local/share/pdm/venv/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
pdm.termui:     return hook(config_settings)
pdm.termui:   File "/tmp/pdm-build-env-he4lxk8v-shared/lib/python3.10/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
pdm.termui:     return self._get_build_requires(config_settings, requirements=['wheel'])
pdm.termui:   File "/tmp/pdm-build-env-he4lxk8v-shared/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
pdm.termui:     self.run_setup()
pdm.termui:   File "/tmp/pdm-build-env-he4lxk8v-shared/lib/python3.10/site-packages/setuptools/build_meta.py", line 507, in run_setup
pdm.termui:     super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
pdm.termui:   File "/tmp/pdm-build-env-he4lxk8v-shared/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in run_setup
pdm.termui:     exec(code, locals())
pdm.termui:   File "<string>", line 9, in <module>
pdm.termui: ModuleNotFoundError: No module named 'torch'
  ✖ Install tinycudann 0.0.0 failed
pdm.termui: Error occurs:
Traceback (most recent call last):
  File "/home/michael/mambaforge/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/michael/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 277, in install_candidate
    self.manager.install(can)
  File "/home/michael/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/installers/manager.py", line 33, in install
    installer(str(prepared.build()), self.environment, prepared.direct_url())
  File "/home/michael/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/models/candidates.py", line 393, in build
    self.wheel = Path(builder.build(build_dir, metadata_directory=self._metadata_dir))
  File "/home/michael/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/builders/wheel.py", line 26, in build
    requires = self._hook.get_requires_for_build_wheel(config_settings)
  File "/home/michael/.local/share/pdm/venv/lib/python3.10/site-packages/pyproject_hooks/_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "/home/michael/.local/share/pdm/venv/lib/python3.10/site-packages/pyproject_hooks/_impl.py", line 311, in _call_hook
    self._subprocess_runner(
  File "/home/michael/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/builders/base.py", line 260, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
  File "/home/michael/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/builders/base.py", line 107, in log_subprocessor
    raise build_error(e) from None
pdm.exceptions.BuildError: Build backend raised error: Module 'torch' is missing, please make sure it is specified in the 'build-system.requires' section. If it is not possible, add it to the project and use '--no-isolation' option.
Showing the last 10 lines of the build output:
  File "/tmp/pdm-build-env-he4lxk8v-shared/lib/python3.10/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
  File "/tmp/pdm-build-env-he4lxk8v-shared/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
    self.run_setup()
  File "/tmp/pdm-build-env-he4lxk8v-shared/lib/python3.10/site-packages/setuptools/build_meta.py", line 507, in run_setup
    super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
  File "/tmp/pdm-build-env-he4lxk8v-shared/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in run_setup
    exec(code, locals())
  File "<string>", line 9, in <module>
ModuleNotFoundError: No module named 'torch'
Traceback (most recent call last):
  File "/home/michael/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/michael/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/core.py", line 290, in main
    return Core().main(args or sys.argv[1:])
  File "/home/michael/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/core.py", line 208, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/home/michael/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/core.py", line 203, in main
    self.handle(project, options)
  File "/home/michael/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/core.py", line 157, in handle
    command.handle(project, options)
  File "/home/michael/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/cli/commands/install.py", line 95, in handle
    actions.do_sync(
  File "/home/michael/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/cli/actions.py", line 213, in do_sync
    synchronizer.synchronize()
  File "/home/michael/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 445, in synchronize
    raise InstallationError("Some package operations are not complete yet")
pdm.exceptions.InstallationError: Some package operations are not complete yet
```

## Expected behavior

PDM should add torch during the build of tinycudann

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
❯ pdm info && pdm info --env
PDM version:
  2.8.2
Python Interpreter:
  /home/michael/Repositories/pdm-test/.venv/bin/python (3.10)
Project Root:
  /home/michael/Repositories/pdm-test
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.10.12",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.2.0-26-generic",
  "platform_system": "Linux",
  "platform_version": "#26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jul 13 16:27:29 UTC 2",
  "python_full_version": "3.10.12",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "linux"
}

```

**Comment by pawamoy** [comment]
Their Torch extension does not declare `torch` in `setup_requires` in setup.py. Please report this on their bugtracker.

Also, what have you tried exactly? You have to install Torch first in your environment, and then use something like this:

```
pdm add --no-isolation "tinycudann @ git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch"
```

**Comment by mjlbach** [comment]
Thanks @pawamoy, the thing I tried was following the suggestion in the error message.

```
pdm.exceptions.BuildError: Build backend raised error: Module 'torch' is missing, please make sure it is specified in the 'build-system.requires' section. If it is not possible, add it to the project and use '--no-isolation' option.
Showing the last 10 lines of the build output:
```

I'm aware of option 2, but should the first (adding torch to 'build-system.requires') option not be sufficient?

**Comment by pawamoy** [comment]
I see, thanks, the message can be confusing indeed: the packages you specify in your own `build-system.requires` section are used to build your own code, not your dependencies. The error message really means that Torch should be added to the `build-system.requires` section of tiny-cuda-nn itself. Since you cannot do that (unless you report the issue on their bugtracker so that it gets fixed), you **have** to rely on the `--no-isolation` option, unfortunately :confused:

**Comment by mjlbach** [comment]
Got it! I'll close the issue here, and report upstream. Thanks for walking me through it.
