### ISSUE TITLE
Install gevent v23.7.0 failed

### ISSUE THREAD

**Issue by XYenon** [pdm-project/pdm#2207]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

See also https://github.com/gevent/gevent/issues/1971

## Steps to reproduce

Install gevent v23.7.0.

## Actual behavior

```
unearth.preparer: Downloading <Link https://bytedpypi.byted.org/packages/pypi/gevent/gevent-23.7.0.tar.gz (from https://bytedpypi.byted.org/simple/gevent/)> (5.8 MB)
pdm.termui: Preparing isolated env for PEP 517 build...
pdm.termui: Saving wheel to cache: <Link https://bytedpypi.byted.org/packages/pypi/gevent/gevent-23.7.0.tar.gz (from https://bytedpypi.byted.org/simple/gevent/)>
pdm.termui: Running PEP 517 backend to build a wheel for <Link https://bytedpypi.byted.org/packages/pypi/gevent/gevent-23.7.0.tar.gz (from https://bytedpypi.byted.org/simple/gevent/)>
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   greenlet>=3.0a1; platform_python_implementation == "CPython"
pdm.termui:   setuptools>=40.8.0
pdm.termui:   cffi>=1.12.3; platform_python_implementation == "CPython"
pdm.termui:   Cython>=3.0b3
pdm.termui:   python>=3.10.12,<3.10.13
pdm.termui:   Adding requirement greenlet>=3.0a1; platform_python_implementation == "CPython"
pdm.termui:   Adding requirement setuptools>=40.8.0
pdm.termui:   Adding requirement cffi>=1.12.3; platform_python_implementation == "CPython"
pdm.termui:   Adding requirement Cython>=3.0b3
pdm.termui:   Adding requirement python>=3.10.12,<3.10.13
pdm.termui: ======== Starting round 0 ========
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
pdm.termui:   Adding requirement pycparser(from cffi 1.15.1)
pdm.termui: Pinning: cffi 1.15.1
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
pdm.termui: Pinning: Cython 3.0.2
pdm.termui: ======== Ending round 2 ========
pdm.termui: ======== Starting round 3 ========
pdm.termui: Pinning: greenlet 3.0.0a1
pdm.termui: ======== Ending round 3 ========
pdm.termui: ======== Starting round 4 ========
pdm.termui: Pinning: setuptools 68.1.2
pdm.termui: ======== Ending round 4 ========
pdm.termui: ======== Starting round 5 ========
pdm.termui: Pinning: pycparser 2.21
pdm.termui: ======== Ending round 5 ========
pdm.termui: ======== Starting round 6 ========
pdm.termui: ======== Resolution Result ========
pdm.termui: Stable pins:
pdm.termui:       python None
pdm.termui:         cffi 1.15.1
pdm.termui:       cython 3.0.2
pdm.termui:     greenlet 3.0.0a1
pdm.termui:   setuptools 68.1.2
pdm.termui:    pycparser 2.21
pdm.termui: Installing cffi@1.15.1...
unearth.preparer: Downloading <Link https://bytedpypi.byted.org/packages/pypi/cffi/cffi-1.15.1-cp310-cp310-macosx_10_9_x86_64.whl (from https://bytedpypi.byted.org/simple/cffi/)> (179 kB)
pdm.termui: Installing cython@3.0.2...
unearth.preparer: Downloading <Link https://bytedpypi.byted.org/packages/pypi/cython/Cython-3.0.2-cp310-cp310-macosx_10_9_x86_64.whl (from https://bytedpypi.byted.org/simple/cython/)> (3.1 MB)
pdm.termui: Installing greenlet@3.0.0a1...
unearth.preparer: Downloading <Link https://bytedpypi.byted.org/packages/pypi/greenlet/greenlet-3.0.0a1-cp310-cp310-macosx_11_0_x86_64.whl (from https://bytedpypi.byted.org/simple/greenlet/)> (238 kB)
  ✖ Install gevent 23.7.0 failed
pdm.termui: Error occurs:
Traceback (most recent call last):
  File "/nix/store/xv07imkf2h5ryyk1xaa89fqdy4q84791-python3-3.10.12/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/nix/store/gilr0rh2g42axsc4wp980kyvnxdsy194-pdm-2.8.2/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 277, in install_candidate
    self.manager.install(can)
  File "/nix/store/gilr0rh2g42axsc4wp980kyvnxdsy194-pdm-2.8.2/lib/python3.10/site-packages/pdm/installers/manager.py", line 33, in install
    installer(str(prepared.build()), self.environment, prepared.direct_url())
  File "/nix/store/gilr0rh2g42axsc4wp980kyvnxdsy194-pdm-2.8.2/lib/python3.10/site-packages/pdm/models/candidates.py", line 393, in build
    self.wheel = Path(builder.build(build_dir, metadata_directory=self._metadata_dir))
  File "/nix/store/gilr0rh2g42axsc4wp980kyvnxdsy194-pdm-2.8.2/lib/python3.10/site-packages/pdm/builders/wheel.py", line 25, in build
    self.install(self._requires, shared=True)
  File "/nix/store/gilr0rh2g42axsc4wp980kyvnxdsy194-pdm-2.8.2/lib/python3.10/site-packages/pdm/builders/base.py", line 297, in install
    install_requirements(missing, env)
  File "/nix/store/gilr0rh2g42axsc4wp980kyvnxdsy194-pdm-2.8.2/lib/python3.10/site-packages/pdm/installers/core.py", line 27, in install_requirements
    syncer.synchronize()
  File "/nix/store/gilr0rh2g42axsc4wp980kyvnxdsy194-pdm-2.8.2/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 248, in synchronize
    manager.install(can)
  File "/nix/store/gilr0rh2g42axsc4wp980kyvnxdsy194-pdm-2.8.2/lib/python3.10/site-packages/pdm/installers/manager.py", line 33, in install
    installer(str(prepared.build()), self.environment, prepared.direct_url())
  File "/nix/store/gilr0rh2g42axsc4wp980kyvnxdsy194-pdm-2.8.2/lib/python3.10/site-packages/pdm/installers/installers.py", line 174, in install_wheel
    _install_wheel(wheel=wheel, destination=destination, additional_metadata=additional_metadata)
  File "/nix/store/gilr0rh2g42axsc4wp980kyvnxdsy194-pdm-2.8.2/lib/python3.10/site-packages/pdm/installers/installers.py", line 270, in _install_wheel
    install(source, destination, additional_metadata=additional_metadata or {})
  File "/nix/store/54l0kikykhzkbcpvcsx5s0h9lhxp8vf9-python3.10-installer-0.7.0/lib/python3.10/site-packages/installer/_core.py", line 109, in install
    record = destination.write_file(
  File "/nix/store/54l0kikykhzkbcpvcsx5s0h9lhxp8vf9-python3.10-installer-0.7.0/lib/python3.10/site-packages/installer/destinations.py", line 207, in write_file
    return self.write_to_fs(scheme, path_, stream, is_executable)
  File "/nix/store/gilr0rh2g42axsc4wp980kyvnxdsy194-pdm-2.8.2/lib/python3.10/site-packages/pdm/installers/installers.py", line 146, in write_to_fs
    return super().write_to_fs(scheme, path, stream, is_executable)
  File "/nix/store/54l0kikykhzkbcpvcsx5s0h9lhxp8vf9-python3.10-installer-0.7.0/lib/python3.10/site-packages/installer/destinations.py", line 173, in write_to_fs
    with open(target_path, "wb") as f:
PermissionError: [Errno 13] Permission denied: '/nix/store/xv07imkf2h5ryyk1xaa89fqdy4q84791-python3-3.10.12/include/python3.10/greenlet.h'
```

## Expected behavior

Install successful.

## Environment Information

```
PDM version:
  2.8.2
Python Interpreter:
  /Users/username/PycharmProjects/project_name/.venv/bin/python (3.10)
Project Root:
  /Users/username/PycharmProjects/project_name
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.10.12",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "22.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64",
  "python_full_version": "3.10.12",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "darwin"
}
```

**Comment by pawamoy** [comment]
> PermissionError: [Errno 13] Permission denied: '/nix/store/xv07imkf2h5ryyk1xaa89fqdy4q84791-python3-3.10.12/include/python3.10/greenlet.h'

Looks like a permission issue on your system :confused: I don't know how nix works, but maybe you could try fixing permissions on `/nix/store/xv07imkf2h5ryyk1xaa89fqdy4q84791-python3-3.10.12/include/python3.10`?

**Comment by pawamoy** [comment]
Yeah that makes sense. Maybe it's a packaging error in gevent then :confused:

**Comment by XYenon** [comment]
> Yeah that makes sense. Maybe it's a packaging error in gevent then 😕

There is an issue in gevent https://github.com/gevent/gevent/issues/1971#issuecomment-1695552489, and they don't think this is a packaging error.

**Comment by frostming** [comment]
I guess you will encounter the same problem with pip. You need to deal with the file permission problem to make installers able to install things into. Even with a virtualenv, the header files will be installed into the host Python. Installers just respect the install scheme and won't setup an isolated folder for it.

**Comment by XYenon** [comment]
Yeah I found it just use a wheel `gevent-22.10.2-cp310-cp310-macosx_10_15_x86_64.whl` on 22.10.2, but 23.7.0 does not have a `-cp310-cp310-macosx_10_15_x86_64` wheel.
