### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by drunkwcodes** [pdm-project/pdm#2209]
- [v ] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

It's my teammate's error log, she used `pdm install -d -v` to install mojopi but failed with this error without clue.
I don't know which file can not be found.

```
Updating the lock file...
STATUS: Resolving dependencies
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   pytest>=7.3.1
pdm.termui:   pylint>=2.17.4
pdm.termui:   black[jupyter]>=23.7.0
pdm.termui:   ipython>=8.14.0
pdm.termui:   requests>=2.31.0
pdm.termui:   requests-toolbelt>=1.0.0
pdm.termui:   towncrier>=23.6.0
pdm.termui:   coverage>=7.2.7
pdm.termui:   ruff>=0.0.282
pdm.termui:   flask>=2.3.2
pdm.termui:   flask-admin>=1.6.1
pdm.termui:   peewee>=3.16.2
pdm.termui:   wtf-peewee>=3.0.4
pdm.termui:   bcrypt>=4.0.1
pdm.termui:   flask-login>=0.6.2
pdm.termui:   tomlkit>=0.11.8
pdm.termui:   readme-renderer[md]>=40.0
pdm.termui:   resolvelib>=1.0.1
pdm.termui:   flask-restx>=1.1.0
pdm.termui:   jsonschema==4.17.3
pdm.termui:   mups @ git+https://github.com/drunkwcodes/mojopi.git
pdm.termui:   python>=3.10
pdm.termui:   Adding requirement pytest>=7.3.1
pdm.termui:   Adding requirement pylint>=2.17.4
pdm.termui:   Adding requirement black[jupyter]>=23.7.0
pdm.termui:   Adding requirement ipython>=8.14.0
pdm.termui:   Adding requirement requests>=2.31.0
pdm.termui:   Adding requirement requests-toolbelt>=1.0.0
pdm.termui:   Adding requirement towncrier>=23.6.0
pdm.termui:   Adding requirement coverage>=7.2.7
pdm.termui:   Adding requirement ruff>=0.0.282
pdm.termui:   Adding requirement flask>=2.3.2
pdm.termui:   Adding requirement flask-admin>=1.6.1
pdm.termui:   Adding requirement peewee>=3.16.2
pdm.termui:   Adding requirement wtf-peewee>=3.0.4
pdm.termui:   Adding requirement bcrypt>=4.0.1
pdm.termui:   Adding requirement flask-login>=0.6.2
pdm.termui:   Adding requirement tomlkit>=0.11.8
pdm.termui:   Adding requirement readme-renderer[md]>=40.0
pdm.termui:   Adding requirement resolvelib>=1.0.1
pdm.termui:   Adding requirement flask-restx>=1.1.0
pdm.termui:   Adding requirement jsonschema==4.17.3
pdm.termui:   Adding requirement mups @ git+https://github.com/drunkwcodes/mojopi.git
pdm.termui:   Adding requirement python>=3.10
pdm.termui: ======== Starting round 0 ========
unearth.vcs.git: Cloning https://github.com/drunkwcodes/mojopi.git to C:\Users\88691\AppData\Local\Temp\pdm-build-4rho848q
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\88691\AppData\Local\Programs\Python\Python311\Scripts\pdm.exe\__main__.py", line 7, in <module>
  File "C:\Users\88691\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\core.py", line 290, in main
    return Core().main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\88691\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\core.py", line 208, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "C:\Users\88691\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\core.py", line 203, in main
    self.handle(project, options)
  File "C:\Users\88691\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\core.py", line 157, in handle
    command.handle(project, options)
  File "C:\Users\88691\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\cli\commands\install.py", line 85, in handle
    actions.do_lock(
  File "C:\Users\88691\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\cli\actions.py", line 96, in do_lock
    mapping, dependencies = resolve(
                            ^^^^^^^^
  File "C:\Users\88691\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\resolver\core.py", line 36, in resolve
    result = resolver.resolve(requirements, max_rounds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\88691\AppData\Local\Programs\Python\Python311\Lib\site-packages\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\88691\AppData\Local\Programs\Python\Python311\Lib\site-packages\resolvelib\resolvers.py", line 426, in resolve
    name = min(unsatisfied_names, key=self._get_preference)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\88691\AppData\Local\Programs\Python\Python311\Lib\site-packages\resolvelib\resolvers.py", line 203, in _get_preference
    return self._p.get_preference(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\88691\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\resolver\providers.py", line 86, in get_preference
    is_backtrack_cause = any(dep.identify() in backtrack_identifiers for dep in self.get_dependencies(candidate))
                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\88691\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\resolver\providers.py", line 186, in get_dependencies
    deps, requires_python, _ = self.repository.get_dependencies(candidate)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\88691\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\models\repositories.py", line 85, in get_dependencies
    requirements, requires_python, summary = getter(candidate)
                                             ^^^^^^^^^^^^^^^^^
  File "C:\Users\88691\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\models\repositories.py", line 44, in wrapper
    result = func(self, candidate)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\88691\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\models\repositories.py", line 219, in _get_dependencies_from_metadata
    deps = prepared.get_dependencies_from_metadata()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\88691\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\models\candidates.py", line 578, in get_dependencies_from_metadata
    self.req.project_name, self.metadata.requires or [], extras  # type: ignore[arg-type]
                           ^^^^^^^^^^^^^
  File "C:\Users\88691\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\models\candidates.py", line 564, in metadata
    result = self.prepare_metadata()
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\88691\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\models\candidates.py", line 466, in prepare_metadata
    self._unpack(validate_hashes=False)
  File "C:\Users\88691\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\models\candidates.py", line 445, in _unpack
    result = finder.download_and_unpack(self.link, build_dir, download_dir, hash_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\88691\AppData\Local\Programs\Python\Python311\Lib\site-packages\unearth\finder.py", line 408, in download_and_unpack
    file = unpack_link(
           ^^^^^^^^^^^^
  File "C:\Users\88691\AppData\Local\Programs\Python\Python311\Lib\site-packages\unearth\preparer.py", line 283, in unpack_link
    backend.fetch(link, location)
  File "C:\Users\88691\AppData\Local\Programs\Python\Python311\Lib\site-packages\unearth\vcs\base.py", line 145, in fetch
    return self.fetch_new(location, url, rev, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\88691\AppData\Local\Programs\Python\Python311\Lib\site-packages\unearth\vcs\git.py", line 46, in fetch_new
    if self.get_git_version() >= (2, 17):
       ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\88691\AppData\Local\Programs\Python\Python311\Lib\site-packages\unearth\vcs\git.py", line 22, in get_git_version
    result = self.run_command(["version"], stdout_only=True, log_output=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\88691\AppData\Local\Programs\Python\Python311\Lib\site-packages\unearth\vcs\base.py", line 64, in run_command
    result = subprocess.run(
             ^^^^^^^^^^^^^^^
  File "C:\Users\88691\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\88691\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\88691\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:

Win11
Python3.11
pdm 2.8.2

```

**Comment by drunkwcodes** [comment]
It seems that "git" is not installed.

Please clarify the error message.
