### ISSUE TITLE
"greater than or equal" version constraints fail if the lowest version number cannot be found

### ISSUE THREAD

**Issue by lazarillo** [pdm-project/pdm#2234]
- [ x ] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Create a `pyproject.toml` file that has a dependency upon a package with a minimum version that cannot be found.  Specifically, I had the following:

- A private repository where the lowest version on the repository was `1.6.0`
- A `pyproject.toml` file that specified that the version was `>=1.5.0`
  - Note that this is _greater than_ or equal to `1.5.0`, so `1.6.0` should have been fine.
  - We moved from one private host location to another, which is why version 1.5 was in the pyproject, but there was no 1.5 version.

Specific highlights from the `pyproject.toml`:

```toml
dependencies = ["faker>=18.6.2", "protobuf>=4.23.4", "phxprotobuf>=1.5.0"]
```
```toml
[[tool.pdm.source]]
name = "private"
url = "https://${PYTHON_REPO_USERNAME}:${PYTHON_REPO_PASSWORD}@<PRIVATE_REPO_REMOVED_FOR_SECURITY>/simple/"
```

where `phxprotobuf` lives on the private repo, but its lowest version is `1.6.0`.

## Actual behavior

The details are shown below, but in short, the package cannot be found.  For some reason, the error only shows that the package cannot be found on `"https://pypi.org/simple"`, so for a while I thought that it was a problem with the credentials.  However, I did several things to ensure that it was not the credentials, including being able to successfully `pip install` (in the proper virtual environment, using `python -m pip install phxprotobuf` after activating the environment).

It then occurred to me that maybe the problem was that it got stuck simply because it *could not find* version `1.5.0`, the lowest suggested version, so that it failed because it couldn't test whether `1.5.0` worked, so it didn't even try to see if any higher versions were available.

## Expected behavior

`pdm` and `unearth` should be able to continue to try other package versions when a specified version is simply not found at all, assuming that the other versions match the version range.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
pdm info
Inside an active virtualenv /home/mike-williamson/repos/phalanx/data/phxfakedata/.venv, reusing it.
Set env var PDM_IGNORE_ACTIVE_VENV to ignore it.
PDM version:
  2.9.1
Python Interpreter:
  /home/mike-williamson/repos/phalanx/data/phxfakedata/.venv/bin/python (3.8)
Project Root:
  /home/mike-williamson/repos/phalanx/data/phxfakedata
Local Packages:


pdm info --env
Inside an active virtualenv /home/mike-williamson/repos/phalanx/data/phxfakedata/.venv, reusing it.
Set env var PDM_IGNORE_ACTIVE_VENV to ignore it.
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.18",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.2.0-31-generic",
  "platform_system": "Linux",
  "platform_version": "#31~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Aug 16 13:45:26 UTC 2",
  "python_full_version": "3.8.18",
  "platform_python_implementation": "CPython",
  "python_version": "3.8",
  "sys_platform": "linux"
}
```

## Detailed output

```bash
m install -v
Lock file hash doesn't match pyproject.toml, packages may be outdated
Updating the lock file...
Inside an active virtualenv /home/mike-williamson/repos/phalanx/data/phxfakedata/.venv, reusing it.
Set env var PDM_IGNORE_ACTIVE_VENV to ignore it.
STATUS: Resolving dependencies
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   faker>=18.6.2
pdm.termui:   protobuf>=4.23.4
pdm.termui:   phxprotobuf>=1.5.0
pdm.termui:   Faker>=18.6.2
pdm.termui:   nox
pdm.termui:   pytest
pdm.termui:   hypothesis
pdm.termui:   ruff
pdm.termui:   python>=3.8
pdm.termui:   Adding requirement faker>=18.6.2
pdm.termui:   Adding requirement protobuf>=4.23.4
pdm.termui:   Adding requirement phxprotobuf>=1.5.0
pdm.termui:   Adding requirement Faker>=18.6.2
pdm.termui:   Adding requirement nox
pdm.termui:   Adding requirement pytest
pdm.termui:   Adding requirement hypothesis
pdm.termui:   Adding requirement ruff
pdm.termui:   Adding requirement python>=3.8
pdm.termui: ======== Starting round 0 ========
STATUS: Resolving: new pin python>=3.8
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
pdm.termui:   Adding requirement python-dateutil>=2.4(from faker 19.2.0)
pdm.termui:   Adding requirement typing-extensions>=3.10.0.1; python_version <= "3.8"(from faker 19.2.0)
STATUS: Resolving: new pin faker 19.2.0
pdm.termui: Pinning: faker 19.2.0
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
pdm.termui:   Adding requirement protobuf>=4.24.0(from phxprotobuf 1.5.0)
STATUS: Resolving: new pin phxprotobuf 1.5.0
pdm.termui: Pinning: phxprotobuf 1.5.0
pdm.termui: ======== Ending round 2 ========
pdm.termui: ======== Starting round 3 ========
STATUS: Resolving: new pin protobuf 4.24.0
pdm.termui: Pinning: protobuf 4.24.0
pdm.termui: ======== Ending round 3 ========
pdm.termui: ======== Starting round 4 ========
pdm.termui:   Adding requirement attrs>=19.2.0(from hypothesis 6.82.2)
pdm.termui:   Adding requirement sortedcontainers<3.0.0,>=2.1.0(from hypothesis 6.82.2)
pdm.termui:   Adding requirement exceptiongroup>=1.0.0; python_version < "3.11"(from hypothesis 6.82.2)
STATUS: Resolving: new pin hypothesis 6.82.2
pdm.termui: Pinning: hypothesis 6.82.2
pdm.termui: ======== Ending round 4 ========
pdm.termui: ======== Starting round 5 ========
pdm.termui:   Adding requirement argcomplete<4.0,>=1.9.4(from nox 2023.4.22)
pdm.termui:   Adding requirement colorlog<7.0.0,>=2.6.1(from nox 2023.4.22)
pdm.termui:   Adding requirement packaging>=20.9(from nox 2023.4.22)
pdm.termui:   Adding requirement virtualenv>=14(from nox 2023.4.22)
STATUS: Resolving: new pin nox 2023.4.22
pdm.termui: Pinning: nox 2023.4.22
pdm.termui: ======== Ending round 5 ========
pdm.termui: ======== Starting round 6 ========
pdm.termui:   Adding requirement iniconfig(from pytest 7.4.0)
pdm.termui:   Adding requirement packaging(from pytest 7.4.0)
pdm.termui:   Adding requirement pluggy<2.0,>=0.12(from pytest 7.4.0)
pdm.termui:   Adding requirement exceptiongroup>=1.0.0rc8; python_version < "3.11"(from pytest 7.4.0)
pdm.termui:   Adding requirement tomli>=1.0.0; python_version < "3.11"(from pytest 7.4.0)
pdm.termui:   Adding requirement colorama; sys_platform == "win32"(from pytest 7.4.0)
STATUS: Resolving: new pin pytest 7.4.0
pdm.termui: Pinning: pytest 7.4.0
pdm.termui: ======== Ending round 6 ========
pdm.termui: ======== Starting round 7 ========
STATUS: Resolving: new pin ruff 0.0.282
pdm.termui: Pinning: ruff 0.0.282
pdm.termui: ======== Ending round 7 ========
pdm.termui: ======== Starting round 8 ========
STATUS: Resolving: new pin argcomplete 3.1.1
pdm.termui: Pinning: argcomplete 3.1.1
pdm.termui: ======== Ending round 8 ========
pdm.termui: ======== Starting round 9 ========
pdm.termui:   Adding requirement colorama; sys_platform == "win32"(from colorlog 6.7.0)
STATUS: Resolving: new pin colorlog 6.7.0
pdm.termui: Pinning: colorlog 6.7.0
pdm.termui: ======== Ending round 9 ========
pdm.termui: ======== Starting round 10 ========
STATUS: Resolving: new pin exceptiongroup 1.1.1
pdm.termui: Pinning: exceptiongroup 1.1.1
pdm.termui: ======== Ending round 10 ========
pdm.termui: ======== Starting round 11 ========
STATUS: Resolving: new pin pluggy 1.0.0
pdm.termui: Pinning: pluggy 1.0.0
pdm.termui: ======== Ending round 11 ========
pdm.termui: ======== Starting round 12 ========
STATUS: Resolving: new pin sortedcontainers 2.4.0
pdm.termui: Pinning: sortedcontainers 2.4.0
pdm.termui: ======== Ending round 12 ========
pdm.termui: ======== Starting round 13 ========
STATUS: Resolving: new pin attrs 23.1.0
pdm.termui: Pinning: attrs 23.1.0
pdm.termui: ======== Ending round 13 ========
pdm.termui: ======== Starting round 14 ========
STATUS: Resolving: new pin packaging 23.1
pdm.termui: Pinning: packaging 23.1
pdm.termui: ======== Ending round 14 ========
pdm.termui: ======== Starting round 15 ========
pdm.termui:   Adding requirement six>=1.5(from python-dateutil 2.8.2)
STATUS: Resolving: new pin python-dateutil 2.8.2
pdm.termui: Pinning: python-dateutil 2.8.2
pdm.termui: ======== Ending round 15 ========
pdm.termui: ======== Starting round 16 ========
STATUS: Resolving: new pin tomli 2.0.1
pdm.termui: Pinning: tomli 2.0.1
pdm.termui: ======== Ending round 16 ========
pdm.termui: ======== Starting round 17 ========
STATUS: Resolving: new pin typing-extensions 4.7.1
pdm.termui: Pinning: typing-extensions 4.7.1
pdm.termui: ======== Ending round 17 ========
pdm.termui: ======== Starting round 18 ========
pdm.termui:   Adding requirement distlib<1,>=0.3.7(from virtualenv 20.24.2)
pdm.termui:   Adding requirement filelock<4,>=3.12.2(from virtualenv 20.24.2)
pdm.termui:   Adding requirement platformdirs<4,>=3.9.1(from virtualenv 20.24.2)
STATUS: Resolving: new pin virtualenv 20.24.2
pdm.termui: Pinning: virtualenv 20.24.2
pdm.termui: ======== Ending round 18 ========
pdm.termui: ======== Starting round 19 ========
STATUS: Resolving: new pin colorama 0.4.6
pdm.termui: Pinning: colorama 0.4.6
pdm.termui: ======== Ending round 19 ========
pdm.termui: ======== Starting round 20 ========
STATUS: Resolving: new pin iniconfig 2.0.0
pdm.termui: Pinning: iniconfig 2.0.0
pdm.termui: ======== Ending round 20 ========
pdm.termui: ======== Starting round 21 ========
STATUS: Resolving: new pin distlib 0.3.7
pdm.termui: Pinning: distlib 0.3.7
pdm.termui: ======== Ending round 21 ========
pdm.termui: ======== Starting round 22 ========
STATUS: Resolving: new pin filelock 3.12.2
pdm.termui: Pinning: filelock 3.12.2
pdm.termui: ======== Ending round 22 ========
pdm.termui: ======== Starting round 23 ========
STATUS: Resolving: new pin platformdirs 3.10.0
pdm.termui: Pinning: platformdirs 3.10.0
pdm.termui: ======== Ending round 23 ========
pdm.termui: ======== Starting round 24 ========
STATUS: Resolving: new pin six 1.16.0
pdm.termui: Pinning: six 1.16.0
pdm.termui: ======== Ending round 24 ========
pdm.termui: ======== Starting round 25 ========
pdm.termui: ======== Resolution Result ========
pdm.termui: Stable pins:
pdm.termui:              python None
pdm.termui:               faker 19.2.0
pdm.termui:         phxprotobuf 1.5.0
pdm.termui:            protobuf 4.24.0
pdm.termui:          hypothesis 6.82.2
pdm.termui:                 nox 2023.4.22
pdm.termui:              pytest 7.4.0
pdm.termui:                ruff 0.0.282
pdm.termui:         argcomplete 3.1.1
pdm.termui:            colorlog 6.7.0
pdm.termui:      exceptiongroup 1.1.1
pdm.termui:              pluggy 1.0.0
pdm.termui:    sortedcontainers 2.4.0
pdm.termui:               attrs 23.1.0
pdm.termui:           packaging 23.1
pdm.termui:     python-dateutil 2.8.2
pdm.termui:               tomli 2.0.1
pdm.termui:   typing-extensions 4.7.1
pdm.termui:          virtualenv 20.24.2
pdm.termui:            colorama 0.4.6
pdm.termui:           iniconfig 2.0.0
pdm.termui:             distlib 0.3.7
pdm.termui:            filelock 3.12.2
pdm.termui:        platformdirs 3.10.0
pdm.termui:                 six 1.16.0
STATUS: Fetching hashes for resolved packages...
unearth.collector: Failed to collect links from https://pypi.org/simple/phxprotobuf/: Client Error(404): Not Found
🔒 Lock successful
Changes are written to pdm.lock.
STATUS: Resolving packages from lockfile...
STATUS: Fetching hashes for resolved packages...
unearth.preparer: The file . is a local directory, use it directly
Synchronizing working set with lock file: 1 to add, 0 to update, 0 to remove

unearth.collector: Failed to collect links from https://pypi.org/simple/phxprotobuf/: Client Error(404): Not Found
  ✖ Install phxprotobuf 1.5.0 failed
pdm.termui: Error occurs: 
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/mike-williamson/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 283, in install_candidate
    self.manager.install(can)
  File "/home/mike-williamson/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/installers/manager.py", line 33, in install
    installer(str(prepared.build()), self.environment, prepared.direct_url())
  File "/home/mike-williamson/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/models/candidates.py", line 381, in build
    self.obtain(allow_all=False)
  File "/home/mike-williamson/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/models/candidates.py", line 422, in obtain
    raise CandidateNotFound(
pdm.exceptions.CandidateNotFound: No candidate is found for `phxprotobuf` that matches the environment or hashes
Retry failed jobs
unearth.collector: Failed to collect links from https://pypi.org/simple/phxprotobuf/: Client Error(404): Not Found
  ✖ Install phxprotobuf 1.5.0 failed
pdm.termui: Error occurs: 
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/mike-williamson/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 283, in install_candidate
    self.manager.install(can)
  File "/home/mike-williamson/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/installers/manager.py", line 33, in install
    installer(str(prepared.build()), self.environment, prepared.direct_url())
  File "/home/mike-williamson/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/models/candidates.py", line 381, in build
    self.obtain(allow_all=False)
  File "/home/mike-williamson/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/models/candidates.py", line 422, in obtain
    raise CandidateNotFound(
pdm.exceptions.CandidateNotFound: No candidate is found for `phxprotobuf` that matches the environment or hashes
Traceback (most recent call last):
  File "/home/mike-williamson/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/mike-williamson/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/core.py", line 290, in main
    return Core().main(args or sys.argv[1:])
  File "/home/mike-williamson/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/core.py", line 208, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/home/mike-williamson/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/core.py", line 203, in main
    self.handle(project, options)
  File "/home/mike-williamson/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/core.py", line 157, in handle
    command.handle(project, options)
  File "/home/mike-williamson/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/cli/commands/install.py", line 95, in handle
    actions.do_sync(
  File "/home/mike-williamson/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/cli/actions.py", line 213, in do_sync
    synchronizer.synchronize()
  File "/home/mike-williamson/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 451, in synchronize
    raise InstallationError("Some package operations are not complete yet")
pdm.exceptions.InstallationError: Some package operations are not complete yet
```

## Assistance

I'm happy to help fork and solve this, but before I start I would just like to know:
1. The proper place to do it.  I'm assuming that `unearth` is actually the right place.
2. If the work is appreciated... maybe the complication in solving for this corner case is not worth it, and I'd rather not do the work if it will not be merged in.

**Comment by frostming** [comment]
The problem is `1.5.0` is pinned in your lockfile and PDM will try to reuse it but find it not existing at all.

You need to update the pins by `pdm update`

**Comment by lazarillo** [comment]
OK, thanks!
