### ISSUE TITLE
Import error when PDM creates virtual environments

### ISSUE THREAD

**Issue by justinmayer** [pdm-project/pdm#2235]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

```
$ git clone git@github.com:pelican-plugins/mau-reader.git
$ cd mau-reader

$ pdm install -v 

STATUS: Resolving packages from lockfile...
python.use_venv is on, creating a virtualenv for this project...
Run command: ['/Users/myuser/.local/pipx/venvs/pdm/bin/python', '-m', 'virtualenv',
'/Users/myuser/Projects/pelican-plugins/mau-reader/.venv', '-p',
'/Users/myuser/.asdf/installs/python/3.11.5/bin/python', '--prompt=mau-reader-3.11',
'--no-pip', '--no-setuptools', '--no-wheel']
created virtual environment CPython3.11.5.final.0-64 in 26ms
  creator CPython3Posix(dest=/Users/myuser/Projects/pelican-plugins/mau-reader/.venv, clear=False, no_vcs_ignore=False, global=False)
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
Virtualenv is created successfully at /Users/myuser/Projects/pelican-plugins/mau-reader/.venv
STATUS: Fetching hashes for resolved packages...
unearth.preparer: The file . is a local directory, use it directly
Synchronizing working set with lock file: 34 to add, 0 to update, 0 to remove

unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/0d/f1/5f39e771cd730d347539bb74c6d496737b9d5f0a53bc9fdbf3e170f1ee48/blinker-1.6.2-py3-none-any.whl (from https://pypi.org/simple/blinker/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/ef/a6/62565a6e1cf69e10f5727360368e451d4b7f58beeac6173dc9db836a5b46/iniconfig-2.0.0-py3-none-any.whl (from https://pypi.org/simple/iniconfig/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/57/f4/a69c20ee4f660081a7dedb1ac57f29be9378e04edfcb90c526b923d4bebc/beautifulsoup4-4.12.2-py3-none-any.whl (from https://pypi.org/simple/beautifulsoup4/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/bd/a1/b7b1711d9bf43c3795366431633ab6ba6942744243aad809272ebfa59b39/feedgenerator-2.1.0-py3-none-any.whl (from https://pypi.org/simple/feedgenerator/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/26/87/f238c0670b94533ac0353a4e2a1a771a0cc73277b88bff23d3ae35a256c1/docutils-0.20.1-py3-none-any.whl (from https://pypi.org/simple/docutils/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/00/2e/d53fa4befbf2cfa713304affc7ca780ce4fc1fd8710527771b58311a3229/click-8.1.7-py3-none-any.whl (from https://pypi.org/simple/click/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/56/61/0bc551ef5e4cd459c34e769969b080d667ea9b2b3265819d4ae1f8d07702/coverage-7.3.0-cp311-cp311-macosx_11_0_arm64.whl (from https://pypi.org/simple/coverage/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/ca/4e/6d625c4030280d7c8b17e014ad6a6ba434acd8c6bd86d8f375d6a1235dfe/black-23.7.0-cp311-cp311-macosx_10_16_universal2.whl (from https://pypi.org/simple/black/)>
  ✔ Install blinker 1.6.2 successful
  ✔ Install iniconfig 2.0.0 successful
  ✔ Install feedgenerator 2.1.0 successful
  ✔ Install click 8.1.7 successful
  ✔ Install beautifulsoup4 4.12.2 successful
  ✔ Install coverage 7.3.0 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/bc/c3/f068337a370801f372f2f8f6bad74a5c140f6fda3d9de154052708dd3c65/Jinja2-3.1.2-py3-none-any.whl (from https://pypi.org/simple/jinja2/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/0a/66/7f8c48009c72d73bc6bbe6eb87ac838d6a526146f7dab14af671121eb379/invoke-2.2.0-py3-none-any.whl (from https://pypi.org/simple/invoke/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/1a/b5/228c1cdcfe138f1a8e01ab1b54284c8b83735476cb22b6ba251656ed13ad/Markdown-3.4.4-py3-none-any.whl (from https://pypi.org/simple/markdown/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/42/d7/1ec15b46af6af88f19b8e5ffea08fa375d433c998b8a7639e76935c14f1f/markdown_it_py-3.0.0-py3-none-any.whl (from https://pypi.org/simple/markdown-it-py/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/fe/09/c31503cb8150cf688c1534a7135cc39bb9092f8e0e6369ec73494d16ee0e/MarkupSafe-2.1.3-cp311-cp311-macosx_10_9_universal2.whl (from https://pypi.org/simple/markupsafe/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/6b/54/708ed319ff349c34d7370c0edb584dfe6b52ad7b648353878ae68bf92481/mau-2.0.3-py2.py3-none-any.whl (from https://pypi.org/simple/mau/)>
  ✔ Install jinja2 3.1.2 successful
  ✔ Install markupsafe 2.1.3 successful
  ✔ Install markdown 3.4.4 successful
  ✔ Install docutils 0.20.1 successful
  ✔ Install mau 2.0.3 successful
  ✔ Install invoke 2.2.0 successful
  ✔ Install markdown-it-py 3.0.0 successful
  ✔ Install black 23.7.0 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/b3/38/89ba8ad64ae25be8de66a6d463314cf1eb366222074cfda9ee839c56a4b4/mdurl-0.1.2-py3-none-any.whl (from https://pypi.org/simple/mdurl/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/2a/e2/5d3f6ada4297caebe1a2add3b126fe800c96f56dbe5d1988a2cbe0b267aa/mypy_extensions-1.0.0-py3-none-any.whl (from https://pypi.org/simple/mypy-extensions/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/ab/c3/57f0601a2d4fe15de7a553c00adbc901425661bf048f2a22dfc500caf121/packaging-23.1-py3-none-any.whl (from https://pypi.org/simple/packaging/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/b4/2a/9b1be29146139ef459188f5e420a66e835dda921208db600b7037093891f/pathspec-0.11.2-py3-none-any.whl (from https://pypi.org/simple/pathspec/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/fc/51/b9a57e22a033a9cef7f6aae8b90adb2957d45c7fa1121d9962b42320c048/pelican-4.8.0-py3-none-any.whl (from https://pypi.org/simple/pelican/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/05/b8/42ed91898d4784546c5f06c60506400548db3f7a4b3fb441cba4e5c17952/pluggy-1.3.0-py3-none-any.whl (from https://pypi.org/simple/pluggy/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/14/51/fe5a0d6ea589f0d4a1b97824fb518962ad48b27cd346dcdfa2405187997a/platformdirs-3.10.0-py3-none-any.whl (from https://pypi.org/simple/platformdirs/)>
  ✔ Install mdurl 0.1.2 successful
  ✔ Install mypy-extensions 1.0.0 successful
  ✔ Install pathspec 0.11.2 successful
  ✔ Install packaging 23.1 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/43/88/29adf0b44ba6ac85045e63734ae0997d3c58d8b1a91c914d240828d0d73d/Pygments-2.16.1-py3-none-any.whl (from https://pypi.org/simple/pygments/)>
  ✔ Install pluggy 1.3.0 successful
  ✔ Install platformdirs 3.10.0 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/a7/4b/8b78d126e275efa2379b1c2e09dc52cf70df16fc3b90613ef82531499d73/pytest_cov-4.1.0-py3-none-any.whl (from https://pypi.org/simple/pytest-cov/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/78/af/1a79db43409ea8569a8a91d0a87db4445c7de4cefcf6141e9a5c77dda2d6/pytest-7.4.1-py3-none-any.whl (from https://pypi.org/simple/pytest/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/36/7a/87837f39d0296e723bb9b62bbb257d0355c7f6128853c78955f57342a56d/python_dateutil-2.8.2-py2.py3-none-any.whl (from https://pypi.org/simple/python-dateutil/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/c7/b2/8f5d346c86e690c58da3b21b7c14d656b4100606abed8e91a98e8b50f3bf/pytest_sugar-0.9.7-py2.py3-none-any.whl (from https://pypi.org/simple/pytest-sugar/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/28/09/55f715ddbf95a054b764b547f617e22f1d5e45d83905660e9a088078fe67/PyYAML-6.0.1-cp311-cp311-macosx_11_0_arm64.whl (from https://pypi.org/simple/pyyaml/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/32/4d/aaf7eff5deb402fd9a24a1449a8119f00d74ae9c2efa79f8ef9994261fc2/pytz-2023.3.post1-py2.py3-none-any.whl (from https://pypi.org/simple/pytz/)>
  ✔ Install pytest-sugar 0.9.7 successful
  ✔ Install pytest-cov 4.1.0 successful
  ✔ Install python-dateutil 2.8.2 successful
  ✔ Install pyyaml 6.0.1 successful
  ✔ Install pytest 7.4.1 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/8d/5f/21a93b2ec205f4b79853ff6e838e3c99064d5dbe85ec6b05967506f14af0/rich-13.5.2-py3-none-any.whl (from https://pypi.org/simple/rich/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl (from https://pypi.org/simple/six/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/4c/f3/038b302fdfbe3be7da016777069f26ceefe11a681055ea1f7817546508e3/soupsieve-2.5-py3-none-any.whl (from https://pypi.org/simple/soupsieve/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/52/c4/0dd703ccd8934d941cdd93974234c615ec6dd56f7653ba9c63c577a75bd3/ruff-0.0.287-py3-none-macosx_10_9_x86_64.macosx_11_0_arm64.macosx_10_9_universal2.whl (from https://pypi.org/simple/ruff/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/67/e1/434566ffce04448192369c1a282931cf4ae593e91907558eaecd2e9f2801/termcolor-2.3.0-py3-none-any.whl (from https://pypi.org/simple/termcolor/)>
  ✔ Install six 1.16.0 successful
  ✔ Install soupsieve 2.5 successful
  ✔ Install termcolor 2.3.0 successful
  ✔ Install rich 13.5.2 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/be/ea/90e14e807da5a39e5b16789acacd48d63ca3e4f23dfa964a840eeadebb13/Unidecode-1.3.6-py3-none-any.whl (from https://pypi.org/simple/unidecode/)>
  ✔ Install pygments 2.16.1 successful
  ✔ Install pelican 4.8.0 successful
  ✔ Install unidecode 1.3.6 successful
  ✔ Install pytz 2023.3.post1 successful
  ✔ Install ruff 0.0.287 successful
Installing the project as an editable package...
pdm.termui: Preparing isolated env for PEP 517 build...
pdm.termui: Running PEP 517 backend to build a wheel for <Link file:///Users/myuser/Projects/pelican-plugins/mau-reader (from None)>
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   hatchling
pdm.termui:   python>=3.11.5,<3.11.6
pdm.termui:   Adding requirement hatchling
pdm.termui:   Adding requirement python>=3.11.5,<3.11.6
pdm.termui: ======== Starting round 0 ========
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
pdm.termui:   Adding requirement editables>=0.3(from hatchling 1.18.0)
pdm.termui:   Adding requirement packaging>=21.3(from hatchling 1.18.0)
pdm.termui:   Adding requirement pathspec>=0.10.1(from hatchling 1.18.0)
pdm.termui:   Adding requirement pluggy>=1.0.0(from hatchling 1.18.0)
pdm.termui:   Adding requirement trove-classifiers(from hatchling 1.18.0)
pdm.termui: Pinning: hatchling 1.18.0
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
pdm.termui: Pinning: editables 0.5
pdm.termui: ======== Ending round 2 ========
pdm.termui: ======== Starting round 3 ========
pdm.termui: Pinning: packaging 23.1
pdm.termui: ======== Ending round 3 ========
pdm.termui: ======== Starting round 4 ========
pdm.termui: Pinning: pathspec 0.11.2
pdm.termui: ======== Ending round 4 ========
pdm.termui: ======== Starting round 5 ========
pdm.termui: Pinning: pluggy 1.3.0
pdm.termui: ======== Ending round 5 ========
pdm.termui: ======== Starting round 6 ========
pdm.termui: Pinning: trove-classifiers 2023.8.7
pdm.termui: ======== Ending round 6 ========
pdm.termui: ======== Starting round 7 ========
pdm.termui: ======== Resolution Result ========
pdm.termui: Stable pins:
pdm.termui:              python None
pdm.termui:           hatchling 1.18.0
pdm.termui:           editables 0.5
pdm.termui:           packaging 23.1
pdm.termui:            pathspec 0.11.2
pdm.termui:              pluggy 1.3.0
pdm.termui:   trove-classifiers 2023.8.7
pdm.termui: Installing editables@0.5...
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/6b/be/0f2f4a5e8adc114a02b63d92bf8edbfa24db6fc602fca83c885af2479e0e/editables-0.5-py3-none-any.whl (from https://pypi.org/simple/editables/)>
pdm.termui: Installing hatchling@1.18.0...
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/76/56/8ccca673e2c896931722f876bf040c0b6a7d8c1a128be60516a8a55bb27a/hatchling-1.18.0-py3-none-any.whl (from https://pypi.org/simple/hatchling/)>
pdm.termui: Installing packaging@23.1...
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/ab/c3/57f0601a2d4fe15de7a553c00adbc901425661bf048f2a22dfc500caf121/packaging-23.1-py3-none-any.whl (from https://pypi.org/simple/packaging/)>
pdm.termui: Installing pathspec@0.11.2...
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/b4/2a/9b1be29146139ef459188f5e420a66e835dda921208db600b7037093891f/pathspec-0.11.2-py3-none-any.whl (from https://pypi.org/simple/pathspec/)>
pdm.termui: Installing pluggy@1.3.0...
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/05/b8/42ed91898d4784546c5f06c60506400548db3f7a4b3fb441cba4e5c17952/pluggy-1.3.0-py3-none-any.whl (from https://pypi.org/simple/pluggy/)>
pdm.termui: Installing trove-classifiers@2023.8.7...
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/14/c6/35e478a586e857c2a6d31fc7b1586d4ff965f729a290552b5c2eb7b9f807/trove_classifiers-2023.8.7-py3-none-any.whl (from https://pypi.org/simple/trove-classifiers/)>
pdm.termui: Synchronization complete.
  ✔ Install pelican-mau-reader 2.0.0 successful

🎉 All complete!

$ pdm -v run python

>>> from mau import Mau
```

## Actual behavior

```
>>> from mau import Mau
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/myuser/Projects/pelican-plugins/mau-reader/.venv/lib/python3.11/site-packages/mau/__init__.py", line 2, in <module>
    from pkg_resources import DistributionNotFound, get_distribution
ModuleNotFoundError: No module named 'pkg_resources'
```

## Expected behavior

I expected to be able to import the module successfully.

I tried to use the following to switch PDM's virtual environment creation to utilize the `venv` module, but that that had no effect (same import error):

    $ pdm config venv.backend venv

## Workaround

I can work around this problem by first manually creating and activating a virtual environment, either via `virtualenv` or via the `venv` module, and then running the same steps-to-reproduce above, which now complete successfully:

```
$ python -m venv .venv
$ source .venv/bin/activate
$ pdm install -v

[… same output as above …]

$ pdm -v run python

Python 3.11.5 (main, Aug 25 2023, 14:27:17) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from mau import Mau
>>>
```

As seen above, in this case the import completes successfully.

## Test Failure Caused by Same Issue in CI

You can see the same problem cause the tests to fail (i.e., cannot import the module) in a GitHub action here: https://github.com/pelican-plugins/mau-reader/actions/runs/6084230942/job/16505736603?pr=29#step:5:45

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:

$ pdm info && pdm info --env
python.use_venv is on, creating a virtualenv for this project...
Virtualenv is created successfully at /Users/myuser/Projects/pelican-plugins/mau-reader/.venv
PDM version:
  2.9.1
Python Interpreter:
  /Users/myuser/Projects/pelican-plugins/mau-reader/.venv/bin/python (3.11)
Project Root:
  /Users/myuser/Projects/pelican-plugins/mau-reader
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.11.5",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "22.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023;
root:xnu-8796.141.3~6/RELEASE_ARM64_T6000",
  "python_full_version": "3.11.5",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "darwin"
}
```

**Comment by justinmayer** [comment]
Thanks for the quick response, Frost. Could you elaborate why `pkg_resources` / `pdm add setuptools` is required with the PDM flow when `python -m venv .venv && source .venv/bin/activate` does not require such a step?

**Comment by frostming** [comment]
python venv by default provides an environment with pip and setuptools installed in it while PDM disables it intentionally to prevent users from rely on them: every module used by your code must be listed as an explicit dependency.

**Comment by frostming** [comment]
You can see the command used by PDM to create a venv in the log output 
```
Run command: ['/Users/myuser/.local/pipx/venvs/pdm/bin/python', '-m', 'virtualenv',
'/Users/myuser/Projects/pelican-plugins/mau-reader/.venv', '-p',
'/Users/myuser/.asdf/installs/python/3.11.5/bin/python', '--prompt=mau-reader-3.11',
'--no-pip', '--no-setuptools', '--no-wheel']
```

**Comment by justinmayer** [comment]
Hey Frost. I just wanted to pass on a belated thank-you for responding to this issue so quickly and for providing a thorough explanation to a situation that had me very confused. I really appreciate it! 🥰

**Comment by frostming** [comment]
by the way Python 3.12 no longer provisions setuptools in a new venv

**Comment by justinmayer** [comment]
Good point. Thank you for reminding me! 💫
