### ISSUE TITLE
 pdm install --no-lock fails in the absence of lock file

### ISSUE THREAD

**Issue by deronnax** [pdm-project/pdm#2245]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

`rm pdm.lock`
`pdm install --no-lock -v`

## Actual behavior

```
$ rm pdm.lock
$ pdm install --no-lock -v
Lock file does not exist
STATUS: Resolving packages from lockfile...
Traceback (most recent call last):
  File "/Users/mathieu/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/mathieu/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 290, in main
    return Core().main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mathieu/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 208, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/Users/mathieu/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 203, in main
    self.handle(project, options)
  File "/Users/mathieu/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 157, in handle
    command.handle(project, options)
  File "/Users/mathieu/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/cli/commands/install.py", line 95, in handle
    actions.do_sync(
  File "/Users/mathieu/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/cli/actions.py", line 197, in do_sync
    candidates = resolve_candidates_from_lockfile(project, requirements)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mathieu/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/cli/actions.py", line 140, in resolve_candidates_from_lockfile
    mapping, *_ = resolve(
                  ^^^^^^^^
  File "/Users/mathieu/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/resolver/core.py", line 36, in resolve
    result = resolver.resolve(requirements, max_rounds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mathieu/.local/pipx/venvs/pdm/lib/python3.11/site-packages/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mathieu/.local/pipx/venvs/pdm/lib/python3.11/site-packages/resolvelib/resolvers.py", line 399, in resolve
    raise ResolutionImpossible(e.criterion.information)
resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=NamedRequirement(name='jinja2', marker=None, extras=set(), specifier=<SpecifierSet('')>, editable=False, prerelease=False), parent=None)]
```

## Expected behavior

install succeeds

## Environment Information

```
 pdm info ; pdm info --env
PDM version:
  2.9.1
Python Interpreter:
  /Users/mathieu/.pyenv/versions/3.10.12/bin/python3 (3.10)
Project Root:
  /Users/mathieu/dev/ggcore
Local Packages:
  /Users/mathieu/dev/ggcore/__pypackages__/3.10
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.12",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "22.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 22.6.0: Wed Jul  5 22:17:35 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8112",
  "python_full_version": "3.10.12",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "darwin"
}

```

**Comment by pawamoy** [comment]
`--no-lock` means don't generate/update a lock file before installing. Of course if there's no lock file it will fail. What else would you expect? :/

**Comment by deronnax** [comment]
No, that's not what it means. The `pdm install --help` about `--no-lock` is clear:
```
  --no-lock             Don't do lock if the lock file is not found or outdated
```

**Comment by pawamoy** [comment]
Well yes.

- you removed the lock file
- you run `pdm install --no-lock`
- lock file is not found
- so PDM does not lock
- so PDM can't install

PDM needs a lock file to install dependencies.

**Comment by frostming** [comment]
Oh, I almost forget there's a such option, i can't remember what the use case it's for.

**Comment by frostming** [comment]
it's looks pretty like pdm sync, maybe we should remove the option.

**Comment by pawamoy** [comment]
Hmmm I definitely don't think `--no-lock` should be removed. The use-case is clear: don't re-lock even if pyproject.toml changed. This allows faster build of Docker images for example. It gives users the choice of *when* to re-lock.

**Comment by deronnax** [comment]
OK I won't lose any more time arguing.
@frostming would you be interested implementing it? We would definitely use it (I am sure other would too).

**Comment by deronnax** [comment]
Awesome, thank you so, so much. Could we have a release for this fix 🙏  ?
