### ISSUE TITLE
Installing packages on external ExFAT SSD throws [UnicodeDecodeError]: 'utf-8' codec can't decode byte 0xb0 in position 37:  invalid start byte

### ISSUE THREAD

**Issue by keysmusician** [pdm-project/pdm#2255]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

`brew install pdm`

CD to a file on an external ExFAT SSD

`pdm init`

`pdm add <package name>`

## Actual behavior

Packages fail to install with `UnicodeDecodeError`.

```
% pdm add numpy -v
Adding packages to default dependencies: numpy
STATUS: Resolving dependencies
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   numpy
pdm.termui:   python>=3.11
pdm.termui:   Adding requirement numpy
pdm.termui:   Adding requirement python>=3.11
pdm.termui: ======== Starting round 0 ========
STATUS: Resolving: new pin python>=3.11
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
STATUS: Resolving: new pin numpy 1.25.2
pdm.termui: Pinning: numpy 1.25.2
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
pdm.termui: ======== Resolution Result ========
pdm.termui: Stable pins:
pdm.termui:   python None
pdm.termui:    numpy 1.25.2
STATUS: Fetching hashes for resolved packages...
pdm.termui: Fetching hashes for numpy@1.25.2
🔒 Lock successful
Changes are written to pyproject.toml.
STATUS: Resolving packages from lockfile...
STATUS: Fetching hashes for resolved packages...
Traceback (most recent call last):
  File "/opt/homebrew/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.9.2/libexec/lib/python3.11/site-packages/pdm/core.py", line 290, in main
    return Core().main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.9.2/libexec/lib/python3.11/site-packages/pdm/core.py", line 208, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/opt/homebrew/Cellar/pdm/2.9.2/libexec/lib/python3.11/site-packages/pdm/core.py", line 203, in main
    self.handle(project, options)
  File "/opt/homebrew/Cellar/pdm/2.9.2/libexec/lib/python3.11/site-packages/pdm/core.py", line 157, in handle
    command.handle(project, options)
  File "/opt/homebrew/Cellar/pdm/2.9.2/libexec/lib/python3.11/site-packages/pdm/cli/commands/add.py", line 69, in handle
    self.do_add(
  File "/opt/homebrew/Cellar/pdm/2.9.2/libexec/lib/python3.11/site-packages/pdm/cli/commands/add.py", line 180, in do_add
    do_sync(
  File "/opt/homebrew/Cellar/pdm/2.9.2/libexec/lib/python3.11/site-packages/pdm/cli/actions.py", line 201, in do_sync
    synchronizer = project.core.synchronizer_class(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.9.2/libexec/lib/python3.11/site-packages/pdm/installers/synchronizers.py", line 131, in __init__
    self.working_set = environment.get_working_set()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.9.2/libexec/lib/python3.11/site-packages/pdm/environments/base.py", line 171, in get_working_set
    return WorkingSet([paths["platlib"], paths["purelib"]])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.9.2/libexec/lib/python3.11/site-packages/pdm/models/working_set.py", line 69, in __init__
    self._dist_map = {
                     ^
  File "/opt/homebrew/Cellar/pdm/2.9.2/libexec/lib/python3.11/site-packages/pdm/models/working_set.py", line 72, in <dictcomp>
    if dist.metadata["Name"]
       ^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/metadata/__init__.py", line 615, in metadata
    or self.read_text('')
       ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/metadata/__init__.py", line 938, in read_text
    return self._path.joinpath(filename).read_text(encoding='utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pathlib.py", line 1059, in read_text
    return f.read()
           ^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte
```

Interestingly, if I `pdm init; pdm add six`, it installs successfully. If I then install `numpy` it fails, and if I install `numpy` first, installing `six` afterwards fails.

Installing packages to a project on my internal drive succeeds.

## Expected behavior

Packages should install successfully.

## Environment Information

```bash
PDM version:
  2.9.2
Python Interpreter:
  /Volumes/T7/Code/.venv/bin/python (3.11)
Project Root:
  /Volumes/T7/Code
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.5",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "22.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:52 PDT 
2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8103",
  "python_full_version": "3.11.5",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
Please follow the error traceback and check if `numpy-*.dist-info/METADATA` is UTF-8 decodable.

**Comment by keysmusician** [comment]
> Please follow the error traceback and check if `numpy-*.dist-info/METADATA` is UTF-8 decodable.

What do you mean, where would I find that file?

**Comment by frostming** [comment]
> What do you mean, where would I find that file?

Just located at `.venv/lib/python3.11/site-packages/numpy-1.25.2.dist-info/METADATA`

**Comment by keysmusician** [comment]
Okay, well apparently I had deleted the old files, so I did `pdm init` and `pdm add numpy` again and got a slightly different traceback (in fact, I had seen a traceback like this before I saw the one I posted about):
```bash
% pdm add numpy -v
Adding packages to default dependencies: numpy
STATUS: Resolving dependencies
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   numpy
pdm.termui:   python>=3.11
pdm.termui:   Adding requirement numpy
pdm.termui:   Adding requirement python>=3.11
pdm.termui: ======== Starting round 0 ========
STATUS: Resolving: new pin python>=3.11
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
STATUS: Resolving: new pin numpy 1.25.2
pdm.termui: Pinning: numpy 1.25.2
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
pdm.termui: ======== Resolution Result ========
pdm.termui: Stable pins:
pdm.termui:   python None
pdm.termui:    numpy 1.25.2
STATUS: Fetching hashes for resolved packages...
pdm.termui: Fetching hashes for numpy@1.25.2
🔒 Lock successful
Changes are written to pyproject.toml.
STATUS: Resolving packages from lockfile...
STATUS: Fetching hashes for resolved packages...
Fatal Python error: init_import_site: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 980, in exec_module
  File "<frozen site>", line 616, in <module>
  File "<frozen site>", line 599, in main
  File "<frozen site>", line 531, in venv
  File "<frozen site>", line 384, in addsitepackages
  File "<frozen site>", line 226, in addsitedir
  File "<frozen site>", line 179, in addpackage
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte
Traceback (most recent call last):
  File "/opt/homebrew/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.9.2/libexec/lib/python3.11/site-packages/pdm/core.py", line 290, in main
    return Core().main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.9.2/libexec/lib/python3.11/site-packages/pdm/core.py", line 208, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/opt/homebrew/Cellar/pdm/2.9.2/libexec/lib/python3.11/site-packages/pdm/core.py", line 203, in main
    self.handle(project, options)
  File "/opt/homebrew/Cellar/pdm/2.9.2/libexec/lib/python3.11/site-packages/pdm/core.py", line 157, in handle
    command.handle(project, options)
  File "/opt/homebrew/Cellar/pdm/2.9.2/libexec/lib/python3.11/site-packages/pdm/cli/commands/add.py", line 69, in handle
    self.do_add(
  File "/opt/homebrew/Cellar/pdm/2.9.2/libexec/lib/python3.11/site-packages/pdm/cli/commands/add.py", line 180, in do_add
    do_sync(
  File "/opt/homebrew/Cellar/pdm/2.9.2/libexec/lib/python3.11/site-packages/pdm/cli/actions.py", line 201, in do_sync
    synchronizer = project.core.synchronizer_class(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.9.2/libexec/lib/python3.11/site-packages/pdm/installers/synchronizers.py", line 131, in __init__
    self.working_set = environment.get_working_set()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.9.2/libexec/lib/python3.11/site-packages/pdm/environments/python.py", line 46, in get_working_set
    scheme = self.get_paths()
             ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.9.2/libexec/lib/python3.11/site-packages/pdm/environments/python.py", line 29, in get_paths
    paths = get_sys_config_paths(str(self.interpreter.executable), replace_vars, kind=kind)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.9.2/libexec/lib/python3.11/site-packages/pdm/models/in_process/__init__.py", line 38, in get_sys_config_paths
    return json.loads(subprocess.check_output(cmd, env=env))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Volumes/T7/Code/pdmtest/.venv/bin/python', '-Es', '/opt/homebrew/Cellar/pdm/2.9.2/libexec/lib/python3.11/site-packages/pdm/models/in_process/sysconfig_get_paths.py', 'default']' returned non-zero exit status 1.
```

All I have in site-packages is:
```bash
ls -a .venv/lib/python3.11/site-packages
.                       ..                      .__virtualenv.pth       .__virtualenv.py        _virtualenv.pth         _virtualenv.py
```

However, I just discovered this:
```bash
% /Volumes/T7/Code/pdmtest/.venv/bin/python
Fatal Python error: init_import_site: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 980, in exec_module
  File "<frozen site>", line 616, in <module>
  File "<frozen site>", line 599, in main
  File "<frozen site>", line 531, in venv
  File "<frozen site>", line 384, in addsitepackages
  File "<frozen site>", line 226, in addsitedir
  File "<frozen site>", line 179, in addpackage
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte
```

**Comment by frostming** [comment]
Is that reproducible with virtualenv? `virtualenv --clear /Volumes/T7/Code/pdmtest/.venv/ && /Volumes/T7/Code/pdmtest/.venv/bin/python`?

**Comment by keysmusician** [comment]
```zsh
% virtualenv --clear /Volumes/T7/Code/pdmtest/.venv/ && /Volumes/T7/Code/pdmtest/.venv/bin/python
zsh: command not found: virtualenv
```
Shall I `pip install virtualenv`?

**Comment by frostming** [comment]
Use it from pdm, replace: `virtualenv -> /opt/homebrew/Cellar/pdm/2.9.2/libexec/bin/virtualenv`

**Comment by keysmusician** [comment]
```zsh
% /opt/homebrew/Cellar/pdm/2.9.2/libexec/bin/virtualenv --clear /Volumes/T7/Code/pdmtest/.venv/ && /Volumes/T7/Code/pdmtest/.venv/bin/python
created virtual environment CPython3.11.5.final.0-64 in 3184ms
  creator CPython3macOsBrew(dest=/Volumes/T7/Code/pdmtest/.venv, clear=True, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/justinmasayda/Library/Application Support/virtualenv)
    added seed packages: ._pip==23.2.1, ._setuptools==68.2.0, ._wheel==0.41.2, pip==23.2.1, setuptools==68.2.0, wheel==0.41.2
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
Fatal Python error: init_import_site: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 980, in exec_module
  File "<frozen site>", line 616, in <module>
  File "<frozen site>", line 599, in main
  File "<frozen site>", line 531, in venv
  File "<frozen site>", line 384, in addsitepackages
  File "<frozen site>", line 226, in addsitedir
  File "<frozen site>", line 179, in addpackage
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte
```

**Comment by frostming** [comment]
PDM can't do anything here.
