### ISSUE TITLE
Can't override URL-based requirement with a local editable requirement

### ISSUE THREAD

**Issue by datalogics-kam** [pdm-project/pdm#2256]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Add a package via a URL, then try to add a local development dependency. Something like this

```shell
pdm add "git+ssh://git@github.com/datalogics-kam/dl-cdk-lib.git@make-dl-cdk-lib"
pdm add --dev -e ../dl-cdk-lib
```

## Actual behavior

Log with `-v`:

```
❯ pdm add --dev -e ../dl-cdk-lib -v
Adding group dev to lockfile
Adding packages to dev dev-dependencies: -e file:///${PROJECT_ROOT}/../dl-cdk-lib#egg=dl-cdk-lib
The saved Python interpreter doesn't match the project's requirement. Trying to find another one.
python.use_venv is on, creating a virtualenv for this project...
Run command: ['/Users/kam/.local/pipx/venvs/pdm/bin/python', '-m', 'virtualenv', '/Users/kam/src/dl/cdk_workshop/.venv', '-p', '/Users/kam/.pyenv/versions/3.11.2/bin/python3', '--prompt=cdk_workshop-3.11', '--no-pip', '--no-setuptools', '--no-wheel']
created virtual environment CPython3.11.2.final.0-64 in 43ms
  creator CPython3Posix(dest=/Users/kam/src/dl/cdk_workshop/.venv, clear=False, no_vcs_ignore=False, global=False)
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
Virtualenv is created successfully at /Users/kam/src/dl/cdk_workshop/.venv
STATUS: Resolving dependencies
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   pre-commit>=3.3.3
pdm.termui:   mypy[dmypy]>=1.5.0
pdm.termui:   pytest-md>=0.2.0
pdm.termui:   pytest-emoji>=0.2.0
pdm.termui:   coverage>=7.3.0
pdm.termui:   ruff>=0.0.284
pdm.termui:   pytest>=7.4.0
pdm.termui:   boto3>=1.28.29
pdm.termui:   boto3-stubs>=1.28.29.post1
pdm.termui:   types-requests>=2.31.0.2
pdm.termui:   -e file:///${PROJECT_ROOT}/../dl-cdk-lib#egg=dl-cdk-lib
pdm.termui:   aws-cdk-lib==2.91.0
pdm.termui:   constructs<11.0.0,>=10.0.0
pdm.termui:   cdk-dynamo-table-view>=0.2.486
pdm.termui:   dl-cdk-lib @ git+ssh://git@github.com/datalogics-kam/dl-cdk-lib.git@make-dl-cdk-lib
pdm.termui:   python>=3.11
pdm.termui:   Adding requirement pre-commit>=3.3.3
pdm.termui:   Adding requirement mypy[dmypy]>=1.5.0
pdm.termui:   Adding requirement pytest-md>=0.2.0
pdm.termui:   Adding requirement pytest-emoji>=0.2.0
pdm.termui:   Adding requirement coverage>=7.3.0
pdm.termui:   Adding requirement ruff>=0.0.284
pdm.termui:   Adding requirement pytest>=7.4.0
pdm.termui:   Adding requirement boto3>=1.28.29
pdm.termui:   Adding requirement boto3-stubs>=1.28.29.post1
pdm.termui:   Adding requirement types-requests>=2.31.0.2
pdm.termui:   Adding requirement -e file:///${PROJECT_ROOT}/../dl-cdk-lib#egg=dl-cdk-lib
pdm.termui:   Adding requirement aws-cdk-lib==2.91.0
pdm.termui:   Adding requirement constructs<11.0.0,>=10.0.0
pdm.termui:   Adding requirement cdk-dynamo-table-view>=0.2.486
pdm.termui:   Adding requirement dl-cdk-lib @ git+ssh://git@github.com/datalogics-kam/dl-cdk-lib.git@make-dl-cdk-lib
🔒 Lock failed
Unable to find a resolution for dl-cdk-lib
because of the following conflicts:
  -e file:///${PROJECT_ROOT}/../dl-cdk-lib#egg=dl-cdk-lib (from project)
  dl-cdk-lib @ git+ssh://git@github.com/datalogics-kam/dl-cdk-lib.git@make-dl-cdk-lib (from project)
To fix this, you could loosen the dependency version constraints in pyproject.toml. See https://pdm.fming.dev/latest/usage/dependency/#solve-the-locking-failure for more details.
Traceback (most recent call last):
  File "/Users/kam/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/kam/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 290, in main
    return Core().main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kam/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 208, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/Users/kam/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 203, in main
    self.handle(project, options)
  File "/Users/kam/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 157, in handle
    command.handle(project, options)
  File "/Users/kam/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/cli/commands/add.py", line 69, in handle
    self.do_add(
  File "/Users/kam/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/cli/commands/add.py", line 161, in do_add
    resolved = do_lock(
               ^^^^^^^^
  File "/Users/kam/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/cli/actions.py", line 117, in do_lock
    raise ResolutionImpossible("Unable to find a resolution") from None
resolvelib.resolvers.ResolutionImpossible: Unable to find a resolution
```

## Expected behavior

Editable requirement overrides the base requirement without an error. This seems to be how it should work, given the discussion in #2199.

## Environment Information

```bash
❯ pdm info && pdm info --env
PDM version:
  2.9.2
Python Interpreter:
  /Users/kam/src/dl/cdk_workshop/.venv/bin/python (3.11)
Project Root:
  /Users/kam/src/dl/cdk_workshop
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.11.2",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "22.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64",
  "python_full_version": "3.11.2",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "darwin"
}
```

**Comment by datalogics-kam** [comment]
Thanks for the reply!

I see. Would be nice, but a decent workaround I figured out is

```
pdm run python -m ensurepip --upgrade
pdm run python -m pip install -e ../dl-cdk-lib
```

...which installs an editable library. One benefit of working this way is that it's totally local and temporary...no changes to `pyproject.toml`.

`pdm sync --no-editable` will restore the virtual environment to what's in `pyproject.toml`.

**Comment by robtaylor** [comment]
> ```
> pdm run python -m ensurepip --upgrade
> pdm run python -m pip install -e ../dl-cdk-lib
> ```
> 
> ...which installs an editable library. One benefit of working this way is that it's totally local and temporary...no changes to `pyproject.toml`.
> 
> `pdm sync --no-editable` will restore the virtual environment to what's in `pyproject.toml`.

Would be nice to add this to the manual, I've been wanting to do this for *aaages*
