### ISSUE TITLE
PDM can not self host

### ISSUE THREAD

**Issue by drunkwcodes** [pdm-project/pdm#2262]
- [v ] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

```
PS C:\Users\drunk\projects\pdm> pdm install -d -v
STATUS: Resolving packages from lockfile...
unearth.preparer: The file . is a local directory, use it directly
pdm.termui: Running PEP 517 backend to get metadata for <Link file:///C:/Users/drunk/projects/pdm (from None)>
pdm.termui: Preparing isolated env for PEP 517 build...
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   pdm-backend
pdm.termui:   python>=3.11.4,<3.11.5
pdm.termui:   Adding requirement pdm-backend
pdm.termui:   Adding requirement python>=3.11.4,<3.11.5
pdm.termui: ======== Starting round 0 ========
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
pdm.termui: Pinning: pdm-backend 2.1.6
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
pdm.termui: ======== Resolution Result ========
pdm.termui: Stable pins:
pdm.termui:        python None
pdm.termui:   pdm-backend 2.1.6
pdm.termui: Installing pdm-backend@2.1.6...
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/d3/03/53dffcd6e051a9dcdcbe665305b8c68a54b881f7023b37815c9d2390d849/pdm_backend-2.1.6-py3-none-any.whl (from https://pypi.org/simple/pdm-backend/)>
pdm.termui: Synchronization complete.
unearth.preparer: The file . is a local directory, use it directly
pdm.termui: Running PEP 517 backend to get metadata for <Link file:///C:/Users/drunk/projects/pdm (from None)>
pdm.termui: Preparing isolated env for PEP 517 build...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\drunk\AppData\Local\Programs\Python\Python311\Scripts\pdm.exe\__main__.py", line 7, in <module>
  File "C:\Users\drunk\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\core.py", line 290, in main
    return Core().main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drunk\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\core.py", line 208, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "C:\Users\drunk\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\core.py", line 203, in main
    self.handle(project, options)
  File "C:\Users\drunk\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\core.py", line 157, in handle
    command.handle(project, options)
  File "C:\Users\drunk\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\cli\commands\install.py", line 95, in handle
    actions.do_sync(
  File "C:\Users\drunk\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\cli\actions.py", line 197, in do_sync
    candidates = resolve_candidates_from_lockfile(project, requirements)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drunk\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\cli\actions.py", line 140, in resolve_candidates_from_lockfile
    mapping, *_ = resolve(
                  ^^^^^^^^
  File "C:\Users\drunk\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdm\resolver\core.py", line 36, in resolve
    result = resolver.resolve(requirements, max_rounds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drunk\AppData\Local\Programs\Python\Python311\Lib\site-packages\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drunk\AppData\Local\Programs\Python\Python311\Lib\site-packages\resolvelib\resolvers.py", line 434, in resolve
    success = self._backjump(causes)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drunk\AppData\Local\Programs\Python\Python311\Lib\site-packages\resolvelib\resolvers.py", line 318, in _backjump
    raise ResolutionImpossible(causes)
resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=PythonRequirement(name='python', marker=None, extras=None, specifier=<PySpecSet >=3.7>, editable=False, prerelease=False), parent=None), RequirementInformation(requirement=PythonRequirement(name='python', marker=None, extras=None, specifier=<PySpecSet >=3.10>, editable=False, prerelease=False), parent=<Candidate truststore@0.7.0>)]
```

## Steps to reproduce

1. git clone pdm
2. cd pdm
3. pdm install -d

## Expected behavior

Editable install succesfully like `pip install -e .`

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:

```

**Comment by pawamoy** [comment]
With which Python version did you make `pdm` available? I have it installed with pipx and Python 3.11, and it works fine.

**Comment by drunkwcodes** [comment]
@pawamoy python3.11.
Now `pip` and `pipx` are all good.

**Comment by frostming** [comment]
not reproducible, also make sure pdm is up-to-date

**Comment by drunkwcodes** [comment]
Can confirm. It is not reproducible in my office.

Btw, I'm having some questions when I developing the fork.
May I email you to ask for details?

How often do you read emails?

**Comment by frostming** [comment]
> Can confirm. It is not reproducible in my office.
> 
> Btw, I'm having some questions when I developing the fork. May I email you to ask for details?
> 
> How often do you read emails?

Anytime welcome. But honestly speaking, I don't have much interest in looking into the fork, one reason of which is it is not developed in an upstream-first manner. But let's see what I can help.

**Comment by drunkwcodes** [comment]
That's great anyway. 

Recently I copied your tests of dependency `GroupSelection`, it failed with my `GroupSelection` only returning ["default"] or empty list, not same with `golden`.

I'm installing pdm's dev environment now to try to debug and compare with my fork.
I will let you know if I find something interesting or confusing.
