### ISSUE TITLE
Cannot install TensorRT

### ISSUE THREAD

**Issue by lykius** [pdm-project/pdm#2280]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

I'm trying to install [tensorrt](https://pypi.org/project/tensorrt/) in my project.  
Everything goes fine using pip:
```
pip install -U pip setuptools wheel  # -> wheel seems to be fundamental
pip install tensorrt==8.6.1
```
At the end of the installation I find the following packages:
```
tensorrt==8.6.1
tensorrt-bindings==8.6.1
tensorrt-libs==8.6.1
```

Instead, if I run
```
pdm add tensorrt==8.6.1
```
`tensorrt-bindings` and `tensorrt-libs` are not installed. If I try to install them manually by running:
```
pdm add tensorrt-bindings==8.6.1
pdm add tensorrt-libs==8.6.1
```
eveything goes fine for `tensorrt-bindings` while `tensorrt-libs` fails with the following output:

```
Adding packages to default dependencies: tensorrt-libs==8.6.1
STATUS: Resolving dependencies
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   tensorrt==8.6.1
pdm.termui:   tensorrt-bindings==8.6.1
pdm.termui:   tensorrt-libs==8.6.1
pdm.termui:   python>=3.9
pdm.termui:   Adding requirement tensorrt==8.6.1
pdm.termui:   Adding requirement tensorrt-bindings==8.6.1
pdm.termui:   Adding requirement tensorrt-libs==8.6.1
pdm.termui:   Adding requirement python>=3.9
pdm.termui: ======== Starting round 0 ========
STATUS: Resolving: new pin python>=3.9
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
STATUS: Resolving: new pin tensorrt 8.6.1
pdm.termui: Pinning: tensorrt 8.6.1
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
STATUS: Resolving: new pin tensorrt-bindings 8.6.1
pdm.termui: Pinning: tensorrt-bindings 8.6.1
pdm.termui: ======== Ending round 2 ========
pdm.termui: ======== Starting round 3 ========
STATUS: Resolving: new pin tensorrt-libs 8.6.1
pdm.termui: Pinning: tensorrt-libs 8.6.1
pdm.termui: ======== Ending round 3 ========
pdm.termui: ======== Starting round 4 ========
pdm.termui: ======== Resolution Result ========
pdm.termui: Stable pins:
pdm.termui:              python None
pdm.termui:            tensorrt 8.6.1
pdm.termui:   tensorrt-bindings 8.6.1
pdm.termui:       tensorrt-libs 8.6.1
STATUS: Fetching hashes for resolved packages...
pdm.termui: Fetching hashes for tensorrt-libs@8.6.1
🔒 Lock successful
Changes are written to pyproject.toml.
STATUS: Resolving packages from lockfile...
STATUS: Fetching hashes for resolved packages...
Synchronizing working set with resolved packages: 1 to add, 0 to update, 0 to remove

unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/87/d1/e24667ab99b54c6f52491caeeaa7365e94dc864fbcba83834d89b59af6ce/tensorrt-libs-8.6.1.tar.gz (from https://pypi.org/simple/tensorrt-libs/)>
pdm.termui: Preparing isolated env for PEP 517 build...
pdm.termui: Saving wheel to cache: <Link https://files.pythonhosted.org/packages/87/d1/e24667ab99b54c6f52491caeeaa7365e94dc864fbcba83834d89b59af6ce/tensorrt-libs-8.6.1.tar.gz (from https://pypi.org/simple/tensorrt-libs/)>
pdm.termui: Running PEP 517 backend to build a wheel for <Link https://files.pythonhosted.org/packages/87/d1/e24667ab99b54c6f52491caeeaa7365e94dc864fbcba83834d89b59af6ce/tensorrt-libs-8.6.1.tar.gz (from https://pypi.org/simple/tensorrt-libs/)>
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   wheel
pdm.termui:   setuptools>=40.8.0
pdm.termui:   python>=3.9.16,<3.9.17
pdm.termui:   Adding requirement wheel
pdm.termui:   Adding requirement setuptools>=40.8.0
pdm.termui:   Adding requirement python>=3.9.16,<3.9.17
pdm.termui: ======== Starting round 0 ========
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
pdm.termui: Pinning: setuptools 68.2.2
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
pdm.termui: Pinning: wheel 0.41.2
pdm.termui: ======== Ending round 2 ========
pdm.termui: ======== Starting round 3 ========
pdm.termui: ======== Resolution Result ========
pdm.termui: Stable pins:
pdm.termui:       python None
pdm.termui:   setuptools 68.2.2
pdm.termui:        wheel 0.41.2
pdm.termui: Installing setuptools@68.2.2...
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/bb/26/7945080113158354380a12ce26873dd6c1ebd88d47f5bc24e2c5bb38c16a/setuptools-68.2.2-py3-none-any.whl (from https://pypi.org/simple/setuptools/)>
pdm.termui: Installing wheel@0.41.2...
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/b8/8b/31273bf66016be6ad22bb7345c37ff350276cfd46e389a0c2ac5da9d9073/wheel-0.41.2-py3-none-any.whl (from https://pypi.org/simple/wheel/)>
pdm.termui: Synchronization complete.
pdm.termui: Traceback (most recent call last):
pdm.termui:   File "/home/lykius/.local/share/pdm/venv/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
pdm.termui:     main()
pdm.termui:   File "/home/lykius/.local/share/pdm/venv/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
pdm.termui:     json_out['return_val'] = hook(**hook_input['kwargs'])
pdm.termui:   File "/home/lykius/.local/share/pdm/venv/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
pdm.termui:     return hook(config_settings)
pdm.termui:   File "/tmp/pdm-build-env-4yvq7gps-shared/lib/python3.9/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
pdm.termui:     return self._get_build_requires(config_settings, requirements=['wheel'])
pdm.termui:   File "/tmp/pdm-build-env-4yvq7gps-shared/lib/python3.9/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
pdm.termui:     self.run_setup()
pdm.termui:   File "/tmp/pdm-build-env-4yvq7gps-shared/lib/python3.9/site-packages/setuptools/build_meta.py", line 507, in run_setup
pdm.termui:     super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
pdm.termui:   File "/tmp/pdm-build-env-4yvq7gps-shared/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in run_setup
pdm.termui:     exec(code, locals())
pdm.termui:   File "<string>", line 81, in <module>
pdm.termui: RuntimeError: Bad params
  ✖ Install tensorrt-libs 8.6.1 failed
pdm.termui: Error occurs: 
Traceback (most recent call last):
  File "/home/lykius/.pyenv/versions/3.9.16/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/lykius/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 283, in install_candidate
    self.manager.install(can)
  File "/home/lykius/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/manager.py", line 33, in install
    installer(str(prepared.build()), self.environment, prepared.direct_url())
  File "/home/lykius/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/models/candidates.py", line 395, in build
    self.wheel = Path(builder.build(build_dir, metadata_directory=self._metadata_dir))
  File "/home/lykius/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/builders/wheel.py", line 26, in build
    requires = self._hook.get_requires_for_build_wheel(config_settings)
  File "/home/lykius/.local/share/pdm/venv/lib/python3.9/site-packages/pyproject_hooks/_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "/home/lykius/.local/share/pdm/venv/lib/python3.9/site-packages/pyproject_hooks/_impl.py", line 311, in _call_hook
    self._subprocess_runner(
  File "/home/lykius/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/builders/base.py", line 260, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
  File "/home/lykius/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/builders/base.py", line 107, in log_subprocessor
    raise build_error(e) from None
pdm.exceptions.BuildError: Build backend raised error: Showing the last 10 lines of the build output:
  File "/tmp/pdm-build-env-4yvq7gps-shared/lib/python3.9/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
  File "/tmp/pdm-build-env-4yvq7gps-shared/lib/python3.9/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
    self.run_setup()
  File "/tmp/pdm-build-env-4yvq7gps-shared/lib/python3.9/site-packages/setuptools/build_meta.py", line 507, in run_setup
    super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
  File "/tmp/pdm-build-env-4yvq7gps-shared/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in run_setup
    exec(code, locals())
  File "<string>", line 81, in <module>
RuntimeError: Bad params
Retry failed jobs
pdm.termui: Preparing isolated env for PEP 517 build...
pdm.termui: Saving wheel to cache: <Link https://files.pythonhosted.org/packages/87/d1/e24667ab99b54c6f52491caeeaa7365e94dc864fbcba83834d89b59af6ce/tensorrt-libs-8.6.1.tar.gz (from https://pypi.org/simple/tensorrt-libs/)>
pdm.termui: Running PEP 517 backend to build a wheel for <Link https://files.pythonhosted.org/packages/87/d1/e24667ab99b54c6f52491caeeaa7365e94dc864fbcba83834d89b59af6ce/tensorrt-libs-8.6.1.tar.gz (from https://pypi.org/simple/tensorrt-libs/)>
pdm.termui: Traceback (most recent call last):
pdm.termui:   File "/home/lykius/.local/share/pdm/venv/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
pdm.termui:     main()
pdm.termui:   File "/home/lykius/.local/share/pdm/venv/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
pdm.termui:     json_out['return_val'] = hook(**hook_input['kwargs'])
pdm.termui:   File "/home/lykius/.local/share/pdm/venv/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
pdm.termui:     return hook(config_settings)
pdm.termui:   File "/tmp/pdm-build-env-4yvq7gps-shared/lib/python3.9/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
pdm.termui:     return self._get_build_requires(config_settings, requirements=['wheel'])
pdm.termui:   File "/tmp/pdm-build-env-4yvq7gps-shared/lib/python3.9/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
pdm.termui:     self.run_setup()
pdm.termui:   File "/tmp/pdm-build-env-4yvq7gps-shared/lib/python3.9/site-packages/setuptools/build_meta.py", line 507, in run_setup
pdm.termui:     super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
pdm.termui:   File "/tmp/pdm-build-env-4yvq7gps-shared/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in run_setup
pdm.termui:     exec(code, locals())
pdm.termui:   File "<string>", line 81, in <module>
pdm.termui: RuntimeError: Bad params
  ✖ Install tensorrt-libs 8.6.1 failed
pdm.termui: Error occurs: 
Traceback (most recent call last):
  File "/home/lykius/.pyenv/versions/3.9.16/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/lykius/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 283, in install_candidate
    self.manager.install(can)
  File "/home/lykius/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/manager.py", line 33, in install
    installer(str(prepared.build()), self.environment, prepared.direct_url())
  File "/home/lykius/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/models/candidates.py", line 395, in build
    self.wheel = Path(builder.build(build_dir, metadata_directory=self._metadata_dir))
  File "/home/lykius/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/builders/wheel.py", line 26, in build
    requires = self._hook.get_requires_for_build_wheel(config_settings)
  File "/home/lykius/.local/share/pdm/venv/lib/python3.9/site-packages/pyproject_hooks/_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "/home/lykius/.local/share/pdm/venv/lib/python3.9/site-packages/pyproject_hooks/_impl.py", line 311, in _call_hook
    self._subprocess_runner(
  File "/home/lykius/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/builders/base.py", line 260, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
  File "/home/lykius/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/builders/base.py", line 107, in log_subprocessor
    raise build_error(e) from None
pdm.exceptions.BuildError: Build backend raised error: Showing the last 10 lines of the build output:
  File "/tmp/pdm-build-env-4yvq7gps-shared/lib/python3.9/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
  File "/tmp/pdm-build-env-4yvq7gps-shared/lib/python3.9/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
    self.run_setup()
  File "/tmp/pdm-build-env-4yvq7gps-shared/lib/python3.9/site-packages/setuptools/build_meta.py", line 507, in run_setup
    super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
  File "/tmp/pdm-build-env-4yvq7gps-shared/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in run_setup
    exec(code, locals())
  File "<string>", line 81, in <module>
RuntimeError: Bad params
Traceback (most recent call last):
  File "/home/lykius/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/lykius/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/core.py", line 290, in main
    return Core().main(args or sys.argv[1:])
  File "/home/lykius/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/core.py", line 208, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/home/lykius/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/core.py", line 203, in main
    self.handle(project, options)
  File "/home/lykius/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/core.py", line 157, in handle
    command.handle(project, options)
  File "/home/lykius/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/cli/commands/add.py", line 69, in handle
    self.do_add(
  File "/home/lykius/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/cli/commands/add.py", line 180, in do_add
    do_sync(
  File "/home/lykius/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/cli/actions.py", line 214, in do_sync
    synchronizer.synchronize()
  File "/home/lykius/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 451, in synchronize
    raise InstallationError("Some package operations are not complete yet")
pdm.exceptions.InstallationError: Some package operations are not complete yet
```

## Actual behavior

Installing `tensorrt` with the command `pdm add tensorrt` does not install `tensorrt-bindings` and `tensorrt-libs` (required).
Manual installation of `tensorrt-libs` with the the command `pdm add tensorrt-libs` fails.

## Expected behavior

It would be nice to install `tensorrt` and its dependencies by simply running `pdm add tensorrt`, as it is done with `pip install tensorrt`.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.9.3
Python Interpreter:
  /home/lykius/dev/test/.venv/bin/python (3.9)
Project Root:
  /home/lykius/dev/test
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.16",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.2.0-33-generic",
  "platform_system": "Linux",
  "platform_version": "#33~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep  7 10:33:52 UTC 2",
  "python_full_version": "3.9.16",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
This package uses a non-standard `setup.py` that installs packages dynamically, which is not friendly to PEP 517 build backends. Further more, I can't manage to install even with pip, it seems it needs some auth credentials to access nvidia index. You can see the content of `setup.py`:
https://inspector.pypi.io/project/tensorrt/8.6.1/packages/25/d8/081cb57cd77e4be6ce55462b51938b00ac570076f37aade5f5c3cdfa8f82/tensorrt-8.6.1.tar.gz/tensorrt-8.6.1/setup.py
