### ISSUE TITLE
Dependency resolution fails for `TTS`

### ISSUE THREAD

**Issue by crepererum** [pdm-project/pdm#2299]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce
Create new project:

```toml
[project]
name = ""
version = ""
description = ""
authors = []
dependencies = []
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}
```

Then run: `pdm add -v 'TTS>=0.17.6'` (you can leave out the version constraint but then it takes VERY VERY long to reproduce the error because PDM will fail for each version of TTS individually).

## Actual behavior

```
Adding packages to default dependencies: TTS>=0.17.6
STATUS: Resolving dependencies
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   TTS>=0.17.6
pdm.termui:   python>=3.11
pdm.termui:   Adding requirement TTS>=0.17.6
pdm.termui:   Adding requirement python>=3.11
pdm.termui: ======== Starting round 0 ========
STATUS: Resolving: new pin python>=3.11
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
pdm.termui:   Adding requirement cython==0.29.30(from TTS 0.17.6)
pdm.termui:   Adding requirement scipy>=1.11.2(from TTS 0.17.6)
pdm.termui:   Adding requirement torch>=1.7(from TTS 0.17.6)
pdm.termui:   Adding requirement torchaudio(from TTS 0.17.6)
pdm.termui:   Adding requirement soundfile==0.12.*(from TTS 0.17.6)
pdm.termui:   Adding requirement librosa==0.10.*(from TTS 0.17.6)
pdm.termui:   Adding requirement scikit-learn==1.3.0(from TTS 0.17.6)
pdm.termui:   Adding requirement inflect==5.6.*(from TTS 0.17.6)
pdm.termui:   Adding requirement tqdm==4.64.*(from TTS 0.17.6)
pdm.termui:   Adding requirement anyascii==0.3.*(from TTS 0.17.6)
pdm.termui:   Adding requirement pyyaml==6.*(from TTS 0.17.6)
pdm.termui:   Adding requirement fsspec==2023.6.0(from TTS 0.17.6)
pdm.termui:   Adding requirement aiohttp==3.8.*(from TTS 0.17.6)
pdm.termui:   Adding requirement packaging==23.1(from TTS 0.17.6)
pdm.termui:   Adding requirement flask==2.*(from TTS 0.17.6)
pdm.termui:   Adding requirement pysbd==0.3.4(from TTS 0.17.6)
pdm.termui:   Adding requirement umap-learn==0.5.*(from TTS 0.17.6)
pdm.termui:   Adding requirement pandas<2.0,>=1.4(from TTS 0.17.6)
pdm.termui:   Adding requirement matplotlib==3.7.*(from TTS 0.17.6)
pdm.termui:   Adding requirement trainer(from TTS 0.17.6)
pdm.termui:   Adding requirement coqpit>=0.0.16(from TTS 0.17.6)
pdm.termui:   Adding requirement jieba(from TTS 0.17.6)
pdm.termui:   Adding requirement pypinyin(from TTS 0.17.6)
pdm.termui:   Adding requirement gruut[de,es,fr]==2.2.3(from TTS 0.17.6)
pdm.termui:   Adding requirement jamo(from TTS 0.17.6)
pdm.termui:   Adding requirement nltk(from TTS 0.17.6)
pdm.termui:   Adding requirement g2pkk>=0.1.1(from TTS 0.17.6)
pdm.termui:   Adding requirement bangla(from TTS 0.17.6)
pdm.termui:   Adding requirement bnnumerizer(from TTS 0.17.6)
pdm.termui:   Adding requirement bnunicodenormalizer(from TTS 0.17.6)
pdm.termui:   Adding requirement k-diffusion(from TTS 0.17.6)
pdm.termui:   Adding requirement einops==0.6.*(from TTS 0.17.6)
pdm.termui:   Adding requirement transformers==4.33.*(from TTS 0.17.6)
pdm.termui:   Adding requirement encodec==0.1.*(from TTS 0.17.6)
pdm.termui:   Adding requirement unidecode==1.3.*(from TTS 0.17.6)
pdm.termui:   Adding requirement numpy==1.24.3; python_version > "3.10"(from TTS 0.17.6)
pdm.termui:   Adding requirement numba==0.57.0; python_version >= "3.9"(from TTS 0.17.6)
pdm.termui:   Adding requirement python>=3.9,<3.12(from TTS 0.17.6)
pdm.termui: Candidate rejected: TTS@0.17.6 because it introduces a new requirement python>=3.9,<3.12 that conflicts with other requirements:
    python>=3.11 (from project)
pdm.termui:   Adding requirement cython==0.29.30(from TTS 0.17.6)
pdm.termui:   Adding requirement scipy>=1.11.2(from TTS 0.17.6)
pdm.termui:   Adding requirement torch>=1.7(from TTS 0.17.6)
pdm.termui:   Adding requirement torchaudio(from TTS 0.17.6)
pdm.termui:   Adding requirement soundfile==0.12.*(from TTS 0.17.6)
pdm.termui:   Adding requirement librosa==0.10.*(from TTS 0.17.6)
pdm.termui:   Adding requirement scikit-learn==1.3.0(from TTS 0.17.6)
pdm.termui:   Adding requirement inflect==5.6.*(from TTS 0.17.6)
pdm.termui:   Adding requirement tqdm==4.64.*(from TTS 0.17.6)
pdm.termui:   Adding requirement anyascii==0.3.*(from TTS 0.17.6)
pdm.termui:   Adding requirement pyyaml==6.*(from TTS 0.17.6)
pdm.termui:   Adding requirement fsspec==2023.6.0(from TTS 0.17.6)
pdm.termui:   Adding requirement aiohttp==3.8.*(from TTS 0.17.6)
pdm.termui:   Adding requirement packaging==23.1(from TTS 0.17.6)
pdm.termui:   Adding requirement flask==2.*(from TTS 0.17.6)
pdm.termui:   Adding requirement pysbd==0.3.4(from TTS 0.17.6)
pdm.termui:   Adding requirement umap-learn==0.5.*(from TTS 0.17.6)
pdm.termui:   Adding requirement pandas<2.0,>=1.4(from TTS 0.17.6)
pdm.termui:   Adding requirement matplotlib==3.7.*(from TTS 0.17.6)
pdm.termui:   Adding requirement trainer(from TTS 0.17.6)
pdm.termui:   Adding requirement coqpit>=0.0.16(from TTS 0.17.6)
pdm.termui:   Adding requirement jieba(from TTS 0.17.6)
pdm.termui:   Adding requirement pypinyin(from TTS 0.17.6)
pdm.termui:   Adding requirement gruut[de,es,fr]==2.2.3(from TTS 0.17.6)
pdm.termui:   Adding requirement jamo(from TTS 0.17.6)
pdm.termui:   Adding requirement nltk(from TTS 0.17.6)
pdm.termui:   Adding requirement g2pkk>=0.1.1(from TTS 0.17.6)
pdm.termui:   Adding requirement bangla(from TTS 0.17.6)
pdm.termui:   Adding requirement bnnumerizer(from TTS 0.17.6)
pdm.termui:   Adding requirement bnunicodenormalizer(from TTS 0.17.6)
pdm.termui:   Adding requirement k-diffusion(from TTS 0.17.6)
pdm.termui:   Adding requirement einops==0.6.*(from TTS 0.17.6)
pdm.termui:   Adding requirement transformers==4.33.*(from TTS 0.17.6)
pdm.termui:   Adding requirement encodec==0.1.*(from TTS 0.17.6)
pdm.termui:   Adding requirement unidecode==1.3.*(from TTS 0.17.6)
pdm.termui:   Adding requirement numpy==1.24.3; python_version > "3.10"(from TTS 0.17.6)
pdm.termui:   Adding requirement numba==0.57.0; python_version >= "3.9"(from TTS 0.17.6)
pdm.termui:   Adding requirement python>=3.9,<3.12(from TTS 0.17.6)
pdm.termui: Candidate rejected: TTS@0.17.6 because it introduces a new requirement python>=3.9,<3.12 that conflicts with other requirements:
    python>=3.11 (from project)
pdm.termui:   Adding requirement cython==0.29.30(from TTS 0.17.6)
pdm.termui:   Adding requirement scipy>=1.11.2(from TTS 0.17.6)
pdm.termui:   Adding requirement torch>=1.7(from TTS 0.17.6)
pdm.termui:   Adding requirement torchaudio(from TTS 0.17.6)
pdm.termui:   Adding requirement soundfile==0.12.*(from TTS 0.17.6)
pdm.termui:   Adding requirement librosa==0.10.*(from TTS 0.17.6)
pdm.termui:   Adding requirement scikit-learn==1.3.0(from TTS 0.17.6)
pdm.termui:   Adding requirement inflect==5.6.*(from TTS 0.17.6)
pdm.termui:   Adding requirement tqdm==4.64.*(from TTS 0.17.6)
pdm.termui:   Adding requirement anyascii==0.3.*(from TTS 0.17.6)
pdm.termui:   Adding requirement pyyaml==6.*(from TTS 0.17.6)
pdm.termui:   Adding requirement fsspec==2023.6.0(from TTS 0.17.6)
pdm.termui:   Adding requirement aiohttp==3.8.*(from TTS 0.17.6)
pdm.termui:   Adding requirement packaging==23.1(from TTS 0.17.6)
pdm.termui:   Adding requirement flask==2.*(from TTS 0.17.6)
pdm.termui:   Adding requirement pysbd==0.3.4(from TTS 0.17.6)
pdm.termui:   Adding requirement umap-learn==0.5.*(from TTS 0.17.6)
pdm.termui:   Adding requirement pandas<2.0,>=1.4(from TTS 0.17.6)
pdm.termui:   Adding requirement matplotlib==3.7.*(from TTS 0.17.6)
pdm.termui:   Adding requirement trainer(from TTS 0.17.6)
pdm.termui:   Adding requirement coqpit>=0.0.16(from TTS 0.17.6)
pdm.termui:   Adding requirement jieba(from TTS 0.17.6)
pdm.termui:   Adding requirement pypinyin(from TTS 0.17.6)
pdm.termui:   Adding requirement gruut[de,es,fr]==2.2.3(from TTS 0.17.6)
pdm.termui:   Adding requirement jamo(from TTS 0.17.6)
pdm.termui:   Adding requirement nltk(from TTS 0.17.6)
pdm.termui:   Adding requirement g2pkk>=0.1.1(from TTS 0.17.6)
pdm.termui:   Adding requirement bangla(from TTS 0.17.6)
pdm.termui:   Adding requirement bnnumerizer(from TTS 0.17.6)
pdm.termui:   Adding requirement bnunicodenormalizer(from TTS 0.17.6)
pdm.termui:   Adding requirement k-diffusion(from TTS 0.17.6)
pdm.termui:   Adding requirement einops==0.6.*(from TTS 0.17.6)
pdm.termui:   Adding requirement transformers==4.33.*(from TTS 0.17.6)
pdm.termui:   Adding requirement encodec==0.1.*(from TTS 0.17.6)
pdm.termui:   Adding requirement unidecode==1.3.*(from TTS 0.17.6)
pdm.termui:   Adding requirement numpy==1.24.3; python_version > "3.10"(from TTS 0.17.6)
pdm.termui:   Adding requirement numba==0.57.0; python_version >= "3.9"(from TTS 0.17.6)
pdm.termui:   Adding requirement python>=3.9,<3.12(from TTS 0.17.6)
pdm.termui: Candidate rejected: TTS@0.17.6 because it introduces a new requirement python>=3.9,<3.12 that conflicts with other requirements:
    python>=3.11 (from project)
pdm.termui:   Adding requirement cython==0.29.30(from TTS 0.17.6)
pdm.termui:   Adding requirement scipy>=1.11.2(from TTS 0.17.6)
pdm.termui:   Adding requirement torch>=1.7(from TTS 0.17.6)
pdm.termui:   Adding requirement torchaudio(from TTS 0.17.6)
pdm.termui:   Adding requirement soundfile==0.12.*(from TTS 0.17.6)
pdm.termui:   Adding requirement librosa==0.10.*(from TTS 0.17.6)
pdm.termui:   Adding requirement scikit-learn==1.3.0(from TTS 0.17.6)
pdm.termui:   Adding requirement inflect==5.6.*(from TTS 0.17.6)
pdm.termui:   Adding requirement tqdm==4.64.*(from TTS 0.17.6)
pdm.termui:   Adding requirement anyascii==0.3.*(from TTS 0.17.6)
pdm.termui:   Adding requirement pyyaml==6.*(from TTS 0.17.6)
pdm.termui:   Adding requirement fsspec==2023.6.0(from TTS 0.17.6)
pdm.termui:   Adding requirement aiohttp==3.8.*(from TTS 0.17.6)
pdm.termui:   Adding requirement packaging==23.1(from TTS 0.17.6)
pdm.termui:   Adding requirement flask==2.*(from TTS 0.17.6)
pdm.termui:   Adding requirement pysbd==0.3.4(from TTS 0.17.6)
pdm.termui:   Adding requirement umap-learn==0.5.*(from TTS 0.17.6)
pdm.termui:   Adding requirement pandas<2.0,>=1.4(from TTS 0.17.6)
pdm.termui:   Adding requirement matplotlib==3.7.*(from TTS 0.17.6)
pdm.termui:   Adding requirement trainer(from TTS 0.17.6)
pdm.termui:   Adding requirement coqpit>=0.0.16(from TTS 0.17.6)
pdm.termui:   Adding requirement jieba(from TTS 0.17.6)
pdm.termui:   Adding requirement pypinyin(from TTS 0.17.6)
pdm.termui:   Adding requirement gruut[de,es,fr]==2.2.3(from TTS 0.17.6)
pdm.termui:   Adding requirement jamo(from TTS 0.17.6)
pdm.termui:   Adding requirement nltk(from TTS 0.17.6)
pdm.termui:   Adding requirement g2pkk>=0.1.1(from TTS 0.17.6)
pdm.termui:   Adding requirement bangla(from TTS 0.17.6)
pdm.termui:   Adding requirement bnnumerizer(from TTS 0.17.6)
pdm.termui:   Adding requirement bnunicodenormalizer(from TTS 0.17.6)
pdm.termui:   Adding requirement k-diffusion(from TTS 0.17.6)
pdm.termui:   Adding requirement einops==0.6.*(from TTS 0.17.6)
pdm.termui:   Adding requirement transformers==4.33.*(from TTS 0.17.6)
pdm.termui:   Adding requirement encodec==0.1.*(from TTS 0.17.6)
pdm.termui:   Adding requirement unidecode==1.3.*(from TTS 0.17.6)
pdm.termui:   Adding requirement numpy==1.24.3; python_version > "3.10"(from TTS 0.17.6)
pdm.termui:   Adding requirement numba==0.57.0; python_version >= "3.9"(from TTS 0.17.6)
pdm.termui:   Adding requirement python>=3.9,<3.12(from TTS 0.17.6)
pdm.termui: Candidate rejected: TTS@0.17.6 because it introduces a new requirement python>=3.9,<3.12 that conflicts with other requirements:
    python>=3.11 (from project)
pdm.termui: Conflicts detected:
  python>=3.11 (from project)
  python>=3.9,<3.12 (from TTS@0.17.6)
🔒 Lock failed
Unable to find a resolution because the following dependencies don't work on all Python versions in the range of the project's `requires-python`: >=3.11.
  python>=3.9,<3.12 (from <Candidate TTS@0.17.6 from https://pypi.org/simple/tts/>)
A possible solution is to change the value of `requires-python` in pyproject.toml to >=3.11,<3.12.
Traceback (most recent call last):
  File "/home/tom/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/tom/.local/share/pdm/venv/lib/python3.11/site-packages/pdm/core.py", line 290, in main
    return Core().main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tom/.local/share/pdm/venv/lib/python3.11/site-packages/pdm/core.py", line 208, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/home/tom/.local/share/pdm/venv/lib/python3.11/site-packages/pdm/core.py", line 203, in main
    self.handle(project, options)
  File "/home/tom/.local/share/pdm/venv/lib/python3.11/site-packages/pdm/core.py", line 157, in handle
    command.handle(project, options)
  File "/home/tom/.local/share/pdm/venv/lib/python3.11/site-packages/pdm/cli/commands/add.py", line 69, in handle
    self.do_add(
  File "/home/tom/.local/share/pdm/venv/lib/python3.11/site-packages/pdm/cli/commands/add.py", line 161, in do_add
    resolved = do_lock(
               ^^^^^^^^
  File "/home/tom/.local/share/pdm/venv/lib/python3.11/site-packages/pdm/cli/actions.py", line 117, in do_lock
    raise ResolutionImpossible("Unable to find a resolution") from None
resolvelib.resolvers.ResolutionImpossible: Unable to find a resolution
```

This lines seems weird:

```
pdm.termui: Candidate rejected: TTS@0.17.6 because it introduces a new requirement python>=3.9,<3.12 that conflicts with other requirements:
    python>=3.11 (from project)
```

I've tried to set other python version constraints for the project, but I think the issue is that PDM trips over the fact that there are at least 3 python version ranges in play here:

1. the project
2. TTS
3. numpy

(technically there's also numba, an maybe more)

## Expected behavior
This should work.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  5.9.3
Python Interpreter:
  /home/tom/src/dreame-coqui2/.venv/bin/python (3.11)
Project Root:
  /home/tom/src/dreame-coqui2
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.11.5",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.5.5-arch1-1",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT_DYNAMIC Sat, 23 Sep 2023 22:55:13 +0000",
  "python_full_version": "3.11.5",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
The cause is shown in the log:
```
pdm.termui: Conflicts detected:
  python>=3.11 (from project)
  python>=3.9,<3.12 (from TTS@0.17.6)
```

The requires-python of your project contain some python versions(such as, Python 3.12) that are not supported by TTS@0.17.6 and there are not any other candidates that meets the requirement.

**Comment by crepererum** [comment]
Oh, so the resolver finds a single solution for the entire python version range specified in the package, not for the subset that is relevant for the venv. That's a bit unexpected.

**Comment by frostming** [comment]
why do you think otherwise, the pdm.lock is project-wide but what version used by venv is highly user-specific. The former should not know the latter
