### ISSUE TITLE
ModuleNotFoundError: No module named 'hatchling' with non-default venv

### ISSUE THREAD

**Issue by Tinche** [pdm-project/pdm#2326]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Hi, I'm the author of [cattrs](https://github.com/python-attrs/cattrs), which [uses PDM](https://github.com/python-attrs/cattrs/blob/main/pyproject.toml). cattrs uses hatchling for its build system, alongside PDM.

If I try creating a non-default virtual environment, PDM fails to install dependencies into it correctly. It works for the default venv, though.

## Actual behavior

```
❯ pdm venv create -n 38 ~/.asdf/installs/python/3.8.9/bin/python
Virtualenv /Users/tintvrtkovic/Library/Application Support/pdm/venvs/cattrs-42pVfgFd-38 is created successfully

❯ pdm install --venv 38 -G:all -v
In virtual environment: /Users/tintvrtkovic/Library/Application Support/pdm/venvs/cattrs-42pVfgFd-38
STATUS: Resolving packages from lockfile...
STATUS: Fetching hashes for resolved packages...
unearth.preparer: The file . is a local directory, use it directly
Synchronizing working set with resolved packages: 67 to add, 0 to update, 0 to remove

unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/64/88/c7083fc61120ab661c5d0b82cb77079fc1429d3f913a456c1c82cf4658f7/alabaster-0.7.13-py3-none-any.whl (from https://pypi.org/simple/alabaster/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/57/f4/a69c20ee4f660081a7dedb1ac57f29be9378e04edfcb90c526b923d4bebc/beautifulsoup4-4.12.2-py3-none-any.whl (from https://pypi.org/simple/beautifulsoup4/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/4c/dd/2234eab22353ffc7d94e8d13177aaa050113286e93e7b40eae01fbf7c3d9/certifi-2023.7.22-py3-none-any.whl (from https://pypi.org/simple/certifi/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/f0/eb/fcb708c7bf5056045e9e98f62b93bd7467eb718b0202e7698eb11d66416c/attrs-23.1.0-py3-none-any.whl (from https://pypi.org/simple/attrs/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/df/c4/1088865e0246d7ecf56d819a233ab2b72f7d6ab043965ef327d0731b5434/Babel-2.12.1-py3-none-any.whl (from https://pypi.org/simple/babel/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/c5/9c/61a60c7b5aee310318eef66dd8c13f5133e27d030cca448171b9ded3b37c/cbor2-5.4.6-cp38-cp38-macosx_10_9_x86_64.whl (from https://pypi.org/simple/cbor2/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/8e/6f/67b20e7bd900b88cd4710fb5061e79740f360677f094271d73cbcaace43c/black-23.7.0-cp38-cp38-macosx_10_16_x86_64.whl (from https://pypi.org/simple/black/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/79/55/9aef5046a1765acacf28f80994f5a964ab4f43ab75208b1265191a11004b/charset_normalizer-3.2.0-cp38-cp38-macosx_10_9_x86_64.whl (from https://pypi.org/simple/charset-normalizer/)>
  ✔ Install alabaster 0.7.13 successful
  ✔ Install cbor2 5.4.6 successful
  ✔ Install certifi 2023.7.22 successful
  ✔ Install attrs 23.1.0 successful
  ✔ Install beautifulsoup4 4.12.2 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/00/2e/d53fa4befbf2cfa713304affc7ca780ce4fc1fd8710527771b58311a3229/click-8.1.7-py3-none-any.whl (from https://pypi.org/simple/click/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/f6/b4/0a9bee52c50f226a3cbfb54263d02bb421c7f2adc136520729c2c689c1e5/dnspython-2.4.2-py3-none-any.whl (from https://pypi.org/simple/dnspython/)>
  ✔ Install charset-normalizer 3.2.0 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/26/87/f238c0670b94533ac0353a4e2a1a771a0cc73277b88bff23d3ae35a256c1/docutils-0.20.1-py3-none-any.whl (from https://pypi.org/simple/docutils/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/ad/83/b71e58666f156a39fb29417e4c8ca4bc7400c0dd4ed9e8842ab54dc8c344/exceptiongroup-1.1.3-py3-none-any.whl (from https://pypi.org/simple/exceptiongroup/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/cb/7e/7af529e3fc72d4e2b7ec228027c21049126994af28a21b0c1d6198e84ef1/furo-2023.8.19-py3-none-any.whl (from https://pypi.org/simple/furo/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/b0/39/efd8ef79db5bf86a0bc7294cfdc67519d6f1d39e4732da47884b41134f30/coverage-7.3.0-cp38-cp38-macosx_10_9_x86_64.whl (from https://pypi.org/simple/coverage/)>
  ✔ Install exceptiongroup 1.1.3 successful
  ✔ Install click 8.1.7 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/fc/34/3030de6f1370931b9dbb4dad48f6ab1015ab1d32447850b9fc94e60097be/idna-3.4-py3-none-any.whl (from https://pypi.org/simple/idna/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/96/a7/8ffef65338ed505545c6013844edbadd5e1092b027cc0d7c76c3e1edd02e/hypothesis-6.82.7-py3-none-any.whl (from https://pypi.org/simple/hypothesis/)>
  ✔ Install idna 3.4 successful
  ✔ Install furo 2023.8.19 successful
  ✔ Install coverage 7.3.0 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/ff/62/85c4c919272577931d407be5ba5d71c20f0b616d31a0befe0ae45bb79abd/imagesize-1.4.1-py2.py3-none-any.whl (from https://pypi.org/simple/imagesize/)>
  ✔ Install black 23.7.0 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/d0/15/85116402b756f2552973580d6d0acb1e52dcc71173f444e164ba673fd600/immutables-0.20-cp38-cp38-macosx_10_9_x86_64.whl (from https://pypi.org/simple/immutables/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/cc/37/db7ba97e676af155f5fcb1a35466f446eadc9104e25b83366e8088c9c926/importlib_metadata-6.8.0-py3-none-any.whl (from https://pypi.org/simple/importlib-metadata/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/ef/a6/62565a6e1cf69e10f5727360368e451d4b7f58beeac6173dc9db836a5b46/iniconfig-2.0.0-py3-none-any.whl (from https://pypi.org/simple/iniconfig/)>
  ✔ Install imagesize 1.4.1 successful
  ✔ Install dnspython 2.4.2 successful
  ✔ Install immutables 0.20 successful
  ✔ Install importlib-metadata 6.8.0 successful
  ✔ Install iniconfig 2.0.0 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/0a/63/4036ae70eea279c63e2304b91ee0ac182f467f24f86394ecfe726092340b/isort-5.12.0-py3-none-any.whl (from https://pypi.org/simple/isort/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/bc/c3/f068337a370801f372f2f8f6bad74a5c140f6fda3d9de154052708dd3c65/Jinja2-3.1.2-py3-none-any.whl (from https://pypi.org/simple/jinja2/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/e5/3c/fe85f19699a7b40c8f9ce8ecee7e269b9b3c94099306df6f9891bdefeedd/mdit_py_plugins-0.4.0-py3-none-any.whl (from https://pypi.org/simple/mdit-py-plugins/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/42/d7/1ec15b46af6af88f19b8e5ffea08fa375d433c998b8a7639e76935c14f1f/markdown_it_py-3.0.0-py3-none-any.whl (from https://pypi.org/simple/markdown-it-py/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/f8/33/e9e83b214b5f8d9a60b26e60051734e7657a416e5bce7d7f1c34e26badad/MarkupSafe-2.1.3-cp38-cp38-macosx_10_9_x86_64.whl (from https://pypi.org/simple/markupsafe/)>
  ✔ Install hypothesis 6.82.7 successful
  ✔ Install markupsafe 2.1.3 successful
  ✔ Install jinja2 3.1.2 successful
  ✔ Install docutils 0.20.1 successful
  ✔ Install isort 5.12.0 successful
  ✔ Install mdit-py-plugins 0.4.0 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/b3/38/89ba8ad64ae25be8de66a6d463314cf1eb366222074cfda9ee839c56a4b4/mdurl-0.1.2-py3-none-any.whl (from https://pypi.org/simple/mdurl/)>
  ✔ Install markdown-it-py 3.0.0 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/2a/e2/5d3f6ada4297caebe1a2add3b126fe800c96f56dbe5d1988a2cbe0b267aa/mypy_extensions-1.0.0-py3-none-any.whl (from https://pypi.org/simple/mypy-extensions/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/33/52/099f0dde1283bac7bf267ab941dfa3b7c89ee701e4252973f8d3c10e68d6/msgpack-1.0.5-cp38-cp38-macosx_10_9_x86_64.whl (from https://pypi.org/simple/msgpack/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/1d/f6/6d61a023d758f488e36638076e8a4ec4447a2cdf86938cf6c60cf1c860e6/myst_parser-2.0.0-py3-none-any.whl (from https://pypi.org/simple/myst-parser/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/b4/2a/9b1be29146139ef459188f5e420a66e835dda921208db600b7037093891f/pathspec-0.11.2-py3-none-any.whl (from https://pypi.org/simple/pathspec/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/ab/c3/57f0601a2d4fe15de7a553c00adbc901425661bf048f2a22dfc500caf121/packaging-23.1-py3-none-any.whl (from https://pypi.org/simple/packaging/)>
  ✔ Install mypy-extensions 1.0.0 successful
  ✔ Install mdurl 0.1.2 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/14/51/fe5a0d6ea589f0d4a1b97824fb518962ad48b27cd346dcdfa2405187997a/platformdirs-3.10.0-py3-none-any.whl (from https://pypi.org/simple/platformdirs/)>
  ✔ Install msgpack 1.0.5 successful
  ✔ Install pathspec 0.11.2 successful
  ✔ Install packaging 23.1 successful
  ✔ Install platformdirs 3.10.0 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/05/b8/42ed91898d4784546c5f06c60506400548db3f7a4b3fb441cba4e5c17952/pluggy-1.3.0-py3-none-any.whl (from https://pypi.org/simple/pluggy/)>
  ✔ Install myst-parser 2.0.0 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/e0/a9/023730ba63db1e494a271cb018dcd361bd2c917ba7004c3e49d5daf795a2/py_cpuinfo-9.0.0-py3-none-any.whl (from https://pypi.org/simple/py-cpuinfo/)>
  ✔ Install pluggy 1.3.0 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/3e/f8/f7a2d67c65c6bfd53fbb1abd856c395c22cf991b92ea77a35af88f7e96b2/pendulum-2.1.2-cp38-cp38-macosx_10_15_x86_64.whl (from https://pypi.org/simple/pendulum/)>
  ✔ Install py-cpuinfo 9.0.0 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/65/73/0492578cbde4c40f8f0d13db2827cc04ba54bcb875d2ee9d4b77ef3c5d28/pyperf-2.6.1-py3-none-any.whl (from https://pypi.org/simple/pyperf/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/43/88/29adf0b44ba6ac85045e63734ae0997d3c58d8b1a91c914d240828d0d73d/Pygments-2.16.1-py3-none-any.whl (from https://pypi.org/simple/pygments/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/cc/fb/35682f5238c5ea915bbe77b80c5551fff700380f95ae4aa2e727805130ee/orjson-3.9.5-cp38-cp38-macosx_10_15_x86_64.macosx_11_0_arm64.macosx_10_15_universal2.whl (from https://pypi.org/simple/orjson/)>
  ✔ Install pyperf 2.6.1 successful
  ✔ Install pendulum 2.1.2 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/33/b2/741130cbcf2bbfa852ed95a60dc311c9e232c7ed25bac3d9b8880a8df4ae/pytest-7.4.0-py3-none-any.whl (from https://pypi.org/simple/pytest/)>
  ✔ Install orjson 3.9.5 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/36/7a/87837f39d0296e723bb9b62bbb257d0355c7f6128853c78955f57342a56d/python_dateutil-2.8.2-py2.py3-none-any.whl (from https://pypi.org/simple/python-dateutil/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/4d/a1/3b70862b5b3f830f0422844f25a823d0470739d994466be9dbbbb414d85a/pytest_benchmark-4.0.0-py3-none-any.whl (from https://pypi.org/simple/pytest-benchmark/)>
  ✔ Install pytest-benchmark 4.0.0 successful
  ✔ Install python-dateutil 2.8.2 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/e0/4f/4474bda990ee740a020cbc3eb271925ef7daa7c8444240d34ff62c8442a3/pytzdata-2020.1-py2.py3-none-any.whl (from https://pypi.org/simple/pytzdata/)>
  ✔ Install pytest 7.4.0 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/9a/76/c0195c3443a725c24b3a479f57636dec89efe53d19d435d1752c5188f7de/psutil-5.9.5-cp36-abi3-macosx_10_9_x86_64.whl (from https://pypi.org/simple/psutil/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/70/8e/0e2d847013cb52cd35b38c009bb167a1a26b2ce6cd6965bf26b47bc0bf44/requests-2.31.0-py3-none-any.whl (from https://pypi.org/simple/requests/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/7f/5d/2779ea035ba1e533c32ed4a249b4e0448f583ba10830b21a3cddafe11a4e/PyYAML-6.0.1-cp38-cp38-macosx_10_9_x86_64.whl (from https://pypi.org/simple/pyyaml/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/7f/99/ad6bd37e748257dd70d6f85d916cafe79c0b0f5e2e95b11f7fbc82bf3110/pytz-2023.3-py2.py3-none-any.whl (from https://pypi.org/simple/pytz/)>
  ✔ Install requests 2.31.0 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/b9/e4/d61f3843cac34fe3c2f5d71177c67d0e3fc06ce7a2c02b3f075a6903a9c8/pymongo-4.5.0-cp38-cp38-macosx_11_0_universal2.whl (from https://pypi.org/simple/pymongo/)>
  ✔ Install psutil 5.9.5 successful
  ✔ Install pyyaml 6.0.1 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl (from https://pypi.org/simple/six/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/ed/dc/c02e01294f7265e63a7315fe086dd1df7dacb9f840a804da846b96d01b96/snowballstemmer-2.2.0-py2.py3-none-any.whl (from https://pypi.org/simple/snowballstemmer/)>
  ✔ Install six 1.16.0 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/93/ba/8c6ba7d2314e231a761a596732a2b014538bd6c80142ffc759807721d64d/ruff-0.0.286-py3-none-macosx_10_9_x86_64.macosx_11_0_arm64.macosx_10_9_universal2.whl (from https://pypi.org/simple/ruff/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/32/46/9cb0e58b2deb7f82b84065f37f3bffeb12413f947f9388e4cac22c4621ce/sortedcontainers-2.4.0-py2.py3-none-any.whl (from https://pypi.org/simple/sortedcontainers/)>
  ✔ Install pygments 2.16.1 successful
  ✔ Install sortedcontainers 2.4.0 successful
  ✔ Install snowballstemmer 2.2.0 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/49/37/673d6490efc51ec46d198c75903d99de59baffdd47aea3d071b80a9e4e89/soupsieve-2.4.1-py3-none-any.whl (from https://pypi.org/simple/soupsieve/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/48/17/325cf6a257d84751a48ae90752b3d8fe0be8f9535b6253add61c49d0d9bc/sphinx-7.1.2-py3-none-any.whl (from https://pypi.org/simple/sphinx/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/3c/dd/018ce05c532a22007ac58d4f45232514cd9d6dd0ee1dc374e309db830983/sphinx_basic_ng-1.0.0b2-py3-none-any.whl (from https://pypi.org/simple/sphinx-basic-ng/)>
  ✔ Install soupsieve 2.4.1 successful
  ✔ Install pymongo 4.5.0 successful
  ✔ Install sphinx-basic-ng 1.0.0b2 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/9e/48/1ea60e74949eecb12cdd6ac43987f9fd331156388dcc2319b45e2ebb81bf/sphinx_copybutton-0.5.2-py3-none-any.whl (from https://pypi.org/simple/sphinx-copybutton/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/06/c1/5e2cafbd03105ce50d8500f9b4e8a6e8d02e22d0475b574c3b3e9451a15f/sphinxcontrib_applehelp-1.0.4-py3-none-any.whl (from https://pypi.org/simple/sphinxcontrib-applehelp/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/c5/09/5de5ed43a521387f18bdf5f5af31d099605c992fd25372b2b9b825ce48ee/sphinxcontrib_devhelp-1.0.2-py2.py3-none-any.whl (from https://pypi.org/simple/sphinxcontrib-devhelp/)>
  ✔ Install sphinx-copybutton 0.5.2 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/6e/ee/a1f5e39046cbb5f8bc8fba87d1ddf1c6643fbc9194e58d26e606de4b9074/sphinxcontrib_htmlhelp-2.0.1-py3-none-any.whl (from https://pypi.org/simple/sphinxcontrib-htmlhelp/)>
  ✔ Install sphinxcontrib-devhelp 1.0.2 successful
  ✔ Install sphinxcontrib-applehelp 1.0.4 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/c2/42/4c8646762ee83602e3fb3fbe774c2fac12f317deb0b5dbeeedd2d3ba4b77/sphinxcontrib_jsmath-1.0.1-py2.py3-none-any.whl (from https://pypi.org/simple/sphinxcontrib-jsmath/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/2b/14/05f9206cf4e9cfca1afb5fd224c7cd434dcc3a433d6d9e4e0264d29c6cdb/sphinxcontrib_qthelp-1.0.3-py2.py3-none-any.whl (from https://pypi.org/simple/sphinxcontrib-qthelp/)>
  ✔ Install sphinxcontrib-htmlhelp 2.0.1 successful
  ✔ Install pytzdata 2020.1 successful
  ✔ Install sphinxcontrib-jsmath 1.0.1 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/c6/77/5464ec50dd0f1c1037e3c93249b040c8fc8078fdda97530eeb02424b6eea/sphinxcontrib_serializinghtml-1.1.5-py2.py3-none-any.whl (from https://pypi.org/simple/sphinxcontrib-serializinghtml/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/97/75/10a9ebee3fd790d20926a90a2547f0bf78f371b2f13aa822c759680ca7b9/tomli-2.0.1-py3-none-any.whl (from https://pypi.org/simple/tomli/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/a0/6d/808775ed618e51edaa7bbe6759e22e1c7eafe359af6e084700c6d39d3455/tomlkit-0.12.1-py3-none-any.whl (from https://pypi.org/simple/tomlkit/)>
  ✔ Install tomli 2.0.1 successful
  ✔ Install tomlkit 0.12.1 successful
  ✔ Install sphinxcontrib-qthelp 1.0.3 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/ec/6b/63cc3df74987c36fe26157ee12e09e8f9db4de771e0f3404263117e75b95/typing_extensions-4.7.1-py3-none-any.whl (from https://pypi.org/simple/typing-extensions/)>
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/c0/16/d5945c790f3ab4a7c32c7a5449d13abf4a0555926640bd5e9e2fbd5831e1/ujson-5.8.0-cp38-cp38-macosx_10_9_x86_64.whl (from https://pypi.org/simple/ujson/)>
  ✔ Install typing-extensions 4.7.1 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/9b/81/62fd61001fa4b9d0df6e31d47ff49cfa9de4af03adecf339c7bc30656b37/urllib3-2.0.4-py3-none-any.whl (from https://pypi.org/simple/urllib3/)>
  ✔ Install ujson 5.8.0 successful
  ✔ Install sphinxcontrib-serializinghtml 1.1.5 successful
  ✔ Install pytz 2023.3 successful
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/8c/08/d3006317aefe25ea79d3b76c9650afabaf6d63d1c8443b236e7405447503/zipp-3.16.2-py3-none-any.whl (from https://pypi.org/simple/zipp/)>
  ✔ Install babel 2.12.1 successful
  ✔ Install zipp 3.16.2 successful
  ✔ Install urllib3 2.0.4 successful
  ✔ Install ruff 0.0.286 successful
  ✔ Install sphinx 7.1.2 successful
Installing the project as an editable package...
pdm.termui: Preparing isolated env for PEP 517 build...
pdm.termui: Running PEP 517 backend to build a wheel for <Link file:///Users/tintvrtkovic/pg/cattrs (from None)>
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   hatchling
pdm.termui:   python>=3.11.1,<3.11.2
pdm.termui:   Adding requirement hatchling
pdm.termui:   Adding requirement python>=3.11.1,<3.11.2
pdm.termui: ======== Starting round 0 ========
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
pdm.termui:   Adding requirement editables>=0.3(from hatchling 1.18.0)
pdm.termui:   Adding requirement packaging>=21.3(from hatchling 1.18.0)
pdm.termui:   Adding requirement pathspec>=0.10.1(from hatchling 1.18.0)
pdm.termui:   Adding requirement pluggy>=1.0.0(from hatchling 1.18.0)
pdm.termui:   Adding requirement tomli>=1.2.2; python_version < "3.11"(from hatchling 1.18.0)
pdm.termui:   Adding requirement trove-classifiers(from hatchling 1.18.0)
pdm.termui: Pinning: hatchling 1.18.0
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
pdm.termui: Pinning: editables 0.5
pdm.termui: ======== Ending round 2 ========
pdm.termui: ======== Starting round 3 ========
pdm.termui: Pinning: packaging 23.2
pdm.termui: ======== Ending round 3 ========
pdm.termui: ======== Starting round 4 ========
pdm.termui: Pinning: pathspec 0.11.2
pdm.termui: ======== Ending round 4 ========
pdm.termui: ======== Starting round 5 ========
pdm.termui: Pinning: pluggy 1.3.0
pdm.termui: ======== Ending round 5 ========
pdm.termui: ======== Starting round 6 ========
pdm.termui: Pinning: tomli 2.0.1
pdm.termui: ======== Ending round 6 ========
pdm.termui: ======== Starting round 7 ========
pdm.termui: Pinning: trove-classifiers 2023.10.18
pdm.termui: ======== Ending round 7 ========
pdm.termui: ======== Starting round 8 ========
pdm.termui: ======== Resolution Result ========
pdm.termui: Stable pins:
pdm.termui:              python None
pdm.termui:           hatchling 1.18.0
pdm.termui:           editables 0.5
pdm.termui:           packaging 23.2
pdm.termui:            pathspec 0.11.2
pdm.termui:              pluggy 1.3.0
pdm.termui:               tomli 2.0.1
pdm.termui:   trove-classifiers 2023.10.18
pdm.termui: Installing editables@0.5...
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/6b/be/0f2f4a5e8adc114a02b63d92bf8edbfa24db6fc602fca83c885af2479e0e/editables-0.5-py3-none-any.whl (from https://pypi.org/simple/editables/)>
pdm.termui: Installing hatchling@1.18.0...
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/76/56/8ccca673e2c896931722f876bf040c0b6a7d8c1a128be60516a8a55bb27a/hatchling-1.18.0-py3-none-any.whl (from https://pypi.org/simple/hatchling/)>
pdm.termui: Installing packaging@23.2...
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/ec/1a/610693ac4ee14fcdf2d9bf3c493370e4f2ef7ae2e19217d7a237ff42367d/packaging-23.2-py3-none-any.whl (from https://pypi.org/simple/packaging/)>
pdm.termui: Installing pathspec@0.11.2...
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/b4/2a/9b1be29146139ef459188f5e420a66e835dda921208db600b7037093891f/pathspec-0.11.2-py3-none-any.whl (from https://pypi.org/simple/pathspec/)>
pdm.termui: Installing pluggy@1.3.0...
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/05/b8/42ed91898d4784546c5f06c60506400548db3f7a4b3fb441cba4e5c17952/pluggy-1.3.0-py3-none-any.whl (from https://pypi.org/simple/pluggy/)>
pdm.termui: Installing tomli@2.0.1...
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/97/75/10a9ebee3fd790d20926a90a2547f0bf78f371b2f13aa822c759680ca7b9/tomli-2.0.1-py3-none-any.whl (from https://pypi.org/simple/tomli/)>
pdm.termui: Installing trove-classifiers@2023.10.18...
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/ec/40/05cb2725ca7e6c844c66af626c5749efd254ec4506f17a1d01ba79ae9da6/trove_classifiers-2023.10.18-py3-none-any.whl (from https://pypi.org/simple/trove-classifiers/)>
pdm.termui: Synchronization complete.
  ✖ Install cattrs 23.2.0.dev0 failed
Traceback (most recent call last):
  File "/Users/tintvrtkovic/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/tintvrtkovic/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 290, in main
    return Core().main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tintvrtkovic/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 208, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/Users/tintvrtkovic/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 203, in main
    self.handle(project, options)
  File "/Users/tintvrtkovic/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 157, in handle
    command.handle(project, options)
  File "/Users/tintvrtkovic/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/cli/commands/install.py", line 100, in handle
    actions.do_sync(
  File "/Users/tintvrtkovic/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/cli/actions.py", line 214, in do_sync
    synchronizer.synchronize()
  File "/Users/tintvrtkovic/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/installers/synchronizers.py", line 462, in synchronize
    self.install_candidate(self_key, progress)
  File "/Users/tintvrtkovic/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/installers/synchronizers.py", line 283, in install_candidate
    self.manager.install(can)
  File "/Users/tintvrtkovic/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/installers/manager.py", line 33, in install
    installer(str(prepared.build()), self.environment, prepared.direct_url())
                  ^^^^^^^^^^^^^^^^
  File "/Users/tintvrtkovic/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/models/candidates.py", line 395, in build
    self.wheel = Path(builder.build(build_dir, metadata_directory=self._metadata_dir))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tintvrtkovic/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/builders/editable.py", line 39, in build
    requires = self._hook.get_requires_for_build_editable(config_settings)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tintvrtkovic/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pyproject_hooks/_impl.py", line 226, in get_requires_for_build_editable
    return self._call_hook('get_requires_for_build_editable', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tintvrtkovic/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pyproject_hooks/_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "/Users/tintvrtkovic/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
  File "/Users/tintvrtkovic/.asdf/installs/python/3.8.9/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'hatchling'
```

## Expected behavior

Auxiliary venvs should be created and set up properly.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
❯ pdm info
PDM version:
  2.9.3
Python Interpreter:
  /Users/tintvrtkovic/pg/cattrs/.venv/bin/python (3.11)
Project Root:
  /Users/tintvrtkovic/pg/cattrs
Local Packages:

❯ pdm info --env
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.1",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "22.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64",
  "python_full_version": "3.11.1",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
Duplicate #2314

**Comment by Tinche** [comment]
Apologies and thanks!
