### ISSUE TITLE
Problem installing perscache package

### ISSUE THREAD

**Issue by antonioloison** [pdm-project/pdm#2338]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

```bash
pdm add perscache
```

## Actual behavior

Returns this:
```
Adding packages to default dependencies: perscache
Inside an active virtualenv /Users/user/Project/.venv, reusing it.
Set env var PDM_IGNORE_ACTIVE_VENV to ignore it.
STATUS: Resolving dependencies
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   Jinja2>=3.1.2
pdm.termui:   perscache
pdm.termui:   python>=3.11,<3.13
pdm.termui:   Adding requirement Jinja2>=3.1.2
pdm.termui:   Adding requirement perscache
pdm.termui:   Adding requirement python>=3.11,<3.13
pdm.termui: ======== Starting round 0 ========
STATUS: Resolving: new pin python>=3.11,<3.13
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
pdm.termui:   Adding requirement MarkupSafe>=2.0(from Jinja2 3.1.2)
STATUS: Resolving: new pin Jinja2 3.1.2
pdm.termui: Pinning: Jinja2 3.1.2
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
pdm.termui:   Adding requirement beartype(from perscache 0.6.1)
pdm.termui:   Adding requirement cloudpickle(from perscache 0.6.1)
pdm.termui:   Adding requirement icontract(from perscache 0.6.1)
STATUS: Resolving: new pin perscache 0.6.1
pdm.termui: Pinning: perscache 0.6.1
pdm.termui: ======== Ending round 2 ========
pdm.termui: ======== Starting round 3 ========
Traceback (most recent call last):
  File "/opt/homebrew/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.10.0/libexec/lib/python3.11/site-packages/pdm/core.py", line 295, in main
    return Core().main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.10.0/libexec/lib/python3.11/site-packages/pdm/core.py", line 208, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/opt/homebrew/Cellar/pdm/2.10.0/libexec/lib/python3.11/site-packages/pdm/core.py", line 203, in main
    self.handle(project, options)
  File "/opt/homebrew/Cellar/pdm/2.10.0/libexec/lib/python3.11/site-packages/pdm/core.py", line 157, in handle
    command.handle(project, options)
  File "/opt/homebrew/Cellar/pdm/2.10.0/libexec/lib/python3.11/site-packages/pdm/cli/commands/add.py", line 69, in handle
    self.do_add(
  File "/opt/homebrew/Cellar/pdm/2.10.0/libexec/lib/python3.11/site-packages/pdm/cli/commands/add.py", line 162, in do_add
    resolved = do_lock(
               ^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.10.0/libexec/lib/python3.11/site-packages/pdm/cli/actions.py", line 99, in do_lock
    mapping, dependencies = resolve(
                            ^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.10.0/libexec/lib/python3.11/site-packages/pdm/resolver/core.py", line 36, in resolve
    result = resolver.resolve(requirements, max_rounds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.10.0/libexec/lib/python3.11/site-packages/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.10.0/libexec/lib/python3.11/site-packages/resolvelib/resolvers.py", line 426, in resolve
    name = min(unsatisfied_names, key=self._get_preference)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.10.0/libexec/lib/python3.11/site-packages/resolvelib/resolvers.py", line 203, in _get_preference
    return self._p.get_preference(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.10.0/libexec/lib/python3.11/site-packages/pdm/resolver/providers.py", line 92, in get_preference
    deps = self.get_dependencies(candidate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.10.0/libexec/lib/python3.11/site-packages/pdm/resolver/providers.py", line 209, in get_dependencies
    deps, requires_python, _ = self.repository.get_dependencies(candidate)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.10.0/libexec/lib/python3.11/site-packages/pdm/models/repositories.py", line 103, in get_dependencies
    requirements, requires_python, summary = getter(candidate)
                                             ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.10.0/libexec/lib/python3.11/site-packages/pdm/models/repositories.py", line 46, in wrapper
    result = func(self, candidate)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.10.0/libexec/lib/python3.11/site-packages/pdm/models/repositories.py", line 279, in _get_dependencies_from_metadata
    deps = prepared.get_dependencies_from_metadata()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.10.0/libexec/lib/python3.11/site-packages/pdm/models/candidates.py", line 603, in get_dependencies_from_metadata
    return filter_requirements_with_extras(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.10.0/libexec/lib/python3.11/site-packages/pdm/models/requirements.py", line 451, in filter_requirements_with_extras
    _r = parse_requirement(req)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.10.0/libexec/lib/python3.11/site-packages/pdm/models/requirements.py", line 506, in parse_requirement
    r = Requirement.from_pkg_requirement(pkg_req)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.10.0/libexec/lib/python3.11/site-packages/pdm/models/requirements.py", line 230, in from_pkg_requirement
    return NamedRequirement(**kwargs)  # type: ignore[arg-type]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 9, in __init__
  File "/opt/homebrew/Cellar/pdm/2.10.0/libexec/lib/python3.11/site-packages/pdm/models/requirements.py", line 89, in __post_init__
    self.requires_python = self.marker.split_pyspec()[1] if self.marker else PySpecSet()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.10.0/libexec/lib/python3.11/site-packages/pdm/models/markers.py", line 42, in split_pyspec
    return marker, _build_pyspec_from_marker(join_list_with(py_markers, "and"))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.10.0/libexec/lib/python3.11/site-packages/pdm/models/markers.py", line 132, in _build_pyspec_from_marker
    int_versions = [int(ver) for ver in version.split(".")]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.10.0/libexec/lib/python3.11/site-packages/pdm/models/markers.py", line 132, in <listcomp>
    int_versions = [int(ver) for ver in version.split(".")]
                    ^^^^^^^^
ValueError: invalid literal for int() with base 10: '=3'
```

## Environment Information

Tried on pdm versions `2.10.0` and `2.9.3` and had the same behaviour

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.10.0
Python Interpreter:
  /Users/user/Project/.venv/bin/python (3.11)
Project Root:
  /Users/user/Project/
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.6",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "23.0.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000",
  "python_full_version": "3.11.6",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "darwin"
}
```

**Comment by pawamoy** [comment]
Caused by this line: https://github.com/Parquery/icontract/blob/master/setup.py#L70

```
'deal==4.23.3;python_version>"=3.8"',
```

**Comment by frostming** [comment]
> Caused by this line: https://github.com/Parquery/icontract/blob/master/setup.py#L70
> 
> 
> 
> ```
> 
> 'deal==4.23.3;python_version>"=3.8"',
> 
> ```

How many such corruptted metadata has pip let go?

**Comment by pawamoy** [comment]
Too many :laughing:
