### ISSUE TITLE
Error after updating  from PDM 2.9 to PDM 2.10: No module named 'pyproject_hooks' 

### ISSUE THREAD

**Issue by bolinocroustibat** [pdm-project/pdm#2348]
## Issue description

After updated PDM from 2.9 to 2.10 with MacOS Homebrew, I cannot launch PDM nor get the PDM version, I get the following error:
```bash
ModuleNotFoundError: No module named 'pyproject_hooks'
```

## Environment

MacOS 14.0 with system Python 3.11.6 and Homebrew 4.1.18-11-g729a6d4

## Detailed output

```bash
Traceback (most recent call last):
  File "/usr/local/bin/pdm", line 5, in <module>
    from pdm.core import main
  File "/usr/local/Cellar/pdm/2.10.0_1/libexec/lib/python3.12/site-packages/pdm/core.py", line 24, in <module>
    from pdm.cli.utils import ArgumentParser, ErrorArgumentParser
  File "/usr/local/Cellar/pdm/2.10.0_1/libexec/lib/python3.12/site-packages/pdm/cli/utils.py", line 40, in <module>
    from pdm.project.lockfile import FLAG_CROSS_PLATFORM, FLAG_STATIC_URLS
  File "/usr/local/Cellar/pdm/2.10.0_1/libexec/lib/python3.12/site-packages/pdm/project/__init__.py", line 2, in <module>
    from pdm.project.core import Project
  File "/usr/local/Cellar/pdm/2.10.0_1/libexec/lib/python3.12/site-packages/pdm/project/core.py", line 21, in <module>
    from pdm.models.repositories import BaseRepository, LockedRepository
  File "/usr/local/Cellar/pdm/2.10.0_1/libexec/lib/python3.12/site-packages/pdm/models/repositories.py", line 14, in <module>
    from pdm.models.candidates import Candidate, make_candidate
  File "/usr/local/Cellar/pdm/2.10.0_1/libexec/lib/python3.12/site-packages/pdm/models/candidates.py", line 17, in <module>
    from pdm.builders import EditableBuilder, WheelBuilder
  File "/usr/local/Cellar/pdm/2.10.0_1/libexec/lib/python3.12/site-packages/pdm/builders/__init__.py", line 1, in <module>
    from pdm.builders.editable import EditableBuilder
  File "/usr/local/Cellar/pdm/2.10.0_1/libexec/lib/python3.12/site-packages/pdm/builders/editable.py", line 6, in <module>
    from pyproject_hooks import HookMissing
ModuleNotFoundError: No module named 'pyproject_hooks'
```

**Comment by xzmeng** [comment]
try `brew install python-pyproject-hooks`

**Comment by xzmeng** [comment]
I encountered a similar situation, in my case it is `certifi` (`python-certifi` in homebrew).

After some investigation, I suspect it is caused by the migration to Python 3.12:
https://github.com/Homebrew/homebrew-core/commit/a634a94b22fc3a30db4a87544bd7cf93f400ea6b

So you might need to upgrade or reinstall the `python-*` (* denotes the module not found) to let it placed in the `3.12` site-package path.

**Comment by bolinocroustibat** [comment]
I also suspects it is caused by the migration to Python 3.12.
However, my system Python is 3.11, I'm not sure on how to install dependencies for the Python 3.12 version on my system.
Shouldn't that be fixed on PDM's side instead?

**Comment by frostming** [comment]
> Shouldn't that be fixed on PDM's side instead?

No, homebrew decide to install some dependencies with the package while others separately, that is not controlled by PDM.
