### ISSUE TITLE
NotImplementedError for ` pdm export -f setuppy -v`

### ISSUE THREAD

**Issue by cauliyang** [pdm-project/pdm#2354]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

`pdm export -f setuppy -v`

## Actual behavior

```
❯ pdm export -f setuppy -v                                                                 15:27:25
The exported requirements file is no longer cross-platform. Using it on other platforms may cause
unexpected result.
STATUS: Resolving packages from lockfile...
STATUS: Fetching hashes for resolved packages...
Traceback (most recent call last):
  File "/Users/ylk4626/miniforge3/envs/pyblat/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/Users/ylk4626/miniforge3/envs/pyblat/lib/python3.9/site-packages/pdm/core.py", line 295, in main
    return Core().main(args or sys.argv[1:])
  File "/Users/ylk4626/miniforge3/envs/pyblat/lib/python3.9/site-packages/pdm/core.py", line 208, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/Users/ylk4626/miniforge3/envs/pyblat/lib/python3.9/site-packages/pdm/core.py", line 203, in main
    self.handle(project, options)
  File "/Users/ylk4626/miniforge3/envs/pyblat/lib/python3.9/site-packages/pdm/core.py", line 157, in handle
    command.handle(project, options)
  File "/Users/ylk4626/miniforge3/envs/pyblat/lib/python3.9/site-packages/pdm/cli/commands/export.py", line 74, in handle
    content = FORMATS[options.format].export(project, packages, options)
  File "/Users/ylk4626/miniforge3/envs/pyblat/lib/python3.9/site-packages/pdm/formats/setup_py.py", line 64, in export
    raise NotImplementedError()
NotImplementedError

```

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
❯ pdm info && pdm info --env                                                               15:27:30
PDM version:
  2.10.0
Python Interpreter:
  /Users/ylk4626/miniforge3/envs/pyblat/bin/python (3.9)
Project Root:
  /Users/ylk4626/ClionProjects/pxblat
Local Packages:

/Users/ylk4626/miniforge3/envs/pyblat/lib/python3.9/site-packages/pdm/cli/actions.py:319: RuntimeWarning: Failed to get latest version: cannot import name 'appengine' from 'urllib3.contrib' (/Users/ylk4626/miniforge3/envs/pyblat/lib/python3.9/site-packages/urllib3/contrib/__init__.py)
  warnings.warn(f"Failed to get latest version: {e}", RuntimeWarning, stacklevel=1)
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.16",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "23.0.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023;
root:xnu-10002.1.13~1/RELEASE_ARM64_T6000",
  "python_full_version": "3.9.16",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "darwin"
}
/Users/ylk4626/miniforge3/envs/pyblat/lib/python3.9/site-packages/pdm/cli/actions.py:319: RuntimeWarning: Failed to get latest version: cannot import name 'appengine' from 'urllib3.contrib' (/Users/ylk4626/miniforge3/envs/pyblat/lib/python3.9/site-packages/urllib3/contrib/__init__.py)
  warnings.warn(f"Failed to get latest version: {e}", RuntimeWarning, stacklevel=1)

```

**Comment by xzmeng** [comment]
Accoding to the [documentation](https://pdm.fming.dev/latest/usage/dependency/#export-locked-packages-to-alternative-formats), exporting `setup.py` is not supported yet:

> Currently, only requirements.txt format is supported
