### ISSUE TITLE
pdm install ModuleNotFoundError: No module named 'certifi' error

### ISSUE THREAD

**Issue by bahadiraraz** [pdm-project/pdm#2361]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

I ran pdm install on pdm 2.10.0.

## Actual behavior

```Traceback (most recent call last):
  File "/opt/homebrew/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.10.0_1/libexec/lib/python3.12/site-packages/pdm/core.py", line 295, in main
    return Core().main(args or sys.argv[1:])
           ^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.10.0_1/libexec/lib/python3.12/site-packages/pdm/core.py", line 57, in __init__
    self.init_parser()
  File "/opt/homebrew/Cellar/pdm/2.10.0_1/libexec/lib/python3.12/site-packages/pdm/core.py", line 87, in init_parser
    module = importlib.import_module(f"pdm.cli.commands.{name}", __name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.0/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/homebrew/Cellar/pdm/2.10.0_1/libexec/lib/python3.12/site-packages/pdm/cli/commands/use.py", line 10, in <module>
    from pdm.models.caches import JSONFileCache
  File "/opt/homebrew/Cellar/pdm/2.10.0_1/libexec/lib/python3.12/site-packages/pdm/models/caches.py", line 12, in <module>
    from cachecontrol.cache import SeparateBodyBaseCache
  File "/opt/homebrew/Cellar/pdm/2.10.0_1/libexec/lib/python3.12/site-packages/cachecontrol/__init__.py", line 13, in <module>
    from cachecontrol.adapter import CacheControlAdapter
  File "/opt/homebrew/Cellar/pdm/2.10.0_1/libexec/lib/python3.12/site-packages/cachecontrol/adapter.py", line 11, in <module>
    from requests.adapters import HTTPAdapter
  File "/opt/homebrew/Cellar/pdm/2.10.0_1/libexec/lib/python3.12/site-packages/requests/__init__.py", line 147, in <module>
    from . import packages, utils
  File "/opt/homebrew/Cellar/pdm/2.10.0_1/libexec/lib/python3.12/site-packages/requests/utils.py", line 24, in <module>
    from . import certs
  File "/opt/homebrew/Cellar/pdm/2.10.0_1/libexec/lib/python3.12/site-packages/requests/certs.py", line 14, in <module>
    from certifi import where
ModuleNotFoundError: No module named 'certifi'```

## Expected behavior

it was supposed to work normally

## Environment Information

```bash
```Traceback (most recent call last):
  File "/opt/homebrew/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.10.0_1/libexec/lib/python3.12/site-packages/pdm/core.py", line 295, in main
    return Core().main(args or sys.argv[1:])
           ^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.10.0_1/libexec/lib/python3.12/site-packages/pdm/core.py", line 57, in __init__
    self.init_parser()
  File "/opt/homebrew/Cellar/pdm/2.10.0_1/libexec/lib/python3.12/site-packages/pdm/core.py", line 87, in init_parser
    module = importlib.import_module(f"pdm.cli.commands.{name}", __name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.0/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/homebrew/Cellar/pdm/2.10.0_1/libexec/lib/python3.12/site-packages/pdm/cli/commands/use.py", line 10, in <module>
    from pdm.models.caches import JSONFileCache
  File "/opt/homebrew/Cellar/pdm/2.10.0_1/libexec/lib/python3.12/site-packages/pdm/models/caches.py", line 12, in <module>
    from cachecontrol.cache import SeparateBodyBaseCache
  File "/opt/homebrew/Cellar/pdm/2.10.0_1/libexec/lib/python3.12/site-packages/cachecontrol/__init__.py", line 13, in <module>
    from cachecontrol.adapter import CacheControlAdapter
  File "/opt/homebrew/Cellar/pdm/2.10.0_1/libexec/lib/python3.12/site-packages/cachecontrol/adapter.py", line 11, in <module>
    from requests.adapters import HTTPAdapter
  File "/opt/homebrew/Cellar/pdm/2.10.0_1/libexec/lib/python3.12/site-packages/requests/__init__.py", line 147, in <module>
    from . import packages, utils
  File "/opt/homebrew/Cellar/pdm/2.10.0_1/libexec/lib/python3.12/site-packages/requests/utils.py", line 24, in <module>
    from . import certs
  File "/opt/homebrew/Cellar/pdm/2.10.0_1/libexec/lib/python3.12/site-packages/requests/certs.py", line 14, in <module>
    from certifi import where
ModuleNotFoundError: No module named 'certifi'```

```

**Comment by xzmeng** [comment]
try
```
brew upgrade $(brew deps -1 pdm)
```

See https://github.com/pdm-project/pdm/issues/2348

**Comment by bahadiraraz** [comment]
> try
> 
> ```
> brew upgrade $(brew deps -1 pdm)
> ```
> 
> See #2348

it is work tnx
