### ISSUE TITLE
Wheel package installation results in InvalidVersion

### ISSUE THREAD

**Issue by liran-cohen-hs** [pdm-project/pdm#2375]
- [V] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

`pip wheel . -w wheels` to create internal package as wheel
then `pdm add "celery @ <github_url>/releases/download/HS_4.4.9-wheel/celery-HS_4.4.9-py2.py3-none-any.whl"`

## Actual behavior

I get this error:
```
Traceback (most recent call last):
  File "/opt/homebrew/opt/python-packaging/lib/python3.12/site-packages/packaging/utils.py", line 126, in parse_wheel_filename
    version = Version(parts[1])
              ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/python-packaging/lib/python3.12/site-packages/packaging/version.py", line 200, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: 'HS_4.4.9'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.0/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.10.0_1/libexec/lib/python3.12/site-packages/pdm/installers/synchronizers.py", line 286, in install_candidate
    self.manager.install(can)
  File "/opt/homebrew/Cellar/pdm/2.10.0_1/libexec/lib/python3.12/site-packages/pdm/installers/manager.py", line 33, in install
    installer(str(prepared.build()), self.environment, prepared.direct_url())
                  ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.10.0_1/libexec/lib/python3.12/site-packages/pdm/models/candidates.py", line 389, in build
    self.obtain(allow_all=False)
  File "/opt/homebrew/Cellar/pdm/2.10.0_1/libexec/lib/python3.12/site-packages/pdm/models/candidates.py", line 421, in obtain
    if not self.link or self.link.is_wheel and not self._wheel_compatible(self.link.filename, allow_all):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.10.0_1/libexec/lib/python3.12/site-packages/pdm/models/candidates.py", line 668, in _wheel_compatible
    file_tags = parse_wheel_filename(wheel_file)[-1]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/python-packaging/lib/python3.12/site-packages/packaging/utils.py", line 128, in parse_wheel_filename
    raise InvalidWheelFilename(
packaging.utils.InvalidWheelFilename: Invalid wheel filename (invalid version): celery-HS_4.4.9-py2.py3-none-any
```
## Expected behavior

if installing by tag (same version) it works:
`pdm add "celery@<github_url>/celery@HS_4.4.9#egg=celery"`
if installing the wheel ("celery @ <github_url>/releases/download/HS_4.4.9-wheel/celery-HS_4.4.9-py2.py3-none-any.whl") with pip it works

## Environment Information

```bash
PDM version:
  2.10.0
Python Interpreter:
  /Users/liran/hiredscore/git/pdm-wheel-test/.venv/bin/python (3.9)
Project Root:
  /Users/liran/hiredscore/git/pdm-wheel-test
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.16",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "22.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000",
  "python_full_version": "3.9.16",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "darwin"
}

```

**Comment by frostming** [comment]
The version number is not valid PEP 440 and is rejected by the `pypa` standard `packaging` module.
However, `pip` is too lenient in this regard to the extent that people consider this file name to be legal.

PDM will keep as it is.
