### ISSUE TITLE
permission denied on `pdm init` if the template file is read-only

### ISSUE THREAD

**Issue by natsukium** [pdm-project/pdm#2385]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

`pdm init` will not work properly if pdm is installed on a read-only filesystem.

This was reported in the following issue of NixOS/nixpkgs.
https://github.com/NixOS/nixpkgs/issues/265883

The nix package manager puts all software in an immutable, read-only store. This is no exception for something like a template file, and when I install pdm with nix, the templates copied by `pdm init` are also read-only.

Reading the source code, I found that `pdm init` uses `shutil.copy2` to replicate the template with permissions.

https://github.com/pdm-project/pdm/blob/90aadf0bd1059241b31235bd2d88e329cafeaac3/src/pdm/cli/templates/__init__.py#L91-L96

https://github.com/pdm-project/pdm/blob/90aadf0bd1059241b31235bd2d88e329cafeaac3/src/pdm/cli/templates/__init__.py#L111-L116

As mentioned above, nix makes the template read-only, so when the file is opened for writing in a later process, a permission denied error occurs, as shown in the title.

I have found that even if I install pdm using an officially supported method, a similar error occurs. For example, if the template is in the local system user environment and a non-root user does not have write access to it.

For example, can we replace `shutil.copy2` with `shutil.copyfile`? Or is there a reason why permissions need to be kept in place?

## Steps to reproduce

`pdm init -n --lib /path/to/templates`

If you can use nix,
`nix run nixpkgs#pdm -- init -n --lib`

## Actual behavior

with nix
```
Traceback (most recent call last):
  File "/nix/store/20fymyb3663ri7lpz85p5ym82amb5yg3-pdm-2.10.0/bin/.pdm-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/20fymyb3663ri7lpz85p5ym82amb5yg3-pdm-2.10.0/lib/python3.11/site-packages/pdm/core.py", line 295, in main
    return Core().main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/20fymyb3663ri7lpz85p5ym82amb5yg3-pdm-2.10.0/lib/python3.11/site-packages/pdm/core.py", line 208, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/nix/store/20fymyb3663ri7lpz85p5ym82amb5yg3-pdm-2.10.0/lib/python3.11/site-packages/pdm/core.py", line 203, in main
    self.handle(project, options)
  File "/nix/store/20fymyb3663ri7lpz85p5ym82amb5yg3-pdm-2.10.0/lib/python3.11/site-packages/pdm/core.py", line 157, in handle
    command.handle(project, options)
  File "/nix/store/20fymyb3663ri7lpz85p5ym82amb5yg3-pdm-2.10.0/lib/python3.11/site-packages/pdm/cli/commands/init.py", line 247, in handle
    self.do_init(project, options=options)
  File "/nix/store/20fymyb3663ri7lpz85p5ym82amb5yg3-pdm-2.10.0/lib/python3.11/site-packages/pdm/cli/commands/init.py", line 38, in do_init
    self._init_builtin(project, options)
  File "/nix/store/20fymyb3663ri7lpz85p5ym82amb5yg3-pdm-2.10.0/lib/python3.11/site-packages/pdm/cli/commands/init.py", line 82, in _init_builtin
    template.generate(project.root, metadata, options.overwrite)
  File "/nix/store/20fymyb3663ri7lpz85p5ym82amb5yg3-pdm-2.10.0/lib/python3.11/site-packages/pdm/cli/templates/__init__.py", line 72, in generate
    replace_all(os.path.join(root, f), original_name, new_name)
  File "/nix/store/20fymyb3663ri7lpz85p5ym82amb5yg3-pdm-2.10.0/lib/python3.11/site-packages/pdm/cli/templates/__init__.py", line 44, in replace_all
    with open(path, "w", encoding=encoding) as fp:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/tmp/pdm-sww2i9h3-template/README.md'
```

## Environment Information

I checked with pdm version 2.10 and 2.10.1, but it should have existed since 2.8.0 when the template feature was introduced.

```bash
# Paste the output of `pdm info && pdm info --env` below:

```

**Comment by frostming** [comment]
you are late #2379
