### ISSUE TITLE
ImportError: cannot import name 

### ISSUE THREAD

**Issue by defp** [pdm-project/pdm#2433]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

```

start spider:  spiders.news.news_21
Traceback (most recent call last):
  File "/Users/lidashuang/Projects/nocode/kg-data-spider/custom_spider.py", line 25, in <module>
    importlib.import_module(f"{name}").run()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lidashuang/.asdf/installs/python/3.11.1/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/lidashuang/Projects/nocode/kg-data-spider/spiders/news/news_21.py", line 5, in <module>
    from loguru import logger
ImportError: cannot import name 'logger' from 'loguru' (unknown location)
```

the loguru exist in __pypackages__

```
__pypackages__/3.11/lib/loguru:
__pycache__

__pypackages__/3.11/lib/loguru-0.7.2.dist-info:
LICENSE		METADATA	RECORD		REFER_TO	WHEEL		top_level.txt
```

## Environment Information

```bash
PDM version:
  2.10.4
Python Interpreter:
  /Users/lidashuang/.asdf/installs/python/3.11.1/bin/python3.11 (3.11)
Project Root:
  /Users/lidashuang/Projects/nocode/kg-data-spider
Local Packages:
  /Users/lidashuang/Projects/nocode/kg-data-spider/__pypackages__/3.11
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.1",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "23.0.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:34 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8103",
  "python_full_version": "3.11.1",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "darwin"
}

```

change to venv  also the same error

**Comment by defp** [comment]
change a ubuntu linux server, it works

**Comment by defp** [comment]
my pyproject.toml
```
[project]
name = "kg-data-spider"
version = "1.0.0"
description = "spider"
authors = [
    {name = "dåshuång li", email = "li.dashuang@icloud.com"},
]
dependencies = [
    "colorlog==4.1.0",
    "pydash==4.9.0",
    "python-dotenv==0.21.0",
    "python-dateutil==2.8.2",
    "requests==2.27.1",
    "w3lib>=2.1.2",
    "loguru>=0.7.2",
    "httpx>=0.23.1",
    "redis>=5.0.1",
    "user-agent>=0.1.10",
    "scrapy>=2.8.0",
    "flake8>=6.0.0",
    "openai>=0.26.5",
    "yapf>=0.32.0",
    "selenium>=4.10.0",
    "bd09convertor>=0.0.3",
    "pyppeteer>=1.0.2",
    "oss2>=2.18.0",
    "markdownify>=0.11.6",
    "jsonpath-ng>=1.5.3",
    "feedparser>=6.0.10",
    "PyPDF2>=3.0.1",
    "openpyxl>=3.1.2",
    "zhconv>=1.4.3",
    "xlrd>=2.0.1",
    "beautifulsoup4>=4.12.2",
    "lxml>=4.9.3",
    "html5lib>=1.1",
    "pytest-playwright>=0.4.3",
    "playwright>=1.27.1",
    "bbpb==1.0.1",
    "sentry-sdk>=1.33.1",
    "retry>=0.9.2",
    "chardet>=5.2.0",
    "retrying>=1.3.4",
    "json5>=0.9.14",
]
requires-python = ">=3.10"
license = {text = "MIT"}
[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"


[tool]
[tool.pdm]

[tool.pdm.dev-dependencies]
lint = [
    "flake8",
    "black"
]
dev = [
    "black>=22.10.0",
    "flake8>=5.0.4",
    "yaml2jsonnet>=1.0.1",
]


[tool.pyright]
extraPaths = ["__pypackages__/3.11/lib/"]
exclude = ["__pypackages__"]
venvPath = "."
venv = ".venv"


[tool.pdm.scripts]
tk_show = {shell = "cd cronjob && tk show environments/prod/ --ext-str"}

dev_spider.cmd = "python main.py run --name={args}"
dev_spider.env_file = ".env.dev"

dev_custom_spider.cmd = "python custom_spider.py {args}"
dev_custom_spider.env_file = ".env.dev"

prod_spider.cmd = "python main.py run --name={args}"
prod_spider.env_file = ".env.prod"

chictr_detail_dev.cmd = "python spiders/clinical_trial/chictr_detail.py"
chictr_detail_dev.env_file = ".env.dev"

who_dev.cmd = "python spiders/clinical_trial/who.py"
who_dev.env_file = ".env.dev"
```

**Comment by frostming** [comment]
> error message

You still didn't show what command you run to trigger this message. Why did you omit that?

**Comment by frostming** [comment]
> _.env_file = ".env"
> runserver.cmd = "python manage.py runserver"
> runserver.env_file = ".env"

Did you change any python env in the .env file?

**Comment by defp** [comment]
no change python env, all pdm run command has problem
I changed system to ubuntu server, it works

**Comment by defp** [comment]
pdm config  example

```
Site/default configuration (/Library/Application Support/pdm/config.toml):
build_isolation = True
cache_dir = /Users/lidashuang/Library/Caches/pdm
check_update = True
global_project.fallback = False
global_project.fallback_verbose = True
global_project.path = /Users/lidashuang/Library/Application Support/pdm/global-project
global_project.user_site = False
install.cache = False
install.cache_method = symlink
install.parallel = True
pypi.ignore_stored_index = False
pypi.json_api = False
pypi.url = https://pypi.org/simple
pypi.verify_ssl = True
python.providers = ['venv', 'path', 'asdf', 'pyenv', 'rye', 'winreg', 'macos']
python.use_pyenv = True
python.use_venv = True
strategy.resolve_max_rounds = 10000
strategy.save = minimum
strategy.update = reuse
theme.error = red
theme.info = blue
theme.primary = cyan
theme.req = bold green
theme.success = green
theme.warning = yellow
venv.backend = virtualenv
venv.in_project = True
venv.location = /Users/lidashuang/Library/Application Support/pdm/venvs
venv.prompt = {project_name}-{python_version}
venv.with_pip = False

Home configuration (/Users/lidashuang/Library/Application Support/pdm/config.toml):
cache_dir = /tmp/cache
install.cache = True
pypi.url = https://pypi.tuna.tsinghua.edu.cn/simple
python.use_venv = False
venv.backend = venv

Project configuration (/Users/lidashuang/Projects/nocode-devops/ops-center/pdm.toml):
```

**Comment by defp** [comment]
https://github.com/pdm-project/pdm/pull/2425/files 
It works with 
```
pdm config install.cache_method hardlink 
```

**Comment by fancyerii** [comment]
@defp 
why it works? if install.cache False, then install.cache_method is useless.

**Comment by defp** [comment]
@fancyerii 也不清楚啥原因, 各种尝试, 我后边都用 venv了

**Comment by fancyerii** [comment]
venv的版本管理功能没有，过一阵依赖升级就挂了。如果你用venv，可以试试pipenv。但是它没有cache功能，每次新建一个项目都得重新安装。这个对我来说不可接受，每次安装pytorch都是很久时间，也浪费空间。就是因为有这个功能才尝试pdm的。

**Comment by defp** [comment]
@fancyerii 我还是用pdm, 只不过从__pypackages__  换成 了 venv模式

**Comment by fancyerii** [comment]
@defp  我现在用的就是venv模式。但是cache功能还是不能用。
