### ISSUE TITLE
brew build for 2.10.4 seems to be broken

### ISSUE THREAD

**Issue by byteSamurai** [pdm-project/pdm#2441]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Install pdm on macOS with
```
brew install pdm
```

## Actual behavior

PDM is currently unusable:
```
❯ pdm                                                                                              
Traceback (most recent call last):
  File "/usr/local/bin/pdm", line 5, in <module>
    from pdm.core import main
  File "/usr/local/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/core.py", line 24, in <module>
    from pdm.cli.utils import ArgumentParser, ErrorArgumentParser
  File "/usr/local/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/cli/utils.py", line 40, in <module>
    from pdm.project.lockfile import FLAG_CROSS_PLATFORM, FLAG_STATIC_URLS
  File "/usr/local/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/project/__init__.py", line 1, in <module>
    from pdm.project.config import Config, ConfigItem
  File "/usr/local/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/project/config.py", line 94, in <module>
    class Config(MutableMapping[str, str]):
  File "/usr/local/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/project/config.py", line 100, in Config
    platformdirs.user_cache_dir("pdm"),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'platformdirs' has no attribute 'user_cache_dir'
```

## Expected behavior

PDM is usable

## Environment Information

```bash
❯ pdm info && pdm info --env                                                                    
Traceback (most recent call last):
  File "/usr/local/bin/pdm", line 5, in <module>
    from pdm.core import main
  File "/usr/local/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/core.py", line 24, in <module>
    from pdm.cli.utils import ArgumentParser, ErrorArgumentParser
  File "/usr/local/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/cli/utils.py", line 40, in <module>
    from pdm.project.lockfile import FLAG_CROSS_PLATFORM, FLAG_STATIC_URLS
  File "/usr/local/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/project/__init__.py", line 1, in <module>
    from pdm.project.config import Config, ConfigItem
  File "/usr/local/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/project/config.py", line 94, in <module>
    class Config(MutableMapping[str, str]):
  File "/usr/local/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/project/config.py", line 100, in Config
    platformdirs.user_cache_dir("pdm"),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'platformdirs' has no attribute 'user_cache_dir'

```

**Comment by frostming** [comment]
Also I don't think it's an issue with homebrew, since it is included by the sanity tests: https://github.com/Homebrew/homebrew-core/blob/8495e7e8cdcbcc2ea7e15e28fff899117db8614e/Formula/p/pdm.rb#L138-L155
