### ISSUE TITLE
After update to 2.10.4 with brew pdm command fails

### ISSUE THREAD

**Issue by danielmoessner** [pdm-project/pdm#2451]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

I just used `brew update` and afterwards `brew reinstall pdm`

Sadly I can somehow not install a previous version with brew? If sb knows a way I could check the older version again that was working fine.

## Actual behavior

```
% pdm install -v                                                          
Traceback (most recent call last):
  File "/opt/homebrew/bin/pdm", line 5, in <module>
    from pdm.core import main
  File "/opt/homebrew/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/core.py", line 24, in <module>
    from pdm.cli.utils import ArgumentParser, ErrorArgumentParser
  File "/opt/homebrew/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/cli/utils.py", line 40, in <module>
    from pdm.project.lockfile import FLAG_CROSS_PLATFORM, FLAG_STATIC_URLS
  File "/opt/homebrew/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/project/__init__.py", line 1, in <module>
    from pdm.project.config import Config, ConfigItem
  File "/opt/homebrew/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/project/config.py", line 94, in <module>
    class Config(MutableMapping[str, str]):
  File "/opt/homebrew/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/project/config.py", line 100, in Config
    platformdirs.user_cache_dir("pdm"),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'platformdirs' has no attribute 'user_cache_dir'
```

## Expected behavior

I get the same error above on every pdm command.

## Environment Information

pdm 2.10.4
Python 3.11
MacOS M1

**Comment by danielmoessner** [comment]
I see this is a problem with pdm using Python 3.12 in this version. How can I force pdm to use python 3.11?

Event in pyproject.toml I have the following setting configured:
`requires-python = "==3.11.*"`

**Comment by danielmoessner** [comment]
Running brew test pdm:


```
% brew test pdm
Warning: test is a developer command, so Homebrew's
developer mode has been automatically turned on.
To turn developer mode off, run:
  brew developer off

==> Installing 'bundler' gem
Fetching bundler-2.4.18.gem
Fetching gem metadata from https://rubygems.org/.......
Fetching concurrent-ruby 1.2.2
Fetching minitest 5.20.0
Fetching zeitwerk 2.6.12
Fetching public_suffix 5.0.4
Installing zeitwerk 2.6.12
Fetching bindata 2.4.15
Installing minitest 5.20.0
Installing public_suffix 5.0.4
Fetching did_you_mean 1.6.3
Fetching plist 3.7.0
Installing bindata 2.4.15
Installing plist 3.7.0
Installing did_you_mean 1.6.3
Installing concurrent-ruby 1.2.2
Fetching ruby-macho 4.0.0
Fetching sorbet-runtime 0.5.10461
Installing ruby-macho 4.0.0
Fetching warning 1.3.0
Installing sorbet-runtime 0.5.10461
Fetching addressable 2.8.5
Installing warning 1.3.0
Fetching elftools 1.2.0
Installing addressable 2.8.5
Installing elftools 1.2.0
Fetching tzinfo 2.0.6
Fetching i18n 1.14.1
Fetching patchelf 1.4.0
Installing i18n 1.14.1
Installing patchelf 1.4.0
Installing tzinfo 2.0.6
Fetching activesupport 6.1.7.6
Installing activesupport 6.1.7.6
Bundle complete! 37 Gemfile dependencies, 17 gems now installed.
Bundled gems are installed into `../../../../../opt/homebrew/Library/Homebrew/vendor/bundle`
==> Testing pdm
==> /opt/homebrew/Cellar/pdm/2.10.4/bin/pdm add requests==2.31.0
Last 15 lines from /Users/d505891/Library/Logs/Homebrew/pdm/test.01.pdm:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pdm/2.10.4/bin/pdm", line 5, in <module>
    from pdm.core import main
  File "/opt/homebrew/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/core.py", line 24, in <module>
    from pdm.cli.utils import ArgumentParser, ErrorArgumentParser
  File "/opt/homebrew/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/cli/utils.py", line 40, in <module>
    from pdm.project.lockfile import FLAG_CROSS_PLATFORM, FLAG_STATIC_URLS
  File "/opt/homebrew/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/project/__init__.py", line 1, in <module>
    from pdm.project.config import Config, ConfigItem
  File "/opt/homebrew/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/project/config.py", line 94, in <module>
    class Config(MutableMapping[str, str]):
  File "/opt/homebrew/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/project/config.py", line 100, in Config
    platformdirs.user_cache_dir("pdm"),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'platformdirs' has no attribute 'user_cache_dir'
Error: pdm: failed
Warning: Removed Sorbet lines from backtrace!
Rerun with --verbose to see the original backtrace
An exception occurred within a child process:
  BuildError: Failed executing: /opt/homebrew/Cellar/pdm/2.10.4/bin/pdm add requests==2.31.0
/opt/homebrew/Library/Homebrew/formula.rb:2734:in `block in system'
/opt/homebrew/Library/Homebrew/formula.rb:2670:in `open'
/opt/homebrew/Library/Homebrew/formula.rb:2670:in `system'
/opt/homebrew/opt/pdm/.brew/pdm.rb:140:in `block in <class:Pdm>'
/opt/homebrew/Library/Homebrew/formula.rb:2493:in `block (3 levels) in run_test'
/opt/homebrew/Library/Homebrew/extend/kernel.rb:499:in `with_env'
/opt/homebrew/Library/Homebrew/formula.rb:2492:in `block (2 levels) in run_test'
/opt/homebrew/Library/Homebrew/formula.rb:1052:in `with_logging'
/opt/homebrew/Library/Homebrew/formula.rb:2491:in `block in run_test'
/opt/homebrew/Library/Homebrew/mktemp.rb:75:in `block in run'
/opt/homebrew/Library/Homebrew/mktemp.rb:75:in `chdir'
/opt/homebrew/Library/Homebrew/mktemp.rb:75:in `run'
/opt/homebrew/Library/Homebrew/formula.rb:2785:in `mktemp'
/opt/homebrew/Library/Homebrew/formula.rb:2485:in `run_test'
/opt/homebrew/Library/Homebrew/test.rb:44:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/opt/homebrew/Library/Homebrew/test.rb:48:in `<main>'
```

**Comment by frostming** [comment]
See https://github.com/pdm-project/pdm/issues/2441#issuecomment-1829475282

Closing due to duplicate and not PDM issue.

**Comment by danielmoessner** [comment]
Awesome thanks. Solution from #2441:

```
> brew doctor
some-package-1
some-package-1

> brew link --overwrite some-package-1
> brew link --overwrite some-package-2
```
