### ISSUE TITLE
pdm cannot find a solution for matplotlib>=3.6.2 and python>=3.8

### ISSUE THREAD

**Issue by J-M0** [pdm-project/pdm#2461]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Run `pdm install` with this `pyproject.toml` file

```toml
[project]
dependencies = [
    "matplotlib>=3.6.2",
]
requires-python = ">=3.8"
```

## Actual behavior

pdm fails to find a vaild soultion because it wants to pin numpy==1.26.2 which requires python >=3.9.

```
pdm.termui: ======== Starting round 3 ========
pdm.termui:   Adding requirement numpy<2.0,>=1.16; python_version <= "3.11"(from contourpy 1.1.1)
pdm.termui:   Adding requirement numpy<2.0,>=1.26.0rc1; python_version >= "3.12"(from contourpy 1.1.1)
STATUS: Resolving: new pin contourpy 1.1.1
pdm.termui: Pinning: contourpy 1.1.1
pdm.termui: ======== Ending round 3 ========
pdm.termui: ======== Starting round 4 ========
STATUS: Resolving: new pin numpy 1.26.2
pdm.termui: Pinning: numpy 1.26.2
pdm.termui: ======== Ending round 4 ========
```

Full `pdm install -v` output:
```
Lock file does not exist
Updating the lock file...
Virtualenv /Users/jamorris/Documents/sandbox/pdm/.venv is reused.
STATUS: Resolving dependencies
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   matplotlib>=3.6.2
pdm.termui:   python>=3.8
pdm.termui:   Adding requirement matplotlib>=3.6.2
/Users/jamorris/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/resolver/providers.py:142: PackageWarning: Skipping matplotlib@3.8.2 because it requires Python>=3.9 but the project claims to work with Python>=3.8.
Narrow down the `requires-python` range to include this version. For example, ">=3.9" should work.
  return self.repository.find_candidates(
/Users/jamorris/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/resolver/providers.py:142: PackageWarning: Skipping matplotlib@3.8.1 because it requires Python>=3.9 but the project claims to work with Python>=3.8.
Narrow down the `requires-python` range to include this version. For example, ">=3.9" should work.
  return self.repository.find_candidates(
/Users/jamorris/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/resolver/providers.py:142: PackageWarning: Skipping matplotlib@3.8.0 because it requires Python>=3.9 but the project claims to work with Python>=3.8.
Narrow down the `requires-python` range to include this version. For example, ">=3.9" should work.
  return self.repository.find_candidates(
pdm.termui:   Adding requirement python>=3.8
pdm.termui: ======== Starting round 0 ========
STATUS: Resolving: new pin python>=3.8
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
pdm.termui:   Adding requirement contourpy>=1.0.1(from matplotlib 3.7.4)
/Users/jamorris/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/resolver/providers.py:142: PackageWarning: Skipping contourpy@1.2.0 because it requires Python>=3.9 but the project claims to work with Python>=3.8.
Narrow down the `requires-python` range to include this version. For example, ">=3.9" should work.
  return self.repository.find_candidates(
pdm.termui:   Adding requirement cycler>=0.10(from matplotlib 3.7.4)
pdm.termui:   Adding requirement fonttools>=4.22.0(from matplotlib 3.7.4)
pdm.termui:   Adding requirement kiwisolver>=1.0.1(from matplotlib 3.7.4)
pdm.termui:   Adding requirement numpy<2,>=1.20(from matplotlib 3.7.4)
/Users/jamorris/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/resolver/providers.py:142: PackageWarning: Skipping numpy@1.26.2 because it requires Python>=3.9 but the project claims to work with Python>=3.8.
Narrow down the `requires-python` range to include this version. For example, ">=3.9" should work.
  return self.repository.find_candidates(
/Users/jamorris/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/resolver/providers.py:142: PackageWarning: Skipping numpy@1.26.1 because it requires Python<3.13,>=3.9 but the project claims to work with Python>=3.8.
Narrow down the `requires-python` range to include this version. For example, ">=3.9,<3.13" should work.
  return self.repository.find_candidates(
/Users/jamorris/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/resolver/providers.py:142: PackageWarning: Skipping numpy@1.26.0 because it requires Python<3.13,>=3.9 but the project claims to work with Python>=3.8.
Narrow down the `requires-python` range to include this version. For example, ">=3.9,<3.13" should work.
  return self.repository.find_candidates(
/Users/jamorris/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/resolver/providers.py:142: PackageWarning: Skipping numpy@1.25.2 because it requires Python>=3.9 but the project claims to work with Python>=3.8.
Narrow down the `requires-python` range to include this version. For example, ">=3.9" should work.
  return self.repository.find_candidates(
/Users/jamorris/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/resolver/providers.py:142: PackageWarning: Skipping numpy@1.25.1 because it requires Python>=3.9 but the project claims to work with Python>=3.8.
Narrow down the `requires-python` range to include this version. For example, ">=3.9" should work.
  return self.repository.find_candidates(
/Users/jamorris/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/resolver/providers.py:142: PackageWarning: Skipping numpy@1.25.0 because it requires Python>=3.9 but the project claims to work with Python>=3.8.
Narrow down the `requires-python` range to include this version. For example, ">=3.9" should work.
  return self.repository.find_candidates(
pdm.termui:   Adding requirement packaging>=20.0(from matplotlib 3.7.4)
pdm.termui:   Adding requirement pillow>=6.2.0(from matplotlib 3.7.4)
pdm.termui:   Adding requirement pyparsing>=2.3.1(from matplotlib 3.7.4)
pdm.termui:   Adding requirement python-dateutil>=2.7(from matplotlib 3.7.4)
pdm.termui:   Adding requirement importlib-resources>=3.2.0; python_version < "3.10"(from matplotlib 3.7.4)
STATUS: Resolving: new pin matplotlib 3.7.4
pdm.termui: Pinning: matplotlib 3.7.4
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
STATUS: Resolving: new pin numpy 1.24.4
pdm.termui: Pinning: numpy 1.24.4
pdm.termui: ======== Ending round 2 ========
pdm.termui: ======== Starting round 3 ========
pdm.termui:   Adding requirement numpy<2.0,>=1.16; python_version <= "3.11"(from contourpy 1.1.1)
pdm.termui:   Adding requirement numpy<2.0,>=1.26.0rc1; python_version >= "3.12"(from contourpy 1.1.1)
STATUS: Resolving: new pin contourpy 1.1.1
pdm.termui: Pinning: contourpy 1.1.1
pdm.termui: ======== Ending round 3 ========
pdm.termui: ======== Starting round 4 ========
STATUS: Resolving: new pin numpy 1.26.2
pdm.termui: Pinning: numpy 1.26.2
pdm.termui: ======== Ending round 4 ========
pdm.termui: ======== Starting round 5 ========
STATUS: Resolving: new pin cycler 0.12.1
pdm.termui: Pinning: cycler 0.12.1
pdm.termui: ======== Ending round 5 ========
pdm.termui: ======== Starting round 6 ========
STATUS: Resolving: new pin fonttools 4.46.0
pdm.termui: Pinning: fonttools 4.46.0
pdm.termui: ======== Ending round 6 ========
pdm.termui: ======== Starting round 7 ========
pdm.termui:   Adding requirement zipp>=3.1.0; python_version < "3.10"(from importlib-resources 6.1.1)
STATUS: Resolving: new pin importlib-resources 6.1.1
pdm.termui: Pinning: importlib-resources 6.1.1
pdm.termui: ======== Ending round 7 ========
pdm.termui: ======== Starting round 8 ========
STATUS: Resolving: new pin kiwisolver 1.4.5
pdm.termui: Pinning: kiwisolver 1.4.5
pdm.termui: ======== Ending round 8 ========
pdm.termui: ======== Starting round 9 ========
STATUS: Resolving: new pin packaging 23.2
pdm.termui: Pinning: packaging 23.2
pdm.termui: ======== Ending round 9 ========
pdm.termui: ======== Starting round 10 ========
STATUS: Resolving: new pin pillow 10.1.0
pdm.termui: Pinning: pillow 10.1.0
pdm.termui: ======== Ending round 10 ========
pdm.termui: ======== Starting round 11 ========
STATUS: Resolving: new pin pyparsing 3.1.1
pdm.termui: Pinning: pyparsing 3.1.1
pdm.termui: ======== Ending round 11 ========
pdm.termui: ======== Starting round 12 ========
pdm.termui:   Adding requirement six>=1.5(from python-dateutil 2.8.2)
STATUS: Resolving: new pin python-dateutil 2.8.2
pdm.termui: Pinning: python-dateutil 2.8.2
pdm.termui: ======== Ending round 12 ========
pdm.termui: ======== Starting round 13 ========
STATUS: Resolving: new pin six 1.16.0
pdm.termui: Pinning: six 1.16.0
pdm.termui: ======== Ending round 13 ========
pdm.termui: ======== Starting round 14 ========
STATUS: Resolving: new pin zipp 3.17.0
pdm.termui: Pinning: zipp 3.17.0
pdm.termui: ======== Ending round 14 ========
pdm.termui: ======== Starting round 15 ========
pdm.termui: ======== Resolution Result ========
pdm.termui: Stable pins:
pdm.termui:                python None
pdm.termui:            matplotlib 3.7.4
pdm.termui:             contourpy 1.1.1
pdm.termui:                 numpy 1.26.2
pdm.termui:                cycler 0.12.1
pdm.termui:             fonttools 4.46.0
pdm.termui:   importlib-resources 6.1.1
pdm.termui:            kiwisolver 1.4.5
pdm.termui:             packaging 23.2
pdm.termui:                pillow 10.1.0
pdm.termui:             pyparsing 3.1.1
pdm.termui:       python-dateutil 2.8.2
pdm.termui:                   six 1.16.0
pdm.termui:                  zipp 3.17.0
Use `-q/--quiet` to suppress these warnings, or ignore them per-package with `ignore_package_warnings` config in [tool.pdm] table.
STATUS: Fetching hashes for resolved packages...
pdm.termui: Fetching hashes for cycler@0.12.1
pdm.termui: Fetching hashes for importlib-resources@6.1.1
pdm.termui: Fetching hashes for packaging@23.2
pdm.termui: Fetching hashes for contourpy@1.1.1
pdm.termui: Fetching hashes for python-dateutil@2.8.2
pdm.termui: Fetching hashes for kiwisolver@1.4.5
pdm.termui: Fetching hashes for fonttools@4.46.0
pdm.termui: Fetching hashes for pyparsing@3.1.1
pdm.termui: Fetching hashes for six@1.16.0
pdm.termui: Fetching hashes for zipp@3.17.0
pdm.termui: Fetching hashes for numpy@1.26.2
pdm.termui: Fetching hashes for matplotlib@3.7.4
pdm.termui: Fetching hashes for pillow@10.1.0
🔒 Lock successful
Changes are written to pdm.lock.
STATUS: Resolving packages from lockfile...
Traceback (most recent call last):
  File "/Users/jamorris/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/jamorris/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/core.py", line 295, in main
    return Core().main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamorris/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/core.py", line 208, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/Users/jamorris/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/core.py", line 203, in main
    self.handle(project, options)
  File "/Users/jamorris/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/core.py", line 157, in handle
    command.handle(project, options)
  File "/Users/jamorris/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/cli/commands/install.py", line 100, in handle
    actions.do_sync(
  File "/Users/jamorris/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/cli/actions.py", line 199, in do_sync
    candidates = resolve_candidates_from_lockfile(project, requirements)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamorris/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/cli/actions.py", line 142, in resolve_candidates_from_lockfile
    mapping, *_ = resolve(
                  ^^^^^^^^
  File "/Users/jamorris/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/resolver/core.py", line 36, in resolve
    result = resolver.resolve(requirements, max_rounds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamorris/.local/pipx/venvs/pdm/lib/python3.12/site-packages/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamorris/.local/pipx/venvs/pdm/lib/python3.12/site-packages/resolvelib/resolvers.py", line 434, in resolve
    success = self._backjump(causes)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamorris/.local/pipx/venvs/pdm/lib/python3.12/site-packages/resolvelib/resolvers.py", line 318, in _backjump
    raise ResolutionImpossible(causes)
resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=NamedRequirement(name='numpy', marker=None, extras=set(), specifier=<SpecifierSet('<2,>=1.20')>, editable=False, prerelease=False), parent=<Candidate matplotlib@3.7.4>)]
```

## Expected behavior
pdm should find a solution. `pip install "matplotlib>=3.6.2"` works correctly and `pip check` reports that there are no broken requirements. The only difference between `pip freeze` and `pdm.lock` is the version of numpy.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.10.4
Python Interpreter:
  /Users/jamorris/Documents/sandbox/pdm/.venv/bin/python (3.8)
Project Root:
  /Users/jamorris/Documents/sandbox/pdm
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.18",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "22.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 22.6.0: Thu Nov  2 07:43:57 PDT 2023; root:xnu-8796.141.3.701.17~6/RELEASE_ARM64_T6000",
  "python_full_version": "3.8.18",
  "platform_python_implementation": "CPython",
  "python_version": "3.8",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
This is caused by a multiple dependency specifiers from `contourpy` that conflicts with other dependencies.:
```
dependencies = [
     "numpy<2.0,>=1.16; python_version <= \"3.11\"",
     "numpy<2.0,>=1.26.0rc1; python_version >= \"3.12\"",
]
```

Specifically, no version in range `numpy<2.0,>=1.26.0rc1;` can satisfy the python requirement: `>=3.8`.

There is no way to make a working resolution before #46 gets resolved., you have to either increase the lower bound of `requires-python` to 3.9, or use a non-cross-platform lockfile.
