### ISSUE TITLE
AttributeError: module 'platformdirs' has no attribute 'user_cache_dir'

### ISSUE THREAD

**Issue by bahadiraraz** [pdm-project/pdm#2477]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

pdm install

❯ pdm install -v
Traceback (most recent call last):
  File "/opt/homebrew/bin/pdm", line 5, in <module>
    from pdm.core import main
  File "/opt/homebrew/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/core.py", line 24, in <module>
    from pdm.cli.utils import ArgumentParser, ErrorArgumentParser
  File "/opt/homebrew/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/cli/utils.py", line 40, in <module>
    from pdm.project.lockfile import FLAG_CROSS_PLATFORM, FLAG_STATIC_URLS
  File "/opt/homebrew/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/project/__init__.py", line 1, in <module>
    from pdm.project.config import Config, ConfigItem
  File "/opt/homebrew/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/project/config.py", line 94, in <module>
    class Config(MutableMapping[str, str]):
  File "/opt/homebrew/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/project/config.py", line 100, in Config
    platformdirs.user_cache_dir("pdm"),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'platformdirs' has no attribute 'user_cache_dir'

## Expected behavior
it shoud be work normal

## Environment Information

```bash
❯ pdm info && pdm info --env
Traceback (most recent call last):
  File "/opt/homebrew/bin/pdm", line 5, in <module>
    from pdm.core import main
  File "/opt/homebrew/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/core.py", line 24, in <module>
    from pdm.cli.utils import ArgumentParser, ErrorArgumentParser
  File "/opt/homebrew/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/cli/utils.py", line 40, in <module>
    from pdm.project.lockfile import FLAG_CROSS_PLATFORM, FLAG_STATIC_URLS
  File "/opt/homebrew/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/project/__init__.py", line 1, in <module>
    from pdm.project.config import Config, ConfigItem
  File "/opt/homebrew/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/project/config.py", line 94, in <module>
    class Config(MutableMapping[str, str]):
  File "/opt/homebrew/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/project/config.py", line 100, in Config
    platformdirs.user_cache_dir("pdm"),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'platformdirs' has no attribute 'user_cache_dir'

```

**Comment by bahadiraraz** [comment]
```bash
❯ pdm info && pdm info --env
python.use_venv is on, creating a virtualenv for this project...
[VirtualenvCreateError]: Command '['/opt/homebrew/Cellar/pdm/2.10.4/libexec/bin/python', '-m', 'virtualenv', '/Users/bahadiraraz/Desktop/sorsorbe/.venv', '-p', '/opt/homebrew/bin/python3.12', '--prompt=sorsorbe-3.12', '--no-pip',
'--no-setuptools', '--no-wheel']' returned non-zero exit status 1.
```

**Comment by bahadiraraz** [comment]
```bash
pdm.termui: Error occurs
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/termui.py", line 246, in logging
    yield logger
  File "/opt/homebrew/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/cli/actions.py", line 140, in resolve_candidates_from_lockfile
    provider = project.get_provider(for_install=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/project/core.py", line 440, in get_provider
    repository = self.get_repository(ignore_compatibility=ignore_compatibility)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/project/core.py", line 405, in get_repository
    return cls(sources, self.environment, ignore_compatibility=ignore_compatibility)
                        ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/project/core.py", line 288, in environment
    self._environment = self.get_environment()
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/project/core.py", line 267, in get_environment
    if self.config["python.use_venv"] and self.python.get_venv() is not None
                                          ^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/project/core.py", line 153, in python
    python = self.resolve_interpreter()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/project/core.py", line 240, in resolve_interpreter
    venv_path = self._create_virtualenv()
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/project/core.py", line 276, in _create_virtualenv
    path = venv_backend.create(
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/cli/commands/venv/backends.py", line 117, in create
    self.perform_create(location, args, prompt=prompt)
  File "/opt/homebrew/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/cli/commands/venv/backends.py", line 143, in perform_create
    self.subprocess_call(cmd)
  File "/opt/homebrew/Cellar/pdm/2.10.4/libexec/lib/python3.12/site-packages/pdm/cli/commands/venv/backends.py", line 70, in subprocess_call
    raise VirtualenvCreateError(e) from None
pdm.cli.commands.venv.backends.VirtualenvCreateError: Command '['/opt/homebrew/Cellar/pdm/2.10.4/libexec/bin/python', '-m', 'virtualenv', '/Users/bahadiraraz/Desktop/sex/sorsorbe/.venv', '-p', '/opt/homebrew/bin/python3', '--prompt=sorsorbe-3.11', '--no-pip', '--no-setuptools', '--no-wheel']' returned non-zero exit status 1.
```

**Comment by frostming** [comment]
Duplicate #2441 #2451 

Please search the issues before reporting
