### ISSUE TITLE
Adding a VCS dependency without explicit name leads to `KeyError` in v2.11.0

### ISSUE THREAD

**Issue by arxikv** [pdm-project/pdm#2488]
Hello,

I am trying to add [this](https://github.com/thunlp/OpenBackdoor) library as a VCS dependency to the blank project:

```
mkdir test-project && cd test-project
pdm init
pdm add "git+https://github.com/thunlp/OpenBackdoor.git"
```

In version 2.11.0, this fails with the following traceback:

```
pdm.termui: Error occurs
Traceback (most recent call last):
  File "/home/arkhipenko/.local/share/pdm/venv/lib/python3.11/site-packages/pdm/termui.py", line 246, in logging
    yield logger
  File "/home/arkhipenko/.local/share/pdm/venv/lib/python3.11/site-packages/pdm/cli/actions.py", line 103, in do_lock
    mapping, dependencies = resolve(
                            ^^^^^^^^
  File "/home/arkhipenko/.local/share/pdm/venv/lib/python3.11/site-packages/pdm/resolver/core.py", line 55, in resolve
    all_markers = merge_markers(result)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/arkhipenko/.local/share/pdm/venv/lib/python3.11/site-packages/pdm/resolver/graph.py", line 66, in merge_markers
    new_markers[k] = _build_marker(crit, all_markers, keep_unresolved)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arkhipenko/.local/share/pdm/venv/lib/python3.11/site-packages/pdm/resolver/graph.py", line 107, in _build_marker
    parent_marker = resolved[_identify_parent(parent)]
                    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'openbackdoor'
```

Running `pdm add "openbackdoor @ git+https://github.com/thunlp/OpenBackdoor.git"` fixes the error.

However, according to the docs, PDM should be able to infer the dependency name automatically (and it worked in v2.10.4).

Thanks :)

**Comment by elenakrittik** [comment]
Hello @frostming. If i understand correctly, the fix has made it into 2.11.1, but i still get this error when trying to `pdm add git+https://github.com/DisnakeDev/disnake@f780cf5d7320210f022eba0d0e4e8b2820db2baa` in an newly-initialized project.

Here are the logs: 
[log.txt](https://github.com/pdm-project/pdm/files/13778240/log.txt)

Should the issue be reopened or is this a problem on my end?

**Comment by elenakrittik** [comment]
Thank you.

**Comment by asuglia-alana** [comment]
I just had the same error while trying to install a library from Github. @frostming when are you planning to integrate this in a release?
