### ISSUE TITLE
pdm update --update-eager can hit InconsistentCandidate error when dependency is included both through default dependencies and extra

### ISSUE THREAD

**Issue by lambda** [pdm-project/pdm#2495]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

I have the following two projects, `package-a` and `package-b`; the contain only the given `pyproject.toml`:

`package-a/pyproject.toml`:

```toml
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "package-a"
description = "Test Project"
authors = [
    { email = "example@example.com", name = "Example" },
]
version = "1.0.0"
requires-python = ">=3.9, <3.12"
dependencies = [
    "aiobotocore[boto3]>=2.7.0",
]

[project.optional-dependencies]
data = [
    "sqlalchemy>=1.4.0",
]
```

`package-b/pyproject.toml`:

```toml
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "package-b"
description = "Test Project"
authors = [
    { email = "example@example.com", name = "Example" },
]
version = "1.0.0"
requires-python = ">=3.9, <3.12"
dependencies = [
    "package-a[data] @ file:///${PROJECT_ROOT}/../package-a",
]
```

In `package-b`, I run `pdm update -v --update-eager --no-sync`. The first time I run it (with no lock file), it succeeds.

The second time I run it, to update the lock file, it fails. Errors reproduced below.

## Actual behavior

This is the second time I run it, after a lock file already exists:

<details>
<summary>failing command</summary>

```console
package-b$ pdm update -v --update-eager --no-sync
STATUS: Resolving dependencies
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   package-a[data] @ file:///${PROJECT_ROOT}/../package-a
pdm.termui:   python>=3.9,<3.12
pdm.termui:   Adding requirement package-a[data] @ file:///${PROJECT_ROOT}/../package-a
pdm.termui:   Adding requirement python>=3.9,<3.12
pdm.termui: ======== Starting round 0 ========
unearth.preparer: The file ../package-a is a local directory, use it directly
STATUS: Resolving: new pin python>=3.9,<3.12
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
pdm.termui:   Adding requirement sqlalchemy>=1.4.0(from package-a 1.0.0)
pdm.termui:   Adding requirement package-a @ file:///${PROJECT_ROOT}/../package-a(from package-a 1.0.0)
STATUS: Resolving: new pin package-a 1.0.0
pdm.termui: Pinning: package-a 1.0.0
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
unearth.preparer: The file ../package-a is a local directory, use it directly
pdm.termui:   Adding requirement aiobotocore[boto3]>=2.7.0(from package-a 1.0.0)
STATUS: Resolving: new pin package-a 1.0.0
pdm.termui: Pinning: package-a 1.0.0
pdm.termui: ======== Ending round 2 ========
pdm.termui: ======== Starting round 3 ========
pdm.termui:   Adding requirement typing-extensions>=4.2.0(from sqlalchemy 2.0.23)
pdm.termui:   Adding requirement greenlet!=0.4.17; platform_machine == "win32" or platform_machine == "WIN32" or platform_machine == "AMD64" or platform_machine == "amd64" or platform_machine == "x86_64" or platform_machine == "ppc64le" or platform_machine == "aarch64"(from sqlalchemy 2.0.23)
STATUS: Resolving: new pin sqlalchemy 2.0.23
pdm.termui: Pinning: sqlalchemy 2.0.23
pdm.termui: ======== Ending round 3 ========
pdm.termui: ======== Starting round 4 ========
pdm.termui:   Adding requirement boto3<1.33.14,>=1.33.2(from aiobotocore 2.9.0)
pdm.termui:   Adding requirement aiobotocore==2.9.0(from aiobotocore 2.9.0)
STATUS: Resolving: new pin aiobotocore 2.9.0
pdm.termui: Pinning: aiobotocore 2.9.0
pdm.termui: ======== Ending round 4 ========
pdm.termui: ======== Starting round 5 ========
pdm.termui:   Adding requirement botocore<1.33.14,>=1.33.2(from aiobotocore 2.9.0)
pdm.termui:   Adding requirement aiohttp<4.0.0,>=3.7.4.post0(from aiobotocore 2.9.0)
pdm.termui:   Adding requirement wrapt<2.0.0,>=1.10.10(from aiobotocore 2.9.0)
pdm.termui:   Adding requirement aioitertools<1.0.0,>=0.5.1(from aiobotocore 2.9.0)
STATUS: Resolving: new pin aiobotocore 2.9.0
pdm.termui: Pinning: aiobotocore 2.9.0
pdm.termui: ======== Ending round 5 ========
pdm.termui: ======== Starting round 6 ========
pdm.termui:   Adding requirement attrs>=17.3.0(from aiohttp 3.9.1)
pdm.termui:   Adding requirement multidict<7.0,>=4.5(from aiohttp 3.9.1)
pdm.termui:   Adding requirement yarl<2.0,>=1.0(from aiohttp 3.9.1)
pdm.termui:   Adding requirement frozenlist>=1.1.1(from aiohttp 3.9.1)
pdm.termui:   Adding requirement aiosignal>=1.1.2(from aiohttp 3.9.1)
pdm.termui:   Adding requirement async-timeout<5.0,>=4.0; python_version < "3.11"(from aiohttp 3.9.1)
STATUS: Resolving: new pin aiohttp 3.9.1
pdm.termui: Pinning: aiohttp 3.9.1
pdm.termui: ======== Ending round 6 ========
pdm.termui: ======== Starting round 7 ========
Traceback (most recent call last):
  File "/home/brcampbell/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/brcampbell/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/core.py", line 288, in main
    return Core().main(args or sys.argv[1:])
  File "/home/brcampbell/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/core.py", line 208, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/home/brcampbell/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/core.py", line 203, in main
    self.handle(project, options)
  File "/home/brcampbell/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/core.py", line 157, in handle
    command.handle(project, options)
  File "/home/brcampbell/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/cli/commands/update.py", line 73, in handle
    self.do_update(
  File "/home/brcampbell/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/cli/commands/update.py", line 168, in do_update
    resolved = do_lock(
  File "/home/brcampbell/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/cli/actions.py", line 103, in do_lock
    mapping, dependencies = resolve(
  File "/home/brcampbell/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/resolver/core.py", line 39, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "/home/brcampbell/.local/pipx/venvs/pdm/lib/python3.10/site-packages/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/brcampbell/.local/pipx/venvs/pdm/lib/python3.10/site-packages/resolvelib/resolvers.py", line 427, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/home/brcampbell/.local/pipx/venvs/pdm/lib/python3.10/site-packages/resolvelib/resolvers.py", line 254, in _attempt_to_pin_criterion
    raise InconsistentCandidate(candidate, criterion)
resolvelib.resolvers.InconsistentCandidate: Provided candidate <Candidate typing-extensions@4.9.0> does not satisfy NamedRequirement(name='typing-extensions', marker=None, extras=set(), specifier=<SpecifierSet('>=4.2.0')>, editable=False, prerelease=False, groups=[])
```
</details>

## Expected behavior

I expect it to behave the way it does the first time I run it; this is how it behaves with no existing lockfile:

<details>
<summary>successful command</summary>

```console
package-b$ pdm update -v --update-eager --no-sync
STATUS: Resolving dependencies
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   package-a[data] @ file:///${PROJECT_ROOT}/../package-a
pdm.termui:   python>=3.9,<3.12
pdm.termui:   Adding requirement package-a[data] @ file:///${PROJECT_ROOT}/../package-a
pdm.termui:   Adding requirement python>=3.9,<3.12
pdm.termui: ======== Starting round 0 ========
unearth.preparer: The file ../package-a is a local directory, use it directly
STATUS: Resolving: new pin python>=3.9,<3.12
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
pdm.termui:   Adding requirement sqlalchemy>=1.4.0(from package-a 1.0.0)
pdm.termui:   Adding requirement package-a @ file:///${PROJECT_ROOT}/../package-a(from package-a 1.0.0)
STATUS: Resolving: new pin package-a 1.0.0
pdm.termui: Pinning: package-a 1.0.0
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
unearth.preparer: The file ../package-a is a local directory, use it directly
pdm.termui:   Adding requirement aiobotocore[boto3]>=2.7.0(from package-a 1.0.0)
STATUS: Resolving: new pin package-a 1.0.0
pdm.termui: Pinning: package-a 1.0.0
pdm.termui: ======== Ending round 2 ========
pdm.termui: ======== Starting round 3 ========
pdm.termui:   Adding requirement typing-extensions>=4.2.0(from sqlalchemy 2.0.23)
pdm.termui:   Adding requirement greenlet!=0.4.17; platform_machine == "win32" or platform_machine == "WIN32" or platform_machine == "AMD64" or platform_machine == "amd64" or platform_machine == "x86_64" or platform_machine == "ppc64le" or platform_machine == "aarch64"(from sqlalchemy 2.0.23)
STATUS: Resolving: new pin sqlalchemy 2.0.23
pdm.termui: Pinning: sqlalchemy 2.0.23
pdm.termui: ======== Ending round 3 ========
pdm.termui: ======== Starting round 4 ========
pdm.termui:   Adding requirement boto3<1.33.14,>=1.33.2(from aiobotocore 2.9.0)
pdm.termui:   Adding requirement aiobotocore==2.9.0(from aiobotocore 2.9.0)
STATUS: Resolving: new pin aiobotocore 2.9.0
pdm.termui: Pinning: aiobotocore 2.9.0
pdm.termui: ======== Ending round 4 ========
pdm.termui: ======== Starting round 5 ========
pdm.termui:   Adding requirement botocore<1.33.14,>=1.33.2(from aiobotocore 2.9.0)
pdm.termui:   Adding requirement aiohttp<4.0.0,>=3.7.4.post0(from aiobotocore 2.9.0)
pdm.termui:   Adding requirement wrapt<2.0.0,>=1.10.10(from aiobotocore 2.9.0)
pdm.termui:   Adding requirement aioitertools<1.0.0,>=0.5.1(from aiobotocore 2.9.0)
STATUS: Resolving: new pin aiobotocore 2.9.0
pdm.termui: Pinning: aiobotocore 2.9.0
pdm.termui: ======== Ending round 5 ========
pdm.termui: ======== Starting round 6 ========
pdm.termui:   Adding requirement attrs>=17.3.0(from aiohttp 3.9.1)
pdm.termui:   Adding requirement multidict<7.0,>=4.5(from aiohttp 3.9.1)
pdm.termui:   Adding requirement yarl<2.0,>=1.0(from aiohttp 3.9.1)
pdm.termui:   Adding requirement frozenlist>=1.1.1(from aiohttp 3.9.1)
pdm.termui:   Adding requirement aiosignal>=1.1.2(from aiohttp 3.9.1)
pdm.termui:   Adding requirement async-timeout<5.0,>=4.0; python_version < "3.11"(from aiohttp 3.9.1)
STATUS: Resolving: new pin aiohttp 3.9.1
pdm.termui: Pinning: aiohttp 3.9.1
pdm.termui: ======== Ending round 6 ========
pdm.termui: ======== Starting round 7 ========
STATUS: Resolving: new pin typing-extensions 4.9.0
pdm.termui: Pinning: typing-extensions 4.9.0
pdm.termui: ======== Ending round 7 ========
pdm.termui: ======== Starting round 8 ========
pdm.termui:   Adding requirement typing-extensions>=4.0; python_version < "3.10"(from aioitertools 0.11.0)
STATUS: Resolving: new pin aioitertools 0.11.0
pdm.termui: Pinning: aioitertools 0.11.0
pdm.termui: ======== Ending round 8 ========
pdm.termui: ======== Starting round 9 ========
pdm.termui:   Adding requirement jmespath<2.0.0,>=0.7.1(from botocore 1.33.13)
pdm.termui:   Adding requirement python-dateutil<3.0.0,>=2.1(from botocore 1.33.13)
pdm.termui:   Adding requirement urllib3<1.27,>=1.25.4; python_version < "3.10"(from botocore 1.33.13)
pdm.termui:   Adding requirement urllib3<2.1,>=1.25.4; python_version >= "3.10"(from botocore 1.33.13)
STATUS: Resolving: new pin botocore 1.33.13
pdm.termui: Pinning: botocore 1.33.13
pdm.termui: ======== Ending round 9 ========
pdm.termui: ======== Starting round 10 ========
STATUS: Resolving: new pin wrapt 1.16.0
pdm.termui: Pinning: wrapt 1.16.0
pdm.termui: ======== Ending round 10 ========
pdm.termui: ======== Starting round 11 ========
STATUS: Resolving: new pin urllib3 1.26.18
pdm.termui: Pinning: urllib3 1.26.18
pdm.termui: ======== Ending round 11 ========
pdm.termui: ======== Starting round 12 ========
STATUS: Resolving: new pin async-timeout 4.0.3
pdm.termui: Pinning: async-timeout 4.0.3
pdm.termui: ======== Ending round 12 ========
pdm.termui: ======== Starting round 13 ========
STATUS: Resolving: new pin jmespath 1.0.1
pdm.termui: Pinning: jmespath 1.0.1
pdm.termui: ======== Ending round 13 ========
pdm.termui: ======== Starting round 14 ========
STATUS: Resolving: new pin multidict 6.0.4
pdm.termui: Pinning: multidict 6.0.4
pdm.termui: ======== Ending round 14 ========
pdm.termui: ======== Starting round 15 ========
pdm.termui:   Adding requirement six>=1.5(from python-dateutil 2.8.2)
STATUS: Resolving: new pin python-dateutil 2.8.2
pdm.termui: Pinning: python-dateutil 2.8.2
pdm.termui: ======== Ending round 15 ========
pdm.termui: ======== Starting round 16 ========
pdm.termui:   Adding requirement idna>=2.0(from yarl 1.9.4)
pdm.termui:   Adding requirement multidict>=4.0(from yarl 1.9.4)
STATUS: Resolving: new pin yarl 1.9.4
pdm.termui: Pinning: yarl 1.9.4
pdm.termui: ======== Ending round 16 ========
pdm.termui: ======== Starting round 17 ========
pdm.termui:   Adding requirement frozenlist>=1.1.0(from aiosignal 1.3.1)
STATUS: Resolving: new pin aiosignal 1.3.1
pdm.termui: Pinning: aiosignal 1.3.1
pdm.termui: ======== Ending round 17 ========
pdm.termui: ======== Starting round 18 ========
STATUS: Resolving: new pin frozenlist 1.4.0
pdm.termui: Pinning: frozenlist 1.4.0
pdm.termui: ======== Ending round 18 ========
pdm.termui: ======== Starting round 19 ========
STATUS: Resolving: new pin attrs 23.1.0
pdm.termui: Pinning: attrs 23.1.0
pdm.termui: ======== Ending round 19 ========
pdm.termui: ======== Starting round 20 ========
STATUS: Resolving: new pin idna 3.6
pdm.termui: Pinning: idna 3.6
pdm.termui: ======== Ending round 20 ========
pdm.termui: ======== Starting round 21 ========
STATUS: Resolving: new pin six 1.16.0
pdm.termui: Pinning: six 1.16.0
pdm.termui: ======== Ending round 21 ========
pdm.termui: ======== Starting round 22 ========
STATUS: Resolving: new pin greenlet 3.0.2
pdm.termui: Pinning: greenlet 3.0.2
pdm.termui: ======== Ending round 22 ========
pdm.termui: ======== Starting round 23 ========
pdm.termui:   Adding requirement botocore<1.34.0,>=1.33.13(from boto3 1.33.13)
pdm.termui:   Adding requirement jmespath<2.0.0,>=0.7.1(from boto3 1.33.13)
pdm.termui:   Adding requirement s3transfer<0.9.0,>=0.8.2(from boto3 1.33.13)
STATUS: Resolving: new pin boto3 1.33.13
pdm.termui: Pinning: boto3 1.33.13
pdm.termui: ======== Ending round 23 ========
pdm.termui: ======== Starting round 24 ========
pdm.termui:   Adding requirement botocore<2.0a.0,>=1.33.2(from s3transfer 0.8.2)
STATUS: Resolving: new pin s3transfer 0.8.2
pdm.termui: Pinning: s3transfer 0.8.2
pdm.termui: ======== Ending round 24 ========
pdm.termui: ======== Starting round 25 ========
pdm.termui: ======== Resolution Result ========
pdm.termui: Stable pins:
pdm.termui:               python None
pdm.termui:      package-a[data] file:///${PROJECT_ROOT}/../package-a
pdm.termui:            package-a file:///${PROJECT_ROOT}/../package-a
pdm.termui:           sqlalchemy 2.0.23
pdm.termui:   aiobotocore[boto3] 2.9.0
pdm.termui:          aiobotocore 2.9.0
pdm.termui:              aiohttp 3.9.1
pdm.termui:    typing-extensions 4.9.0
pdm.termui:         aioitertools 0.11.0
pdm.termui:             botocore 1.33.13
pdm.termui:                wrapt 1.16.0
pdm.termui:              urllib3 1.26.18
pdm.termui:        async-timeout 4.0.3
pdm.termui:             jmespath 1.0.1
pdm.termui:            multidict 6.0.4
pdm.termui:      python-dateutil 2.8.2
pdm.termui:                 yarl 1.9.4
pdm.termui:            aiosignal 1.3.1
pdm.termui:           frozenlist 1.4.0
pdm.termui:                attrs 23.1.0
pdm.termui:                 idna 3.6
pdm.termui:                  six 1.16.0
pdm.termui:             greenlet 3.0.2
pdm.termui:                boto3 1.33.13
pdm.termui:           s3transfer 0.8.2
STATUS: Fetching hashes for resolved packages...
pdm.termui: Fetching hashes for jmespath@1.0.1
pdm.termui: Fetching hashes for python-dateutil@2.8.2
pdm.termui: Fetching hashes for idna@3.6
pdm.termui: Fetching hashes for aiobotocore@2.9.0
pdm.termui: Fetching hashes for aiosignal@1.3.1
pdm.termui: Fetching hashes for typing-extensions@4.9.0
pdm.termui: Fetching hashes for aioitertools@0.11.0
pdm.termui: Fetching hashes for async-timeout@4.0.3
pdm.termui: Fetching hashes for six@1.16.0
pdm.termui: Fetching hashes for attrs@23.1.0
pdm.termui: Fetching hashes for urllib3@1.26.18
pdm.termui: Fetching hashes for s3transfer@0.8.2
pdm.termui: Fetching hashes for aiobotocore@2.9.0
pdm.termui: Fetching hashes for frozenlist@1.4.0
pdm.termui: Fetching hashes for wrapt@1.16.0
pdm.termui: Fetching hashes for greenlet@3.0.2
pdm.termui: Fetching hashes for yarl@1.9.4
pdm.termui: Fetching hashes for multidict@6.0.4
pdm.termui: Fetching hashes for boto3@1.33.13
pdm.termui: Fetching hashes for aiohttp@3.9.1
pdm.termui: Fetching hashes for botocore@1.33.13
pdm.termui: Fetching hashes for sqlalchemy@2.0.23
🔒 Lock successful
```
</details>

I should also note that it succeeds if I move the `sqlalchemy` dependency into the main dependencies rather than the optional dependencies.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.11.1
Python Interpreter:
  /home/brcampbell/tmp/pdm-bug/package-b/.venv/bin/python (3.10)
Project Root:
  /home/brcampbell/tmp/pdm-bug/package-b
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.12",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.2.0-39-generic",
  "platform_system": "Linux",
  "platform_version": "#40~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov 16 10:53:04 UTC 2",
  "python_full_version": "3.10.12",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "linux"
}
```

**Comment by robtaylor** [comment]
I'm hitting this on our internal projects. It seems to be being triggered in _attempt_to_pin_criterion for a package where a dependancy had a conflicting version specifier against the project's dependency (which was a git head). 
I think its a bug, I will try to come up with a public test case. Either way, it would be good if the error message was more useful - showing when, which package was trying to be resolved and which requirement caused the mismatch.
