### ISSUE TITLE
PDM does not discover variables in .env files in external sources/repositories

### ISSUE THREAD

**Issue by baggiponte** [pdm-project/pdm#2513]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

I configured a private index in `pyproject.toml`:

```toml
[[tool.pdm.source]]
name = "private"
url="https://__token__:${PRIVATE_PAT}@<REPO-URL>"
include_packages = ["private-*"]
```

And a dotenv file with `PRIVATE_PAT=<PAT>`.

Then tried to install:

```bash
pdm add private-pkg -v
Adding packages to default dependencies: private-pkg
STATUS: Resolving dependencies
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   nemoguardrails>=0.6.0
pdm.termui:   private-pkg
pdm.termui:   python>=3.10,<3.11
pdm.termui:   Adding requirement nemoguardrails>=0.6.0
pdm.termui:   Adding requirement private-pkg
unearth.auth: 401 Error, Credentials not correct for <REPO-URL>
unearth.collector: Failed to collect links from <REPO-URL>: Client Error(401): Unauthorized
Traceback (most recent call last):
  File "/Users/luca/.local/share/pipx/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/luca/.local/share/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/core.py", line 288, in main
    return Core().main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luca/.local/share/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/core.py", line 208, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/Users/luca/.local/share/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/core.py", line 203, in main
    self.handle(project, options)
  File "/Users/luca/.local/share/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/core.py", line 157, in handle
    command.handle(project, options)
  File "/Users/luca/.local/share/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/cli/commands/add.py", line 69, in handle
    self.do_add(
  File "/Users/luca/.local/share/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/cli/commands/add.py", line 159, in do_add
    resolved = do_lock(
               ^^^^^^^^
  File "/Users/luca/.local/share/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/cli/actions.py", line 103, in do_lock
    mapping, dependencies = resolve(
                            ^^^^^^^^
  File "/Users/luca/.local/share/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/resolver/core.py", line 39, in resolve
    result = resolver.resolve(requirements, max_rounds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luca/.local/share/pipx/venvs/pdm/lib/python3.12/site-packages/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luca/.local/share/pipx/venvs/pdm/lib/python3.12/site-packages/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/Users/luca/.local/share/pipx/venvs/pdm/lib/python3.12/site-packages/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/luca/.local/share/pipx/venvs/pdm/lib/python3.12/site-packages/resolvelib/structs.py", line 127, in __bool__
    next(iter(self))
  File "/Users/luca/.local/share/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/resolver/providers.py", line 313, in matches_gen
    yield from super_find()
               ^^^^^^^^^^^^
  File "/Users/luca/.local/share/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/resolver/providers.py", line 184, in matches_gen
    candidates = self._find_candidates(reqs[0])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luca/.local/share/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/resolver/providers.py", line 158, in _find_candidates
    return self.repository.find_candidates(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luca/.local/share/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/models/repositories.py", line 173, in find_candidates
    cans = LazySequence(self._find_candidates(requirement, minimal_version=minimal_version))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luca/.local/share/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/models/repositories.py", line 440, in _find_candidates
    raise CandidateNotFound(
pdm.exceptions.CandidateNotFound: Unable to find candidates for private-pkg. There may exist some issues with the package name or network condition.
```

If I run:

```bash

PRIVATE_PAT=<PAT> pdm add private-pkg -v
```

Everything is installed correctly.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
 pdm info && pdm info --env
PDM version:
  2.11.1
Python Interpreter:
  /Users/luca/nemo/.venv/bin/python (3.10)
Project Root:
  /Users/luca/nemo
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.10.13",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "23.1.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 23.1.0: Mon Oct  9 21:32:11 PDT 2023; root:xnu-10002.41.9~7/RELEASE_ARM64_T6030",
  "python_full_version": "3.10.13",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
PDM doesn't read `.env` when managing dependencies, it's only for running scripts.
But you can achieve this with the help of `pdm.toml`.

```toml
# pyproject.toml
[[tool.pdm.source]]
name = "private"
url="https://<REPO-URL>"
include_packages = ["private-*"]
```

```toml
# pdm.toml
[pypi.private]
username = "__token__"
password = "<password>"
```

And remember to ignore `pdm.toml` from SCM.

Since there is already an obvious way to do it, I'll close it as resolved.

**Comment by znd4** [comment]
Thanks @JeyDi for the kind words! It'd be super cool to see this functionality implemented in pdm.

One big missing sub-feature that a plugin like `pdm-dotenv` can't support is adding variables to the output of `pdm venv activate`. 

`pdm run $SHELL` can be a decent workaround, but still feels worth mentioning.

**Comment by frostming** [comment]
> Configuring pdm.toml is a bit inconvenient because in the case of a structured project developers usually configure a single file with variables (an .env in fact).

@JeyDi I don't see why it's inconvenient.

Let's talk under the scenarios of CI/CD as you mentioned earlier. First, the credentials mustn't be committed to the VCS, So they must be specified on the spot in CI. So either `.env` or `pdm.toml` will likely be populated in the CI workflow.

To specify credentials in CI pipeline, you just need to run:

```
pdm config --local pypi.private.username xxx
pdm config --local pypi.private.password xxx
```
It's very much like how you configure git usernames in a CI pipeline. And you don't need to care about where the info is stored.

But using `.env`, how would you make such a file in a CI pipeline?

**Comment by baggiponte** [comment]
Hey there, thanks for the follow up. For my use-case, it's not a CI problem, but more of a continuity/collaboration matter and preserving the workflow of the team. In my personal experience, I have always found a bit of friction about this when explaining to my teammates:

1. They have to store _some_ secrets in the dotenv and some other in `pdm.toml`
2. Versioning has some friction too because tools like gitignore.io (i.e. GitHub's official Python [gitignore template](https://github.com/github/gitignore/blob/4488915eec0b3a45b5c63ead28f286819c0917de/Python.gitignore#L104-L110)) don't match PDM latest gitignore spec, so there's always some editing involved to port older projects - where the secrets are already stored in dotenv files.
3. I absolutely don't mean to downgrade the excellent job that @znd4 did with the plugin, but I received a flat no when recommending `pdm-dotenv` even though it's open source, purely because of the sensitive nature of the secrets stored.

Since PDM is already using python-dotenv and reads from `.env` when running scripts, I thought it'd be relatively easy to support looking for `PDM_*` env vars (or in the first code snippet I posted above) automatically in such files too.

**Comment by znd4** [comment]
@baggiponte, it should be possible to fork pdm-dotenv and configure pdm to install the fork. It doesn't solve all of your concerns, but it should at least solve the security concern.

I'll test it later and document it if it works
