### ISSUE TITLE
`pdm init .` raises [PdmException]: Template pyproject.toml not found

### ISSUE THREAD

**Issue by Tinche** [pdm-project/pdm#2520]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

In an empty directory, I run `pdm init .` and just press enter.

## Actual behavior

```
❯ pdm init -v .
Creating a pyproject.toml for PDM...
Please enter the Python interpreter to use
0. /Users/tintvrtkovic/.local/bin/python3 (3.11)
1. /Users/tintvrtkovic/.asdf/installs/python/3.12.0/bin/python3.12 (3.12)
2. /Users/tintvrtkovic/.asdf/installs/python/3.12.0rc3/bin/python3.12 (3.12)
3. /Users/tintvrtkovic/.asdf/installs/python/3.12.0b3/bin/python3.12 (3.12)
4. /usr/local/bin/python3.11 (3.11)
5. /Users/tintvrtkovic/.asdf/installs/python/3.11.3/bin/python3.11 (3.11)
6. /Users/tintvrtkovic/.asdf/installs/python/3.11.1/bin/python3.11 (3.11)
7. /Users/tintvrtkovic/pg/ap/.venv/bin/python (3.11)
8. /Users/tintvrtkovic/.asdf/installs/python/3.10.13/bin/python3.10 (3.10)
9. /usr/local/bin/python3.10 (3.10)
10. /Users/tintvrtkovic/.asdf/installs/python/3.10.5/bin/python3.10 (3.10)
11. /Users/tintvrtkovic/.asdf/installs/python/3.10.1/bin/python3.10 (3.10)
12. /Users/tintvrtkovic/.asdf/installs/python/3.10.0rc2/bin/python3.10 (3.10)
13. /Users/tintvrtkovic/.asdf/installs/python/3.9.18/bin/python3.9 (3.9)
14. /usr/local/bin/python3.9 (3.9)
15. /Users/tintvrtkovic/.asdf/installs/python/3.9.14/bin/python3.9 (3.9)
16. /Users/tintvrtkovic/.asdf/installs/python/pypy3.9-7.3.9/bin/pypy3.9 (3.9)
17. /Users/tintvrtkovic/.asdf/installs/python/3.9.12/bin/python3.9 (3.9)
18. /Users/tintvrtkovic/.asdf/installs/python/3.9.11/bin/python3.9 (3.9)
19. /Users/tintvrtkovic/.asdf/installs/python/3.9.10/bin/python3.9 (3.9)
20. /Users/tintvrtkovic/.asdf/installs/python/3.9.7/bin/python3.9 (3.9)
21. /usr/bin/python3 (3.9)
22. /Users/tintvrtkovic/.asdf/installs/python/3.9.0/bin/python3.9 (3.9)
23. /usr/local/bin/python3.8 (3.8)
24. /Users/tintvrtkovic/.asdf/installs/python/pypy3.8-7.3.7/bin/pypy3 (3.8)
25. /Users/tintvrtkovic/.asdf/installs/python/3.8.9/bin/python3.8 (3.8)
26. /Users/tintvrtkovic/.asdf/installs/python/3.7.13/bin/python3.7m (3.7)
27. /Users/tintvrtkovic/.asdf/installs/python/3.7.13/bin/python3.7 (3.7)
28. /Users/tintvrtkovic/.asdf/installs/python/2.7.18/bin/python2.7 (2.7)
Please select (0):
Would you like to create a virtualenv with /Users/tintvrtkovic/.local/bin/python3? [y/n] (y):
Cleaning existing target directory /Users/tintvrtkovic/pg/ap/.venv
Run command: ['/Users/tintvrtkovic/.local/bin/python3', '-m', 'venv', '/Users/tintvrtkovic/pg/ap/.venv', '--prompt=ap-3.11', '--without-pip']
Virtualenv is created successfully at /Users/tintvrtkovic/pg/ap/.venv
Project name (ap):
Project version (0.1.0):
Is the project a library that is installable?
If yes, we will need to ask a few more questions to include the build backend [y/n] (n):
License(SPDX name) (MIT):
Author name (Tin Tvrtković):
Author email (tinchester@gmail.com):
Python requires('*' to allow any) (==3.11.*):
Traceback (most recent call last):
  File "/Users/tintvrtkovic/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/tintvrtkovic/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 288, in main
    return Core().main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tintvrtkovic/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 208, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/Users/tintvrtkovic/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 203, in main
    self.handle(project, options)
  File "/Users/tintvrtkovic/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 157, in handle
    command.handle(project, options)
  File "/Users/tintvrtkovic/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/cli/commands/init.py", line 254, in handle
    self.do_init(project, options=options)
  File "/Users/tintvrtkovic/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/cli/commands/init.py", line 44, in do_init
    self._init_builtin(project, options)
  File "/Users/tintvrtkovic/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/cli/commands/init.py", line 86, in _init_builtin
    template.generate(project.root, metadata, options.overwrite)
  File "/Users/tintvrtkovic/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/cli/templates/__init__.py", line 52, in generate
    raise PdmException("Template pyproject.toml not found") from None
pdm.exceptions.PdmException: Template pyproject.toml not found

```

## Expected behavior

`pdm init .` sets up a new project.

## Environment Information

`pdm info` doesn't work since there's no pyproject.toml. I'm running pdm 2.11.1 installed via pipx on macOs.

**Comment by frostming** [comment]
The positional arg is the template name, not the project path. Just leave that

```
pdm init
```
would work.

**Comment by Tinche** [comment]
Ah oops, my bad. Thanks.
