### ISSUE TITLE
Unable to update black in venv with pdm update --update-all , permission denied

### ISSUE THREAD

**Issue by steakhutzeee** [pdm-project/pdm#2531]
- [ X ] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Update my project deps with `pdm update --update-all -v`.
Note that i use pyenv win to manage Python versions https://github.com/pyenv-win/pyenv-win but i'm inside the venv when i launch the update.

Log:

```
(my_project) PS C:\Users\user\code\user\my_project> pdm update --update-all -v
INFO: Inside an active virtualenv C:\Users\user\.venv\my_project, reusing it.
Set env var PDM_IGNORE_ACTIVE_VENV to ignore it.
STATUS: Resolving dependencies
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   holidays==0.30
pdm.termui:   pandas==2.0.3
pdm.termui:   tkcalendar==1.6.1
pdm.termui:   openpyxl==3.1.2
pdm.termui:   black>=22.12.0
pdm.termui:   isort>=5.12.0
pdm.termui:   flake8>=6.0.0
pdm.termui:   flake8-bugbear>=23.1.20
pdm.termui:   flake8-builtins>=2.1.0
pdm.termui:   flake8-comprehensions>=3.10.1
pdm.termui:   pep8-naming>=0.13.3
pdm.termui:   flake8-noqa>=1.3.2
pdm.termui:   flake8-eradicate>=1.5.0
pdm.termui:   python>=3.11.1
pdm.termui:   Adding requirement holidays==0.30
pdm.termui:   Adding requirement pandas==2.0.3
pdm.termui:   Adding requirement tkcalendar==1.6.1
pdm.termui:   Adding requirement openpyxl==3.1.2
pdm.termui:   Adding requirement black>=22.12.0
pdm.termui:   Adding requirement isort>=5.12.0
pdm.termui:   Adding requirement flake8>=6.0.0
pdm.termui:   Adding requirement flake8-bugbear>=23.1.20
pdm.termui:   Adding requirement flake8-builtins>=2.1.0
pdm.termui:   Adding requirement flake8-comprehensions>=3.10.1
pdm.termui:   Adding requirement pep8-naming>=0.13.3
pdm.termui:   Adding requirement flake8-noqa>=1.3.2
pdm.termui:   Adding requirement flake8-eradicate>=1.5.0
pdm.termui:   Adding requirement python>=3.11.1
pdm.termui: ======== Starting round 0 ========
STATUS: Resolving: new pin python>=3.11.1
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
pdm.termui:   Adding requirement python-dateutil(from holidays 0.30)
STATUS: Resolving: new pin holidays 0.30
pdm.termui: Pinning: holidays 0.30
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
pdm.termui:   Adding requirement et-xmlfile(from openpyxl 3.1.2)
STATUS: Resolving: new pin openpyxl 3.1.2
pdm.termui: Pinning: openpyxl 3.1.2
pdm.termui: ======== Ending round 2 ========
pdm.termui: ======== Starting round 3 ========
pdm.termui:   Adding requirement python-dateutil>=2.8.2(from pandas 2.0.3)
pdm.termui:   Adding requirement pytz>=2020.1(from pandas 2.0.3)
pdm.termui:   Adding requirement tzdata>=2022.1(from pandas 2.0.3)
pdm.termui:   Adding requirement numpy>=1.21.0; python_version >= "3.10"(from pandas 2.0.3)
pdm.termui:   Adding requirement numpy>=1.23.2; python_version >= "3.11"(from pandas 2.0.3)
STATUS: Resolving: new pin pandas 2.0.3
pdm.termui: Pinning: pandas 2.0.3
pdm.termui: ======== Ending round 3 ========
pdm.termui: ======== Starting round 4 ========
pdm.termui:   Adding requirement babel(from tkcalendar 1.6.1)
STATUS: Resolving: new pin tkcalendar 1.6.1
pdm.termui: Pinning: tkcalendar 1.6.1
pdm.termui: ======== Ending round 4 ========
pdm.termui: ======== Starting round 5 ========
pdm.termui:   Adding requirement click>=8.0.0(from black 23.12.1)
pdm.termui:   Adding requirement mypy-extensions>=0.4.3(from black 23.12.1)
pdm.termui:   Adding requirement packaging>=22.0(from black 23.12.1)
pdm.termui:   Adding requirement pathspec>=0.9.0(from black 23.12.1)
pdm.termui:   Adding requirement platformdirs>=2(from black 23.12.1)
STATUS: Resolving: new pin black 23.12.1
pdm.termui: Pinning: black 23.12.1
pdm.termui: ======== Ending round 5 ========
pdm.termui: ======== Starting round 6 ========
pdm.termui:   Adding requirement mccabe<0.8.0,>=0.7.0(from flake8 6.1.0)
pdm.termui:   Adding requirement pycodestyle<2.12.0,>=2.11.0(from flake8 6.1.0)
pdm.termui:   Adding requirement pyflakes<3.2.0,>=3.1.0(from flake8 6.1.0)
STATUS: Resolving: new pin flake8 6.1.0
pdm.termui: Pinning: flake8 6.1.0
pdm.termui: ======== Ending round 6 ========
pdm.termui: ======== Starting round 7 ========
pdm.termui:   Adding requirement flake8>=6.0.0(from flake8-bugbear 23.12.2)
pdm.termui:   Adding requirement attrs>=19.2.0(from flake8-bugbear 23.12.2)
STATUS: Resolving: new pin flake8-bugbear 23.12.2
pdm.termui: Pinning: flake8-bugbear 23.12.2
pdm.termui: ======== Ending round 7 ========
pdm.termui: ======== Starting round 8 ========
pdm.termui:   Adding requirement flake8(from flake8-builtins 2.2.0)
STATUS: Resolving: new pin flake8-builtins 2.2.0
pdm.termui: Pinning: flake8-builtins 2.2.0
pdm.termui: ======== Ending round 8 ========
pdm.termui: ======== Starting round 9 ========
pdm.termui:   Adding requirement flake8!=3.2.0,>=3.0(from flake8-comprehensions 3.14.0)
STATUS: Resolving: new pin flake8-comprehensions 3.14.0
pdm.termui: Pinning: flake8-comprehensions 3.14.0
pdm.termui: ======== Ending round 9 ========
pdm.termui: ======== Starting round 10 ========
pdm.termui:   Adding requirement attrs(from flake8-eradicate 1.5.0)
pdm.termui:   Adding requirement eradicate<3.0,>=2.0(from flake8-eradicate 1.5.0)
pdm.termui:   Adding requirement flake8>5(from flake8-eradicate 1.5.0)
STATUS: Resolving: new pin flake8-eradicate 1.5.0
pdm.termui: Pinning: flake8-eradicate 1.5.0
pdm.termui: ======== Ending round 10 ========
pdm.termui: ======== Starting round 11 ========
pdm.termui:   Adding requirement flake8<7.0,>=3.8.0(from flake8-noqa 1.3.2)
pdm.termui:   Adding requirement typing-extensions>=3.7.4.2(from flake8-noqa 1.3.2)
STATUS: Resolving: new pin flake8-noqa 1.3.2
pdm.termui: Pinning: flake8-noqa 1.3.2
pdm.termui: ======== Ending round 11 ========
pdm.termui: ======== Starting round 12 ========
STATUS: Resolving: new pin isort 5.13.2
pdm.termui: Pinning: isort 5.13.2
pdm.termui: ======== Ending round 12 ========
pdm.termui: ======== Starting round 13 ========
pdm.termui:   Adding requirement flake8>=5.0.0(from pep8-naming 0.13.3)
STATUS: Resolving: new pin pep8-naming 0.13.3
pdm.termui: Pinning: pep8-naming 0.13.3
pdm.termui: ======== Ending round 13 ========
pdm.termui: ======== Starting round 14 ========
STATUS: Resolving: new pin eradicate 2.3.0
pdm.termui: Pinning: eradicate 2.3.0
pdm.termui: ======== Ending round 14 ========
pdm.termui: ======== Starting round 15 ========
STATUS: Resolving: new pin mccabe 0.7.0
pdm.termui: Pinning: mccabe 0.7.0
pdm.termui: ======== Ending round 15 ========
pdm.termui: ======== Starting round 16 ========
STATUS: Resolving: new pin numpy 1.26.2
pdm.termui: Pinning: numpy 1.26.2
pdm.termui: ======== Ending round 16 ========
pdm.termui: ======== Starting round 17 ========
STATUS: Resolving: new pin pycodestyle 2.11.1
pdm.termui: Pinning: pycodestyle 2.11.1
pdm.termui: ======== Ending round 17 ========
pdm.termui: ======== Starting round 18 ========
STATUS: Resolving: new pin pyflakes 3.1.0
pdm.termui: Pinning: pyflakes 3.1.0
pdm.termui: ======== Ending round 18 ========
pdm.termui: ======== Starting round 19 ========
STATUS: Resolving: new pin attrs 23.2.0
pdm.termui: Pinning: attrs 23.2.0
pdm.termui: ======== Ending round 19 ========
pdm.termui: ======== Starting round 20 ========
pdm.termui:   Adding requirement colorama; platform_system == "Windows"(from click 8.1.7)
STATUS: Resolving: new pin click 8.1.7
pdm.termui: Pinning: click 8.1.7
pdm.termui: ======== Ending round 20 ========
pdm.termui: ======== Starting round 21 ========
STATUS: Resolving: new pin mypy-extensions 1.0.0
pdm.termui: Pinning: mypy-extensions 1.0.0
pdm.termui: ======== Ending round 21 ========
pdm.termui: ======== Starting round 22 ========
STATUS: Resolving: new pin packaging 23.2
pdm.termui: Pinning: packaging 23.2
pdm.termui: ======== Ending round 22 ========
pdm.termui: ======== Starting round 23 ========
STATUS: Resolving: new pin pathspec 0.12.1
pdm.termui: Pinning: pathspec 0.12.1
pdm.termui: ======== Ending round 23 ========
pdm.termui: ======== Starting round 24 ========
STATUS: Resolving: new pin platformdirs 4.1.0
pdm.termui: Pinning: platformdirs 4.1.0
pdm.termui: ======== Ending round 24 ========
pdm.termui: ======== Starting round 25 ========
pdm.termui:   Adding requirement six>=1.5(from python-dateutil 2.8.2)
STATUS: Resolving: new pin python-dateutil 2.8.2
pdm.termui: Pinning: python-dateutil 2.8.2
pdm.termui: ======== Ending round 25 ========
pdm.termui: ======== Starting round 26 ========
STATUS: Resolving: new pin pytz 2023.3.post1
pdm.termui: Pinning: pytz 2023.3.post1
pdm.termui: ======== Ending round 26 ========
pdm.termui: ======== Starting round 27 ========
STATUS: Resolving: new pin typing-extensions 4.9.0
pdm.termui: Pinning: typing-extensions 4.9.0
pdm.termui: ======== Ending round 27 ========
pdm.termui: ======== Starting round 28 ========
STATUS: Resolving: new pin tzdata 2023.4
pdm.termui: Pinning: tzdata 2023.4
pdm.termui: ======== Ending round 28 ========
pdm.termui: ======== Starting round 29 ========
STATUS: Resolving: new pin babel 2.14.0
pdm.termui: Pinning: babel 2.14.0
pdm.termui: ======== Ending round 29 ========
pdm.termui: ======== Starting round 30 ========
STATUS: Resolving: new pin et-xmlfile 1.1.0
pdm.termui: Pinning: et-xmlfile 1.1.0
pdm.termui: ======== Ending round 30 ========
pdm.termui: ======== Starting round 31 ========
STATUS: Resolving: new pin six 1.16.0
pdm.termui: Pinning: six 1.16.0
pdm.termui: ======== Ending round 31 ========
pdm.termui: ======== Starting round 32 ========
STATUS: Resolving: new pin colorama 0.4.6
pdm.termui: Pinning: colorama 0.4.6
pdm.termui: ======== Ending round 32 ========
pdm.termui: ======== Starting round 33 ========
pdm.termui: ======== Resolution Result ========
pdm.termui: Stable pins:
pdm.termui:                  python None
pdm.termui:                holidays 0.30
pdm.termui:                openpyxl 3.1.2
pdm.termui:                  pandas 2.0.3
pdm.termui:              tkcalendar 1.6.1
pdm.termui:                   black 23.12.1
pdm.termui:                  flake8 6.1.0
pdm.termui:          flake8-bugbear 23.12.2
pdm.termui:         flake8-builtins 2.2.0
pdm.termui:   flake8-comprehensions 3.14.0
pdm.termui:        flake8-eradicate 1.5.0
pdm.termui:             flake8-noqa 1.3.2
pdm.termui:                   isort 5.13.2
pdm.termui:             pep8-naming 0.13.3
pdm.termui:               eradicate 2.3.0
pdm.termui:                  mccabe 0.7.0
pdm.termui:                   numpy 1.26.2
pdm.termui:             pycodestyle 2.11.1
pdm.termui:                pyflakes 3.1.0
pdm.termui:                   attrs 23.2.0
pdm.termui:                   click 8.1.7
pdm.termui:         mypy-extensions 1.0.0
pdm.termui:               packaging 23.2
pdm.termui:                pathspec 0.12.1
pdm.termui:            platformdirs 4.1.0
pdm.termui:         python-dateutil 2.8.2
pdm.termui:                    pytz 2023.3.post1
pdm.termui:       typing-extensions 4.9.0
pdm.termui:                  tzdata 2023.4
pdm.termui:                   babel 2.14.0
pdm.termui:              et-xmlfile 1.1.0
pdm.termui:                     six 1.16.0
pdm.termui:                colorama 0.4.6
STATUS: Fetching hashes for resolved packages...
pdm.termui: Fetching hashes for holidays@0.30
pdm.termui: Fetching hashes for openpyxl@3.1.2
pdm.termui: Fetching hashes for tkcalendar@1.6.1
pdm.termui: Fetching hashes for flake8@6.1.0
pdm.termui: Fetching hashes for flake8-builtins@2.2.0
pdm.termui: Fetching hashes for flake8-bugbear@23.12.2
pdm.termui: Fetching hashes for black@23.12.1
pdm.termui: Fetching hashes for flake8-eradicate@1.5.0
pdm.termui: Fetching hashes for flake8-comprehensions@3.14.0
pdm.termui: Fetching hashes for flake8-noqa@1.3.2
pdm.termui: Fetching hashes for eradicate@2.3.0
pdm.termui: Fetching hashes for mccabe@0.7.0
pdm.termui: Fetching hashes for pep8-naming@0.13.3
pdm.termui: Fetching hashes for pyflakes@3.1.0
pdm.termui: Fetching hashes for isort@5.13.2
pdm.termui: Fetching hashes for pandas@2.0.3
pdm.termui: Fetching hashes for pycodestyle@2.11.1
pdm.termui: Fetching hashes for click@8.1.7
pdm.termui: Fetching hashes for attrs@23.2.0
pdm.termui: Fetching hashes for mypy-extensions@1.0.0
pdm.termui: Fetching hashes for et-xmlfile@1.1.0
pdm.termui: Fetching hashes for pathspec@0.12.1
pdm.termui: Fetching hashes for six@1.16.0
pdm.termui: Fetching hashes for python-dateutil@2.8.2
pdm.termui: Fetching hashes for tzdata@2023.4
pdm.termui: Fetching hashes for babel@2.14.0
pdm.termui: Fetching hashes for platformdirs@4.1.0
pdm.termui: Fetching hashes for typing-extensions@4.9.0
pdm.termui: Fetching hashes for packaging@23.2
pdm.termui: Fetching hashes for colorama@0.4.6
pdm.termui: Fetching hashes for pytz@2023.3.post1
pdm.termui: Fetching hashes for numpy@1.26.2
🔒 Lock successful
STATUS: Resolving packages from lockfile...
STATUS: Fetching hashes for resolved packages...
Synchronizing working set with resolved packages: 0 to add, 1 to update, 0 to remove

pdm.termui: Overwriting distribution black
unearth.preparer: Using cached <Link https://files.pythonhosted.org/packages/37/bf/a80abc6fcdb00f0d4d3d74184b172adbf2197f6b002913fa0fb6af4dc6db/black-23.12.1-cp311-cp311-win_amd64.whl (from https://pypi.org/simple/black/)>
  ✖ Update black 23.12.0 -> 23.12.1 failed
pdm.termui: Error occurs:
Traceback (most recent call last):
  File "C:\Users\user\.pyenv\pyenv-win\versions\3.11.4\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\installers\synchronizers.py", line 307, in update_candidate
    self.manager.overwrite(dist, can)
  File "C:\Users\user\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\installers\manager.py", line 58, in overwrite
    installed = self.install(candidate)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\installers\manager.py", line 34, in install
    dist_info = installer(str(prepared.build()), self.environment, prepared.direct_url())
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\installers\installers.py", line 199, in install_wheel
    return _install_wheel(wheel=wheel, destination=destination, additional_metadata=additional_metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\installers\installers.py", line 312, in _install_wheel
    install(source, destination, additional_metadata=additional_metadata or {})
  File "C:\Users\user\AppData\Roaming\pdm\venv\Lib\site-packages\installer\_core.py", line 109, in install
    record = destination.write_file(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\pdm\venv\Lib\site-packages\installer\destinations.py", line 207, in write_file
    return self.write_to_fs(scheme, path_, stream, is_executable)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\installers\installers.py", line 166, in write_to_fs
    os.unlink(target_path)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\user\\.venv\\my_project\\Lib\\site-packages\\black/__init__.cp311-win_amd64.pyd'
Retry failed jobs
pdm.termui: Overwriting distribution black
  ✖ Update black 23.12.0 -> 23.12.1 failed
pdm.termui: Error occurs:
Traceback (most recent call last):
  File "C:\Users\user\.pyenv\pyenv-win\versions\3.11.4\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\installers\synchronizers.py", line 307, in update_candidate
    self.manager.overwrite(dist, can)
  File "C:\Users\user\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\installers\manager.py", line 58, in overwrite
    installed = self.install(candidate)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\installers\manager.py", line 34, in install
    dist_info = installer(str(prepared.build()), self.environment, prepared.direct_url())
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\installers\installers.py", line 199, in install_wheel
    return _install_wheel(wheel=wheel, destination=destination, additional_metadata=additional_metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\installers\installers.py", line 312, in _install_wheel
    install(source, destination, additional_metadata=additional_metadata or {})
  File "C:\Users\user\AppData\Roaming\pdm\venv\Lib\site-packages\installer\_core.py", line 109, in install
    record = destination.write_file(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\pdm\venv\Lib\site-packages\installer\destinations.py", line 207, in write_file
    return self.write_to_fs(scheme, path_, stream, is_executable)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\installers\installers.py", line 166, in write_to_fs
    os.unlink(target_path)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\user\\.venv\\my_project\\Lib\\site-packages\\black/__init__.cp311-win_amd64.pyd'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\user\appdata\roaming\python\scripts\pdm.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\core.py", line 288, in main
    return Core().main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\core.py", line 208, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "C:\Users\user\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\core.py", line 203, in main
    self.handle(project, options)
  File "C:\Users\user\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\core.py", line 157, in handle
    command.handle(project, options)
  File "C:\Users\user\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\cli\commands\update.py", line 73, in handle
    self.do_update(
  File "C:\Users\user\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\cli\commands\update.py", line 189, in do_update
    do_sync(
  File "C:\Users\user\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\cli\actions.py", line 238, in do_sync
    synchronizer.synchronize()
  File "C:\Users\user\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\installers\synchronizers.py", line 454, in synchronize
    raise InstallationError("Some package operations are not complete yet")
pdm.exceptions.InstallationError: Some package operations are not complete yet
(my_project) PS C:\Users\user\code\user\my_project>
```

## Actual behavior

All packages are updated but black fails to update. This happened also with the previous version of black and i resolved deleting and recreating the venv and installing all deps with pdm.

## Expected behavior

black to be updated.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:

(my_project) PS C:\Users\user\code\user\my_project> pdm info && pdm info --env
INFO: Inside an active virtualenv C:\Users\user\.venv\my_project, reusing it.
Set env var PDM_IGNORE_ACTIVE_VENV to ignore it.
PDM version:
  2.11.2
Python Interpreter:
  C:\Users\user\.venv\my_project\Scripts\python.exe (3.11)
Project Root:
  C:/Users/user/code/user/my_project
Local Packages:

INFO: Inside an active virtualenv C:\Users\user\.venv\my_project, reusing it.
Set env var PDM_IGNORE_ACTIVE_VENV to ignore it.
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.4",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.22621",
  "python_full_version": "3.11.4",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "win32"
}
(my_project) PS C:\Users\user\code\user\my_project>

```

**Comment by frostming** [comment]
There might be a background process using black, such as your IDE. In this case, Windows will prevent it from being deleted.

**Comment by steakhutzeee** [comment]
Yes, thanks. Updating outside of VS code fixed it.
