### ISSUE TITLE
Crash during pdm install with json.decoder.JSONDecodeError: Unterminated string ...

### ISSUE THREAD

**Issue by paugier** [pdm-project/pdm#2532]
## Steps to reproduce

I get a long traceback while running `pdm install -G dev -v` in a Gitlab CI (https://foss.heptapod.net/fluiddyn/fluidsim/-/jobs/2206353).

```
$ pdm install -G dev -v
STATUS: Resolving packages from lockfile...
INFO: python.use_venv is on, creating a virtualenv for this project...
Run command: ['/usr/local/bin/python', '-m', 'virtualenv', '/builds/fluiddyn/fluidsim/.venv', '-p', '/usr/local/bin/python', '--prompt=fluidsim-3.9', '--no-pip', '--no-setuptools', '--no-wheel']
created virtual environment CPython3.9.16.final.0-64 in 196ms
  creator CPython3Posix(dest=/builds/fluiddyn/fluidsim/.venv, clear=False, no_vcs_ignore=False, global=False)
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
Virtualenv is created successfully at /builds/fluiddyn/fluidsim/.venv
unearth.preparer: The file . is a local directory, use it directly
Synchronizing working set with resolved packages: 49 to add, 0 to update, 0 to remove
pdm.termui: Preparing environment(Isolated mode) for PEP 517 build...
pdm.termui: Running PEP 517 backend to build a wheel for <Link file:///builds/fluiddyn/fluidsim/lib (from None)>
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   flit-core<4,>=3.2
pdm.termui:   python>=3.9.16,<3.9.17
pdm.termui:   Adding requirement flit-core<4,>=3.2
  ✖ Install fluidsim-core 0.7.4 failed
Traceback (most recent call last):
  File "/home/appuser/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/appuser/.local/lib/python3.9/site-packages/pdm/core.py", line 288, in main
    return Core().main(args or sys.argv[1:])
  File "/home/appuser/.local/lib/python3.9/site-packages/pdm/core.py", line 208, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/home/appuser/.local/lib/python3.9/site-packages/pdm/core.py", line 203, in main
    self.handle(project, options)
  File "/home/appuser/.local/lib/python3.9/site-packages/pdm/core.py", line 157, in handle
    command.handle(project, options)
  File "/home/appuser/.local/lib/python3.9/site-packages/pdm/cli/commands/install.py", line 100, in handle
    actions.do_sync(
  File "/home/appuser/.local/lib/python3.9/site-packages/pdm/cli/actions.py", line 238, in do_sync
    synchronizer.synchronize()
  File "/home/appuser/.local/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 436, in synchronize
    handlers[kind](key, progress)
  File "/home/appuser/.local/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 286, in install_candidate
    self.manager.install(can)
  File "/home/appuser/.local/lib/python3.9/site-packages/pdm/installers/manager.py", line 34, in install
    dist_info = installer(str(prepared.build()), self.environment, prepared.direct_url())
  File "/home/appuser/.local/lib/python3.9/site-packages/pdm/models/candidates.py", line 418, in build
    self.wheel = Path(builder.build(build_dir, metadata_directory=self._metadata_dir))
  File "/home/appuser/.local/lib/python3.9/site-packages/pdm/builders/editable.py", line 37, in build
    self.install(self._requires, shared=True)
  File "/home/appuser/.local/lib/python3.9/site-packages/pdm/builders/base.py", line 298, in install
    install_requirements(missing, env)
  File "/home/appuser/.local/lib/python3.9/site-packages/pdm/installers/core.py", line 25, in install_requirements
    resolved, _ = resolve(resolver, reqs, environment.python_requires, max_rounds=resolve_max_rounds, keep_self=True)
  File "/home/appuser/.local/lib/python3.9/site-packages/pdm/resolver/core.py", line 39, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "/home/appuser/.local/lib/python3.9/site-packages/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/appuser/.local/lib/python3.9/site-packages/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/home/appuser/.local/lib/python3.9/site-packages/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "/home/appuser/.local/lib/python3.9/site-packages/resolvelib/structs.py", line 127, in __bool__
    next(iter(self))
  File "/home/appuser/.local/lib/python3.9/site-packages/resolvelib/structs.py", line 136, in __iter__
    self._factory() if self._iterable is None else self._iterable
  File "/home/appuser/.local/lib/python3.9/site-packages/pdm/resolver/providers.py", line 184, in matches_gen
    candidates = self._find_candidates(reqs[0])
  File "/home/appuser/.local/lib/python3.9/site-packages/pdm/resolver/providers.py", line 158, in _find_candidates
    return self.repository.find_candidates(
  File "/home/appuser/.local/lib/python3.9/site-packages/pdm/models/repositories.py", line 173, in find_candidates
    cans = LazySequence(self._find_candidates(requirement, minimal_version=minimal_version))
  File "/home/appuser/.local/lib/python3.9/site-packages/pdm/models/repositories.py", line 440, in _find_candidates
    for c in finder.find_all_packages(requirement.project_name, allow_yanked=requirement.is_pinned)
  File "/home/appuser/.local/lib/python3.9/site-packages/unearth/finder.py", line 295, in find_all_packages
    self._find_packages(package_name, allow_yanked), hashes=hashes or {}
  File "/home/appuser/.local/lib/python3.9/site-packages/unearth/finder.py", line 275, in _find_packages
    return sorted(all_packages, key=self._sort_key, reverse=True)
  File "/home/appuser/.local/lib/python3.9/site-packages/unearth/collector.py", line 135, in collect_links_from_location
    yield from _collect_links_from_index(session, location)
  File "/home/appuser/.local/lib/python3.9/site-packages/unearth/collector.py", line 85, in parse_json_response
    data = json.loads(page.content)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 10236 (char 10235)
```

This traceback is obtained only in the CI. The same command works fine locally and also in the same Docker image run locally.

I can install packages without PDM (for example with pip or tox) with this docker image and Gitlab CI.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
$ pdm info
INFO: python.use_venv is on, creating a virtualenv for this project...
Virtualenv is created successfully at /builds/fluiddyn/fluidsim/.venv
PDM version:
  2.11.2
Python Interpreter:
  /builds/fluiddyn/fluidsim/.venv/bin/python (3.9)
Project Root:
  /builds/fluiddyn/fluidsim
Local Packages:
  
/home/appuser/.local/lib/python3.9/site-packages/pdm/cli/actions.py:335: RuntimeWarning: Failed to get latest version: Unterminated string starting at: line 1 column 122786 (char 122785)
  warnings.warn(f"Failed to get latest version: {e}", RuntimeWarning, stacklevel=1)

$ pdm info --env
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.16",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.10.0-8-amd64",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Debian 5.10.46-4 (2021-08-03)",
  "python_full_version": "3.9.16",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

**Comment by paugier** [comment]
I used a modified version of unearth to see where it fails: 

```
  File "/home/appuser/.local/lib/python3.9/site-packages/pdm/models/repositories.py", line 440, in _find_candidates
    for c in finder.find_all_packages(requirement.project_name, allow_yanked=requirement.is_pinned)
  File "/builds/fluiddyn/unearth/src/unearth/finder.py", line 301, in find_all_packages
    raise RuntimeError(f"{package_name=}, {allow_yanked=}, {hashes=}")
RuntimeError: package_name='flit-core', allow_yanked=False, hashes=None
```

I guess one could easily reproduce only using unearth.

**Comment by frostming** [comment]
Close this since it is reported upstream
