### ISSUE TITLE
pdm fails to find different versions of a dependency for different platforms

### ISSUE THREAD

**Issue by paugier** [pdm-project/pdm#2566]
In a new clean project created with `pdm init`, `pdm add pyqt5` leads to this error:

```
Adding packages to default dependencies: pyqt5
🔒 Lock successful
Changes are written to pyproject.toml.
Synchronizing working set with resolved packages: 1 to add, 0 to update, 0 to remove

  ✖ Install pyqt5-qt5 5.15.12 failed
Retry failed jobs
  ✖ Install pyqt5-qt5 5.15.12 failed

ERRORS:
add pyqt5-qt5 failed:
Traceback (most recent call last):
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/users/augier3pi/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 286, in 
install_candidate
    self.manager.install(can)
  File "/home/users/augier3pi/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/installers/manager.py", line 34, in install
    dist_info = installer(str(prepared.build()), self.environment, prepared.direct_url())
  File "/home/users/augier3pi/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/models/candidates.py", line 403, in build
    self.obtain(allow_all=False)
  File "/home/users/augier3pi/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/models/candidates.py", line 447, in obtain
    raise CandidateNotFound(
pdm.exceptions.CandidateNotFound: No candidate is found for `pyqt5-qt5` that matches the environment or hashes

See /tmp/pdm-install-lus99ysv.log for detailed debug log.
[InstallationError]: Some package operations are not complete yet
```

The problem seems to be related to https://pypi.org/project/PyQt5-Qt5 which has a version 5.15.12 only for MacOS (https://pypi.org/project/PyQt5-Qt5/#files). A wheel for Linux is available in https://pypi.org/project/PyQt5-Qt5/5.15.2/#files

A bad workaround is to use `pdm add pyqt5 pyqt5-qt5==5.15.2`. It's bad and not acceptable because it writes

```
dependencies = [
    "pyqt5>=5.15.10",
    "pyqt5-qt5==5.15.2",
]
```
so that the project can't be installed on MacOS.

It seems that a clean solution would be to have different versions for different platforms.

Note that Pixi does that with a `platforms` parameter (https://pixi.sh/configuration/#platforms), solving the dependencies for the different platform and including in its lock file the different results.

## Environment Information

```bash
PDM version:
  2.11.2
Python Interpreter:
  /home/users/augier3pi/tmp/bug_pdm_pyqt5/.venv/bin/python (3.9)
Project Root:
  /home/users/augier3pi/tmp/bug_pdm_pyqt5
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.2",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.10.0-27-amd64",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Debian 5.10.205-2 (2023-12-31)",
  "python_full_version": "3.9.2",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

**Comment by paugier** [comment]
A better workaround would actually be to use `pdm lock --strategy no_cross_platform` (https://pdm-project.org/latest/usage/dependency/#cross-platform).

However, it's buggy because it does not list wheels for different python versions:

```
[[package]]
name = "scipy"
version = "1.11.4"
requires_python = ">=3.9"
summary = "Fundamental algorithms for scientific computing in Python"
groups = ["doc", "full", "test"]
dependencies = [
    "numpy<1.28.0,>=1.21.6",
]
files = [
    {file = "scipy-1.11.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", hash = "sha256:91af76a68eeae0064887a48e25c4e616fa519fa0d38602eda7e0f97d65d57937"},
    {file = "scipy-1.11.4.tar.gz", hash = "sha256:90a2b78e7f5733b9de748f589f09225013685f9b218275257f8a8168ededaeaa"},
]
```

so installing with another Python version uses the sdist. I opened #2568 to track this specific problem.
