### ISSUE TITLE
Problem Starting Spoolman "RuntimeError: Directory 'client/dist' does not exist"

### ISSUE THREAD

**Issue by Robnex** [pdm-project/pdm#2583]
System: Biqu Pad 7
Linux: Debian GNU/Linux 11 (bullseye)
Spoolman installed as Service with "bash ./scripts/install_debian.sh"

## Steps to reproduce
sudo systemctl start Spoolman.service

## Actual behavior

Spoolman stops with error. 
Running "sudo journalctl -u Spoolman"
![Spoolman](https://github.com/pdm-project/pdm/assets/97597150/f3f06155-c6cb-45dc-be02-7bccf3e8e628)

No open Port 7912 with:
"netstat -tulpn"

## Expected behavior

Spoolman starts without error.

## Environment Information
```
PDM version:
  2.12.2
Python Interpreter:
  /home/biqu/Spoolman/.venv/bin/python (3.9)
Project Root:
  /home/biqu/Spoolman
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.9.2",
  "os_name": "posix",
  "platform_machine": "aarch64",
  "platform_release": "5.16.17-sun50iw9",
  "platform_system": "Linux",
  "platform_version": "#2.3.3 SMP Wed Jul 12 11:07:49 CST 2023",
  "python_full_version": "3.9.2",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

**Comment by Robnex** [comment]
Output of the error:

```
WARNING: /home/biqu/.local/bin is not in PATH, this will make it difficult to run PDM commands. Temporarily addin>
Jan 23 17:22:25 BTT-Pad7 start.sh[39849]: To make this permanent, add the following line to your .bashrc or .zshrc file:
Jan 23 17:22:25 BTT-Pad7 start.sh[39849]: export PATH=/home/biqu/.local/bin:$PATH
Jan 23 17:22:25 BTT-Pad7 start.sh[39849]: Starting Spoolman...
Jan 23 17:22:33 BTT-Pad7 start.sh[39875]: Traceback (most recent call last):
Jan 23 17:22:33 BTT-Pad7 start.sh[39875]:   File "/home/biqu/Spoolman/.venv/bin/uvicorn", line 8, in <module>
Jan 23 17:22:33 BTT-Pad7 start.sh[39875]:     sys.exit(main())
Jan 23 17:22:33 BTT-Pad7 start.sh[39875]:   File "/home/biqu/Spoolman/.venv/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
Jan 23 17:22:33 BTT-Pad7 start.sh[39875]:     return self.main(*args, **kwargs)
Jan 23 17:22:33 BTT-Pad7 start.sh[39875]:   File "/home/biqu/Spoolman/.venv/lib/python3.9/site-packages/click/core.py", line 1078, in main
Jan 23 17:22:33 BTT-Pad7 start.sh[39875]:     rv = self.invoke(ctx)
Jan 23 17:22:33 BTT-Pad7 start.sh[39875]:   File "/home/biqu/Spoolman/.venv/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
Jan 23 17:22:33 BTT-Pad7 start.sh[39875]:     return ctx.invoke(self.callback, **ctx.params)
Jan 23 17:22:33 BTT-Pad7 start.sh[39875]:   File "/home/biqu/Spoolman/.venv/lib/python3.9/site-packages/click/core.py", line 783, in invoke
Jan 23 17:22:33 BTT-Pad7 start.sh[39875]:     return __callback(*args, **kwargs)
Jan 23 17:22:33 BTT-Pad7 start.sh[39875]:   File "/home/biqu/Spoolman/.venv/lib/python3.9/site-packages/uvicorn/main.py", line 410, in main
Jan 23 17:22:33 BTT-Pad7 start.sh[39875]:     run(
Jan 23 17:22:33 BTT-Pad7 start.sh[39875]:   File "/home/biqu/Spoolman/.venv/lib/python3.9/site-packages/uvicorn/main.py", line 578, in run
Jan 23 17:22:33 BTT-Pad7 start.sh[39875]:     server.run()
Jan 23 17:22:33 BTT-Pad7 start.sh[39875]:   File "/home/biqu/Spoolman/.venv/lib/python3.9/site-packages/uvicorn/server.py", line 61, in run
Jan 23 17:22:33 BTT-Pad7 start.sh[39875]:     return asyncio.run(self.serve(sockets=sockets))
Jan 23 17:22:33 BTT-Pad7 start.sh[39875]:   File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
Jan 23 17:22:33 BTT-Pad7 start.sh[39875]:     return loop.run_until_complete(main)
Jan 23 17:22:33 BTT-Pad7 start.sh[39875]:   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
Jan 23 17:22:33 BTT-Pad7 start.sh[39875]:   File "/home/biqu/Spoolman/.venv/lib/python3.9/site-packages/uvicorn/server.py", line 68, in serve
Jan 23 17:22:33 BTT-Pad7 start.sh[39875]:     config.load()
Jan 23 17:22:33 BTT-Pad7 start.sh[39875]:   File "/home/biqu/Spoolman/.venv/lib/python3.9/site-packages/uvicorn/config.py", line 473, in load
Jan 23 17:22:33 BTT-Pad7 start.sh[39875]:     self.loaded_app = import_from_string(self.app)
Jan 23 17:22:33 BTT-Pad7 start.sh[39875]:   File "/home/biqu/Spoolman/.venv/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
Jan 23 17:22:33 BTT-Pad7 start.sh[39875]:     module = importlib.import_module(module_str)
Jan 23 17:22:33 BTT-Pad7 start.sh[39875]:   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
Jan 23 17:22:33 BTT-Pad7 start.sh[39875]:     return _bootstrap._gcd_import(name[level:], package, level)
Jan 23 17:22:33 BTT-Pad7 start.sh[39875]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
Jan 23 17:22:33 BTT-Pad7 start.sh[39875]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Jan 23 17:22:33 BTT-Pad7 start.sh[39875]:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
Jan 23 17:22:33 BTT-Pad7 start.sh[39875]:   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
Jan 23 17:22:33 BTT-Pad7 start.sh[39875]:   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
Jan 23 17:22:33 BTT-Pad7 start.sh[39875]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
Jan 23 17:22:33 BTT-Pad7 start.sh[39875]:   File "/home/biqu/Spoolman/spoolman/main.py", line 40, in <module>
Jan 23 17:22:33 BTT-Pad7 start.sh[39875]:     app.mount("/", app=SinglePageApplication(directory="client/dist"), name="client")
Jan 23 17:22:33 BTT-Pad7 start.sh[39875]:   File "/home/biqu/Spoolman/spoolman/client.py", line 16, in __init__
Jan 23 17:22:33 BTT-Pad7 start.sh[39875]:     super().__init__(directory=directory, packages=None, html=True, check_dir=True)
Jan 23 17:22:33 BTT-Pad7 start.sh[39875]:   File "/home/biqu/Spoolman/.venv/lib/python3.9/site-packages/starlette/staticfiles.py", line 57, in __init__
Jan 23 17:22:33 BTT-Pad7 start.sh[39875]:     raise RuntimeError(f"Directory '{directory}' does not exist")
Jan 23 17:22:33 BTT-Pad7 start.sh[39875]: RuntimeError: Directory 'client/dist' does not exist
Jan 23 17:22:34 BTT-Pad7 systemd[1]: Spoolman.service: Main process exited, code=exited, status=1/FAILURE
Jan 23 17:22:34 BTT-Pad7 systemd[1]: Spoolman.service: Failed with result 'exit-code'.

```

**Comment by pawamoy** [comment]
It does not look like it has anything to do with PDM. This is likely a problem with spoolman or your setup. The starlette server does not find this directory. I suggest closing this issue and reopening in a more relevant repository.

**Comment by Robnex** [comment]
What do you mean with more relevant repository. 

When the Scarlett server don't find a directory there should be a fix?

When I create the /Spoolman/client/dist the service starts but the Webserver don't start correctly.

**Comment by pawamoy** [comment]
I mean Spoolman's repository, to get help there. I suspect you just need to create the missing directory (or spoolman has a bug).

**Comment by Robnex** [comment]
Oh damn. I see what you mean. I really posted in the wrong repository. Sorry for that.
