### ISSUE TITLE
PDM fails to solve constraint for protobuf

### ISSUE THREAD

**Issue by baggiponte** [pdm-project/pdm#2596]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

```
mkdir tmp/test
cd tmp/test
pdm init -n
pdm add llm-guard
pdm add "protobuf>=3.30,<4"
```

- I am using the latest Python 3.10
- `llm-guard` might fail to install because of `xformers`. It didn't for me, but that may have been because of a previous version already being in the cache. Using `--no-isolation` worked the first time.
- `llm-guard` specifies `protobuf<4,>=3.2.0`. This installs version `3.20.3`. For whatever reason, I needed to have it `>3.30` but when I try bumping the version, the resolution fails:

```
❯ pdm add "protobuf<4,>=3.30" -v
Adding packages to default dependencies: protobuf<4,>=3.30
STATUS: Resolving dependencies
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   llm-guard>=0.3.7
pdm.termui:   protobuf<4,>=3.30
pdm.termui:   python>=3.10,<3.11
pdm.termui:   Adding requirement llm-guard>=0.3.7
pdm.termui:   Adding requirement protobuf<4,>=3.30
🔒 Lock failed
WARNING: Unable to find a resolution for protobuf
Please make sure the package name is correct.
Traceback (most recent call last):
  File "/Users/luca/.local/share/pipx/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/luca/.local/share/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/core.py", line 288, in main
    return Core().main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luca/.local/share/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/core.py", line 208, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/Users/luca/.local/share/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/core.py", line 203, in main
    self.handle(project, options)
  File "/Users/luca/.local/share/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/core.py", line 157, in handle
    command.handle(project, options)
  File "/Users/luca/.local/share/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/cli/commands/add.py", line 69, in handle
    self.do_add(
  File "/Users/luca/.local/share/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/cli/commands/add.py", line 159, in do_add
    resolved = do_lock(
               ^^^^^^^^
  File "/Users/luca/.local/share/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/cli/actions.py", line 124, in do_lock
    raise ResolutionImpossible("Unable to find a resolution") from None
resolvelib.resolvers.ResolutionImpossible: Unable to find a resolution
```

```bash
# Paste the output of `pdm info && pdm info --env` below:
pdm info && pdm info --env
PDM version:
  2.12.2
Python Interpreter:
  /private/tmp/test/.venv/bin/python (3.10)
Project Root:
  /private/tmp/test
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.10.13",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "23.1.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 23.1.0: Mon Oct  9 21:32:11 PDT 2023; root:xnu-10002.41.9~7/RELEASE_ARM64_T6030",
  "python_full_version": "3.10.13",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "darwin"
}
```

**Comment by baggiponte** [comment]
My bad, 3.30 does not exist.
