### ISSUE TITLE
ChunkedEncodingError raised when adding pytest 7.4.4

### ISSUE THREAD

**Issue by houbie** [pdm-project/pdm#2598]
`pdm add pytest==7.4.4` fails with a ChunkedEncodingError:

```
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   pytest==7.4.4
pdm.termui:   python>=3.8,<3.9
pdm.termui:   Adding requirement pytest==7.4.4
Traceback (most recent call last):
  File "/tmp/venv/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/tmp/venv/lib/python3.8/site-packages/pdm/core.py", line 288, in main
    return Core().main(args or sys.argv[1:])
  File "/tmp/venv/lib/python3.8/site-packages/pdm/core.py", line 208, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/tmp/venv/lib/python3.8/site-packages/pdm/core.py", line 203, in main
    self.handle(project, options)
  File "/tmp/venv/lib/python3.8/site-packages/pdm/core.py", line 157, in handle
    command.handle(project, options)
  File "/tmp/venv/lib/python3.8/site-packages/pdm/cli/commands/add.py", line 69, in handle
    self.do_add(
  File "/tmp/venv/lib/python3.8/site-packages/pdm/cli/commands/add.py", line 159, in do_add
    resolved = do_lock(
  File "/tmp/venv/lib/python3.8/site-packages/pdm/cli/actions.py", line 102, in do_lock
    mapping, dependencies = resolve(
  File "/tmp/venv/lib/python3.8/site-packages/pdm/resolver/core.py", line 39, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "/tmp/venv/lib/python3.8/site-packages/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/tmp/venv/lib/python3.8/site-packages/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/tmp/venv/lib/python3.8/site-packages/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "/tmp/venv/lib/python3.8/site-packages/resolvelib/structs.py", line 127, in __bool__
    next(iter(self))
  File "/tmp/venv/lib/python3.8/site-packages/pdm/resolver/providers.py", line 354, in matches_gen
    yield from super_find()
  File "/tmp/venv/lib/python3.8/site-packages/pdm/resolver/providers.py", line 230, in matches_gen
    candidates = self._find_candidates(reqs[0])
  File "/tmp/venv/lib/python3.8/site-packages/pdm/resolver/providers.py", line 202, in _find_candidates
    return self.repository.find_candidates(
  File "/tmp/venv/lib/python3.8/site-packages/pdm/models/repositories.py", line 173, in find_candidates
    cans = LazySequence(self._find_candidates(requirement, minimal_version=minimal_version))
  File "/tmp/venv/lib/python3.8/site-packages/pdm/models/repositories.py", line 440, in _find_candidates
    for c in finder.find_all_packages(requirement.project_name, allow_yanked=requirement.is_pinned)
  File "/tmp/venv/lib/python3.8/site-packages/unearth/finder.py", line 287, in find_all_packages
    self._find_packages(package_name, allow_yanked), hashes=hashes or {}
  File "/tmp/venv/lib/python3.8/site-packages/unearth/finder.py", line 267, in _find_packages
    return sorted(all_packages, key=self._sort_key, reverse=True)
  File "/tmp/venv/lib/python3.8/site-packages/unearth/collector.py", line 135, in collect_links_from_location
    yield from _collect_links_from_index(session, location)
  File "/tmp/venv/lib/python3.8/site-packages/unearth/collector.py", line 155, in _collect_links_from_index
    page = fetch_page(session, location)
  File "/tmp/venv/lib/python3.8/site-packages/unearth/collector.py", line 142, in fetch_page
    resp = _get_html_response(session, location)
  File "/tmp/venv/lib/python3.8/site-packages/unearth/collector.py", line 177, in _get_html_response
    resp = session.get(
  File "/tmp/venv/lib/python3.8/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/tmp/venv/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/tmp/venv/lib/python3.8/site-packages/unearth/session.py", line 147, in send
    return super().send(request, **kwargs)
  File "/tmp/venv/lib/python3.8/site-packages/requests/sessions.py", line 747, in send
    r.content
  File "/tmp/venv/lib/python3.8/site-packages/requests/models.py", line 899, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
  File "/tmp/venv/lib/python3.8/site-packages/requests/models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(34034 bytes read, 261 more expected)', IncompleteRead(34034 bytes read, 261 more expected))
```
Running `pdm install` on an existing project with pytest==7.4.4 in pdm.lock, fails with the same error.

## Expected behavior
pytest 7.4.4 should be installed because it is not yanked in pypi and can still be installed with `pip install pytest==7.4.4`

## Environment Information
Tested with python 3.8 amd 3.12

This might be a pypi issue, but pdm handles is different than pip.

**Comment by frostming** [comment]
clear the cache: `pdm cache clear` and try again.

Also, what is the version of `cachecontrol` are you using?: `pdm self list`

**Comment by houbie** [comment]
Clearing the cache did the trick. Thanks for the swift response!
FYI: using CacheControl 0.13.1
