### ISSUE TITLE
When installing PyTorch 2.2, I encountered a read time out.

### ISSUE THREAD

**Issue by lingkerio** [pdm-project/pdm#2622]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

pdm add torch torchaudio torchvision -v

## Actual behavior

STATUS: Resolving: new pin torch 2.2.0
pdm.termui: Pinning: torch 2.2.0
pdm.termui: ======== Ending round 10 ========
pdm.termui: ======== Starting round 11 ========
unearth.preparer: Downloading <Link https://files.pythonhosted.org/packages/0f/95/48fdbba24c93614d1ecd35bc6bdc6087bd17cbacc3abc4b05a9c2a1ca232/nvidia_cusparse_cu12-12.1.0.106-py3-none-win_amd64.whl (from https://pypi.org/simple/nvidia-cusparse-cu12/)> (195.4 MB)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Scoop\apps\pdm\current\venv\Scripts\pdm.exe\__main__.py", line 7, in <module>
  File "D:\Scoop\apps\pdm\2.12.3\venv\Lib\site-packages\pdm\core.py", line 288, in main
    return Core().main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Scoop\apps\pdm\2.12.3\venv\Lib\site-packages\pdm\core.py", line 208, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "D:\Scoop\apps\pdm\2.12.3\venv\Lib\site-packages\pdm\core.py", line 203, in main
    self.handle(project, options)
  File "D:\Scoop\apps\pdm\2.12.3\venv\Lib\site-packages\pdm\core.py", line 157, in handle
    command.handle(project, options)
  File "D:\Scoop\apps\pdm\2.12.3\venv\Lib\site-packages\pdm\cli\commands\add.py", line 69, in handle
    self.do_add(
  File "D:\Scoop\apps\pdm\2.12.3\venv\Lib\site-packages\pdm\cli\commands\add.py", line 159, in do_add
    resolved = do_lock(
               ^^^^^^^^
  File "D:\Scoop\apps\pdm\2.12.3\venv\Lib\site-packages\pdm\cli\actions.py", line 102, in do_lock
    mapping, dependencies = resolve(
                            ^^^^^^^^
  File "D:\Scoop\apps\pdm\2.12.3\venv\Lib\site-packages\pdm\resolver\core.py", line 39, in resolve
    result = resolver.resolve(requirements, max_rounds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Scoop\apps\pdm\2.12.3\venv\Lib\site-packages\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Scoop\apps\pdm\2.12.3\venv\Lib\site-packages\resolvelib\resolvers.py", line 426, in resolve
    name = min(unsatisfied_names, key=self._get_preference)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Scoop\apps\pdm\2.12.3\venv\Lib\site-packages\resolvelib\resolvers.py", line 203, in _get_preference
    return self._p.get_preference(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Scoop\apps\pdm\2.12.3\venv\Lib\site-packages\pdm\resolver\providers.py", line 139, in get_preference
    deps = self.get_dependencies(candidate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Scoop\apps\pdm\2.12.3\venv\Lib\site-packages\pdm\resolver\providers.py", line 278, in get_dependencies
    deps, requires_python, _ = self.repository.get_dependencies(candidate)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Scoop\apps\pdm\2.12.3\venv\Lib\site-packages\pdm\models\repositories.py", line 89, in get_dependencies
    requirements, requires_python, summary = getter(candidate)
                                             ^^^^^^^^^^^^^^^^^
  File "D:\Scoop\apps\pdm\2.12.3\venv\Lib\site-packages\pdm\models\repositories.py", line 47, in wrapper
    result = func(self, candidate)
             ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Scoop\apps\pdm\2.12.3\venv\Lib\site-packages\pdm\models\repositories.py", line 269, in _get_dependencies_from_metadata
    deps = prepared.get_dependencies_from_metadata()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Scoop\apps\pdm\2.12.3\venv\Lib\site-packages\pdm\models\candidates.py", line 618, in get_dependencies_from_metadata
    return filter_requirements_with_extras(self.metadata.requires or [], extras)
                                           ^^^^^^^^^^^^^
  File "D:\Scoop\apps\pdm\2.12.3\venv\Lib\site-packages\pdm\models\candidates.py", line 605, in metadata
    result = self.prepare_metadata()
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Scoop\apps\pdm\2.12.3\venv\Lib\site-packages\pdm\models\candidates.py", line 500, in prepare_metadata
    self._unpack(validate_hashes=False)
  File "D:\Scoop\apps\pdm\2.12.3\venv\Lib\site-packages\pdm\models\candidates.py", line 472, in _unpack
    result = finder.download_and_unpack(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Scoop\apps\pdm\2.12.3\venv\Lib\site-packages\unearth\finder.py", line 413, in download_and_unpack
    file = unpack_link(
           ^^^^^^^^^^^^
  File "D:\Scoop\apps\pdm\2.12.3\venv\Lib\site-packages\unearth\preparer.py", line 344, in unpack_link
    for chunk in iter_with_callback(
  File "D:\Scoop\apps\pdm\2.12.3\venv\Lib\site-packages\unearth\utils.py", line 266, in iter_with_callback
    for item in iterable:
  File "D:\Scoop\apps\pdm\2.12.3\venv\Lib\site-packages\requests\models.py", line 822, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

## Expected behavior

Successfully installed these packages.

I can download these packages through the browser, so there shouldn't be any issues with my network environment.

Furthermore, I noticed that when I try to download the latest version of PyTorch using pip as provided on the PyTorch official website, I encounter issues with finding a suitable candidate version. However, I have no issues downloading it using the conda version command.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:

PDM version:
  2.12.3
Python Interpreter:
  C:\Users\lingkerio\OneDrive\桌面\Python\.venv\Scripts\python.exe (3.12)
Project Root:
  C:/Users/lingkerio/OneDrive/桌面/Python
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.12.1",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "11",
  "platform_system": "Windows",
  "platform_version": "10.0.22631",
  "python_full_version": "3.12.1",
  "platform_python_implementation": "CPython",
  "python_version": "3.12",
  "sys_platform": "win32"
}

```

**Comment by somata-cn** [comment]
你可以使用`pdm config pypi.url "https://test.pypi.org/simple"`命令，把默认源换到国内镜像站点。

e.g. `pdm config pypi.url https://pypi.tuna.tsinghua.edu.cn/simple`这个命令，可以把默认镜像切换到清华大学的开源镜像站点。

**Comment by lingkerio** [comment]
> 我认为这并不是软件BUG，只是国内访问外网并不稳定。
> 
> 你可以使用`pdm config pypi.url "https://test.pypi.org/simple"`命令，把默认源换到国内镜像站点。
> 
> e.g. `pdm config pypi.url https://pypi.tuna.tsinghua.edu.cn/simple`这个命令，可以把默认镜像切换到清华大学的开源镜像站点。

换了清华源确实没问题了，主要是安装其他包都没什么问题，也在想着镜像源更新包版本会不会不及时就一直没想过换源（毕竟也不是做项目就是平时学习用）

**Comment by somata-cn** [comment]
> 换了清华源确实没问题了，主要是安装其他包都没什么问题，也在想着镜像源更新包版本会不会不及时就一直没想过换源（毕竟也不是做项目就是平时学习用）

@lingkerio 清华大学的镜像好像会过滤nightly这类预发布版本（具体过滤哪些没有验证过），剩下的每天都会同步好几次，如果只是平时学习使用完全够了。你可以在 https://mirrors.tuna.tsinghua.edu.cn/status/ 这个链接里看到镜像站 pypi 上次的同步时间(直接搜索关键词 pypi)，以及同步成功等信息。

**Comment by lingkerio** [comment]
> > 换了清华源确实没问题了，主要是安装其他包都没什么问题，也在想着镜像源更新包版本会不会不及时就一直没想过换源（毕竟也不是做项目就是平时学习用）
> 
> @lingkerio 清华大学的镜像好像会过滤nightly这类预发布版本（具体过滤哪些没有验证过），剩下的每天都会同步好几次，如果只是平时学习使用完全够了。你可以在 https://mirrors.tuna.tsinghua.edu.cn/status/ 这个链接里看到镜像站 pypi 上次的同步时间(直接搜索关键词 pypi)，以及同步成功等信息。

好的，非常感谢！

**Comment by lingkerio** [comment]
我安装的是torch2.2.1（之前安装了2.2.0 ，用pdm update更新了）
![图片](https://github.com/pdm-project/pdm/assets/112792583/a329e2e7-c22a-40b6-a937-453cc1617400)
但是当我运行python查看却发现torch版本还是2.2.0
![图片](https://github.com/pdm-project/pdm/assets/112792583/69fde641-b2f5-4f53-9417-b6301c9924d2)
而且安装的还是cpu版本（我是用pdm add torch torchaudio torchvision命令安装的），我又该如何安装GPU版本呢？

**Comment by zrr1999** [comment]
> 我安装的是torch2.2.1（之前安装了2.2.0 ，用pdm update更新了） ![图片](https://private-user-images.githubusercontent.com/112792583/307784703-a329e2e7-c22a-40b6-a937-453cc1617400.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNTgyMTAsIm5iZiI6MTcxMjA1NzkxMCwicGF0aCI6Ii8xMTI3OTI1ODMvMzA3Nzg0NzAzLWEzMjllMmU3LWMyMmEtNDBiNi1hOTM3LTQ1M2NjMTYxNzQwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMlQxMTM4MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNWYwZmI4MjUwZTc4NGEzYTE3NDk0ODQ2N2VlYTdhNTdkZjhmNTBlYWM0MDg2ZmUyY2JiODBiNDViMTJmNGE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F-ljuq9P8pK4if_ecSnsjxPMNFVtgPa54xVwy0RRj-M) 但是当我运行python查看却发现torch版本还是2.2.0 ![图片](https://private-user-images.githubusercontent.com/112792583/307784366-69fde641-b2f5-4f53-9417-b6301c9924d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNTgyMTAsIm5iZiI6MTcxMjA1NzkxMCwicGF0aCI6Ii8xMTI3OTI1ODMvMzA3Nzg0MzY2LTY5ZmRlNjQxLWIyZjUtNGY1My05NDE3LWI2MzAxYzk5MjRkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMlQxMTM4MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MjRkZWNmZjRjMmIyNGUxOGQzNDU0NWI4NTdmMGRlNmFiODNjZmI3MjMyNjAzYTE1NTVhODE5YTc2MTk3YWNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GIdVD2WmS3Q082MEuzy7ti3PORheQLbNkxUrR__5xto) 而且安装的还是cpu版本（我是用pdm add torch torchaudio torchvision命令安装的），我又该如何安装GPU版本呢？

看下这个
https://github.com/pdm-project/pdm/issues/1645
https://github.com/pdm-project/pdm/pull/2323/files

**Comment by zrr1999** [comment]
pytorch应该只有cuda121版本上传到pypi了
