### ISSUE TITLE
Resolving dependency is very very slow

### ISSUE THREAD

**Issue by fancyerii** [pdm-project/pdm#2664]
It takes very long time to resolving dependency.  

```
$ ps -o etime= -p 156826
      18:01
```
It still runs now(when I am writing).
 
pyproject.toml:

```
[project] 
name = "paddlespeechserver"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "lili", email = "fancyerii@gmail.com"},
]
dependencies = [
    "paddlepaddle-gpu==2.4.2.post117",
    "pytest-runner>=6.0.1",
    "setuptools>=69.1.1",
    "paddlespeech>=1.4.1",
    "numpy<=1.23.5",
    "paddlespeech-ctcdecoders>=0.2.1",
    "opencc==1.1.6",
    "pip>=24.0",
]
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true

[[tool.pdm.source]]
type = "find_links"
url = "https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html"
name = "paddlepaddle"

```

**Comment by fancyerii** [comment]
I ran a slightly different version. it ran for 02:52:06 and still running!
I use ctrl+c to stop it. the calling stack is :

```
$ pdm install -G cpu
WARNING: Lockfile does not exist
Updating the lock file...
Traceback (most recent call last):
  File "/home/lili/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/lili/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/core.py", line 288, in main
    return Core().main(args or sys.argv[1:])
  File "/home/lili/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/core.py", line 203, in main
    self.handle(project, options)
  File "/home/lili/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/core.py", line 157, in handle
    command.handle(project, options)
  File "/home/lili/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/cli/commands/install.py", line 92, in handle
    actions.do_lock(
  File "/home/lili/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/cli/actions.py", line 102, in do_lock
    mapping, dependencies = resolve(
  File "/home/lili/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/resolver/core.py", line 39, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "/home/lili/.local/share/pdm/venv/lib/python3.9/site-packages/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/lili/.local/share/pdm/venv/lib/python3.9/site-packages/resolvelib/resolvers.py", line 427, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/home/lili/.local/share/pdm/venv/lib/python3.9/site-packages/resolvelib/resolvers.py", line 239, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "/home/lili/.local/share/pdm/venv/lib/python3.9/site-packages/resolvelib/resolvers.py", line 230, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "/home/lili/.local/share/pdm/venv/lib/python3.9/site-packages/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "/home/lili/.local/share/pdm/venv/lib/python3.9/site-packages/resolvelib/structs.py", line 127, in __bool__
    next(iter(self))
  File "/home/lili/.local/share/pdm/venv/lib/python3.9/site-packages/resolvelib/structs.py", line 136, in __iter__
    self._factory() if self._iterable is None else self._iterable
  File "/home/lili/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/resolver/providers.py", line 226, in matches_gen
    candidates = self._find_candidates(reqs[0])
  File "/home/lili/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/resolver/providers.py", line 196, in _find_candidates
    return self.repository.find_candidates(
  File "/home/lili/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/models/repositories.py", line 174, in find_candidates
    cans = LazySequence(self._find_candidates(requirement, minimal_version=minimal_version))
  File "/home/lili/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/models/repositories.py", line 437, in _find_candidates
    for c in finder.find_all_packages(requirement.project_name, allow_yanked=requirement.is_pinned)
  File "/home/lili/.local/share/pdm/venv/lib/python3.9/site-packages/unearth/finder.py", line 287, in find_all_packages
    self._find_packages(package_name, allow_yanked), hashes=hashes or {}
  File "/home/lili/.local/share/pdm/venv/lib/python3.9/site-packages/unearth/finder.py", line 267, in _find_packages
    return sorted(all_packages, key=self._sort_key, reverse=True)
  File "/home/lili/.local/share/pdm/venv/lib/python3.9/site-packages/unearth/evaluator.py", line 193, in evaluate_link
    self.format_control.check_format(link, self.package_name)
  File "/home/lili/.local/share/pdm/venv/lib/python3.9/site-packages/unearth/evaluator.py", line 124, in check_format
    if link.is_wheel and "binary" not in allowed_formats:
  File "/home/lili/.local/share/pdm/venv/lib/python3.9/site-packages/unearth/link.py", line 116, in is_wheel
    return self.filename.endswith(".whl")
  File "/home/lili/.local/share/pdm/venv/lib/python3.9/site-packages/unearth/link.py", line 103, in filename
    path = self.parsed.path.rsplit("@", 1)[0]
  File "/usr/local/lib/python3.9/functools.py", line 993, in __get__
    val = self.func(instance)
  File "/home/lili/.local/share/pdm/venv/lib/python3.9/site-packages/unearth/link.py", line 72, in parsed
    return urlparse(self.normalized)
  File "/usr/local/lib/python3.9/urllib/parse.py", line 407, in urlparse
    result = ParseResult(scheme, netloc, url, params, query, fragment)
  File "<string>", line 1, in <lambda>
KeyboardInterrupt
```

my project.toml
```
[project]
name = "paddlespeechserver"
version = "0.1.0"
description = "Default template for PDM package"
authors = [ 
    {name = "lili", email = "fancyerii@gmail.com"},
]
dependencies = [ 
    "pytest-runner>=6.0.1",
    "setuptools>=69.1.1",
    "paddlespeech>=1.4.1",
    "numpy<=1.23.5",
    "paddlespeech-ctcdecoders>=0.2.1",
    "opencc<=1.1.6",
    "pip>=24.0",
]



requires-python = ">=3.9.0"
readme = "README.md"
license = {text = "MIT"}


[project.optional-dependencies]
gpu_cuda102 = ["paddlepaddle-gpu==2.4.2"]
gpu_cuda112 = ["paddlepaddle-gpu==2.4.2.post112"]
gpu_cuda117 = ["paddlepaddle-gpu==2.4.2.post117"]
gpu_cuda116 = ["paddlepaddle-gpu==2.4.2.post116"]
cpu = ["paddlepaddle==2.4.2"]

[tool.pdm]
distribution = false

[[tool.pdm.source]]
type = "find_links"
url = "https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html"
name = "paddlepaddle-gpu"

[[tool.pdm.source]]
type = "find_links"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
name = "paddlepaddle-cpu"

```

**Comment by frostming** [comment]
On my machine it resolves successfully in around 6 minutes

**Comment by fancyerii** [comment]
> On my machine it resolves successfully in around 6 minutes, but tested on the main branch.

Could you please try this one?  run with "pdm install -G cpu"

```
[project]
name = "paddlespeechserver"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "lili", email = "fancyerii@gmail.com"},
]
dependencies = [
    "pytest-runner>=6.0.1",
    "setuptools>=69.1.1",
    "paddlespeech>=1.4.1",
    "numpy<=1.23.5",
    "paddlespeech-ctcdecoders>=0.2.1",
    "opencc<=1.1.6",
    "pip>=24.0",
]



requires-python = ">=3.9.0"
readme = "README.md"
license = {text = "MIT"}


[project.optional-dependencies]
gpu_cuda102 = ["paddlepaddle-gpu==2.4.2"]
gpu_cuda112 = ["paddlepaddle-gpu==2.4.2.post112"]
gpu_cuda117 = ["paddlepaddle-gpu==2.4.2.post117"]
gpu_cuda116 = ["paddlepaddle-gpu==2.4.2.post116"]
cpu = ["paddlepaddle==2.4.2"]

[tool.pdm]
distribution = false

[[tool.pdm.source]]
type = "find_links"
url = "https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html"
name = "paddlepaddle-gpu"
```
I have switch default pypi.url to tsinghua(because I am in China) but still very slow.

```
$ pdm config
....

Project configuration (/home/lili/codes/paddlespeechserver/pdm.toml):
pypi.url = https://pypi.tuna.tsinghua.edu.cn/simple
```

**Comment by fancyerii** [comment]
It's the network problem.
