### ISSUE TITLE
pdm always crashes on a poetry project with names including comma

### ISSUE THREAD

**Issue by alsrbbk** [pdm-project/pdm#2665]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

On my test project with pyproject.toml of which name contains any comma(,), e.g.:

```toml
[tool.poetry]
name = "test"
version = "1.0.0"
descrption = "test project"
authors = ["Min-Gyu, Kim <alsrbbk@gmail.com>"]

[tool.poetry.dependencies]
python = "~3.11.6"
```

pdm command-line execution always crashes.

## Actual behavior

I got a main error when executing any CLI commands.

It seems to be due to a regex, unmatching commas.

Example as follows:

```sh
$ pdm
Traceback (most recent call last):
  File "/home/alsrbbk/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/alsrbbk/.local/share/pdm/venv/lib/python3.11/site-packages/pdm/core.py", line 288, in main
    return Core().main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alsrbbk/.local/share/pdm/venv/lib/python3.11/site-packages/pdm/core.py", line 181, in main
    args = self._get_cli_args(args, obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alsrbbk/.local/share/pdm/venv/lib/python3.11/site-packages/pdm/core.py", line 163, in _get_cli_args
    config = project.pyproject.settings.get("options", {})
             ^^^^^^^^^^^^^^^^^
  File "/home/alsrbbk/.pyenv/versions/3.11.6/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/alsrbbk/.local/share/pdm/venv/lib/python3.11/site-packages/pdm/project/core.py", line 112, in pyproject
    return PyProject(self.root / self.PYPROJECT_FILENAME, ui=self.core.ui)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alsrbbk/.local/share/pdm/venv/lib/python3.11/site-packages/pdm/project/toml_file.py", line 18, in __init__
    self._data = self.read()
                 ^^^^^^^^^^^
  File "/home/alsrbbk/.local/share/pdm/venv/lib/python3.11/site-packages/pdm/project/project_file.py", line 33, in read
    metadata, settings = converter.convert(None, self._path, None)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alsrbbk/.local/share/pdm/venv/lib/python3.11/site-packages/pdm/formats/poetry.py", line 213, in convert
    return converter.convert()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/alsrbbk/.local/share/pdm/venv/lib/python3.11/site-packages/pdm/formats/base.py", line 85, in convert
    raise MetaConvertError(errors, data=self._data, settings=self.settings)
pdm.formats.base.MetaConvertError: 
authors: 'NoneType' object has no attribute 'groupdict'
```

## Expected behavior

`$ pdm` execution succeeded and show a help page.

## Environment Information

(cannot launch CLI)

**Comment by frostming** [comment]
According to the [specification](https://arc.net/l/quote/gvitpksa) the name can't contain commas, if I interpret it correctly

**Comment by pawamoy** [comment]
Possibly related: https://discuss.python.org/t/clarification-regarding-the-authors-maintainers-field-in-pyproject-toml/33731

**Comment by alsrbbk** [comment]
An email name needs to be non-comma according to the spec., so I have to change my name.

As @pawamoy said, PDM should not be crashed on a poetry project even if it contains an invalid name before any convertion. Maybe it can warn us to correct the name format. I had to spend a bit of time to figure out the reason.
