### ISSUE TITLE
Pdm v2.13.x fails to install dependencies with `msgpack.exceptions.ExtraData: unpack(b) received extra data.` error

### ISSUE THREAD

**Issue by woopla** [pdm-project/pdm#2745]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Since we updated our infra from v1.12.4 to 2.13.0 (and then 2.13.1 as a trial), I cannot run `pdm install` on this simple `pyproject.toml` file:

```toml
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "John Smith", email = "john.smith@company.com"},
]
dependencies = [
    "sqlalchemy>=2.0.25",
    "pymysql>=1.1.0",
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "Internal"}
```

I get the following stacktrace:
```python
> ~/.local/bin/pdm install -v
WARNING: Lockfile is generated on an older version of PDM
STATUS: Resolving packages from lockfile...
STATUS: Fetching hashes for resolved packages...
Synchronizing working set with resolved packages: 4 to add, 0 to update, 0 to remove

  ✖ Install greenlet 3.0.3 failed
  ✖ Install sqlalchemy 2.0.25 failed
pdm.termui: Error occurs: 
Traceback (most recent call last):
  File "/usr/mgc/peteoss/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/calgit/.local/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 282, in install_candidate
    self.manager.install(can)
  File "/home/calgit/.local/lib/python3.8/site-packages/pdm/installers/manager.py", line 29, in install
    dist_info = install_package(prepared.build(), self.environment, prepared.direct_url(), self.use_install_cache)
  File "/home/calgit/.local/lib/python3.8/site-packages/pdm/models/candidates.py", line 404, in build
    self.obtain(allow_all=False)
  File "/home/calgit/.local/lib/python3.8/site-packages/pdm/models/candidates.py", line 443, in obtain
    self.link = _find_best_match_link(
  File "/home/calgit/.local/lib/python3.8/site-packages/pdm/models/candidates.py", line 107, in _find_best_match_link
    found = attempt_to_find()
  File "/home/calgit/.local/lib/python3.8/site-packages/pdm/models/candidates.py", line 98, in attempt_to_find
    best = finder.find_best_match(req.as_line(), hashes=hashes).best
  File "/home/calgit/.local/lib/python3.8/site-packages/unearth/finder.py", line 391, in find_best_match
    best_match = next(iter(applicable_candidates), None)
  File "/home/calgit/.local/lib/python3.8/site-packages/unearth/finder.py", line 324, in _find_packages_from_requirement
    yield from self._find_packages(requirement.name, allow_yanked)
  File "/home/calgit/.local/lib/python3.8/site-packages/unearth/finder.py", line 290, in _find_packages
    return sorted(all_packages, key=self._sort_key, reverse=True)
  File "/home/calgit/.local/lib/python3.8/site-packages/unearth/collector.py", line 178, in collect_links_from_location
    yield from _collect_links_from_index(session, location)
  File "/home/calgit/.local/lib/python3.8/site-packages/unearth/collector.py", line 198, in _collect_links_from_index
    page = fetch_page(session, location)
  File "/home/calgit/.local/lib/python3.8/site-packages/unearth/collector.py", line 185, in fetch_page
    resp = _get_html_response(session, location)
  File "/home/calgit/.local/lib/python3.8/site-packages/unearth/collector.py", line 220, in _get_html_response
    resp = session.get(
  File "/home/calgit/.local/lib/python3.8/site-packages/httpx/_client.py", line 1054, in get
    return self.request(
  File "/home/calgit/.local/lib/python3.8/site-packages/httpx/_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/calgit/.local/lib/python3.8/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
  File "/home/calgit/.local/lib/python3.8/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/home/calgit/.local/lib/python3.8/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/home/calgit/.local/lib/python3.8/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
  File "/home/calgit/.local/lib/python3.8/site-packages/hishel/_sync/_transports.py", line 112, in handle_request
    stored_data = self._storage.retrieve(key)
  File "/home/calgit/.local/lib/python3.8/site-packages/hishel/_sync/_storages.py", line 139, in retrieve
    return self._serializer.loads(read_data)
  File "/home/calgit/.local/lib/python3.8/site-packages/pdm/models/session.py", line 83, in loads
    full_dict = cast("dict[str, Any]", msgpack.loads(data, raw=False))
  File "msgpack/_unpacker.pyx", line 201, in msgpack._cmsgpack.unpackb
msgpack.exceptions.ExtraData: unpack(b) received extra data.
pdm.termui: Error occurs: 
Traceback (most recent call last):
  File "/usr/mgc/peteoss/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/calgit/.local/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 282, in install_candidate
    self.manager.install(can)
  File "/home/calgit/.local/lib/python3.8/site-packages/pdm/installers/manager.py", line 29, in install
    dist_info = install_package(prepared.build(), self.environment, prepared.direct_url(), self.use_install_cache)
  File "/home/calgit/.local/lib/python3.8/site-packages/pdm/models/candidates.py", line 404, in build
    self.obtain(allow_all=False)
  File "/home/calgit/.local/lib/python3.8/site-packages/pdm/models/candidates.py", line 443, in obtain
    self.link = _find_best_match_link(
  File "/home/calgit/.local/lib/python3.8/site-packages/pdm/models/candidates.py", line 107, in _find_best_match_link
    found = attempt_to_find()
  File "/home/calgit/.local/lib/python3.8/site-packages/pdm/models/candidates.py", line 98, in attempt_to_find
    best = finder.find_best_match(req.as_line(), hashes=hashes).best
  File "/home/calgit/.local/lib/python3.8/site-packages/unearth/finder.py", line 391, in find_best_match
    best_match = next(iter(applicable_candidates), None)
  File "/home/calgit/.local/lib/python3.8/site-packages/unearth/finder.py", line 324, in _find_packages_from_requirement
    yield from self._find_packages(requirement.name, allow_yanked)
  File "/home/calgit/.local/lib/python3.8/site-packages/unearth/finder.py", line 290, in _find_packages
    return sorted(all_packages, key=self._sort_key, reverse=True)
  File "/home/calgit/.local/lib/python3.8/site-packages/unearth/collector.py", line 178, in collect_links_from_location
    yield from _collect_links_from_index(session, location)
  File "/home/calgit/.local/lib/python3.8/site-packages/unearth/collector.py", line 198, in _collect_links_from_index
    page = fetch_page(session, location)
  File "/home/calgit/.local/lib/python3.8/site-packages/unearth/collector.py", line 185, in fetch_page
    resp = _get_html_response(session, location)
  File "/home/calgit/.local/lib/python3.8/site-packages/unearth/collector.py", line 220, in _get_html_response
    resp = session.get(
  File "/home/calgit/.local/lib/python3.8/site-packages/httpx/_client.py", line 1054, in get
    return self.request(
  File "/home/calgit/.local/lib/python3.8/site-packages/httpx/_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/calgit/.local/lib/python3.8/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
  File "/home/calgit/.local/lib/python3.8/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/home/calgit/.local/lib/python3.8/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/home/calgit/.local/lib/python3.8/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
  File "/home/calgit/.local/lib/python3.8/site-packages/hishel/_sync/_transports.py", line 112, in handle_request
    stored_data = self._storage.retrieve(key)
  File "/home/calgit/.local/lib/python3.8/site-packages/hishel/_sync/_storages.py", line 139, in retrieve
    return self._serializer.loads(read_data)
  File "/home/calgit/.local/lib/python3.8/site-packages/pdm/models/session.py", line 83, in loads
    full_dict = cast("dict[str, Any]", msgpack.loads(data, raw=False))
  File "msgpack/_unpacker.pyx", line 201, in msgpack._cmsgpack.unpackb
msgpack.exceptions.ExtraData: unpack(b) received extra data.
  ✔ Install typing-extensions 4.9.0 successful
  ✔ Install pymysql 1.1.0 successful
Retry failed jobs
  ✖ Install greenlet 3.0.3 failed
pdm.termui: Error occurs: 
Traceback (most recent call last):
  File "/usr/mgc/peteoss/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/calgit/.local/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 282, in install_candidate
    self.manager.install(can)
  File "/home/calgit/.local/lib/python3.8/site-packages/pdm/installers/manager.py", line 29, in install
    dist_info = install_package(prepared.build(), self.environment, prepared.direct_url(), self.use_install_cache)
  File "/home/calgit/.local/lib/python3.8/site-packages/pdm/models/candidates.py", line 404, in build
    self.obtain(allow_all=False)
  File "/home/calgit/.local/lib/python3.8/site-packages/pdm/models/candidates.py", line 443, in obtain
    self.link = _find_best_match_link(
  File "/home/calgit/.local/lib/python3.8/site-packages/pdm/models/candidates.py", line 107, in _find_best_match_link
    found = attempt_to_find()
  File "/home/calgit/.local/lib/python3.8/site-packages/pdm/models/candidates.py", line 98, in attempt_to_find
    best = finder.find_best_match(req.as_line(), hashes=hashes).best
  File "/home/calgit/.local/lib/python3.8/site-packages/unearth/finder.py", line 391, in find_best_match
    best_match = next(iter(applicable_candidates), None)
  File "/home/calgit/.local/lib/python3.8/site-packages/unearth/finder.py", line 324, in _find_packages_from_requirement
    yield from self._find_packages(requirement.name, allow_yanked)
  File "/home/calgit/.local/lib/python3.8/site-packages/unearth/finder.py", line 290, in _find_packages
    return sorted(all_packages, key=self._sort_key, reverse=True)
  File "/home/calgit/.local/lib/python3.8/site-packages/unearth/collector.py", line 178, in collect_links_from_location
    yield from _collect_links_from_index(session, location)
  File "/home/calgit/.local/lib/python3.8/site-packages/unearth/collector.py", line 198, in _collect_links_from_index
    page = fetch_page(session, location)
  File "/home/calgit/.local/lib/python3.8/site-packages/unearth/collector.py", line 185, in fetch_page
    resp = _get_html_response(session, location)
  File "/home/calgit/.local/lib/python3.8/site-packages/unearth/collector.py", line 220, in _get_html_response
    resp = session.get(
  File "/home/calgit/.local/lib/python3.8/site-packages/httpx/_client.py", line 1054, in get
    return self.request(
  File "/home/calgit/.local/lib/python3.8/site-packages/httpx/_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/calgit/.local/lib/python3.8/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
  File "/home/calgit/.local/lib/python3.8/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/home/calgit/.local/lib/python3.8/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/home/calgit/.local/lib/python3.8/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
  File "/home/calgit/.local/lib/python3.8/site-packages/hishel/_sync/_transports.py", line 112, in handle_request
    stored_data = self._storage.retrieve(key)
  File "/home/calgit/.local/lib/python3.8/site-packages/hishel/_sync/_storages.py", line 139, in retrieve
    return self._serializer.loads(read_data)
  File "/home/calgit/.local/lib/python3.8/site-packages/pdm/models/session.py", line 83, in loads
    full_dict = cast("dict[str, Any]", msgpack.loads(data, raw=False))
  File "msgpack/_unpacker.pyx", line 201, in msgpack._cmsgpack.unpackb
msgpack.exceptions.ExtraData: unpack(b) received extra data.
  ✖ Install sqlalchemy 2.0.25 failed
pdm.termui: Error occurs: 
Traceback (most recent call last):
  File "/usr/mgc/peteoss/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/calgit/.local/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 282, in install_candidate
    self.manager.install(can)
  File "/home/calgit/.local/lib/python3.8/site-packages/pdm/installers/manager.py", line 29, in install
    dist_info = install_package(prepared.build(), self.environment, prepared.direct_url(), self.use_install_cache)
  File "/home/calgit/.local/lib/python3.8/site-packages/pdm/models/candidates.py", line 404, in build
    self.obtain(allow_all=False)
  File "/home/calgit/.local/lib/python3.8/site-packages/pdm/models/candidates.py", line 443, in obtain
    self.link = _find_best_match_link(
  File "/home/calgit/.local/lib/python3.8/site-packages/pdm/models/candidates.py", line 107, in _find_best_match_link
    found = attempt_to_find()
  File "/home/calgit/.local/lib/python3.8/site-packages/pdm/models/candidates.py", line 98, in attempt_to_find
    best = finder.find_best_match(req.as_line(), hashes=hashes).best
  File "/home/calgit/.local/lib/python3.8/site-packages/unearth/finder.py", line 391, in find_best_match
    best_match = next(iter(applicable_candidates), None)
  File "/home/calgit/.local/lib/python3.8/site-packages/unearth/finder.py", line 324, in _find_packages_from_requirement
    yield from self._find_packages(requirement.name, allow_yanked)
  File "/home/calgit/.local/lib/python3.8/site-packages/unearth/finder.py", line 290, in _find_packages
    return sorted(all_packages, key=self._sort_key, reverse=True)
  File "/home/calgit/.local/lib/python3.8/site-packages/unearth/collector.py", line 178, in collect_links_from_location
    yield from _collect_links_from_index(session, location)
  File "/home/calgit/.local/lib/python3.8/site-packages/unearth/collector.py", line 198, in _collect_links_from_index
    page = fetch_page(session, location)
  File "/home/calgit/.local/lib/python3.8/site-packages/unearth/collector.py", line 185, in fetch_page
    resp = _get_html_response(session, location)
  File "/home/calgit/.local/lib/python3.8/site-packages/unearth/collector.py", line 220, in _get_html_response
    resp = session.get(
  File "/home/calgit/.local/lib/python3.8/site-packages/httpx/_client.py", line 1054, in get
    return self.request(
  File "/home/calgit/.local/lib/python3.8/site-packages/httpx/_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/calgit/.local/lib/python3.8/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
  File "/home/calgit/.local/lib/python3.8/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/home/calgit/.local/lib/python3.8/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/home/calgit/.local/lib/python3.8/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
  File "/home/calgit/.local/lib/python3.8/site-packages/hishel/_sync/_transports.py", line 112, in handle_request
    stored_data = self._storage.retrieve(key)
  File "/home/calgit/.local/lib/python3.8/site-packages/hishel/_sync/_storages.py", line 139, in retrieve
    return self._serializer.loads(read_data)
  File "/home/calgit/.local/lib/python3.8/site-packages/pdm/models/session.py", line 83, in loads
    full_dict = cast("dict[str, Any]", msgpack.loads(data, raw=False))
  File "msgpack/_unpacker.pyx", line 201, in msgpack._cmsgpack.unpackb
msgpack.exceptions.ExtraData: unpack(b) received extra data.
Traceback (most recent call last):
  File "/home/calgit/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/calgit/.local/lib/python3.8/site-packages/pdm/core.py", line 341, in main
    return core.main(args or sys.argv[1:])
  File "/home/calgit/.local/lib/python3.8/site-packages/pdm/core.py", line 259, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/home/calgit/.local/lib/python3.8/site-packages/pdm/core.py", line 254, in main
    self.handle(project, options)
  File "/home/calgit/.local/lib/python3.8/site-packages/pdm/core.py", line 209, in handle
    command.handle(project, options)
  File "/home/calgit/.local/lib/python3.8/site-packages/pdm/cli/commands/install.py", line 100, in handle
    actions.do_sync(
  File "/home/calgit/.local/lib/python3.8/site-packages/pdm/cli/actions.py", line 238, in do_sync
    synchronizer.synchronize()
  File "/home/calgit/.local/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 450, in synchronize
    raise InstallationError("Some package operations are not complete yet")
pdm.exceptions.InstallationError: Some package operations are not complete yet

```

## Actual behavior

The packages from `pyproject.toml` are not installed.

## Expected behavior

The packages are installed.

** NOTE **: reverting back to 2.12.4 causes the problem to go away.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.13.1
Python Interpreter:
  /path/to/project/.venv/bin/python (3.8)
Project Root:
  /path/to/project
Local Packages:
 {
  "implementation_name": "cpython",
  "implementation_version": "3.8.7",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "4.18.0-372.32.1.el8_6.x86_64",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Thu Oct 27 15:18:36 UTC 2022",
  "python_full_version": "3.8.7",
  "platform_python_implementation": "CPython",
  "python_version": "3.8",
  "sys_platform": "linux"
}

```

**Comment by frostming** [comment]
Corrupted cache, clean the caches with `pdm cache clear` and try again?

**Comment by woopla** [comment]
Thanks, that did work after both `pdm cache clear` and `mv ~/.cache/pdm/packages ~/.cache/pdm/packages.bak`. Without moving the `packages` dir aside I was getting:
```python
FileNotFoundError: [Errno 2] No such file or directory: 
'/home/user/.cache/pdm/packages/f2/a1/59/11/1a0f58fb034c93eeba211b4141137ec4b0a6e75789ab7a3ef3c7e7e3/SQLAlchemy-2.0.25-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.cache/SQLAlchemy-2.0.25.dist-info/WHEEL'
```

Feel free to close if you think it's a one-off, but maybe `pdm cache clear` needs to be more thorough?

**Comment by NorthernScott** [comment]
I am experiencing this same issue. pdm cache clear has not resolved it. I am on windows and don't have the same cache files as OP.
