### ISSUE TITLE
[Exception]: You need either charset_normalizer or chardet installed

### ISSUE THREAD

**Issue by menzenski** [pdm-project/pdm#2768]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

A few days ago all PDM commands began failing for me with this error:

```shell
$ pdm install
[Exception]: You need either charset_normalizer or chardet installed
WARNING: Add '-v' to see the detailed traceback
```

I have PDM installed via Homebrew, and I did upgrade Homebrew packages at about that time, so I believe that may be related, but I haven't been able to figure out what's going on here.

## Actual behavior

I can run `pdm` and `pdm --version` successfully, but other commands `pdm info`, `pdm install`, `pdm add`, etc all fail with this error.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
pdm info && pdm info --env
[Exception]: You need either charset_normalizer or chardet installed
WARNING: Add '-v' to see the detailed traceback
```

I am using Pyenv to manage Python versions. I have tried several different Python versions, with no success. I have run `brew reinstall pdm` with no success.

I have installed both `chardet` and `charset_normalizers` in my active Python version:

```shell
python -m pip install charset_normalizer
python -m pip install chardet
```

But I still get the same error:

```shell
$ pdm install
[Exception]: You need either charset_normalizer or chardet installed
WARNING: Add '-v' to see the detailed traceback
```

**Comment by frostming** [comment]
What is the verbose output?

**Comment by menzenski** [comment]
```shell
$ pdm install -v
Traceback (most recent call last):
  File "/usr/local/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/Cellar/pdm/2.13.2/libexec/lib/python3.12/site-packages/pdm/core.py", line 341, in main
    return core.main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/pdm/2.13.2/libexec/lib/python3.12/site-packages/pdm/core.py", line 259, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/usr/local/Cellar/pdm/2.13.2/libexec/lib/python3.12/site-packages/pdm/core.py", line 254, in main
    self.handle(project, options)
  File "/usr/local/Cellar/pdm/2.13.2/libexec/lib/python3.12/site-packages/pdm/core.py", line 209, in handle
    command.handle(project, options)
  File "/usr/local/Cellar/pdm/2.13.2/libexec/lib/python3.12/site-packages/pdm/cli/commands/install.py", line 100, in handle
    actions.do_sync(
  File "/usr/local/Cellar/pdm/2.13.2/libexec/lib/python3.12/site-packages/pdm/cli/actions.py", line 221, in do_sync
    requirements.extend(project.get_dependencies(group).values())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/pdm/2.13.2/libexec/lib/python3.12/site-packages/pdm/project/core.py", line 335, in get_dependencies
    req = parse_requirement(line)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/pdm/2.13.2/libexec/lib/python3.12/site-packages/pdm/models/requirements.py", line 495, in parse_requirement
    r = Requirement.from_pkg_requirement(pkg_req)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/pdm/2.13.2/libexec/lib/python3.12/site-packages/pdm/models/requirements.py", line 211, in from_pkg_requirement
    from unearth import Link
  File "/usr/local/Cellar/pdm/2.13.2/libexec/lib/python3.12/site-packages/unearth/__init__.py", line 11, in <module>
    from unearth.finder import BestMatch, PackageFinder, Source
  File "/usr/local/Cellar/pdm/2.13.2/libexec/lib/python3.12/site-packages/unearth/finder.py", line 34, in <module>
    from unearth.preparer import noop_download_reporter, noop_unpack_reporter, unpack_link
  File "/usr/local/Cellar/pdm/2.13.2/libexec/lib/python3.12/site-packages/unearth/preparer.py", line 35, in <module>
    from requests import HTTPError
  File "/usr/local/lib/python3.12/site-packages/requests/__init__.py", line 105, in <module>
    check_compatibility(
  File "/usr/local/lib/python3.12/site-packages/requests/__init__.py", line 86, in check_compatibility
    raise Exception("You need either charset_normalizer or chardet installed")
Exception: You need either charset_normalizer or chardet installed
```

**Comment by menzenski** [comment]
I've fixed this just now by reinstalling the Homebrew Python with `brew reinstall python@3.12`.

It seems not to have been an issue with PDM.
