### ISSUE TITLE
extras are not respected when referred in optional dependencies

### ISSUE THREAD

**Issue by zhukovgreen** [pdm-project/pdm#2770]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

1. Create the dependency package as follows. There are two extra groups A and B.
A contains attrs 23.3, B - attrs 22.2.

```
/tmp/dependency
❯ tree -I dist -I __pycache__  
.
├── README.md
├── pyproject.toml
├── src
│   └── dependency
│       └── __init__.py
└── tests
    └── __init__.py

❯ cat pyproject.toml              
[project]
name = "dependency"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "zhukovgreen", email = "iam@zhukovgreen.pro"},
]
dependencies = []
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project.optional-dependencies]
A = [
    "attrs==23.3.0",
]
B = [
    "attrs==22.2.0",
]

[tool.pdm]
distribution = true
```
2. Build wheel by running `pdm build`

3. Create dependent project as follows

```
/tmp/dependant
❯ tree -I dist -I __pycache__   
.
├── README.md
├── pyproject.toml
├── src
│   └── dependant
│       └── __init__.py
└── tests
    └── __init__.py

4 directories, 4 files

❯ cat pyproject.toml  
[project]
name = "dependant"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "zhukovgreen", email = "iam@zhukovgreen.pro"},
]
dependencies = [
]
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}

[project.optional-dependencies]
A = [
    "dependency[A] @ file:///${PROJECT_ROOT}/../dependency/dist/dependency-0.1.0-py3-none-any.whl",
]
B = [
    "dependency[B] @ file:///${PROJECT_ROOT}/../dependency/dist/dependency-0.1.0-py3-none-any.whl",
]

[tool.pdm]
distribution = false
```

4. Build a lock file for B extra group only
```
❯ pdm lock -G B -L B.pdm.lock   
🔒 Lock successful
Changes are written to B.pdm.lock.
```

5. Build a lock file for A extra group only
```
❯ pdm lock -G A -L A.pdm.lock -v
STATUS: Resolving dependencies
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   dependency[A] @ file:///${PROJECT_ROOT}/../dependency/dist/dependency-0.1.0-py3-none-any.whl
pdm.termui:   python==3.12.*
pdm.termui:   Adding requirement dependency[A] @ file:///${PROJECT_ROOT}/../dependency/dist/dependency-0.1.0-py3-none-any.whl
pdm.termui:   Adding requirement python==3.12.*
pdm.termui: ======== Starting round 0 ========
STATUS: Resolving: new pin python==3.12.*
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
pdm.termui:   Adding requirement attrs==23.3.0(from dependency 0.1.0)
pdm.termui: Candidate rejected: dependency@file:///${PROJECT_ROOT}/../dependency/dist/dependency-0.1.0-py3-none-any.whl because it introduces a new requirement attrs==23.3.0 that conflicts with other requirements:
  
pdm.termui: Conflicts detected: 
  attrs==23.3.0 (from dependency@file:///${PROJECT_ROOT}/../dependency/dist/dependency-0.1.0-py3-none-any.whl)
🔒 Lock failed
ERROR: Unable to find a resolution for attrs
Please make sure the package name is correct.
Traceback (most recent call last):
  File "/Users/uname/.pyenv/versions/3.12.2/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/uname/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pdm/core.py", line 341, in main
    return core.main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/uname/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pdm/core.py", line 259, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/Users/uname/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pdm/core.py", line 254, in main
    self.handle(project, options)
  File "/Users/uname/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pdm/core.py", line 209, in handle
    command.handle(project, options)
  File "/Users/uname/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pdm/cli/commands/lock.py", line 92, in handle
    actions.do_lock(
  File "/Users/uname/.pyenv/versions/3.12.2/lib/python3.12/site-packages/pdm/cli/actions.py", line 125, in do_lock
    raise ResolutionImpossible("Unable to find a resolution") from None
resolvelib.resolvers.ResolutionImpossible: Unable to find a resolution
```

## Actual behavior

```
❯ pdm lock -G A -L A.pdm.lock -v
```
fails

## Expected behavior

I expect both lock files are generated.

Also tried it with `--without` parameter - same issue:
```
❯ pdm lock -G A --without B -L A.pdm.lock   
🔒 Lock failed
ERROR: Unable to find a resolution for attrs
Please make sure the package name is correct.
See /Users/azhukov/Library/Logs/pdm/pdm-lock-g1o6woe5.log for detailed debug log.
[ResolutionImpossible]: Unable to find a resolution
WARNING: Add '-v' to see the detailed traceback
```

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
❯ pdm info && pdm info --env
PDM version:
  2.13.2
Python Interpreter:
  /private/tmp/dependant/.venv/bin/python (3.12)
Project Root:
  /private/tmp/dependant
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.12.2",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "23.4.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; 
root:xnu-10063.101.17~1/RELEASE_ARM64_T6000",
  "python_full_version": "3.12.2",
  "platform_python_implementation": "CPython",
  "python_version": "3.12",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
> "attrs==23.3.0",

As of today(April 4, 2024), the latest version of `attrs` is `23.2.0`, please check it again.

**Comment by zhukovgreen** [comment]
That's sad:) I am sorry for a wrong call
