### ISSUE TITLE
"pdm init django" does not work well with Python3.8 : backports.zoneinfo is not installed

### ISSUE THREAD

**Issue by fallen** [pdm-project/pdm#2772]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

```bash
fallen@fallen-ThinkPad-X260:~/dev$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy
fallen@fallen-ThinkPad-X260:~/dev$ mkdir pdmtest
fallen@fallen-ThinkPad-X260:~/dev$ cd pdmtest
fallen@fallen-ThinkPad-X260:~/dev/pdmtest$ pdm -V
PDM, version 2.13.2
fallen@fallen-ThinkPad-X260:~/dev/pdmtest$ pdm -v init django
Creating a pyproject.toml for PDM...
Please enter the Python interpreter to use
 0. cpython@3.10 (/usr/bin/python)
 1. cpython@3.10 (/usr/bin/python3.10)
 2. pypy@3.8 (/usr/bin/pypy3.8)
 3. cpython@3.8 (/usr/bin/python3.8)
 4. cpython@2.7 (/usr/bin/python2.7)
 5. pypy@2.7 (/usr/bin/pypy)
 6. cpython@3.10 (/home/fallen/.local/share/pdm/venv/bin/python)
Please select (0): 3
Virtualenv is created successfully at /home/fallen/dev/pdmtest/.venv
Project name (pdmtest): 
Project version (0.1.0): 
Do you want to build this project for distribution(such as wheel)?
If yes, it will be installed by default when running `pdm install`. [y/n] (n): 
License(SPDX name) (MIT): 
Author name (Yann Sionneau): 
Author email (yann@sionneau.net): 
Python requires('*' to allow any) (==3.8.*): 
WARNING: Lockfile is generated on an older version of PDM
Synchronizing working set with resolved packages: 4 to add, 0 to update, 0 to remove

  ✔ Install asgiref 3.7.2 successful
  ✔ Install typing-extensions 4.6.3 successful
  ✔ Install sqlparse 0.4.4 successful
  ✔ Install django 4.2.2 successful

🎉 All complete!

Traceback (most recent call last):
  File "/home/fallen/dev/pdmtest/.venv/lib/python3.8/site-packages/django/utils/timezone.py", line 10, in <module>
    import zoneinfo
ModuleNotFoundError: No module named 'zoneinfo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 11, in main
    from django.core.management import execute_from_command_line
  File "/home/fallen/dev/pdmtest/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 19, in <module>
    from django.core.management.base import (
  File "/home/fallen/dev/pdmtest/.venv/lib/python3.8/site-packages/django/core/management/base.py", line 13, in <module>
    from django.core import checks
  File "/home/fallen/dev/pdmtest/.venv/lib/python3.8/site-packages/django/core/checks/__init__.py", line 26, in <module>
    import django.core.checks.templates  # NOQA isort:skip
  File "/home/fallen/dev/pdmtest/.venv/lib/python3.8/site-packages/django/core/checks/templates.py", line 5, in <module>
    from django.template.backends.django import get_template_tag_modules
  File "/home/fallen/dev/pdmtest/.venv/lib/python3.8/site-packages/django/template/__init__.py", line 44, in <module>
    from .engine import Engine
  File "/home/fallen/dev/pdmtest/.venv/lib/python3.8/site-packages/django/template/engine.py", line 7, in <module>
    from .base import Template
  File "/home/fallen/dev/pdmtest/.venv/lib/python3.8/site-packages/django/template/base.py", line 59, in <module>
    from django.utils.formats import localize
  File "/home/fallen/dev/pdmtest/.venv/lib/python3.8/site-packages/django/utils/formats.py", line 9, in <module>
    from django.utils import dateformat, numberformat
  File "/home/fallen/dev/pdmtest/.venv/lib/python3.8/site-packages/django/utils/dateformat.py", line 26, in <module>
    from django.utils.timezone import (
  File "/home/fallen/dev/pdmtest/.venv/lib/python3.8/site-packages/django/utils/timezone.py", line 12, in <module>
    from backports import zoneinfo
ModuleNotFoundError: No module named 'backports'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

```

## Actual behavior

It installs Django and its dependencies except "backports.zoneinfo" : https://github.com/django/django/blob/stable/4.2.x/setup.cfg#L44

## Expected behavior

I would expect pdm to install backports.zoneinfo since I told pdm to use Python 3.8
If I manually type `pdm add backports.zoneinfo` then everythings works fine:

```bash
fallen@fallen-ThinkPad-X260:~/dev/pdmtest$ pdm -v add backports.zoneinfo
Adding packages to default dependencies: backports-zoneinfo
🔒 Lock successful
Changes are written to pyproject.toml.
Synchronizing working set with resolved packages: 1 to add, 0 to update, 0 to remove

  ✔ Install backports-zoneinfo 0.2.1 successful

🎉 All complete!

fallen@fallen-ThinkPad-X260:~/dev/pdmtest$ pdm run start
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
April 04, 2024 - 21:10:47
Django version 4.2.2, using settings 'pdmtest.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

```

## Environment Information

```bash
fallen@fallen-ThinkPad-X260:~/dev/pdmtest$ pdm info && pdm info --env
PDM version:
  2.13.2
Python Interpreter:
  /home/fallen/dev/pdmtest/.venv/bin/python (3.8)
Project Root:
  /home/fallen/dev/pdmtest
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.10",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.1.13-060113-generic",
  "platform_system": "Linux",
  "platform_version": "#202302221342 SMP PREEMPT_DYNAMIC Wed Feb 22 15:30:01 UTC 2023",
  "python_full_version": "3.8.10",
  "platform_python_implementation": "CPython",
  "python_version": "3.8",
  "sys_platform": "linux"
}

```

**Comment by frostming** [comment]
Fixed by removing the pdm.lock from the template

**Comment by fallen** [comment]
Thanks @frostming :)
