### ISSUE TITLE
proxy environment variables are not recognised by pdm anymore on windows

### ISSUE THREAD

**Issue by Nomiez** [pdm-project/pdm#2788]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce
Have a initialised project (pyproject.toml file) without a venv.
Have PyPi behind a **proxy** (in my case a company proxy).
Set the env vars:
```
set HTTPS_PROXY=...
set HTTP_PROXY=...
```
Now run `pdm  -v install`

## Actual behavior
Installation fails during "Synchronizing working set with resolved packages:
[ConnectError]: [Errno 11001] getaddrinfo failed

```bash
STATUS: Resolving packages from lockfile...
Synchronizing working set with resolved packages: 146 to add, 0 to update, 0 to remove

  ✖ Install pip 24.0 failed
Traceback (most recent call last):
  File "C:\[----]\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\[----]\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\[----]\AppData\Local\Programs\Python\Python39\Scripts\pdm.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\[----]\AppData\Local\Programs\Python\Python39\lib\site-packages\pdm\core.py", line 341, in main
    return core.main(args or sys.argv[1:])
  File "C:\[----]\AppData\Local\Programs\Python\Python39\lib\site-packages\pdm\core.py", line 259, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "C:\[----]\AppData\Local\Programs\Python\Python39\lib\site-packages\pdm\core.py", line 254, in main
    self.handle(project, options)
  File "C:\[----]\AppData\Local\Programs\Python\Python39\lib\site-packages\pdm\core.py", line 209, in handle
    command.handle(project, options)
  File "C:\[----]\AppData\Local\Programs\Python\Python39\lib\site-packages\pdm\cli\commands\install.py", line 100, in handle
    actions.do_sync(
  File "C:\[----]\AppData\Local\Programs\Python\Python39\lib\site-packages\pdm\cli\actions.py", line 238, in do_sync
    synchronizer.synchronize()
  File "C:\[----]\AppData\Local\Programs\Python\Python39\lib\site-packages\pdm\installers\synchronizers.py", line 445, in synchronize
    handlers[kind](key, progress)
  File "C:\[----]\AppData\Local\Programs\Python\Python39\lib\site-packages\pdm\installers\synchronizers.py", line 282, in install_candidate
    self.manager.install(can)
  File "C:\[----]\AppData\Local\Programs\Python\Python39\lib\site-packages\pdm\installers\manager.py", line 33, in install
    prepared.get_cached_package(),
  File "C:\[----]\AppData\Local\Programs\Python\Python39\lib\site-packages\pdm\models\candidates.py", line 404, in get_cached_package
    self._obtain(allow_all=False)
  File "C:\[----]\AppData\Local\Programs\Python\Python39\lib\site-packages\pdm\models\candidates.py", line 459, in _obtain
    self.link = _find_best_match_link(
  File "C:\[----]\AppData\Local\Programs\Python\Python39\lib\site-packages\pdm\models\candidates.py", line 107, in _find_best_match_link
    found = attempt_to_find()
  File "C:\[----]\AppData\Local\Programs\Python\Python39\lib\site-packages\pdm\models\candidates.py", line 98, in attempt_to_find
    best = finder.find_best_match(req.as_line(), hashes=hashes).best
  File "C:\[----]\AppData\Local\Programs\Python\Python39\lib\site-packages\unearth\finder.py", line 391, in find_best_match
    best_match = next(iter(applicable_candidates), None)
  File "C:\[----]\AppData\Local\Programs\Python\Python39\lib\site-packages\unearth\finder.py", line 324, in _find_packages_from_requirement
    yield from self._find_packages(requirement.name, allow_yanked)
  File "C:\[----]\AppData\Local\Programs\Python\Python39\lib\site-packages\unearth\finder.py", line 290, in _find_packages
    return sorted(all_packages, key=self._sort_key, reverse=True)
  File "C:\[----]\AppData\Local\Programs\Python\Python39\lib\site-packages\unearth\collector.py", line 178, in collect_links_from_location
    yield from _collect_links_from_index(session, location)
  File "C:\[----]\AppData\Local\Programs\Python\Python39\lib\site-packages\unearth\collector.py", line 198, in _collect_links_from_index
    page = fetch_page(session, location)
  File "C:\[----]\AppData\Local\Programs\Python\Python39\lib\site-packages\unearth\collector.py", line 185, in fetch_page
    resp = _get_html_response(session, location)
  File "C:\[----]\AppData\Local\Programs\Python\Python39\lib\site-packages\unearth\collector.py", line 220, in _get_html_response
    resp = session.get(
  File "C:\[----]\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 1054, in get
    return self.request(
  File "C:\[----]\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "C:\[----]\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 914, in send
    response = self._send_handling_auth(
  File "C:\[----]\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
  File "C:\[----]\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
  File "C:\[----]\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
  File "C:\[----]\AppData\Local\Programs\Python\Python39\lib\site-packages\hishel\_sync\_transports.py", line 215, in handle_request
    response = self._transport.handle_request(request)
  File "C:\[----]\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_transports\default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
  File "C:\[----]\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\[----]\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_transports\default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 11001] getaddrinfo failed
```

Could be related to: #2784 
## Expected behavior
The packages should be installed after setting the proxy variables (worked in pdm version <2.13.3).

## Environment Information

```bash
Version: PDM 2.13.3
Python Interpreter Version: 3.9.8

>pdm info --env  
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.8",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19045",
  "python_full_version": "3.9.8",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "win32"
}
C:\[----]\.venv\lib\site-packages\pdm\cli\actions.py:335: RuntimeWarning: Failed to get latest version: [Errno 11001] getaddrinfo failed
  warnings.warn(f"Failed to get latest version: {e}", RuntimeWarning, stacklevel=1)

```

**Comment by frostming** [comment]
#2784 has been fixed on main, can you verify if it fixes your problem?

**Comment by Nomiez** [comment]
Sadly it does not fix the problem :(

**Comment by frostming** [comment]
@Nomiez I don't think there is any other commits related to the http client. Maybe you can run `git bisect` to find the broken commit?

**Comment by dan-wilton** [comment]
@frostming, I wanted to confirm that this issue is actually fixed on `main` and a release can be cut.

I've tested the latest `main` locally, where I was previously receiving an error when I had the following configuration:
- `pypi.url` set to a private repository in the Home configuration `config.toml`, with `pypi.username` and `pypi.password` specified.
- `pypi.ca_certs` set to a company SSL cert
- `verify_ssl` set to `True`
- `HTTP_PROXY` and `HTTPS_PROXY` set in Windows Environment Variables

This is now working and I'm able to pull packages down from our private PyPi repo behind a HTTP Proxy again, thanks!
And great work on the switch to `httpx` too.

**Comment by Nomiez** [comment]
@frostming also works for me, thanks a lot :)
