### ISSUE TITLE
pdm add somepackage：[ConnectTimeout]: _ssl.c:983: The handshake operation timed out

### ISSUE THREAD

**Issue by Boxer-egg** [pdm-project/pdm#2807]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

```bash
pdm add phonenumbers -v
Adding packages to default dependencies: phonenumbers
STATUS: Resolving dependencies
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   phonenumbers
pdm.termui:   python==3.12.*
pdm.termui:   Adding requirement phonenumbers
Traceback (most recent call last):
  File "/Users/box/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/core.py", line 341, in main
    return core.main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/core.py", line 259, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/core.py", line 254, in main
    self.handle(project, options)
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/core.py", line 209, in handle
    command.handle(project, options)
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/cli/commands/add.py", line 69, in handle
    self.do_add(
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/cli/commands/add.py", line 159, in do_add
    resolved = do_lock(
               ^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/cli/actions.py", line 102, in do_lock
    mapping, dependencies = resolve(
                            ^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/resolver/core.py", line 39, in resolve
    result = resolver.resolve(requirements, max_rounds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/resolvelib/structs.py", line 127, in __bool__
    next(iter(self))
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/resolver/providers.py", line 350, in matches_gen
    yield from super_find()
               ^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/resolver/providers.py", line 226, in matches_gen
    candidates = self._find_candidates(reqs[0])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/resolver/providers.py", line 196, in _find_candidates
    return self.repository.find_candidates(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/models/repositories.py", line 174, in find_candidates
    cans = LazySequence(self._find_candidates(requirement, minimal_version=minimal_version))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/models/repositories.py", line 436, in _find_candidates
    for c in finder.find_all_packages(requirement.project_name, allow_yanked=requirement.is_pinned)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/unearth/finder.py", line 310, in find_all_packages
    self._find_packages(package_name, allow_yanked), hashes=hashes or {}
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/unearth/finder.py", line 290, in _find_packages
    return sorted(all_packages, key=self._sort_key, reverse=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/unearth/collector.py", line 178, in collect_links_from_location
    yield from _collect_links_from_index(session, location)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/unearth/collector.py", line 198, in _collect_links_from_index
    page = fetch_page(session, location)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/unearth/collector.py", line 185, in fetch_page
    resp = _get_html_response(session, location)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/unearth/collector.py", line 220, in _get_html_response
    resp = session.get(
           ^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/httpx/_client.py", line 1054, in get
    return self.request(
           ^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/httpx/_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/hishel/_sync/_transports.py", line 215, in handle_request
    response = self._transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/httpx/_transports/default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout: _ssl.c:983: The handshake operation timed out
```

## Steps to reproduce
```bash
pdm add phonenumbers
Adding packages to default dependencies: phonenumbers
See /Users/box/Library/Logs/pdm/pdm-lock-_98uxfsy.log for detailed debug log.
[ConnectTimeout]: _ssl.c:983: The handshake operation timed out
WARNING: Add '-v' to see the detailed traceback
```

## log
```bash
cat /Users/box/Library/Logs/pdm/pdm-lock-_98uxfsy.log
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   phonenumbers
pdm.termui:   python==3.12.*
pdm.termui:   Adding requirement phonenumbers
unearth.collector: Collecting links from https://pypi.org/simple/phonenumbers/
unearth.auth: Found index url https://pypi.org/simple/
pdm.termui: Error occurs
Traceback (most recent call last):
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/httpcore/_sync/connection.py", line 154, in _connect
    stream = stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/httpcore/_backends/sync.py", line 152, in start_tls
    with map_exceptions(exc_map):
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout: _ssl.c:983: The handshake operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/termui.py", line 255, in logging
    yield logger
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/cli/actions.py", line 102, in do_lock
    mapping, dependencies = resolve(
                            ^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/resolver/core.py", line 39, in resolve
    result = resolver.resolve(requirements, max_rounds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/resolvelib/structs.py", line 127, in __bool__
    next(iter(self))
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/resolver/providers.py", line 350, in matches_gen
    yield from super_find()
               ^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/resolver/providers.py", line 226, in matches_gen
    candidates = self._find_candidates(reqs[0])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/resolver/providers.py", line 196, in _find_candidates
    return self.repository.find_candidates(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/models/repositories.py", line 174, in find_candidates
    cans = LazySequence(self._find_candidates(requirement, minimal_version=minimal_version))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/models/repositories.py", line 436, in _find_candidates
    for c in finder.find_all_packages(requirement.project_name, allow_yanked=requirement.is_pinned)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/unearth/finder.py", line 310, in find_all_packages
    self._find_packages(package_name, allow_yanked), hashes=hashes or {}
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/unearth/finder.py", line 290, in _find_packages
    return sorted(all_packages, key=self._sort_key, reverse=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/unearth/collector.py", line 178, in collect_links_from_location
    yield from _collect_links_from_index(session, location)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/unearth/collector.py", line 198, in _collect_links_from_index
    page = fetch_page(session, location)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/unearth/collector.py", line 185, in fetch_page
    resp = _get_html_response(session, location)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/unearth/collector.py", line 220, in _get_html_response
    resp = session.get(
           ^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/httpx/_client.py", line 1054, in get
    return self.request(
           ^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/httpx/_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/hishel/_sync/_transports.py", line 215, in handle_request
    response = self._transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/httpx/_transports/default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/Users/box/.local/pipx/venvs/pdm/lib/python3.12/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout: _ssl.c:983: The handshake operation timed out
```

## Expected behavior

Successful installation

## Environment Information

```bash
 pdm info && pdm info --env
PDM version:
  2.13.3
Python Interpreter:
  /Users/box/new/Python/learn_duckdb/src/.venv/bin/python (3.12)
Project Root:
  /Users/box/new/Python/learn_duckdb/src
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.12.2",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "23.4.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; 
root:xnu-10063.101.17~1/RELEASE_ARM64_T6000",
  "python_full_version": "3.12.2",
  "platform_python_implementation": "CPython",
  "python_version": "3.12",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
are you hiding behind a proxy?

**Comment by Boxer-egg** [comment]
> are you hiding behind a proxy?

yes
export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890

**Comment by Boxer-egg** [comment]
Without activating proxy, promptly fill in the following information in pyproject.toml  :

[[tool. pdm. source]]
Name="Tuna"
URL=“ https://pypi.tuna.tsinghua.edu.cn/simple “
Verify_ssl=true


It's also the same error

**Comment by Boxer-egg** [comment]
pdm config pypi.url https://mirrors.aliyun.com/pypi/simple/

it works
