### ISSUE TITLE
Unable to add Blender `bpy` to a project on macOS (arm)

### ISSUE THREAD

**Issue by taranlu-houzz** [pdm-project/pdm#2824]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

1. Install `cpython@3.11.8` using `pdm python install`.
2. Create a new project using `pdm init`.
3. Try to add `bpy` by running: `pdm add bpy==4.1.0`.

## Actual behavior

Fails to add the package. It seems that it is unable to find the correct package version.

<details>
  <summary>Command Output</summary>

```fish
❯ pdm add -v bpy==4.1.0
Adding packages to default dependencies: bpy==4.1.0
STATUS: Resolving dependencies
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   pip>=24.0
pdm.termui:   bpy==4.1.0
pdm.termui:   python<3.12,>=3.11
pdm.termui:   Adding requirement pip>=24.0
pdm.termui:   Adding requirement bpy==4.1.0
pdm.termui:   Adding requirement python<3.12,>=3.11
pdm.termui: ======== Starting round 0 ========
STATUS: Resolving: new pin python<3.12,>=3.11
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
pdm.termui:   Adding requirement cython(from bpy 4.1.0)
pdm.termui:   Adding requirement numpy(from bpy 4.1.0)
pdm.termui:   Adding requirement requests(from bpy 4.1.0)
pdm.termui:   Adding requirement zstandard(from bpy 4.1.0)
STATUS: Resolving: new pin bpy 4.1.0
pdm.termui: Pinning: bpy 4.1.0
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
STATUS: Resolving: new pin pip 24.0
pdm.termui: Pinning: pip 24.0
pdm.termui: ======== Ending round 2 ========
pdm.termui: ======== Starting round 3 ========
STATUS: Resolving: new pin cython 3.0.10
pdm.termui: Pinning: cython 3.0.10
pdm.termui: ======== Ending round 3 ========
pdm.termui: ======== Starting round 4 ========
STATUS: Resolving: new pin numpy 1.26.4
pdm.termui: Pinning: numpy 1.26.4
pdm.termui: ======== Ending round 4 ========
pdm.termui: ======== Starting round 5 ========
pdm.termui:   Adding requirement charset-normalizer<4,>=2(from requests 2.31.0)
pdm.termui:   Adding requirement idna<4,>=2.5(from requests 2.31.0)
pdm.termui:   Adding requirement urllib3<3,>=1.21.1(from requests 2.31.0)
pdm.termui:   Adding requirement certifi>=2017.4.17(from requests 2.31.0)
STATUS: Resolving: new pin requests 2.31.0
pdm.termui: Pinning: requests 2.31.0
pdm.termui: ======== Ending round 5 ========
pdm.termui: ======== Starting round 6 ========
pdm.termui:   Adding requirement cffi>=1.11; platform_python_implementation == "PyPy"(from zstandard 0.22.0)
STATUS: Resolving: new pin zstandard 0.22.0
pdm.termui: Pinning: zstandard 0.22.0
pdm.termui: ======== Ending round 6 ========
pdm.termui: ======== Starting round 7 ========
STATUS: Resolving: new pin charset-normalizer 3.3.2
pdm.termui: Pinning: charset-normalizer 3.3.2
pdm.termui: ======== Ending round 7 ========
pdm.termui: ======== Starting round 8 ========
STATUS: Resolving: new pin idna 3.7
pdm.termui: Pinning: idna 3.7
pdm.termui: ======== Ending round 8 ========
pdm.termui: ======== Starting round 9 ========
STATUS: Resolving: new pin urllib3 2.2.1
pdm.termui: Pinning: urllib3 2.2.1
pdm.termui: ======== Ending round 9 ========
pdm.termui: ======== Starting round 10 ========
STATUS: Resolving: new pin certifi 2024.2.2
pdm.termui: Pinning: certifi 2024.2.2
pdm.termui: ======== Ending round 10 ========
pdm.termui: ======== Starting round 11 ========
pdm.termui:   Adding requirement pycparser(from cffi 1.16.0)
STATUS: Resolving: new pin cffi 1.16.0
pdm.termui: Pinning: cffi 1.16.0
pdm.termui: ======== Ending round 11 ========
pdm.termui: ======== Starting round 12 ========
STATUS: Resolving: new pin pycparser 2.22
pdm.termui: Pinning: pycparser 2.22
pdm.termui: ======== Ending round 12 ========
pdm.termui: ======== Starting round 13 ========
pdm.termui: ======== Resolution Result ========
pdm.termui: Stable pins:
pdm.termui:               python None
pdm.termui:                  bpy 4.1.0
pdm.termui:                  pip 24.0
pdm.termui:               cython 3.0.10
pdm.termui:                numpy 1.26.4
pdm.termui:             requests 2.31.0
pdm.termui:            zstandard 0.22.0
pdm.termui:   charset-normalizer 3.3.2
pdm.termui:                 idna 3.7
pdm.termui:              urllib3 2.2.1
pdm.termui:              certifi 2024.2.2
pdm.termui:                 cffi 1.16.0
pdm.termui:            pycparser 2.22
STATUS: Fetching hashes for resolved packages...
pdm.termui: Fetching hashes for bpy@4.1.0
pdm.termui: Fetching hashes for requests@2.31.0
pdm.termui: Fetching hashes for idna@3.7
pdm.termui: Fetching hashes for pycparser@2.22
pdm.termui: Fetching hashes for certifi@2024.2.2
pdm.termui: Fetching hashes for urllib3@2.2.1
pdm.termui: Fetching hashes for numpy@1.26.4
pdm.termui: Fetching hashes for charset-normalizer@3.3.2
pdm.termui: Fetching hashes for cffi@1.16.0
pdm.termui: Fetching hashes for zstandard@0.22.0
pdm.termui: Fetching hashes for cython@3.0.10
🔒 Lock successful
Changes are written to pyproject.toml.
STATUS: Resolving packages from lockfile...
unearth.preparer: The file . is a local directory, use it directly
Synchronizing working set with resolved packages: 9 to add, 0 to update, 0 to remove

  ✖ Install bpy 4.1.0 failed
pdm.termui: Error occurs:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.14.0/libexec/lib/python3.12/site-packages/pdm/installers/synchronizers.py", line 282, in install_candidate
    self.manager.install(can)
  File "/opt/homebrew/Cellar/pdm/2.14.0/libexec/lib/python3.12/site-packages/pdm/installers/manager.py", line 33, in install
    prepared.build(),
    ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.14.0/libexec/lib/python3.12/site-packages/pdm/models/candidates.py", line 402, in build
    self._obtain(allow_all=False)
  File "/opt/homebrew/Cellar/pdm/2.14.0/libexec/lib/python3.12/site-packages/pdm/models/candidates.py", line 445, in _obtain
    raise CandidateNotFound(
pdm.exceptions.CandidateNotFound: No candidate is found for `bpy` that matches the environment or hashes
pdm.termui: Using cached response for https://files.pythonhosted.org/packages/a2/73/a68704750a7679d0b6d3ad7aa8d4da8e14e151ae82e6fee774e6e0d05ec8/urllib3-2.2.1-py3-none-any.whl
unearth.preparer: Downloading <Link https://files.pythonhosted.org/packages/a2/73/a68704750a7679d0b6d3ad7aa8d4da8e14e151ae82e6fee774e6e0d05ec8/urllib3-2.2.1-py3-none-any.whl (from https://pypi.org/simple/urllib3/)> (121 kB)
pdm.termui: Using cached response for https://files.pythonhosted.org/packages/54/fc/c1b1a1e140451f3362789f546731b3ef36c78668be19d7fc6fbd4326b535/zstandard-0.22.0-cp311-cp311-macosx_11_0_arm64.whl
unearth.preparer: Downloading <Link https://files.pythonhosted.org/packages/54/fc/c1b1a1e140451f3362789f546731b3ef36c78668be19d7fc6fbd4326b535/zstandard-0.22.0-cp311-cp311-macosx_11_0_arm64.whl (from https://pypi.org/simple/zstandard/)> (703 kB)
pdm.termui: Using cached response for https://files.pythonhosted.org/packages/e5/3e/741d8c82801c347547f8a2a06aa57dbb1992be9e948df2ea0eda2c8b79e8/idna-3.7-py3-none-any.whl
unearth.preparer: Downloading <Link https://files.pythonhosted.org/packages/e5/3e/741d8c82801c347547f8a2a06aa57dbb1992be9e948df2ea0eda2c8b79e8/idna-3.7-py3-none-any.whl (from https://pypi.org/simple/idna/)> (66 kB)
pdm.termui: Using cached response for https://files.pythonhosted.org/packages/ba/06/a07f096c664aeb9f01624f858c3add0a4e913d6c96257acb4fce61e7de14/certifi-2024.2.2-py3-none-any.whl
unearth.preparer: Downloading <Link https://files.pythonhosted.org/packages/ba/06/a07f096c664aeb9f01624f858c3add0a4e913d6c96257acb4fce61e7de14/certifi-2024.2.2-py3-none-any.whl (from https://pypi.org/simple/certifi/)> (163 kB)
pdm.termui: Using cached response for https://files.pythonhosted.org/packages/70/8e/0e2d847013cb52cd35b38c009bb167a1a26b2ce6cd6965bf26b47bc0bf44/requests-2.31.0-py3-none-any.whl
unearth.preparer: Downloading <Link https://files.pythonhosted.org/packages/70/8e/0e2d847013cb52cd35b38c009bb167a1a26b2ce6cd6965bf26b47bc0bf44/requests-2.31.0-py3-none-any.whl (from https://pypi.org/simple/requests/)> (62 kB)
pdm.termui: Using cached response for https://files.pythonhosted.org/packages/dd/51/68b61b90b24ca35495956b718f35a9756ef7d3dd4b3c1508056fa98d1a1b/charset_normalizer-3.3.2-cp311-cp311-macosx_11_0_arm64.whl
unearth.preparer: Downloading <Link https://files.pythonhosted.org/packages/dd/51/68b61b90b24ca35495956b718f35a9756ef7d3dd4b3c1508056fa98d1a1b/charset_normalizer-3.3.2-cp311-cp311-macosx_11_0_arm64.whl (from https://pypi.org/simple/charset-normalizer/)> (118 kB)
pdm.termui: Using cached response for https://files.pythonhosted.org/packages/1a/2e/151484f49fd03944c4a3ad9c418ed193cfd02724e138ac8a9505d056c582/numpy-1.26.4-cp311-cp311-macosx_11_0_arm64.whl
unearth.preparer: Downloading <Link https://files.pythonhosted.org/packages/1a/2e/151484f49fd03944c4a3ad9c418ed193cfd02724e138ac8a9505d056c582/numpy-1.26.4-cp311-cp311-macosx_11_0_arm64.whl (from https://pypi.org/simple/numpy/)> (14.0 MB)
pdm.termui: Using cached response for https://files.pythonhosted.org/packages/b6/83/b0a63fc7b315edd46821a1a381d18765c1353d201246da44558175cddd56/Cython-3.0.10-py2.py3-none-any.whl
unearth.preparer: Downloading <Link https://files.pythonhosted.org/packages/b6/83/b0a63fc7b315edd46821a1a381d18765c1353d201246da44558175cddd56/Cython-3.0.10-py2.py3-none-any.whl (from https://pypi.org/simple/cython/)> (1.2 MB)
  ✔ Install requests 2.31.0 successful
  ✔ Install certifi 2024.2.2 successful
  ✔ Install urllib3 2.2.1 successful
  ✔ Install idna 3.7 successful
  ✔ Install charset-normalizer 3.3.2 successful
  ✔ Install zstandard 0.22.0 successful
  ✔ Install cython 3.0.10 successful
  ✔ Install numpy 1.26.4 successful
Retry failed jobs
  ✖ Install bpy 4.1.0 failed
pdm.termui: Error occurs:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.14.0/libexec/lib/python3.12/site-packages/pdm/installers/synchronizers.py", line 282, in install_candidate
    self.manager.install(can)
  File "/opt/homebrew/Cellar/pdm/2.14.0/libexec/lib/python3.12/site-packages/pdm/installers/manager.py", line 33, in install
    prepared.build(),
    ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.14.0/libexec/lib/python3.12/site-packages/pdm/models/candidates.py", line 402, in build
    self._obtain(allow_all=False)
  File "/opt/homebrew/Cellar/pdm/2.14.0/libexec/lib/python3.12/site-packages/pdm/models/candidates.py", line 445, in _obtain
    raise CandidateNotFound(
pdm.exceptions.CandidateNotFound: No candidate is found for `bpy` that matches the environment or hashes
Traceback (most recent call last):
  File "/opt/homebrew/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.14.0/libexec/lib/python3.12/site-packages/pdm/core.py", line 359, in main
    return core.main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.14.0/libexec/lib/python3.12/site-packages/pdm/core.py", line 277, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/opt/homebrew/Cellar/pdm/2.14.0/libexec/lib/python3.12/site-packages/pdm/core.py", line 272, in main
    self.handle(project, options)
  File "/opt/homebrew/Cellar/pdm/2.14.0/libexec/lib/python3.12/site-packages/pdm/core.py", line 208, in handle
    command.handle(project, options)
  File "/opt/homebrew/Cellar/pdm/2.14.0/libexec/lib/python3.12/site-packages/pdm/cli/commands/add.py", line 69, in handle
    self.do_add(
  File "/opt/homebrew/Cellar/pdm/2.14.0/libexec/lib/python3.12/site-packages/pdm/cli/commands/add.py", line 178, in do_add
    do_sync(
  File "/opt/homebrew/Cellar/pdm/2.14.0/libexec/lib/python3.12/site-packages/pdm/cli/actions.py", line 238, in do_sync
    synchronizer.synchronize()
  File "/opt/homebrew/Cellar/pdm/2.14.0/libexec/lib/python3.12/site-packages/pdm/installers/synchronizers.py", line 464, in synchronize
    raise InstallationError("Some package operations are not complete yet")
pdm.exceptions.InstallationError: Some package operations are not complete yet
```
</details>

I also commented on the Blender project issue tracker to illustrates what happens: https://projects.blender.org/blender/blender/issues/120181#issuecomment-1169278

I think this is related to some silliness with macOS versions. I was able to install the whl directly by changing the name of the file:

```
# doesn't install
bpy-4.1.0-cp311-cp311-macosx_11_2_arm64.whl

# symlink to the same file with the name changed works
bpy-4.1.0-cp311-cp311-macosx_11_0_arm64.whl
```

`pip` itself also appears to have this issue: https://stackoverflow.com/questions/76918323/pip-cannot-install-some-python-packages-due-to-missing-platform-tag-in-m1-mac

I think it was mentioned that `pdm` does not use `pip` to install packages under the hood, so I figured it made sense to raise an issue here as well.

## Expected behavior

The package should be able to be correctly installed.

`pdm` is able to install the previous version of `bpy==4.0.0` just fine (on Python 3.10).

## Environment Information

```bash
❯ pdm info && pdm info --env
PDM version:
  2.14.0
Python Interpreter:
  /Users/----/src/python/to_delete/.venv/bin/python (3.11)
Project Root:
  /Users/----/src/python/to_delete
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.11.8",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "22.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 22.6.0: Sun Dec 17 22:12:45 PST 2023; root:xnu-8796.141.3.703.2~2/RELEASE_ARM64_T6000",
  "python_full_version": "3.11.8",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "darwin"
}


```

**Comment by frostming** [comment]
It seems the maintainer of `bpy` should fix the wrong tag generated. Also read https://github.com/pypa/packaging/issues/435



> I think it was mentioned that `pdm` does not use `pip` to install packages under the hood, so I figured it made sense to raise an issue here as well.

True, but PDM uses the same utility library `packaging` to generate a list of accepted platform tags.

With that said, i am going to close this issue because there is nothing PDM can improve or fix.
