### ISSUE TITLE
PDM export to poetry format bug

### ISSUE THREAD

**Issue by natali-avr** [pdm-project/pdm#2877]
When running the command **pdm export --format poetry -v**
It throws an NotImplementedError error.
          
STATUS: Resolving packages from lockfile...
STATUS: Fetching hashes for resolved packages...
Traceback (most recent call last):
  File "/opt/homebrew/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pdm/core.py", line 358, in main
    return core.main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pdm/core.py", line 276, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/opt/homebrew/lib/python3.11/site-packages/pdm/core.py", line 271, in main
    self.handle(project, options)
  File "/opt/homebrew/lib/python3.11/site-packages/pdm/core.py", line 207, in handle
    command.handle(project, options)
  File "/opt/homebrew/lib/python3.11/site-packages/pdm/cli/commands/export.py", line 80, in handle
    content = FORMATS[options.format].export(project, packages, options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pdm/formats/poetry.py", line 238, in export
    raise NotImplementedError()
NotImplementedError

**PDM version installed:** 
PDM, version 2.15.2

**Comment by frostming** [comment]
Haha, no export now. Or are you interested in contributing this?
