### ISSUE TITLE
keyring 401 Unauthorized

### ISSUE THREAD

**Issue by ZlatyChlapec** [pdm-project/pdm#2961]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

1. brew install pdm
2. gcloud auth login
3. pdm add keyrings-google-artifactregistry-auth
4. activate venv
5. have private index configured:
 ```
[[tool.pdm.source]]
name = "private-idx"
url = "https://europe-west1-python.pkg.dev/gcp-project/private-idx/simple/"
```
6. pdm add private-dep

## Actual behavior

```pdm add private-dep -vv
Adding packages to default dependencies: private-dep
STATUS: Resolving dependencies
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   keyrings-google-artifactregistry-auth>=1.1.2
pdm.termui:   pytest>=8.2.2
pdm.termui:   unearth>=0.15.4
pdm.termui:   httpx>=0.27.0
pdm.termui:   private-dep
pdm.termui:   python==3.11.*
pdm.termui:   Adding requirement keyrings-google-artifactregistry-auth>=1.1.2
pdm.termui:   Adding requirement pytest>=8.2.2
pdm.termui:   Adding requirement unearth>=0.15.4
pdm.termui:   Adding requirement httpx>=0.27.0
pdm.termui:   Adding requirement private-dep
unearth.collector: Collecting links from https://pypi.org/simple/private-dep/
unearth.auth: Found index url https://pypi.org/simple/
unearth.collector: Failed to collect links from https://pypi.org/simple/private-dep/: Client Error(404): Not Found
unearth.collector: Collecting links from https://europe-west1-python.pkg.dev/gcp-project/private-idx/simple/private-dep/
unearth.auth: Found index url https://europe-west1-python.pkg.dev/gcp-project/private-idx/simple/
unearth.auth: Found index url https://europe-west1-python.pkg.dev/gcp-project/private-idx/simple/
unearth.auth: Getting password from keyring CLI for __token__@https://europe-west1-python.pkg.dev/gcp-project/private-idx/simple/
unearth.auth: Found credentials in keyring for europe-west1-python.pkg.dev
unearth.auth: 401 Error, Credentials not correct for https://europe-west1-python.pkg.dev/gcp-project/private-idx/simple/private-dep/
unearth.collector: Failed to collect links from https://europe-west1-python.pkg.dev/gcp-project/private-idx/simple/private-dep/: Client Error(401): Unauthorized
Traceback (most recent call last):
  File "/opt/homebrew/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.15.4/libexec/lib/python3.12/site-packages/pdm/core.py", line 359, in main
    return core.main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.15.4/libexec/lib/python3.12/site-packages/pdm/core.py", line 277, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/opt/homebrew/Cellar/pdm/2.15.4/libexec/lib/python3.12/site-packages/pdm/core.py", line 272, in main
    self.handle(project, options)
  File "/opt/homebrew/Cellar/pdm/2.15.4/libexec/lib/python3.12/site-packages/pdm/core.py", line 208, in handle
    command.handle(project, options)
  File "/opt/homebrew/Cellar/pdm/2.15.4/libexec/lib/python3.12/site-packages/pdm/cli/commands/add.py", line 69, in handle
    self.do_add(
  File "/opt/homebrew/Cellar/pdm/2.15.4/libexec/lib/python3.12/site-packages/pdm/cli/commands/add.py", line 162, in do_add
    resolved = do_lock(
               ^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.15.4/libexec/lib/python3.12/site-packages/pdm/cli/actions.py", line 101, in do_lock
    mapping, dependencies = resolve(
                            ^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.15.4/libexec/lib/python3.12/site-packages/pdm/resolver/core.py", line 39, in resolve
    result = resolver.resolve(requirements, max_rounds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.15.4/libexec/lib/python3.12/site-packages/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.15.4/libexec/lib/python3.12/site-packages/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/opt/homebrew/Cellar/pdm/2.15.4/libexec/lib/python3.12/site-packages/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.15.4/libexec/lib/python3.12/site-packages/resolvelib/structs.py", line 127, in __bool__
    next(iter(self))
  File "/opt/homebrew/Cellar/pdm/2.15.4/libexec/lib/python3.12/site-packages/pdm/resolver/providers.py", line 350, in matches_gen
    yield from super_find()
               ^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.15.4/libexec/lib/python3.12/site-packages/pdm/resolver/providers.py", line 226, in matches_gen
    candidates = self._find_candidates(reqs[0])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.15.4/libexec/lib/python3.12/site-packages/pdm/resolver/providers.py", line 196, in _find_candidates
    return self.repository.find_candidates(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.15.4/libexec/lib/python3.12/site-packages/pdm/models/repositories.py", line 174, in find_candidates
    cans = LazySequence(self._find_candidates(requirement, minimal_version=minimal_version))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.15.4/libexec/lib/python3.12/site-packages/pdm/models/repositories.py", line 439, in _find_candidates
    raise CandidateNotFound(
pdm.exceptions.CandidateNotFound: Unable to find candidates for private-dep. There may exist some issues with the package name or network condition.
```

## Expected behavior

dependency gets installed

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
❯ pdm info && pdm info --env
PDM version:
  2.15.4
Python Interpreter:
  /Users/user/Projects/project21/.venv/bin/python (3.11)
Project Root:
  /Users/user/Projects/project21
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.11.7",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "23.5.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000",
  "python_full_version": "3.11.7",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "darwin"
}
```

## Debugging

I have created following file in same project and all solutions were able to retrieve creds/dependency successfully.
```python
import logging

import httpx
import unearth

logging.basicConfig(level=logging.DEBUG)

repo = "https://europe-west1-python.pkg.dev/gcp-project/private-idx/simple/"
prc = unearth.auth.KeyringCliProvider("keyring")
prm = unearth.auth.KeyringModuleProvider()
mdba = unearth.auth.MultiDomainBasicAuth(False, [repo])
client = httpx.Client(auth=mdba)

print("CLI", prc.get_auth_info(repo, None))
print()
print("MODULE", prm.get_auth_info(repo, None))
print()
resp = client.get(repo)
print("MDBA", resp.text, resp.status_code)

pfr = unearth.PackageFinder(index_urls=[repo])
for pkg in pfr.find_all_packages("private-dep"):
    print(pkg)
```

**Comment by frostming** [comment]
> unearth.auth: Found credentials in keyring for europe-west1-python.pkg.dev
> unearth.auth: 401 Error, Credentials not correct for https://europe-west1-python.pkg.dev/gcp-project/private-idx/simple/private-dep/

Credentials found but not correct, please check it and reset if necessary

**Comment by ZlatyChlapec** [comment]
Yeah but that doesn't make any sense because when I run script from Debugging section everything worked. Even when I installed pdm inside venv it was able to correctly install package.

**Comment by ZlatyChlapec** [comment]
Running this:
```python
from pdm.models.finder import PDMPackageFinder
ppfr = PDMPackageFinder(index_urls=["https://europe-west1-python.pkg.dev/gcp-project/private-idx/simple/"])
for pkg in ppfr.find_all_packages("private-dep"):
    print(pkg)
```
also successfully found package but when I run pdm installed by brew while in active venv which has keyring I get "Credentials not correct".

**Comment by frostming** [comment]
Try adding a breakpoint and see if the credentials are correct.

**Comment by ZlatyChlapec** [comment]
After further testing I have found out that `unearth.PackageFinder` is able to retrieve package info if credentials are retrieved via `KeyringModuleProvider` but fails to do so in case they are retrieved via `KeyringCliProvider`.

>Try adding a breakpoint and see if the credentials are correct.

I am not sure how to check if credentials are correct because token changes with each call.

**Comment by ZlatyChlapec** [comment]
In the end issue was that without `--mode creds` flag, keyring CLI was returning just token but module version was returning `oauth2accesstoken` as username and token as password.

I have opened PR with fix in [unearth](https://github.com/frostming/unearth) repo.
