### ISSUE TITLE
`pdm add pyqt5` lead to `[InstallationError]: Some package operations are not complete yet`

### ISSUE THREAD

**Issue by H1DDENADM1N** [pdm-project/pdm#2984]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

```powershell
┏[user0][main]
┖[~\Documents\PyQt-SiliconUI]> pdm --version
PDM, version 2.16.1
```

## Steps to reproduce

```powershell
┏[user0][main]
┖[~\Documents\PyQt-SiliconUI]> pdm add pyqt5
Adding packages to default dependencies: pyqt5
🔒 Lock successful
Changes are written to pyproject.toml.
Synchronizing working set with resolved packages: 1 to add, 0 to update, 0 to remove

  ✖ Install pyqt5-qt5 5.15.14 failed
Retry failed jobs
  ✖ Install pyqt5-qt5 5.15.14 failed

ERRORS:
add pyqt5-qt5 failed:
Traceback (most recent call last):
  File "C:\Users\user0\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user0\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\installers\synchronizers.py", line 282, in install_candidate
    self.manager.install(can)
  File "C:\Users\user0\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\installers\manager.py", line 33, in install
    prepared.build(),
    ^^^^^^^^^^^^^^^^
  File "C:\Users\user0\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\models\candidates.py", line 404, in build
    self._obtain(allow_all=False)
  File "C:\Users\user0\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\models\candidates.py", line 447, in _obtain
    raise CandidateNotFound(
pdm.exceptions.CandidateNotFound: No candidate is found for `pyqt5-qt5` that matches the environment or hashes

See C:\Users\user0\AppData\Local\pdm\pdm\Logs\pdm-install-b1e66h2k.log for detailed debug log.
[InstallationError]: Some package operations are not complete yet
WARNING: Add '-v' to see the detailed traceback
```

## Actual behavior

`pdm add pyqt5` lead to `[InstallationError]: Some package operations are not complete yet`, `pyqt5-qt5` can't be installed.

```powershell
┏[user0][main]
┖[~\Documents\PyQt-SiliconUI]> pdm list --tree
pyqt5 5.15.10 [ required: >=5.15.10 ]
├── pyqt5-qt5 [ not installed ] [ required: >=5.15.2 ]
└── pyqt5-sip 12.13.0 [ required: <13,>=12.13 ]
setuptools 70.1.1 [ required: >=70.1.1 ]
```

## Expected behavior

`pdm add pyqt5` works fine as it should be.

## Environment Information

```powershell
# Paste the output of `pdm info && pdm info --env` below:

┏[user0][main]
┖[~\Documents\PyQt-SiliconUI]> pdm info && pdm info --env
PDM version:
  2.16.1
Python Interpreter:
  C:\Users\user0\Documents\PyQt-SiliconUI\.venv\Scripts\python.exe (3.12)
Project Root:
  C:/Users/user0/Documents/PyQt-SiliconUI
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.12.4",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19044",
  "python_full_version": "3.12.4",
  "platform_python_implementation": "CPython",
  "python_version": "3.12",
  "sys_platform": "win32"
}

```

**Comment by H1DDENADM1N** [comment]
C:\Users\user0\AppData\Local\pdm\pdm\Logs\pdm-install-b1e66h2k.log

```log
unearth.collector: Collecting links from https://pypi.org/simple/pyqt5-qt5/
unearth.auth: Found index url https://pypi.org/simple/
unearth.collector: Fetching HTML page https://pypi.org/simple/pyqt5-qt5/
unearth.evaluator: Skipping link <Link https://files.pythonhosted.org/packages/62/09/99a222b0360616250fb2e6003a54e43a2a06b0774f0f8d5daafb86a2c375/PyQt5_Qt5-5.15.2-py3-none-macosx_10_13_intel.whl (from https://pypi.org/simple/pyqt5-qt5/)>: none of the wheel tags(py3-none-macosx_10_13_intel) are compatible
unearth.evaluator: Skipping link <Link https://files.pythonhosted.org/packages/83/d4/241a6a518d0bcf0a9fcdcbad5edfed18d43e884317eab8d5230a2b27e206/PyQt5_Qt5-5.15.2-py3-none-manylinux2014_x86_64.whl (from https://pypi.org/simple/pyqt5-qt5/)>: none of the wheel tags(py3-none-manylinux2014_x86_64) are compatible
unearth.evaluator: Skipping link <Link https://files.pythonhosted.org/packages/1c/7e/ce7c66a541a105fa98b41d6405fe84940564695e29fc7dccf6d9e8c5f898/PyQt5_Qt5-5.15.2-py3-none-win32.whl (from https://pypi.org/simple/pyqt5-qt5/)>: none of the wheel tags(py3-none-win32) are compatible
unearth.evaluator: Skipping link <Link https://files.pythonhosted.org/packages/e1/66/3f374e3f9e74c1bc5659c23f6312d12684d8f78782d3b51c874c3657fa69/PyQt5_Qt5-5.15.11-1-py3-none-macosx_11_0_arm64.whl (from https://pypi.org/simple/pyqt5-qt5/)>: none of the wheel tags(py3-none-macosx_11_0_arm64) are compatible
unearth.evaluator: Skipping link <Link https://files.pythonhosted.org/packages/66/f5/0a684b2b33b1f1dceaf894d4e8a105f523bb08003f81c89a91e509c5f854/PyQt5_Qt5-5.15.11-py3-none-macosx_10_13_x86_64.whl (from https://pypi.org/simple/pyqt5-qt5/)>: none of the wheel tags(py3-none-macosx_10_13_x86_64) are compatible
unearth.evaluator: Skipping link <Link https://files.pythonhosted.org/packages/e0/ff/7ca1897bfb045562090491e3c368b3d2034dcdc04a92efae1e765564309a/PyQt5_Qt5-5.15.11-py3-none-macosx_11_0_arm64.whl (from https://pypi.org/simple/pyqt5-qt5/)>: none of the wheel tags(py3-none-macosx_11_0_arm64) are compatible
unearth.evaluator: Skipping link <Link https://files.pythonhosted.org/packages/be/3c/0f2ab2ef3bdf93ddb6834540613add6fca9ba76de08deb4a2465bb108088/PyQt5_Qt5-5.15.12-py3-none-macosx_10_13_x86_64.whl (from https://pypi.org/simple/pyqt5-qt5/)>: none of the wheel tags(py3-none-macosx_10_13_x86_64) are compatible
unearth.evaluator: Skipping link <Link https://files.pythonhosted.org/packages/46/c0/8d23f1e671fa63345d82852cf6734ade99f7dc69452ceed757afdcc6a868/PyQt5_Qt5-5.15.12-py3-none-macosx_11_0_arm64.whl (from https://pypi.org/simple/pyqt5-qt5/)>: none of the wheel tags(py3-none-macosx_11_0_arm64) are compatible
unearth.evaluator: Skipping link <Link https://files.pythonhosted.org/packages/40/dc/96d9d0ba0d13256343b53efffe8729f278e62409ab4c937bb22e70ab98ac/PyQt5_Qt5-5.15.13-py3-none-macosx_10_13_x86_64.whl (from https://pypi.org/simple/pyqt5-qt5/)>: none of the wheel tags(py3-none-macosx_10_13_x86_64) are compatible
unearth.evaluator: Skipping link <Link https://files.pythonhosted.org/packages/c9/8b/4441c208c8ca29b50fab6467ebfa32b6401d16c5c915a031a48dc85dfa7a/PyQt5_Qt5-5.15.13-py3-none-macosx_11_0_arm64.whl (from https://pypi.org/simple/pyqt5-qt5/)>: none of the wheel tags(py3-none-macosx_11_0_arm64) are compatible
unearth.evaluator: Skipping link <Link https://files.pythonhosted.org/packages/41/6c/fb7bfdf7345ef3ce8b1ed8ae67374cae177b0ea89928490de063932ae284/PyQt5_Qt5-5.15.14-py3-none-macosx_10_13_x86_64.whl (from https://pypi.org/simple/pyqt5-qt5/)>: none of the wheel tags(py3-none-macosx_10_13_x86_64) are compatible
unearth.evaluator: Skipping link <Link https://files.pythonhosted.org/packages/bf/b4/99c33cfe20b58426302783096a882a3defef0bc594c7891ff58c6122132c/PyQt5_Qt5-5.15.14-py3-none-macosx_11_0_arm64.whl (from https://pypi.org/simple/pyqt5-qt5/)>: none of the wheel tags(py3-none-macosx_11_0_arm64) are compatible
unearth.evaluator: Skipping package Package(name='pyqt5-qt5', version='5.15.2'): version doesn't match ==5.15.14
pdm.termui: Error occurs: 
Traceback (most recent call last):
  File "C:\Users\user0\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user0\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\installers\synchronizers.py", line 282, in install_candidate
    self.manager.install(can)
  File "C:\Users\user0\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\installers\manager.py", line 33, in install
    prepared.build(),
    ^^^^^^^^^^^^^^^^
  File "C:\Users\user0\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\models\candidates.py", line 404, in build
    self._obtain(allow_all=False)
  File "C:\Users\user0\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\models\candidates.py", line 447, in _obtain
    raise CandidateNotFound(
pdm.exceptions.CandidateNotFound: No candidate is found for `pyqt5-qt5` that matches the environment or hashes
unearth.collector: Collecting links from https://pypi.org/simple/pyqt5-qt5/
unearth.auth: Found index url https://pypi.org/simple/
unearth.collector: Fetching HTML page https://pypi.org/simple/pyqt5-qt5/
unearth.evaluator: Skipping link <Link https://files.pythonhosted.org/packages/62/09/99a222b0360616250fb2e6003a54e43a2a06b0774f0f8d5daafb86a2c375/PyQt5_Qt5-5.15.2-py3-none-macosx_10_13_intel.whl (from https://pypi.org/simple/pyqt5-qt5/)>: none of the wheel tags(py3-none-macosx_10_13_intel) are compatible
unearth.evaluator: Skipping link <Link https://files.pythonhosted.org/packages/83/d4/241a6a518d0bcf0a9fcdcbad5edfed18d43e884317eab8d5230a2b27e206/PyQt5_Qt5-5.15.2-py3-none-manylinux2014_x86_64.whl (from https://pypi.org/simple/pyqt5-qt5/)>: none of the wheel tags(py3-none-manylinux2014_x86_64) are compatible
unearth.evaluator: Skipping link <Link https://files.pythonhosted.org/packages/1c/7e/ce7c66a541a105fa98b41d6405fe84940564695e29fc7dccf6d9e8c5f898/PyQt5_Qt5-5.15.2-py3-none-win32.whl (from https://pypi.org/simple/pyqt5-qt5/)>: none of the wheel tags(py3-none-win32) are compatible
unearth.evaluator: Skipping link <Link https://files.pythonhosted.org/packages/e1/66/3f374e3f9e74c1bc5659c23f6312d12684d8f78782d3b51c874c3657fa69/PyQt5_Qt5-5.15.11-1-py3-none-macosx_11_0_arm64.whl (from https://pypi.org/simple/pyqt5-qt5/)>: none of the wheel tags(py3-none-macosx_11_0_arm64) are compatible
unearth.evaluator: Skipping link <Link https://files.pythonhosted.org/packages/66/f5/0a684b2b33b1f1dceaf894d4e8a105f523bb08003f81c89a91e509c5f854/PyQt5_Qt5-5.15.11-py3-none-macosx_10_13_x86_64.whl (from https://pypi.org/simple/pyqt5-qt5/)>: none of the wheel tags(py3-none-macosx_10_13_x86_64) are compatible
unearth.evaluator: Skipping link <Link https://files.pythonhosted.org/packages/e0/ff/7ca1897bfb045562090491e3c368b3d2034dcdc04a92efae1e765564309a/PyQt5_Qt5-5.15.11-py3-none-macosx_11_0_arm64.whl (from https://pypi.org/simple/pyqt5-qt5/)>: none of the wheel tags(py3-none-macosx_11_0_arm64) are compatible
unearth.evaluator: Skipping link <Link https://files.pythonhosted.org/packages/be/3c/0f2ab2ef3bdf93ddb6834540613add6fca9ba76de08deb4a2465bb108088/PyQt5_Qt5-5.15.12-py3-none-macosx_10_13_x86_64.whl (from https://pypi.org/simple/pyqt5-qt5/)>: none of the wheel tags(py3-none-macosx_10_13_x86_64) are compatible
unearth.evaluator: Skipping link <Link https://files.pythonhosted.org/packages/46/c0/8d23f1e671fa63345d82852cf6734ade99f7dc69452ceed757afdcc6a868/PyQt5_Qt5-5.15.12-py3-none-macosx_11_0_arm64.whl (from https://pypi.org/simple/pyqt5-qt5/)>: none of the wheel tags(py3-none-macosx_11_0_arm64) are compatible
unearth.evaluator: Skipping link <Link https://files.pythonhosted.org/packages/40/dc/96d9d0ba0d13256343b53efffe8729f278e62409ab4c937bb22e70ab98ac/PyQt5_Qt5-5.15.13-py3-none-macosx_10_13_x86_64.whl (from https://pypi.org/simple/pyqt5-qt5/)>: none of the wheel tags(py3-none-macosx_10_13_x86_64) are compatible
unearth.evaluator: Skipping link <Link https://files.pythonhosted.org/packages/c9/8b/4441c208c8ca29b50fab6467ebfa32b6401d16c5c915a031a48dc85dfa7a/PyQt5_Qt5-5.15.13-py3-none-macosx_11_0_arm64.whl (from https://pypi.org/simple/pyqt5-qt5/)>: none of the wheel tags(py3-none-macosx_11_0_arm64) are compatible
unearth.evaluator: Skipping link <Link https://files.pythonhosted.org/packages/41/6c/fb7bfdf7345ef3ce8b1ed8ae67374cae177b0ea89928490de063932ae284/PyQt5_Qt5-5.15.14-py3-none-macosx_10_13_x86_64.whl (from https://pypi.org/simple/pyqt5-qt5/)>: none of the wheel tags(py3-none-macosx_10_13_x86_64) are compatible
unearth.evaluator: Skipping link <Link https://files.pythonhosted.org/packages/bf/b4/99c33cfe20b58426302783096a882a3defef0bc594c7891ff58c6122132c/PyQt5_Qt5-5.15.14-py3-none-macosx_11_0_arm64.whl (from https://pypi.org/simple/pyqt5-qt5/)>: none of the wheel tags(py3-none-macosx_11_0_arm64) are compatible
unearth.evaluator: Skipping package Package(name='pyqt5-qt5', version='5.15.2'): version doesn't match ==5.15.14
pdm.termui: Error occurs: 
Traceback (most recent call last):
  File "C:\Users\user0\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user0\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\installers\synchronizers.py", line 282, in install_candidate
    self.manager.install(can)
  File "C:\Users\user0\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\installers\manager.py", line 33, in install
    prepared.build(),
    ^^^^^^^^^^^^^^^^
  File "C:\Users\user0\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\models\candidates.py", line 404, in build
    self._obtain(allow_all=False)
  File "C:\Users\user0\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\models\candidates.py", line 447, in _obtain
    raise CandidateNotFound(
pdm.exceptions.CandidateNotFound: No candidate is found for `pyqt5-qt5` that matches the environment or hashes
pdm.termui: Error occurs
Traceback (most recent call last):
  File "C:\Users\user0\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\termui.py", line 257, in logging
    yield logger
  File "C:\Users\user0\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\cli\actions.py", line 237, in do_sync
    synchronizer.synchronize()
  File "C:\Users\user0\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\installers\synchronizers.py", line 464, in synchronize
    raise InstallationError("Some package operations are not complete yet")
pdm.exceptions.InstallationError: Some package operations are not complete yet
```

**Comment by frostming** [comment]
Add `pyqt5-qt5==5.15.2` to the dependencies

**Comment by H1DDENADM1N** [comment]
> Add `pyqt5-qt5==5.15.2` to the dependencies

Thank you very much, It worked pretty effectively.

**Comment by JostTim** [comment]
Hello, 
There is still an issue with pyqt5 as a requirement, not being able to resolve automatically it's own pyqt5-qt5 requirements, if it is not also pinned out with a precise version (pyqt5-qt5==5.15.2).
Do you have an idea of the cause and if it may be possible to fix it in the future ?

**Comment by frostming** [comment]
> Do you have an idea of the cause and if it may be possible to fix it in the future ?

It is because pyqt5-qt5>5.15.2 doesn't ship any wheel for windows platform. So it will be prefered by the cross-platform resolver but not eligible on windows.

Maybe the packager decides to drop Windows, i don't know
