### ISSUE TITLE
2.16.1 appears to be hanging on `pdm init` to initialise a new project

### ISSUE THREAD

**Issue by Mjboothaus** [pdm-project/pdm#2990]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

```
PDM, version 2.16.1
% pdm init
Creating a pyproject.toml for PDM...
^CTraceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 550, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 1209, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 2116, in _communicate
    self._check_timeout(endtime, orig_timeout, stdout, stderr)
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 1253, in _check_timeout
    raise TimeoutExpired(
subprocess.TimeoutExpired: Command '['/Users/mjboothaus/.pyenv/shims/python3', '-EsSc', 'import platform; print(platform.python_version())']' timed out after 5.0 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.16.1/libexec/lib/python3.12/site-packages/pdm/core.py", line 363, in main
    return core.main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.16.1/libexec/lib/python3.12/site-packages/pdm/core.py", line 276, in main
    self.handle(project, options)
  File "/opt/homebrew/Cellar/pdm/2.16.1/libexec/lib/python3.12/site-packages/pdm/core.py", line 212, in handle
    command.handle(project, options)
  File "/opt/homebrew/Cellar/pdm/2.16.1/libexec/lib/python3.12/site-packages/pdm/cli/commands/init.py", line 237, in handle
    self.do_init(project, options=options)
  File "/opt/homebrew/Cellar/pdm/2.16.1/libexec/lib/python3.12/site-packages/pdm/cli/commands/init.py", line 40, in do_init
    self.set_python(project, options.python, hooks)
  File "/opt/homebrew/Cellar/pdm/2.16.1/libexec/lib/python3.12/site-packages/pdm/cli/commands/init.py", line 214, in set_python
    python_info = UseCommand().do_use(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.16.1/libexec/lib/python3.12/site-packages/pdm/cli/commands/use.py", line 144, in do_use
    selected_python = self.select_python(
                      ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.16.1/libexec/lib/python3.12/site-packages/pdm/cli/commands/use.py", line 102, in select_python
    found_interpreters = list(dict.fromkeys(project.iter_interpreters(python, filter_func=version_matcher)))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.16.1/libexec/lib/python3.12/site-packages/pdm/project/core.py", line 653, in iter_interpreters
    if filter_func is None or filter_func(interpreter):
                              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.16.1/libexec/lib/python3.12/site-packages/pdm/cli/commands/use.py", line 64, in version_matcher
    return py_version.valid and (
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.16.1/libexec/lib/python3.12/site-packages/pdm/models/python.py", line 33, in valid
    return self._py_ver.executable.exists() and self._py_ver.is_valid()
                                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.16.1/libexec/lib/python3.12/site-packages/findpython/python.py", line 46, in is_valid
    v = self._get_version()
        ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.16.1/libexec/lib/python3.12/site-packages/findpython/python.py", line 202, in _get_version
    version = _run_script(
              ^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pdm/2.16.1/libexec/lib/python3.12/site-packages/findpython/python.py", line 23, in _run_script
    return subprocess.run(
           ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 563, in run
    process.wait()
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 1264, in wait
    return self._wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 2053, in _wait
    (pid, sts) = self._try_wait(0)
                 ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 2011, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
```

## Steps to reproduce

Run `pdm init`

## Actual behavior

Command just hangs and need to interrupt (see output above). Tried `brew` uninstall/reinstall also via `pipx` and same result.

## Expected behavior

Command runs and provides a list of available Python environments to choose from as 1st step in the init process.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
pdm info && pdm info --env
[ProjectError]: The pyproject.toml has not been initialized yet. You can do this by running `pdm init`.
```

Also
```
% brew list python
/opt/homebrew/Cellar/python@3.12/3.12.4/bin/2to3
/opt/homebrew/Cellar/python@3.12/3.12.4/bin/2to3-3.12
/opt/homebrew/Cellar/python@3.12/3.12.4/bin/idle3
/opt/homebrew/Cellar/python@3.12/3.12.4/bin/idle3.12
/opt/homebrew/Cellar/python@3.12/3.12.4/bin/pip3
/opt/homebrew/Cellar/python@3.12/3.12.4/bin/pip3.12
/opt/homebrew/Cellar/python@3.12/3.12.4/bin/pydoc3
/opt/homebrew/Cellar/python@3.12/3.12.4/bin/pydoc3.12
/opt/homebrew/Cellar/python@3.12/3.12.4/bin/python3
/opt/homebrew/Cellar/python@3.12/3.12.4/bin/python3-config
/opt/homebrew/Cellar/python@3.12/3.12.4/bin/python3.12
/opt/homebrew/Cellar/python@3.12/3.12.4/bin/python3.12-config
...
```

**Comment by Mjboothaus** [comment]
I closed/reopened VS Code in the hope of "solving" the issue. This did not work.

So I tried re-booting my MacBook and this seems to have fixed it (unless it was unrelated to the reboot - not sure if it is subject to a network connection? Although my internet seemed ok).

Thanks for all your work on PDM.

Cheers,
Michael
