### ISSUE TITLE
`pdm` installed scripts break in with venv + non-src layout

### ISSUE THREAD

**Issue by ditsuke** [pdm-project/pdm#2996]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce
1. Project layout
```
.
├── co.py
├── nvim.local.log
├── pdm.lock
├── pyproject.toml
└── src
    └── a.py
```

2. `pyproject.toml`
```toml
[project]
name = "llama-cpp-scripts"
version = "0.0.0"
requires-python = ">=3.9,<3.12"
dependencies = ["numpy<2.0.0,>=1.25.0"]

[tool.pdm.build]
includes = ["*.py"]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project.scripts]
co = "co:main"
```

3. Run script
```sh
❯ pdm install && pdm run co
INFO: The saved Python interpreter doesn't match the project's requirement. Trying to find another one.
WARNING: Project requires a python version of <3.12,>=3.9, The virtualenv is being created for you as it cannot be matched to the right 
version.
INFO: python.use_venv is on, creating a virtualenv for this project...
Virtualenv is created successfully at /home/dt/Documents/temp/fail-pdm/.venv
Synchronizing working set with resolved packages: 1 to add, 0 to update, 0 to remove

  ✔ Install numpy 1.26.4 successful
Installing the project as an editable package...
  ✔ Install llama-cpp-scripts 0.0.0 successful

🎉 All complete!

Traceback (most recent call last):
  File "/home/dt/Documents/temp/fail-pdm/.venv/bin/co", line 5, in <module>
    from co import main
ModuleNotFoundError: No module named 'co'
```

## Actual behavior
Script run fails with a `ModuleNotFoundError`. Ref: https://github.com/ggerganov/llama.cpp/pull/5745/#discussion_r1665676033

## Expected behavior

Script run succeeds. `pdm` shouldn't be thrown off by an `src` directory, it should instead compute sys.path through paths of file in `include`.

## Environment Information

```bash
❯ pdm info && pdm info --env
PDM version:
  2.16.1
Python Interpreter:
  /home/dt/Documents/temp/fail-pdm/.venv/bin/python (3.11)
Project Root:
  /home/dt/Documents/temp/fail-pdm
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.9",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.9.6-200.fc40.x86_64",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT_DYNAMIC Fri Jun 21 15:48:21 UTC 2024",
  "python_full_version": "3.11.9",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "linux"
}
```

Minimum reproducible project archive: [minrepoduction.tar.gz](https://github.com/user-attachments/files/16101892/minrepoduction.tar.gz)

**Comment by pawamoy** [comment]
You might be confusing `[project.scripts]` and [tool.poetry.scripts]`, they are not the same thing.

`[project.scripts] co = "co:main"` will create an executable in a venv's bin folder, which will try to import `main` from `co` and run it. Except there are no `co` module installed. This is reproducible with pip:

```
rm -rf .venv
python -m venv .venv
. .venv/bin/activate
pip install -e .
co
```

...gives the same error:

```
Traceback (most recent call last):
  File "/tmp/t/.venv/bin/co", line 5, in <module>
    from co import main
ModuleNotFoundError: No module named 'co'
```

You might want to use [user scripts](https://pdm-project.org/en/latest/usage/scripts/#user-scripts) instead, or actually put your `co.py` module into your sources, so that it is installed and the `co:main` scripts can find it.

**Comment by ditsuke** [comment]
I believe for pdm, the proper analogue to `tool.poetry.scripts` is `project.scripts` as `tool.pdm.scripts` does not register as project entrypoints (which is a requirement here.

To demonstrate further, this behavior changes when the `src` directory is removed:
```py
❯ mv src src2 && pdm install && pdm run co
All packages are synced to date, nothing to do.
Installing the project as an editable package...
  ✔ Update llama-cpp-scripts 0.0.0 -> 0.0.0 successful

🎉 All complete!

sys.path: ['/home/dt/Documents/temp/fail-pdm/.venv/bin', '/home/dt/.local/share/mise/installs/python/3.11/lib/python311.zip', '/home/dt/.
local/share/mise/installs/python/3.11/lib/python3.11', '/home/dt/.local/share/mise/installs/python/3.11/lib/python3.11/lib-dynload', '/ho
me/dt/Documents/temp/fail-pdm/.venv/lib/python3.11/site-packages', '/home/dt/Documents/temp/fail-pdm']
```

And also when the script is in src:
```
❯ mv co.py src && pdm install && pdm run co
All packages are synced to date, nothing to do.
Installing the project as an editable package...
  ✔ Update llama-cpp-scripts 0.0.0 -> 0.0.0 successful

🎉 All complete!

sys.path: ['/home/dt/Documents/temp/fail-pdm/.venv/bin', '/home/dt/.local/share/mise/installs/python/3.11/lib/python311.zip', '/home/dt/.
local/share/mise/installs/python/3.11/lib/python3.11', '/home/dt/.local/share/mise/installs/python/3.11/lib/python3.11/lib-dynload', '/ho
me/dt/Documents/temp/fail-pdm/.venv/lib/python3.11/site-packages', '/home/dt/Documents/temp/fail-pdm/src']
```

Curiously, the `sys.path` changes with the presence of the `src` folder. I don't observe this behavior with poetry, where `sys.path` always includes project root. I'm unable to discern how pdm manages this.

**Comment by ditsuke** [comment]
> or actually put your co.py module into your sources, so that it is installed and the co:main script can find it.

Could you clarify if this means putting it in `include` (already done) or some other key?

**Comment by frostming** [comment]
There may be a tricky issue here, where `src` is not included by `includes`, but the project is detected as src layout

**Comment by frostming** [comment]
It's weird I can't reproduce the ModuleNotFound with or without `src/`

Can you please check the file existence inside `.venv/lib/pythonX.Y/site-packages`?

**Comment by pawamoy** [comment]
> I believe for pdm, the proper analogue to tool.poetry.scripts is project.scripts as tool.pdm.scripts does not register as project entrypoints (which is a hard requirement here).

Sorry, yes, I was the one confused :slightly_smiling_face: So you really want `[project.scripts]`, OK.

> Interestingly also reproducible with pip, so not which part is introducing the sys.path detection now

Interesting indeed! Thanks for investigating further. Let me try as well.

**Comment by pawamoy** [comment]
With `src`, after `pip install -e .`:

```console
% cat .venv/lib/python3.11/site-packages/llama_cpp_scripts.pth
/tmp/t/src
```

In that case the `co.py` module isn't found and calling your entrypoint fails.

---

With `src2`, after `pip install -e .`:

```console
% cat .venv/lib/python3.11/site-packages/llama_cpp_scripts.pth
/tmp/t
```

Indeed if the `src` folder is found, it is used as source folder, and if it isn't found, then the repository root is used as source folder. In that case, the `co.py` module is found and calling your entrypoint works.

---

So the issue comes from the automatic detection of `src` by PDM backend when installing the project in editable mode. But I wouldn't call this an issue. Detection of `src` is advertised and expected.

---

> Could you clarify if this means putting it in include (already done) or some other key?

I meant to move `co.py` into your `src` folder (i.e. into your package, since you seem to want to bundle it anyway).

**Comment by frostming** [comment]
> It's weird I can't reproduce the ModuleNotFound with or without `src/`, the project root is always in the `sys.path`

FIne, some platform difference, I reproduced it on Linux

This is a bit tricky, the project is detected as src layout but `src` is not even included by the build.
