### ISSUE TITLE
`ValueError` Occurs When Creating Virtual Environment with PDM (2.17.1)

### ISSUE THREAD

**Issue by alynlee** [pdm-project/pdm#3046]
- [v] I have searched the issue tracker and believe that this is not a duplicate.

## Description
I encounter a ValueError when attempting to create a virtual environment using PDM.

## Steps to Reproduce
Run pdm venv create or a similar command to create a new virtual environment.
Observe the error message that appears during the process.

## Expected Behavior
The virtual environment should be created successfully without any errors.

## Actual Behavior
A ValueError is raised, and the virtual environment is not created. The specific error message is as follows:

```bash
❯ pdm venv create --name litestar-3.12 -v
STATUS: Creating virtualenv using virtualenv...
Traceback (most recent call last):
  File "/Users/ialeum/.local/bin/pdm", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/ialeum/Library/Application Support/pdm/venv/lib/python3.11/site-packages/pdm/core.py", line 346, in main
    return core.main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ialeum/Library/Application Support/pdm/venv/lib/python3.11/site-packages/pdm/core.py", line 264, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/Users/ialeum/Library/Application Support/pdm/venv/lib/python3.11/site-packages/pdm/core.py", line 259, in main
    self.handle(project, options)
  File "/Users/ialeum/Library/Application Support/pdm/venv/lib/python3.11/site-packages/pdm/core.py", line 195, in handle
    command.handle(project, options)
  File "/Users/ialeum/Library/Application Support/pdm/venv/lib/python3.11/site-packages/pdm/cli/commands/venv/create.py", line 50, in handle
    path = venv_backend.create(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/ialeum/Library/Application Support/pdm/venv/lib/python3.11/site-packages/pdm/cli/commands/venv/backends.py", line 126, in create
    prompt = prompt.format(
             ^^^^^^^^^^^^^^
ValueError: Invalid format specifier '0:10' for object of type 'str`
```
## Environment Information
PDM Version: [2.17.1]
Python Version: [3.12]
Operating System: [macOS 14.4.1 (23E224)]

**Comment by frostming** [comment]
Can you show the output of `pdm config`? Check the `venv.prompt` config.

**Comment by alynlee** [comment]
Hi,

Thank you for your response. Here is my pdm.config setup. Could you please take a look at it?

```bash
❯ pdm config
Site/default configuration (/Library/Application Support/pdm/config.toml):
build_isolation = True
cache_dir = /Users/ialeum/Library/Caches/pdm
check_update = True
global_project.fallback = False
global_project.fallback_verbose = True
global_project.path = /Users/ialeum/Library/Application Support/pdm/global-project
global_project.user_site = False
install.cache = False
install.cache_method = symlink
install.parallel = True
log_dir = /Users/ialeum/Library/Logs/pdm
pypi.ignore_stored_index = False
pypi.json_api = False
pypi.url = https://pypi.org/simple
pypi.verify_ssl = True
python.install_root = /Users/ialeum/Library/Application Support/pdm/python
python.providers = ['venv', 'path', 'asdf', 'pyenv', 'rye', 'winreg', 'macos']
python.use_pyenv = True
python.use_venv = True
request_timeout = 15
strategy.inherit_metadata = True
strategy.resolve_max_rounds = 10000
strategy.save = minimum
strategy.update = reuse
theme.error = red
theme.info = blue
theme.primary = cyan
theme.req = bold green
theme.success = green
theme.warning = yellow
venv.backend = virtualenv
venv.in_project = True
venv.location = /Users/ialeum/Library/Application Support/pdm/venvs
venv.prompt = {project_name}-{python_version}
venv.with_pip = False

Home configuration (/Users/ialeum/Library/Application Support/pdm/config.toml):
venv.backend = virtualenv
venv.in_project = True
venv.location = /Users/ialeum/Library/Application Support/pdm/venvs
venv.prompt = {project_name:0:10}-{python_version}
venv.with_pip = True
```

**pdm/config.toml**
```
[venv]
backend = "virtualenv"
in_project = true
location = "/Users/ialeum/Library/Application Support/pdm/venvs"
prompt = "{project_name:0:10}-{python_version}"
with_pip = true
```

**Comment by frostming** [comment]
> **pdm/config.toml**
> 
> ```
> [venv]
> backend = "virtualenv"
> in_project = true
> location = "/Users/ialeum/Library/Application Support/pdm/venvs"
> prompt = "{project_name:0:10}-{python_version}"
> with_pip = true
> ```

Check the prompt here, the syntax is wrong, you need to fix it.
