### ISSUE TITLE
fix_legacy_specifier function broken in todays update

### ISSUE THREAD

**Issue by MartinSA04** [pdm-project/pdm#3062]
- [x ] I have searched the issue tracker and believe that this is not a duplicate.

```bash
Traceback (most recent call last):
  File "/home/martin/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/martin/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/core.py", line 346, in main
    return core.main(args or sys.argv[1:])
  File "/home/martin/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/core.py", line 264, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/home/martin/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/core.py", line 259, in main
    self.handle(project, options)
  File "/home/martin/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/core.py", line 195, in handle
    command.handle(project, options)
  File "/home/martin/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/cli/commands/update.py", line 75, in handle
    self.do_update(
  File "/home/martin/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/cli/commands/update.py", line 181, in do_update
    resolved = do_lock(
  File "/home/martin/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/cli/actions.py", line 145, in do_lock
    mapping = _lock_for_env(
  File "/home/martin/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/cli/actions.py", line 189, in _lock_for_env
    mapping, *_ = resolve(
  File "/home/martin/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/resolver/core.py", line 43, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "/home/martin/.local/share/pdm/venv/lib/python3.10/site-packages/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/martin/.local/share/pdm/venv/lib/python3.10/site-packages/resolvelib/resolvers.py", line 426, in resolve
    name = min(unsatisfied_names, key=self._get_preference)
  File "/home/martin/.local/share/pdm/venv/lib/python3.10/site-packages/resolvelib/resolvers.py", line 203, in _get_preference
    return self._p.get_preference(
  File "/home/martin/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/resolver/providers.py", line 117, in get_preference
    deps = self.get_dependencies(candidate)
  File "/home/martin/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/resolver/providers.py", line 276, in get_dependencies
    deps, requires_python, _ = self.repository.get_dependencies(candidate)
  File "/home/martin/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/models/repositories/base.py", line 101, in get_dependencies
    requirements, requires_python, summary = getter(candidate)
  File "/home/martin/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/models/repositories/base.py", line 41, in wrapper
    result = func(self, candidate)
  File "/home/martin/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/models/repositories/base.py", line 276, in _get_dependencies_from_metadata
    deps = prepared.get_dependencies_from_metadata()
  File "/home/martin/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/models/candidates.py", line 611, in get_dependencies_from_metadata
    return filter_requirements_with_extras(self.metadata.requires or [], extras)
  File "/home/martin/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/models/candidates.py", line 604, in metadata
    self.candidate.requires_python = result.metadata.get("Requires-Python", "")
  File "/home/martin/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/models/candidates.py", line 241, in requires_python
    PySpecSet(value)
  File "/home/martin/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/models/specifiers.py", line 89, in __init__
    super().__init__(fix_legacy_specifier(spec))
  File "/home/martin/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/models/specifiers.py", line 68, in fix_legacy_specifier
    return _legacy_specifier_re.sub(fix_wildcard, specifier)
TypeError: expected string or bytes-like object
```

## Steps to reproduce

Update to latest version 2.17.2 and have some legacy specifiers in project.

## Actual behavior

pdm update crashes as a result of this

## Expected behavior

pdm update should not crash

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.17.2
Python Interpreter:
  /home/martin/weldstack/.venv/bin/python (3.11)
Project Root:
  /home/martin/weldstack
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.12",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.5.0-45-generic",
  "platform_system": "Linux",
  "platform_version": "#45~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 15 16:40:02 UTC 2",
  "python_full_version": "3.11.9",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "linux"
}
```

**Comment by sydney-runkle** [comment]
We're running into a similar issue, though we have `requires-python` in our `pyproject.toml`: https://github.com/pydantic/pydantic/actions/runs/10181383157/job/28161403864?pr=10003

**Comment by sydney-runkle** [comment]
If it's helpful, here's our PR with a few fixes allowing for compatibility with v2.17.0: https://github.com/pydantic/pydantic/pull/10003

**Comment by frostming** [comment]
I am not on my computer so I can't debug. can you confirm if the line returns `None`? that is a bit surprising to me

```python 
self.candidate.requires_python = result.metadata.get("Requires-Python", "")
```

should not it be an empty string if the field is missing?

**Comment by MartinSA04** [comment]
Yep, that line returns None, as the field is not missing there, but its value is None.
