### ISSUE TITLE
PDM unnecessarily updates packages

### ISSUE THREAD

**Issue by mjspeck** [pdm-project/pdm#3066]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

In my `pyproject.toml` I have this:

```toml
dependencies = [
...
"torch>=2,<3"
...
]
```

I'm installing in a pyenv virtualenv with python `3.10.13` on a Macbook with an M2 chip.

## Actual behavior

If I use pip install everything works fine and torch 2.2.2 is installed. However, when I try to install with PDM I get this:

```
Changes are written to pdm.lock.
Synchronizing working set with resolved packages: 0 to add, 1 to update, 0 to remove

  ✖ Update torch 2.2.2 -> 2.4.0 failed
Retry failed jobs
  ✖ Update torch 2.2.2 -> 2.4.0 failed

ERRORS:
update torch failed:
Traceback (most recent call last):
  File "/Users/mattspeck/.pyenv/versions/3.11.3/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mattspeck/Library/Application Support/pdm/venv/lib/python3.11/site-packages/pdm/installers/synchronizers.py", line 251, in update_candidate
    self.manager.overwrite(dist, can)
  File "/Users/mattspeck/Library/Application Support/pdm/venv/lib/python3.11/site-packages/pdm/installers/manager.py", line 62, in overwrite
    installed = self.install(candidate)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mattspeck/Library/Application Support/pdm/venv/lib/python3.11/site-packages/pdm/installers/manager.py", line 33, in install
    prepared.build(),
    ^^^^^^^^^^^^^^^^
  File "/Users/mattspeck/Library/Application Support/pdm/venv/lib/python3.11/site-packages/pdm/models/candidates.py", line 388, in build
    self._obtain(allow_all=False)
  File "/Users/mattspeck/Library/Application Support/pdm/venv/lib/python3.11/site-packages/pdm/models/candidates.py", line 429, in _obtain
    raise CandidateNotFound(
pdm.exceptions.CandidateNotFound: No candidate is found for `torch` that matches the environment or hashes

See /Users/mattspeck/Library/Logs/pdm/pdm-install-jwlbeq0v.log for detailed debug log.
[InstallationError]: Some package operations are not complete yet
```

## Expected behavior

There's no need for PDM to try to update to `2.4.0` and even if it does try, the install should not fail because torch `2.2.2` is a valid torch version.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:

INFO: Inside an active virtualenv /Users/mattspeck/.pyenv/versions/3.10.13/envs/pdm-env, reusing it.
Set env var PDM_IGNORE_ACTIVE_VENV to ignore it.
PDM version:
  2.17.1
Python Interpreter:
  /Users/mattspeck/.pyenv/versions/3.10.13/envs/pdm-env/bin/python (3.10)
Project Root:
  /Users/mattspeck/Development/Cynnovative/pdm-env/repos/PDM-PROJ
Local Packages:
  
INFO: Inside an active virtualenv /Users/mattspeck/.pyenv/versions/3.10.13/envs/pdm-env, reusing it.
Set env var PDM_IGNORE_ACTIVE_VENV to ignore it.
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.3",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "23.2.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 23.2.0: Wed Nov 15 21:59:33 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8112",
  "python_full_version": "3.10.13",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "darwin"
}

```

**Comment by frostming** [comment]
> First, I can't reproduce, I am also on a M2 chip mac and it installs 2.4.0 successfully.

Okay, I saw the difference here, you are using an intel Python on M2 chip?

> ```shell
>   "platform_machine": "x86_64",
> ```
