### ISSUE TITLE
PDM errors for source that is not defined in `pyproject.toml`

### ISSUE THREAD

**Issue by NiklasRosenstein** [pdm-project/pdm#3078]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

<details><summary><code>pdm install -v</code></summary>

```
WARNING: Lockfile is generated on an older version of PDM
STATUS: Resolving packages from lockfile...
unearth.preparer: The file . is a local directory, use it directly
All packages are synced to date, nothing to do.
  Installing the project as an editable package...
pdm.termui: Overwriting distribution pdm-project
pdm.termui: Preparing environment(Isolated mode) for PEP 517 build...
pdm.termui: Running PEP 517 backend to build a wheel for <Link file:///Users/niklas.rosenstein/git/kraken-build/kraken/examples/pdm-project (from None)>
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   pdm-backend
pdm.termui:   python==3.12.4
pdm.termui:   Adding requirement pdm-backend
  ✖ Update pdm-project 0.1.0 -> 0.1.0 failed
Traceback (most recent call last):
  File "/Users/niklas.rosenstein/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/niklas.rosenstein/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/core.py", line 346, in main
    return core.main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niklas.rosenstein/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/core.py", line 264, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/Users/niklas.rosenstein/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/core.py", line 259, in main
    self.handle(project, options)
  File "/Users/niklas.rosenstein/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/core.py", line 195, in handle
    command.handle(project, options)
  File "/Users/niklas.rosenstein/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/cli/commands/install.py", line 103, in handle
    actions.do_sync(
  File "/Users/niklas.rosenstein/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/cli/actions.py", line 330, in do_sync
    synchronizer.synchronize()
  File "/Users/niklas.rosenstein/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/installers/synchronizers.py", line 434, in synchronize
    self.update_candidate(self_key, status.progress)
  File "/Users/niklas.rosenstein/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/installers/synchronizers.py", line 249, in update_candidate
    self.manager.overwrite(dist, can)
  File "/Users/niklas.rosenstein/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/installers/manager.py", line 62, in overwrite
    installed = self.install(candidate)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niklas.rosenstein/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/installers/manager.py", line 33, in install
    prepared.build(),
    ^^^^^^^^^^^^^^^^
  File "/Users/niklas.rosenstein/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/models/candidates.py", line 406, in build
    self._cached = Path(builder.build(build_dir, metadata_directory=self._metadata_dir))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niklas.rosenstein/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/builders/base.py", line 84, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niklas.rosenstein/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/builders/editable.py", line 37, in build
    self.install(self._requires, shared=True)
  File "/Users/niklas.rosenstein/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/builders/base.py", line 322, in install
    install_requirements(missing, env)
  File "/Users/niklas.rosenstein/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/installers/core.py", line 31, in install_requirements
    resolved, _ = resolve(resolver, reqs, max_rounds=resolve_max_rounds, keep_self=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niklas.rosenstein/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/resolver/core.py", line 43, in resolve
    result = resolver.resolve(requirements, max_rounds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niklas.rosenstein/.local/pipx/venvs/pdm/lib/python3.12/site-packages/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niklas.rosenstein/.local/pipx/venvs/pdm/lib/python3.12/site-packages/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/Users/niklas.rosenstein/.local/pipx/venvs/pdm/lib/python3.12/site-packages/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/niklas.rosenstein/.local/pipx/venvs/pdm/lib/python3.12/site-packages/resolvelib/structs.py", line 127, in __bool__
    next(iter(self))
         ^^^^^^^^^^
  File "/Users/niklas.rosenstein/.local/pipx/venvs/pdm/lib/python3.12/site-packages/resolvelib/structs.py", line 136, in __iter__
    self._factory() if self._iterable is None else self._iterable
    ^^^^^^^^^^^^^^^
  File "/Users/niklas.rosenstein/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/resolver/providers.py", line 230, in matches_gen
    candidates = self._find_candidates(reqs[0])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niklas.rosenstein/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/resolver/providers.py", line 200, in _find_candidates
    return self.repository.find_candidates(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niklas.rosenstein/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/models/repositories/base.py", line 176, in find_candidates
    cans = LazySequence(self._find_candidates(requirement, minimal_version=minimal_version))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niklas.rosenstein/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/models/repositories/pypi.py", line 68, in _find_candidates
    for c in finder.find_all_packages(req_name, allow_yanked=requirement.is_pinned)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niklas.rosenstein/.local/pipx/venvs/pdm/lib/python3.12/site-packages/unearth/finder.py", line 315, in find_all_packages
    self._find_packages(package_name, allow_yanked), hashes=hashes or {}
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niklas.rosenstein/.local/pipx/venvs/pdm/lib/python3.12/site-packages/unearth/finder.py", line 295, in _find_packages
    return sorted(all_packages, key=self._sort_key, reverse=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niklas.rosenstein/.local/pipx/venvs/pdm/lib/python3.12/site-packages/unearth/collector.py", line 187, in collect_links_from_location
    yield from _collect_links_from_index(session, location)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niklas.rosenstein/.local/pipx/venvs/pdm/lib/python3.12/site-packages/unearth/collector.py", line 210, in _collect_links_from_index
    page = fetch_page(session, location, headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niklas.rosenstein/.local/pipx/venvs/pdm/lib/python3.12/site-packages/unearth/collector.py", line 195, in fetch_page
    resp = _get_html_response(session, location, headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niklas.rosenstein/.local/pipx/venvs/pdm/lib/python3.12/site-packages/unearth/collector.py", line 234, in _get_html_response
    resp = session.get(
           ^^^^^^^^^^^^
  File "/Users/niklas.rosenstein/.local/pipx/venvs/pdm/lib/python3.12/site-packages/httpx/_client.py", line 1054, in get
    return self.request(
           ^^^^^^^^^^^^^
  File "/Users/niklas.rosenstein/.local/pipx/venvs/pdm/lib/python3.12/site-packages/httpx/_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niklas.rosenstein/.local/pipx/venvs/pdm/lib/python3.12/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niklas.rosenstein/.local/pipx/venvs/pdm/lib/python3.12/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niklas.rosenstein/.local/pipx/venvs/pdm/lib/python3.12/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niklas.rosenstein/.local/pipx/venvs/pdm/lib/python3.12/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niklas.rosenstein/.local/pipx/venvs/pdm/lib/python3.12/site-packages/hishel/_sync/_transports.py", line 197, in handle_request
    regular_response = self._transport.handle_request(request)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/niklas.rosenstein/.local/pipx/venvs/pdm/lib/python3.12/site-packages/httpx/_transports/default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/Users/niklas.rosenstein/.local/pipx/venvs/pdm/lib/python3.12/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: ('“rcgen self signed cert” certificate is not trusted',)
```

</details>

## Steps to reproduce

* Have a Python index with a certificate that your system doesn't trust by default
* Create two entries for it in the PDM `config.toml`, one with `ca_certs` (so PDM will trust it) and one without
  * In the real scenario it's a different index but one is enough to reproduce the issue
    
    Example:
    
    ```toml
    [pypi]
    [pypi.main]
    url = "https://example.com/python-all/simple/"
    username = "niklas.rosenstein"
    ca_certs = "/Users/Shared/corpnet.crt"
    
    [pypi.testing]
    url = "https://example.com/python-testing-all/simple"
    username = "niklas.rosenstein"
    ```

* Create a PDM project that only sources packages from the one with `ca_certs` configured:

    Example:
    
    ```toml
    [[tool.pdm.source]]
    name = "main"
    url = "https://example.com/python-all/simple/"
    ```

* Run `pdm install`

## Actual behavior

You get the following error because of the `testing` source:

```
httpx.ConnectError: ('“rcgen self signed cert” certificate is not trusted',)
```

## Expected behavior

PDM shouldn't care about the `testing` repository. I don't even know why it would want to open a connection to it.

## Environment Information

```bash
❯ pdm info && pdm info --env
PDM version:
  2.17.3
Python Interpreter:
  /Users/niklas.rosenstein/git/kraken-build/kraken/examples/pdm-project/.venv/bin/python (3.12)
Project Root:
  /Users/niklas.rosenstein/git/kraken-build/kraken/examples/pdm-project
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.12.4",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "23.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 23.6.0: Fri Jul  5 17:56:39 PDT 2024; root:xnu-10063.141.1~2/RELEASE_ARM64_T8122",
  "python_full_version": "3.12.4",
  "platform_python_implementation": "CPython",
  "python_version": "3.12",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
> PDM shouldn't care about the `testing` repository.

All configured sources are considered by default, disable those from the config files by setting `pypi.ignore_saved_index`
https://pdm-project.org/en/latest/usage/config/#configure-the-package-indexes
