### ISSUE TITLE
can't add geatpy lib

### ISSUE THREAD

**Issue by lingkerio** [pdm-project/pdm#3093]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

pdm add geatpy -v

## Actual behavior

It seems to be reinstalling all the libraries that are already installed in the current project.

Adding packages to default dependencies: geatpy
  Lock successful.
Changes are written to pyproject.toml.
Synchronizing working set with resolved packages: 111 to add, 0 to update, 0 to remove

  x Install setuptools 72.1.0 failed
  x Install comm 0.2.2 failed
  x Install asttokens 2.4.1 failed
  x Install beautifulsoup4 4.12.3 failed
  x Install argon2-cffi 23.1.0 failed
  x Install argon2-cffi-bindings 21.2.0 failed
  x Install decorator 5.1.1 failed
  x Install anyio 4.4.0 failed
  x Install cycler 0.12.1 failed
  x Install cffi 1.17.0 failed
  x Install async-lru 2.0.4 failed
  x Install arrow 1.3.0 failed
  x Install defusedxml 0.7.1 failed
  x Install certifi 2024.7.4 failed
  x Install attrs 24.2.0 failed
  x Install bleach 6.1.0 failed
  x Install fastjsonschema 2.20.0 failed
  x Install contourpy 1.2.1 failed
  x Install colorama 0.4.6 failed
  x Install charset-normalizer 3.3.2 failed
  x Install executing 2.0.1 failed
  x Install fqdn 1.5.1 failed
  x Install h11 0.14.0 failed
  x Install idna 3.7 failed
  x Install ipykernel 6.29.5 failed
  x Install httpcore 1.0.5 failed
  x Install httpx 0.27.0 failed
  x Install isoduration 20.11.0 failed
  x Install joblib 1.4.2 failed

The full message is too long; it essentially consists of failure messages from reinstalling various libraries, similar to this snippet:
```
add fonttools failed:
Traceback (most recent call last):
  File "D:\Scoop\apps\python\current\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\Scoop\apps\pdm\2.17.3\venv\Lib\site-packages\pdm\installers\synchronizers.py", line 228, in install_candidate
    self.manager.install(can)
  File "D:\Scoop\apps\pdm\2.17.3\venv\Lib\site-packages\pdm\installers\manager.py", line 32, in install
    dist_info = install_wheel(
  File "D:\Scoop\apps\pdm\2.17.3\venv\Lib\site-packages\pdm\installers\installers.py", line 194, in install_wheel
    dist_info_dir = install(source, destination=destination, additional_metadata=additional_metadata)
  File "D:\Scoop\apps\pdm\2.17.3\venv\Lib\site-packages\pdm\installers\installers.py", line 206, in install
    _install(source, destination, additional_metadata=additional_metadata or {})
  File "D:\Scoop\apps\pdm\2.17.3\venv\Lib\site-packages\installer\_core.py", line 109, in install
    record = destination.write_file(
  File "D:\Scoop\apps\pdm\2.17.3\venv\Lib\site-packages\installer\destinations.py", line 207, in write_file
    return self.write_to_fs(scheme, path_, stream, is_executable)
  File "D:\Scoop\apps\pdm\2.17.3\venv\Lib\site-packages\pdm\installers\installers.py", line 122, in write_to_fs
    with open(target_path, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\simple_ds\\.venv\\Lib\\site-packages\\fontTools/__init__.py'
```

## Expected behavior

Normally add the geatpy library.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.17.3
Python Interpreter:
  D:\simple_ds\.venv\Scripts\python.exe (3.12)
Project Root:
  D:/simple_ds
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.12.5",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "11",
  "platform_system": "Windows",
  "platform_version": "10.0.22631",
  "python_full_version": "3.12.5",
  "platform_python_implementation": "CPython",
  "python_version": "3.12",
  "sys_platform": "win32"
}
```

**Comment by frostming** [comment]
This looks very abnormal. Do you think it's possible that PDM can't install even a single package?

Try completely deleting `.venv` and try again.

**Comment by lingkerio** [comment]
> This looks very abnormal. Do you think it's possible that PDM can't install even a single package?
> 
> Try completely deleting `.venv` and try again.

After deleting the .venv folder and running `pdm add geatpy -v` again, the original 111 packages were reinstalled correctly, but geatpy still couldn't be installed.

```
unearth.preparer: Downloading <Link https://pypi.tuna.tsinghua.edu.cn/packages/5a/84/44687a29792a70e111c5c477230a72c4b957d88d16141199bf9acb7537a3/websocket_client-1.8.0-py3-none-any.whl (from https://pypi.tuna.tsinghua.edu.cn/simple/websocket-client/)> (58 kB)
  ✔ Install pygments 2.18.0 successful
  ✔ Install urllib3 2.2.2 successful
  ✔ Install tornado 6.4.1 successful
  ✔ Install websocket-client 1.8.0 successful
unearth.preparer: Downloading <Link https://pypi.tuna.tsinghua.edu.cn/packages/3f/72/305686527c68f33f1dd3ebdd28f53340d372b2f9e44dccaf6f92e17739d3/scipy-1.14.0-cp312-cp312-win_amd64.whl (from https://pypi.tuna.tsinghua.edu.cn/simple/scipy/)> (44.5 MB)
  ✔ Install notebook 7.2.1 successful
  ✔ Install pytz 2024.1 successful
  ✔ Install matplotlib 3.9.1.post1 successful
  ✔ Install pywin32 306 successful
  ✔ Install tzdata 2024.1 successful
  ✔ Install jupyterlab 4.2.4 successful
  ✔ Install babel 2.16.0 successful
  ✔ Install numpy 2.0.1 successful
unearth.preparer: Downloading <Link https://pypi.tuna.tsinghua.edu.cn/packages/e2/7b/8c1b410cd0604cee9a167a19f7e1746f5b92ae7d02ad574ab560b73c5a48/xgboost-2.1.1-py3-none-win_amd64.whl (from https://pypi.tuna.tsinghua.edu.cn/simple/xgboost/)> (124.9 MB)
  ✔ Install scikit-learn 1.5.1 successful
  ✔ Install jedi 0.19.1 successful
  ✔ Install pandas 2.2.2 successful
  ✔ Install statsmodels 0.14.2 successful
  ✔ Install scipy 1.14.0 successful
  ✔ Install xgboost 2.1.1 successful
pdm.termui: Preparing environment(Isolated mode) for PEP 517 build...
pdm.termui: Saving wheel to cache: <Link https://pypi.tuna.tsinghua.edu.cn/packages/6a/be/195167884ff2fb6859cac2f32c8d351db7460df72e15f7afc1a7616b11d3/geatpy-2.4.0.tar.gz (from https://pypi.tuna.tsinghua.edu.cn/simple/geatpy/)>
pdm.termui: Running PEP 517 backend to build a wheel for <Link https://pypi.tuna.tsinghua.edu.cn/packages/6a/be/195167884ff2fb6859cac2f32c8d351db7460df72e15f7afc1a7616b11d3/geatpy-2.4.0.tar.gz (from https://pypi.tuna.tsinghua.edu.cn/simple/geatpy/)>
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   setuptools>=40.8.0
pdm.termui:   wheel
pdm.termui:   python==3.12.5
pdm.termui:   Adding requirement setuptools>=40.8.0
pdm.termui:   Adding requirement wheel
pdm.termui:   Adding requirement python==3.12.5
pdm.termui: ======== Starting round 0 ========
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
pdm.termui: Pinning: setuptools 72.1.0
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
pdm.termui: Pinning: wheel 0.44.0
pdm.termui: ======== Ending round 2 ========
pdm.termui: ======== Starting round 3 ========
pdm.termui: ======== Resolution Result ========
pdm.termui: Stable pins:
pdm.termui:       python None
pdm.termui:   setuptools 72.1.0
pdm.termui:        wheel 0.44.0
pdm.termui: Installing setuptools@72.1.0...
unearth.preparer: Downloading <Link https://pypi.tuna.tsinghua.edu.cn/packages/e1/58/e0ef3b9974a04ce9cde2a7a33881ddcb2d68450803745804545cdd8d258f/setuptools-72.1.0-py3-none-any.whl (from https://pypi.tuna.tsinghua.edu.cn/simple/setuptools/)> (2.3 MB)
pdm.termui: Installing wheel@0.44.0...
unearth.preparer: Downloading <Link https://pypi.tuna.tsinghua.edu.cn/packages/1b/d1/9babe2ccaecff775992753d8686970b1e2755d21c8a63be73aba7a4e7d77/wheel-0.44.0-py3-none-any.whl (from https://pypi.tuna.tsinghua.edu.cn/simple/wheel/)> (67 kB)
pdm.termui: Synchronization complete.
pdm.termui: Traceback (most recent call last):
pdm.termui:   File "D:\Scoop\apps\pdm\2.17.3\venv\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 373, in <module>
pdm.termui:     main()
pdm.termui:   File "D:\Scoop\apps\pdm\2.17.3\venv\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 357, in main
pdm.termui:     json_out["return_val"] = hook(**hook_input["kwargs"])
pdm.termui:                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pdm.termui:   File "D:\Scoop\apps\pdm\2.17.3\venv\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 134, in get_requires_for_build_wheel
pdm.termui:     return hook(config_settings)
pdm.termui:            ^^^^^^^^^^^^^^^^^^^^^
pdm.termui:   File "C:\Users\LINGKE~1\AppData\Local\Temp\pdm-build-env-kv9et68v-shared\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel
pdm.termui:     return self._get_build_requires(config_settings, requirements=[])
pdm.termui:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pdm.termui:   File "C:\Users\LINGKE~1\AppData\Local\Temp\pdm-build-env-kv9et68v-shared\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
pdm.termui:     self.run_setup()
pdm.termui:   File "C:\Users\LINGKE~1\AppData\Local\Temp\pdm-build-env-kv9et68v-shared\Lib\site-packages\setuptools\build_meta.py", line 497, in run_setup
pdm.termui:     super().run_setup(setup_script=setup_script)
pdm.termui:   File "C:\Users\LINGKE~1\AppData\Local\Temp\pdm-build-env-kv9et68v-shared\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
pdm.termui:     exec(code, locals())
pdm.termui:   File "<string>", line 15, in <module>
pdm.termui: ModuleNotFoundError: No module named 'numpy'
  ✖ Install geatpy 2.4.0 failed
pdm.termui: Error occurs:
Traceback (most recent call last):
  File "D:\Scoop\apps\python\current\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Scoop\apps\pdm\2.17.3\venv\Lib\site-packages\pdm\installers\synchronizers.py", line 228, in install_candidate
    self.manager.install(can)
  File "D:\Scoop\apps\pdm\2.17.3\venv\Lib\site-packages\pdm\installers\manager.py", line 33, in install
    prepared.build(),
    ^^^^^^^^^^^^^^^^
  File "D:\Scoop\apps\pdm\2.17.3\venv\Lib\site-packages\pdm\models\candidates.py", line 406, in build
    self._cached = Path(builder.build(build_dir, metadata_directory=self._metadata_dir))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Scoop\apps\pdm\2.17.3\venv\Lib\site-packages\pdm\builders\base.py", line 84, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Scoop\apps\pdm\2.17.3\venv\Lib\site-packages\pdm\builders\wheel.py", line 24, in build
    requires = self._hook.get_requires_for_build_wheel(self.config_settings)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Scoop\apps\pdm\2.17.3\venv\Lib\site-packages\pyproject_hooks\_impl.py", line 196, in get_requires_for_build_wheel
    return self._call_hook(
           ^^^^^^^^^^^^^^^^
  File "D:\Scoop\apps\pdm\2.17.3\venv\Lib\site-packages\pyproject_hooks\_impl.py", line 392, in _call_hook
    self._subprocess_runner(
  File "D:\Scoop\apps\pdm\2.17.3\venv\Lib\site-packages\pdm\builders\base.py", line 281, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Scoop\apps\pdm\2.17.3\venv\Lib\site-packages\pdm\builders\base.py", line 128, in log_subprocessor
    raise build_error(e) from None
pdm.exceptions.BuildError: Build backend raised error: Module 'numpy' is missing, please make sure it is specified in the 'build-system.requires' section. If it is not possible, add it to the project and use '--no-isolation' option.
Showing the last 10 lines of the build output:
    return self._get_build_requires(config_settings, requirements=[])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LINGKE~1\AppData\Local\Temp\pdm-build-env-kv9et68v-shared\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
    self.run_setup()
  File "C:\Users\LINGKE~1\AppData\Local\Temp\pdm-build-env-kv9et68v-shared\Lib\site-packages\setuptools\build_meta.py", line 497, in run_setup
    super().run_setup(setup_script=setup_script)
  File "C:\Users\LINGKE~1\AppData\Local\Temp\pdm-build-env-kv9et68v-shared\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
    exec(code, locals())
  File "<string>", line 15, in <module>
ModuleNotFoundError: No module named 'numpy'
  Retry failed jobs(2/2)
pdm.termui: Preparing environment(Isolated mode) for PEP 517 build...
pdm.termui: Saving wheel to cache: <Link https://pypi.tuna.tsinghua.edu.cn/packages/6a/be/195167884ff2fb6859cac2f32c8d351db7460df72e15f7afc1a7616b11d3/geatpy-2.4.0.tar.gz (from https://pypi.tuna.tsinghua.edu.cn/simple/geatpy/)>
pdm.termui: Running PEP 517 backend to build a wheel for <Link https://pypi.tuna.tsinghua.edu.cn/packages/6a/be/195167884ff2fb6859cac2f32c8d351db7460df72e15f7afc1a7616b11d3/geatpy-2.4.0.tar.gz (from https://pypi.tuna.tsinghua.edu.cn/simple/geatpy/)>
pdm.termui: Traceback (most recent call last):
pdm.termui:   File "D:\Scoop\apps\pdm\2.17.3\venv\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 373, in <module>
pdm.termui:     main()
pdm.termui:   File "D:\Scoop\apps\pdm\2.17.3\venv\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 357, in main
pdm.termui:     json_out["return_val"] = hook(**hook_input["kwargs"])
pdm.termui:                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pdm.termui:   File "D:\Scoop\apps\pdm\2.17.3\venv\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 134, in get_requires_for_build_wheel
pdm.termui:     return hook(config_settings)
pdm.termui:            ^^^^^^^^^^^^^^^^^^^^^
pdm.termui:   File "C:\Users\LINGKE~1\AppData\Local\Temp\pdm-build-env-kv9et68v-shared\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel
pdm.termui:     return self._get_build_requires(config_settings, requirements=[])
pdm.termui:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pdm.termui:   File "C:\Users\LINGKE~1\AppData\Local\Temp\pdm-build-env-kv9et68v-shared\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
pdm.termui:     self.run_setup()
pdm.termui:   File "C:\Users\LINGKE~1\AppData\Local\Temp\pdm-build-env-kv9et68v-shared\Lib\site-packages\setuptools\build_meta.py", line 497, in run_setup
pdm.termui:     super().run_setup(setup_script=setup_script)
pdm.termui:   File "C:\Users\LINGKE~1\AppData\Local\Temp\pdm-build-env-kv9et68v-shared\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
pdm.termui:     exec(code, locals())
pdm.termui:   File "<string>", line 15, in <module>
pdm.termui: ModuleNotFoundError: No module named 'numpy'
  ✖ Install geatpy 2.4.0 failed
pdm.termui: Error occurs:
Traceback (most recent call last):
  File "D:\Scoop\apps\python\current\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Scoop\apps\pdm\2.17.3\venv\Lib\site-packages\pdm\installers\synchronizers.py", line 228, in install_candidate
    self.manager.install(can)
  File "D:\Scoop\apps\pdm\2.17.3\venv\Lib\site-packages\pdm\installers\manager.py", line 33, in install
    prepared.build(),
    ^^^^^^^^^^^^^^^^
  File "D:\Scoop\apps\pdm\2.17.3\venv\Lib\site-packages\pdm\models\candidates.py", line 406, in build
    self._cached = Path(builder.build(build_dir, metadata_directory=self._metadata_dir))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Scoop\apps\pdm\2.17.3\venv\Lib\site-packages\pdm\builders\base.py", line 84, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Scoop\apps\pdm\2.17.3\venv\Lib\site-packages\pdm\builders\wheel.py", line 24, in build
    requires = self._hook.get_requires_for_build_wheel(self.config_settings)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Scoop\apps\pdm\2.17.3\venv\Lib\site-packages\pyproject_hooks\_impl.py", line 196, in get_requires_for_build_wheel
    return self._call_hook(
           ^^^^^^^^^^^^^^^^
  File "D:\Scoop\apps\pdm\2.17.3\venv\Lib\site-packages\pyproject_hooks\_impl.py", line 392, in _call_hook
    self._subprocess_runner(
  File "D:\Scoop\apps\pdm\2.17.3\venv\Lib\site-packages\pdm\builders\base.py", line 281, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Scoop\apps\pdm\2.17.3\venv\Lib\site-packages\pdm\builders\base.py", line 128, in log_subprocessor
    raise build_error(e) from None
pdm.exceptions.BuildError: Build backend raised error: Module 'numpy' is missing, please make sure it is specified in the 'build-system.requires' section. If it is not possible, add it to the project and use '--no-isolation' option.
Showing the last 10 lines of the build output:
    return self._get_build_requires(config_settings, requirements=[])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LINGKE~1\AppData\Local\Temp\pdm-build-env-kv9et68v-shared\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
    self.run_setup()
  File "C:\Users\LINGKE~1\AppData\Local\Temp\pdm-build-env-kv9et68v-shared\Lib\site-packages\setuptools\build_meta.py", line 497, in run_setup
    super().run_setup(setup_script=setup_script)
  File "C:\Users\LINGKE~1\AppData\Local\Temp\pdm-build-env-kv9et68v-shared\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
    exec(code, locals())
  File "<string>", line 15, in <module>
ModuleNotFoundError: No module named 'numpy'
  ✖ Some package operations failed.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Scoop\apps\pdm\current\venv\Scripts\pdm.exe\__main__.py", line 7, in <module>
  File "D:\Scoop\apps\pdm\2.17.3\venv\Lib\site-packages\pdm\core.py", line 346, in main
    return core.main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Scoop\apps\pdm\2.17.3\venv\Lib\site-packages\pdm\core.py", line 264, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "D:\Scoop\apps\pdm\2.17.3\venv\Lib\site-packages\pdm\core.py", line 259, in main
    self.handle(project, options)
  File "D:\Scoop\apps\pdm\2.17.3\venv\Lib\site-packages\pdm\core.py", line 195, in handle
    command.handle(project, options)
  File "D:\Scoop\apps\pdm\2.17.3\venv\Lib\site-packages\pdm\cli\commands\add.py", line 71, in handle
    self.do_add(
  File "D:\Scoop\apps\pdm\2.17.3\venv\Lib\site-packages\pdm\cli\commands\add.py", line 177, in do_add
    do_sync(
  File "D:\Scoop\apps\pdm\2.17.3\venv\Lib\site-packages\pdm\cli\actions.py", line 330, in do_sync
    synchronizer.synchronize()
  File "D:\Scoop\apps\pdm\2.17.3\venv\Lib\site-packages\pdm\installers\synchronizers.py", line 425, in synchronize
    raise InstallationError("Some package operations failed.")
pdm.exceptions.InstallationError: Some package operations failed.
```

**Comment by lingkerio** [comment]
> This looks very abnormal. Do you think it's possible that PDM can't install even a single package?
> 
> Try completely deleting `.venv` and try again.

That's exactly what I find strange. PDM shouldn't have any special behavior when installing an evolutionary algorithm library like this one. However, this issue only occurs with this particular library. In fact, this is already my second attempt at recreating the environment.

**Comment by frostming** [comment]
> However, this issue only occurs with this particular library

So it should be concluded that the problem lies with this package, right?

In fact, `geatpy` is using several external libraries at build time but didn't declare them in a PEP 517 manner, which is the only build mechanism supported by PDM. The requirements include `numpy` and `cython`.

To make it work, add `numpy` and `cython` to your `pyproject.toml` dependencies list and run `pdm add geatpy --no-isolation`, but you still need luck because the package was published 5 years ago.

**Comment by frostming** [comment]
> Well, my project already has numpy installed, but it's still indicating that numpy cannot be found...

Did you use the `--no-isolation` option?



> Maybe I should consider not using it?

Sure thing.

**Comment by lingkerio** [comment]
> > Well, my project already has numpy installed, but it's still indicating that numpy cannot be found...
> 
> Did you use the `--no-isolation` option?

With this option added, it recognizes correctly now. Oh, sorry, I didn't observe carefully when I added this option earlier.
