### ISSUE TITLE
Missing Python.h when building custom Cuda Kernel

### ISSUE THREAD

**Issue by KukumavMozolo** [pdm-project/pdm#3116]
- [ x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Write Custom Cuda kernel following this tutorial: https://pytorch.org/tutorials/advanced/cpp_extension.html

Create setup.py
try to import it via `npm import setup.py`
run `npm build`

## Actual behavior
Build fails because Python.h can not be found 

## Expected behavior
Build succedes

## Environment Information

```bash
PDM version:
  2.18.1
Python Interpreter:
  /home/kukumav/vscode_projects/pytorch_sparse_addons/.venv/bin/python (3.11)
Project Root:
  /home/kukumav/vscode_projects/pytorch_sparse_addons
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.12",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.8.0-40-generic",
  "platform_system": "Linux",
  "platform_version": "#40~22.04.3-Ubuntu SMP PREEMPT_DYNAMIC Tue Jul 30 17:30:19 UTC 2",
  "python_full_version": "3.11.9",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "linux"
}

```
If necessary i can provide a better example, atm i fail to understand why Python.h can not be found since `pip install .` succeeds.

**Comment by pawamoy** [comment]
This bug report is a bit light. I don't think it's a PDM issue anyway. Have you installed Python headers on your system? https://stackoverflow.com/a/21530768/3451029

**Comment by KukumavMozolo** [comment]
That might well be the case, however i am out of clue what it might be since `pip install . ` works, e.g. it can find the python headers.

**Comment by pawamoy** [comment]
> I will try to construct a minimal example tomorrow.

Thank you, that's probably the best thing to do :)

**Comment by KukumavMozolo** [comment]
So here is the minimal example:
created a dir test_pdm with files: 
test_pdm
 -test.cpp
 -setup.py

test.cpp:
```c++
#include <torch/extension.h>


torch::Tensor test_func(){
    std::cout << "Hello World!";
}



PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
  m.def("cdist", &test_func, "test bind");
}

```

setup.py
```python
from setuptools import setup
from torch.utils.cpp_extension import BuildExtension, CUDAExtension



setup(
    name='cdist',
    ext_modules=[
        CUDAExtension('test_extension', [
            'test.cpp'
        ])
    ],
    cmdclass={
        'build_ext': BuildExtension
    })

```

console output from running `pdm init`:
```bash
➜  test_pdm pdm init
Creating a pyproject.toml for PDM...
Please enter the Python interpreter to use
 0. cpython@3.10 (/usr/bin/python3)
 1. cpython@3.11 (/home/kukumav/vscode_projects/test_pdm/.venv/bin/python)
 2. cpython@3.11 (/usr/bin/python3.11)
 3. cpython@3.11 (/usr/local/bin/python3.11)
 4. cpython@3.10 (/usr/bin/python3.10)
 5. cpython@3.9 (/usr/bin/python3.9)
 6. cpython@3.8 (/usr/bin/python3.8)
Please select (0): 2
Virtualenv is created successfully at /home/kukumav/vscode_projects/test_pdm/.venv
Project name (test_pdm): 
Project version (0.1.0): 
Do you want to build this project for distribution(such as wheel)?
If yes, it will be installed by default when running `pdm install`. [y/n] (n): y
Project description (): 
Which build backend to use?
0. pdm-backend
1. setuptools
2. flit-core
3. hatchling
Please select (0): 1
License(SPDX name) (MIT): 
Author name (): 
Author email (kukumav@example.com): 
Python requires('*' to allow any) (>=3.11): 
Project is initialized successfully
Found following files from other formats that you may import:
0. /home/kukumav/vscode_projects/test_pdm/setup.py (setuppy)
1. don't do anything, I will import later.
Please select: 0
Traceback (most recent call last):
  File "/home/kukumav/.local/lib/python3.10/site-packages/pdm/models/in_process/parse_setup.py", line 219, in <module>
    json.dump(parse_setup(sys.argv[1]), f, default=json_default)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kukumav/.local/lib/python3.10/site-packages/pdm/models/in_process/parse_setup.py", line 181, in parse_setup
    raise RuntimeError(
RuntimeError: setuptools is required to convert setup.py, install it by `pdm add setuptools`
[CalledProcessError]: Command '['/home/kukumav/vscode_projects/test_pdm/.venv/bin/python', '-Es', '/home/kukumav/.local/lib/python3.10/site-packages/pdm/models/in_process/parse_setup.py', 
'/home/kukumav/vscode_projects/test_pdm', '/tmp/tmpssyoegw4.json']' returned non-zero exit status 1.
WARNING: Add '-v' to see the detailed traceback
```

this will create the following pyproject.toml:

```
[project]
name = "test_pdm"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "", email = "kukumav@example.com"},
]
dependencies = []
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"


[tool.pdm]
distribution = true
```
pdm complains about missing setuptools and after running `pdm add setuptools` it will complain that torch is missing from the `[build-system] requires` section in the pyproject.toml

So changing pyproject.toml as follows:
```
[project]
name = "test_pdm"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "", email = "kukumav@example.com"},
]
dependencies = []
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["setuptools>=61", "wheel", "torch"]
build-backend = "setuptools.build_meta"


[tool.pdm]
distribution = true

```

and then as told by pdm running: `pdm add setuptools`
```bash
➜  test_pdm pdm add setuptools
Adding packages to default dependencies: setuptools
  0:00:00 🔒 Lock successful.  
Changes are written to pyproject.toml.
Synchronizing working set with resolved packages: 1 to add, 0 to update, 0 to remove

  ✔ Install setuptools 73.0.0 successful
  ✖ Install test_pdm 0.1.0 failed

  0:00:00 Installing the project as an editable package... 1/1
See /home/kukumav/.local/state/pdm/log/pdm-install-1syso7xg.log for detailed debug log.
[BuildError]: Build backend raised error: Showing the last 10 lines of the build output:
  File "/tmp/pdm-build-env-lhkn66uw-shared/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 557, in build_extension
    objects = self.compiler.compile(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/pdm-build-env-lhkn66uw-shared/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 679, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/tmp/pdm-build-env-lhkn66uw-shared/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1785, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/tmp/pdm-build-env-lhkn66uw-shared/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 2121, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
WARNING: Add '-v' to see the detailed traceback
```

the log is to long to post it here unfortunatelly
it contains the following errors:

not sure this is relevant
```
unearth.utils: Couldn't parse netrc because of FileNotFoundError: [Errno 2] No such file or directory: '/home/kukumav/.netrc'
```

```
pdm.termui: [1/1] c++ -MMD -MF /tmp/tmpok5js7s4.build-temp/test.o.d -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/tmp/pdm-build-env-lhkn66uw-shared/lib/python3.11/site-packages/torch/include -I/tmp/pdm-build-env-lhkn66uw-shared/lib/python3.11/site-packages/torch/include/torch/csrc/api/include -I/tmp/pdm-build-env-lhkn66uw-shared/lib/python3.11/site-packages/torch/include/TH -I/tmp/pdm-build-env-lhkn66uw-shared/lib/python3.11/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/kukumav/vscode_projects/test_pdm/.venv/include -I/usr/include/python3.11 -c -c /home/kukumav/vscode_projects/test_pdm/test.cpp -o /tmp/tmpok5js7s4.build-temp/test.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=test_extension -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17
pdm.termui: FAILED: /tmp/tmpok5js7s4.build-temp/test.o 
pdm.termui: c++ -MMD -MF /tmp/tmpok5js7s4.build-temp/test.o.d -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/tmp/pdm-build-env-lhkn66uw-shared/lib/python3.11/site-packages/torch/include -I/tmp/pdm-build-env-lhkn66uw-shared/lib/python3.11/site-packages/torch/include/torch/csrc/api/include -I/tmp/pdm-build-env-lhkn66uw-shared/lib/python3.11/site-packages/torch/include/TH -I/tmp/pdm-build-env-lhkn66uw-shared/lib/python3.11/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/kukumav/vscode_projects/test_pdm/.venv/include -I/usr/include/python3.11 -c -c /home/kukumav/vscode_projects/test_pdm/test.cpp -o /tmp/tmpok5js7s4.build-temp/test.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=test_extension -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17
pdm.termui: In file included from /tmp/pdm-build-env-lhkn66uw-shared/lib/python3.11/site-packages/torch/include/torch/csrc/Device.h:4,
pdm.termui:                  from /tmp/pdm-build-env-lhkn66uw-shared/lib/python3.11/site-packages/torch/include/torch/csrc/api/include/torch/python.h:8,
pdm.termui:                  from /tmp/pdm-build-env-lhkn66uw-shared/lib/python3.11/site-packages/torch/include/torch/extension.h:9,
pdm.termui:                  from /home/kukumav/vscode_projects/test_pdm/test.cpp:1:
pdm.termui: /tmp/pdm-build-env-lhkn66uw-shared/lib/python3.11/site-packages/torch/include/torch/csrc/python_headers.h:12:10: fatal error: Python.h: No such file or directory
pdm.termui:    12 | #include <Python.h>
pdm.termui:       |          ^~
```

and testing if `pip install .` works:
```
➜  test_pdm pip install .     
Defaulting to user installation because normal site-packages is not writeable
Processing /home/kukumav/vscode_projects/test_pdm
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: cdist
  Building wheel for cdist (pyproject.toml) ... done
  Created wheel for cdist: filename=cdist-0.0.0-cp310-cp310-linux_x86_64.whl size=2553517 sha256=cc19d9657ee11c1d087224703ae4273ac2b99790aabccc35537bcf418bd62947
  Stored in directory: /tmp/pip-ephem-wheel-cache-oa_5dnu5/wheels/f7/97/43/1b6b6e65aff4df1861a1b1c1041ab36c322bce829b1465d28c
Successfully built cdist
Installing collected packages: cdist
  Attempting uninstall: cdist
    Found existing installation: cdist 0.0.0
    Uninstalling cdist-0.0.0:
      Successfully uninstalled cdist-0.0.0
Successfully installed cdist-0.0.0
```
apparently it does /:

**Comment by frostming** [comment]
I created the directory with the following files:

```
test_pdm
-test.cpp
-setup.py
- pyproject.toml
```
Use the same content as you give. Run `pdm install`, everything works fine

**Comment by KukumavMozolo** [comment]
ok that seems to succeed(after adding README.md manually) but it seems `test.cpp` doesnt get compiled?

**Comment by frostming** [comment]
> ok that seems to succeed but it seems `test.cpp` doesnt get compiled?

```
~/wkspace$ ls
pdm.lock  pyproject.toml  setup.py   test.cpp  test_extension.cpython-311-x86_64-linux-gnu.so  test_pdm.egg-info
```

**Comment by frostming** [comment]
A possible reason is you used different interpreter when using pdm and pip and the one used by pdm is missing the header files. You can see the interpreter being used by:

```
# pdm
pdm info
# pip
pip --version
```

**Comment by KukumavMozolo** [comment]
Thank you very much for your time and effort!
