### ISSUE TITLE
Cannot resolve/add pdoc3: "distlib.metadata.MetadataConflictError: Unknown metadata set"

### ISSUE THREAD

**Issue by blueyed** [pdm-project/pdm#312]
I've noticed that adding/resolving [pdoc3](https://pypi.org/project/pdoc3/) fails:

```
% pdm add pdoc3 -v
Adding packages to default dependencies: pdoc3
======== Start resolving requirements ========
	pdoc3
	Adding requirement pdoc3
Using cached wheel link: file:///home/user/.cache/pdm/wheels/0e/cf/76/780013262201c933d30b0f3f24c3e261519577cc45661fa8d6/pdoc3-0.9.2-py3-none-any.whl
Traceback (most recent call last):
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/distlib/metadata.py", line 675, in __init__
    self._data = json.loads(data)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "…/Vcs/pdm/.venv/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/pdm/core.py", line 76, in __call__
    return self.main(*args, **kwargs)
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/pdm/core.py", line 131, in main
    raise err.with_traceback(traceback)
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/pdm/core.py", line 127, in main
    f(options.project, options)
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/pdm/cli/commands/add.py", line 35, in handle
    actions.do_add(
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/pdm/cli/actions.py", line 175, in do_add
    resolved = do_model1(project, strategy, tracked_names, reqs)
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/pdm/cli/actions.py", line 70, in do_model1
    mapping, dependencies, summaries = resolve(
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/pdm/resolver/core.py", line 152, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/resolvelib/resolvers.py", line 453, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/resolvelib/resolvers.py", line 347, in resolve
    failure_causes = self._attempt_to_pin_criterion(name, criterion)
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/resolvelib/resolvers.py", line 207, in _attempt_to_pin_criterion
    criteria = self._get_criteria_to_update(candidate)
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/resolvelib/resolvers.py", line 198, in _get_criteria_to_update
    for r in self._p.get_dependencies(candidate):
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/pdm/resolver/providers.py", line 77, in get_dependencies
    deps, requires_python, summary = self.repository.get_dependencies(candidate)
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/pdm/models/repositories.py", line 64, in get_dependencies
    requirements, requires_python, summary = getter(candidate)
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/pdm/models/repositories.py", line 30, in wrapper
    result = func(self, candidate)
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/pdm/models/repositories.py", line 141, in _get_dependencies_from_metadata
    deps = candidate.get_dependencies_from_metadata()
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/pdm/models/candidates.py", line 201, in get_dependencies_from_metadata
    metadata = self.get_metadata()
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/pdm/models/candidates.py", line 169, in get_metadata
    self.metadata = self.wheel.metadata
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/distlib/util.py", line 446, in __get__
    value = self.func(obj)
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/distlib/wheel.py", line 237, in metadata
    result = Metadata(fileobj=wf)
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/distlib/metadata.py", line 686, in __init__
    self.validate()
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/distlib/metadata.py", line 903, in validate
    missing, warnings = self._legacy.check(True)
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/distlib/metadata.py", line 503, in check
    self.set_metadata_version()
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/distlib/metadata.py", line 265, in set_metadata_version
    self._fields['Metadata-Version'] = _best_version(self._fields)
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/distlib/metadata.py", line 169, in _best_version
    raise MetadataConflictError('Unknown metadata set')
distlib.metadata.MetadataConflictError: Unknown metadata set
```

pyproject.toml:
```toml
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "…", email = "…"},
]
dependencies = []
dev-dependencies = []
requires-python = ">=3.9"
dynamic = ["classifiers"]
license = {text = "MIT"}

[project.urls]
homepage = ""

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"
```

```
126     def _best_version(fields):
127         """Detect the best version depending on the fields used."""
128         def _has_marker(keys, markers):
129             for marker in markers:
130                 if marker in keys:
131                     return True
132             return False
133     
134         keys = []
135         for key, value in fields.items():
136             if value in ([], 'UNKNOWN', None):
137                 continue
138             keys.append(key)
139     
140         possible_versions = ['1.0', '1.1', '1.2', '1.3', '2.0', '2.1']
141     
142         # first let's try to see if a field is not part of one of the version
143         for key in keys:
144             if key not in _241_FIELDS and '1.0' in possible_versions:
145                 possible_versions.remove('1.0')
146                 logger.debug('Removed 1.0 due to %s', key)
147             if key not in _314_FIELDS and '1.1' in possible_versions:
148                 possible_versions.remove('1.1')
149                 logger.debug('Removed 1.1 due to %s', key)
150             if key not in _345_FIELDS and '1.2' in possible_versions:
151                 possible_versions.remove('1.2')
152                 logger.debug('Removed 1.2 due to %s', key)
153             if key not in _566_FIELDS and '1.3' in possible_versions:
154                 possible_versions.remove('1.3')
155                 logger.debug('Removed 1.3 due to %s', key)
156             if key not in _566_FIELDS and '2.1' in possible_versions:
157                 if key != 'Description':  # In 2.1, description allowed after headers
158                     possible_versions.remove('2.1')
159                     logger.debug('Removed 2.1 due to %s', key)
160             if key not in _426_FIELDS and '2.0' in possible_versions:
161                 possible_versions.remove('2.0')
162                 logger.debug('Removed 2.0 due to %s', key)
163     
164         # possible_version contains qualified versions
165         if len(possible_versions) == 1:
166             return possible_versions[0]   # found !
167         elif len(possible_versions) == 0:
168             logger.debug('Out of options - unknown metadata set: %s', fields)
169  ->         raise MetadataConflictError('Unknown metadata set')                                                                                                                                                  
…
(Pdb++) fields.keys()
dict_keys(['Metadata-Version', 'License', 'Obsoletes', 'Project-URL', 'Classifier', 'Home-page', 'Summary', 'Provides', 'Requires-Dist', 'Description-Content-Type', 'Requires-Python', 'Version', 'Platform', 'Name', 'Description'])
```

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.4.3.dev2+g58eab22                          
Python Interpreter: /home/user/Vcs/pdm/.venv/bin/python (3.9.2)
Project Root:       /home/user/Vcs/pdm/t                       
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.2",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.11.6-arch1-1",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT Thu, 11 Mar 2021 13:48:23 +0000",
  "python_full_version": "3.9.2",
  "platform_python_implementaiton": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
> dict_keys(['Metadata-Version', 'License', 'Obsoletes', 'Project-URL', 'Classifier', 'Home-page', 'Summary', 'Provides', 'Requires-Dist', 'Description-Content-Type', 'Requires-Python', 'Version', 'Platform', 'Name', 'Description'])

The wheel builder produces a `Obsoletes` field in the `METADATA` that is introduced in [PEP-314] and deprecated in [PEP-345], and the Metadata v2.1 ([PEP-566]) version drops the support(at least in `distlib`). It looks that there should be some fix in one of (`distlib`, `setuptools` or `wheel`). What do you think?

[PEP-314]: https://www.python.org/dev/peps/pep-0314/
[PEP-345]: https://www.python.org/dev/peps/pep-0345/
[PEP-566]: https://www.python.org/dev/peps/pep-0566/

**Comment by frostming** [comment]
Hmm, I think it's `setuptools` that takes it wrong, `wheel` just converts `PKGINFO` to `METADATA` while those deprecated fields are kept unchanged.

**Comment by blueyed** [comment]
I cannot really advice there, thanks for looking into it already!
When debugging it quickly it seemed like using a strict check (via the legacy method) in distlib might be something to question/avoid maybe: https://bitbucket.org/pypa/distlib/src/4f54a3117db58f6bb00c69ab9a892170b91acd3b/distlib/metadata.py#lines-905

**Comment by blueyed** [comment]
This works by now using PDM 1.8.0 with setuptools 57.4.0, closing.
