### ISSUE TITLE
ModuleNotFoundError: No module named 'dep_logic' with new pdm 2.19.0 release

### ISSUE THREAD

**Issue by toppk** [pdm-project/pdm#3178]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

```shell 
echo rm -rf .venv # start with empty venv
pdm sync
```
I think there's a chicken and egg problem here, where the .venv cannot be bootstrapped due to missing dep_logic module.

Probably related to this:

https://github.com/pdm-project/pdm/pull/3176

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
$ pdm info
PDM version:
  2.19.0
Python Interpreter:
  /home/toppk/workspace/ratetick/pygrid/.venv/bin/python (3.11)
Project Root:
  /home/toppk/workspace/ratetick/pygrid
Local Packages:
$ pdm info --env
Traceback (most recent call last):
  File "/home/toppk/.local/lib/python3.11/site-packages/pdm/models/in_process/env_spec.py", line 24, in <module>
    print(json.dumps(get_current_env_spec(sys.argv[1]), indent=2))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/toppk/.local/lib/python3.11/site-packages/pdm/models/in_process/env_spec.py", line 12, in get_current_env_spec
    from dep_logic.tags import Platform
ModuleNotFoundError: No module named 'dep_logic'
[CalledProcessError]: Command 
'['/home/toppk/workspace/ratetick/pygrid/.venv/bin/python', '-EsS', 
'/home/toppk/.local/lib/python3.11/site-packages/pdm/models/in_process/env_spec.
py', '/usr/local/lib/python3.11/site-packages']' returned non-zero exit status 
1.
WARNING: Add '-v' to see the detailed traceback

```

**Comment by frostming** [comment]
I can't reproduce locally. Can you make a clean docker environment for reproduction?

And `dep_logic` should exist under `/home/toppk/.local/lib/python3.11/site-packages/` and the path is loaded here: https://github.com/pdm-project/pdm/blob/1dc5f69aa65604fd2b973cfe5ad2f9a40c95d9b9/src/pdm/models/in_process/env_spec.py#L11

Can you help make me more clear since the above doesn't make sense.

**Comment by frostming** [comment]
Fine, you are installing pdm into user site and the path is not loaded
