### ISSUE TITLE
Build editable broken with new version 2.19.1

### ISSUE THREAD

**Issue by sdeframond-lowit** [pdm-project/pdm#3180]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

I have a project `my-project` setup as a monorepo. The main package depends on another one named `my-dependency`.

Since today, PDM fail to install the main package with a erro related to `pyproject_hooks._impl.HookMissing: build_editable` (see below).

Here the relevant part of `my-project/my-main-package/pyproject.toml`:
```toml
[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "-e file:///${PROJECT_ROOT}/../my-dependency#egg=my-dependency",
]
```

## Actual behavior

```
$ pdm install -v
STATUS: Resolving packages from lockfile...
Synchronizing working set with resolved packages: 0 to add, 1 to update, 0 to remove

pdm.termui: Overwriting distribution my-dependency
pdm.termui: Preparing environment(Isolated mode) for PEP 517 build...
pdm.termui: Running PEP 517 backend to build a wheel for <Link file:///home/sdeframond/my-project/my-dependency (from None)>
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   Adding requirement python==3.11.5
pdm.termui:   Adding requirement setuptools==63.4.3
pdm.termui:   Adding requirement setuptools-scm
pdm.termui:   Adding requirement packaging>=20(from setuptools-scm 8.1.0)
pdm.termui:   Adding requirement setuptools(from setuptools-scm 8.1.0)
pdm.termui: ======== Resolution Result ========
pdm.termui:           python None
pdm.termui:       setuptools 63.4.3
pdm.termui:   setuptools-scm 8.1.0
pdm.termui:        packaging 24.1
pdm.termui: Fetching hashes for packaging@24.1
pdm.termui: Fetching hashes for setuptools-scm@8.1.0
pdm.termui: Fetching hashes for setuptools@63.4.3
pdm.termui: Installing packaging@24.1...
pdm.termui: Using cached response for https://files.pythonhosted.org/packages/08/aa/cc0199a5f0ad350994d660967a8efb233fe0416e4639146c089643407ce6/packaging-24.1-py3-none-any.whl
unearth.preparer: Downloading <Link https://files.pythonhosted.org/packages/08/aa/cc0199a5f0ad350994d660967a8efb233fe0416e4639146c089643407ce6/packaging-24.1-py3-none-any.whl (from https://pypi.org/simple/packaging/)> (53 kB)
pdm.termui: Installing setuptools@63.4.3...
pdm.termui: Using cached response for https://files.pythonhosted.org/packages/2a/a3/49c29680d6118273b992b40ebe881e8e899b8e26a4e951f37f223da8f862/setuptools-63.4.3-py3-none-any.whl
unearth.preparer: Downloading <Link https://files.pythonhosted.org/packages/2a/a3/49c29680d6118273b992b40ebe881e8e899b8e26a4e951f37f223da8f862/setuptools-63.4.3-py3-none-any.whl (from https://pypi.org/simple/setuptools/)> (1.2 MB)
pdm.termui: Installing setuptools-scm@8.1.0...
pdm.termui: Using cached response for https://files.pythonhosted.org/packages/a0/b9/1906bfeb30f2fc13bb39bf7ddb8749784c05faadbd18a21cf141ba37bff2/setuptools_scm-8.1.0-py3-none-any.whl
unearth.preparer: Downloading <Link https://files.pythonhosted.org/packages/a0/b9/1906bfeb30f2fc13bb39bf7ddb8749784c05faadbd18a21cf141ba37bff2/setuptools_scm-8.1.0-py3-none-any.whl (from https://pypi.org/simple/setuptools-scm/)> (43 kB)
pdm.termui: Synchronization complete.
  ✖ Update my-dependency 1.0.0 -> 1.0.0 failed
pdm.termui: Error occurs:
Traceback (most recent call last):
  File "/home/sdeframond/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/builders/base.py", line 84, in wrapper
    return func(*args, **kwargs)
  File "/home/sdeframond/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/builders/editable.py", line 26, in build
    filename = self._hook.build_editable(out_dir, self.config_settings, metadata_directory)
  File "/home/sdeframond/.local/share/pdm/venv/lib/python3.10/site-packages/pyproject_hooks/_impl.py", line 270, in build_editable
    return self._call_hook('build_editable', {
  File "/home/sdeframond/.local/share/pdm/venv/lib/python3.10/site-packages/pyproject_hooks/_impl.py", line 329, in _call_hook
    raise HookMissing(data.get('missing_hook_name') or hook_name)
pyproject_hooks._impl.HookMissing: build_editable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sdeframond/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 189, in synchronize
    handlers[kind](key, status.progress)
  File "/home/sdeframond/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 50, in update_candidate
    self.manager.overwrite(dist, can)
  File "/home/sdeframond/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/installers/manager.py", line 62, in overwrite
    installed = self.install(candidate)
  File "/home/sdeframond/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/installers/manager.py", line 33, in install
    prepared.build(),
  File "/home/sdeframond/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/models/candidates.py", line 411, in build
    self._cached = Path(builder.build(build_dir, metadata_directory=self._metadata_dir))
  File "/home/sdeframond/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/builders/base.py", line 86, in wrapper
    raise BuildError(str(e)) from e
pdm.exceptions.BuildError: build_editable
  Retry failed jobs(2/2)
pdm.termui: Overwriting distribution my-dependency
pdm.termui: Preparing environment(Isolated mode) for PEP 517 build...
pdm.termui: Running PEP 517 backend to build a wheel for <Link file:///home/sdeframond/my-project/my-dependency (from None)>
  ✖ Update my-dependency 1.0.0 -> 1.0.0 failed
pdm.termui: Error occurs:
Traceback (most recent call last):
  File "/home/sdeframond/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/builders/base.py", line 84, in wrapper
    return func(*args, **kwargs)
  File "/home/sdeframond/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/builders/editable.py", line 26, in build
    filename = self._hook.build_editable(out_dir, self.config_settings, metadata_directory)
  File "/home/sdeframond/.local/share/pdm/venv/lib/python3.10/site-packages/pyproject_hooks/_impl.py", line 270, in build_editable
    return self._call_hook('build_editable', {
  File "/home/sdeframond/.local/share/pdm/venv/lib/python3.10/site-packages/pyproject_hooks/_impl.py", line 329, in _call_hook
    raise HookMissing(data.get('missing_hook_name') or hook_name)
pyproject_hooks._impl.HookMissing: build_editable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sdeframond/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 189, in synchronize
    handlers[kind](key, status.progress)
  File "/home/sdeframond/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 50, in update_candidate
    self.manager.overwrite(dist, can)
  File "/home/sdeframond/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/installers/manager.py", line 62, in overwrite
    installed = self.install(candidate)
  File "/home/sdeframond/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/installers/manager.py", line 33, in install
    prepared.build(),
  File "/home/sdeframond/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/models/candidates.py", line 411, in build
    self._cached = Path(builder.build(build_dir, metadata_directory=self._metadata_dir))
  File "/home/sdeframond/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/builders/base.py", line 86, in wrapper
    raise BuildError(str(e)) from e
pdm.exceptions.BuildError: build_editable
  ✖ Some package operations failed.
Traceback (most recent call last):
  File "/home/sdeframond/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/sdeframond/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/core.py", line 378, in main
    return core.main(args or sys.argv[1:])
  File "/home/sdeframond/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/core.py", line 267, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/home/sdeframond/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/core.py", line 262, in main
    self.handle(project, options)
  File "/home/sdeframond/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/core.py", line 194, in handle
    command.handle(project, options)
  File "/home/sdeframond/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/cli/commands/install.py", line 103, in handle
    actions.do_sync(
  File "/home/sdeframond/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/cli/actions.py", line 301, in do_sync
    synchronizer.synchronize()
  File "/home/sdeframond/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 226, in synchronize
    raise InstallationError("Some package operations failed.")
pdm.exceptions.InstallationError: Some package operations failed.
```

## Expected behavior

Same as with version 2.18.2:

```
$ pdm install -v
STATUS: Resolving packages from lockfile...
STATUS: Fetching hashes for resolved packages...
Synchronizing working set with resolved packages: 0 to add, 1 to update, 0 to remove

pdm.termui: Overwriting distribution my-dependency
pdm.termui: Preparing environment(Isolated mode) for PEP 517 build...
pdm.termui: Running PEP 517 backend to build a wheel for <Link file:///home/sdeframond/my-project/my-dependency (from None)>
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   Adding requirement setuptools==63.4.3
pdm.termui:   Adding requirement setuptools-scm
pdm.termui:   Adding requirement python==3.11.5
pdm.termui:   Adding requirement packaging>=20(from setuptools-scm 8.1.0)
pdm.termui:   Adding requirement setuptools(from setuptools-scm 8.1.0)
pdm.termui: ======== Resolution Result ========
pdm.termui:           python None
pdm.termui:       setuptools 63.4.3
pdm.termui:   setuptools-scm 8.1.0
pdm.termui:        packaging 24.1
pdm.termui: Installing packaging@24.1...
pdm.termui: Using cached response for https://files.pythonhosted.org/packages/08/aa/cc0199a5f0ad350994d660967a8efb233fe0416e4639146c089643407ce6/packaging-24.1-py3-none-any.whl
unearth.preparer: Downloading <Link https://files.pythonhosted.org/packages/08/aa/cc0199a5f0ad350994d660967a8efb233fe0416e4639146c089643407ce6/packaging-24.1-py3-none-any.whl (from https://pypi.org/simple/packaging/)> (53 kB)
pdm.termui: Installing setuptools@63.4.3...
pdm.termui: Using cached response for https://files.pythonhosted.org/packages/2a/a3/49c29680d6118273b992b40ebe881e8e899b8e26a4e951f37f223da8f862/setuptools-63.4.3-py3-none-any.whl
unearth.preparer: Downloading <Link https://files.pythonhosted.org/packages/2a/a3/49c29680d6118273b992b40ebe881e8e899b8e26a4e951f37f223da8f862/setuptools-63.4.3-py3-none-any.whl (from https://pypi.org/simple/setuptools/)> (1.2 MB)
pdm.termui: Installing setuptools-scm@8.1.0...
pdm.termui: Using cached response for https://files.pythonhosted.org/packages/a0/b9/1906bfeb30f2fc13bb39bf7ddb8749784c05faadbd18a21cf141ba37bff2/setuptools_scm-8.1.0-py3-none-any.whl
unearth.preparer: Downloading <Link https://files.pythonhosted.org/packages/a0/b9/1906bfeb30f2fc13bb39bf7ddb8749784c05faadbd18a21cf141ba37bff2/setuptools_scm-8.1.0-py3-none-any.whl (from https://pypi.org/simple/setuptools-scm/)> (43 kB)
pdm.termui: Synchronization complete.
pdm.termui: The build backend doesn't support PEP 660, falling back to setuptools-pep660
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   Adding requirement setuptools-pep660
pdm.termui:   Adding requirement python==3.11.5
pdm.termui:   Adding requirement setuptools<61,>=42(from setuptools-pep660 0.1.4)
pdm.termui:   Adding requirement wheel(from setuptools-pep660 0.1.4)
pdm.termui: ======== Resolution Result ========
pdm.termui:              python None
pdm.termui:   setuptools-pep660 0.1.4
pdm.termui:          setuptools 60.10.0
pdm.termui:               wheel 0.44.0
pdm.termui: Installing setuptools@60.10.0...
pdm.termui: Using cached response for https://files.pythonhosted.org/packages/7c/5b/3d92b9f0f7ca1645cba48c080b54fe7d8b1033a4e5720091d1631c4266db/setuptools-60.10.0-py3-none-any.whl
unearth.preparer: Downloading <Link https://files.pythonhosted.org/packages/7c/5b/3d92b9f0f7ca1645cba48c080b54fe7d8b1033a4e5720091d1631c4266db/setuptools-60.10.0-py3-none-any.whl (from https://pypi.org/simple/setuptools/)> (1.1 MB)
pdm.termui: Installing setuptools-pep660@0.1.4...
pdm.termui: Using cached response for https://files.pythonhosted.org/packages/cf/94/5a0ec01ef048a781b603976fed7c7c2669674f975dd905199be9277e0eea/setuptools_pep660-0.1.4-py3-none-any.whl
unearth.preparer: Downloading <Link https://files.pythonhosted.org/packages/cf/94/5a0ec01ef048a781b603976fed7c7c2669674f975dd905199be9277e0eea/setuptools_pep660-0.1.4-py3-none-any.whl (from https://pypi.org/simple/setuptools-pep660/)> (4.1 kB)
pdm.termui: Installing wheel@0.44.0...
pdm.termui: Using cached response for https://files.pythonhosted.org/packages/1b/d1/9babe2ccaecff775992753d8686970b1e2755d21c8a63be73aba7a4e7d77/wheel-0.44.0-py3-none-any.whl
unearth.preparer: Downloading <Link https://files.pythonhosted.org/packages/1b/d1/9babe2ccaecff775992753d8686970b1e2755d21c8a63be73aba7a4e7d77/wheel-0.44.0-py3-none-any.whl (from https://pypi.org/simple/wheel/)> (67 kB)
pdm.termui: Synchronization complete.
pdm.termui: running editable_wheel
pdm.termui: running dist_info
pdm.termui: creating /tmp/pdm-wheel-cache-v3udmawn/26/50/db/88b93f1f7ed4085a24dac5c1652b0335cb9332b018605e8fab/tmpojtrxqza/energy_diag.egg-info
pdm.termui: writing /tmp/pdm-wheel-cache-v3udmawn/26/50/db/88b93f1f7ed4085a24dac5c1652b0335cb9332b018605e8fab/tmpojtrxqza/energy_diag.egg-info/PKG-INFO
pdm.termui: writing dependency_links to /tmp/pdm-wheel-cache-v3udmawn/26/50/db/88b93f1f7ed4085a24dac5c1652b0335cb9332b018605e8fab/tmpojtrxqza/energy_diag.egg-info/dependency_links.txt
pdm.termui: writing top-level names to /tmp/pdm-wheel-cache-v3udmawn/26/50/db/88b93f1f7ed4085a24dac5c1652b0335cb9332b018605e8fab/tmpojtrxqza/energy_diag.egg-info/top_level.txt
pdm.termui: writing manifest file '/tmp/pdm-wheel-cache-v3udmawn/26/50/db/88b93f1f7ed4085a24dac5c1652b0335cb9332b018605e8fab/tmpojtrxqza/energy_diag.egg-info/SOURCES.txt'
pdm.termui: reading manifest file '/tmp/pdm-wheel-cache-v3udmawn/26/50/db/88b93f1f7ed4085a24dac5c1652b0335cb9332b018605e8fab/tmpojtrxqza/energy_diag.egg-info/SOURCES.txt'
pdm.termui: writing manifest file '/tmp/pdm-wheel-cache-v3udmawn/26/50/db/88b93f1f7ed4085a24dac5c1652b0335cb9332b018605e8fab/tmpojtrxqza/energy_diag.egg-info/SOURCES.txt'
pdm.termui: creating '/tmp/pdm-wheel-cache-v3udmawn/26/50/db/88b93f1f7ed4085a24dac5c1652b0335cb9332b018605e8fab/tmpojtrxqza/energy_diag.dist-info'
pdm.termui: running build_ext
  ✔ Update my-dependency 1.0.0 -> 1.0.0 successful
  🎉 All complete!
INFO: PDM 2.18.2 is installed, while 2.19.0 is available.
Please run `pdm self update` to upgrade.
Run `pdm config check_update false` to disable the check.
```

## Environment Information

With the bug

```bash
# Paste the output of `pdm info && pdm info --env` below:
$ pdm info && pdm info --env
PDM version:
  2.19.1
Python Interpreter:
  /home/sdeframond/my-project/my-main-package/.venv/bin/python (3.11)
Project Root:
  /home/sdeframond/my-project/my-main-package
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.10.7",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.15.133.1-microsoft-standard-WSL2",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Thu Oct 5 21:02:42 UTC 2023",
  "python_full_version": "3.11.5",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "linux"
}
```

WITHOUT the bug:

```bash
# Paste the output of `pdm info && pdm info --env` below:
$ pdm info && pdm info --env
PDM version:
  2.18.2
Python Interpreter:
  /home/sdeframond/my-project/my-main-package/.venv/bin/python (3.11)
Project Root:
  /home/sdeframond/my-project/my-main-package
Local Packages:

INFO: PDM 2.18.2 is installed, while 2.19.0 is available.
Please run `pdm self update` to upgrade.
Run `pdm config check_update false` to disable the check.
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.7",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.15.133.1-microsoft-standard-WSL2",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Thu Oct 5 21:02:42 UTC 2023",
  "python_full_version": "3.11.5",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "linux"
}
INFO: PDM 2.18.2 is installed, while 2.19.0 is available.
Please run `pdm self update` to upgrade.
Run `pdm config check_update false` to disable the check.
```

**Comment by frostming** [comment]
> PDM no longer falls back to setuptools-pep660 when the build backend doesn't support PEP 660. (#3159)


please update your build backend config to use a modern build backend supporting pep 660
