### ISSUE TITLE
use_uv fails to lock when there are Chinese in pyproject.toml on windows

### ISSUE THREAD

**Issue by monchin** [pdm-project/pdm#3181]
- [ √] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Hello, `uv` integration is  really exciting, but I found there exist some issues when `pyproject.toml` contains Chinese. For example, below is my `pyproject.toml`
```toml
[project]
name = "test_uv"
version = "0.1.0"
description = "中文utf8的uv测试"
authors = [
    {name = "mon", email = "fake@email.com"},
]
dependencies = []
requires-python = ">=3.10.0"
readme = "README.md"
license = {text = "MIT"}

[tool.pdm]
distribution = false
```
If `pdm config use_uv` is False, then `pdm lock` will generate `pdm.lock` successfully like this:
```toml
# This file is @generated by PDM.
# It is not intended for manual editing.

[metadata]
groups = ["default"]
strategy = ["inherit_metadata"]
lock_version = "4.5.0"
content_hash = "sha256:4b8b731c3049455738b6707d4e9b8a8551bf6bf65d8bad6cc7a708f98c6406a4"

[[metadata.targets]]
requires_python = ">=3.10.0"
```
But if I set `pdm config use_uv True`, and type `pdm lock`, then an error occurs, below is the output in console:
```
⠋ 0:00:00 Resolving dependencies  WARNING: inherit_metadata strategy is not supported by uv resolver, it will be ignored
⠋ 0:00:00 Resolve for environment (>=3.10.0) None
INFO: Using uv is experimental and might break due to uv updates.
error: failed to read from file `C:\Project\test\test_uv\pyproject.toml`
  Caused by: stream did not contain valid UTF-8
⠋ 0:00:00 Resolve for environment (>=3.10.0) None
See C:\Users\c.men\AppData\Local\pdm\pdm\Logs\pdm-lock-n3wgv4eg.log for detailed debug log.
[CalledProcessError]: Command '['c:\\users\\c.men\\.cargo\\bin\\uv.EXE', 'lock', '-p', 'C:\\Project\\test\\test_uv\\.venv\\Scripts\\python.exe', '--index-url', 'http://10.0.4.16:8084/root/custom/+simple/',   
'--index-strategy=unsafe-best-match']' returned non-zero exit status 2.
WARNING: Add '-v' to see the detailed traceback
```
Below is the detailed debug log
```
pdm.termui: Error occurs
Traceback (most recent call last):
  File "C:\Users\c.men\AppData\Roaming\pdm\venv\lib\site-packages\pdm\termui.py", line 260, in logging
    yield logger
  File "C:\Users\c.men\AppData\Roaming\pdm\venv\lib\site-packages\pdm\cli\actions.py", line 133, in do_lock
    resolved, collected_groups = resolver.resolve()
  File "C:\Users\c.men\AppData\Roaming\pdm\venv\lib\site-packages\pdm\resolver\uv.py", line 185, in resolve
    subprocess.run(uv_lock_command, cwd=self.project.root, check=True)
  File "C:\Users\c.men\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['c:\\users\\c.men\\.cargo\\bin\\uv.EXE', 'lock', '-p', 'C:\\Project\\test\\test_uv\\.venv\\Scripts\\python.exe', '--index-url', 'http://10.0.4.16:8084/root/custom/+simple/', '--index-strategy=unsafe-best-match']' returned non-zero exit status 2.
```
If I remove all Chinese in `pyproject.toml`, it works for `use_uv True`:
```
⠋ 0:00:00 Resolving dependencies  WARNING: inherit_metadata strategy is not supported by uv resolver, it will be ignored
⠋ 0:00:00 Resolve for environment (==3.10.*) None
INFO: Using uv is experimental and might break due to uv updates.
Resolved 1 package in 4ms
Changes are written to pdm.lock.
  0:00:00 🔒 Lock successful.
```
So I thought it might be a bug for uv, but when I put some Chinese in the `pyproject.toml` and tried to directly type
```
uv lock -p .venv/Scripts/python.exe --index-url http://10.0.4.16:8084/root/custom/+simple/ --index-strategy=unsafe-best-match
```
as written in the output and debug log, it succeeded with Chinese and generated a file `uv.lock`:
```toml
version = 1
requires-python = ">=3.10.0"

[[package]]
name = "test-uv"
version = "0.1.0"
source = { virtual = "." }
```
So maybe it's not `uv`'s issue.
## Expected behavior
`pdm` can `use_uv` with utf-8 Chinese in `pyproject.toml`

## Environment Information
- OS: win11
- python: 3.10.11
- pdm: 2.19.1

As we know, windows in China default uses `gbk` encoding, maybe it is an issue about that, although I really save `pyproject.toml` with utf-8. So I tested again on my wls2 ubuntu 24.04, and it did work. Below is the output:
```
INFO: The saved Python interpreter doesn't match the project's requirement. Trying to find another one.
WARNING: Project requires a python version of >=3.10.0, The virtualenv is being created for you as it cannot be matched
to the right version.
INFO: python.use_venv is on, creating a virtualenv for this project...
INFO: Using uv is experimental and might break due to uv updates.
Using Python 3.12.3 interpreter at: /usr/bin/python3
Creating virtual environment at: .venv
Activate with: source .venv/bin/activate
Virtualenv is created successfully at /mnt/c/Project/test/test_uv/.venv
⠋ 0:00:00 Resolve for environment (>=3.10.0) None
Resolved 1 package in 7ms
Changes are written to pdm.lock.
  0:00:00 🔒 Lock successful.
```
And I found that it seems pdm would create a `pyproject.toml.bak` file, I guess if it is because `pyproject.toml.bak` is  created by default encoding, so uv failed on windows with Chinese?

**Comment by monchin** [comment]
Here it is more apparent if I use `pdm add numpy -v`, the output is:
``` 
Adding packages to default dependencies: numpy
Traceback (most recent call last):
  File "C:\Users\c.men\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\c.men\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\c.men\AppData\Roaming\Python\Scripts\pdm.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\c.men\AppData\Roaming\pdm\venv\lib\site-packages\pdm\core.py", line 378, in main
    return core.main(args or sys.argv[1:])
  File "C:\Users\c.men\AppData\Roaming\pdm\venv\lib\site-packages\pdm\core.py", line 267, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "C:\Users\c.men\AppData\Roaming\pdm\venv\lib\site-packages\pdm\core.py", line 262, in main
    self.handle(project, options)
  File "C:\Users\c.men\AppData\Roaming\pdm\venv\lib\site-packages\pdm\core.py", line 194, in handle
    command.handle(project, options)
  File "C:\Users\c.men\AppData\Roaming\pdm\venv\lib\site-packages\pdm\cli\commands\add.py", line 71, in handle
    self.do_add(
  File "C:\Users\c.men\AppData\Roaming\pdm\venv\lib\site-packages\pdm\cli\commands\add.py", line 159, in do_add
    resolved = do_lock(
  File "C:\Users\c.men\AppData\Roaming\pdm\venv\lib\site-packages\pdm\cli\actions.py", line 133, in do_lock
    resolved, collected_groups = resolver.resolve()
  File "C:\Users\c.men\AppData\Roaming\pdm\venv\lib\site-packages\pdm\resolver\uv.py", line 179, in resolve
    builder.build_uv_lock()
  File "C:\Users\c.men\AppData\Roaming\pdm\venv\lib\site-packages\pdm\formats\uv.py", line 93, in build_uv_lock
    this_candidate = self.project.make_self_candidate(True)
  File "C:\Users\c.men\AppData\Roaming\pdm\venv\lib\site-packages\pdm\project\core.py", line 534, in make_self_candidate
    req = parse_requirement(path_to_url(self.root.as_posix()), editable)
  File "C:\Users\c.men\AppData\Roaming\pdm\venv\lib\site-packages\pdm\models\requirements.py", line 511, in parse_requirement
    r = FileRequirement.create(**args)
  File "C:\Users\c.men\AppData\Roaming\pdm\venv\lib\site-packages\pdm\models\requirements.py", line 294, in create
    return super().create(**kwargs)
  File "C:\Users\c.men\AppData\Roaming\pdm\venv\lib\site-packages\pdm\models\requirements.py", line 150, in create
    return cls(**{k: v for k, v in kwargs.items() if k in inspect.signature(cls).parameters})
  File "<string>", line 15, in __init__
  File "C:\Users\c.men\AppData\Roaming\pdm\venv\lib\site-packages\pdm\models\requirements.py", line 256, in __post_init__
    self._check_installable()
  File "C:\Users\c.men\AppData\Roaming\pdm\venv\lib\site-packages\pdm\models\requirements.py", line 402, in _check_installable
    result = Setup.from_directory(self.path.absolute())
  File "C:\Users\c.men\AppData\Roaming\pdm\venv\lib\site-packages\pdm\models\setup.py", line 40, in from_directory
    return _SetupReader.read_from_directory(dir)
  File "C:\Users\c.men\AppData\Roaming\pdm\venv\lib\site-packages\pdm\models\setup.py", line 64, in read_from_directory
    new_result = file_reader(filepath)
  File "C:\Users\c.men\AppData\Roaming\pdm\venv\lib\site-packages\pdm\models\setup.py", line 77, in read_pyproject_toml
    metadata = PyProject(file, ui=termui.UI()).metadata.unwrap()
  File "C:\Users\c.men\AppData\Roaming\pdm\venv\lib\site-packages\pdm\project\toml_file.py", line 18, in __init__
    self._data = self.read()
  File "C:\Users\c.men\AppData\Roaming\pdm\venv\lib\site-packages\pdm\project\project_file.py", line 27, in read
    data = super().read()
  File "C:\Users\c.men\AppData\Roaming\pdm\venv\lib\site-packages\pdm\project\toml_file.py", line 23, in read
    return super().read()
  File "C:\Users\c.men\AppData\Roaming\pdm\venv\lib\site-packages\tomlkit\toml_file.py", line 32, in read
    content = f.read()
  File "C:\Users\c.men\AppData\Local\Programs\Python\Python310\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd6 in position 60: invalid continuation byte
```
Notice that it says the specific byte `0xd6` and position `60`, I copied a `pyproject copy.toml` file but saved it with encoding `gbk`, and open both `toml` files with hex. In the raw `pyproject.toml` file with utf-8, there is no `0xd6` in the whole file, and the first description character is `0xE4`, 
![image](https://github.com/user-attachments/assets/2528c5f6-9670-443f-86f5-bf34f680ceb0)
the Data Inspector is 
```txt
Data Inspector
binary
11100100
octal
344
uint8
228
int8
-28
uint16
47332
int16
-18204
uint24
11385060
int24
-5392156
uint32
3870144740
int32
-424822556
uint64
946467953886214372
int64
946467953886214372
ULEB128
149780219780196
SLEB128
149780219780196
float16
-0.611328125
bfloat16
-0.0001087188720703125
float32
-4.101900157887259e+23
float64
2.1201211201119114e-245
ASCII
ä
UTF-8
中
UTF-16
룤
GB18030
涓
BIG5
銝
SHIFT-JIS
荳
```
We can see that the utf-8 is "中". While in the copied `pyproject copy.toml` with gbk encoding, the first character in descprtion is `0xD6`, 
![image](https://github.com/user-attachments/assets/62ff902d-84f9-4b82-bd7a-d967c0c2dd3a)
with Data Inspector
```txt
 Data Inspector
binary
11010110
octal
326
uint8
214
int8
-42
uint16
53462
int16
-12074
uint24
13553878
int24
-3223338
uint32
3301888214
int32
-993079082
uint64
6992415814428053718
int64
6992415814428053718
ULEB128
9270700118
SLEB128
9270700118
float16
-38.6875
bfloat16
-28722593792
float32
-1654.526123046875
float64
2.861391746354985e+159
ASCII
Ö
UTF-8
�
UTF-16
탖
GB18030
中
BIG5
笢
SHIFT-JIS
ﾖ
```
utf-8 is random wrong charactor but gb18030 is "中"
