### ISSUE TITLE
pdm failing to install dependencies from AWS CodeArtifact

### ISSUE THREAD

**Issue by tinovyatkin** [pdm-project/pdm#3185]
We are using AWS CodeArtifact and noticed that `pdm` after the version 2.12.4 started to fail with following error related to missing `Date` header:

```bash
Traceback (most recent call last):
  File "/var/lang/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/lang/lib/python3.10/site-packages/pdm/installers/synchronizers.py",
line 29, in install_candidate
    self.manager.install(can)
  File "/var/lang/lib/python3.10/site-packages/pdm/installers/manager.py", line 
33, in install
    prepared.build(),
  File "/var/lang/lib/python3.10/site-packages/pdm/models/candidates.py", line 
397, in build
    self._obtain(allow_all=False)
  File "/var/lang/lib/python3.10/site-packages/pdm/models/candidates.py", line 
451, in _obtain
    self._unpack(validate_hashes=not allow_all)
  File "/var/lang/lib/python3.10/site-packages/pdm/models/candidates.py", line 
465, in _unpack
    result = finder.download_and_unpack(
  File "/var/lang/lib/python3.10/site-packages/unearth/finder.py", line 441, in 
download_and_unpack
    file = unpack_link(
  File "/var/lang/lib/python3.10/site-packages/unearth/preparer.py", line 340, 
in unpack_link
    with session.get_stream(link.normalized) as resp:
  File "/var/lang/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/var/lang/lib/python3.10/site-packages/httpx/_client.py", line 880, in 
stream
    response = self.send(
  File "/var/lang/lib/python3.10/site-packages/httpx/_client.py", line 926, in 
send
    response = self._send_handling_auth(
  File "/var/lang/lib/python3.10/site-packages/httpx/_client.py", line 954, in 
_send_handling_auth
    response = self._send_handling_redirects(
  File "/var/lang/lib/python3.10/site-packages/httpx/_client.py", line 991, in 
_send_handling_redirects
    response = self._send_single_request(request)
  File "/var/lang/lib/python3.10/site-packages/httpx/_client.py", line 1027, in 
_send_single_request
    response = transport.handle_request(request)
  File "/var/lang/lib/python3.10/site-packages/hishel/_sync/_transports.py", 
line 131, in handle_request
    res = self._controller.construct_response_from_cache(
  File "/var/lang/lib/python3.10/site-packages/hishel/_controller.py", line 319,
in construct_response_from_cache
    age = get_age(response, self._clock)
  File "/var/lang/lib/python3.10/site-packages/hishel/_controller.py", line 83, 
in get_age
    raise RuntimeError("The `Date` header is missing in the response.")
RuntimeError: The `Date` header is missing in the response.
```

This problem doesn't affect `pip` or `uv` and wasn't there in earlier versions of pdm as I mentioned.

**Comment by karpetrosyan** [comment]
Hey, that's the caching library, which cannot find the Date header that must be present in all requests, according to the RFC that have a "clock".

> An origin server with a clock (as defined in [Section 5.6.7](https://www.rfc-editor.org/rfc/rfc9110.html#http.date)) MUST generate a Date header field in all [2xx (Successful)](https://www.rfc-editor.org/rfc/rfc9110.html#status.2xx), [3xx (Redirection)](https://www.rfc-editor.org/rfc/rfc9110.html#status.3xx), and [4xx (Client Error)](https://www.rfc-editor.org/rfc/rfc9110.html#status.4xx) responses, and MAY generate a Date header field in [1xx (Informational)](https://www.rfc-editor.org/rfc/rfc9110.html#status.1xx) and [5xx (Server Error)](https://www.rfc-editor.org/rfc/rfc9110.html#status.5xx) responses.

But actually, I think it would be more user-friendly to silently ignore such resources instead of raising an error and forcing the client code to handle the exception. Therefore, I will modify the behavior in [Hishel](https://hishel.com) and submit a pull request with the fix.

**Comment by tinovyatkin** [comment]
@karpetrosyan is there any temporary workaround? Like switching off caching...

**Comment by karpetrosyan** [comment]
I have released the new version, you can specify it explicitly in your dependencies `hishel==0.0.32`, to force pdm using the newer version.

**Comment by tinovyatkin** [comment]
Thank you for the fix!

@karpetrosyan @frostming taking into account that files on PyPi.org [are immutable](https://test.pypi.org/help/#file-name-reuse) I'm very surprised that `pdm` is even taking into account something else (like HTTP response `Date`) for caching. This probably affects caching performance very negatively.
