### ISSUE TITLE
pdm add --dev: List Index Out Of Range Exception

### ISSUE THREAD

**Issue by georggrab** [pdm-project/pdm#3196]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

Let me know if I'm doing something obviously wrong.
I want to add sphinx to my dev dependencies:

```
pdm add sphinx --dev
```

and receive:

```
pdm add sphinx --dev -v
Adding packages to dev dev-dependencies: sphinx
Traceback (most recent call last):
  File "/Users/georggrab/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/georggrab/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/core.py", line 378, in main
    return core.main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/georggrab/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/core.py", line 267, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/Users/georggrab/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/core.py", line 262, in main
    self.handle(project, options)
  File "/Users/georggrab/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/core.py", line 194, in handle
    command.handle(project, options)
  File "/Users/georggrab/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/cli/commands/add.py", line 71, in handle
    self.do_add(
  File "/Users/georggrab/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/cli/commands/add.py", line 148, in do_add
    group_deps = project.add_dependencies(requirements, group, selection.dev or False, write=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/georggrab/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/project/core.py", line 625, in add_dependencies
    setter(cast(Array, deps).multiline(True))
  File "/Users/georggrab/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/project/core.py", line 568, in update_dev_dependencies
    del self.pyproject._data["tool"]["pdm"]
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/Users/georggrab/.local/pipx/venvs/pdm/lib/python3.12/site-packages/tomlkit/container.py", line 867, in __delitem__
    table = self._tables[i]
            ~~~~~~~~~~~~^^^
IndexError: list index out of range
```

I have the following `pyproject.toml`:

```
[project]
name = "redacted-project"
version = "0.3.0"
description = "redacted."
authors = [
    {name = "Georg Grab", email = "g_grab@redacted.com"},
]
dependencies = [
    "requests>=2",
    "aiohttp>=3.10.7",
]
requires-python = ">=3.9"
readme = "README.md"
license = {text = "All rights reserved"}

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[[tool.pdm.source]]
name = "pypi-redacted"
url = "https://pypi.redacted.com/simple"
verify_ssl = true


[tool.pdm.dev-dependencies]
dev = [
    "pytest-asyncio>=0.24.0",
]
[tool.pdm]
distribution = true

```

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
pdm info && pdm info --env
PDM version:
  2.19.1
Python Interpreter:
  /Users/georggrab/code/redacted/.venv/bin/python (3.9)
Project Root:
  /Users/georggrab/code/redacted
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.12.6",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "24.0.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 24.0.0: Mon Aug 12 20:52:41 PDT 2024; root:xnu-11215.1.10~2/RELEASE_ARM64_T6031",
  "python_full_version": "3.9.6",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "darwin"
}
```

**Comment by georggrab** [comment]
Apologies, user error. I placed 

```
[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
```

to the bottom and then it worked. Closing this
