### ISSUE TITLE
[bug] pdm install fails when running in uv mode

### ISSUE THREAD

**Issue by axelwas** [pdm-project/pdm#3233]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

pdm install command using uv fails using on PDM v2.19.3 using uv 0.4.28 on Macos Silicon machine.

## Actual behavior

Install fails early before even trying to install deps.
uv is throwing the error below

```bash
thread 'main' panicked at crates/uv-distribution-types/src/file.rs:154:32:
called `Result::unwrap()` on an `Err` value: RelativeUrlWithoutBase
```

## Expected behavior

Install should work as in normal mode.

## Environment Information

```bash
uv 0.4.28 (debe67ffd 2024-10-28)
PDM version:
  2.19.3
Python Interpreter:
  /Users/axel/code/bi_dagster/.venv/bin/python (3.11)
Project Root:
  /Users/axel/code/bi_dagster
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.12.7",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "23.5.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024;
root:xnu-10063.121.3~5/RELEASE_ARM64_T6000",
  "python_full_version": "3.11.4",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "darwin"
}
```

**Comment by axelwas** [comment]
Here are the full logs:

``` bash
STATUS: Resolving packages from lockfile...
INFO: Using uv is experimental and might break due to uv updates.
Running uv sync command: ['/Users/axel/.cargo/bin/uv', 'sync', '--all-extras', '--frozen', '-p', '/Users/axel/code/bi_dagster/.venv/bin/python', '--verbose', '--inexact', '--index-url', 'https://pypi.org/simple']
DEBUG uv 0.4.28 (debe67ffd 2024-10-28)
DEBUG Found project root: `/Users/axel/code/bi_dagster`
DEBUG No workspace root found, using project root
DEBUG The virtual environment's Python version satisfies `path `.venv/bin/python``
DEBUG Using request timeout of 30s
DEBUG Identified uncached distribution: agate==1.7.1
DEBUG Identified uncached distribution: alembic==1.13.1
DEBUG Identified uncached distribution: aniso8601==9.0.1
DEBUG Identified uncached distribution: annotated-types==0.6.0
DEBUG Identified uncached distribution: anyio==4.2.0
DEBUG Identified uncached distribution: asn1crypto==1.5.1
DEBUG Identified uncached distribution: astunparse==1.6.3
DEBUG Identified uncached distribution: attrs==23.2.0
DEBUG Identified uncached distribution: aws-secretsmanager-caching==1.1.3
DEBUG Identified uncached distribution: babel==2.14.0
DEBUG Identified uncached distribution: backoff==2.2.1
DEBUG Identified uncached distribution: bi-dagster @ file:///Users/axel/code/bi_dagster
DEBUG Identified uncached distribution: black==24.10.0
DEBUG Identified uncached distribution: boto3==1.35.37
DEBUG Identified uncached distribution: boto3-stubs==1.35.37
DEBUG Identified uncached distribution: botocore==1.35.37
DEBUG Identified uncached distribution: botocore-stubs==1.34.31
DEBUG Identified uncached distribution: cachetools==5.3.2
DEBUG Identified uncached distribution: casefy==0.1.7
DEBUG Identified uncached distribution: certifi==2023.11.17
DEBUG Identified uncached distribution: cffi==1.16.0
DEBUG Identified uncached distribution: cfgv==3.4.0
DEBUG Identified uncached distribution: charset-normalizer==3.3.2
DEBUG Identified uncached distribution: click==8.1.7
DEBUG Identified uncached distribution: clickhouse-connect==0.7.19
DEBUG Identified uncached distribution: colorama==0.4.6
DEBUG Identified uncached distribution: coloredlogs==14.0
DEBUG Identified uncached distribution: confluent-kafka==2.5.3
DEBUG Identified uncached distribution: croniter==2.0.1
DEBUG Identified uncached distribution: cryptography==41.0.7
DEBUG Identified uncached distribution: dacite==1.8.1
DEBUG Identified uncached distribution: daff==1.3.46
DEBUG Identified uncached distribution: dagit==1.8.10
DEBUG Identified uncached distribution: dagster==1.8.10
DEBUG Identified uncached distribution: dagster-airbyte==0.24.10
DEBUG Identified uncached distribution: dagster-aws==0.24.10
DEBUG Identified uncached distribution: dagster-dbt==0.24.10
DEBUG Identified uncached distribution: dagster-docker==0.24.10
DEBUG Identified uncached distribution: dagster-embedded-elt==0.24.10
DEBUG Identified uncached distribution: dagster-fivetran==0.24.10
DEBUG Identified uncached distribution: dagster-graphql==1.8.10
DEBUG Identified uncached distribution: dagster-k8s==0.24.10
DEBUG Identified uncached distribution: dagster-pipes==1.8.10
DEBUG Identified uncached distribution: dagster-postgres==0.24.10
DEBUG Identified uncached distribution: dagster-slack==0.24.10
DEBUG Identified uncached distribution: dagster-webserver==1.8.10
DEBUG Identified uncached distribution: dataclasses-avroschema==0.60.1
DEBUG Identified uncached distribution: dataclasses-json==0.6.7
DEBUG Identified uncached distribution: dbt-adapters==1.2.1
DEBUG Identified uncached distribution: dbt-common==1.2.0
DEBUG Identified uncached distribution: dbt-core==1.8.1
DEBUG Identified uncached distribution: dbt-extractor==0.5.1
DEBUG Identified uncached distribution: dbt-semantic-interfaces==0.5.1
DEBUG Identified uncached distribution: dbt-snowflake==1.8.3
DEBUG Identified uncached distribution: defusedxml==0.7.1
DEBUG Identified uncached distribution: dill==0.3.9
DEBUG Identified uncached distribution: distlib==0.3.8
DEBUG Identified uncached distribution: dlt==1.2.0
DEBUG Identified uncached distribution: docker==7.0.0
DEBUG Identified uncached distribution: docker-image-py==0.1.12
DEBUG Identified uncached distribution: docstring-parser==0.15
DEBUG Identified uncached distribution: envyaml==1.10.211231
DEBUG Identified uncached distribution: et-xmlfile==1.1.0
DEBUG Identified uncached distribution: fastavro==1.9.7
DEBUG Identified uncached distribution: filelock==3.13.1
DEBUG Identified uncached distribution: fsspec==2023.12.2
DEBUG Identified uncached distribution: gitdb==4.0.11
DEBUG Identified uncached distribution: gitpython==3.1.43
DEBUG Identified uncached distribution: giturlparse==0.12.0
DEBUG Identified uncached distribution: google-api-core==2.16.1
DEBUG Identified uncached distribution: google-api-python-client==2.149.0
DEBUG Identified uncached distribution: google-auth==2.27.0
DEBUG Identified uncached distribution: google-auth-httplib2==0.2.0
DEBUG Identified uncached distribution: google-auth-oauthlib==1.2.1
DEBUG Identified uncached distribution: googleapis-common-protos==1.62.0
DEBUG Identified uncached distribution: gql==3.5.0
DEBUG Identified uncached distribution: graphene==3.3
DEBUG Identified uncached distribution: graphql-core==3.2.3
DEBUG Identified uncached distribution: graphql-relay==3.2.0
DEBUG Identified uncached distribution: grpcio==1.60.0
DEBUG Identified uncached distribution: grpcio-health-checking==1.60.0
DEBUG Identified uncached distribution: h11==0.14.0
DEBUG Identified uncached distribution: hexbytes==1.2.0
DEBUG Identified uncached distribution: httplib2==0.22.0
DEBUG Identified uncached distribution: httptools==0.6.1
DEBUG Identified uncached distribution: humanfriendly==10.0
DEBUG Identified uncached distribution: humanize==4.9.0
DEBUG Identified uncached distribution: identify==2.5.33
DEBUG Identified uncached distribution: idna==3.6
DEBUG Identified uncached distribution: importlib-metadata==6.11.0
DEBUG Identified uncached distribution: inflector==3.1.1
DEBUG Identified uncached distribution: iniconfig==2.0.0
DEBUG Identified uncached distribution: isodate==0.6.1
DEBUG Identified uncached distribution: jaraco-classes==3.3.0
DEBUG Identified uncached distribution: jinja2==3.1.4
DEBUG Identified uncached distribution: jmespath==1.0.1
DEBUG Identified uncached distribution: jsonpath-ng==1.6.1
DEBUG Identified uncached distribution: jsonschema==4.21.1
DEBUG Identified uncached distribution: jsonschema-specifications==2023.12.1
DEBUG Identified uncached distribution: keyring==24.3.0
DEBUG Identified uncached distribution: kubernetes==30.1.0
DEBUG Identified uncached distribution: leather==0.3.4
DEBUG Identified uncached distribution: logbook==1.5.3
DEBUG Identified uncached distribution: lz4==4.3.3
DEBUG Identified uncached distribution: makefun==1.15.2
DEBUG Identified uncached distribution: mako==1.3.2
DEBUG Identified uncached distribution: markdown-it-py==3.0.0
DEBUG Identified uncached distribution: markupsafe==2.1.4
DEBUG Identified uncached distribution: marshmallow==3.22.0
DEBUG Identified uncached distribution: mashumaro==3.12
DEBUG Identified uncached distribution: mdurl==0.1.2
DEBUG Identified uncached distribution: minimal-snowplow-tracker==0.0.2
DEBUG Identified uncached distribution: more-itertools==10.2.0
DEBUG Identified uncached distribution: msgpack==1.0.7
DEBUG Identified uncached distribution: multidict==6.0.4
DEBUG Identified uncached distribution: multiprocess==0.70.17
DEBUG Identified uncached distribution: mypy==1.11.2
DEBUG Identified uncached distribution: mypy-extensions==1.0.0
DEBUG Identified uncached distribution: networkx==3.2.1
DEBUG Identified uncached distribution: nodeenv==1.8.0
DEBUG Identified uncached distribution: numpy==1.26.3
DEBUG Identified uncached distribution: oauth2client==4.1.3
DEBUG Identified uncached distribution: oauthlib==3.2.2
DEBUG Identified uncached distribution: openpyxl==3.1.5
DEBUG Identified uncached distribution: orjson==3.9.10
DEBUG Identified uncached distribution: packaging==23.2
DEBUG Identified uncached distribution: pandas==2.2.3
DEBUG Identified uncached distribution: parsedatetime==2.6
DEBUG Identified uncached distribution: pathos==0.3.3
DEBUG Identified uncached distribution: pathspec==0.11.2
DEBUG Identified uncached distribution: pathvalidate==3.2.0
DEBUG Identified uncached distribution: pendulum==3.0.0
DEBUG Identified uncached distribution: platformdirs==3.11.0
DEBUG Identified uncached distribution: plotly==5.24.1
DEBUG Identified uncached distribution: pluggy==1.5.0
DEBUG Identified uncached distribution: ply==3.11
DEBUG Identified uncached distribution: pox==0.3.5
DEBUG Identified uncached distribution: ppft==1.7.6.9
DEBUG Identified uncached distribution: pre-commit==4.0.1
DEBUG Identified uncached distribution: protobuf==4.25.2
DEBUG Identified uncached distribution: psycopg2-binary==2.9.9
DEBUG Identified uncached distribution: pyarrow==15.0.0
DEBUG Identified uncached distribution: pyasn1==0.5.1
DEBUG Identified uncached distribution: pyasn1-modules==0.3.0
DEBUG Identified uncached distribution: pyathena==3.9.0
DEBUG Identified uncached distribution: pycarlo==0.9.12
DEBUG Identified uncached distribution: pycparser==2.21
DEBUG Identified uncached distribution: pydantic==2.9.2
DEBUG Identified uncached distribution: pydantic-core==2.23.4
DEBUG Identified uncached distribution: pydrive2==1.20.0
DEBUG Identified uncached distribution: pygments==2.17.2
DEBUG Identified uncached distribution: pyjwt==2.8.0
DEBUG Identified uncached distribution: pyodbc==5.1.0
DEBUG Identified uncached distribution: pyopenssl==23.3.0
DEBUG Identified uncached distribution: pyparsing==3.1.1
DEBUG Identified uncached distribution: pytest==8.3.3
DEBUG Identified uncached distribution: python-box==7.2.0
DEBUG Identified uncached distribution: python-dateutil==2.9.0.post0
DEBUG Identified uncached distribution: python-dotenv==1.0.1
DEBUG Identified uncached distribution: python-slugify==8.0.2
DEBUG Identified uncached distribution: pytimeparse==1.1.8
DEBUG Identified uncached distribution: pytz==2023.4
DEBUG Identified uncached distribution: pyyaml==6.0.2
DEBUG Identified uncached distribution: ratelimit==2.2.1
DEBUG Identified uncached distribution: referencing==0.33.0
DEBUG Identified uncached distribution: regex==2023.12.25
DEBUG Identified uncached distribution: requests==2.31.0
DEBUG Identified uncached distribution: requests-oauthlib==1.3.1
DEBUG Identified uncached distribution: requests-toolbelt==1.0.0
DEBUG Identified uncached distribution: requirements-parser==0.9.0
DEBUG Identified uncached distribution: rich==13.7.0
DEBUG Identified uncached distribution: rpds-py==0.17.1
DEBUG Identified uncached distribution: rsa==4.9
DEBUG Identified uncached distribution: ruff==0.1.15
DEBUG Identified uncached distribution: s3transfer==0.10.0
DEBUG Identified uncached distribution: semver==3.0.2
DEBUG Identified uncached distribution: setuptools==69.0.3
DEBUG Identified uncached distribution: sgqlc==16.3
DEBUG Identified uncached distribution: simplejson==3.19.2
DEBUG Identified uncached distribution: six==1.16.0
DEBUG Identified uncached distribution: slack-sdk==3.26.2
DEBUG Identified uncached distribution: sling==1.2.20
DEBUG Identified uncached distribution: sling-linux-amd64==1.2.20
DEBUG Identified uncached distribution: sling-mac-arm64==1.2.20
DEBUG Identified uncached distribution: smmap==5.0.1
DEBUG Identified uncached distribution: sniffio==1.3.0
DEBUG Identified uncached distribution: snowflake-connector-python==3.12.2
DEBUG Identified uncached distribution: sortedcontainers==2.4.0
DEBUG Identified uncached distribution: sqlalchemy==2.0.35
DEBUG Identified uncached distribution: sqlglot==24.1.2
DEBUG Identified uncached distribution: sqlglotrs==0.2.5
DEBUG Identified uncached distribution: sqlparse==0.5.0
DEBUG Identified uncached distribution: starlette==0.36.1
DEBUG Identified uncached distribution: structlog==24.1.0
DEBUG Identified uncached distribution: tableauhyperapi==0.0.20027
DEBUG Identified uncached distribution: tableauserverclient==0.33
DEBUG Identified uncached distribution: tabulate==0.9.0
DEBUG Identified uncached distribution: tenacity==8.2.3
DEBUG Identified uncached distribution: text-unidecode==1.3
DEBUG Identified uncached distribution: time-machine==2.14.1
DEBUG Identified uncached distribution: tomli==2.0.1
DEBUG Identified uncached distribution: tomlkit==0.12.3
DEBUG Identified uncached distribution: toposort==1.10
DEBUG Identified uncached distribution: tqdm==4.66.1
DEBUG Identified uncached distribution: typer==0.9.0
DEBUG Identified uncached distribution: types-awscrt==0.20.3
DEBUG Identified uncached distribution: types-cffi==1.16.0.20240331
DEBUG Identified uncached distribution: types-croniter==3.0.3.20240731
DEBUG Identified uncached distribution: types-pyopenssl==24.1.0.20240722
DEBUG Identified uncached distribution: types-pytz==2024.2.0.20241003
DEBUG Identified uncached distribution: types-pyyaml==6.0.12.20240917
DEBUG Identified uncached distribution: types-requests==2.32.0.20240914
DEBUG Identified uncached distribution: types-s3transfer==0.10.0
DEBUG Identified uncached distribution: types-setuptools==70.0.0.20240524
DEBUG Identified uncached distribution: types-tzlocal==5.1.0.1
DEBUG Identified uncached distribution: types-urllib3==1.26.25.14
DEBUG Identified uncached distribution: typing-extensions==4.9.0
DEBUG Identified uncached distribution: typing-inspect==0.9.0
DEBUG Identified uncached distribution: tzdata==2023.4
DEBUG Identified uncached distribution: universal-pathlib==0.2.2
DEBUG Identified uncached distribution: uritemplate==4.1.1
DEBUG Identified uncached distribution: urllib3==2.2.2
DEBUG Identified uncached distribution: uvicorn==0.27.0.post1
DEBUG Identified uncached distribution: uvloop==0.19.0
DEBUG Identified uncached distribution: virtualenv==20.25.0
DEBUG Identified uncached distribution: watchdog==3.0.0
DEBUG Identified uncached distribution: watchfiles==0.21.0
DEBUG Identified uncached distribution: websocket-client==1.8.0
DEBUG Identified uncached distribution: websockets==12.0
DEBUG Identified uncached distribution: wheel==0.43.0
DEBUG Identified uncached distribution: yarl==1.9.4
DEBUG Identified uncached distribution: zipp==3.17.0
DEBUG Identified uncached distribution: zstandard==0.22.0
thread 'main' panicked at crates/uv-distribution-types/src/file.rs:154:32:
called `Result::unwrap()` on an `Err` value: RelativeUrlWithoutBase
stack backtrace:
   0:        0x10134cdc8 - __mh_execute_header
   1:        0x1010557b0 - __mh_execute_header
   2:        0x101319694 - __mh_execute_header
   3:        0x10134fe00 - __mh_execute_header
   4:        0x10134f850 - __mh_execute_header
   5:        0x101351568 - __mh_execute_header
   6:        0x1013507f8 - __mh_execute_header
   7:        0x10135076c - __mh_execute_header
   8:        0x101350760 - __mh_execute_header
   9:        0x1021d1970 - __mh_execute_header
  10:        0x1021d1cfc - __mh_execute_header
  11:        0x101602824 - __mh_execute_header
  12:        0x1016b7f78 - __mh_execute_header
  13:        0x1019f0674 - __mh_execute_header
  14:        0x101917fc8 - __mh_execute_header
  15:        0x101738ddc - __mh_execute_header
  16:        0x1016226e4 - __mh_execute_header
  17:        0x101635260 - __mh_execute_header
  18:        0x1014a9224 - __mh_execute_header
  19:        0x1014a4f18 - __mh_execute_header
  20:        0x10157677c - __mh_execute_header
  21:        0x1015389c0 - __mh_execute_header
  22:        0x1014ddedc - __mh_execute_header
  23:        0x1014dd1bc - __mh_execute_header
  24:        0x10173ea08 - __mh_execute_header
  25:        0x101979088 - __mh_execute_header
  26:        0x10173a11c - __mh_execute_header
  27:        0x101978bd0 - __mh_execute_header
Traceback (most recent call last):
  File "/Users/axel/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/axel/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/core.py", line 378, in main
    return core.main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/axel/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/core.py", line 267, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/Users/axel/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/core.py", line 262, in main
    self.handle(project, options)
  File "/Users/axel/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/core.py", line 194, in handle
    command.handle(project, options)
  File "/Users/axel/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/cli/commands/install.py", line 103, in handle
    actions.do_sync(
  File "/Users/axel/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/cli/actions.py", line 301, in do_sync
    synchronizer.synchronize()
  File "/Users/axel/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/installers/uv.py", line 41, in synchronize
    subprocess.run(cmd, check=True, cwd=self.environment.project.root)
  File "/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/axel/.cargo/bin/uv', 'sync', '--all-extras', '--frozen', '-p', '/Users/axel/code/bi_dagster/.venv/bin/python', '--verbose', '--inexact', '--index-url', 'https://pypi.org/simple']' returned non-zero exit status 101.

```

**Comment by monchin** [comment]
You must delete "inherit_metadata" in `pdm.lock`'s strategy when using uv, but I agree it is a bug, as the program should ignore "inherit_metadata" automatically

**Comment by corrosive4354** [comment]
Make sure you are using the latest version of PDM and uv. You can try to upgrade to the latest version:
pip install --upgrade pdm uv

If there is still a problem, it is probably an environment problem.
You can try [Servbay](https://servbay.com), which is more professional than docker on Mac
