### ISSUE TITLE
[bug] pdm cannot install on 2.20.0

### ISSUE THREAD

**Issue by monchin** [pdm-project/pdm#3239]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

run `pdm sync -v`

## Actual behavior

```
STATUS: Resolving packages from lockfile...
Traceback (most recent call last):
  File "C:\Users\c.men\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\c.men\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\c.men\AppData\Roaming\Python\Scripts\pdm.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\c.men\AppData\Roaming\pdm\venv\lib\site-packages\pdm\core.py", line 378, in main
    return core.main(args or sys.argv[1:])
  File "C:\Users\c.men\AppData\Roaming\pdm\venv\lib\site-packages\pdm\core.py", line 267, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "C:\Users\c.men\AppData\Roaming\pdm\venv\lib\site-packages\pdm\core.py", line 262, in main
    self.handle(project, options)
  File "C:\Users\c.men\AppData\Roaming\pdm\venv\lib\site-packages\pdm\core.py", line 194, in handle
    command.handle(project, options)
  File "C:\Users\c.men\AppData\Roaming\pdm\venv\lib\site-packages\pdm\cli\commands\sync.py", line 44, in handle
    actions.do_sync(
  File "C:\Users\c.men\AppData\Roaming\pdm\venv\lib\site-packages\pdm\cli\actions.py", line 284, in do_sync
    packages = list(resolve_from_lockfile(project, requirements, groups=list(selection)))
  File "C:\Users\c.men\AppData\Roaming\pdm\venv\lib\site-packages\pdm\cli\actions.py", line 206, in resolve_from_lockfile
    resolver = project.get_resolver()(
  File "<string>", line 13, in __init__
  File "C:\Users\c.men\AppData\Roaming\pdm\venv\lib\site-packages\pdm\resolver\resolvelib.py", line 30, in __post_init__ 
    provider = self.project.get_provider(
  File "C:\Users\c.men\AppData\Roaming\pdm\venv\lib\site-packages\pdm\project\core.py", line 552, in get_provider        
    from pdm.resolver.providers import get_provider
  File "C:\Users\c.men\AppData\Roaming\pdm\venv\lib\site-packages\pdm\resolver\providers.py", line 49, in <module>       
    class BaseProvider(AbstractProvider[Requirement, Candidate, str]):
TypeError: 'type' object is not subscriptable
```

## Expected behavior

install successfully

## Environment Information

pdm 2.20.0, windows 10, use_uv false

It'll succeed on 4401ff552bd071537d6b2b017a5a2f5266401d42, so it seems efaccb8d7ac96b63602f060a9d8ddd5512db1bdc got something wrong

**Comment by frostming** [comment]
Update `resolvelib` to 1.1.0
