### ISSUE TITLE
ResolveLib + PDM Errors

### ISSUE THREAD

**Issue by alexanderepstein** [pdm-project/pdm#3240]
Installing `pymssql` from source
With the following in pyproject.toml section

```
[tool.pdm.resolution]
respect-source-order = true
no-binary = ["pymssql"]
```

Using pdm version: `2.18.2`
Same error on both Mac/Linux

```
  ✖ Install pymssql 2.3.1 failed
ERRORS:
add pymssql failed:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File 
"/usr/local/lib/python3.11/site-packages/pdm/installers/synchronizers.py", line 
228, in install_candidate
    self.manager.install(can)
  File "/usr/local/lib/python3.11/site-packages/pdm/installers/manager.py", line
33, in install
    prepared.build(),
    ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pdm/models/candidates.py", line 
411, in build
    self._cached = Path(builder.build(build_dir, 
metadata_directory=self._metadata_dir))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pdm/builders/base.py", line 84, 
in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pdm/builders/wheel.py", line 23,
in build
    self.install(self._requires, shared=True)
  File "/usr/local/lib/python3.11/site-packages/pdm/builders/base.py", line 322,
in install
    install_requirements(missing, env)
  File "/usr/local/lib/python3.11/site-packages/pdm/installers/core.py", line 
29, in install_requirements
    resolved, _ = resolve(resolver, reqs, max_rounds=resolve_max_rounds, 
keep_self=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pdm/resolver/core.py", line 43, 
in resolve
    result = resolver.resolve(requirements, max_rounds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File 
"/usr/local/lib/python3.11/site-packages/resolvelib/resolvers/resolution.py", 
line 515, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File 
"/usr/local/lib/python3.11/site-packages/resolvelib/resolvers/resolution.py", 
line 440, in resolve
    name = min(narrowed_unstatisfied_names, key=self._get_preference)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File 
"/usr/local/lib/python3.11/site-packages/resolvelib/resolvers/resolution.py", 
line 173, in _get_preference
    return self._p.get_preference(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pdm/resolver/providers.py", line
112, in get_preference
    dep_depth = min(parent_depths, default=0) + 1
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pdm/resolver/providers.py", line
109, in <genexpr>
    self._known_depth if parent is not None else 0
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'setuptools-scm'
  0:00:39 ✖ Some package operations failed. 1/1
See /root/.local/state/pdm/log/pdm-install-4cx7vf9r.log for detailed debug log.
```

The error started occuring as soon as resolvelib released their latest update, so I have also created an issue on their side as it is not clear to me where the real issue lies. It may be that the latest pdm resolves this problem, but pdm 2.20.0 has the following error when trying to run any commands

```
    class BaseProvider(AbstractProvider[Requirement, Candidate, str]):
                       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: type 'AbstractProvider' is not subscriptable
```

**Comment by alexanderepstein** [comment]
https://github.com/sarugaku/resolvelib/issues/174
