### ISSUE TITLE
PDM breaks with FIPS mode

### ISSUE THREAD

**Issue by wilrodriguez** [pdm-project/pdm#3242]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Enable fips mode on a linux system (in this case, Rocky 9) and try to run _most_ pdm commands.

This actually is the same issue as seen in the twine library here: https://github.com/pypa/twine/issues/857

To quote the findings over there:

> Blake2 algorithms are disabled on FIPS mode on OpenSSL level
> and preferred on Python level which cause the check of
> API (attributes) to fail sooner than OpenSSL raises ValueError
> for unavailable function.

## Actual behavior

```
[root@dev01 test]# pdm lock -v
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   requests
pdm.termui:   Adding requirement python>=3.9
pdm.termui:   Adding requirement requests
Traceback (most recent call last):
  File "/root/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/root/.local/share/pdm/venv/lib64/python3.9/site-packages/pdm/core.py", line 378, in main
    return core.main(args or sys.argv[1:])
  File "/root/.local/share/pdm/venv/lib64/python3.9/site-packages/pdm/core.py", line 267, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/root/.local/share/pdm/venv/lib64/python3.9/site-packages/pdm/core.py", line 262, in main
    self.handle(project, options)
  File "/root/.local/share/pdm/venv/lib64/python3.9/site-packages/pdm/core.py", line 194, in handle
    command.handle(project, options)
  File "/root/.local/share/pdm/venv/lib64/python3.9/site-packages/pdm/cli/commands/lock.py", line 123, in handle
    actions.do_lock(
  File "/root/.local/share/pdm/venv/lib64/python3.9/site-packages/pdm/cli/actions.py", line 133, in do_lock
    resolved, collected_groups = resolver.resolve()
  File "/root/.local/share/pdm/venv/lib64/python3.9/site-packages/pdm/resolver/resolvelib.py", line 50, in resolve
    mapping = self._do_resolve()
  File "/root/.local/share/pdm/venv/lib64/python3.9/site-packages/pdm/resolver/resolvelib.py", line 88, in _do_resolve
    result = resolver.resolve(requirements, max_rounds)
  File "/root/.local/share/pdm/venv/lib64/python3.9/site-packages/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/root/.local/share/pdm/venv/lib64/python3.9/site-packages/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/root/.local/share/pdm/venv/lib64/python3.9/site-packages/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "/root/.local/share/pdm/venv/lib64/python3.9/site-packages/resolvelib/structs.py", line 127, in __bool__
    next(iter(self))
  File "/root/.local/share/pdm/venv/lib64/python3.9/site-packages/resolvelib/structs.py", line 136, in __iter__
    self._factory() if self._iterable is None else self._iterable
  File "/root/.local/share/pdm/venv/lib64/python3.9/site-packages/pdm/resolver/providers.py", line 232, in matches_gen
    candidates = self._find_candidates(reqs[0])
  File "/root/.local/share/pdm/venv/lib64/python3.9/site-packages/pdm/resolver/providers.py", line 202, in _find_candidates
    return self.repository.find_candidates(
  File "/root/.local/share/pdm/venv/lib64/python3.9/site-packages/pdm/models/repositories/base.py", line 180, in find_candidates
    cans = LazySequence(self._find_candidates(requirement, minimal_version=minimal_version))
  File "/root/.local/share/pdm/venv/lib64/python3.9/site-packages/pdm/models/repositories/pypi.py", line 68, in _find_candidates
    for c in finder.find_all_packages(req_name, allow_yanked=requirement.is_pinned)
  File "/root/.local/share/pdm/venv/lib64/python3.9/site-packages/unearth/finder.py", line 315, in find_all_packages
    self._find_packages(package_name, allow_yanked), hashes=hashes or {}
  File "/root/.local/share/pdm/venv/lib64/python3.9/site-packages/unearth/finder.py", line 295, in _find_packages
    return sorted(all_packages, key=self._sort_key, reverse=True)
  File "/root/.local/share/pdm/venv/lib64/python3.9/site-packages/unearth/collector.py", line 187, in collect_links_from_location
    yield from _collect_links_from_index(session, location)
  File "/root/.local/share/pdm/venv/lib64/python3.9/site-packages/unearth/collector.py", line 210, in _collect_links_from_index
    page = fetch_page(session, location, headers)
  File "/root/.local/share/pdm/venv/lib64/python3.9/site-packages/unearth/collector.py", line 195, in fetch_page
    resp = _get_html_response(session, location, headers)
  File "/root/.local/share/pdm/venv/lib64/python3.9/site-packages/unearth/collector.py", line 234, in _get_html_response
    resp = session.get(
  File "/root/.local/share/pdm/venv/lib64/python3.9/site-packages/httpx/_client.py", line 1066, in get
    return self.request(
  File "/root/.local/share/pdm/venv/lib64/python3.9/site-packages/httpx/_client.py", line 837, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/root/.local/share/pdm/venv/lib64/python3.9/site-packages/httpx/_client.py", line 926, in send
    response = self._send_handling_auth(
  File "/root/.local/share/pdm/venv/lib64/python3.9/site-packages/httpx/_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/root/.local/share/pdm/venv/lib64/python3.9/site-packages/httpx/_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/root/.local/share/pdm/venv/lib64/python3.9/site-packages/httpx/_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
  File "/root/.local/share/pdm/venv/lib64/python3.9/site-packages/hishel/_sync/_transports.py", line 113, in handle_request
    key = self._controller._key_generator(httpcore_request, body_for_key)
  File "/root/.local/share/pdm/venv/lib64/python3.9/site-packages/hishel/_utils.py", line 52, in generate_key
    key = blake2b(digest_size=16)
TypeError: 'digest_size' is an invalid keyword argument for openssl_blake2b()
```

## Expected behavior

Should function within a fips enabled environment

## Environment Information

```bash
[root@dev01 test]# pdm info && pdm info --env
PDM version:
  2.19.3
Python Interpreter:
  /root/test/.venv/bin/python (3.9)
Project Root:
  /root/test
Local Packages:

WARNING: Failed to get latest version: 'digest_size' is an invalid keyword argument for openssl_blake2b()
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.18",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.14.0-427.40.1.el9_4.x86_64",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT_DYNAMIC Wed Oct 16 14:57:47 UTC 2024",
  "python_full_version": "3.9.18",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
WARNING: Failed to get latest version: 'digest_size' is an invalid keyword argument for openssl_blake2b()
```

**Comment by wilrodriguez** [comment]
Note that the source of the errors is hishel, which was just recently patched, so, hopefully this should be resolvable soon https://github.com/karpetrosyan/hishel/issues/284
