### ISSUE TITLE
error occured when `pdm init`, import from requirements.txt

### ISSUE THREAD

**Issue by batkiz** [pdm-project/pdm#328]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

while initing pyproject with pdm, an error occured when importing from `requirements.txt`, full log below:

```
git clone --depth=1 https://github.com/twintproject/twint
cd twint
```

```
> pdm init -v
pyproject.toml already exists, update it now.
Please enter the Python interpreter to use: python
Using Python interpreter: C:\soft\Scoop\shims\python.EXE (3.8.8)
Is the project a library that will be upload to PyPI?(y/n) [n]:
License(SPDX name) [MIT]:
Author name [batkiz]:
Author email [batkiz@outlook.com]:
Python requires('*' to allow any) [>=3.8]:
Changes are written to pyproject.toml.
Found following files from other formats that you may import:
0. C:/code/tmp/twint/requirements.txt (requirements)
1. don't do anything, I will import later.
Please select: (0, 1): 0
Traceback (most recent call last):
  File "c:\soft\scoop\apps\python38\current\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\soft\scoop\apps\python38\current\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\batkiz\.local\bin\pdm.exe\__main__.py", line 7, in <module>
  File "c:\users\batkiz\.local\pipx\venvs\pdm\lib\site-packages\pdm\core.py", line 76, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\batkiz\.local\pipx\venvs\pdm\lib\site-packages\pdm\core.py", line 131, in main
    raise err.with_traceback(traceback)
  File "c:\users\batkiz\.local\pipx\venvs\pdm\lib\site-packages\pdm\core.py", line 127, in main
    f(options.project, options)
  File "c:\users\batkiz\.local\pipx\venvs\pdm\lib\site-packages\pdm\cli\commands\init.py", line 57, in handle
    actions.ask_for_import(project)
  File "c:\users\batkiz\.local\pipx\venvs\pdm\lib\site-packages\pdm\cli\actions.py", line 580, in ask_for_import
    do_import(project, filepath, key)
  File "c:\users\batkiz\.local\pipx\venvs\pdm\lib\site-packages\pdm\cli\actions.py", line 532, in do_import
    project_data, settings = FORMATS[key].convert(project, filename, options)
  File "c:\users\batkiz\.local\pipx\venvs\pdm\lib\site-packages\pdm\formats\requirements.py", line 103, in convert
    if options.dev and options.section:
AttributeError: 'NoneType' object has no attribute 'dev'
```

## Actual behavior

the error occured.

## Expected behavior

pdm project inited.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.4.2
Python Interpreter: C:/soft/Scoop/shims/python.EXE (3.8.8)
Project Root:       C:/code/tmp/twint
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.8",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19041",
  "python_full_version": "3.8.8",
  "platform_python_implementaiton": "CPython",
  "python_version": "3.8",
  "sys_platform": "win32"
}
```

BTW pdm installed via pipx, python installed via scoop.

**Comment by batkiz** [comment]
Sadly the fix doesn't work for me :(

log:
```
Found following files from other formats that you may import:
0. C:/code/tmp/twint/requirements.txt (requirements)
1. don't do anything, I will import later.
Please select: (0, 1): 0
Traceback (most recent call last):
  File "c:\soft\scoop\apps\python38\current\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\soft\scoop\apps\python38\current\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\batkiz\.local\bin\pdm.exe\__main__.py", line 7, in <module>
  File "c:\users\batkiz\.local\pipx\venvs\pdm\lib\site-packages\pdm\core.py", line 171, in main
    return Core().main(args)
  File "c:\users\batkiz\.local\pipx\venvs\pdm\lib\site-packages\pdm\core.py", line 133, in main
    raise err.with_traceback(traceback)
  File "c:\users\batkiz\.local\pipx\venvs\pdm\lib\site-packages\pdm\core.py", line 128, in main
    f(options.project, options)
  File "c:\users\batkiz\.local\pipx\venvs\pdm\lib\site-packages\pdm\cli\commands\init.py", line 53, in handle
    actions.ask_for_import(project)
  File "c:\users\batkiz\.local\pipx\venvs\pdm\lib\site-packages\pdm\cli\actions.py", line 571, in ask_for_import
    do_import(project, filepath, key, Namespace())
  File "c:\users\batkiz\.local\pipx\venvs\pdm\lib\site-packages\pdm\cli\actions.py", line 523, in do_import
    project_data, settings = FORMATS[key].convert(project, filename, options)
  File "c:\users\batkiz\.local\pipx\venvs\pdm\lib\site-packages\pdm\formats\requirements.py", line 102, in convert
    if options.dev and options.section:
AttributeError: 'Namespace' object has no attribute 'dev'
```

env:

```
> pdm info && pdm info --env
PDM version:        1.4.3
Python Interpreter: C:/soft/Scoop/shims/python.EXE (3.8.8)
Project Root:       C:/code/tmp/twint
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.8",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19041",
  "python_full_version": "3.8.8",
  "platform_python_implementaiton": "CPython",
  "python_version": "3.8",
  "sys_platform": "win32"
}
```

**Comment by frostming** [comment]
@batkiz Can you try again on the master branch?

**Comment by batkiz** [comment]
It works!🎉 Thanks for your work!
