### ISSUE TITLE
[ImportError] math.cpython-311-x86_64-linux-gnu.so: undefined symbol: _PyModule_Add

### ISSUE THREAD

**Issue by vfdff** [pdm-project/pdm#3342]
### Describe the bug

When I try **python3 -m venv mlir_venv** according https://github.com/llvm/torch-mlir/blob/main/docs/development.md
and it report undefined symbol: _PyModule_Add，detail info as following:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/root/anaconda3/envs/py311-source/lib/python3.11/venv/__init__.py", line 10, in <module>
    import subprocess
  File "/root/anaconda3/envs/py311-source/lib/python3.11/subprocess.py", line 119, in <module>
    import selectors
  File "/root/anaconda3/envs/py311-source/lib/python3.11/selectors.py", line 11, in <module>
    import math
ImportError: /root/anaconda3/envs/py311-source/lib/python3.11/lib-dynload/math.cpython-311-x86_64-linux-gnu.so: undefined symbol: _PyModule_Add
```

### To reproduce

python3 -m venv mlir_venv

it can't update the python with **pip install python=3.11.5**

### Expected Behavior

works fine

### Environment Information

(py311-source) (mlir_venv) root@998ee80b761b:/home/zhongyunde/torch-mlir# python3 --version{,}
Python 3.11.0 (main, Mar  1 2023, 18:26:19) [GCC 11.2.0]
(py311-source) (mlir_venv) root@998ee80b761b:/home/zhongyunde/torch-mlir# uname -v
#211-Ubuntu SMP Thu Nov 24 18:16:04 UTC 2022

### Are you willing to submit a PR to fix this bug?

- [ ] Yes, I would like to submit a PR.

**Comment by frostming** [comment]
Broken python installation that you need to deal with it yourself.
