### ISSUE TITLE
Error installing the experimental python3.13t

### ISSUE THREAD

**Issue by jefer94** [pdm-project/pdm#3343]
### Describe the bug

`pdm python install 3.13` works

`pdm python install 3.13t` throws
```txt
[ModuleNotFoundError]: zstandard is required to unpack .zst files
```

### To reproduce

```bash
pdm python install 3.13t
```

### Expected Behavior

```bash
Successfully installed cpython@3.13.0t
Version: 3.13.0t
Executable: /home/jefer/.local/share/pdm/python/cpython@3.13.0t/bin/python3
```

### Environment Information

```
PDM version:
  2.21.0
Python Interpreter:
  /home/jefer/dev/work/works-api/pdm/.venv/bin/python (3.12)
Project Root:
  /home/jefer/dev/work/works-api/pdm
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.12.7",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.15.146.1-microsoft-standard-WSL2",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Thu Jan 11 04:09:03 UTC 2024",
  "python_full_version": "3.12.7",
  "platform_python_implementation": "CPython",
  "python_version": "3.12",
  "sys_platform": "linux"
}
```

### Verbose Command Output

```bash
STATUS: Downloading cpython@3.13.0t
STATUS: Installing cpython@3.13.0t
Traceback (most recent call last):
  File "/home/jefer/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/jefer/.local/share/pdm/venv/lib/python3.12/site-packages/pdm/core.py", line 392, in main
    return core.main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jefer/.local/share/pdm/venv/lib/python3.12/site-packages/pdm/core.py", line 270, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/home/jefer/.local/share/pdm/venv/lib/python3.12/site-packages/pdm/core.py", line 265, in main
    self.handle(project, options)
  File "/home/jefer/.local/share/pdm/venv/lib/python3.12/site-packages/pdm/core.py", line 195, in handle
    command.handle(project, options)
  File "/home/jefer/.local/share/pdm/venv/lib/python3.12/site-packages/pdm/cli/commands/python.py", line 128, in handle
    self.install_python(project, version)
  File "/home/jefer/.local/share/pdm/venv/lib/python3.12/site-packages/pdm/cli/commands/python.py", line 162, in install_python
    install_file(tf.name, destination, original_filename)
  File "/home/jefer/.local/share/pdm/venv/lib/python3.12/site-packages/pbs_installer/_install.py", line 157, in install_file
    unpack_zst(filename, destination)
  File "/home/jefer/.local/share/pdm/venv/lib/python3.12/site-packages/pbs_installer/_utils.py", line 80, in unpack_zst
    raise ModuleNotFoundError("zstandard is required to unpack .zst files") from None
ModuleNotFoundError: zstandard is required to unpack .zst files
```

### Additional Context

Archlinux
Linux Jeferson 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 GNU/Linux

### Are you willing to submit a PR to fix this bug?

- [ ] Yes, I would like to submit a PR.

**Comment by jefer94** [comment]
I installed it first with pipx install pdm, and them, I unistalled PDM to use the official installation script

**Comment by frostming** [comment]
`pdm self add zstandard` to add the dependency
