### ISSUE TITLE
[AttributeError]: 'PosixPath' object has no attribute 'filepath'

### ISSUE THREAD

**Issue by WAY29** [pdm-project/pdm#359]
- [ ] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce
pdm init
*Is the project a library that will be upload to PyPI? [y/N]: Y*
***If i choose N the bug will not appear***
pdm add ‘any module’

## Actual behavior
pdm add -v requests
Adding packages to default dependencies: requests
Traceback (most recent call last):
  File "/home/longlone/.local/lib/python3.9/site-packages/pip/_vendor/packaging/requirements.py", line 113, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/home/longlone/.local/lib/python3.9/site-packages/pip/_vendor/pyparsing.py", line 1955, in parseString
    raise exc
  File "/home/longlone/.local/lib/python3.9/site-packages/pip/_vendor/pyparsing.py", line 3814, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected stringEnd, found ':'  (at char 4), (line:1, col:5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/longlone/.local/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3101, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/home/longlone/.local/lib/python3.9/site-packages/pip/_vendor/packaging/requirements.py", line 115, in __init__
    raise InvalidRequirement(
pip._vendor.packaging.requirements.InvalidRequirement: Parse error at "':///home'": Expected stringEnd

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/longlone/.local/lib/python3.9/site-packages/pdm/models/requirements.py", line 460, in parse_requirement
    r = NamedRequirement.parse(line)
  File "/home/longlone/.local/lib/python3.9/site-packages/pdm/models/requirements.py", line 362, in parse
    PackageRequirement.__init__(r, line)
  File "/home/longlone/.local/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3103, in __init__
    raise RequirementParseError(str(e))
pip._vendor.pkg_resources.RequirementParseError: Parse error at "':///home'": Expected stringEnd

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/longlone/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/longlone/.local/lib/python3.9/site-packages/pdm/core.py", line 171, in main
    return Core().main(args)
  File "/home/longlone/.local/lib/python3.9/site-packages/pdm/core.py", line 133, in main
    raise err.with_traceback(traceback)
  File "/home/longlone/.local/lib/python3.9/site-packages/pdm/core.py", line 128, in main
    f(options.project, options)
  File "/home/longlone/.local/lib/python3.9/site-packages/pdm/cli/commands/add.py", line 35, in handle
    actions.do_add(
  File "/home/longlone/.local/lib/python3.9/site-packages/pdm/cli/actions.py", line 173, in do_add
    resolved = do_lock(project, strategy, tracked_names, reqs)
  File "/home/longlone/.local/lib/python3.9/site-packages/pdm/cli/actions.py", line 54, in do_lock
    provider = project.get_provider(strategy, tracked_names)
  File "/home/longlone/.local/lib/python3.9/site-packages/pdm/project/core.py", line 305, in get_provider
    preferred_pins = self.get_locked_candidates("__all__")
  File "/home/longlone/.local/lib/python3.9/site-packages/pdm/project/core.py", line 380, in get_locked_candidates
    result[self.meta.project_name.lower()] = self.make_self_candidate(True)
  File "/home/longlone/.local/lib/python3.9/site-packages/pdm/project/core.py", line 348, in make_self_candidate
    req = parse_requirement(pip_shims.path_to_url(self.root.as_posix()), editable)
  File "/home/longlone/.local/lib/python3.9/site-packages/pdm/models/requirements.py", line 464, in parse_requirement
    r = FileRequirement.parse(line, m.groupdict())
  File "/home/longlone/.local/lib/python3.9/site-packages/pdm/models/requirements.py", line 278, in parse
    r = cls(
  File "/home/longlone/.local/lib/python3.9/site-packages/pdm/models/requirements.py", line 258, in __init__
    self._check_installable()
  File "/home/longlone/.local/lib/python3.9/site-packages/pdm/models/requirements.py", line 351, in _check_installable
    result = SetupReader.read_from_directory(self.path.absolute().as_posix())
  File "/home/longlone/.local/lib/python3.9/site-packages/pdm/models/readers.py", line 35, in read_from_directory
    new_result = getattr(cls(), "read_{}".format(filename.replace(".", "_")))(
  File "/home/longlone/.local/lib/python3.9/site-packages/pdm/models/readers.py", line 57, in read_pyproject_toml
    metadata = MutableMetadata(filepath)
  File "/home/longlone/.local/lib/python3.9/site-packages/pdm/project/metadata.py", line 17, in __init__
    data = self._read_pyproject(self.filepath)
  File "/home/longlone/.local/lib/python3.9/site-packages/pdm/project/metadata.py", line 23, in _read_pyproject
    return Metadata._read_pyproject(filepath)
  File "/home/longlone/.local/lib/python3.9/site-packages/pdm/pep517/metadata.py", line 91, in _read_pyproject
    data = toml.loads(self.filepath.read_text(encoding="utf-8"))
AttributeError: 'PosixPath' object has no attribute 'filepath'

## Expected behavior
install module success

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.4.4                               
Python Interpreter: /usr/bin/python3 (3.9.2)            
Project Root:       /home/longlone/workon/python/glimmer
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.2",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "4.19.128-microsoft-standard",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Tue Jun 23 12:58:10 UTC 2020",
  "python_full_version": "3.9.2",
  "platform_python_implementaiton": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

**Comment by WAY29** [comment]
By the way, I can success install module if I use **pdm==1.4.2**

**Comment by frostming** [comment]
Duplicate with, please upgrade # to the latest version
