### ISSUE TITLE
Permission denied: '/usr/bin/easy_install'

### ISSUE THREAD

**Issue by frafra** [pdm-project/pdm#393]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

```
pdm add black -v
```

## Actual behavior

```
Adding packages to default dependencies: black
======== Start resolving requirements ========
        black
        Adding requirement black
Preparing isolated env for PEP 517 build...
Requirement already satisfied: setuptools>=41.0 in /usr/lib/python3.8/site-packages (from -r /tmp/pdm-build-reqs-x8fmgvu2.txt (line 1)) (44.1.1)
Collecting setuptools-scm
  Using cached setuptools_scm-6.0.1-py3-none-any.whl (27 kB)
Collecting wheel
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Installing collected packages: setuptools-scm, wheel
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

setuptools-scm 6.0.1 requires setuptools>=45, but you'll have setuptools 44.1.1 which is incompatible.
Successfully installed setuptools-scm-6.0.1 wheel-0.36.2
Collecting wheel
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Collecting setuptools_scm
  Using cached setuptools_scm-6.0.1-py3-none-any.whl (27 kB)
Collecting setuptools>=45
  Using cached setuptools-56.0.0-py3-none-any.whl (784 kB)
Installing collected packages: wheel, setuptools, setuptools-scm
  Attempting uninstall: setuptools
    Found existing installation: setuptools 44.1.1
    Uninstalling setuptools-44.1.1:
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/bin/easy_install'
Consider using the `--user` option or check the permissions.

Failed to build package, try parsing project files.
Traceback (most recent call last):
  File "/home/frafra/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/models/builders.py", line 90, in log_subprocessor
    subprocess.check_call(
  File "/usr/lib64/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-Im', 'pip', 'install', '--prefix', '/tmp/pdm-build-env-ff0ejhfk', '-r', '/tmp/pdm-build-reqs-pq065_ak.txt']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frafra/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/models/candidates.py", line 164, in get_metadata
    built = self.environment.build(ireq, self.hashes, allow_all_wheels)
  File "/home/frafra/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/models/environment.py", line 317, in build
    return builder.build_wheel(output_dir)
  File "/home/frafra/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/models/builders.py", line 254, in build_wheel
    self.install(requires)
  File "/home/frafra/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/models/builders.py", line 247, in install
    self.subprocess_runner(cmd)
  File "/home/frafra/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/models/builders.py", line 161, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
  File "/home/frafra/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/models/builders.py", line 98, in log_subprocessor
    raise BuildError(f"Call command {cmd} return non-zero status.")
pdm.exceptions.BuildError: Call command ['/usr/bin/python3', '-Im', 'pip', 'install', '--prefix', '/tmp/pdm-build-env-ff0ejhfk', '-r', '/tmp/pdm-build-reqs-pq065_ak.txt'] return non-zero status.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frafra/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/frafra/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/core.py", line 171, in main
    return Core().main(args)
  File "/home/frafra/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/core.py", line 133, in main
    raise err.with_traceback(traceback)
  File "/home/frafra/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/core.py", line 128, in main
    f(options.project, options)
  File "/home/frafra/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/cli/commands/add.py", line 35, in handle
    actions.do_add(
  File "/home/frafra/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/cli/actions.py", line 173, in do_add
    resolved = do_lock(project, strategy, tracked_names, reqs)
  File "/home/frafra/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/cli/actions.py", line 68, in do_lock
    mapping, dependencies, summaries = resolve(
  File "/home/frafra/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/resolver/core.py", line 152, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "/home/frafra/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/resolvelib/resolvers.py", line 453, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/frafra/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/resolvelib/resolvers.py", line 347, in resolve
    failure_causes = self._attempt_to_pin_criterion(name, criterion)
  File "/home/frafra/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/resolvelib/resolvers.py", line 207, in _attempt_to_pin_criterion
    criteria = self._get_criteria_to_update(candidate)
  File "/home/frafra/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/resolvelib/resolvers.py", line 198, in _get_criteria_to_update
    for r in self._p.get_dependencies(candidate):
  File "/home/frafra/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/resolver/providers.py", line 77, in get_dependencies
    deps, requires_python, summary = self.repository.get_dependencies(candidate)
  File "/home/frafra/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/models/repositories.py", line 64, in get_dependencies
    requirements, requires_python, summary = getter(candidate)
  File "/home/frafra/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/models/repositories.py", line 30, in wrapper
    result = func(self, candidate)
  File "/home/frafra/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/models/repositories.py", line 141, in _get_dependencies_from_metadata
    deps = candidate.get_dependencies_from_metadata()
  File "/home/frafra/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/models/candidates.py", line 217, in get_dependencies_from_metadata
    metadata = self.get_metadata()
  File "/home/frafra/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/models/candidates.py", line 169, in get_metadata
    meta_dict = SetupReader.read_from_directory(ireq.unpacked_source_directory)
  File "/home/frafra/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/models/readers.py", line 40, in read_from_directory
    if new_result[key]:
KeyError: 'name'
```

It looks like there is an error because setuptools should be upgraded, but it tries to remove it from the system.

## Expected behavior

No error.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.4.5                               
Python Interpreter: /usr/bin/python3 (3.8.8)            
Project Root:       /home/frafra/Code/viltkamera-manager
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.8",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.9.14-1-default",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Sat Dec 12 06:57:32 UTC 2020 (c648a46)",
  "python_full_version": "3.8.8",
  "platform_python_implementation": "CPython",
  "python_version": "3.8",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
Any chance try the 1.5.0b1 release? you can get it by `pipx upgrade pdm --pip-args="--pre"`

**Comment by frafra** [comment]
It seems to work! :)

**Comment by frostming** [comment]
Thanks, enjoy the new release
