### ISSUE TITLE
pyenv: fails with non-existing ~/.pyenv/shims/python

### ISSUE THREAD

**Issue by blueyed** [pdm-project/pdm#406]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

I am using an experimental/WIP branch with pyenv, where it has shims per version: https://github.com/pyenv/pyenv/pull/1185

This means that although pyenv is detected `/home/user/.pyenv/shims/python` does not exist, and pdm fails like this:

```
% .venv/bin/pdm init -v
Creating a pyproject.toml for PDM...
[5] > /tmp/pdm-test/.venv/lib/python3.9/site-packages/pdm/project/core.py(553)find_interpreters()
-> yield PythonInfo.from_path(os.path.join(PYENV_ROOT, "shims", "python"))
(Pdb++) c
[8] > /tmp/pdm-test/.venv/lib/python3.9/site-packages/pythonfinder/models/python.py(534)parse()
-> version_dict = parse_python_version(str(version))
(Pdb++) version
'python'
(Pdb++) c
Traceback (most recent call last):
  File "/tmp/pdm-test/.venv/lib/python3.9/site-packages/pythonfinder/models/python.py", line 583, in from_path
    instance_dict = cls.parse(path_name)
  File "/tmp/pdm-test/.venv/lib/python3.9/site-packages/pythonfinder/models/python.py", line 534, in parse
    version_dict = parse_python_version(str(version))
  File "/tmp/pdm-test/.venv/lib/python3.9/site-packages/pythonfinder/utils.py", line 131, in parse_python_version
    raise InvalidPythonVersion("%s is not a python version" % version_str)
pythonfinder.exceptions.InvalidPythonVersion: python is not a python version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/pdm-test/.venv/lib/python3.9/site-packages/pythonfinder/models/python.py", line 619, in parse_executable
    result_version = get_python_version(path)
  File "/tmp/pdm-test/.venv/lib/python3.9/site-packages/pythonfinder/utils.py", line 105, in get_python_version
    c = subprocess.Popen(version_cmd, **subprocess_kwargs)
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.pyenv/shims/python'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/pdm-test/.venv/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/tmp/pdm-test/.venv/lib/python3.9/site-packages/pdm/core.py", line 184, in main
    return Core().main(args)
  File "/tmp/pdm-test/.venv/lib/python3.9/site-packages/pdm/core.py", line 145, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/tmp/pdm-test/.venv/lib/python3.9/site-packages/pdm/core.py", line 140, in main
    f(options.project, options)
  File "/tmp/pdm-test/.venv/lib/python3.9/site-packages/pdm/cli/commands/init.py", line 45, in handle
    actions.do_use(project)
  File "/tmp/pdm-test/.venv/lib/python3.9/site-packages/pdm/cli/actions.py", line 424, in do_use
    dict.fromkeys(filter(version_matcher, project.find_interpreters(python)))
  File "/tmp/pdm-test/.venv/lib/python3.9/site-packages/pdm/project/core.py", line 553, in find_interpreters
    yield PythonInfo.from_path(os.path.join(PYENV_ROOT, "shims", "python"))
  File "/tmp/pdm-test/.venv/lib/python3.9/site-packages/pdm/models/python.py", line 27, in from_path
    return cls.from_python_version(PythonVersion.from_path(str(path)))
  File "/tmp/pdm-test/.venv/lib/python3.9/site-packages/pythonfinder/models/python.py", line 585, in from_path
    instance_dict = cls.parse_executable(path.path.absolute().as_posix())
  File "/tmp/pdm-test/.venv/lib/python3.9/site-packages/pythonfinder/models/python.py", line 621, in parse_executable
    raise ValueError("Not a valid python path: %r" % path)
ValueError: Not a valid python path: '/home/user/.pyenv/shims/python'
```

1. I think that using the file path is a good optimization maybe, but it certainly should fall back to `pyenv which python` if it does not exist; but using it always would be more consistent, given that plugins might hook into it to change the behavior also.
2. why is it special-casing pyenv, given that it should be used via `shutil.which("python")` anyway (if wanted/installed)?  FWIW, I am using pyenv mainly for building custom versions, not its local versions etc, where I rather use just specific `.venv` dirs, activated via chdir handlers.
3. the `pythonfinder.exceptions.InvalidPythonVersion: python is not a python version` exception looks suspicious ((why) is it parsing "python" as a Python version!? - is it trying to parse version 3.6 out of "python3.6" there?)] - anyway, that's another project/library

Ref: https://github.com/pdm-project/pdm/issues/36

**Comment by frostming** [comment]
>why is it special-casing pyenv, given that it should be used via `shutil.which("python")`

Because in this way PDM doesn't freeze the python path in `.pdm.toml`, but instead stores a *dynamic* shimmed path there. In this case, pyenv will take the charge to switch the python version.

I never expect PDM can work with a WIP pyenv with breaking changes as such. You can anyway manually specify the python via `pdm use /path/to/python`. Thanks.

**Comment by blueyed** [comment]
> I never expect PDM can work with a WIP pyenv with breaking changes as such.

Sure, fair enough.
However if I had time to finish it up it would likely be something good to merge there, and it would break PDM then.
How would you adopt to it?  By changing the behavior to call `pyenv which python` always?

I'm not sure myself that special-casing pyenv is a good idea, if you rather want something along "always use the `python` from the $PATH" (assuming that pyenv controls it), where the version number might change.

This could be wrapped in another setting, not really to pyenv then probably/maybe instead?
So it could be used with some other wrapper, where you want the behavior of picking up `python` from the $PATH, and/or if you want to use pyenv explicitly (by providing the path to the shim manually/explicitly)

**Comment by frostming** [comment]
You can turn off the behavior by `pdm config python.use_pyenv false`. A file existing check should be added here

**Comment by leogzyl** [comment]
This doesn't seem to be working for me. Maybe this needs to be re-opened?

```zsh
❯ uname -a
Linux XXXXXX 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
❯ pyenv --version
pyenv 2.0.0
❯ pyenv version
system (set by /home/leo/.pyenv/version)
❯ pdm --version
pdm, version 1.6.2
❯ pdm init -v
Creating a pyproject.toml for PDM...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pythonfinder/models/python.py", line 582, in from_path
    instance_dict = cls.parse(path_name)
  File "/usr/local/lib/python3.8/dist-packages/pythonfinder/models/python.py", line 533, in parse
    version_dict = parse_python_version(str(version))
  File "/usr/local/lib/python3.8/dist-packages/pythonfinder/utils.py", line 131, in parse_python_version
    raise InvalidPythonVersion("%s is not a python version" % version_str)
pythonfinder.exceptions.InvalidPythonVersion: python is not a python version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pythonfinder/models/python.py", line 618, in parse_executable
    result_version = get_python_version(path)
  File "/usr/local/lib/python3.8/dist-packages/pythonfinder/utils.py", line 116, in get_python_version
    raise InvalidPythonVersion("%s is not a valid python path" % path)
pythonfinder.exceptions.InvalidPythonVersion: /home/leo/.pyenv/shims/python is not a valid python path

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/pdm/core.py", line 184, in main
    return Core().main(args)
  File "/usr/local/lib/python3.8/dist-packages/pdm/core.py", line 145, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/usr/local/lib/python3.8/dist-packages/pdm/core.py", line 140, in main
    f(options.project, options)
  File "/usr/local/lib/python3.8/dist-packages/pdm/cli/commands/init.py", line 45, in handle
    actions.do_use(project)
  File "/usr/local/lib/python3.8/dist-packages/pdm/cli/actions.py", line 467, in do_use
    dict.fromkeys(filter(version_matcher, project.find_interpreters(python)))
  File "/usr/local/lib/python3.8/dist-packages/pdm/project/core.py", line 558, in find_interpreters
    yield PythonInfo.from_path(pyenv_shim)
  File "/usr/local/lib/python3.8/dist-packages/pdm/models/python.py", line 27, in from_path
    return cls.from_python_version(PythonVersion.from_path(str(path)))
  File "/usr/local/lib/python3.8/dist-packages/pythonfinder/models/python.py", line 584, in from_path
    instance_dict = cls.parse_executable(path.path.absolute().as_posix())
  File "/usr/local/lib/python3.8/dist-packages/pythonfinder/models/python.py", line 620, in parse_executable
    raise ValueError("Not a valid python path: %r" % path)
ValueError: Not a valid python path: '/home/leo/.pyenv/shims/python'
```

OS: Ubuntu 20.04 on WSL
