### ISSUE TITLE
setup_dev.py fails on master: AttributeError: module 'pip._internal.req.req_uninstall' has no attribute 'bin_py'

### ISSUE THREAD

**Issue by blueyed** [pdm-project/pdm#415]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

```
% python setup_dev.py
Creating a venv using /usr/bin/python at /tmp/pdm/env...
Installing base requirements...
…
Successfully installed SecretStorage-3.3.1 appdirs-1.4.4 attrs-20.3.0 cached-property-1.5.2 cffi-1.14.5 click-7.1.2 colorama-0.4.4 cryptography-3.4.7 distlib-0.3.1 importlib-metadata-4.0.1 jeepney-0.6.0 keyring-23.0.1 packaging-20.9 pdm-1.5.1 pdm-pep517-0.7.1 pep517-0.10.0 pip-21.1 pycparser-2.20 pyparsing-2.4.7 python-cfonts-1.4.0 python-dotenv-0.17.0 pythonfinder-1.2.6 resolvelib-0.7.0 shellingham-1.4.0 six-1.15.0 toml-0.10.2 tomlkit-0.7.0 wheel-0.36.2 zipp-3.4.1
Setup project for development...
Using Python interpreter: /usr/bin/python (3.9)
[CHANGE IN 1.5.0]: dev-dependencies are included by default and can be excluded with `--prod` option
Synchronizing working set with lock file: 74 to add, 0 to update, 0 to remove

Traceback (most recent call last):
  File "/tmp/pdm/env/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/tmp/pdm/env/lib/python3.9/site-packages/pdm/core.py", line 184, in main
    return Core().main(args)
  File "/tmp/pdm/env/lib/python3.9/site-packages/pdm/core.py", line 145, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/tmp/pdm/env/lib/python3.9/site-packages/pdm/core.py", line 140, in main
    f(options.project, options)
  File "/tmp/pdm/env/lib/python3.9/site-packages/pdm/cli/commands/install.py", line 41, in handle
    actions.do_sync(
  File "/tmp/pdm/env/lib/python3.9/site-packages/pdm/cli/actions.py", line 127, in do_sync
    handler.synchronize()
  File "/tmp/pdm/env/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 301, in synchronize
    with self.ui.logging("install"), self.environment.activate():
  File "/usr/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/tmp/pdm/env/lib/python3.9/site-packages/pdm/models/environment.py", line 131, in activate
    bin_py = req_uninstall.bin_py
AttributeError: module 'pip._internal.req.req_uninstall' has no attribute 'bin_py'
Traceback (most recent call last):
  File "/tmp/pdm/setup_dev.py", line 62, in <module>
    main()
  File "/tmp/pdm/setup_dev.py", line 38, in main
    subprocess.check_call([venv_pdm, "install", "-vv"])
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/tmp/pdm/env/bin/pdm', 'install', '-vv']' returned non-zero exit status 1.
```

**Comment by blueyed** [comment]
Note that it also fails with 1.5.1 (a37bdb6), where also pip 21.1 is installed/used within the temporary venv.

**Comment by blueyed** [comment]
Might make sense to pin (base) requirements to what is used in `pdm.lock`?  (this would at least not break it for the current release (1.5.1) then)
Code ref: https://github.com/pdm-project/pdm/blob/109ada5426dea83cf62def467d6bf8a5d62ca267/setup_dev.py#L30

**Comment by linw1995** [comment]
This problem is fixed on the master branch. But this change currently unreleased to PyPI.

Below diff is a temporary patch for this problem. @blueyed 

```diff
diff --git a/setup_dev.py b/setup_dev.py
index 17c9dcc..1ab8296 100644
--- a/setup_dev.py
+++ b/setup_dev.py
@@ -26,9 +26,8 @@ def main():
     subprocess.check_call([sys.executable, "-m", "venv", venv_path.as_posix()])
 
     print("Installing base requirements...", flush=True)
-    subprocess.check_call(
-        [venv_python.as_posix(), "-m", "pip", "install", "-U", "pip", "pdm"]
-    )
+    subprocess.check_call([venv_python.as_posix(), "-m", "pip", "install", "-U", "pip"])
+    subprocess.check_call([venv_python.as_posix(), "-m", "pip", "install", "."])
 
     print("Setup project for development...", flush=True)
     venv_pdm = (venv_python.parent / "pdm").as_posix()
```
