### ISSUE TITLE
Invoke Python in a inexistence path when I init a project

### ISSUE THREAD

**Issue by dodorz** [pdm-project/pdm#424]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce
When i run `pdm init`, it returns `[ValueError]: Not a valid python path: 'C:/Tool/Scoop/apps/Python/3.9.1/python.exe'`. But my Python is installed in C:/Tool/Scoop/apps/Python/3.9.4/python.exe now.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:

```

**Comment by frostming** [comment]
How do you reproduce the bug? what is the output of `pdm info && pdm info --env`, `pdm config` output is also useful

**Comment by dodorz** [comment]
Even can't initialized a project, so I don't have `pdm info` and `pdm info --env` output.

**Comment by dodorz** [comment]
The `pdm config` output is:
```
Home configuration (C:\Users\XXX\.pdm\config.toml):
  auto_global = False
  cache_dir = C:\Users\XXX\AppData\Local\pdm\pdm\Cache
  parallel_install = True
  pypi.json_api = False
  pypi.url = https://mirrors.aliyun.com/pypi/simple
  pypi.verify_ssl = True
  python.use_pyenv = True
  strategy.resolve_max_rounds = 1000
  strategy.save = compatible
  strategy.update = reuse
  use_venv = False
```

**Comment by dodorz** [comment]
I have installed pdm with `pipx` or `pip install --user`. But get the same result.

**Comment by frostming** [comment]
What is the version of `pythonfinder` installed with `pdm`?

**Comment by frostming** [comment]
To see the full traceback, you add `-v` to the command.

**Comment by dodorz** [comment]
pythonfinder-1.2.6

**Comment by dodorz** [comment]
The -v result:
```
Creating a pyproject.toml for PDM...
Traceback (most recent call last):
  File "C:\Users\XXX\AppData\Roaming\Python\Python39\site-packages\pythonfinder\models\python.py", line 618, in parse_executable
    result_version = get_python_version(path)
  File "C:\Users\XXX\AppData\Roaming\Python\Python39\site-packages\pythonfinder\utils.py", line 105, in get_python_version
    c = subprocess.Popen(version_cmd, **subprocess_kwargs)
  File "c:\tool\python\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\tool\python\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\tool\python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\tool\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\XXX\AppData\Roaming\Python\Python\Scripts\pdm.exe\__main__.py", line 7, in <module>
  File "C:\Users\XXX\AppData\Roaming\Python\Python39\site-packages\pdm\core.py", line 184, in main
    return Core().main(args)
  File "C:\Users\XXX\AppData\Roaming\Python\Python39\site-packages\pdm\core.py", line 145, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "C:\Users\XXX\AppData\Roaming\Python\Python39\site-packages\pdm\core.py", line 140, in main
    f(options.project, options)
  File "C:\Users\XXX\AppData\Roaming\Python\Python39\site-packages\pdm\cli\commands\init.py", line 45, in handle
    actions.do_use(project)
  File "C:\Users\XXX\AppData\Roaming\Python\Python39\site-packages\pdm\cli\actions.py", line 425, in do_use
    dict.fromkeys(filter(version_matcher, project.find_interpreters(python)))
  File "C:\Users\XXX\AppData\Roaming\Python\Python39\site-packages\pdm\project\core.py", line 576, in find_interpreters
    for entry in finder.find_all_python_versions(*args):
  File "C:\Users\XXX\AppData\Roaming\Python\Python39\site-packages\pythonfinder\pythonfinder.py", line 312, in find_all_python_versions
    python_version_dict = getattr(self.system_path, "python_version_dict", {})
  File "C:\Users\XXX\AppData\Roaming\Python\Python39\site-packages\pythonfinder\pythonfinder.py", line 120, in system_path
    self._system_path = self.create_system_path()
  File "C:\Users\XXX\AppData\Roaming\Python\Python39\site-packages\pythonfinder\pythonfinder.py", line 82, in create_system_path
    return pyfinder_path.SystemPath.create(
  File "C:\Users\XXX\AppData\Roaming\Python\Python39\site-packages\pythonfinder\models\path.py", line 682, in create
    instance = instance._run_setup()
  File "C:\Users\XXX\AppData\Roaming\Python\Python39\site-packages\pythonfinder\models\path.py", line 233, in _run_setup
    new_instance = new_instance._setup_windows()
  File "C:\Users\XXX\AppData\Roaming\Python\Python39\site-packages\pythonfinder\models\path.py", line 411, in _setup_windows
    windows_finder = WindowsFinder.create()
  File "C:\Users\XXX\AppData\Roaming\Python\Python39\site-packages\pythonfinder\models\windows.py", line 146, in create
    return cls()
  File "<attrs generated init pythonfinder.models.windows.WindowsFinder>", line 13, in __init__
  File "C:\Users\XXX\AppData\Roaming\Python\Python39\site-packages\pythonfinder\models\windows.py", line 113, in get_versions
    versions[py_version.version_tuple[:5]] = base_dir
  File "C:\Users\XXX\AppData\Roaming\Python\Python39\site-packages\pythonfinder\models\python.py", line 365, in __getattribute__
    result = super(PythonVersion, self).__getattribute__(key)
  File "C:\Users\XXX\AppData\Roaming\Python\Python39\site-packages\pythonfinder\models\python.py", line 430, in version_tuple
    self.patch,
  File "C:\Users\XXX\AppData\Roaming\Python\Python39\site-packages\pythonfinder\models\python.py", line 375, in __getattribute__
    instance_dict = self.parse_executable(executable)
  File "C:\Users\XXX\AppData\Roaming\Python\Python39\site-packages\pythonfinder\models\python.py", line 620, in parse_executable
    raise ValueError("Not a valid python path: %r" % path)
ValueError: Not a valid python path: 'C:/Tool/Scoop/apps/Python/3.9.1/python.exe'
```

**Comment by frostming** [comment]
You should remove the broken Python records in `regedit`, you can find all versions under `HKEY_CURRENT_USER\SOFTWARE\Python\PythonCore`

**Comment by dodorz** [comment]
Thank you!

**Comment by karolzlot** [comment]
@frostming 

I had the same error.
In my case it was `HKEY_LOCAL_MACHINE\SOFTWARE\Python\PythonCore`

I think as `pdm` popularity will grow, more user will experience this issue. I suggest to improve `pdm` so it can ignore such invalid python paths.

**Comment by frostming** [comment]
@karolzlot What is the version of `pythonfinder` dependency?

**Comment by karolzlot** [comment]
@frostming 1.2.8

![image](https://user-images.githubusercontent.com/11590960/127791817-cffc4b03-84ad-43cc-9001-90099f0e1b2c.png)
