### ISSUE TITLE
"AttributeError" when running pdm init

### ISSUE THREAD

**Issue by sqlgofaster** [pdm-project/pdm#434]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**
```
Traceback (most recent call last):
  File "c:\program files\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python38\Scripts\pdm.exe\__main__.py", line 7, in <module>
  File "c:\program files\python38\lib\site-packages\pdm\core.py", line 184, in main
    return Core().main(args)
  File "c:\program files\python38\lib\site-packages\pdm\core.py", line 145, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "c:\program files\python38\lib\site-packages\pdm\core.py", line 140, in main
    f(options.project, options)
  File "c:\program files\python38\lib\site-packages\pdm\cli\commands\init.py", line 45, in handle
    actions.do_use(project)
  File "c:\program files\python38\lib\site-packages\pdm\cli\actions.py", line 425, in do_use
    dict.fromkeys(filter(version_matcher, project.find_interpreters(python)))
  File "c:\program files\python38\lib\site-packages\pdm\project\core.py", line 576, in find_interpreters
    for entry in finder.find_all_python_versions(*args):
  File "c:\program files\python38\lib\site-packages\pythonfinder\pythonfinder.py", line 328, in find_all_python_versions
    path_list = sorted(filter(None, versions), key=version_sort, reverse=True)
AttributeError: 'NoneType' object has no attribute 'version_sort'
```
## Steps to reproduce
Installed via pipx
run `pdm init`

## Actual behavior

pyproject.toml is not created.

## Expected behavior

pyproject.toml is created.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:

The pyproject.toml has not been initialized yet. You can do this by running 'pdm init'.
pipx version: 0.16.2.1
pip version 21.1.1
```

**Comment by frostming** [comment]
Check if there is any dangling Python entries in regedit, which can be found in key `HKCU/SOFTWARE/Python`

**Comment by sqlgofaster** [comment]
Thanks, I'll check.
