### ISSUE TITLE
Failed execute `pdm add requests` on Mac

### ISSUE THREAD

**Issue by Rhythmicc** [pdm-project/pdm#447]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

I just want to try pdm on my Mac.

## Actual behavior

- [x] `pip3 install pdm`
- [x] `mkdir test`
- [x] `pdm init`
- [ ]  `pdm add requests`

pdm reports following info:
```
❯ pdm add requests
Adding packages to default dependencies: requests
✔ 🔒 Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
Synchronizing working set with lock file: 9 to add, 0 to update, 0 to remove

  ✖ Install certifi 2020.12.5 failed
  ✖ Install chardet 4.0.0 failed
  ✖ Install fastapi 0.63.0 failed
  ✖ Install idna 2.10 failed
  ✖ Install starlette 0.13.6 failed
  ✖ Install pydantic 1.8.1 failed
  ✖ Install requests 2.25.1 failed
  ✖ Install typing-extensions 3.10.0.0 failed
  ✖ Install urllib3 1.26.4 failed
  Retry failed jobs
  ✖ Install chardet 4.0.0 failed
  ✖ Install requests 2.25.1 failed
  ✖ Install fastapi 0.63.0 failed
  ✖ Install idna 2.10 failed
  ✖ Install starlette 0.13.6 failed
  ✖ Install typing-extensions 3.10.0.0 failed
  ✖ Install urllib3 1.26.4 failed
  ✖ Install pydantic 1.8.1 failed
  ✖ Install certifi 2020.12.5 failed

ERRORS:
add chardet failed:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 148, in install_candidate
    installer.install(can)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pdm/installers/installers.py", line 47, in install
    self.install_wheel(candidate.wheel)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pdm/installers/installers.py", line 53, in install_wheel
    enquoted_executable = distlib.scripts.enquote_executable(
AttributeError: module 'distlib.scripts' has no attribute 'enquote_executable'
add requests failed:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 148, in install_candidate
    installer.install(can)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pdm/installers/installers.py", line 47, in install
    self.install_wheel(candidate.wheel)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pdm/installers/installers.py", line 53, in install_wheel
    enquoted_executable = distlib.scripts.enquote_executable(
AttributeError: module 'distlib.scripts' has no attribute 'enquote_executable'
add fastapi failed:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 148, in install_candidate
    installer.install(can)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pdm/installers/installers.py", line 47, in install
    self.install_wheel(candidate.wheel)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pdm/installers/installers.py", line 53, in install_wheel
    enquoted_executable = distlib.scripts.enquote_executable(
AttributeError: module 'distlib.scripts' has no attribute 'enquote_executable'
add idna failed:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 148, in install_candidate
    installer.install(can)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pdm/installers/installers.py", line 47, in install
    self.install_wheel(candidate.wheel)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pdm/installers/installers.py", line 53, in install_wheel
    enquoted_executable = distlib.scripts.enquote_executable(
AttributeError: module 'distlib.scripts' has no attribute 'enquote_executable'
add pydantic failed:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 148, in install_candidate
    installer.install(can)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pdm/installers/installers.py", line 47, in install
    self.install_wheel(candidate.wheel)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pdm/installers/installers.py", line 53, in install_wheel
    enquoted_executable = distlib.scripts.enquote_executable(
AttributeError: module 'distlib.scripts' has no attribute 'enquote_executable'
add urllib3 failed:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 148, in install_candidate
    installer.install(can)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pdm/installers/installers.py", line 47, in install
    self.install_wheel(candidate.wheel)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pdm/installers/installers.py", line 53, in install_wheel
    enquoted_executable = distlib.scripts.enquote_executable(
AttributeError: module 'distlib.scripts' has no attribute 'enquote_executable'
add starlette failed:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 148, in install_candidate
    installer.install(can)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pdm/installers/installers.py", line 47, in install
    self.install_wheel(candidate.wheel)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pdm/installers/installers.py", line 53, in install_wheel
    enquoted_executable = distlib.scripts.enquote_executable(
AttributeError: module 'distlib.scripts' has no attribute 'enquote_executable'
add typing-extensions failed:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 148, in install_candidate
    installer.install(can)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pdm/installers/installers.py", line 47, in install
    self.install_wheel(candidate.wheel)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pdm/installers/installers.py", line 53, in install_wheel
    enquoted_executable = distlib.scripts.enquote_executable(
AttributeError: module 'distlib.scripts' has no attribute 'enquote_executable'
add certifi failed:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 148, in install_candidate
    installer.install(can)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pdm/installers/installers.py", line 47, in install
    self.install_wheel(candidate.wheel)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pdm/installers/installers.py", line 53, in install_wheel
    enquoted_executable = distlib.scripts.enquote_executable(
AttributeError: module 'distlib.scripts' has no attribute 'enquote_executable'

See /var/folders/26/qgv4hgzj1pl_9bv96jqn476r0000gn/T/pdm-install-36zbjz3l.log for detailed debug log.
[InstallationError]: Some package operations are not complete yet
Add '-v' to see the detailed traceback
```

## Expected behavior

Successfully added.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.5.2
Python Interpreter: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 (3.8)
Project Root:       /Users/lianhaocheng/Downloads/test
Project Packages:   /Users/lianhaocheng/Downloads/test/__pypackages__/3.8
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.1",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "20.4.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64",
  "python_full_version": "3.8.1",
  "platform_python_implementation": "CPython",
  "python_version": "3.8",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
You are using an outdated version of `distlib`, please upgrade `distlib` in the same lib as pdm

**Comment by s0undt3ch** [comment]
> You are using an outdated version of distlib, please upgrade distlib in the same lib as pdm

Shouldn't `pdm` specify the minimum version of `distlib` in its requirements?

**Comment by frostming** [comment]
> > You are using an outdated version of distlib, please upgrade distlib in the same lib as pdm
> 
> Shouldn't `pdm` specify the minimum version of `distlib` in its requirements?

It should have, but the API was introduced in a release [10 months ago](https://pypi.org/project/distlib/) and it is hard for downstream projects to investigate which APIs are changed recently and which are stable. This is why we do not recommend installing PDM into the global site-packages as it will unexpectedly reuse a deprecated version of package we are not aware of.

**Comment by s0undt3ch** [comment]
Agreed.
