### ISSUE TITLE
Loses executable bit from dependencies' data files

### ISSUE THREAD

**Issue by oprypin** [pdm-project/pdm#467]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

```bash
pdm init -n
pdm add 'pytype; python_version<"3.10"'
touch test.py
pdm run pytype test.py
```

## Actual behavior

```
Computing dependencies
Analyzing 1 sources with 0 local dependencies
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/pd2/__pypackages__/3.9/lib/ninja/__main__.py", line 4, in <module>
    ninja()
  File "/tmp/pd2/__pypackages__/3.9/lib/ninja/__init__.py", line 50, in ninja
    raise SystemExit(_program('ninja', sys.argv[1:]))
  File "/tmp/pd2/__pypackages__/3.9/lib/ninja/__init__.py", line 46, in _program
    return subprocess.call([os.path.join(BIN_DIR, name)] + args)
  File "/usr/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/tmp/pd2/__pypackages__/3.9/lib/ninja/data/bin/ninja'
Leaving directory '.pytype'
```

## Expected behavior

```
Computing dependencies
Analyzing 1 sources with 0 local dependencies
ninja: Entering directory `.pytype'
[1/1] check test
Leaving directory '.pytype'
Success: no errors found
```

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.5.3                      
Python Interpreter: /usr/bin/python (3.9)      
Project Root:       /tmp/pd2                   
Project Packages:   /tmp/pd2/__pypackages__/3.9
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.4",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.11.16-arch1-1",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT Wed, 21 Apr 2021 17:22:13 +0000",
  "python_full_version": "3.9.4",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
It is an issue of the installer from `distlib`. You should report it upstream.

**Comment by frostming** [comment]
I was not blaming you that it shouldn't have been reported here, but I was asking for excuses that it would not be likely dealt with shortly.

**Comment by frostming** [comment]
Here it is: https://bitbucket.org/pypa/distlib/issues/147/distlibwheelwheelinstall-loses-the

**Comment by frostming** [comment]
This issue has been fixed upstream and released: https://pypi.org/project/distlib/0.3.2/

You may need to upgrade `distlib` or perform a fresh re-install of PDM. Make sure `distlib 0.3.2` is installed. This issue can be closed now.
