### ISSUE TITLE
Resolution failure with python >= 3.6, and >= 3.7 markers for dev-deps

### ISSUE THREAD

**Issue by pawamoy** [pdm-project/pdm#476]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

Followup of https://github.com/pdm-project/pdm/issues/454#issuecomment-846662543

## Steps to reproduce

<details><summary><code>pyproject.toml</code></summary>

```toml
[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

[project]
name = "pawamoy-testing"
version = {use_scm = true}
description = "Testing this great template"
authors = [{name = "Timothee Mazzucotelli", email = "pawamoy@pm.me"}]
license = {file = "LICENSE"}
readme = "README.md"
requires-python = ">=3.6"
dynamic = ["version", "classifiers"]
classifiers = ["Development Status :: 4 - Beta"]
dependencies = []

[project.scripts]
pawamoy-testing = "pawamoy_testing.cli:main"

[project.urls]
Repository = "https://github.com/pawamoy/pawamoy-testing"
Homepage = "https://github.com/pawamoy/pawamoy-testing"

[tool.pdm]
package-dir = "src"

[tool.pdm.dev-dependencies]
duty = ["duty~=0.6"]
docs = [
    "mkdocs~=1.1; python_version >= '3.7'",
    "mkdocs-coverage~=0.2; python_version >= '3.7'",
    "mkdocs-gen-files~=0.3; python_version >= '3.7'",
    "mkdocs-literate-nav~=0.3; python_version >= '3.7'",
    "mkdocs-material~=7.1; python_version >= '3.7'",
    "mkdocs-section-index~=0.3; python_version >= '3.7'",
    "mkdocstrings~=0.15; python_version >= '3.7'",
    "toml~=0.10; python_version >= '3.7'",
]
format = [
    "autoflake~=1.4",
    "black~=20.8b1",
    "isort~=5.8",
]
maintain = [
    # TODO: remove this section when git-changelog is more powerful
    "git-changelog~=0.4",
]
quality = [
    "darglint~=1.7",
    "flake8-bandit~=2.1",
    "flake8-black~=0.2",
    "flake8-bugbear~=21.3",
    "flake8-builtins~=1.5",
    "flake8-comprehensions~=3.4",
    "flake8-docstrings~=1.6",
    "flake8-pytest-style~=1.4",
    "flake8-string-format~=0.3",
    "flake8-tidy-imports~=4.2",
    "flake8-variables-names~=0.0",
    "pep8-naming~=0.11",
    "wps-light~=0.15",
]
tests = [
    "pytest~=6.2",
    "pytest-cov~=2.11",
    "pytest-randomly~=3.6",
    "pytest-sugar~=0.9",
    "pytest-xdist~=2.2",
]
typing = ["mypy~=0.812"]
```

</details>

<details><summary><code>pdm lock -v</code></summary>

```console
% pdm lock -v
======== Start resolving requirements ========
	autoflake~=1.4
	black~=20.8b1
	isort~=5.8
	duty~=0.6
	mypy~=0.812
	git-changelog~=0.4
	mkdocs~=1.1; python_version >= "3.7"
	mkdocs-coverage~=0.2; python_version >= "3.7"
	mkdocs-gen-files~=0.3; python_version >= "3.7"
	mkdocs-literate-nav~=0.3; python_version >= "3.7"
	mkdocs-material~=7.1; python_version >= "3.7"
	mkdocs-section-index~=0.3; python_version >= "3.7"
	mkdocstrings~=0.15; python_version >= "3.7"
	toml~=0.10; python_version >= "3.7"
	darglint~=1.7
	flake8-bandit~=2.1
	flake8-black~=0.2
	flake8-bugbear~=21.3
	flake8-builtins~=1.5
	flake8-comprehensions~=3.4
	flake8-docstrings~=1.6
	flake8-pytest-style~=1.4
	flake8-string-format~=0.3
	flake8-tidy-imports~=4.2
	flake8-variables-names~=0.0
	pep8-naming~=0.11
	wps-light~=0.15
	pytest~=6.2
	pytest-cov~=2.11
	pytest-randomly~=3.6
	pytest-sugar~=0.9
	pytest-xdist~=2.2
	Adding requirement autoflake~=1.4
	Found matching candidates:
	  <Candidate autoflake 1.4 from https://pypi.org/simple/autoflake/>
	Adding requirement black~=20.8b1
	Found matching candidates:
	  <Candidate black 20.8b1 from https://pypi.org/simple/black/>
	Adding requirement isort~=5.8
	Found matching candidates:
	  <Candidate isort 5.8.0 from https://pypi.org/simple/isort/>
	Adding requirement duty~=0.6
	Found matching candidates:
	  <Candidate duty 0.6.0 from https://pypi.org/simple/duty/>
	Adding requirement mypy~=0.812
	Found matching candidates:
	  <Candidate mypy 0.812 from https://pypi.org/simple/mypy/>
	Adding requirement git-changelog~=0.4
	Found matching candidates:
	  <Candidate git-changelog 0.4.2 from https://pypi.org/simple/git-changelog/>
	  <Candidate git-changelog 0.4.1 from https://pypi.org/simple/git-changelog/>
	  <Candidate git-changelog 0.4.0 from https://pypi.org/simple/git-changelog/>
	Adding requirement mkdocs~=1.1; python_version >= "3.7"
	Found matching candidates:
	  <Candidate mkdocs 1.1.2 from https://pypi.org/simple/mkdocs/>
	  <Candidate mkdocs 1.1.1 from https://pypi.org/simple/mkdocs/>
	  <Candidate mkdocs 1.1 from https://pypi.org/simple/mkdocs/>
	Adding requirement mkdocs-coverage~=0.2; python_version >= "3.7"
	Found matching candidates:
	  <Candidate mkdocs-coverage 0.2.4 from https://pypi.org/simple/mkdocs-coverage/>
	  <Candidate mkdocs-coverage 0.2.3 from https://pypi.org/simple/mkdocs-coverage/>
	  <Candidate mkdocs-coverage 0.2.1 from https://pypi.org/simple/mkdocs-coverage/>
	  <Candidate mkdocs-coverage 0.2.0 from https://pypi.org/simple/mkdocs-coverage/>
	Adding requirement mkdocs-gen-files~=0.3; python_version >= "3.7"
	Found matching candidates:
	  <Candidate mkdocs-gen-files 0.3.2 from https://pypi.org/simple/mkdocs-gen-files/>
	  <Candidate mkdocs-gen-files 0.3.1 from https://pypi.org/simple/mkdocs-gen-files/>
	  <Candidate mkdocs-gen-files 0.3.0 from https://pypi.org/simple/mkdocs-gen-files/>
	Adding requirement mkdocs-literate-nav~=0.3; python_version >= "3.7"
	Found matching candidates:
	  <Candidate mkdocs-literate-nav 0.3.1 from https://pypi.org/simple/mkdocs-literate-nav/>
	  <Candidate mkdocs-literate-nav 0.3.0 from https://pypi.org/simple/mkdocs-literate-nav/>
	Adding requirement mkdocs-material~=7.1; python_version >= "3.7"
	Found matching candidates:
	  <Candidate mkdocs-material 7.1.5 from https://pypi.org/simple/mkdocs-material/>
	  <Candidate mkdocs-material 7.1.4 from https://pypi.org/simple/mkdocs-material/>
	  <Candidate mkdocs-material 7.1.3 from https://pypi.org/simple/mkdocs-material/>
	  <Candidate mkdocs-material 7.1.2 from https://pypi.org/simple/mkdocs-material/>
	  <Candidate mkdocs-material 7.1.1 from https://pypi.org/simple/mkdocs-material/>
	  <Candidate mkdocs-material 7.1.0 from https://pypi.org/simple/mkdocs-material/>
	Adding requirement mkdocs-section-index~=0.3; python_version >= "3.7"
	Found matching candidates:
	  <Candidate mkdocs-section-index 0.3.0 from https://pypi.org/simple/mkdocs-section-index/>
	Adding requirement mkdocstrings~=0.15; python_version >= "3.7"
	Found matching candidates:
	  <Candidate mkdocstrings 0.15.1 from https://pypi.org/simple/mkdocstrings/>
	  <Candidate mkdocstrings 0.15.0 from https://pypi.org/simple/mkdocstrings/>
	Adding requirement toml~=0.10; python_version >= "3.7"
	Found matching candidates:
	  <Candidate toml 0.10.2 from https://pypi.org/simple/toml/>
	  <Candidate toml 0.10.1 from https://pypi.org/simple/toml/>
	  <Candidate toml 0.10.0 from https://pypi.org/simple/toml/>
	Adding requirement darglint~=1.7
	Found matching candidates:
	  <Candidate darglint 1.8.0 from https://pypi.org/simple/darglint/>
	  <Candidate darglint 1.7.0 from https://pypi.org/simple/darglint/>
	Adding requirement flake8-bandit~=2.1
	Found matching candidates:
	  <Candidate flake8-bandit 2.1.2 from https://pypi.org/simple/flake8-bandit/>
	  <Candidate flake8-bandit 2.1.1 from https://pypi.org/simple/flake8-bandit/>
	  <Candidate flake8-bandit 2.1.0 from https://pypi.org/simple/flake8-bandit/>
	Adding requirement flake8-black~=0.2
	Found matching candidates:
	  <Candidate flake8-black 0.2.1 from https://pypi.org/simple/flake8-black/>
	  <Candidate flake8-black 0.2.0 from https://pypi.org/simple/flake8-black/>
	Adding requirement flake8-bugbear~=21.3
	Found matching candidates:
	  <Candidate flake8-bugbear 21.4.3 from https://pypi.org/simple/flake8-bugbear/>
	  <Candidate flake8-bugbear 21.4.2 from https://pypi.org/simple/flake8-bugbear/>
	  <Candidate flake8-bugbear 21.4.1 from https://pypi.org/simple/flake8-bugbear/>
	  <Candidate flake8-bugbear 21.3.2 from https://pypi.org/simple/flake8-bugbear/>
	  <Candidate flake8-bugbear 21.3.1 from https://pypi.org/simple/flake8-bugbear/>
	Adding requirement flake8-builtins~=1.5
	Found matching candidates:
	  <Candidate flake8-builtins 1.5.3 from https://pypi.org/simple/flake8-builtins/>
	  <Candidate flake8-builtins 1.5.2 from https://pypi.org/simple/flake8-builtins/>
	  <Candidate flake8-builtins 1.5.1 from https://pypi.org/simple/flake8-builtins/>
	  <Candidate flake8-builtins 1.5.0 from https://pypi.org/simple/flake8-builtins/>
	Adding requirement flake8-comprehensions~=3.4
	Found matching candidates:
	  <Candidate flake8-comprehensions 3.5.0 from https://pypi.org/simple/flake8-comprehensions/>
	  <Candidate flake8-comprehensions 3.4.0 from https://pypi.org/simple/flake8-comprehensions/>
	Adding requirement flake8-docstrings~=1.6
	Found matching candidates:
	  <Candidate flake8-docstrings 1.6.0 from https://pypi.org/simple/flake8-docstrings/>
	Adding requirement flake8-pytest-style~=1.4
	Found matching candidates:
	  <Candidate flake8-pytest-style 1.4.2 from https://pypi.org/simple/flake8-pytest-style/>
	  <Candidate flake8-pytest-style 1.4.1 from https://pypi.org/simple/flake8-pytest-style/>
	  <Candidate flake8-pytest-style 1.4.0 from https://pypi.org/simple/flake8-pytest-style/>
	Adding requirement flake8-string-format~=0.3
	Found matching candidates:
	  <Candidate flake8-string-format 0.3.0 from https://pypi.org/simple/flake8-string-format/>
	Adding requirement flake8-tidy-imports~=4.2
	Found matching candidates:
	  <Candidate flake8-tidy-imports 4.3.0 from https://pypi.org/simple/flake8-tidy-imports/>
	  <Candidate flake8-tidy-imports 4.2.1 from https://pypi.org/simple/flake8-tidy-imports/>
	  <Candidate flake8-tidy-imports 4.2.0 from https://pypi.org/simple/flake8-tidy-imports/>
	Adding requirement flake8-variables-names~=0.0
	Found matching candidates:
	  <Candidate flake8-variables-names 0.0.4 from https://pypi.org/simple/flake8-variables-names/>
	  <Candidate flake8-variables-names 0.0.3 from https://pypi.org/simple/flake8-variables-names/>
	  <Candidate flake8-variables-names 0.0.2 from https://pypi.org/simple/flake8-variables-names/>
	  <Candidate flake8-variables-names 0.0.1 from https://pypi.org/simple/flake8-variables-names/>
	Adding requirement pep8-naming~=0.11
	Found matching candidates:
	  <Candidate pep8-naming 0.11.1 from https://pypi.org/simple/pep8-naming/>
	  <Candidate pep8-naming 0.11.0 from https://pypi.org/simple/pep8-naming/>
	Adding requirement wps-light~=0.15
	Found matching candidates:
	  <Candidate wps-light 0.15.2 from https://pypi.org/simple/wps-light/>
	Adding requirement pytest~=6.2
	Found matching candidates:
	  <Candidate pytest 6.2.4 from https://pypi.org/simple/pytest/>
	  <Candidate pytest 6.2.3 from https://pypi.org/simple/pytest/>
	  <Candidate pytest 6.2.2 from https://pypi.org/simple/pytest/>
	  <Candidate pytest 6.2.1 from https://pypi.org/simple/pytest/>
	  <Candidate pytest 6.2.0 from https://pypi.org/simple/pytest/>
	Adding requirement pytest-cov~=2.11
	Found matching candidates:
	  <Candidate pytest-cov 2.12.0 from https://pypi.org/simple/pytest-cov/>
	  <Candidate pytest-cov 2.11.1 from https://pypi.org/simple/pytest-cov/>
	  <Candidate pytest-cov 2.11.0 from https://pypi.org/simple/pytest-cov/>
	Adding requirement pytest-randomly~=3.6
	Found matching candidates:
	  <Candidate pytest-randomly 3.8.0 from https://pypi.org/simple/pytest-randomly/>
	  <Candidate pytest-randomly 3.7.0 from https://pypi.org/simple/pytest-randomly/>
	  <Candidate pytest-randomly 3.6.0 from https://pypi.org/simple/pytest-randomly/>
	Adding requirement pytest-sugar~=0.9
	Found matching candidates:
	  <Candidate pytest-sugar 0.9.4 from https://pypi.org/simple/pytest-sugar/>
	  <Candidate pytest-sugar 0.9.3 from https://pypi.org/simple/pytest-sugar/>
	  <Candidate pytest-sugar 0.9.2 from https://pypi.org/simple/pytest-sugar/>
	  <Candidate pytest-sugar 0.9.1 from https://pypi.org/simple/pytest-sugar/>
	  <Candidate pytest-sugar 0.9.0 from https://pypi.org/simple/pytest-sugar/>
	Adding requirement pytest-xdist~=2.2
	Found matching candidates:
	  <Candidate pytest-xdist 2.2.1 from https://pypi.org/simple/pytest-xdist/>
	  <Candidate pytest-xdist 2.2.0 from https://pypi.org/simple/pytest-xdist/>
	Adding requirement pyflakes>=1.1.0(from autoflake 1.4)
	Found matching candidates:
	  <Candidate pyflakes 2.3.1 from https://pypi.org/simple/pyflakes/>
	  <Candidate pyflakes 2.3.0 from https://pypi.org/simple/pyflakes/>
	  <Candidate pyflakes 2.2.0 from https://pypi.org/simple/pyflakes/>
	  <Candidate pyflakes 2.1.1 from https://pypi.org/simple/pyflakes/>
	  <Candidate pyflakes 2.1.0 from https://pypi.org/simple/pyflakes/>
	  <Candidate pyflakes 2.0.0 from https://pypi.org/simple/pyflakes/>
	  <Candidate pyflakes 1.6.0 from https://pypi.org/simple/pyflakes/>
	  <Candidate pyflakes 1.5.0 from https://pypi.org/simple/pyflakes/>
	  <Candidate pyflakes 1.4.0 from https://pypi.org/simple/pyflakes/>
	  <Candidate pyflakes 1.3.0 from https://pypi.org/simple/pyflakes/>
	  ... [20 more candidate(s)]
Resolving: autoflake 1.4
	New pin: autoflake 1.4
======== Ending round 0 ========
	Adding requirement click>=7.1.2(from black 20.8b1)
	Found matching candidates:
	  <Candidate click 8.0.1 from https://pypi.org/simple/click/>
	  <Candidate click 8.0.0 from https://pypi.org/simple/click/>
	  <Candidate click 7.1.2 from https://pypi.org/simple/click/>
	Adding requirement appdirs(from black 20.8b1)
	Found matching candidates:
	  <Candidate appdirs 1.4.4 from https://pypi.org/simple/appdirs/>
	  <Candidate appdirs 1.4.3 from https://pypi.org/simple/appdirs/>
	  <Candidate appdirs 1.4.2 from https://pypi.org/simple/appdirs/>
	  <Candidate appdirs 1.4.1 from https://pypi.org/simple/appdirs/>
	  <Candidate appdirs 1.4.0 from https://pypi.org/simple/appdirs/>
	  <Candidate appdirs 1.3.0 from https://pypi.org/simple/appdirs/>
	  <Candidate appdirs 1.2.0 from https://pypi.org/simple/appdirs/>
	  <Candidate appdirs 1.1.0 from https://pypi.org/simple/appdirs/>
	Adding requirement toml>=0.10.1(from black 20.8b1)
	Found matching candidates:
	  <Candidate toml 0.10.2 from https://pypi.org/simple/toml/>
	  <Candidate toml 0.10.1 from https://pypi.org/simple/toml/>
	  <Candidate toml 0.10.0 from https://pypi.org/simple/toml/>
	Adding requirement typed-ast>=1.4.0(from black 20.8b1)
	Found matching candidates:
	  <Candidate typed-ast 1.4.3 from https://pypi.org/simple/typed-ast/>
	  <Candidate typed-ast 1.4.2 from https://pypi.org/simple/typed-ast/>
	  <Candidate typed-ast 1.4.1 from https://pypi.org/simple/typed-ast/>
	  <Candidate typed-ast 1.4.0 from https://pypi.org/simple/typed-ast/>
	Adding requirement regex>=2020.1.8(from black 20.8b1)
	Found matching candidates:
	  <Candidate regex 2021.4.4 from https://pypi.org/simple/regex/>
	  <Candidate regex 2021.3.17 from https://pypi.org/simple/regex/>
	  <Candidate regex 2020.11.13 from https://pypi.org/simple/regex/>
	  <Candidate regex 2020.11.11 from https://pypi.org/simple/regex/>
	  <Candidate regex 2020.10.28 from https://pypi.org/simple/regex/>
	  <Candidate regex 2020.10.23 from https://pypi.org/simple/regex/>
	  <Candidate regex 2020.10.22 from https://pypi.org/simple/regex/>
	  <Candidate regex 2020.10.15 from https://pypi.org/simple/regex/>
	  <Candidate regex 2020.10.11 from https://pypi.org/simple/regex/>
	  <Candidate regex 2020.9.27 from https://pypi.org/simple/regex/>
	  ... [542 more candidate(s)]
	Adding requirement pathspec<1,>=0.6(from black 20.8b1)
	Found matching candidates:
	  <Candidate pathspec 0.8.1 from https://pypi.org/simple/pathspec/>
	  <Candidate pathspec 0.8.0 from https://pypi.org/simple/pathspec/>
	  <Candidate pathspec 0.7.0 from https://pypi.org/simple/pathspec/>
	  <Candidate pathspec 0.6.0 from https://pypi.org/simple/pathspec/>
	Adding requirement typing-extensions>=3.7.4(from black 20.8b1)
	Found matching candidates:
	  <Candidate typing-extensions 3.10.0.0 from https://pypi.org/simple/typing-extensions/>
	  <Candidate typing-extensions 3.7.4.3 from https://pypi.org/simple/typing-extensions/>
	  <Candidate typing-extensions 3.7.4.2 from https://pypi.org/simple/typing-extensions/>
	  <Candidate typing-extensions 3.7.4.1 from https://pypi.org/simple/typing-extensions/>
	  <Candidate typing-extensions 3.7.4 from https://pypi.org/simple/typing-extensions/>
	Adding requirement mypy-extensions>=0.4.3(from black 20.8b1)
	Found matching candidates:
	  <Candidate mypy-extensions 0.4.3 from https://pypi.org/simple/mypy-extensions/>
	Adding requirement dataclasses>=0.6; python_version < "3.7"(from black 20.8b1)
	Found matching candidates:
	  <Candidate dataclasses 0.8 from https://pypi.org/simple/dataclasses/>
	  <Candidate dataclasses 0.7 from https://pypi.org/simple/dataclasses/>
	  <Candidate dataclasses 0.6 from https://pypi.org/simple/dataclasses/>
Resolving: black 20.8b1
	New pin: black 20.8b1
======== Ending round 1 ========
Resolving: isort 5.8.0
	New pin: isort 5.8.0
======== Ending round 2 ========
	Adding requirement cached-property<2.0.0,>=1.5.2; python_version < "3.8"(from duty 0.6.0)
	Found matching candidates:
	  <Candidate cached-property 1.5.2 from https://pypi.org/simple/cached-property/>
	Adding requirement failprint<0.7.0,>=0.6.2(from duty 0.6.0)
	Found matching candidates:
	  <Candidate failprint 0.6.2 from https://pypi.org/simple/failprint/>
Resolving: duty 0.6.0
	New pin: duty 0.6.0
======== Ending round 3 ========
	Adding requirement dataclasses<0.8,>=0.7; python_version < "3.7"(from mkdocs-section-index 0.3.0)
	Found matching candidates:
	  <Candidate dataclasses 0.8 from https://pypi.org/simple/dataclasses/>
	  <Candidate dataclasses 0.7 from https://pypi.org/simple/dataclasses/>
	  <Candidate dataclasses 0.6 from https://pypi.org/simple/dataclasses/>
	Adding requirement dataclasses<0.8,>=0.7; python_version < "3.7"(from mkdocs-section-index 0.3.0)
	Found matching candidates:
	  <Candidate dataclasses 0.8 from https://pypi.org/simple/dataclasses/>
	  <Candidate dataclasses 0.7 from https://pypi.org/simple/dataclasses/>
	  <Candidate dataclasses 0.6 from https://pypi.org/simple/dataclasses/>
Candidate rejected: duty 0.6.0
Backtracking...
	Found matching candidates:
	  <Candidate duty 0.6.0 from https://pypi.org/simple/duty/>
Candidate rejected: isort 5.8.0
Backtracking...
	Found matching candidates:
	  <Candidate isort 5.8.0 from https://pypi.org/simple/isort/>
Candidate rejected: black 20.8b1
Backtracking...
	Found matching candidates:
	  <Candidate black 20.8b1 from https://pypi.org/simple/black/>
Candidate rejected: autoflake 1.4
Backtracking...
	Found matching candidates:
	  <Candidate autoflake 1.4 from https://pypi.org/simple/autoflake/>
🔒 Lock failed
Unable to find a resolution that satisfies the following requirements:
  dataclasses>=0.6; python_version < "3.7" (from <Candidate black 20.8b1 from https://pypi.org/simple/black/>)
  dataclasses<0.8,>=0.7; python_version < "3.7" (from <Candidate mkdocs-section-index 0.3.0 from https://pypi.org/simple/mkdocs-section-index/>)
  dataclasses>=0.6; python_version < "3.7" (from <Candidate black 20.8b1 from https://pypi.org/simple/black/>)
  dataclasses<0.8,>=0.7; python_version < "3.7" (from <Candidate mkdocs-section-index 0.3.0 from https://pypi.org/simple/mkdocs-section-index/>)
Please make sure the package names are correct. If so, you can either loosen the version constraints of these dependencies, or set a narrower `requires-python` range in the pyproject.toml.
Traceback (most recent call last):
  File "/home/pawamoy/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/core.py", line 184, in main
    return Core().main(args)
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/core.py", line 145, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/core.py", line 140, in main
    f(options.project, options)
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/cli/commands/lock.py", line 12, in handle
    actions.do_lock(project)
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/cli/actions.py", line 64, in do_lock
    mapping, dependencies, summaries = resolve(
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/resolver/core.py", line 150, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.9/site-packages/resolvelib/resolvers.py", line 473, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.9/site-packages/resolvelib/resolvers.py", line 377, in resolve
    raise ResolutionImpossible(causes)
resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=<NamedRequirement dataclasses>=0.6; python_version < "3.7">, parent=<Candidate black 20.8b1 from https://pypi.org/simple/black/>), RequirementInformation(requirement=<NamedRequirement dataclasses<0.8,>=0.7; python_version < "3.7">, parent=<Candidate mkdocs-section-index 0.3.0 from https://pypi.org/simple/mkdocs-section-index/>), RequirementInformation(requirement=<NamedRequirement dataclasses>=0.6; python_version < "3.7">, parent=<Candidate black 20.8b1 from https://pypi.org/simple/black/>), RequirementInformation(requirement=<NamedRequirement dataclasses<0.8,>=0.7; python_version < "3.7">, parent=<Candidate mkdocs-section-index 0.3.0 from https://pypi.org/simple/mkdocs-section-index/>)]
```

</details>

## Actual behavior

Emphasis on

```
  dataclasses>=0.6; python_version < "3.7" (from <Candidate black 20.8b1 from https://pypi.org/simple/black/>)
  dataclasses<0.8,>=0.7; python_version < "3.7" (from <Candidate mkdocs-section-index 0.3.0 from https://pypi.org/simple/mkdocs-section-index/>)
```

...which doesn't seem unresolvable to me :thinking:

## Expected behavior

Should probably resolve to dataclasses==0.7 for Python 3.6, and no dataclasses for Python 3.7+?

## Environment Information

```console
% pdm info && pdm info --env
PDM version:        1.5.3                                                          
Python Interpreter: /home/pawamoy/.basher-packages/pyenv/pyenv/shims/python (3.9)  
Project Root:       /media/data/dev/pawamoy/copier-pdm/tests/tmp                   
Project Packages:   /media/data/dev/pawamoy/copier-pdm/tests/tmp/__pypackages__/3.9
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.5",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.12.5-arch1-1",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT Wed, 19 May 2021 10:32:40 +0000",
  "python_full_version": "3.9.5",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
A minimal reproducible example:

```
[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

[project]
name = "pawamoy-testing"
version = {use_scm = true}
description = "Testing this great template"
authors = [{name = "Timothee Mazzucotelli", email = "pawamoy@pm.me"}]
license = {file = "LICENSE"}
readme = "README.md"
requires-python = ">=3.6"
dynamic = ["version", "classifiers"]
classifiers = ["Development Status :: 4 - Beta"]
dependencies = []

[project.scripts]
pawamoy-testing = "pawamoy_testing.cli:main"

[project.urls]
Repository = "https://github.com/pawamoy/pawamoy-testing"
Homepage = "https://github.com/pawamoy/pawamoy-testing"

[tool.pdm]
package-dir = "src"

[tool.pdm.dev-dependencies]
docs = [
    "mkdocs-section-index~=0.3; python_version >= '3.7'"
]
format = [
    "black~=20.8b1"
]
```

**Comment by frostming** [comment]
It was fixed in https://github.com/pdm-project/pdm/commit/ccfb4dffc53c3dd20aacd27a3f90b39dd2b061d1
