### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'sections'

### ISSUE THREAD

**Issue by blueyed** [pdm-project/pdm#484]
0fd62dc7fb7e244a00392c4a6f6801617b63e05e (https://github.com/pdm-project/pdm/pull/471) introduced a regression when using the `update` action:

```
% python -m pdbpp -m pdm update django -p test -v
[1] > …/Vcs/pdm/pdm/__main__.py(1)<module>()
-> from pdm.core import main
(Pdb++) c
Updating packages: django.
<class 'pdm.models.requirements.NamedRequirement'>
Traceback (most recent call last):
  File "/usr/lib/python3.9/pdb.py", line 1703, in main
    pdb._runmodule(mainpyfile)
  File "/usr/lib/python3.9/pdb.py", line 1547, in _runmodule
    self.run(code)
  File "/usr/lib/python3.9/bdb.py", line 580, in run
    exec(cmd, globals, locals)
  File "…/Vcs/pdm/pdm/__main__.py", line 1, in <module>
    from pdm.core import main
  File "…/Vcs/pdm/pdm/core.py", line 184, in main
    return Core().main(args)
  File "…/Vcs/pdm/pdm/core.py", line 145, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "…/Vcs/pdm/pdm/core.py", line 140, in main
    f(options.project, options)
  File "…/Vcs/pdm/pdm/cli/commands/update.py", line 48, in handle
    actions.do_update(
  File "…/Vcs/pdm/pdm/cli/actions.py", line 275, in do_update
    resolved = do_model1(
  File "…/Vcs/pdm/pdm/cli/actions.py", line 49, in do_model1
    provider = project.get_provider(strategy, tracked_names)
  File "…/Vcs/pdm/pdm/project/core.py", line 342, in get_provider
    locked_repository = self.locked_repository
  File "…/Vcs/pdm/pdm/project/core.py", line 319, in locked_repository
    return LockedRepository(lockfile, self.sources, self.environment)
  File "…/Vcs/pdm/pdm/models/repositories.py", line 345, in __init__
    self._read_lockfile(lockfile)
  File "…/Vcs/pdm/pdm/models/repositories.py", line 362, in _read_lockfile
    req = Requirement.from_req_dict(package_name, req_dict)
  File "…/Vcs/pdm/pdm/models/requirements.py", line 163, in from_req_dict
    return NamedRequirement.create(name=name, **req_dict)
  File "…/Vcs/pdm/pdm/models/requirements.py", line 146, in create
    return cls(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'sections'
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
[15] > …/Vcs/pdm/pdm/models/requirements.py(146)create()
-> return cls(**kwargs)
(Pdb++) cls
<class 'pdm.models.requirements.NamedRequirement'>
(Pdb++) kwargs
{'name': 'asgiref', 'sections': ['default'], 'specifier': <SpecifierSet('==3.3.1')>}
(Pdb++)
```

(maybe) relevant deps:
```
pdm                1.5.4.dev50+g0fd62dc
pdm-pep517         0.7.1
pep517             0.10.0
pip                20.2.3
```

Let me know if more information is required, e.g. a minimal producer, but hopefully it is clear.

Note: there's also a stray `print` left: https://github.com/pdm-project/pdm/blob/0fd62dc7fb7e244a00392c4a6f6801617b63e05e/pdm/models/requirements.py#L136

**Comment by frostming** [comment]
You are not on the latest commit of master branch

**Comment by frostming** [comment]
Thanks for the catch, it turns out a bug not cleaned with the new implementation

**Comment by blueyed** [comment]
> You are not on the latest commit of master branch

I've checked with latest master also, but then git-bisected it.
Sorry for not making that clearer, and thanks for the quick fix!
