### ISSUE TITLE
PDM breaks on attempting its publicized package add (pytest)

### ISSUE THREAD

**Issue by koenera** [pdm-project/pdm#486]
- [ x] I have searched the issue tracker and believe that this is not a duplicate.

(Similar bugs were reported, but it isn't clear to me that the bug was either fixed or is the same.)

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

(Following exactly the description in your article: https://dev.to/frostming/a-review-pipenv-vs-poetry-vs-pdm-39b4)

```
Clean install of PDM:
pip install --user pdm && pdm --pep582 >> .bashrc
pdm completion bash > pdm.bash-completion && sudo cp pdm.bash-completion /etc/bash_completion.d/ && rm pdm.bash-completion
```

Then initialize project:

`pdm init`

Simply accepted all default ansers to the questions, resulting in the followng `pyproject.toml`:

```
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Randal A. Koene", email = "rkoene@carboncopies.org"},
]
dependencies = []
requires-python = ">=3.8"
dynamic = ["classifiers"]
license = {text = "MIT"}

[project.urls]
homepage = ""

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"
```

Now, exactly as stated in the article: "**Now let's add one dependency pytest from a clean project.**"

`pdm add pytest`

(Let's actually do it with `-v` for this report.)

`pdm add pytest -v`

## Actual behavior

```
Adding packages to default dependencies: pytest
Traceback (most recent call last):
  File "/home/randalk/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/randalk/.local/lib/python3.8/site-packages/pdm/core.py", line 184, in main
    return Core().main(args)
  File "/home/randalk/.local/lib/python3.8/site-packages/pdm/core.py", line 145, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/home/randalk/.local/lib/python3.8/site-packages/pdm/core.py", line 140, in main
    f(options.project, options)
  File "/home/randalk/.local/lib/python3.8/site-packages/pdm/cli/commands/add.py", line 35, in handle
    actions.do_add(
  File "/home/randalk/.local/lib/python3.8/site-packages/pdm/cli/actions.py", line 173, in do_add
    resolved = do_lock(project, strategy, tracked_names, reqs)
  File "/home/randalk/.local/lib/python3.8/site-packages/pdm/cli/actions.py", line 64, in do_lock
    mapping, dependencies, summaries = resolve(
  File "/home/randalk/.local/lib/python3.8/site-packages/pdm/resolver/core.py", line 150, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "/usr/share/python-wheels/resolvelib-0.3.0-py2.py3-none-any.whl/resolvelib/resolvers.py", line 413, in resolve
  File "/usr/share/python-wheels/resolvelib-0.3.0-py2.py3-none-any.whl/resolvelib/resolvers.py", line 280, in resolve
  File "/home/randalk/.local/lib/python3.8/site-packages/pdm/resolver/core.py", line 24, in _merge_into_criterion
    identifier, crit = _old_merge_into_criterion(self, requirement, parent)
  File "/usr/share/python-wheels/resolvelib-0.3.0-py2.py3-none-any.whl/resolvelib/resolvers.py", line 182, in _merge_into_criterion
TypeError: adding_requirement() missing 1 required positional argument: 'parent'
```

## Expected behavior

```
Adding packages to default dependencies: pytest
✔ 🔒 Lock successful
...

  ✔ Install pytest 4.6.11 successful

...
🎉 All complete!
```

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
```

```
PDM version:        1.5.3                                                 
Python Interpreter: /usr/bin/python3.8 (3.8)                              
Project Root:       /home/randalk/src/braingenix/ariana                   
Project Packages:   /home/randalk/src/braingenix/ariana/__pypackages__/3.8
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.6",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.8.0-53-generic",
  "platform_system": "Linux",
  "platform_version": "#60-Ubuntu SMP Thu May 6 07:46:32 UTC 2021",
  "python_full_version": "3.8.6",
  "platform_python_implementation": "CPython",
  "python_version": "3.8",
  "sys_platform": "linux"
}
```

Cheers,
Randal

**Comment by frostming** [comment]
Did you set PYTHONPATH? An extremely old version of resolvelib is being used while it is limited to 0.7.0+ in pdm's dependencies spec

**Comment by frostming** [comment]
Close it for not being an issue with pdm
