### ISSUE TITLE
"pdm add" generates invalid toml

### ISSUE THREAD

**Issue by blueyed** [pdm-project/pdm#487]
`pdm add sentry-sdk` generated this diff for `pyproject.toml`:
```diff
 dependencies = [
     "django~=3.1",
-]
+, "sentry-sdk~=1.1"]
 requires-python = ">=3.9"
```

This then fails at the end, or with `pdm lock -v`:
```
…
🔒 Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
Traceback (most recent call last):
  File "…/project/.venv/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "…/project/.venv/lib/python3.9/site-packages/pdm/core.py", line 184, in main
    return Core().main(args)
  File "…/project/.venv/lib/python3.9/site-packages/pdm/core.py", line 145, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "…/project/.venv/lib/python3.9/site-packages/pdm/core.py", line 140, in main
    f(options.project, options)
  File "…/project/.venv/lib/python3.9/site-packages/pdm/cli/commands/add.py", line 44, in handle
    actions.do_add(
  File "…/project/.venv/lib/python3.9/site-packages/pdm/cli/actions.py", line 208, in do_add
    project.write_lockfile(lockfile, False)
  File "…/project/.venv/lib/python3.9/site-packages/pdm/project/core.py", line 395, in write_lockfile
    toml_data["metadata"].update(self.get_lock_metadata())
  File "…/project/.venv/lib/python3.9/site-packages/pdm/project/core.py", line 388, in get_lock_metadata
    content_hash = atoml.string("sha256:" + self.get_content_hash("sha256"))
  File "…/project/.venv/lib/python3.9/site-packages/pdm/project/core.py", line 417, in get_content_hash
    "sources": self.tool_settings.get("source", []),
  File "…/project/.venv/lib/python3.9/site-packages/pdm/project/core.py", line 103, in tool_settings
    data = self.pyproject
  File "…/project/.venv/lib/python3.9/site-packages/pdm/project/core.py", line 93, in pyproject
    data = atoml.parse(self.pyproject_file.read_text("utf-8"))
  File "…/project/.venv/lib/python3.9/site-packages/atoml/api.py", line 61, in parse
    return Parser(string).parse()
  File "…/project/.venv/lib/python3.9/site-packages/atoml/parser.py", line 152, in parse
    key, value = self._parse_table()
  File "…/project/.venv/lib/python3.9/site-packages/atoml/parser.py", line 1146, in _parse_table
    item = self._parse_item()
  File "…/project/.venv/lib/python3.9/site-packages/atoml/parser.py", line 298, in _parse_item
    return self._parse_key_value(True)
  File "…/project/.venv/lib/python3.9/site-packages/atoml/parser.py", line 389, in _parse_key_value
    val = self._parse_value()
  File "…/project/.venv/lib/python3.9/site-packages/atoml/parser.py", line 561, in _parse_value
    return self._parse_array()
  File "…/project/.venv/lib/python3.9/site-packages/atoml/parser.py", line 729, in _parse_array
    raise self.parse_error(UnexpectedCharError, self._current)
atoml.exceptions.UnexpectedCharError: Unexpected character: ',' at line 10 col 0
```

version 1.6.2
Related/similar issue: https://github.com/pdm-project/pdm/issues/462

**Comment by frostming** [comment]
An issue with tomlkit/atoml, let me check

**Comment by frostming** [comment]
Note that you can get this fixed immediately by upgrading the atoml version to 1.0.2

https://github.com/pdm-project/pdm/commit/90b22d232365dad36478b529d2c1b0008047a218 just makes the array format more beautiful

**Comment by blueyed** [comment]
Thanks, the fix/upgrade works well.

I've wondered if there is a way to trigger a regeneration of the dependencies (format-only) automatically / through pdm?
I've noticed that `pdm update --unconstrained` will trigger it, although the deps/versions are not changed, but that a) might not be intentional, and/or b) there is a better way for this maybe?
(Anyway, I am just curious - it is easy enough to adjust/re-format it manually)
