### ISSUE TITLE
Error with editable install of project with missing project section in pyproject.toml

### ISSUE THREAD

**Issue by blueyed** [pdm-project/pdm#497]
Trying to `pdm add -e /path/to/ptpython` (https://github.com/prompt-toolkit/ptpython/tree/0f026780106b71a6128b95a0e6360e5ac535d8be) fails with:

```
% pdm add -e ~v/ptpython -v
Adding packages to default dependencies: ptpython
======== Start resolving requirements ========
  …
  -e file://…/Vcs/ptpython#egg=ptpython
  …
  ptpython~=3.0
  …
Preparing isolated env for PEP 517 build...
Traceback (most recent call last):
  File "…/project/.venv/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "…/project/.venv/lib/python3.9/site-packages/pdm/core.py", line 184, in main
    return Core().main(args)
  File "…/project/.venv/lib/python3.9/site-packages/pdm/core.py", line 145, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "…/project/.venv/lib/python3.9/site-packages/pdm/core.py", line 140, in main
    f(options.project, options)
  File "…/project/.venv/lib/python3.9/site-packages/pdm/cli/commands/add.py", line 44, in handle
    actions.do_add(
  File "…/project/.venv/lib/python3.9/site-packages/pdm/cli/actions.py", line 202, in do_add
    resolved = do_lock(project, strategy, tracked_names, reqs)
  File "…/project/.venv/lib/python3.9/site-packages/pdm/cli/actions.py", line 67, in do_lock
    mapping, dependencies, summaries = resolve(
  File "…/project/.venv/lib/python3.9/site-packages/pdm/resolver/core.py", line 49, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "…/project/.venv/lib/python3.9/site-packages/resolvelib/resolvers.py", line 473, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "…/project/.venv/lib/python3.9/site-packages/resolvelib/resolvers.py", line 341, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "…/project/.venv/lib/python3.9/site-packages/pdm/resolver/core.py", line 23, in _merge_into_criterion
    identifier, crit = _old_merge_into_criterion(self, requirement, parent)
  File "…/project/.venv/lib/python3.9/site-packages/resolvelib/resolvers.py", line 168, in _merge_into_criterion
    candidates=build_iter_view(matches),
  File "…/project/.venv/lib/python3.9/site-packages/resolvelib/structs.py", line 152, in build_iter_view
    matches = list(matches)
  File "…/project/.venv/lib/python3.9/site-packages/pdm/resolver/providers.py", line 142, in find_matches
    yield from super().find_matches(identifier, requirements, incompatibilities)
  File "…/project/.venv/lib/python3.9/site-packages/pdm/resolver/providers.py", line 52, in find_matches
    can.get_metadata()
  File "…/project/.venv/lib/python3.9/site-packages/pdm/models/candidates.py", line 184, in get_metadata
    built = self.environment.build(ireq, self.hashes, allow_all_wheels)
  File "…/project/.venv/lib/python3.9/site-packages/pdm/models/environment.py", line 289, in build
    ret = ireq.metadata_directory = builder.build(build_dir)
  File "…/project/.venv/lib/python3.9/site-packages/pdm/builders/egg_info.py", line 37, in build
    builder._meta = MutableMetadata(
  File "…/project/.venv/lib/python3.9/site-packages/pdm/pep517/metadata.py", line 85, in __init__
    self._read_pyproject()
  File "…/project/.venv/lib/python3.9/site-packages/pdm/project/metadata.py", line 16, in _read_pyproject
    return super()._read_pyproject()
  File "…/project/.venv/lib/python3.9/site-packages/pdm/pep517/metadata.py", line 100, in _read_pyproject
    raise ProjectError("No [project] config in pyproject.toml")
pdm.pep517.metadata.ProjectError: No [project] config in pyproject.toml
```

(note that this error also shows up in https://github.com/pdm-project/pdm/issues/492 (inbetween))

It works when not using `-e`.

pdm, version 1.6.3.dev4+gd6c1214

**Comment by frostming** [comment]
IMO the error message tells what happened, or what you expect it to be?
