### ISSUE TITLE
pdm add fasttext

### ISSUE THREAD

**Issue by Cameronwood611** [pdm-project/pdm#513]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

`mkdir test-fasttext`
`cd test-fasttext`
`pdm init`
`pdm add fasttext -v`

## Actual behavior

```
➜  test-fasttext pdm add fasttext -v
Adding packages to default dependencies: fasttext
Updating the whole lock file as it is not compatible with PDM
======== Start resolving requirements ========
  fasttext
  Adding requirement fasttext
	Found matching candidates:
	  <Candidate fasttext 0.9.2 from https://pypi.org/simple/fasttext/>
	  <Candidate fasttext 0.9.1 from https://pypi.org/simple/fasttext/>
	  <Candidate fasttext 0.8.4 from https://pypi.org/simple/fasttext/>
	  <Candidate fasttext 0.8.3 from https://pypi.org/simple/fasttext/>
	  <Candidate fasttext 0.8.2 from https://pypi.org/simple/fasttext/>
	  <Candidate fasttext 0.8.1 from https://pypi.org/simple/fasttext/>
	  <Candidate fasttext 0.8.0 from https://pypi.org/simple/fasttext/>
	  <Candidate fasttext 0.7.6 from https://pypi.org/simple/fasttext/>
	  <Candidate fasttext 0.7.5 from https://pypi.org/simple/fasttext/>
	  <Candidate fasttext 0.7.4 from https://pypi.org/simple/fasttext/>
	  ... [26 more candidate(s)]
======== Starting round 0 ========
  Adding requirement numpy(from fasttext 0.9.2)
	Found matching candidates:
	  <Candidate numpy 1.20.3 from https://pypi.org/simple/numpy/>
	  <Candidate numpy 1.20.2 from https://pypi.org/simple/numpy/>
	  <Candidate numpy 1.20.1 from https://pypi.org/simple/numpy/>
	  <Candidate numpy 1.20.0 from https://pypi.org/simple/numpy/>
	  <Candidate numpy 1.19.5 from https://pypi.org/simple/numpy/>
	  <Candidate numpy 1.19.4 from https://pypi.org/simple/numpy/>
	  <Candidate numpy 1.19.3 from https://pypi.org/simple/numpy/>
	  <Candidate numpy 1.19.2 from https://pypi.org/simple/numpy/>
	  <Candidate numpy 1.19.1 from https://pypi.org/simple/numpy/>
	  <Candidate numpy 1.19.0 from https://pypi.org/simple/numpy/>
	  ... [1359 more candidate(s)]
  Adding requirement pybind11>=2.2(from fasttext 0.9.2)
	Found matching candidates:
	  <Candidate pybind11 2.6.2 from https://pypi.org/simple/pybind11/>
	  <Candidate pybind11 2.6.1 from https://pypi.org/simple/pybind11/>
	  <Candidate pybind11 2.6.0 from https://pypi.org/simple/pybind11/>
	  <Candidate pybind11 2.5.0 from https://pypi.org/simple/pybind11/>
	  <Candidate pybind11 2.4.3 from https://pypi.org/simple/pybind11/>
		  <Candidate pybind11 2.4.2 from https://pypi.org/simple/pybind11/>
	  <Candidate pybind11 2.4.1 from https://pypi.org/simple/pybind11/>
	  <Candidate pybind11 2.4.0 from https://pypi.org/simple/pybind11/>
	  <Candidate pybind11 2.3.0 from https://pypi.org/simple/pybind11/>
	  <Candidate pybind11 2.2.4 from https://pypi.org/simple/pybind11/>
	  ... [18 more candidate(s)]
  Adding requirement setuptools>=0.7.0(from fasttext 0.9.2)
	Found matching candidates:
	  <Candidate setuptools 57.0.0 from https://pypi.org/simple/setuptools/>
	  <Candidate setuptools 56.2.0 from https://pypi.org/simple/setuptools/>
	  <Candidate setuptools 56.1.0 from https://pypi.org/simple/setuptools/>
	  <Candidate setuptools 56.0.0 from https://pypi.org/simple/setuptools/>
	  <Candidate setuptools 54.2.0 from https://pypi.org/simple/setuptools/>
	  <Candidate setuptools 54.1.3 from https://pypi.org/simple/setuptools/>
	  <Candidate setuptools 54.1.2 from https://pypi.org/simple/setuptools/>
	  <Candidate setuptools 54.1.1 from https://pypi.org/simple/setuptools/>
	  <Candidate setuptools 54.1.0 from https://pypi.org/simple/setuptools/>
	  <Candidate setuptools 54.0.0 from https://pypi.org/simple/setuptools/>
	  ... [1011 more candidate(s)]
Resolving: new pin fasttext 0.9.2
======== Ending round 0 ========
======== Starting round 1 ========
Resolving: new pin pybind11 2.6.2
======== Ending round 1 ========
======== Starting round 2 ========
Resolving: new pin setuptools 57.0.0
======== Ending round 2 ========
======== Starting round 3 ========
Resolving: new pin numpy 1.20.3
======== Ending round 3 ========
======== Starting round 4 ========
======== Resolution Result ========
Stable pins:
    fasttext 0.9.2
    pybind11 2.6.2
  setuptools 57.0.0
       numpy 1.20.3
	Found matching candidates:
	  <Candidate fasttext 0.9.2 from https://pypi.org/simple/fasttext/>
	Found matching candidates:
	  <Candidate pybind11 2.6.2 from https://pypi.org/simple/pybind11/>
	Found matching candidates:
	  <Candidate setuptools 57.0.0 from https://pypi.org/simple/setuptools/>
	Found matching candidates:
	  <Candidate numpy 1.20.3 from https://pypi.org/simple/numpy/>
🔒 Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
Synchronizing working set with lock file: 4 to add, 0 to update, 0 to remove

Install setuptools 57.0.0 successful
Install pybind11 2.6.2 successful
Preparing isolated env for PEP 517 build...
Collecting wheel (from -r /var/folders/v4/ljdky9k54195x1zf7hk6r_1h0000gn/T/pdm-build-reqs-uavplc06.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/65/63/39d04c74222770ed1589c0eaba06c05891801219272420b40311cd60c880/wheel-0.36.2-py2.py3-none-any.whl
Collecting setuptools>=40.8.0 (from -r /var/folders/v4/ljdky9k54195x1zf7hk6r_1h0000gn/T/pdm-build-reqs-uavplc06.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/4e/78/56aa1b5f4d8ac548755ae767d84f0be54fdd9d404197a3d9e4659d272348/setuptools-57.0.0-py3-none-any.whl
Installing collected packages: wheel, setuptools
  WARNING: The script wheel is installed in '/var/folders/v4/ljdky9k54195x1zf7hk6r_1h0000gn/T/pdm-build-env-518xvnx6/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Install numpy 1.20.3 successful
Successfully installed setuptools-57.0.0 wheel-0.36.2
WARNING: You are using pip version 19.2.3, however version 21.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
/Applications/Xcode.app/Contents/Developer/usr/bin/python3: No module named pip
Traceback (most recent call last):
  File "setup.py", line 38, in __init__
    import pybind11
ModuleNotFoundError: No module named 'pybind11'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/pdm/1.6.3/libexec/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 280, in <module>
    main()
  File "/usr/local/Cellar/pdm/1.6.3/libexec/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 263, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/usr/local/Cellar/pdm/1.6.3/libexec/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 114, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/var/folders/v4/ljdky9k54195x1zf7hk6r_1h0000gn/T/pdm-build-env-518xvnx6/lib/python3.8/site-packages/setuptools/build_meta.py", line 154, in get_requires_for_build_wheel
    return self._get_build_requires(
  File "/var/folders/v4/ljdky9k54195x1zf7hk6r_1h0000gn/T/pdm-build-env-518xvnx6/lib/python3.8/site-packages/setuptools/build_meta.py", line 135, in _get_build_requires
    self.run_setup()
  File "/var/folders/v4/ljdky9k54195x1zf7hk6r_1h0000gn/T/pdm-build-env-518xvnx6/lib/python3.8/site-packages/setuptools/build_meta.py", line 258, in run_setup
    super(_BuildMetaLegacyBackend,
  File "/var/folders/v4/ljdky9k54195x1zf7hk6r_1h0000gn/T/pdm-build-env-518xvnx6/lib/python3.8/site-packages/setuptools/build_meta.py", line 150, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 72, in <module>
    get_pybind_include(),
  File "setup.py", line 41, in __init__
    raise RuntimeError('pybind11 install failed.')
RuntimeError: pybind11 install failed.
Install fasttext 0.9.2 failed
  Retry failed jobs
Preparing isolated env for PEP 517 build...
/Applications/Xcode.app/Contents/Developer/usr/bin/python3: No module named pip
Traceback (most recent call last):
  File "setup.py", line 38, in __init__
    import pybind11
ModuleNotFoundError: No module named 'pybind11'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/pdm/1.6.3/libexec/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 280, in <module>
    main()
  File "/usr/local/Cellar/pdm/1.6.3/libexec/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 263, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/usr/local/Cellar/pdm/1.6.3/libexec/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 114, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/var/folders/v4/ljdky9k54195x1zf7hk6r_1h0000gn/T/pdm-build-env-518xvnx6/lib/python3.8/site-packages/setuptools/build_meta.py", line 154, in get_requires_for_build_wheel
    return self._get_build_requires(
  File "/var/folders/v4/ljdky9k54195x1zf7hk6r_1h0000gn/T/pdm-build-env-518xvnx6/lib/python3.8/site-packages/setuptools/build_meta.py", line 135, in _get_build_requires
    self.run_setup()
  File "/var/folders/v4/ljdky9k54195x1zf7hk6r_1h0000gn/T/pdm-build-env-518xvnx6/lib/python3.8/site-packages/setuptools/build_meta.py", line 258, in run_setup
    super(_BuildMetaLegacyBackend,
  File "/var/folders/v4/ljdky9k54195x1zf7hk6r_1h0000gn/T/pdm-build-env-518xvnx6/lib/python3.8/site-packages/setuptools/build_meta.py", line 150, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 72, in <module>
    get_pybind_include(),
  File "setup.py", line 41, in __init__
    raise RuntimeError('pybind11 install failed.')
RuntimeError: pybind11 install failed.
Install fasttext 0.9.2 failed

ERRORS:
add fasttext failed:
Traceback (most recent call last):
  File "/usr/local/Cellar/pdm/1.6.3/libexec/lib/python3.9/site-packages/pdm/builders/base.py", line 77, in log_subprocessor
    subprocess.check_call(
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/usr/local/Cellar/pdm/1.6.3/libexec/lib/python3.9/site-packages/pep517/in_process/_in_process.py', 'get_requires_for_build_wheel', '/var/folders/v4/ljdky9k54195x1zf7hk6r_1h0000gn/T/tmpbpe4eoye']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/Cellar/pdm/1.6.3/libexec/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 157, in install_candidate
    installer.install(can)
  File "/usr/local/Cellar/pdm/1.6.3/libexec/lib/python3.9/site-packages/pdm/installers/installers.py", line 43, in install
    candidate.get_metadata(allow_all_wheels=False, raising=True)
  File "/usr/local/Cellar/pdm/1.6.3/libexec/lib/python3.9/site-packages/pdm/models/candidates.py", line 183, in get_metadata
    built = self.environment.build(ireq, self.hashes, allow_all_wheels)
  File "/usr/local/Cellar/pdm/1.6.3/libexec/lib/python3.9/site-packages/pdm/models/environment.py", line 307, in build
    return EnvWheelBuilder(ireq.unpacked_source_directory, self).build(output_dir)
  File "/usr/local/Cellar/pdm/1.6.3/libexec/lib/python3.9/site-packages/pdm/builders/wheel.py", line 14, in build
    requires = self._hook.get_requires_for_build_wheel(config_settings)
  File "/usr/local/Cellar/pdm/1.6.3/libexec/lib/python3.9/site-packages/pep517/wrappers.py", line 168, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "/usr/local/Cellar/pdm/1.6.3/libexec/lib/python3.9/site-packages/pep517/wrappers.py", line 265, in _call_hook
    self._subprocess_runner(
  File "/usr/local/Cellar/pdm/1.6.3/libexec/lib/python3.9/site-packages/pdm/builders/base.py", line 191, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
  File "/usr/local/Cellar/pdm/1.6.3/libexec/lib/python3.9/site-packages/pdm/builders/base.py", line 85, in log_subprocessor
    raise BuildError(f"Call command {cmd} return non-zero status.")
pdm.exceptions.BuildError: Call command ['/usr/bin/python3', '/usr/local/Cellar/pdm/1.6.3/libexec/lib/python3.9/site-packages/pep517/in_process/_in_process.py', 'get_requires_for_build_wheel', '/var/folders/v4/ljdky9k54195x1zf7hk6r_1h0000gn/T/tmpbpe4eoye'] return non-zero status.

Traceback (most recent call last):
  File "/usr/local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/usr/local/Cellar/pdm/1.6.3/libexec/lib/python3.9/site-packages/pdm/core.py", line 185, in main
    return Core().main(args)
  File "/usr/local/Cellar/pdm/1.6.3/libexec/lib/python3.9/site-packages/pdm/core.py", line 146, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/usr/local/Cellar/pdm/1.6.3/libexec/lib/python3.9/site-packages/pdm/core.py", line 141, in main
    f(options.project, options)
  File "/usr/local/Cellar/pdm/1.6.3/libexec/lib/python3.9/site-packages/pdm/cli/commands/add.py", line 51, in handle
    actions.do_add(
  File "/usr/local/Cellar/pdm/1.6.3/libexec/lib/python3.9/site-packages/pdm/cli/actions.py", line 217, in do_add
    do_sync(
  File "/usr/local/Cellar/pdm/1.6.3/libexec/lib/python3.9/site-packages/pdm/cli/actions.py", line 166, in do_sync
    handler.synchronize()
  File "/usr/local/Cellar/pdm/1.6.3/libexec/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 324, in synchronize
    raise InstallationError("Some package operations are not complete yet")
pdm.exceptions.InstallationError: Some package operations are not complete yet
```

## Expected behavior

Install without errors.
It's worth noting that it installs fine with pip and pipenv.

## Environment Information

```
PDM version:        1.6.3                                          
Python Interpreter: /usr/bin/python3 (3.8)                         
Project Root:       /Users/cameron/test-fasttext                   
Project Packages:   /Users/cameron/test-fasttext/__pypackages__/3.8
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.2",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "20.4.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64",
  "python_full_version": "3.8.2",
  "platform_python_implementation": "CPython",
  "python_version": "3.8",
  "sys_platform": "darwin"
}

```

**Comment by frostming** [comment]
`fasttext` isn't following PEP 517. It doesn't have a `pyproject.toml` while requiring extra dependencies `pybind11` in install time, it even invokes `pip` to install missing dependencies when executing. PDM is not able to handle such a package, unfortunately. Try this  workaround:

```bash
pip install -t $(pdm info --packages)/lib fasttext
```

Hope it helps

**Comment by Cameronwood611** [comment]
> `fasttext` isn't following PEP 517. It doesn't have a `pyproject.toml` while requiring extra dependencies `pybind11` in install time, it even invokes `pip` to install missing dependencies when executing. PDM is not able to handle such a package, unfortunately. Try this workaround:
> 
> ```shell
> pip install -t $(pdm info --packages)/lib fasttext
> ```
> 
> Hope it helps

That works, thank you. Something to note is that fasttext's own module, `fasttext_pybind` (referenced in ther setup.py), does not build with python 3.8.2. However, it does build with python 3.9.5 and allows fasttext to be imported without errors :/
