### ISSUE TITLE
Cannot install in docker

### ISSUE THREAD

**Issue by Ierezell** [pdm-project/pdm#515]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce
Use a docker file to install pdm and bring the project to production. 

Docker file : 

```dockerfile
FROM archlinux

# Init package manager keyring
RUN pacman-key --init 
# Update and basic development tools (gcc etc...)
RUN pacman -Syu --noconfirm --quiet  
RUN pacman -S --noconfirm --quiet base-devel  

# Create a project folder
RUN mkdir /python-nlu
WORKDIR /python-nlu

# Copy all project files (including pyproject.toml)
COPY . /python-nlu
RUN mkdir -p models/nlu

# Install the python dependency and python project 
RUN pacman -S --noconfirm --quiet git
RUN pacman -S --noconfirm --quiet python-pip python-setuptools python-wheel 
# Can also run pip install setuptools wheel instead
RUN pip install pdm 
RUN pdm install # Crashes here (or any other pdm related command with the same error)
CMD ["pdm", "run", "server"]
```

## Actual behavior

Getting a 
```bash
Traceback (most recent call last):
  File "/usr/sbin/pdm", line 5, in <module>
    from pdm.core import main
  File "/usr/lib/python3.9/site-packages/pdm/__init__.py", line 6, in <module>
    from pdm.core import Core
  File "/usr/lib/python3.9/site-packages/pdm/core.py", line 16, in <module>
    from pdm.cli.actions import migrate_pyproject, print_pep582_command
  File "/usr/lib/python3.9/site-packages/pdm/cli/actions.py", line 37, in <module>
    from pdm.resolver import resolve
  File "/usr/lib/python3.9/site-packages/pdm/resolver/__init__.py", line 1, in <module>
    from pdm.resolver.core import resolve  # noqa
  File "/usr/lib/python3.9/site-packages/pdm/resolver/core.py", line 16, in <module>
    _old_merge_into_criterion = Resolution._merge_into_criterion
AttributeError: type object 'Resolution' has no attribute '_merge_into_criterion'
```

Note that pdm install works locally on my machine (which is also on archlinux).

## Expected behavior
Build the image without problems and run pdm in a container

## Environment Information
Cannot run `pdm info` or other pdm related command as it leads to the same error (shown above)

Note that I need the archlinux image as I'm also installing tools (like java, llvm10), etc... so I cannot use the official pdm image.

I suspect that the pip version was updated and pdm isn't working with the new one maybe something like https://github.com/pypa/pip/issues/9188

**Comment by flortsch** [comment]
Having the same issue in multiple environments (on my local Arch Linux machine and in a Ubuntu Focal Docker container). In the Ubuntu container, I also get the same issue when running the new PDM install script.

**Comment by frostming** [comment]
It is because PDM is patching an internal class of `resolvelib` and is broken by the new release of `resolvelib`. A bugfix release will soon be out. As a workaround, you can pin the resolvelib version by:

```bash
pip install resolvelib==0.7.0 pdm
```

**Comment by Ierezell** [comment]
Hi @frostming, thanks a lot for the fast reply and the fast fix. 

I tried both pdm and pdm with your workaraound and both lead to this error : 

<details>
<summary> Short trace</summary>
</br>

```bash 
Resolving: new pin colorama 0.4.4
======== Ending round 51 ========
======== Starting round 52 ========
Resolving: new pin pyparsing 3.0.0b2
======== Ending round 52 ========
======== Starting round 53 ========
Preparing isolated env for PEP 517 build...
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 223, in _main
    status = self.run(options, args)
  File "/usr/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/usr/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 320, in run
    requirement_set = resolver.resolve(
  File "/usr/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 121, in resolve
    self._result = resolver.resolve(
  File "/usr/lib/python3.9/site-packages/resolvelib/resolvers.py", line 473, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/lib/python3.9/site-packages/resolvelib/resolvers.py", line 341, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/usr/lib/python3.9/site-packages/resolvelib/resolvers.py", line 147, in _merge_into_criterion
    matches = self._p.find_matches(
TypeError: find_matches() got an unexpected keyword argument 'identifier'
Failed to build package, try parsing project files.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pdm/builders/base.py", line 77, in log_subprocessor
    subprocess.check_call(
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3.9', '-Esm', 'pip', 'install', '--ignore-installed', '--prefix', '/tmp/pdm-build-env-eudry9af', '-i', 'https://pypi.org/simple', '-r', '/tmp/pdm-build-reqs-nubfzfj1.txt']' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pdm/models/candidates.py", line 188, in get_metadata
    built = self.environment.build(ireq, self.hashes, allow_all_wheels)
  File "/usr/lib/python3.9/site-packages/pdm/models/environment.py", line 315, in build
    return EnvWheelBuilder(ireq.unpacked_source_directory, self).build(output_dir)
  File "/usr/lib/python3.9/site-packages/pdm/builders/wheel.py", line 13, in build
    self.install(self._build_system["requires"])
  File "/usr/lib/python3.9/site-packages/pdm/builders/base.py", line 226, in install
    self.subprocess_runner(cmd, isolated=False)
  File "/usr/lib/python3.9/site-packages/pdm/builders/base.py", line 191, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
  File "/usr/lib/python3.9/site-packages/pdm/builders/base.py", line 85, in log_subprocessor
    raise BuildError(f"Call command {cmd} return non-zero status.")
pdm.exceptions.BuildError: Call command ['/usr/bin/python3.9', '-Esm', 'pip', 'install', '--ignore-installed', '--prefix', '/tmp/pdm-build-env-eudry9af', '-i', 'https://pypi.org/simple', '-r', '/tmp/pdm-build-reqs-nubfzfj1.txt'] return non-zero status.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/sbin/pdm", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/pdm/core.py", line 185, in main
    return Core().main(args)
  File "/usr/lib/python3.9/site-packages/pdm/core.py", line 146, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/usr/lib/python3.9/site-packages/pdm/core.py", line 141, in main
    f(options.project, options)
  File "/usr/lib/python3.9/site-packages/pdm/cli/commands/install.py", line 38, in handle
    actions.do_lock(project, strategy="all")
  File "/usr/lib/python3.9/site-packages/pdm/cli/actions.py", line 67, in do_lock
    mapping, dependencies, summaries = resolve(
  File "/usr/lib/python3.9/site-packages/pdm/resolver/core.py", line 30, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "/usr/lib/python3.9/site-packages/resolvelib/resolvers.py", line 473, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/lib/python3.9/site-packages/resolvelib/resolvers.py", line 367, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/usr/lib/python3.9/site-packages/resolvelib/resolvers.py", line 213, in _attempt_to_pin_criterion
    criteria = self._get_criteria_to_update(candidate)
  File "/usr/lib/python3.9/site-packages/resolvelib/resolvers.py", line 202, in _get_criteria_to_update
    for r in self._p.get_dependencies(candidate=candidate):
  File "/usr/lib/python3.9/site-packages/pdm/resolver/providers.py", line 87, in get_dependencies
    deps, requires_python, summary = self.repository.get_dependencies(candidate)
  File "/usr/lib/python3.9/site-packages/pdm/models/repositories.py", line 79, in get_dependencies
    requirements, requires_python, summary = getter(candidate)
  File "/usr/lib/python3.9/site-packages/pdm/models/repositories.py", line 46, in wrapper
    result = func(self, candidate)
  File "/usr/lib/python3.9/site-packages/pdm/models/repositories.py", line 185, in _get_dependencies_from_metadata
    deps = candidate.get_dependencies_from_metadata()
  File "/usr/lib/python3.9/site-packages/pdm/models/candidates.py", line 243, in get_dependencies_from_metadata
    metadata = self.get_metadata()
  File "/usr/lib/python3.9/site-packages/pdm/models/candidates.py", line 193, in get_metadata
    meta_dict = Setup.from_directory(
  File "/usr/lib/python3.9/site-packages/pdm/models/setup.py", line 37, in from_directory
    return _SetupReader.read_from_directory(dir)
  File "/usr/lib/python3.9/site-packages/pdm/models/setup.py", line 59, in read_from_directory
    new_result = file_reader(filepath)
  File "/usr/lib/python3.9/site-packages/pdm/models/setup.py", line 97, in read_setup_py
    extras_require=cls._find_extras_require(setup_call, body),
  File "/usr/lib/python3.9/site-packages/pdm/models/setup.py", line 300, in _find_extras_require
    extras_require[key.s] = [e.s for e in val.elts]
  File "/usr/lib/python3.9/site-packages/pdm/models/setup.py", line 300, in <listcomp>
    extras_require[key.s] = [e.s for e in val.elts]
AttributeError: 'JoinedStr' object has no attribute 's'
The command '/bin/sh -c pdm install -v' returned a non-zero code: 1
```

<details>

**Comment by frostming** [comment]
Did you do a fresh-install? You should upgrade to pdm 1.6.4 and resolvelib 0.7.1 respectively

**Comment by Ierezell** [comment]
My bad, I copy-pasted the above comment with resolvlib 1.7.0 (I should've double-checked). I replaced it with 1.7.1

I did a fresh install by removing `__pypackages__` and `pdm.lock` was it the "fresh" you intended ? 
I also have them in my .dockerignore so they're not copied. Also did a` docker system prune -a`

It works except that I'm stuck in either an infinite dependency resolving loop or get the `AttributeError: 'JoinedStr' object has no attribute 's'` error from above. 

here is my dependency list if you want to try to reproduce (the only constrain is on torch): 
```
"torch==1.8.0", # To make pdm able to install it (latest is 1.9)
"transformers", # need torch
"torchaudio", # need torch
"spacy-transformers", # dependency loop as it need torch 
"uvicorn",
"uvloop",
"faiss-cpu",
"rich",
"fastapi",
"scikit-learn",
"sklearn-crfsuite",
"recognizers-text-suite",
"pytesseract",
"pdf2image",
"scrapy",
"python-multipart",
"language_tool_python",
"symspellpy",
"textdistance",
"epitran",
"bertopic",
"jellyfish",
"claucy @ git+git://github.com/Ierezell/spacy-clausie.git@master",
"parrot @ git+https://github.com/PrithivirajDamodaran/Parrot_Paraphraser.git@main",
```

Thanks again for your precious time ! 
Have a great day
