### ISSUE TITLE
PDM init failing to recognize python version on windows 10

### ISSUE THREAD

**Issue by clawsl** [pdm-project/pdm#518]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

install PDM following the recommentation for Windows:
```(Invoke-WebRequest -Uri https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py -UseBasicParsing).Content | python -```

run `pdm init` 

## Actual behavior

```
pdm init -v
Creating a pyproject.toml for PDM...
Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\pdm.exe\__main__.py", line 7, in <module>
  File "c:\python39\lib\site-packages\pdm\core.py", line 185, in main
    return Core().main(args)
  File "c:\python39\lib\site-packages\pdm\core.py", line 146, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "c:\python39\lib\site-packages\pdm\core.py", line 141, in main
    f(options.project, options)
  File "c:\python39\lib\site-packages\pdm\cli\commands\init.py", line 45, in handle
    actions.do_use(project)
  File "c:\python39\lib\site-packages\pdm\cli\actions.py", line 473, in do_use
    dict.fromkeys(filter(version_matcher, project.find_interpreters(python)))
  File "c:\python39\lib\site-packages\pdm\project\core.py", line 582, in find_interpreters
    for entry in finder.find_all_python_versions(*args):
  File "c:\python39\lib\site-packages\pythonfinder\pythonfinder.py", line 328, in find_all_python_versions
    path_list = sorted(filter(None, versions), key=version_sort, reverse=True)
AttributeError: 'NoneType' object has no attribute 'version_sort'
```

## Expected behavior

pdm init should succeed 

## Environment Information
```pdm info```
[ProjectError]: The pyproject.toml has not been initialized yet. You can do this by running 'pdm init'.

```pdm info --env```
[ProjectError]: The pyproject.toml has not been initialized yet. You can do this by running 'pdm init'.

```
pip list
Package            Version
------------------ ---------
appdirs            1.4.4
argcomplete        1.12.3
astroid            2.4.2
atoml              1.0.2
attrs              20.2.0
autopep8           1.5.4
aws-sam-translator 1.28.1
boto3              1.17.94
botocore           1.20.94
cached-property    1.5.2
certifi            2021.5.30
cfn-lint           0.39.0
click              8.0.1
colorama           0.4.4
decorator          4.4.2
distlib            0.3.2
filelock           3.0.12
flake8             3.9.2
gitdb              4.0.5
gitdb2             4.0.2
GitPython          3.0.6
isort              5.6.4
jmespath           0.10.0
jsonpatch          1.26
jsonpointer        2.0
jsonschema         3.2.0
junit-xml          1.9
lazy-object-proxy  1.4.3
mccabe             0.6.1
mypy               0.910
mypy-extensions    0.4.3
networkx           2.5
packaging          20.9
pdm                1.6.4
pdm-pep517         0.7.4
pip                21.1.2
pipx               0.16.3
pycodestyle        2.7.0
pyflakes           2.3.1
pylint             2.6.0
pyparsing          2.4.7
pyrsistent         0.17.3
python-cfonts      1.5.0
python-dateutil    2.8.1
python-dotenv      0.18.0
pythonfinder       1.2.6
PyYAML             5.3.1
resolvelib         0.7.1
s3transfer         0.4.2
setuptools         49.2.1
shellingham        1.4.0
six                1.15.0
smmap              3.0.5
toml               0.10.1
truffleHog         2.2.1
truffleHogRegexes  0.0.7
typing-extensions  3.10.0.0
urllib3            1.25.11
userpath           1.6.0
wheel              0.36.2
wrapt              1.12.1
```

python version
```python
Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.```

**Comment by clawsl** [comment]
searching for the issue, I found that this seems to be a none issue with version detection for [pipenv on Windows](https://stackoverflow.com/questions/62367399/failed-to-run-any-pipenv-command-on-windows), where the general recommendation was to install an old pipenv version. 

However even after installing the pipenv version 2018.11.26 the behavior doesn't change for me. 

```pip install pipenv==2018.11.26
...
Installing collected packages: virtualenv-clone, virtualenv, pipenv
Successfully installed pipenv-2018.11.26 virtualenv-20.4.7 virtualenv-clone-0.5.4
```

```
pdm init
Creating a pyproject.toml for PDM...
[AttributeError]: 'NoneType' object has no attribute 'version_sort'
Add '-v' to see the detailed traceback
```

Is there perhaps a way to not use the python version detection (and skip pythonfinder this way) when creating a new project ?

**Comment by frostming** [comment]
There are broken installations of Python on your system. Clean them and their winreg entries and retry.

**Comment by frostming** [comment]
Try a fresh install (You can do this by rerunning the install command) and see if the issue is gone
