### ISSUE TITLE
Cannot install pandas because latest version 1.3.0 is not available for used Python version

### ISSUE THREAD

**Issue by pohlt** [pdm-project/pdm#525]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

1. Create a clean pdm repo.
2. Do a `pdm add pandas`

## Actual behavior

pdm checks for the latest pandas version and goes for 1.3.0.
However, there currently is no pandas 1.3.0 for Python 3.8.
Currently, `https://pypi.org/simple/pandas/` looks like this:
```
[...]
pandas-1.2.5-cp37-cp37m-macosx_10_9_x86_64.whl
pandas-1.2.5-cp37-cp37m-manylinux_2_5_i686.manylinux1_i686.whl
pandas-1.2.5-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl
pandas-1.2.5-cp37-cp37m-win32.whl
pandas-1.2.5-cp37-cp37m-win_amd64.whl
pandas-1.2.5-cp38-cp38-macosx_10_9_x86_64.whl
pandas-1.2.5-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
pandas-1.2.5-cp38-cp38-manylinux_2_5_i686.manylinux1_i686.whl
pandas-1.2.5-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl
pandas-1.2.5-cp38-cp38-win32.whl
pandas-1.2.5-cp38-cp38-win_amd64.whl
pandas-1.2.5-cp39-cp39-macosx_10_9_x86_64.whl
pandas-1.2.5-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
pandas-1.2.5-cp39-cp39-manylinux_2_5_i686.manylinux1_i686.whl
pandas-1.2.5-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl
pandas-1.2.5-cp39-cp39-win32.whl
pandas-1.2.5-cp39-cp39-win_amd64.whl
pandas-1.2.5.tar.gz
pandas-1.3.0rc1-cp37-cp37m-macosx_10_9_x86_64.whl
pandas-1.3.0rc1-cp37-cp37m-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
pandas-1.3.0rc1-cp37-cp37m-manylinux_2_5_i686.manylinux1_i686.whl
pandas-1.3.0rc1-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl
pandas-1.3.0rc1-cp37-cp37m-win32.whl
pandas-1.3.0rc1-cp37-cp37m-win_amd64.whl
pandas-1.3.0rc1-cp38-cp38-macosx_10_9_x86_64.whl
pandas-1.3.0rc1-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
pandas-1.3.0rc1-cp38-cp38-manylinux_2_5_i686.manylinux1_i686.whl
pandas-1.3.0rc1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl
pandas-1.3.0rc1-cp38-cp38-win32.whl
pandas-1.3.0rc1-cp38-cp38-win_amd64.whl
pandas-1.3.0rc1-cp39-cp39-macosx_10_9_x86_64.whl
pandas-1.3.0rc1-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
pandas-1.3.0rc1-cp39-cp39-manylinux_2_5_i686.manylinux1_i686.whl
pandas-1.3.0rc1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl
pandas-1.3.0rc1-cp39-cp39-win32.whl
pandas-1.3.0rc1-cp39-cp39-win_amd64.whl
pandas-1.3.0rc1.tar.gz
pandas-1.3.0-cp37-cp37m-macosx_10_9_x86_64.whl
pandas-1.3.0-cp37-cp37m-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
pandas-1.3.0-cp37-cp37m-manylinux_2_5_i686.manylinux1_i686.whl
pandas-1.3.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl
pandas-1.3.0-cp37-cp37m-win32.whl
pandas-1.3.0-cp37-cp37m-win_amd64.whl
```
pdm fails to install pandas with
```
[...]
======== Resolution Result ========
Stable pins:
           pandas 1.3.0
  python-dateutil 2.8.1
             pytz 2021.1
              six 1.16.0
            numpy 1.21.0
        Found matching candidates:
          <Candidate pandas 1.3.0 from https://pypi.org/simple/pandas/>
        Found matching candidates:
          <Candidate python-dateutil 2.8.1 from https://pypi.org/simple/python-dateutil/>
        Found matching candidates:
          <Candidate pytz 2021.1 from https://pypi.org/simple/pytz/>
        Found matching candidates:
          <Candidate six 1.16.0 from https://pypi.org/simple/six/>
        Found matching candidates:
          <Candidate numpy 1.21.0 from https://pypi.org/simple/numpy/>
🔒 Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
Synchronizing working set with lock file: 1 to add, 0 to update, 0 to remove

Could not find a version that satisfies the requirement pandas==1.3.0 (from versions: 0.1, 0.2b0, 0.2b1, 0.2, 0.3.0b0, 0.3.0b2, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.6.0, 0.6.1, 0.7.0rc1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0rc1, 0.8.0rc2, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.16.2, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0rc1, 0.19.0, 0.19.1, 0.19.2, 0.20.0rc1, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.21.0rc1, 0.21.0, 0.21.1, 0.22.0, 0.23.0rc2, 0.23.0, 0.23.1, 0.23.2, 0.23.3, 0.23.4, 0.24.0rc1, 0.24.0, 0.24.1, 0.24.2, 0.25.0rc0, 0.25.0, 0.25.1, 0.25.2, 0.25.3, 1.0.0rc0, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0rc0, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.2.0rc0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.3.0rc1)
Install pandas 1.3.0 failed
  Retry failed jobs
Could not find a version that satisfies the requirement pandas==1.3.0 (from versions: 0.1, 0.2b0, 0.2b1, 0.2, 0.3.0b0, 0.3.0b2, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.6.0, 0.6.1, 0.7.0rc1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0rc1, 0.8.0rc2, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.16.2, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0rc1, 0.19.0, 0.19.1, 0.19.2, 0.20.0rc1, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.21.0rc1, 0.21.0, 0.21.1, 0.22.0, 0.23.0rc2, 0.23.0, 0.23.1, 0.23.2, 0.23.3, 0.23.4, 0.24.0rc1, 0.24.0, 0.24.1, 0.24.2, 0.25.0rc0, 0.25.0, 0.25.1, 0.25.2, 0.25.3, 1.0.0rc0, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0rc0, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.2.0rc0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.3.0rc1)
Install pandas 1.3.0 failed

ERRORS:                                                                                              
add pandas failed:
Traceback (most recent call last):
  File "/usr/lib64/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/tom/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/installers/synchronizers.py", line 157, in install_candidate
    installer.install(can)
  File "/home/tom/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/installers/installers.py", line 43, in install
    candidate.get_metadata(allow_all_wheels=False, raising=True)
  File "/home/tom/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/models/candidates.py", line 188, in get_metadata
    built = self.environment.build(ireq, self.hashes, allow_all_wheels)
  File "/home/tom/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/models/environment.py", line 248, in build
    populate_link(finder, ireq, False)
  File "/home/tom/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/utils.py", line 371, in populate_link
    candidate = finder.find_requirement(ireq, upgrade)
  File "/home/tom/.local/pipx/shared/lib/python3.8/site-packages/pip/_internal/index/package_finder.py", line 924, in find_requirement
    raise DistributionNotFound(
pip._internal.exceptions.DistributionNotFound: No matching distribution found for pandas==1.3.0

Traceback (most recent call last):
  File "/home/tom/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/tom/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/core.py", line 185, in main
    return Core().main(args)
  File "/home/tom/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/core.py", line 146, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/home/tom/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/core.py", line 141, in main
    f(options.project, options)
  File "/home/tom/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/cli/commands/add.py", line 51, in handle
    actions.do_add(
  File "/home/tom/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/cli/actions.py", line 217, in do_add
    do_sync(
  File "/home/tom/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/cli/actions.py", line 166, in do_sync
    handler.synchronize()
  File "/home/tom/.local/pipx/venvs/pdm/lib64/python3.8/site-packages/pdm/installers/synchronizers.py", line 324, in synchronize
    raise InstallationError("Some package operations are not complete yet")
pdm.exceptions.InstallationError: Some package operations are not complete yet
```

## Expected behavior

pdm installs pandas 1.2.5 (like pip does).

## Environment Information

```bash
PDM version:        1.6.4                                    
Python Interpreter: /usr/bin/python3 (3.8)                   
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.10",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.12.12-1-default",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Fri Jun 18 11:07:46 UTC 2021 (0e46a2c)",
  "python_full_version": "3.8.10",
  "platform_python_implementation": "CPython",
  "python_version": "3.8",
  "sys_platform": "linux"
}
```

**Comment by pohlt** [comment]
Sure, I could manually ask for pandas 1.2.5, but pdm should be at least as clever as pip when dealing with such issue, IMHO. 😉 
I was actually trying to install streamlit which pulls in pandas and the root cause (pandas' currently limited Python version support) was even less obvious why the installation failed.

**Comment by frostming** [comment]
This is usually a broken package, the packager should be responsible to fix it(**it has been fixed**).

Pip is clever because it only needs to ensure the resolution works for the current python version and environment. But pdm tries to make the resolution work for a given range of python versions. The locker has no knowledge of what python version is going to be used and assume all distributions on PyPI should be well formed and should provide a proper artifact for all python versions it promised to work and at least a sdist for fallback. But pandas 1.3.0 breaks the assumption. So pdm can't proceed to install.

**Comment by pohlt** [comment]
Maybe it's just me, but when I try to quickly setup a venv to test some stuff and I do a `pip install streamlit` and it just works, and I do a `pdm add streamlit` and it breaks, I - as an end-user - have the impression that pip is more "clever". Could be that pdm is just not the optimal tool for this task. 🤔 

Wouldn't it make sense for pdm and the locker in particular to consider _two_ inputs for the Python version?

1. The Python version which is required for the local project to work as stored in `requires-python`.
2. The Python version which is currently being used to run the local package. (Could potentially be determined by asking the current interpreter about its version.)

Based on the second input, would pdm be more robust against broken / incomplete packages?

**Comment by frostming** [comment]
> The Python version which is required for the local project to work as stored in requires-python.

This is what the locker is doing now.

> The Python version which is currently being used to run the local package. 

No, the reason behind this is PDM wants to support **cross version and platform** resolution. Say you are on Python 3.7 and one of the dependency has a sub-dependency that is required on Python 3.6 only like `dataclasses; python_version < 3.7`. When the locker queries the metadata of `dataclasses`, it can download the wheel and extract the metadata, despite the current Python version being used. We can't discard it because it has no wheel for Python 3.7(Just an assumption, `dataclasses` is not the case though). You may say, we could treat it differently if it has environment markers. However, determining the environment marker of a dependency is a difficult and tricky job. Because the marker might come from parent dependants and there is no robust way to resolve and merge the markers correctly.

As you see, all is about trade-offs. You gain the ability of cross resolution and lose some accuracy of the resolution result.

**Comment by pohlt** [comment]
Thanks for the explanation.
I was trying to replace pip by pdm in my daily tasks as much as possible. Maybe I just have to reconsider when to use which tool.
