### ISSUE TITLE
`--freeze` to output requirements.txt format, exclusive with `--graph`.

### ISSUE THREAD

**Issue by frostming** [pdm-project/pdm#533]

**Comment by tronorama** [comment]
I upgraded my pdm version and tried this new command, but I got an error:
```

❯ pip -V
pip 20.3.4 from /usr/lib/python3.9/site-packages/pip (python 3.9)
❯ pdm --version
pdm, version 1.7.0
❯ pdm list --freeze -v
Traceback (most recent call last):
  File "/home/ddg/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/ddg/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/core.py", line 194, in main
    return Core().main(args)
  File "/home/ddg/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/core.py", line 152, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/home/ddg/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/core.py", line 147, in main
    f(options.project, options)
  File "/home/ddg/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/cli/commands/list.py", line 26, in handle
    actions.do_list(
  File "/home/ddg/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/cli/actions.py", line 387, in do_list
    reqs = [
  File "/home/ddg/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/cli/actions.py", line 388, in <listcomp>
    str(FrozenRequirement.from_dist(dist))
  File "/home/ddg/.local/pipx/shared/lib/python3.9/site-packages/pip/_internal/operations/freeze.py", line 257, in from_dist
    req, editable, comments = _get_editable_info(dist)
  File "/home/ddg/.local/pipx/shared/lib/python3.9/site-packages/pip/_internal/operations/freeze.py", line 165, in _get_editable_info
    if not dist.editable:
  File "/home/ddg/.local/pipx/shared/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2816, in __getattr__
    return getattr(self._provider, attr)
AttributeError: 'PathMetadata' object has no attribute 'editable'
```
I wondered if there is something else I need to fix, or there is a different way I can generate a requirements.txt file from pdm?

**Comment by frostming** [comment]
Try upgrading pip to the latest version, if that is not possible, use an isolated installation method.

**Comment by emcd** [comment]
I am seeing this problem as well, using latest `pdm` (built from Git clone) or latest released `pdm`:
```bash
$ which pdm
/home/me/src/pdm/venv/bin/pdm
$ pdm info && pdm info --env
PDM version:        1.10.4.dev13+geec4112
Python Interpreter: /home/me/.asdf/installs/python/3.6.15/bin/python (3.6)
Project Root:       /home/me/src/python-lockup
Project Packages:   /home/me/src/python-lockup/__pypackages__/3.6
{
  "implementation_name": "cpython",
  "implementation_version": "3.6.15",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.10.16.3-microsoft-standard-WSL2",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Fri Apr 2 22:23:49 UTC 2021",
  "python_full_version": "3.6.15",
  "platform_python_implementation": "CPython",
  "python_version": "3.6",
  "sys_platform": "linux"
}

Pip version is up-to-date.
```bash
$ pip --version
pip 21.3.1 from /home/me/src/pdm/venv/lib/python3.8/site-packages/pip (python 3.8)
```

Traceback:
```
$ pdm list --freeze -v
Traceback (most recent call last):
  File "/home/me/src/pdm/venv/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/me/src/pdm/pdm/core.py", line 200, in main
    return Core().main(args)
  File "/home/me/src/pdm/pdm/core.py", line 153, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/home/me/src/pdm/pdm/core.py", line 148, in main
    f(options.project, options)
  File "/home/me/src/pdm/pdm/cli/commands/list.py", line 31, in handle
    actions.do_list(
  File "/home/me/src/pdm/pdm/cli/actions.py", line 404, in do_list
    reqs = [
  File "/home/me/src/pdm/pdm/cli/actions.py", line 405, in <listcomp>
    frozen_requirement_from_dist(dist)
  File "/home/me/src/pdm/pdm/cli/utils.py", line 647, in frozen_requirement_from_dist
    return str(FrozenRequirement.from_dist(pkg_dist))
  File "/home/me/src/pdm/venv/lib/python3.8/site-packages/pip/_internal/operations/freeze.py", line 235, in from_dist
    editable = dist.editable
  File "/home/me/src/pdm/venv/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2816, in __getattr__
    return getattr(self._provider, attr)
AttributeError: 'PathMetadata' object has no attribute 'editable'
```

Pip produces correct output:
```
$ pip freeze --path __pypackages__/3.6/lib
alabaster==0.7.12
astroid==2.9.0
attrs==21.2.0
Babel==2.9.1
backports.entry-points-selectable==1.1.1
bandit==1.7.1
beautifulsoup4==4.10.0
bleach==4.1.0
bracex==2.2.1
bump2version==1.0.1
certifi==2021.10.8
```
...

**Comment by frostming** [comment]
This is an API change of `pip`, reopen it now.
