### ISSUE TITLE
Mac install instructions don't work

### ISSUE THREAD

**Issue by boxabirds** [pdm-project/pdm#536]
`curl -sSL https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py | python -`

```
  File "<stdin>", line 42
    def _call_subprocess(args: list[str]) -> int:
                             ^
SyntaxError: invalid syntax
```

python on Mac is v 2.7. It's recommended never to change the default OS-level python. 

So I installed python3. 

`curl -sSL https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py | python3`

```
Installing PDM (1.6.4): Creating virtual environment
Traceback (most recent call last):
  File "<stdin>", line 433, in <module>
  File "<stdin>", line 429, in main
  File "<stdin>", line 354, in install
  File "<stdin>", line 275, in _make_env
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/venv/__init__.py", line 391, in create
    builder.create(env_dir)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/venv/__init__.py", line 68, in create
    self._setup_pip(context)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/venv/__init__.py", line 289, in _setup_pip
    subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/julianharris/Library/Application Support/pdm/venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' died with <Signals.SIGABRT: 6>.
```

Am I holding it wrong?

**Comment by frostming** [comment]
Can you do `python3 -m venv temp_venv` to see if it works?
