### ISSUE TITLE
[InconsistentCandidate] error 

### ISSUE THREAD

**Issue by hrithik098** [pdm-project/pdm#551]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

```
pdm add django-graphql-jwt
```

## Actual behavior

```
Adding packages to default dependencies: django-graphql-jwt
See /var/folders/2x/97gh7f4j1010pp_s8hctmmdh0000gn/T/pdm-lock-nfk01zls.log for detailed debug log.
[InconsistentCandidate]: Provided candidate <Candidate graphene-django 2.15.0 from unknown> does not satisfy <NamedRequirement graphene-django~=2.15>, <NamedRequirement graphene-django>=2.0>, <NamedRequirement graphene-django>=3.0.0b1>
```

Logs are too big. So adding the part which actually produces the error.
```
======== Ending round 93 ========
	New pin: oauthlib 3.1.1
======== Ending round 94 ========
	New pin: wcwidth 0.2.5
======== Ending round 95 ========
	New pin: psycopg2-binary 2.8.5
======== Ending round 96 ========
	New pin: coverage 5.1
======== Ending round 97 ========
	New pin: nodeenv 1.6.0
======== Ending round 98 ========
	New pin: asgiref 3.3.4
======== Ending round 99 ========
	Adding requirement pytz>=2015.7(from babel 2.9.1)
	Found matching candidates:
	  <Candidate pytz 2020.1 from https://pypi.org/simple/pytz/>
	New pin: babel 2.9.1
======== Ending round 100 ========
	New pin: hiredis 1.0.1
======== Ending round 101 ========
	Adding requirement Django>=1.11(from django-graphql-jwt 0.3.2)
	Found matching candidates:
	  <Candidate Django 3.0 from https://pypi.org/simple/django/>
	Adding requirement graphene-django>=3.0.0b1(from django-graphql-jwt 0.3.2)
	Found matching candidates:
	  <Candidate graphene-django 2.15.0 from https://pypi.org/simple/graphene-django/>
	Adding requirement PyJWT<3,>=2(from django-graphql-jwt 0.3.2)
	Found matching candidates:
	  <Candidate PyJWT 2.1.0 from https://pypi.org/simple/pyjwt/>
	  <Candidate PyJWT 2.0.1 from https://pypi.org/simple/pyjwt/>
	  <Candidate PyJWT 2.0.0 from https://pypi.org/simple/pyjwt/>
	New pin: django-graphql-jwt 0.3.2
======== Ending round 102 ========
	Adding requirement six>=1.10.0(from graphene-django 2.15.0)
	Found matching candidates:
	  <Candidate six 1.16.0 from https://pypi.org/simple/six/>
	  <Candidate six 1.15.0 from https://pypi.org/simple/six/>
	  <Candidate six 1.14.0 from https://pypi.org/simple/six/>
	  <Candidate six 1.13.0 from https://pypi.org/simple/six/>
	  <Candidate six 1.12.0 from https://pypi.org/simple/six/>
	  <Candidate six 1.11.0 from https://pypi.org/simple/six/>
	  <Candidate six 1.10.0 from https://pypi.org/simple/six/>
	  <Candidate six 1.9.0 from https://pypi.org/simple/six/>
	  <Candidate six 1.8.0 from https://pypi.org/simple/six/>
	  <Candidate six 1.7.3 from https://pypi.org/simple/six/>
	  ... [28 more candidate(s)]
	Adding requirement graphene<3,>=2.1.7(from graphene-django 2.15.0)
	Found matching candidates:
	  <Candidate graphene 2.1.9 from https://pypi.org/simple/graphene/>
	  <Candidate graphene 2.1.8 from https://pypi.org/simple/graphene/>
	  <Candidate graphene 2.1.7 from https://pypi.org/simple/graphene/>
	Adding requirement graphql-core<3,>=2.1.0(from graphene-django 2.15.0)
	Found matching candidates:
	  <Candidate graphql-core 2.3.2 from https://pypi.org/simple/graphql-core/>
	  <Candidate graphql-core 2.3.1 from https://pypi.org/simple/graphql-core/>
	  <Candidate graphql-core 2.3 from https://pypi.org/simple/graphql-core/>
	  <Candidate graphql-core 2.2.1 from https://pypi.org/simple/graphql-core/>
	  <Candidate graphql-core 2.2 from https://pypi.org/simple/graphql-core/>
	  <Candidate graphql-core 2.1 from https://pypi.org/simple/graphql-core/>
	Adding requirement Django>=1.11(from graphene-django 2.15.0)
	Found matching candidates:
	  <Candidate Django 3.0 from https://pypi.org/simple/django/>
	Adding requirement singledispatch>=3.4.0.3(from graphene-django 2.15.0)
	Found matching candidates:
	  <Candidate singledispatch 3.6.2 from https://pypi.org/simple/singledispatch/>
	  <Candidate singledispatch 3.6.1 from https://pypi.org/simple/singledispatch/>
	  <Candidate singledispatch 3.6.0 from https://pypi.org/simple/singledispatch/>
	  <Candidate singledispatch 3.5.0 from https://pypi.org/simple/singledispatch/>
	  <Candidate singledispatch 3.4.0.4 from https://pypi.org/simple/singledispatch/>
	  <Candidate singledispatch 3.4.0.3 from https://pypi.org/simple/singledispatch/>
	Adding requirement promise>=2.1(from graphene-django 2.15.0)
	Found matching candidates:
	  <Candidate promise 2.3 from https://pypi.org/simple/promise/>
	  <Candidate promise 2.2.1 from https://pypi.org/simple/promise/>
	  <Candidate promise 2.2 from https://pypi.org/simple/promise/>
	  <Candidate promise 2.1 from https://pypi.org/simple/promise/>
	Adding requirement text-unidecode(from graphene-django 2.15.0)
	Found matching candidates:
	  <Candidate text-unidecode 1.3 from https://pypi.org/simple/text-unidecode/>
Error occurs
Traceback (most recent call last):
  File "/usr/local/Cellar/pdm/1.5.3/libexec/lib/python3.9/site-packages/pdm/termui.py", line 192, in logging
    yield logger
  File "/usr/local/Cellar/pdm/1.5.3/libexec/lib/python3.9/site-packages/pdm/cli/actions.py", line 64, in do_lock
    mapping, dependencies, summaries = resolve(
  File "/usr/local/Cellar/pdm/1.5.3/libexec/lib/python3.9/site-packages/pdm/resolver/core.py", line 150, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "/usr/local/Cellar/pdm/1.5.3/libexec/lib/python3.9/site-packages/resolvelib/resolvers.py", line 473, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/local/Cellar/pdm/1.5.3/libexec/lib/python3.9/site-packages/resolvelib/resolvers.py", line 367, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/usr/local/Cellar/pdm/1.5.3/libexec/lib/python3.9/site-packages/resolvelib/resolvers.py", line 227, in _attempt_to_pin_criterion
    raise InconsistentCandidate(candidate, criterion)
resolvelib.resolvers.InconsistentCandidate: Provided candidate <Candidate graphene-django 2.15.0 from unknown> does not satisfy <NamedRequirement graphene-django~=2.15>, <NamedRequirement graphene-django>=2.0>, <NamedRequirement graphene-django>=3.0.0b1>
```

## Expected behavior

Package to be installed 

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:

PDM version:        1.5.3
Python Interpreter: /usr/local/bin/python3 (3.9)
Project Root:       /Users/apple/Projects/blixt_backend
Project Packages:   /Users/apple/Projects/blixt_backend/__pypackages__/3.9
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.5",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "21.0.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 21.0.0: Sun Jun 20 18:43:49 PDT 2021; root:xnu-8011.0.0.121.4~2/RELEASE_X86_64",
  "python_full_version": "3.9.5",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "darwin"
}

```

**Comment by frostming** [comment]
May I have the content of pyproject.toml?

**Comment by hrithik098** [comment]
```yaml
[project]
name = "Blixt Backend"
version = "0.1.0"
description = "Backend for Blixt & Co. ERP"
authors = [
    {name = "hrithik098", email = "hrithiky328@gmail.com"},
]
dependencies = [
    "pytz==2020.1",
    "python-slugify==4.0.0",
    "argon2-cffi==19.2.0",
    "redis==3.5.0",
    "hiredis==1.0.1",
    "celery==4.4.2",
    "django-celery-beat==2.0.0",
    "Django==3.0",
    "django-environ==0.4.5",
    "django-model-utils==4.0.0",
    "django-allauth==0.41.0",
    "django-crispy-forms==1.9.0",
    "django-redis==4.11.0",
    "djangorestframework==3.11.0",
    "django-tinymce==3.0.2",
    "django-cors-headers==3.5.0",
    "django-jsonfield==1.4.1",
    "loguru==0.5.3",
    "django-tailwind==1.1.1",
    "pretty-errors~=1.2",
    "Pillow~=8.2",
    "graphene-django~=2.15",
    "graphene-django-cud~=0.9",
]
requires-python = ">=3.8"
dynamic = ["classifiers"]
license = {text = "MIT"}

[project.urls]
homepage = ""


[project.optional-dependencies]
dev = [
    "Werkzeug==1.0.1",
    "ipdb==0.13.2",
    "Sphinx==3.0.4",
    "psycopg2-binary==2.8.5",
    "mypy==0.770",
    "django-stubs==1.5.0",
    "pytest==5.4.2",
    "pytest-sugar==0.9.3",
    "flake8==3.8.2",
    "flake8-isort==3.0.0",
    "coverage==5.1",
    "black==19.10b0",
    "pylint-django==2.0.15",
    "pylint-celery==0.3",
    "pre-commit==2.4.0",
    "factory-boy==2.12.0",
    "django-debug-toolbar==2.2",
    "django-extensions==2.2.9",
    "django-coverage-plugin==1.8.0",
    "pytest-django==3.9.0",
]
prod = [
    "gunicorn==20.0.4",
    "psycopg2==2.8.5",
    "Collectfast==2.1.0",
    "sentry-sdk==0.14.4",
    "django-storages[boto3]==1.9.1",
    "django-anymail[amazon_ses]==7.1.0",
]
[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

[tool.pdm.scripts]
_.env_file = ".env.base"
# TODO There is still the problem of python binary being named as `python3` and `python`
dev = {shell="python3 manage.py runserver 0.0.0.0:8000", help="Run Django development server at 0.0.0.0:8000", env_file="local.env"}
migrate = {shell="python3 manage.py migrate", help="Apply Django migrations"}
load_data = {shell="python3 manage.py loaddata fixtures/dump.json", help="Load server with dummy data for testing."}

# TODO Add refresh-dummy-data script to pdm scripts

[tool]

[tool.pdm]
allow_prereleases = true
```

**Comment by hrithik098** [comment]
So i found the `django-graphql-jwt` wants `graphene-django>=3.0.0b1`which is still in beta release. So I forked `django-graphql-jwt` and changed the graphene-django to my version. The error is still the same, I am installing it locally, but it still wants the same beta version.

**Comment by frostming** [comment]
1. Can you reduce the dependency set to minimal for reproduce? Can `graphene-django` and `django-graphql-jwt` alone reproduce?
2. Try upgrading to the latest release of PDM(v1.7.0)

**Comment by robtaylor** [comment]
I'm hitting the same kind of issue, with an upgrade to pdm breaking our internal builds and then not being able to lock. I think something that would help here is a better message about *why* the candidates don't match. In our case it seems to be a change around 'allow_prereleases" after some deeper debugging.
