### ISSUE TITLE
Unable to install aio-pika on pdm==1.7.0

### ISSUE THREAD

**Issue by Cameronwood611** [pdm-project/pdm#558]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

(I have seen other issues similar to this: #130, but I believe this is specifically a pdm issue now)
 
**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

pdm init
pdm add aio-pika -v

## Actual behavior

```
pdm add aio-pika -v
...

🔒 Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
Synchronizing working set with lock file: 2 to add, 0 to update, 0 to remove

Install aiormq 3.3.1 failed
Install aio-pika 6.8.0 failed
  Retry failed jobs
Install aiormq 3.3.1 failed
Install aio-pika 6.8.0 failed

ERRORS:
add aiormq failed:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/distlib/metadata.py", line 675, in __init__
    self._data = json.loads(data)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 157, in install_candidate
    installer.install(can)
  File "/usr/local/lib/python3.9/site-packages/pdm/installers/installers.py", line 47, in install
    self.install_wheel(Wheel(built))
  File "/usr/local/lib/python3.9/site-packages/pdm/installers/installers.py", line 57, in install_wheel
    wheel.install(paths, maker)
  File "/usr/local/lib/python3.9/site-packages/distlib/wheel.py", line 674, in install
    dist = InstalledDistribution(p)
  File "/usr/local/lib/python3.9/site-packages/distlib/database.py", line 558, in __init__
    metadata = Metadata(fileobj=stream, scheme='legacy')
  File "/usr/local/lib/python3.9/site-packages/distlib/metadata.py", line 684, in __init__
    self._legacy = LegacyMetadata(fileobj=StringIO(data),
  File "/usr/local/lib/python3.9/site-packages/distlib/metadata.py", line 259, in __init__
    self.read_file(fileobj)
  File "/usr/local/lib/python3.9/site-packages/distlib/metadata.py", line 357, in read_file
    self.set(field, value)
  File "/usr/local/lib/python3.9/site-packages/distlib/metadata.py", line 457, in set
    if not scheme.is_valid_constraint_list(value):
  File "/usr/local/lib/python3.9/site-packages/distlib/version.py", line 713, in is_valid_constraint_list
    return self.is_valid_matcher('dummy_name (%s)' % s)
  File "/usr/local/lib/python3.9/site-packages/distlib/version.py", line 703, in is_valid_matcher
    self.matcher(s)
  File "/usr/local/lib/python3.9/site-packages/distlib/version.py", line 115, in __init__
    raise ValueError('\'.*\' not allowed for '
ValueError: '.*' not allowed for '>' constraints
add aio-pika failed:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/distlib/metadata.py", line 675, in __init__
    self._data = json.loads(data)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 157, in install_candidate
    installer.install(can)
  File "/usr/local/lib/python3.9/site-packages/pdm/installers/installers.py", line 47, in install
    self.install_wheel(Wheel(built))
  File "/usr/local/lib/python3.9/site-packages/pdm/installers/installers.py", line 57, in install_wheel
    wheel.install(paths, maker)
  File "/usr/local/lib/python3.9/site-packages/distlib/wheel.py", line 674, in install
    dist = InstalledDistribution(p)
  File "/usr/local/lib/python3.9/site-packages/distlib/database.py", line 558, in __init__
    metadata = Metadata(fileobj=stream, scheme='legacy')
  File "/usr/local/lib/python3.9/site-packages/distlib/metadata.py", line 684, in __init__
    self._legacy = LegacyMetadata(fileobj=StringIO(data),
  File "/usr/local/lib/python3.9/site-packages/distlib/metadata.py", line 259, in __init__
    self.read_file(fileobj)
  File "/usr/local/lib/python3.9/site-packages/distlib/metadata.py", line 357, in read_file
    self.set(field, value)
  File "/usr/local/lib/python3.9/site-packages/distlib/metadata.py", line 457, in set
    if not scheme.is_valid_constraint_list(value):
  File "/usr/local/lib/python3.9/site-packages/distlib/version.py", line 713, in is_valid_constraint_list
    return self.is_valid_matcher('dummy_name (%s)' % s)
  File "/usr/local/lib/python3.9/site-packages/distlib/version.py", line 703, in is_valid_matcher
    self.matcher(s)
  File "/usr/local/lib/python3.9/site-packages/distlib/version.py", line 115, in __init__
    raise ValueError('\'.*\' not allowed for '
ValueError: '.*' not allowed for '>' constraints

Traceback (most recent call last):
  File "/usr/local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/pdm/core.py", line 194, in main
    return Core().main(args)
  File "/usr/local/lib/python3.9/site-packages/pdm/core.py", line 152, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/usr/local/lib/python3.9/site-packages/pdm/core.py", line 147, in main
    f(options.project, options)
  File "/usr/local/lib/python3.9/site-packages/pdm/cli/commands/add.py", line 51, in handle
    actions.do_add(
  File "/usr/local/lib/python3.9/site-packages/pdm/cli/actions.py", line 218, in do_add
    do_sync(
  File "/usr/local/lib/python3.9/site-packages/pdm/cli/actions.py", line 167, in do_sync
    handler.synchronize()
  File "/usr/local/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 324, in synchronize
    raise InstallationError("Some package operations are not complete yet")
pdm.exceptions.InstallationError: Some package operations are not complete yet
```

## Expected behavior

Install aio-pika (works fine with the exact same python version on pdm==1.6.4).

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:

➜  test-pdm pdm info && pdm info --env
PDM version:        1.7.0                                     
Python Interpreter: /usr/local/bin/python3 (3.9)              
Project Root:       /Users/cameron/test-pdm                   
Project Packages:   /Users/cameron/test-pdm/__pypackages__/3.9
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.5",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "20.5.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64",
  "python_full_version": "3.9.5",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "darwin"
}

```

**Comment by frostming** [comment]
It is indeed a regression. I think #519 will solve this problem by replacing `distlib` with `installer`. But if I am not able to do that (#519 is blocked by a bugfix release of the upstream) in a week I will fix it with the same approach of #130 and cut a release.
