### ISSUE TITLE
Updates fail with `FileExistsError` in 1.7.1

### ISSUE THREAD

**Issue by knowsuchagency** [pdm-project/pdm#567]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

`pdm install # or pdm update`

in my case...

```
Synchronizing working set with lock file: 242 to add, 1 to update, 0 to remove
```

## Actual behavior

```
Update setuptools 44.0.0 -> 57.4.0 failed
Traceback (most recent call last):
  File "/opt/circleci/.pyenv/versions/3.9.4/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/opt/circleci/.pyenv/versions/3.9.4/lib/python3.9/site-packages/pdm/core.py", line 194, in main
    return Core().main(args)
  File "/opt/circleci/.pyenv/versions/3.9.4/lib/python3.9/site-packages/pdm/core.py", line 152, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/opt/circleci/.pyenv/versions/3.9.4/lib/python3.9/site-packages/pdm/core.py", line 147, in main
    f(options.project, options)
  File "/opt/circleci/.pyenv/versions/3.9.4/lib/python3.9/site-packages/pdm/cli/commands/install.py", line 44, in handle
    actions.do_sync(
  File "/opt/circleci/.pyenv/versions/3.9.4/lib/python3.9/site-packages/pdm/cli/actions.py", line 167, in do_sync
    handler.synchronize()
  File "/opt/circleci/.pyenv/versions/3.9.4/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 306, in synchronize
    handlers[kind](key)
  File "/opt/circleci/.pyenv/versions/3.9.4/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 177, in update_candidate
    installer.install(can)
  File "/opt/circleci/.pyenv/versions/3.9.4/lib/python3.9/site-packages/pdm/installers/installers.py", line 66, in install
    self.install_wheel(built)
  File "/opt/circleci/.pyenv/versions/3.9.4/lib/python3.9/site-packages/pdm/installers/installers.py", line 79, in install_wheel
    install(
  File "/opt/circleci/.pyenv/versions/3.9.4/lib/python3.9/site-packages/installer/_core.py", line 113, in install
    record = destination.write_file(
  File "/opt/circleci/.pyenv/versions/3.9.4/lib/python3.9/site-packages/installer/destinations.py", line 151, in write_file
    return self.write_to_fs(scheme, path, stream)
  File "/opt/circleci/.pyenv/versions/3.9.4/lib/python3.9/site-packages/installer/destinations.py", line 124, in write_to_fs
    raise FileExistsError(message)
FileExistsError: File already exists: /home/circleci/project/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py
```

## Expected behavior

For `pdm` to successfully install packages

## Environment Information

```bash
❯ pdm info
PDM version:        1.7.1   
```

**Comment by frostming** [comment]
Duplicate with #565, was fixed in the main branch
