### ISSUE TITLE
Cannot install nltk

### ISSUE THREAD

**Issue by pabloelisseo** [pdm-project/pdm#577]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce
In a empty project just run
`pdm add nltk`

## Actual behavior
Logs are too big, I'll paste the part is describing the errror:
```
Install nltk 3.6.2 failed
  Retry failed jobs
Install nltk 3.6.2 failed

ERRORS:
add nltk failed:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/distlib/metadata.py", line 677, in __init__
    self._data = json.loads(data)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 157, in install_candidate
    installer.install(can)
  File "/usr/local/lib/python3.9/site-packages/pdm/installers/installers.py", line 47, in install
    self.install_wheel(Wheel(built))
  File "/usr/local/lib/python3.9/site-packages/pdm/installers/installers.py", line 57, in install_wheel
    wheel.install(paths, maker)
  File "/usr/local/lib/python3.9/site-packages/distlib/wheel.py", line 684, in install
    dist = InstalledDistribution(p)
  File "/usr/local/lib/python3.9/site-packages/distlib/database.py", line 558, in __init__
    metadata = Metadata(fileobj=stream, scheme='legacy')
  File "/usr/local/lib/python3.9/site-packages/distlib/metadata.py", line 686, in __init__
    self._legacy = LegacyMetadata(fileobj=StringIO(data),
  File "/usr/local/lib/python3.9/site-packages/distlib/metadata.py", line 261, in __init__
    self.read_file(fileobj)
  File "/usr/local/lib/python3.9/site-packages/distlib/metadata.py", line 359, in read_file
    self.set(field, value)
  File "/usr/local/lib/python3.9/site-packages/distlib/metadata.py", line 459, in set
    if not scheme.is_valid_constraint_list(value):
  File "/usr/local/lib/python3.9/site-packages/distlib/version.py", line 716, in is_valid_constraint_list
    return self.is_valid_matcher('dummy_name (%s)' % s)
  File "/usr/local/lib/python3.9/site-packages/distlib/version.py", line 703, in is_valid_matcher
    self.matcher(s)
  File "/usr/local/lib/python3.9/site-packages/distlib/version.py", line 115, in __init__
    raise ValueError('\'.*\' not allowed for '
ValueError: '.*' not allowed for '>=' constraints

Traceback (most recent call last):
  File "/usr/local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/pdm/core.py", line 194, in main
    return Core().main(args)
  File "/usr/local/lib/python3.9/site-packages/pdm/core.py", line 152, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/usr/local/lib/python3.9/site-packages/pdm/core.py", line 147, in main
    f(options.project, options)
  File "/usr/local/lib/python3.9/site-packages/pdm/cli/commands/add.py", line 51, in handle
    actions.do_add(
  File "/usr/local/lib/python3.9/site-packages/pdm/cli/actions.py", line 218, in do_add
    do_sync(
  File "/usr/local/lib/python3.9/site-packages/pdm/cli/actions.py", line 167, in do_sync
    handler.synchronize()
  File "/usr/local/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 324, in synchronize
    raise InstallationError("Some package operations are not complete yet")
pdm.exceptions.InstallationError: Some package operations are not complete yet
```

## Expected behavior

The package to be installed.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.7.0                          
Python Interpreter: /usr/local/bin/python (3.9)    
Project Root:       /usr/src/app                   
Project Packages:   /usr/src/app/__pypackages__/3.9
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.6",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.10.16.3-microsoft-standard-WSL2",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Fri Apr 2 22:23:49 UTC 2021",
  "python_full_version": "3.9.6",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

**Comment by pabloelisseo** [comment]
I have also experienced the same error tying to install `smart-open==5.1.0` in the same environment (and also in a similar docker with 3.8.11 version0.

**Comment by frostming** [comment]
Try upgrading pdm to the latest version

**Comment by ElijahSink** [comment]
Working fine for me on 1.7.2!

**Comment by pabloelisseo** [comment]
As @ElijahSink said working fine in latest version. Thank you so much!
