### ISSUE TITLE
"pdm init" issue with pyenv version of Python (Ubuntu 21.04)

### ISSUE THREAD

**Issue by btegs** [pdm-project/pdm#590]
I currently have [pyenv](https://github.com/pyenv/pyenv) installed to manage my Python versions and when I do `which python3`, I get the output of `/home/btegs/.pyenv/shims/python3`.

**TLDR:** Maybe PDM can look for a python path of `python3` first then fallback to `python` if `python3` doesn't exist. That will cover both bases as we need to target Python 3.

This has worked in the past as pyenv is working with my `.profile` in Ubuntu 21.04 and have been able to use other tools like [Poetry](https://python-poetry.org/). I am currently using the default Python 3.9 (listed as system in pyenv) and if I am in a directory and do a `pdm init` I get this error: 

```
Creating a pyproject.toml for PDM...
[ValueError]: Not a valid python path: '/home/btegs/.pyenv/shims/python'
Add '-v' to see the detailed traceback
```
and if I pass the -v flag, this is what it tells me:

```
Creating a pyproject.toml for PDM...
Traceback (most recent call last):
  File "/home/btegs/.local/share/pdm/venv/lib/python3.9/site-packages/pythonfinder/models/python.py", line 582, in from_path
    instance_dict = cls.parse(path_name)
  File "/home/btegs/.local/share/pdm/venv/lib/python3.9/site-packages/pythonfinder/models/python.py", line 533, in parse
    version_dict = parse_python_version(str(version))
  File "/home/btegs/.local/share/pdm/venv/lib/python3.9/site-packages/pythonfinder/utils.py", line 131, in parse_python_version
    raise InvalidPythonVersion("%s is not a python version" % version_str)
pythonfinder.exceptions.InvalidPythonVersion: python is not a python version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/btegs/.local/share/pdm/venv/lib/python3.9/site-packages/pythonfinder/models/python.py", line 618, in parse_executable
    result_version = get_python_version(path)
  File "/home/btegs/.local/share/pdm/venv/lib/python3.9/site-packages/pythonfinder/utils.py", line 116, in get_python_version
    raise InvalidPythonVersion("%s is not a valid python path" % path)
pythonfinder.exceptions.InvalidPythonVersion: /home/btegs/.pyenv/shims/python is not a valid python path

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/btegs/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/btegs/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/core.py", line 194, in main
    return Core().main(args)
  File "/home/btegs/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/core.py", line 152, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/home/btegs/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/core.py", line 147, in main
    f(options.project, options)
  File "/home/btegs/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/cli/commands/init.py", line 45, in handle
    actions.do_use(project)
  File "/home/btegs/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/cli/actions.py", line 481, in do_use
    dict.fromkeys(filter(version_matcher, project.find_interpreters(python)))
  File "/home/btegs/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/project/core.py", line 560, in find_interpreters
    yield PythonInfo.from_path(pyenv_shim)
  File "/home/btegs/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/models/python.py", line 38, in from_path
    return cls.from_python_version(PythonVersion.from_path(str(path)))
  File "/home/btegs/.local/share/pdm/venv/lib/python3.9/site-packages/pythonfinder/models/python.py", line 584, in from_path
    instance_dict = cls.parse_executable(path.path.absolute().as_posix())
  File "/home/btegs/.local/share/pdm/venv/lib/python3.9/site-packages/pythonfinder/models/python.py", line 620, in parse_executable
    raise ValueError("Not a valid python path: %r" % path)
ValueError: Not a valid python path: '/home/btegs/.pyenv/shims/python'
```

What could help is that the initial install script and the references you have inside pdm should reference the `python3` executable if it exists instead of `python` as it may be linked to Python 2.7 which may no longer be installed.

I also want to note that if I try to execute `python` or `~/.pyenv/shims/python` in the terminal I get this:

```
pyenv: python: command not found

The `python' command exists in these Python versions:
  2.7.18
  3.8.11

Note: See 'pyenv help global' for tips on allowing both
      python2 and python3 to be found.

```

but `python3` or `~/.pyenv/shims/python3` will return the proper runtime:

```
Python 3.9.5 (default, May 11 2021, 08:20:37) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

**Comment by frostming** [comment]
Would it work if you `pyenv global` to set an interpreter?

**Comment by btegs** [comment]
> Would it work if you `pyenv global` to set an interpreter?

If I type `pyenv global` it will output `system` as I currently want Ubuntu to use the system Python for the packages that require it. Since I am using the Python 3 that comes with Ubuntu as the default and do not have Python 2.7 installed, the `python` command will fail if i have the global set to the system.

Pyenv seems to not provide the `python` runtime if set to `system` with Python 2 not installed, but if I were to change the system default (which I don't want to do) or do a `pyenv local` inside of a directory, it will work.

For example, my system Python 3 is 3.9.5, but if I create a new folder, install a newer version via `pyenv install 3.9.6` and then do `pyenv local 3.9.6`, both the `python` and `python3` runtimes are available to PDM and I can do the `pdm init` without issue.

**Comment by ndpu** [comment]
Same situation: ubuntu 22.04 with 3.10 system python and python 2.7 installed by pyenv. **Setting pyenv local to system in dir does not help!**
```
$ pyenv versions
* system (set by /home/user/Desktop/bt200 reports/.python-version)
  2.7.18
```
pdm init error:

```
$ pdm init
Creating a pyproject.toml for PDM...
Please enter the Python interpreter to use
[CalledProcessError]: Command '['/home/user/.pyenv/shims/python', '-c', 'import sys; print(sys.executable)']' returned non-zero exit 
status 127.
Add '-v' to see the detailed traceback

```
Executing python output:
```
pyenv: python: command not found

The `python' command exists in these Python versions:
  2.7.18

Note: See 'pyenv help global' for tips on allowing both
      python2 and python3 to be found.
```

Workaround: **temporarily remove ~/.pyenv/shims/python** executable. Running pdm init without it works:
```
$ pdm init
Creating a pyproject.toml for PDM...
Please enter the Python interpreter to use
0. /usr/bin/python3.10 (3.10)
1. /home/user/.pyenv/versions/2.7.18/bin/python2.7 (2.7)
2. /home/user/.local/share/pdm/venv/bin/python (3.10)
```
I think additional command line argument to pdm init - _python interpreter_ can be helpful...
