### ISSUE TITLE
Cannot install psycopg3

### ISSUE THREAD

**Issue by frafra** [pdm-project/pdm#614]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

```
pdm config pypi.url https://test.pypi.org/simple
pdm add -v psycopg
```

## Actual behavior

```
Adding packages to default dependencies: psycopg
======== Start resolving requirements ========
  psycopg
  Adding requirement psycopg
	Found matching candidates:
	  <Candidate psycopg 3.0.dev1 from https://test.pypi.org/simple/psycopg/>
	  <Candidate psycopg 3.0.dev0 from https://test.pypi.org/simple/psycopg/>
======== Starting round 0 ========
Preparing isolated env for PEP 517 build...
Looking in indexes: https://test.pypi.org/simple
ERROR: Could not find a version that satisfies the requirement setuptools>=49.2.0 (from versions: none)
ERROR: No matching distribution found for setuptools>=49.2.0
Failed to build package, try parsing project files.
Traceback (most recent call last):
  File "/home/frafra/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/builders/base.py", line 78, in log_subprocessor
    subprocess.check_call(
  File "/home/frafra/Downloads/python-3.9.6/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/frafra/bin/python3.9', '-Esm', 'pip', 'install', '--ignore-installed', '--prefix', '/tmp/pdm-build-env-8bgnquti-shared', '-i', 'https://test.pypi.org/simple', '-r', '/tmp/pdm-build-reqs-t6wqd51c.txt']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frafra/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/models/candidates.py", line 214, in metadata
    self._metadata_dir = builder(
  File "/home/frafra/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/builders/wheel.py", line 13, in prepare_metadata
    self.install(self._build_system["requires"], shared=True)
  File "/home/frafra/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/builders/base.py", line 250, in install
    self.subprocess_runner(cmd, isolated=False)
  File "/home/frafra/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/builders/base.py", line 212, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
  File "/home/frafra/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/builders/base.py", line 86, in log_subprocessor
    raise BuildError(f"Call command {cmd} return non-zero status.")
pdm.exceptions.BuildError: Call command ['/home/frafra/bin/python3.9', '-Esm', 'pip', 'install', '--ignore-installed', '--prefix', '/tmp/pdm-build-env-8bgnquti-shared', '-i', 'https://test.pypi.org/simple', '-r', '/tmp/pdm-build-reqs-t6wqd51c.txt'] return non-zero status.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frafra/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/frafra/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/core.py", line 195, in main
    return Core().main(args)
  File "/home/frafra/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/core.py", line 153, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/home/frafra/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/core.py", line 148, in main
    f(options.project, options)
  File "/home/frafra/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/cli/commands/add.py", line 62, in handle
    actions.do_add(
  File "/home/frafra/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/cli/actions.py", line 209, in do_add
    resolved = do_lock(project, strategy, tracked_names, reqs)
  File "/home/frafra/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/cli/actions.py", line 68, in do_lock
    mapping, dependencies, summaries = resolve(
  File "/home/frafra/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/resolver/core.py", line 30, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "/home/frafra/.local/pipx/venvs/pdm/lib/python3.9/site-packages/resolvelib/resolvers.py", line 472, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/frafra/.local/pipx/venvs/pdm/lib/python3.9/site-packages/resolvelib/resolvers.py", line 366, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/home/frafra/.local/pipx/venvs/pdm/lib/python3.9/site-packages/resolvelib/resolvers.py", line 212, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "/home/frafra/.local/pipx/venvs/pdm/lib/python3.9/site-packages/resolvelib/resolvers.py", line 202, in _get_updated_criteria
    for requirement in self._p.get_dependencies(candidate=candidate):
  File "/home/frafra/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/resolver/providers.py", line 106, in get_dependencies
    deps, requires_python, summary = self.repository.get_dependencies(candidate)
  File "/home/frafra/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/models/repositories.py", line 79, in get_dependencies
    requirements, requires_python, summary = getter(candidate)
  File "/home/frafra/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/models/repositories.py", line 46, in wrapper
    result = func(self, candidate)
  File "/home/frafra/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/models/repositories.py", line 181, in _get_dependencies_from_metadata
    deps = candidate.get_dependencies_from_metadata()
  File "/home/frafra/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/models/candidates.py", line 273, in get_dependencies_from_metadata
    self.metadata.requires or [], extras  # type: ignore
  File "/home/frafra/Downloads/python-3.9.6/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File "/home/frafra/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/models/candidates.py", line 221, in metadata
    result = parse_metadata_from_source(self.source_dir)
  File "/home/frafra/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/models/requirements.py", line 506, in parse_metadata_from_source
    setup = Setup.from_directory(Path(src_dir))
  File "/home/frafra/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/models/setup.py", line 37, in from_directory
    return _SetupReader.read_from_directory(dir)
  File "/home/frafra/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/models/setup.py", line 59, in read_from_directory
    new_result = file_reader(filepath)
  File "/home/frafra/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/models/setup.py", line 97, in read_setup_py
    extras_require=cls._find_extras_require(setup_call, body),
  File "/home/frafra/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/models/setup.py", line 312, in _find_extras_require
    extras_require[key.s] = [e.s for e in val.elts]
  File "/home/frafra/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/models/setup.py", line 312, in <listcomp>
    extras_require[key.s] = [e.s for e in val.elts]
AttributeError: 'JoinedStr' object has no attribute 's'
```

## Expected behavior

psycopg3 installed.

## Environment Information

```bash
PDM version:        1.8.0                                                            
Python Interpreter: /home/frafra/bin/python3.9 (3.9)                   
Project Root:       /home/frafra/Code/csv2postgresql                   
Project Packages:   /home/frafra/Code/csv2postgresql/__pypackages__/3.9
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.6",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "4.15.0-147-generic",
  "platform_system": "Linux",
  "platform_version": "#151-Ubuntu SMP Fri Jun 18 19:21:19 UTC 2021",
  "python_full_version": "3.9.6",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
`https://test.pypi.org/simple` can't be used as a *PyPI* mirror, instead, it should be used as an *extra index*, you can do this by adding a source in pyproject.toml:

```toml
[tool.pdm]
allow_prereleases = true  # this is also required to pick lates dev versions from test PyPI

[[tool.pdm.source]]
url = "https://test.pypi.org/simple"
name = "test"
verify_ssl = true
```
