### ISSUE TITLE
CalledProcessError with editable install: "No module named pip"

### ISSUE THREAD

**Issue by blueyed** [pdm-project/pdm#626]
Trying to `pdm add -e` pytest (current main branch, https://github.com/pytest-dev/pytest/tree/59189ebeb51be1241024b7977f279f14269ff62f) I get the following error:

```
% ~v/pdm/.venv/bin/pdm add -e /tmp/pytest -d -v
Adding packages to dev dev-dependencies: pytest
======== Start resolving requirements ========
  -e file:///tmp/pytest#egg=pytest
  Adding requirement -e file:///tmp/pytest#egg=pytest
Preparing isolated env for PEP 517 build...
Collecting setuptools
  Using cached setuptools-57.4.0-py3-none-any.whl (819 kB)
Installing collected packages: setuptools
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
twine 3.4.2 requires setuptools-scm[toml]>=6.0, which is not installed.
twine 3.4.2 requires wheel, which is not installed.
Successfully installed setuptools-57.4.0
WARNING: The wheel package is not available.
/usr/bin/python: No module named pip
Traceback (most recent call last):
  File "/tmp/pdm-build-env-n7lolnv9-overlay/lib/python3.9/site-packages/setuptools/installer.py", line 75, in fetch_build_egg
    subprocess.check_call(cmd)
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmplv5h9040', '--quiet', 'setuptools-scm[toml]>=3.4']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/pytest/setup.py", line 4, in <module>
    setup()
  File "/tmp/pdm-build-env-n7lolnv9-overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 152, in setup
    _install_setup_requires(attrs)
  File "/tmp/pdm-build-env-n7lolnv9-overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/tmp/pdm-build-env-n7lolnv9-overlay/lib/python3.9/site-packages/setuptools/dist.py", line 785, in fetch_build_eggs
    resolved_dists = pkg_resources.working_set.resolve(
  File "/tmp/pdm-build-env-n7lolnv9-overlay/lib/python3.9/site-packages/pkg_resources/__init__.py", line 766, in resolve
    dist = best[req.key] = env.best_match(
  File "/tmp/pdm-build-env-n7lolnv9-overlay/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1051, in best_match
    return self.obtain(req, installer)
  File "/tmp/pdm-build-env-n7lolnv9-overlay/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1063, in obtain
    return installer(requirement)
  File "/tmp/pdm-build-env-n7lolnv9-overlay/lib/python3.9/site-packages/setuptools/dist.py", line 844, in fetch_build_egg
    return fetch_build_egg(self, req)
  File "/tmp/pdm-build-env-n7lolnv9-overlay/lib/python3.9/site-packages/setuptools/installer.py", line 77, in fetch_build_egg
    raise DistutilsError(str(e)) from e
distutils.errors.DistutilsError: Command '['/usr/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmplv5h9040', '--quiet', 'setuptools-scm[toml]>=3.4']' returned non-zero exit status 1.
Failed to build package, try parsing project files.
======== Starting round 0 ========
Traceback (most recent call last):
  File "…/Vcs/pdm/.venv/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/pdm/core.py", line 194, in main
    return Core().main(args)
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/pdm/core.py", line 152, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/pdm/core.py", line 147, in main
    f(options.project, options)
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/pdm/cli/commands/add.py", line 51, in handle
    actions.do_add(
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/pdm/cli/actions.py", line 208, in do_add
    resolved = do_lock(project, strategy, tracked_names, reqs)
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/pdm/cli/actions.py", line 68, in do_lock
    mapping, dependencies, summaries = resolve(
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/pdm/resolver/core.py", line 30, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/resolvelib/resolvers.py", line 472, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/resolvelib/resolvers.py", line 366, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/resolvelib/resolvers.py", line 212, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/resolvelib/resolvers.py", line 202, in _get_updated_criteria
    for requirement in self._p.get_dependencies(candidate=candidate):
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/pdm/resolver/providers.py", line 106, in get_dependencies
    deps, requires_python, summary = self.repository.get_dependencies(candidate)
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/pdm/models/repositories.py", line 79, in get_dependencies
    requirements, requires_python, summary = getter(candidate)
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/pdm/models/repositories.py", line 47, in wrapper
    self._candidate_info_cache.set(candidate, result)
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/pdm/models/caches.py", line 58, in set
    key = self._get_key(candidate)
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/pdm/models/caches.py", line 45, in _get_key
    raise KeyError
KeyError
```

pyproject.toml:
```toml
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "user name", email = "foo@example.com"},
]
dependencies = []
requires-python = ">=3.9"
dynamic = ["classifiers"]
license = {text = "MIT"}

[project.urls]
homepage = ""

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

[tool]
[tool.pdm]
```

Note that `/usr/bin/python -m pip` works (i.e. the module is available in /usr/lib/python3.9/site-packages/pip/__init__.py) - despite the error / warning above.
Also running the command (`/usr/bin/python -m pip --disable-pip-version-check wheel --no-deps -w /tmp/tmp4wgcfp8p 'setuptools-scm[toml]>=3.4'`) manually works.

It looks like for some reason pip and wheel are missing when it is run through pdm!?

btw: why is twine involved here!?

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.8.0
Python Interpreter: /usr/bin/python (3.9)
Project Root:       /tmp/test-pdm-e
Project Packages:   /tmp/test-pdm-e/__pypackages__/3.9
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.6",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.13.10-arch1-1",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT Thu, 12 Aug 2021 21:59:14 +0000",
  "python_full_version": "3.9.6",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

**Comment by blueyed** [comment]
Using main (1018d07) it looks like this:
```
% ~v/pdm/.venv/bin/pdm add -e /tmp/pytest -d -v
Adding packages to dev dev-dependencies: pytest
======== Start resolving requirements ========
  -e file:///tmp/pytest#egg=pytest
  Adding requirement -e file:///tmp/pytest#egg=pytest
Preparing isolated env for PEP 517 build...
Collecting setuptools>=42.0
  Using cached setuptools-57.4.0-py3-none-any.whl (819 kB)
Collecting wheel
  Using cached wheel-0.37.0-py2.py3-none-any.whl (35 kB)
Collecting setuptools-scm[toml]>=3.4
  Using cached setuptools_scm-6.0.1-py3-none-any.whl (27 kB)
Collecting toml
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Installing collected packages: setuptools, toml, setuptools-scm, wheel
  WARNING: The script wheel is installed in '/tmp/pdm-build-env-e34h9vx9-shared/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed setuptools-57.4.0 setuptools-scm-6.0.1 toml-0.10.2 wheel-0.37.0
Collecting setuptools_pep660
  Using cached setuptools_pep660-0.1-py3-none-any.whl (4.1 kB)
Collecting setuptools>=42
  Using cached setuptools-57.4.0-py3-none-any.whl (819 kB)
Collecting wheel
  Using cached wheel-0.37.0-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel, setuptools, setuptools-pep660
  WARNING: The script wheel is installed in '/tmp/pdm-build-env-e34h9vx9-shared/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
twine 3.4.2 requires setuptools-scm[toml]>=6.0, which is not installed.
Successfully installed setuptools-57.4.0 setuptools-pep660-0.1 wheel-0.37.0
running editable_wheel
running dist_info
creating /tmp/pdm-meta-qsim7_tq/tmpnmno4jfh/pytest.egg-info
writing /tmp/pdm-meta-qsim7_tq/tmpnmno4jfh/pytest.egg-info/PKG-INFO
writing dependency_links to /tmp/pdm-meta-qsim7_tq/tmpnmno4jfh/pytest.egg-info/dependency_links.txt
writing entry points to /tmp/pdm-meta-qsim7_tq/tmpnmno4jfh/pytest.egg-info/entry_points.txt
writing requirements to /tmp/pdm-meta-qsim7_tq/tmpnmno4jfh/pytest.egg-info/requires.txt
writing top-level names to /tmp/pdm-meta-qsim7_tq/tmpnmno4jfh/pytest.egg-info/top_level.txt
writing manifest file '/tmp/pdm-meta-qsim7_tq/tmpnmno4jfh/pytest.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file '/tmp/pdm-meta-qsim7_tq/tmpnmno4jfh/pytest.egg-info/SOURCES.txt'
creating '/tmp/pdm-meta-qsim7_tq/tmpnmno4jfh/pytest.dist-info'
running build_ext
Traceback (most recent call last):
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_editable
    hook = backend.prepare_metadata_for_build_editable
AttributeError: module 'setuptools_pep660' has no attribute 'prepare_metadata_for_build_editable'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 349, in <module>
    main()
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 331, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 174, in prepare_metadata_for_build_editable
    return _get_wheel_metadata_from_wheel(whl_basename,
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 209, in _get_wheel_metadata_from_wheel
    dist_info = _dist_info_files(zipf)
  File "…/Vcs/pdm/.venv/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 193, in _dist_info_files
    raise Exception("No .dist-info folder found in wheel")
Exception: No .dist-info folder found in wheel
Failed to build package, try parsing project files.
…
```

**Comment by frostming** [comment]
A new version of `setuptools-pep660` is released, this should be fixed.
