### ISSUE TITLE
Error in `pdm install -dG`

### ISSUE THREAD

**Issue by abersheeran** [pdm-project/pdm#633]
https://github.com/abersheeran/baize/pull/16/checks?check_run_id=3475234673

Error message:
```
  pdm install -dG build
  pdm run pytest tests -o log_cli=true -o log_cli_level=DEBUG
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.7.11/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.7.11/x64/lib:/opt/hostedtoolcache/Python/3.8.11/x64/lib
    PYTHONPATH: /opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/pdm/pep582
    LD_PRELOAD: /lib/x86_64-linux-gnu/libgcc_s.so.1
All packages are synced to date, nothing to do.

Installing the project as an editable package...
Update baize 0.10.1 -> 0.10.1 failed
  See /tmp/pdm-install-dtxd9lu3.log for detailed debug log.
  Add '-v' to see the detailed traceback
  [UninstallError]: [Errno 2] No such file or directory: '/home/runner/work/baize/baize/__pypackages__/3.7/lib/__pycache__/_baize.cpython-37.pyc'
Error: Process completed with exit code 1.
```

**Comment by abersheeran** [comment]
verbose:
```
  pdm install -v -dG build
  pdm run pytest tests -o log_cli=true -o log_cli_level=DEBUG
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.7.11/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.7.11/x64/lib:/opt/hostedtoolcache/Python/3.8.11/x64/lib
    PYTHONPATH: /opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/pdm/pep582
    LD_PRELOAD: /lib/x86_64-linux-gnu/libgcc_s.so.1
All packages are synced to date, nothing to do.

Installing the project as an editable package...
Removing file /home/runner/work/baize/baize/__pypackages__/3.7/lib/baize.pth
Removing file /home/runner/work/baize/baize/__pypackages__/3.7/lib/_baize.py
Removing directory /home/runner/work/baize/baize/__pypackages__/3.7/lib/baize/
Removing file /home/runner/work/baize/baize/__pypackages__/3.7/lib/__pycache__/_baize.cpython-37.pyc
Error occurred during uninstallation, roll back the changes now.
Rollback /home/runner/work/baize/baize/__pypackages__/3.7/lib/baize.pth
 from /tmp/pdm-xa36z3x3-uninstall/baize.pth
Rollback /home/runner/work/baize/baize/__pypackages__/3.7/lib/_baize.py
 from /tmp/pdm-xa36z3x3-uninstall/_baize.py
Rollback /home/runner/work/baize/baize/__pypackages__/3.7/lib/baize/
 from /tmp/pdm-xa36z3x3-uninstall/baize
Update baize 0.10.1 -> 0.10.1 failed
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/shutil.py", line 791, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/baize/baize/__pypackages__/3.7/lib/__pycache__/_baize.cpython-37.pyc' -> '/tmp/pdm-xa36z3x3-uninstall/__pycache__/_baize.cpython-37.pyc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/pdm/installers/manager.py", line 41, in uninstall
    remove_path.remove()
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/pdm/installers/uninstallers.py", line 208, in remove
    self._stash_files()
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/pdm/installers/uninstallers.py", line 250, in _stash_files
    renames(old_path, new_path)
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/pdm/installers/uninstallers.py", line 28, in renames
    shutil.move(old, new)
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/shutil.py", line 811, in move
    copy_function(src, real_dst)
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/baize/baize/__pypackages__/3.7/lib/__pycache__/_baize.cpython-37.pyc'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.11/x64/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/pdm/core.py", line 198, in main
    return Core().main(args)
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/pdm/core.py", line 153, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/pdm/core.py", line 148, in main
    f(options.project, options)
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/pdm/cli/commands/install.py", line 44, in handle
    actions.do_sync(
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/pdm/cli/actions.py", line 170, in do_sync
    handler.synchronize()
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 370, in synchronize
    self.update_candidate(self_key)
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 209, in update_candidate
    self.manager.uninstall(dist)
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/pdm/installers/manager.py", line 48, in uninstall
    raise UninstallError(e) from e
pdm.exceptions.UninstallError: [Errno 2] No such file or directory: '/home/runner/work/baize/baize/__pypackages__/3.7/lib/__pycache__/_baize.cpython-37.pyc'
Error: Process completed with exit code 1.
```
