### ISSUE TITLE
KeyError caffe2/ when installing torch 1.5.1+cpu

### ISSUE THREAD

**Issue by pawamoy** [pdm-project/pdm#636]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

It's actually quite similar to the last comment of #500.

## Steps to reproduce

```console
$ pdm install -v
...
Install torch 1.5.1+cpu failed
Error occurs: 
Traceback (most recent call last):
  File "/usr/lib64/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 190, in install_candidate
    self.manager.install(can)
  File "/usr/local/lib/python3.8/site-packages/pdm/installers/manager.py", line 31, in install
    installer(candidate.build(), self.environment, candidate.direct_url())
  File "/usr/local/lib/python3.8/site-packages/pdm/installers/installers.py", line 74, in install_wheel
    _install_wheel(
  File "/usr/local/lib/python3.8/site-packages/pdm/installers/installers.py", line 173, in _install_wheel
    for record_elements, stream in source.get_contents():
  File "/usr/local/lib/python3.8/site-packages/installer/sources.py", line 165, in get_contents
    record = record_mapping.pop(item.filename)
KeyError: 'caffe2/'
```

**EDIT:** ah, you might not be able to reproduce since torch CPU versions are not on pypi.org I think...

## Actual behavior

It seems PDM 1.8.1 / `installer` has troube installing torch 1.5.1+cpu.

## Expected behavior

I think versions of PDM before the ones using `installer` were able to install torch 1.5.1+cpu without issues.

## Environment Information

Running in CI, so I don't have the output of the PDM info commands, but it's CPython 3.8.3 on Linux and PDM 1.8.1.

**Comment by pawamoy** [comment]
Ah, I think it's a simple bug in `installer`: `pop(item.filename)` -> `pop(item.filename, None)`. Let me close and open again there.

**Comment by pawamoy** [comment]
I guess it means the wheel for torch 1.5.1+cpu is broken though.
