### ISSUE TITLE
Install error with mypyc compiled package

### ISSUE THREAD

**Issue by abersheeran** [pdm-project/pdm#652]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Just run `pdm add baize`

```
> pdm install -v    
Synchronizing working set with lock file: 1 to add, 0 to update, 0 to remove

Install baize 0.10.1 failed
Error occurs:
Traceback (most recent call last):
  File "c:\users\aber\appdata\local\programs\python\python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\aber\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\synchronizers.py", line 190, in install_candidate
    self.manager.install(can)
  File "C:\Users\aber\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\manager.py", line 31, in install
    installer(candidate.build(), self.environment, candidate.direct_url())
  File "C:\Users\aber\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\installers.py", line 74, in install_wheel
    _install_wheel(
  File "C:\Users\aber\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\installers.py", line 176, in _install_wheel
    for record_elements, stream in source.get_contents():
  File "C:\Users\aber\.local\pipx\venvs\pdm\lib\site-packages\installer\sources.py", line 165, in get_contents
    record = record_mapping.pop(item.filename)
KeyError: 'baize/asgi.py'
  Retry failed jobs
Install baize 0.10.1 failed
Error occurs:
Traceback (most recent call last):
  File "c:\users\aber\appdata\local\programs\python\python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\aber\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\synchronizers.py", line 190, in install_candidate
    self.manager.install(can)
  File "C:\Users\aber\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\manager.py", line 31, in install
    installer(candidate.build(), self.environment, candidate.direct_url())
  File "C:\Users\aber\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\installers.py", line 74, in install_wheel
    _install_wheel(
  File "C:\Users\aber\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\installers.py", line 176, in _install_wheel
    for record_elements, stream in source.get_contents():
  File "C:\Users\aber\.local\pipx\venvs\pdm\lib\site-packages\installer\sources.py", line 165, in get_contents
    record = record_mapping.pop(item.filename)
KeyError: 'baize/asgi.py'

ERRORS:
add baize failed:
Traceback (most recent call last):
  File "c:\users\aber\appdata\local\programs\python\python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\aber\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\synchronizers.py", line 190, in install_candidate
    self.manager.install(can)
  File "C:\Users\aber\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\manager.py", line 31, in install
    installer(candidate.build(), self.environment, candidate.direct_url())
  File "C:\Users\aber\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\installers.py", line 74, in install_wheel
    _install_wheel(
  File "C:\Users\aber\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\installers.py", line 176, in _install_wheel
    for record_elements, stream in source.get_contents():
  File "C:\Users\aber\.local\pipx\venvs\pdm\lib\site-packages\installer\sources.py", line 165, in get_contents
    record = record_mapping.pop(item.filename)
KeyError: 'baize/asgi.py'

Traceback (most recent call last):
  File "c:\users\aber\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\aber\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\aber\.local\bin\pdm.exe\__main__.py", line 7, in <module>
  File "C:\Users\aber\.local\pipx\venvs\pdm\lib\site-packages\pdm\core.py", line 198, in main
    return Core().main(args)
  File "C:\Users\aber\.local\pipx\venvs\pdm\lib\site-packages\pdm\core.py", line 153, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "C:\Users\aber\.local\pipx\venvs\pdm\lib\site-packages\pdm\core.py", line 148, in main
    f(options.project, options)
  File "C:\Users\aber\.local\pipx\venvs\pdm\lib\site-packages\pdm\cli\commands\install.py", line 44, in handle
    actions.do_sync(
  File "C:\Users\aber\.local\pipx\venvs\pdm\lib\site-packages\pdm\cli\actions.py", line 170, in do_sync
    handler.synchronize()
  File "C:\Users\aber\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\synchronizers.py", line 357, in synchronize
    raise InstallationError("Some package operations are not complete yet")
pdm.exceptions.InstallationError: Some package operations are not complete yet
```

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.8.3
Python Interpreter: C:/Users/aber/AppData/Local/Programs/Python/Python39/python.EXE (3.9)
Project Root:       C:/Users/aber/Documents/GitHub/multidict
Project Packages:   C:\Users\aber\Documents\GitHub\multidict\__pypackages__\3.9
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.6",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19043",
  "python_full_version": "3.9.6",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "win32"
}
```

## Other info

In https://pypi.org/project/baize/#files , baize has some compiled wheel, but pdm try build in local.

**Comment by abersheeran** [comment]
Other familiar issue: https://github.com/pdm-project/pdm/issues/269

**Comment by frostming** [comment]
This is an issue with the build tool, closing it now

**Comment by abersheeran** [comment]
I used `setup.py bdist_wheel sdist` replace `poetry build` to fixed it.
