### ISSUE TITLE
Could not install ortools

### ISSUE THREAD

**Issue by lgblkb** [pdm-project/pdm#653]
- [ ] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

pdm add ortools -v

## Actual behavior

```
Adding packages to default dependencies: ortools
======== Start resolving requirements ========
  ortools
  Adding requirement ortools
	Found matching candidates:
	  <Candidate ortools 9.0.9048 from https://pypi.org/simple/ortools/>
	  <Candidate ortools 8.2.8710 from https://pypi.org/simple/ortools/>
	  <Candidate ortools 8.1.8487 from https://pypi.org/simple/ortools/>
	  <Candidate ortools 8.0.8283 from https://pypi.org/simple/ortools/>
	  <Candidate ortools 7.8.7959 from https://pypi.org/simple/ortools/>
	  <Candidate ortools 7.7.7810 from https://pypi.org/simple/ortools/>
	  <Candidate ortools 7.6.7691 from https://pypi.org/simple/ortools/>
	  <Candidate ortools 7.5.7466 from https://pypi.org/simple/ortools/>
	  <Candidate ortools 7.4.7247 from https://pypi.org/simple/ortools/>
	  <Candidate ortools 7.3.7083 from https://pypi.org/simple/ortools/>
	  ... [268 more candidate(s)]
======== Starting round 0 ========
  Adding requirement protobuf>=3.15.8(from ortools 9.0.9048)
	Found matching candidates:
	  <Candidate protobuf 3.17.3 from https://pypi.org/simple/protobuf/>
	  <Candidate protobuf 3.17.2 from https://pypi.org/simple/protobuf/>
	  <Candidate protobuf 3.17.1 from https://pypi.org/simple/protobuf/>
	  <Candidate protobuf 3.17.0 from https://pypi.org/simple/protobuf/>
	  <Candidate protobuf 3.16.0 from https://pypi.org/simple/protobuf/>
	  <Candidate protobuf 3.15.8 from https://pypi.org/simple/protobuf/>
  Adding requirement absl-py>=0.11(from ortools 9.0.9048)
	Found matching candidates:
	  <Candidate absl-py 0.13.0 from https://pypi.org/simple/absl-py/>
	  <Candidate absl-py 0.12.0 from https://pypi.org/simple/absl-py/>
	  <Candidate absl-py 0.11.0 from https://pypi.org/simple/absl-py/>
Resolving: new pin ortools 9.0.9048
======== Ending round 0 ========
======== Starting round 1 ========
  Adding requirement six(from absl-py 0.13.0)
	Found matching candidates:
	  <Candidate six 1.16.0 from https://pypi.org/simple/six/>
	  <Candidate six 1.15.0 from https://pypi.org/simple/six/>
	  <Candidate six 1.14.0 from https://pypi.org/simple/six/>
	  <Candidate six 1.13.0 from https://pypi.org/simple/six/>
	  <Candidate six 1.12.0 from https://pypi.org/simple/six/>
	  <Candidate six 1.11.0 from https://pypi.org/simple/six/>
	  <Candidate six 1.10.0 from https://pypi.org/simple/six/>
	  <Candidate six 1.9.0 from https://pypi.org/simple/six/>
	  <Candidate six 1.8.0 from https://pypi.org/simple/six/>
	  <Candidate six 1.7.3 from https://pypi.org/simple/six/>
	  ... [35 more candidate(s)]
Resolving: new pin absl-py 0.13.0
======== Ending round 1 ========
======== Starting round 2 ========
Resolving: new pin six 1.16.0
======== Ending round 2 ========
======== Starting round 3 ========
  Adding requirement six>=1.9(from protobuf 3.17.3)
	Found matching candidates:
	  <Candidate six 1.16.0 from https://pypi.org/simple/six/>
	  <Candidate six 1.15.0 from https://pypi.org/simple/six/>
	  <Candidate six 1.14.0 from https://pypi.org/simple/six/>
	  <Candidate six 1.13.0 from https://pypi.org/simple/six/>
	  <Candidate six 1.12.0 from https://pypi.org/simple/six/>
	  <Candidate six 1.11.0 from https://pypi.org/simple/six/>
	  <Candidate six 1.10.0 from https://pypi.org/simple/six/>
	  <Candidate six 1.9.0 from https://pypi.org/simple/six/>
Resolving: new pin protobuf 3.17.3
======== Ending round 3 ========
======== Starting round 4 ========
======== Resolution Result ========
Stable pins:
   ortools 9.0.9048
   absl-py 0.13.0
       six 1.16.0
  protobuf 3.17.3
	Found matching candidates:
	  <Candidate ortools 9.0.9048 from https://pypi.org/simple/ortools/>
	Found matching candidates:
	  <Candidate absl-py 0.13.0 from https://pypi.org/simple/absl-py/>
	Found matching candidates:
	  <Candidate six 1.16.0 from https://pypi.org/simple/six/>
	Found matching candidates:
	  <Candidate protobuf 3.17.3 from https://pypi.org/simple/protobuf/>
🔒 Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
Synchronizing working set with lock file: 4 to add, 0 to update, 0 to remove

Install six 1.16.0 successful
Install absl-py 0.13.0 successful
Install protobuf 3.17.3 successful
Install ortools 9.0.9048 failed
Error occurs: 
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 190, in install_candidate
    self.manager.install(can)
  File "/root/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/installers/manager.py", line 31, in install
    installer(candidate.build(), self.environment, candidate.direct_url())
  File "/root/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/installers/installers.py", line 74, in install_wheel
    _install_wheel(
  File "/root/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/installers/installers.py", line 176, in _install_wheel
    for record_elements, stream in source.get_contents():
  File "/root/.local/share/pdm/venv/lib/python3.8/site-packages/installer/sources.py", line 165, in get_contents
    record = record_mapping.pop(item.filename)
KeyError: 'ortools/'
  Retry failed jobs
Install ortools 9.0.9048 failed
Error occurs: 
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 190, in install_candidate
    self.manager.install(can)
  File "/root/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/installers/manager.py", line 31, in install
    installer(candidate.build(), self.environment, candidate.direct_url())
  File "/root/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/installers/installers.py", line 74, in install_wheel
    _install_wheel(
  File "/root/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/installers/installers.py", line 176, in _install_wheel
    for record_elements, stream in source.get_contents():
  File "/root/.local/share/pdm/venv/lib/python3.8/site-packages/installer/sources.py", line 165, in get_contents
    record = record_mapping.pop(item.filename)
KeyError: 'ortools/'

ERRORS:
add ortools failed:
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 190, in install_candidate
    self.manager.install(can)
  File "/root/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/installers/manager.py", line 31, in install
    installer(candidate.build(), self.environment, candidate.direct_url())
  File "/root/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/installers/installers.py", line 74, in install_wheel
    _install_wheel(
  File "/root/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/installers/installers.py", line 176, in _install_wheel
    for record_elements, stream in source.get_contents():
  File "/root/.local/share/pdm/venv/lib/python3.8/site-packages/installer/sources.py", line 165, in get_contents
    record = record_mapping.pop(item.filename)
KeyError: 'ortools/'

Traceback (most recent call last):
  File "/root/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/root/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/core.py", line 198, in main
    return Core().main(args)
  File "/root/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/core.py", line 153, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/root/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/core.py", line 148, in main
    f(options.project, options)
  File "/root/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/cli/commands/add.py", line 62, in handle
    actions.do_add(
  File "/root/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/cli/actions.py", line 221, in do_add
    do_sync(
  File "/root/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/cli/actions.py", line 170, in do_sync
    handler.synchronize()
  File "/root/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 357, in synchronize
    raise InstallationError("Some package operations are not complete yet")
pdm.exceptions.InstallationError: Some package operations are not complete yet
```

## Expected behavior

ortools installs successfully

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.8.3                     
Python Interpreter: /opt/venv/bin/python (3.8)
Project Root:       /                         
Project Packages:   /__pypackages__/3.8       
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.10",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.8.0-63-generic",
  "platform_system": "Linux",
  "platform_version": "#71~20.04.1-Ubuntu SMP Thu Jul 15 17:46:08 UTC 2021",
  "python_full_version": "3.8.10",
  "platform_python_implementation": "CPython",
  "python_version": "3.8",
  "sys_platform": "linux"
}

```

**Comment by pawamoy** [comment]
See https://github.com/pradyunsg/installer/pull/70. The ortools package is probably broken.
