### ISSUE TITLE
ResolutionImpossible

### ISSUE THREAD

**Issue by DanLipsitt** [pdm-project/pdm#654]
Adding the `ward` package fails with the message `ResolutionImpossible`. It's not clear from the error message why it fails. Pip is able to install the package.

- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

```bash
pdm init -n
pdm add ward
```

## Actual behavior

```
resolvelib.resolvers.RequirementsConflicted: Requirements conflict: NamedRequirement(name='ward', marker=None, extras=(), specifier=<SpecifierSet('~=0.63')>, editable=False)
```

<details><summary>Full output with -v</summary>
<p>

```console
$ pdm init -n && pdm add ward -v
Creating a pyproject.toml for PDM...
Using Python interpreter: /Users/dlipsitt/Library/Application Support/pdm/venvs/pdm_tmp-s27rSO4g-3.9/bin/python (3.9)
Changes are written to pyproject.toml.
Adding packages to default dependencies: ward
======== Start resolving requirements ========
  ward
  Adding requirement ward
   Could not find any matching candidates.
   Found matching candidates:
     <Candidate ward 0.63.0b0 from https://pypi.org/simple/ward/>
     <Candidate ward 0.62.1b0 from https://pypi.org/simple/ward/>
     <Candidate ward 0.62.0b0 from https://pypi.org/simple/ward/>
     <Candidate ward 0.61.1b0 from https://pypi.org/simple/ward/>
     <Candidate ward 0.61.0b0 from https://pypi.org/simple/ward/>
     <Candidate ward 0.60.1b0 from https://pypi.org/simple/ward/>
     <Candidate ward 0.60.0b0 from https://pypi.org/simple/ward/>
     <Candidate ward 0.59.0b0 from https://pypi.org/simple/ward/>
     <Candidate ward 0.58.0b0 from https://pypi.org/simple/ward/>
     <Candidate ward 0.57.2b0 from https://pypi.org/simple/ward/>
     ... [162 more candidate(s)]
======== Starting round 0 ========
  Adding requirement click<9,>=7(from ward 0.63.0b0)
   Found matching candidates:
     <Candidate click 8.0.1 from https://pypi.org/simple/click/>
     <Candidate click 8.0.0 from https://pypi.org/simple/click/>
     <Candidate click 7.1.2 from https://pypi.org/simple/click/>
     <Candidate click 7.1.1 from https://pypi.org/simple/click/>
     <Candidate click 7.1 from https://pypi.org/simple/click/>
     <Candidate click 7.0 from https://pypi.org/simple/click/>
  Adding requirement click-completion<0.6.0,>=0.5.2(from ward 0.63.0b0)
   Found matching candidates:
     <Candidate click-completion 0.5.2 from https://pypi.org/simple/click-completion/>
  Adding requirement click-default-group<2.0.0,>=1.2.2(from ward 0.63.0b0)
   Found matching candidates:
     <Candidate click-default-group 1.2.2 from https://pypi.org/simple/click-default-group/>
  Adding requirement cucumber-tag-expressions<3.0.0,>=2.0.0(from ward 0.63.0b0)
   Found matching candidates:
     <Candidate cucumber-tag-expressions 2.0.4 from https://pypi.org/simple/cucumber-tag-expressions/>
     <Candidate cucumber-tag-expressions 2.0.3 from https://pypi.org/simple/cucumber-tag-expressions/>
  Adding requirement pluggy<0.14.0,>=0.13.1(from ward 0.63.0b0)
   Found matching candidates:
     <Candidate pluggy 0.13.1 from https://pypi.org/simple/pluggy/>
  Adding requirement pprintpp<0.5.0,>=0.4.0(from ward 0.63.0b0)
   Found matching candidates:
     <Candidate pprintpp 0.4.0 from https://pypi.org/simple/pprintpp/>
  Adding requirement rich<11.0.0,>=10.0.0(from ward 0.63.0b0)
   Found matching candidates:
     <Candidate rich 10.9.0 from https://pypi.org/simple/rich/>
     <Candidate rich 10.8.0 from https://pypi.org/simple/rich/>
     <Candidate rich 10.7.0 from https://pypi.org/simple/rich/>
     <Candidate rich 10.6.0 from https://pypi.org/simple/rich/>
     <Candidate rich 10.5.0 from https://pypi.org/simple/rich/>
     <Candidate rich 10.4.0 from https://pypi.org/simple/rich/>
     <Candidate rich 10.3.0 from https://pypi.org/simple/rich/>
     <Candidate rich 10.2.2 from https://pypi.org/simple/rich/>
     <Candidate rich 10.2.1 from https://pypi.org/simple/rich/>
     <Candidate rich 10.2.0 from https://pypi.org/simple/rich/>
     ... [16 more candidate(s)]
  Adding requirement tomli<2.0.0,>=1.0.0(from ward 0.63.0b0)
   Found matching candidates:
     <Candidate tomli 1.2.1 from https://pypi.org/simple/tomli/>
     <Candidate tomli 1.2.0 from https://pypi.org/simple/tomli/>
     <Candidate tomli 1.1.0 from https://pypi.org/simple/tomli/>
     <Candidate tomli 1.0.4 from https://pypi.org/simple/tomli/>
     <Candidate tomli 1.0.3 from https://pypi.org/simple/tomli/>
     <Candidate tomli 1.0.2 from https://pypi.org/simple/tomli/>
     <Candidate tomli 1.0.1 from https://pypi.org/simple/tomli/>
     <Candidate tomli 1.0.0 from https://pypi.org/simple/tomli/>
Resolving: new pin ward 0.63.0b0
======== Ending round 0 ========
======== Starting round 1 ========
  Adding requirement click(from click-completion 0.5.2)
   Found matching candidates:
     <Candidate click 8.0.1 from https://pypi.org/simple/click/>
     <Candidate click 8.0.0 from https://pypi.org/simple/click/>
     <Candidate click 7.1.2 from https://pypi.org/simple/click/>
     <Candidate click 7.1.1 from https://pypi.org/simple/click/>
     <Candidate click 7.1 from https://pypi.org/simple/click/>
     <Candidate click 7.0 from https://pypi.org/simple/click/>
  Adding requirement jinja2(from click-completion 0.5.2)
   Found matching candidates:
     <Candidate jinja2 3.0.1 from https://pypi.org/simple/jinja2/>
     <Candidate jinja2 3.0.0 from https://pypi.org/simple/jinja2/>
     <Candidate jinja2 2.11.3 from https://pypi.org/simple/jinja2/>
     <Candidate jinja2 2.11.2 from https://pypi.org/simple/jinja2/>
     <Candidate jinja2 2.11.1 from https://pypi.org/simple/jinja2/>
     <Candidate jinja2 2.11.0 from https://pypi.org/simple/jinja2/>
     <Candidate jinja2 2.10.3 from https://pypi.org/simple/jinja2/>
     <Candidate jinja2 2.10.2 from https://pypi.org/simple/jinja2/>
     <Candidate jinja2 2.10.1 from https://pypi.org/simple/jinja2/>
     <Candidate jinja2 2.10 from https://pypi.org/simple/jinja2/>
     ... [48 more candidate(s)]
  Adding requirement six(from click-completion 0.5.2)
   Found matching candidates:
     <Candidate six 1.16.0 from https://pypi.org/simple/six/>
     <Candidate six 1.15.0 from https://pypi.org/simple/six/>
     <Candidate six 1.14.0 from https://pypi.org/simple/six/>
     <Candidate six 1.13.0 from https://pypi.org/simple/six/>
     <Candidate six 1.12.0 from https://pypi.org/simple/six/>
     <Candidate six 1.11.0 from https://pypi.org/simple/six/>
     <Candidate six 1.10.0 from https://pypi.org/simple/six/>
     <Candidate six 1.9.0 from https://pypi.org/simple/six/>
     <Candidate six 1.8.0 from https://pypi.org/simple/six/>
     <Candidate six 1.7.3 from https://pypi.org/simple/six/>
     ... [35 more candidate(s)]
  Adding requirement shellingham(from click-completion 0.5.2)
   Found matching candidates:
     <Candidate shellingham 1.4.0 from https://pypi.org/simple/shellingham/>
     <Candidate shellingham 1.3.2 from https://pypi.org/simple/shellingham/>
     <Candidate shellingham 1.3.1 from https://pypi.org/simple/shellingham/>
     <Candidate shellingham 1.3.0 from https://pypi.org/simple/shellingham/>
     <Candidate shellingham 1.2.8 from https://pypi.org/simple/shellingham/>
     <Candidate shellingham 1.2.7 from https://pypi.org/simple/shellingham/>
     <Candidate shellingham 1.2.6 from https://pypi.org/simple/shellingham/>
     <Candidate shellingham 1.2.5 from https://pypi.org/simple/shellingham/>
     <Candidate shellingham 1.2.4 from https://pypi.org/simple/shellingham/>
     <Candidate shellingham 1.2.3 from https://pypi.org/simple/shellingham/>
     ... [20 more candidate(s)]
Resolving: new pin click-completion 0.5.2
======== Ending round 1 ========
======== Starting round 2 ========
  Adding requirement click(from click-default-group 1.2.2)
   Found matching candidates:
     <Candidate click 8.0.1 from https://pypi.org/simple/click/>
     <Candidate click 8.0.0 from https://pypi.org/simple/click/>
     <Candidate click 7.1.2 from https://pypi.org/simple/click/>
     <Candidate click 7.1.1 from https://pypi.org/simple/click/>
     <Candidate click 7.1 from https://pypi.org/simple/click/>
     <Candidate click 7.0 from https://pypi.org/simple/click/>
Resolving: new pin click-default-group 1.2.2
======== Ending round 2 ========
======== Starting round 3 ========
Resolving: new pin cucumber-tag-expressions 2.0.4
======== Ending round 3 ========
======== Starting round 4 ========
Resolving: new pin pluggy 0.13.1
======== Ending round 4 ========
======== Starting round 5 ========
Resolving: new pin pprintpp 0.4.0
======== Ending round 5 ========
======== Starting round 6 ========
  Adding requirement colorama; platform_system == "Windows"(from click 8.0.1)
   Found matching candidates:
     <Candidate colorama 0.4.4 from https://pypi.org/simple/colorama/>
     <Candidate colorama 0.4.3 from https://pypi.org/simple/colorama/>
     <Candidate colorama 0.4.2 from https://pypi.org/simple/colorama/>
     <Candidate colorama 0.4.1 from https://pypi.org/simple/colorama/>
     <Candidate colorama 0.4.0 from https://pypi.org/simple/colorama/>
     <Candidate colorama 0.3.9 from https://pypi.org/simple/colorama/>
     <Candidate colorama 0.3.8 from https://pypi.org/simple/colorama/>
     <Candidate colorama 0.3.7 from https://pypi.org/simple/colorama/>
     <Candidate colorama 0.3.6 from https://pypi.org/simple/colorama/>
     <Candidate colorama 0.3.5 from https://pypi.org/simple/colorama/>
     ... [74 more candidate(s)]
Resolving: new pin click 8.0.1
======== Ending round 6 ========
======== Starting round 7 ========
Resolving: new pin tomli 1.2.1
======== Ending round 7 ========
======== Starting round 8 ========
  Adding requirement colorama<0.5.0,>=0.4.0(from rich 10.9.0)
   Found matching candidates:
     <Candidate colorama 0.4.4 from https://pypi.org/simple/colorama/>
     <Candidate colorama 0.4.3 from https://pypi.org/simple/colorama/>
     <Candidate colorama 0.4.2 from https://pypi.org/simple/colorama/>
     <Candidate colorama 0.4.1 from https://pypi.org/simple/colorama/>
     <Candidate colorama 0.4.0 from https://pypi.org/simple/colorama/>
  Adding requirement commonmark<0.10.0,>=0.9.0(from rich 10.9.0)
   Found matching candidates:
     <Candidate commonmark 0.9.1 from https://pypi.org/simple/commonmark/>
     <Candidate commonmark 0.9.0 from https://pypi.org/simple/commonmark/>
  Adding requirement pygments<3.0.0,>=2.6.0(from rich 10.9.0)
   Found matching candidates:
     <Candidate pygments 2.10.0 from https://pypi.org/simple/pygments/>
     <Candidate pygments 2.9.0 from https://pypi.org/simple/pygments/>
     <Candidate pygments 2.8.1 from https://pypi.org/simple/pygments/>
     <Candidate pygments 2.8.0 from https://pypi.org/simple/pygments/>
     <Candidate pygments 2.7.4 from https://pypi.org/simple/pygments/>
     <Candidate pygments 2.7.3 from https://pypi.org/simple/pygments/>
     <Candidate pygments 2.7.2 from https://pypi.org/simple/pygments/>
     <Candidate pygments 2.7.1 from https://pypi.org/simple/pygments/>
     <Candidate pygments 2.7.0 from https://pypi.org/simple/pygments/>
     <Candidate pygments 2.6.1 from https://pypi.org/simple/pygments/>
     ... [12 more candidate(s)]
Resolving: new pin rich 10.9.0
======== Ending round 8 ========
======== Starting round 9 ========
Resolving: new pin commonmark 0.9.1
======== Ending round 9 ========
======== Starting round 10 ========
Resolving: new pin colorama 0.4.4
======== Ending round 10 ========
======== Starting round 11 ========
Resolving: new pin pygments 2.10.0
======== Ending round 11 ========
======== Starting round 12 ========
Resolving: new pin shellingham 1.4.0
======== Ending round 12 ========
======== Starting round 13 ========
Resolving: new pin six 1.16.0
======== Ending round 13 ========
======== Starting round 14 ========
  Adding requirement MarkupSafe>=2.0(from jinja2 3.0.1)
   Found matching candidates:
     <Candidate MarkupSafe 2.0.1 from https://pypi.org/simple/markupsafe/>
     <Candidate MarkupSafe 2.0.0 from https://pypi.org/simple/markupsafe/>
Resolving: new pin jinja2 3.0.1
======== Ending round 14 ========
======== Starting round 15 ========
Resolving: new pin MarkupSafe 2.0.1
======== Ending round 15 ========
======== Starting round 16 ========
======== Resolution Result ========
Stable pins:
                      ward 0.63.0b0
          click-completion 0.5.2
       click-default-group 1.2.2
  cucumber-tag-expressions 2.0.4
                    pluggy 0.13.1
                  pprintpp 0.4.0
                     click 8.0.1
                     tomli 1.2.1
                      rich 10.9.0
                commonmark 0.9.1
                  colorama 0.4.4
                  pygments 2.10.0
               shellingham 1.4.0
                       six 1.16.0
                    jinja2 3.0.1
                markupsafe 2.0.1
   Found matching candidates:
     <Candidate ward 0.63.0b0 from https://pypi.org/simple/ward/>
   Found matching candidates:
     <Candidate click-completion 0.5.2 from https://pypi.org/simple/click-completion/>
   Found matching candidates:
     <Candidate click-default-group 1.2.2 from https://pypi.org/simple/click-default-group/>
   Found matching candidates:
     <Candidate cucumber-tag-expressions 2.0.4 from https://pypi.org/simple/cucumber-tag-expressions/>
   Found matching candidates:
     <Candidate pluggy 0.13.1 from https://pypi.org/simple/pluggy/>
   Found matching candidates:
     <Candidate pprintpp 0.4.0 from https://pypi.org/simple/pprintpp/>
   Found matching candidates:
     <Candidate click 8.0.1 from https://pypi.org/simple/click/>
   Found matching candidates:
     <Candidate tomli 1.2.1 from https://pypi.org/simple/tomli/>
   Found matching candidates:
     <Candidate rich 10.9.0 from https://pypi.org/simple/rich/>
   Found matching candidates:
     <Candidate commonmark 0.9.1 from https://pypi.org/simple/commonmark/>
   Found matching candidates:
     <Candidate colorama 0.4.4 from https://pypi.org/simple/colorama/>
   Found matching candidates:
     <Candidate pygments 2.10.0 from https://pypi.org/simple/pygments/>
   Found matching candidates:
     <Candidate shellingham 1.4.0 from https://pypi.org/simple/shellingham/>
   Found matching candidates:
     <Candidate six 1.16.0 from https://pypi.org/simple/six/>
   Found matching candidates:
     <Candidate jinja2 3.0.1 from https://pypi.org/simple/jinja2/>
   Found matching candidates:
     <Candidate MarkupSafe 2.0.1 from https://pypi.org/simple/markupsafe/>
🔒 Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
Traceback (most recent call last):
  File "/Users/dlipsitt/.local/pipx/venvs/pdm/lib/python3.9/site-packages/resolvelib/resolvers.py", line 341, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/Users/dlipsitt/.local/pipx/venvs/pdm/lib/python3.9/site-packages/resolvelib/resolvers.py", line 173, in _add_to_criteria
    raise RequirementsConflicted(criterion)
resolvelib.resolvers.RequirementsConflicted: Requirements conflict: NamedRequirement(name='ward', marker=None, extras=(), specifier=<SpecifierSet('~=0.63')>, editable=False)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dlipsitt/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/Users/dlipsitt/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/core.py", line 198, in main
    return Core().main(args)
  File "/Users/dlipsitt/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/core.py", line 153, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/Users/dlipsitt/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/core.py", line 148, in main
    f(options.project, options)
  File "/Users/dlipsitt/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/cli/commands/add.py", line 62, in handle
    actions.do_add(
  File "/Users/dlipsitt/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/cli/actions.py", line 221, in do_add
    do_sync(
  File "/Users/dlipsitt/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/cli/actions.py", line 154, in do_sync
    candidates = resolve_candidates_from_lockfile(project, requirements)
  File "/Users/dlipsitt/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/cli/actions.py", line 112, in resolve_candidates_from_lockfile
    mapping, *_ = resolve(
  File "/Users/dlipsitt/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/resolver/core.py", line 30, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "/Users/dlipsitt/.local/pipx/venvs/pdm/lib/python3.9/site-packages/resolvelib/resolvers.py", line 472, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/Users/dlipsitt/.local/pipx/venvs/pdm/lib/python3.9/site-packages/resolvelib/resolvers.py", line 343, in resolve
    raise ResolutionImpossible(e.criterion.information)
resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=NamedRequirement(name='ward', marker=None, extras=(), specifier=<SpecifierSet('~=0.63')>, editable=False), parent=None)]
```

</p>
</details>

## Expected behavior

If there is actually a conflict, it would help if two conflicting requirements were listed. Or can a single requirement conflict by itself? 🤔

The following commands succeed (in an empty dir):

```bash
mkdir __pypackages__
pip install -t __pypackages__ ward
PYTHONPATH=__pypackages__ __pypackages__/bin/ward
```

`pdm run pip install ward` also works in an existing project.

## Environment Information

```
PDM version:        1.8.3
Python Interpreter: /Users/dlipsitt/Library/Application Support/pdm/venvs/pdm_tmp-s27rSO4g-3.9/bin/python (3.9)
Project Root:       /private/tmp/pdm_tmp
Project Packages:   None
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.6",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "20.3.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101",
  "python_full_version": "3.9.6",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
Update the version range in `pyproject.toml` to `ward>=0.63.0b0` and do `pdm install`. This is a workaround and the fix is done in main branch.
