### ISSUE TITLE
tox.exception.InterpreterNotFound: InterpreterNotFound

### ISSUE THREAD

**Issue by laike9m** [pdm-project/pdm#655]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

```
$ pdm run tox -v                                                                                                                            
using tox.ini: /Users/laike9m/Dev/Python/Cyberbrain/tox.ini (pid 29243)
using tox-3.24.3 from /Users/laike9m/Dev/Python/Cyberbrain/__pypackages__/3.9/lib/tox/__init__.py (pid 29243)
'exit code 127' cmd '/Users/laike9m/.pyenv/shims/python3.7' out '' err "pyenv: python3.7: command not found\n\nThe `python3.7' command exists in these Python versions:\n  3.7.12\n  3.7.7\n\nNote: See 'pyenv help global' for tips on allowing both\n      python2 and python3 to be found.\n"
Traceback (most recent call last):
  File "/Users/laike9m/Dev/Python/Cyberbrain/__pypackages__/3.9/bin/tox", line 8, in <module>
    sys.exit(cmdline())
  File "/Users/laike9m/Dev/Python/Cyberbrain/__pypackages__/3.9/lib/tox/session/__init__.py", line 44, in cmdline
    main(args)
  File "/Users/laike9m/Dev/Python/Cyberbrain/__pypackages__/3.9/lib/tox/session/__init__.py", line 69, in main
    exit_code = session.runcommand()
  File "/Users/laike9m/Dev/Python/Cyberbrain/__pypackages__/3.9/lib/tox/session/__init__.py", line 197, in runcommand
    return self.subcommand_test()
  File "/Users/laike9m/Dev/Python/Cyberbrain/__pypackages__/3.9/lib/tox/session/__init__.py", line 213, in subcommand_test
    venv.package = self.hook.tox_package(session=self, venv=venv)
  File "/Users/laike9m/Dev/Python/Cyberbrain/__pypackages__/3.9/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/Users/laike9m/Dev/Python/Cyberbrain/__pypackages__/3.9/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/Users/laike9m/Dev/Python/Cyberbrain/__pypackages__/3.9/lib/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/Users/laike9m/Dev/Python/Cyberbrain/__pypackages__/3.9/lib/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/laike9m/Dev/Python/Cyberbrain/__pypackages__/3.9/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/Users/laike9m/Dev/Python/Cyberbrain/__pypackages__/3.9/lib/tox_pdm/plugin3.py", line 86, in tox_package
    session.package, session.dist = get_package(session, venv)
  File "/Users/laike9m/Dev/Python/Cyberbrain/__pypackages__/3.9/lib/tox_pdm/plugin3.py", line 57, in get_package
    package = acquire_package(config, venv)
  File "/Users/laike9m/Dev/Python/Cyberbrain/__pypackages__/3.9/lib/tox_pdm/plugin3.py", line 73, in acquire_package
    tox_testenv_create(venv, action)
  File "/Users/laike9m/Dev/Python/Cyberbrain/__pypackages__/3.9/lib/tox_pdm/plugin3.py", line 35, in tox_testenv_create
    config_interpreter = venv.getsupportedinterpreter()
  File "/Users/laike9m/Dev/Python/Cyberbrain/__pypackages__/3.9/lib/tox/venv.py", line 311, in getsupportedinterpreter
    return self.envconfig.getsupportedinterpreter()
  File "/Users/laike9m/Dev/Python/Cyberbrain/__pypackages__/3.9/lib/tox/config/__init__.py", line 1110, in getsupportedinterpreter
    raise tox.exception.InterpreterNotFound(self.basepython)
tox.exception.InterpreterNotFound: InterpreterNotFound: python3.7
```

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.8.3
Python Interpreter: /Users/laike9m/.pyenv/versions/3.9.7/bin/python (3.9)
Project Root:       /Users/laike9m/Dev/Python/Cyberbrain
Project Packages:   /Users/laike9m/Dev/Python/Cyberbrain/__pypackages__/3.9
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.7",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "19.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 19.6.0: Tue Jun 22 19:49:55 PDT 2021; root:xnu-6153.141.35~1/RELEASE_X86_64",
  "python_full_version": "3.9.7",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "darwin"
}
```

**Comment by laike9m** [comment]
Tried putting `python3.7` in `envlist` (instead of `py37`), tox is able to run, but somehow was using 3.9 as 3.7:

```
$ pdm run tox -v                                                                                                                            
using tox.ini: /Users/laike9m/Dev/Python/Cyberbrain/tox.ini (pid 30659)
using tox-3.24.3 from /Users/laike9m/Dev/Python/Cyberbrain/__pypackages__/3.9/lib/tox/__init__.py (pid 30659)
[30707] /Users/laike9m/Dev/Python/Cyberbrain/.tox/python3.7$ /Users/laike9m/.local/bin/pdm use -f /Users/laike9m/.pyenv/versions/3.9.7/bin/python >log/python3.7-0.log
[30711] /Users/laike9m/Dev/Python/Cyberbrain$ /Users/laike9m/.local/bin/pdm build --no-wheel -d .tox/.package >.tox/python3.7/log/python3.7-1.log
python3.7 buildpkg: /Users/laike9m/Dev/Python/Cyberbrain/.tox/.package/cyberbrain-0.2.0.tar.gz
package .tmp/package/1/cyberbrain-0.2.0.tar.gz links to .package/cyberbrain-0.2.0.tar.gz (/Users/laike9m/Dev/Python/Cyberbrain/.tox)
python3.7 cannot reuse: no previous config /Users/laike9m/Dev/Python/Cyberbrain/.tox/python3.7/.tox-config1
python3.7 create: /Users/laike9m/Dev/Python/Cyberbrain/.tox/python3.7
[30821] /Users/laike9m/Dev/Python/Cyberbrain/.tox/python3.7$ /Users/laike9m/.local/bin/pdm use -f /Users/laike9m/.pyenv/versions/3.9.7/bin/python >log/python3.7-2.log
python3.7 pdminstall: ['; Dependency groups in pyproject.toml', 'test', 'extra_tests']
[30825] /Users/laike9m/Dev/Python/Cyberbrain$ /Users/laike9m/.local/bin/pdm install -p .tox/python3.7 --group '; Dependency groups in pyproject.toml' --group test --group extra_tests --no-self >.tox/python3.7/log/python3.7-3.log
python3.7 inst: /Users/laike9m/Dev/Python/Cyberbrain/.tox/.tmp/package/1/cyberbrain-0.2.0.tar.gz
write config to /Users/laike9m/Dev/Python/Cyberbrain/.tox/python3.7/.tox-config1 as '40695e075f17e2ca79ca88bec1e3287297249d1adbebeb7742b40ba0377a1553 /Users/laike9m/.pyenv/versions/3.9.7/bin/python\n3.24.3 0 0 0'
[30852] /Users/laike9m/Dev/Python/Cyberbrain$ /Users/laike9m/.pyenv/versions/3.9.7/bin/python -m pip install --exists-action w .tox/.tmp/package/1/cyberbrain-0.2.0.tar.gz -t .tox/python3.7/__pypackages__/3.9/lib >.tox/python3.7/log/python3.7-4.log
[30869] /Users/laike9m/Dev/Python/Cyberbrain$ /Users/laike9m/.pyenv/versions/3.9.7/bin/python -m pip freeze --path .tox/python3.7/__pypackages__/3.9/lib >.tox/python3.7/log/python3.7-5.log
python3.7 installed: attrs==20.3.0,backports.entry-points-selectable==1.1.0,certifi==2021.5.30,charset-normalizer==2.0.4,cheap-repr==0.5.0,colorama==0.4.4,crayons==0.4.0,cyberbrain @ file:///Users/laike9m/Dev/Python/Cyberbrain/.tox/.tmp/package/1/cyberbrain-0.2.0.tar.gz,detect==2020.12.3,distlib==0.3.2,execnet==1.9.0,filelock==3.0.12,get-port==0.0.5,idna==3.2,iniconfig==1.1.1,jsonpickle==1.5.2,more-itertools==8.9.0,msgpack==1.0.2,numpy==1.18.0,packaging==21.0,pandas==1.1.3,platformdirs==2.3.0,pluggy==1.0.0,portpicker==1.4.0,py==1.10.0,Pygments==2.10.0,PyHamcrest==2.0.2,pyparsing==2.4.7,pytest==6.2.5,pytest-forked==1.3.0,pytest-xdist==1.34.0,python-dateutil==2.8.2,pytz==2021.1,requests==2.26.0,responses==0.14.0,shortuuid==1.0.1,six==1.16.0,toml==0.10.2,tox==3.24.3,tox-pdm==0.3.0,tox-pyenv==1.1.0,typing-extensions==3.10.0.2,ujson==4.1.0,urllib3==1.26.6,virtualenv==20.7.2
python3.7 run-test-pre: PYTHONHASHSEED='247012615'
python3.7 run-test: commands[0] | pdm run -p /Users/laike9m/Dev/Python/Cyberbrain/.tox/python3.7 pytest -s -vv /Users/laike9m/Dev/Python/Cyberbrain/test/ --assert=plain
[30885] /Users/laike9m/Dev/Python/Cyberbrain$ /Users/laike9m/.local/bin/pdm run -p .tox/python3.7 pytest -s -vv test --assert=plain
================================================================== test session starts ==================================================================
platform darwin -- Python 3.9.7, pytest-6.2.5, py-1.10.0, pluggy-1.0.0 -- /Users/laike9m/.pyenv/versions/3.9.7/bin/python3.9
cachedir: .tox/python3.7/.pytest_cache
rootdir: /Users/laike9m/Dev/Python/Cyberbrain, configfile: pyproject.toml, testpaths: test
plugins: xdist-1.34.0, forked-1.3.0
collected 64 items

test/test_api_decorator.py::test_decorator_api PASSED
test/test_api_disabled.py::test_disabled_tracer PASSED
test/test_api_disabled.py::test_decorator_with_argument PASSED
test/test_api_state.py::test_call_tracer_multiple_times Can't connect to RPC server
PASSED
test/test_api_state.py::test_decorator_multiple_times PASSED
test/test_api_tracer.py::test_api_tracer PASSED
test/test_assertion.py::test_assertion Can't connect to RPC server
```

**Comment by laike9m** [comment]
Resolved. I need to have a `.python-version` file locally so that pyenv/tox knows which Python to look at. I have python 3.7.7 and a 3.7.12 installed at the same time. So basically, `.python-version` looks like:

```
3.9.7
3.7.12
3.8.12
```
