### ISSUE TITLE
AssertionError with pdm use

### ISSUE THREAD

**Issue by pawamoy** [pdm-project/pdm#656]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

```console
% pdm use -f python3.9 -v
Using Python interpreter: /usr/bin/python3.9 (3.9)
Updating executable scripts...
Traceback (most recent call last):
  File "/home/pawamoy/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/core.py", line 198, in main
    return Core().main(args)
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/core.py", line 153, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/core.py", line 148, in main
    f(options.project, options)
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/cli/commands/use.py", line 23, in handle
    actions.do_use(project, options.python, options.first)
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/cli/actions.py", line 522, in do_use
    project.environment.update_shebangs(selected_python.executable)
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/models/environment.py", line 165, in update_shebangs
    child.write_bytes(_replace_shebang(child.read_bytes(), new_shebang))
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/models/environment.py", line 60, in _replace_shebang
    assert match is not None
AssertionError

% pdm use -f python3.8 -v
Using Python interpreter: /usr/bin/python3.8 (3.8)
Updating executable scripts...
Traceback (most recent call last):
  File "/home/pawamoy/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/core.py", line 198, in main
    return Core().main(args)
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/core.py", line 153, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/core.py", line 148, in main
    f(options.project, options)
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/cli/commands/use.py", line 23, in handle
    actions.do_use(project, options.python, options.first)
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/cli/actions.py", line 522, in do_use
    project.environment.update_shebangs(selected_python.executable)
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/models/environment.py", line 165, in update_shebangs
    child.write_bytes(_replace_shebang(child.read_bytes(), new_shebang))
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/models/environment.py", line 60, in _replace_shebang
    assert match is not None
AssertionError
```

If I run the command with the same version two times in a row, it works the second time:

```console
% pdm use -f python3.8 -v
Using Python interpreter: /usr/bin/python3.8 (3.8)
```

Also note that the selected version is correctly written in `.pdm.toml`, even when it fails the first time:

```console
% pdm use -f python3.9 -v
Using Python interpreter: /usr/bin/python3.9 (3.9)
Updating executable scripts...
Traceback (most recent call last):
  File "/home/pawamoy/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/core.py", line 198, in main
    return Core().main(args)
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/core.py", line 153, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/core.py", line 148, in main
    f(options.project, options)
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/cli/commands/use.py", line 23, in handle
    actions.do_use(project, options.python, options.first)
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/cli/actions.py", line 522, in do_use
    project.environment.update_shebangs(selected_python.executable)
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/models/environment.py", line 165, in update_shebangs
    child.write_bytes(_replace_shebang(child.read_bytes(), new_shebang))
  File "/home/pawamoy/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/models/environment.py", line 60, in _replace_shebang
    assert match is not None
AssertionError

% cat .pdm.toml          
[python]
path = "/usr/bin/python3.9"
```

## Environment Information

```bash
PDM version:        1.8.4                                    
Python Interpreter: /usr/bin/python3.9 (3.9)                 
Project Root:       /media/data/dev/griffe                   
Project Packages:   /media/data/dev/griffe/__pypackages__/3.9
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.7",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.14.3-arch1-1",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT Sun, 12 Sep 2021 20:51:34 +0000",
  "python_full_version": "3.9.7",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

**Comment by pawamoy** [comment]
Thanks for the instant fix :100: !

**Comment by pawamoy** [comment]
Hey @frostming, I'm experiencing this issue again in 1.10.1 :confused:

**Comment by pawamoy** [comment]
OK I found the cause: I had `wsdump.py` scripts in my bin folders which didn't start with a shebang, breaking PDM.

```console
% cat wsdump.py 
"""

"""

"""
websocket - WebSocket client library for Python

Copyright (C) 2010 Hiroki Ohtani(liris)
...
"""

import argparse
...
```

I've removed those, upgraded the related dependency, and these scripts are not added anymore, restoring a normal behavior.

**Comment by pawamoy** [comment]
Indeed the script was fixed: https://github.com/websocket-client/websocket-client/blob/master/bin/wsdump.py
