### ISSUE TITLE
`requires-python` affects resolution when it should not

### ISSUE THREAD

**Issue by gregdan3** [pdm-project/pdm#657]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

1. `pdm init` in an empty directory.
2. Choose the default for all prompts, except specify `*` for the Python version required, or provide any specific Python version (such as `==3.7`, `==3.9`)
3. Attempt to `pdm add rsa`

## Actual behavior

`pdm` will fail to resolve the `rsa` dependency while any specific major version is specified for `requires-python`, as well as when any `""` is specified. It is possible to install `rsa` when `requires-python = ">=3.5"` or any greater Python version, but you must specify `>=`. `==` and no specification (any, in the prompt) do not work.

```
~/pdm-test ❯ pdm init
Creating a pyproject.toml for PDM...
Please enter the Python interpreter to use
0. /usr/bin/python (3.9)
1. /usr/bin/python3 (3.9)
2. /usr/bin/python3.9 (3.9)
3. /home/gregdan3/.local/pipx/venvs/pdm/bin/python (3.9)
Please select: [0]: 
Using Python interpreter: /usr/bin/python (3.9)
Is the project a library that will be uploaded to PyPI? [y/N]: 
License(SPDX name) [MIT]: 
Author name [Gregory Danielson]: 
Author email [gregory.danielson3@gmail.com]: 
Python requires('*' to allow any) [>=3.9]: *
Changes are written to pyproject.toml.
~/pdm-test via 🐍 v3.9.7 took 4s ❯ pdm add rsa -vv
Adding packages to default dependencies: rsa
======== Start resolving requirements ========
  rsa
  Adding requirement rsa
	Found matching candidates:
	 <Candidate rsa 4.7.1 from https://pypi.org/simple/rsa/>
	 <Candidate rsa 4.4 from https://pypi.org/simple/rsa/>
	 <Candidate rsa 4.2 from https://pypi.org/simple/rsa/>
	 <Candidate rsa 4.1.1 from https://pypi.org/simple/rsa/>
	 <Candidate rsa 4.0 from https://pypi.org/simple/rsa/>
	 <Candidate rsa 3.4.2 from https://pypi.org/simple/rsa/>
	 <Candidate rsa 3.4.1 from https://pypi.org/simple/rsa/>
	 <Candidate rsa 3.4 from https://pypi.org/simple/rsa/>
	 <Candidate rsa 3.3 from https://pypi.org/simple/rsa/>
	 <Candidate rsa 3.2.3 from https://pypi.org/simple/rsa/>
	 ... [24 more candidate(s)]
======== Starting round 0 ========
  Adding requirement pyasn1>=0.1.3(from rsa 4.7.1)
	Found matching candidates:
	 <Candidate pyasn1 0.4.8 from https://pypi.org/simple/pyasn1/>
	 <Candidate pyasn1 0.4.7 from https://pypi.org/simple/pyasn1/>
	 <Candidate pyasn1 0.4.6 from https://pypi.org/simple/pyasn1/>
	 <Candidate pyasn1 0.4.5 from https://pypi.org/simple/pyasn1/>
	 <Candidate pyasn1 0.4.4 from https://pypi.org/simple/pyasn1/>
	 <Candidate pyasn1 0.4.3 from https://pypi.org/simple/pyasn1/>
	 <Candidate pyasn1 0.4.2 from https://pypi.org/simple/pyasn1/>
	 <Candidate pyasn1 0.4.1 from https://pypi.org/simple/pyasn1/>
	 <Candidate pyasn1 0.3.7 from https://pypi.org/simple/pyasn1/>
	 <Candidate pyasn1 0.3.6 from https://pypi.org/simple/pyasn1/>
	 ... [34 more candidate(s)]
Resolving: new pin rsa 4.7.1
======== Ending round 0 ========
======== Starting round 1 ========
Resolving: new pin pyasn1 0.4.8
======== Ending round 1 ========
======== Starting round 2 ========
======== Resolution Result ========
Stable pins:
     rsa 4.7.1
  pyasn1 0.4.8
	Found matching candidates:
	 <Candidate rsa 4.7.1 from https://pypi.org/simple/rsa/>
	Found matching candidates:
	 <Candidate pyasn1 0.4.8 from https://pypi.org/simple/pyasn1/>
🔒 Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
Traceback (most recent call last):
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/resolvelib/resolvers.py", line 341, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/resolvelib/resolvers.py", line 173, in _add_to_criteria
    raise RequirementsConflicted(criterion)
resolvelib.resolvers.RequirementsConflicted: Requirements conflict: NamedRequirement(name='rsa', marker=None, extras=(), specifier=<SpecifierSet('~=4.7')>, editable=False)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gregdan3/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/core.py", line 198, in main
    return Core().main(args)
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/core.py", line 153, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/core.py", line 148, in main
    f(options.project, options)
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/cli/commands/add.py", line 62, in handle
    actions.do_add(
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/cli/actions.py", line 220, in do_add
    do_sync(
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/cli/actions.py", line 154, in do_sync
    candidates = resolve_candidates_from_lockfile(project, requirements)
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/cli/actions.py", line 112, in resolve_candidates_from_lockfile
    mapping, *_ = resolve(
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/resolver/core.py", line 30, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/resolvelib/resolvers.py", line 472, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/resolvelib/resolvers.py", line 343, in resolve
    raise ResolutionImpossible(e.criterion.information)
resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=NamedRequirement(name='rsa', marker=None, extras=(), specifier=<SpecifierSet('~=4.7')>, editable=False), parent=None)]
```

## Expected behavior

When `requires-python = ""` is specified in `pyproject.toml`, the `rsa` dependency should be resolvable, as this would match valid Python versions for `rsa` to be installable (in the repo, >=3.6 is specified).

More generally, the specified version of `requires-python` should not affect resolution so long as it matches a valid major version that the dependency needs.

## Environment Information

```bash
PDM version:        1.8.5                                     
Python Interpreter: /usr/bin/python (3.9)                     
Project Root:       /home/gregdan3/pdm-test                   
Project Packages:   /home/gregdan3/pdm-test/__pypackages__/3.9
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.7",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.13.13-arch1-1",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT Thu, 26 Aug 2021 19:14:36 +0000",
  "python_full_version": "3.9.7",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}

```

**Comment by frostming** [comment]
It is not fully resolved, reopen it now
