### ISSUE TITLE
PDM Fails if Micropython is Installed

### ISSUE THREAD

**Issue by danieldjewell** [pdm-project/pdm#659]
- [x] I have searched the issue tracker and believe that this is not a duplicate.
## Steps to reproduce
1. Install `micropython` (available on Debian with that package name)
2. Run PDM

## Actual behavior

```
/usr/local/lib/python3.9/dist-packages/requests/__init__.py:87: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (5.0.0dev0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/usr/local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/pdm/core.py", line 198, in main
    return Core().main(args)
  File "/usr/local/lib/python3.9/dist-packages/pdm/core.py", line 153, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/usr/local/lib/python3.9/dist-packages/pdm/core.py", line 148, in main
    f(options.project, options)
  File "/usr/local/lib/python3.9/dist-packages/pdm/cli/commands/init.py", line 45, in handle
    actions.do_use(project)
  File "/usr/local/lib/python3.9/dist-packages/pdm/cli/actions.py", line 488, in do_use
    dict.fromkeys(filter(version_matcher, project.find_interpreters(python)))
  File "/usr/local/lib/python3.9/dist-packages/pdm/project/core.py", line 593, in find_interpreters
    yield PythonInfo.from_python_version(entry.py_version)
  File "/usr/local/lib/python3.9/dist-packages/pdm/models/python.py", line 33, in from_python_version
    return cls(path=py_version.executable, version=py_version.version)
  File "<string>", line 5, in __init__
  File "/usr/local/lib/python3.9/dist-packages/pdm/models/python.py", line 28, in __post_init__
    executable = get_underlying_executable(self.path)
  File "/usr/local/lib/python3.9/dist-packages/pdm/models/in_process/__init__.py", line 79, in get_underlying_executable
    subprocess.check_output(
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/micropython', '-Esc', 'import sys;print(sys.executable)']' returned non-zero exit status 1.
```

## Expected behavior

Ignoring Micropython

## Environment Information

See [Debian/sid -- Micropython](https://packages.debian.org/en/sid/micropython)

**Comment by danieldjewell** [comment]
Running a `chmod -x /usr/bin/micropython` is a working workaround

**Comment by frostming** [comment]
Why wasn't it executable anyway?
