### ISSUE TITLE
Could not install sqlalchemy

### ISSUE THREAD

**Issue by UlisesAlexanderAM** [pdm-project/pdm#664]
- [x]  I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

pdm add sqlalchemy

## Actual behavior
```bash
Adding packages to default dependencies: sqlalchemy
======== Start resolving requirements ========
  sqlalchemy
  Adding requirement sqlalchemy
	Found matching candidates:
	  <Candidate sqlalchemy 1.4.25 from https://pypi.org/simple/sqlalchemy/>
	  <Candidate sqlalchemy 1.4.24 from https://pypi.org/simple/sqlalchemy/>
	  <Candidate sqlalchemy 1.4.23 from https://pypi.org/simple/sqlalchemy/>
	  <Candidate sqlalchemy 1.4.22 from https://pypi.org/simple/sqlalchemy/>
	  <Candidate sqlalchemy 1.4.21 from https://pypi.org/simple/sqlalchemy/>
	  <Candidate sqlalchemy 1.4.20 from https://pypi.org/simple/sqlalchemy/>
	  <Candidate sqlalchemy 1.4.19 from https://pypi.org/simple/sqlalchemy/>
	  <Candidate sqlalchemy 1.4.18 from https://pypi.org/simple/sqlalchemy/>
	  <Candidate sqlalchemy 1.4.17 from https://pypi.org/simple/sqlalchemy/>
	  <Candidate sqlalchemy 1.4.16 from https://pypi.org/simple/sqlalchemy/>
	  ... [1282 more candidate(s)]
======== Starting round 0 ========
  Adding requirement greenlet!=0.4.17; python_version >= "3" and (platform_machine == "aarch64" or (platform_machine == "ppc64le" or (platform_machine == "x86_64" or (platform_machine == "amd64" or (platform_machine == "AMD64" or (platform_machine == "win32" or platform_machine == "WIN32"))))))(from sqlalchemy 1.4.25)
	Found matching candidates:
	  <Candidate greenlet 1.1.1 from https://pypi.org/simple/greenlet/>
	  <Candidate greenlet 1.1.0 from https://pypi.org/simple/greenlet/>
	  <Candidate greenlet 1.0.0 from https://pypi.org/simple/greenlet/>
	  <Candidate greenlet 0.4.16 from https://pypi.org/simple/greenlet/>
	  <Candidate greenlet 0.4.15 from https://pypi.org/simple/greenlet/>
	  <Candidate greenlet 0.4.14 from https://pypi.org/simple/greenlet/>
	  <Candidate greenlet 0.4.13 from https://pypi.org/simple/greenlet/>
	  <Candidate greenlet 0.4.12 from https://pypi.org/simple/greenlet/>
	  <Candidate greenlet 0.4.11 from https://pypi.org/simple/greenlet/>
	  <Candidate greenlet 0.4.10 from https://pypi.org/simple/greenlet/>
	  ... [341 more candidate(s)]
Resolving: new pin sqlalchemy 1.4.25
======== Ending round 0 ========
======== Starting round 1 ========
Resolving: new pin greenlet 1.1.1
======== Ending round 1 ========
======== Starting round 2 ========
======== Resolution Result ========
Stable pins:
  sqlalchemy 1.4.25
    greenlet 1.1.1
	Found matching candidates:
	  <Candidate sqlalchemy 1.4.25 from https://pypi.org/simple/sqlalchemy/>
	Found matching candidates:
	  <Candidate greenlet 1.1.1 from https://pypi.org/simple/greenlet/>
🔒 Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
Synchronizing working set with lock file: 2 to add, 0 to update, 0 to remove

Install greenlet 1.1.1 successful
Install sqlalchemy 1.4.25 failed
Error occurs:
Traceback (most recent call last):
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ulisesaam/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 190, in install_candidate
    self.manager.install(can)
  File "/home/ulisesaam/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/manager.py", line 38, in install
    installer(candidate.build(), self.environment, candidate.direct_url())
  File "/home/ulisesaam/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/installers.py", line 124, in install_wheel_with_cache
    dist_info_dir = _install_wheel(
  File "/home/ulisesaam/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/installers.py", line 176, in _install_wheel
    for record_elements, stream in source.get_contents():
  File "/home/ulisesaam/.local/share/pdm/venv/lib/python3.9/site-packages/installer/sources.py", line 165, in get_contents
    record = record_mapping.pop(item.filename)
KeyError: 'sqlalchemy/'
  Retry failed jobs
Install sqlalchemy 1.4.25 failed
Error occurs:
Traceback (most recent call last):
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ulisesaam/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 190, in install_candidate
    self.manager.install(can)
  File "/home/ulisesaam/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/manager.py", line 38, in install
    installer(candidate.build(), self.environment, candidate.direct_url())
  File "/home/ulisesaam/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/installers.py", line 124, in install_wheel_with_cache
    dist_info_dir = _install_wheel(
  File "/home/ulisesaam/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/installers.py", line 176, in _install_wheel
    for record_elements, stream in source.get_contents():
  File "/home/ulisesaam/.local/share/pdm/venv/lib/python3.9/site-packages/installer/sources.py", line 165, in get_contents
    record = record_mapping.pop(item.filename)
KeyError: 'sqlalchemy/'

ERRORS:
add sqlalchemy failed:
Traceback (most recent call last):
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ulisesaam/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 190, in install_candidate
    self.manager.install(can)
  File "/home/ulisesaam/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/manager.py", line 38, in install
    installer(candidate.build(), self.environment, candidate.direct_url())
  File "/home/ulisesaam/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/installers.py", line 124, in install_wheel_with_cache
    dist_info_dir = _install_wheel(
  File "/home/ulisesaam/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/installers.py", line 176, in _install_wheel
    for record_elements, stream in source.get_contents():
  File "/home/ulisesaam/.local/share/pdm/venv/lib/python3.9/site-packages/installer/sources.py", line 165, in get_contents
    record = record_mapping.pop(item.filename)
KeyError: 'sqlalchemy/'

Traceback (most recent call last):
  File "/home/ulisesaam/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/ulisesaam/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/core.py", line 198, in main
    return Core().main(args)
  File "/home/ulisesaam/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/core.py", line 153, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/home/ulisesaam/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/core.py", line 148, in main
    f(options.project, options)
  File "/home/ulisesaam/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/cli/commands/add.py", line 62, in handle
    actions.do_add(
  File "/home/ulisesaam/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/cli/actions.py", line 220, in do_add
    do_sync(
  File "/home/ulisesaam/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/cli/actions.py", line 169, in do_sync
    handler.synchronize()
  File "/home/ulisesaam/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 357, in synchronize
    raise InstallationError("Some package operations are not complete yet")
pdm.exceptions.InstallationError: Some package operations are not complete yet
```

## Expected behavior

sqlalchemy installs successfully

## Environment Information

```bash
PDM version:        1.8.5
Python Interpreter: /usr/bin/python3 (3.9)
Project Root:       /tmp/test
Project Packages:   /tmp/test/__pypackages__/3.9
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.7",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.14.8-arch1-1",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT Sun, 26 Sep 2021 19:36:15 +0000",
  "python_full_version": "3.9.7",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

**Comment by UlisesAlexanderAM** [comment]
Thanks for the info.

**Comment by jonathanpascoe** [comment]
When is the next version of the `installer` expected to be released?

**Comment by pawamoy** [comment]
For the reference, here's the PR fixing these errors: https://github.com/pradyunsg/installer/pull/72 (it's merged).
Now there are big PRs still open, such as https://github.com/pradyunsg/installer/pull/74, so I fear this could take some time before the next release. Best to ask @pradyunsg directly I guess!

**Comment by pawamoy** [comment]
Also, in the meantime, you can probably inject the latest `installer` into your PDM environment, something like:

```bash
. ~/.local/pipx/venvs/pdm/bin/activate
pip install git+https://github.com/pradyunsg/installer
```

**Comment by jonathanpascoe** [comment]
Thanks for the pointer @pawamoy.

**Comment by UnoYakshi** [comment]
Until I used pawamoy's solution, PDM couldn't find (?) `sqlalchemy==1.4.46` or `sqlalchemy==1.4.47` (when standard `pip` could).
