### ISSUE TITLE
typing_extensions needed for Python 3.7

### ISSUE THREAD

**Issue by dejanceltra** [pdm-project/pdm#674]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

`pdm` doesn't have `typing_extensions` specified as a dependency, but it's needed for Python 3.7:
https://github.com/pdm-project/pdm/blob/1f83b7e87bfb396cb9c923459a629defeacbdd29/pdm/_types.py#L4-L9

## Steps to reproduce

```
$ /usr/local/python3.7/bin/pip install pdm==1.8.5
$ /usr/local/python3.7/bin/pdm
```

## Actual behavior

```
$ /usr/local/python3.7/bin/pdm
Traceback (most recent call last):
  File "/usr/local/python3.7/bin/pdm", line 5, in <module>
    from pdm.core import main
  File "/usr/local/python3.7/lib/python3.7/site-packages/pdm/__init__.py", line 5, in <module>
    from pdm.cli.commands.base import BaseCommand
  File "/usr/local/python3.7/lib/python3.7/site-packages/pdm/cli/commands/base.py", line 5, in <module>
    from pdm.cli.options import Option, global_option, project_option, verbose_option
  File "/usr/local/python3.7/lib/python3.7/site-packages/pdm/cli/options.py", line 9, in <module>
    from pdm._types import Protocol
  File "/usr/local/python3.7/lib/python3.7/site-packages/pdm/_types.py", line 9, in <module>
    from typing_extensions import Literal, Protocol, TypedDict
ModuleNotFoundError: No module named 'typing_extensions'
```

**Comment by blueyed** [comment]
Might be worth only importing it with/for `typing.TYPE_CHECKING`…

**Comment by pawamoy** [comment]
@frostming I think you shouldn't rely on a package being a dependency of another dependency. If you import it directly, list it as a dependency. This could prevent bad surprises :) And it gives you control over the accepted versions.
