### ISSUE TITLE
pdm install error (regarding to resolvelib)

### ISSUE THREAD

**Issue by stepanselyuk** [pdm-project/pdm#685]
- [+] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

```
pdm install -v
```

## Actual behavior

```
$ pdm install -v
Traceback (most recent call last):
  File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 171, in _merge_into_criterion
KeyError: 'flask'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/pdm/core.py", line 200, in main
    return Core().main(args)
  File "/usr/local/lib/python3.9/dist-packages/pdm/core.py", line 153, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/usr/local/lib/python3.9/dist-packages/pdm/core.py", line 148, in main
    f(options.project, options)
  File "/usr/local/lib/python3.9/dist-packages/pdm/cli/commands/install.py", line 45, in handle
    actions.do_sync(
  File "/usr/local/lib/python3.9/dist-packages/pdm/cli/actions.py", line 154, in do_sync
    candidates = resolve_candidates_from_lockfile(project, requirements)
  File "/usr/local/lib/python3.9/dist-packages/pdm/cli/actions.py", line 112, in resolve_candidates_from_lockfile
    mapping, *_ = resolve(
  File "/usr/local/lib/python3.9/dist-packages/pdm/resolver/core.py", line 31, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 453, in resolve
  File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 318, in resolve
  File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 173, in _merge_into_criterion
  File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 79, in from_requirement
TypeError: find_matches() missing 2 required positional arguments: 'requirements' and 'incompatibilities'

```

## Expected behavior

Packages installed successfully

## Environment Information

```bash
$ pdm info && pdm info --env
PDM version:        1.9.0                                    
Python Interpreter: /bin/python3 (3.9)                       
Project Root:       /home/pi/rpi-led-strip                   
Project Packages:   /home/pi/rpi-led-strip/__pypackages__/3.9
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.2",
  "os_name": "posix",
  "platform_machine": "armv6l",
  "platform_release": "5.10.63+",
  "platform_system": "Linux",
  "platform_version": "#1459 Wed Oct 6 16:40:27 BST 2021",
  "python_full_version": "3.9.2",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

This is a new raspbian/buster installation with upgrading to raspbian/bullseye and installation of:
```
sudo apt install python3 python3-pip
sudo pip3 install pdm
```

**Comment by frostming** [comment]
Try to upgrade the version of `resolvelib` in `/usr/share/python-wheels`

**Comment by frostming** [comment]
I don't know how the distro works but pdm pinned `"resolvelib>=0.7.0,<0.8.0"`. So it is better not to install pdm in the global environment.

**Comment by stepanselyuk** [comment]
@frostming yes, but for example controlling a led strip requires sudo, and so pdm should be in that environment or I will need to dance around with sudo / PATH / etc. It seems to upgrade pip and wheels helped in this case.

**Comment by henri-hulski** [comment]
Why is this closed? Is there a fix?
I have exactly the same Problem.
I'm on Debian 11 (Bullseye), which is the newest stable.
The content from `/usr/share/python-wheels` is provided by the Debian package python-pip-whl (20.3.4-4) which is a dependency of python3.9-venv (3.9.2-1), python3-virtualvenv (20.4.0+ds-2) and python3-pip (20.3.4-4). python3.9-venv is a dependency of python3.9 so no way to uninstall it.
As I understand the only way to upgrade `/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl` is to install an updates version of python-pip-whl, which is out of our scope.
So I think PDM should ship with it's own version of resolvelib included. Otherwise it will fail on all current Linux distributions which derived from Debian and didn't address this issue.

**Comment by frostming** [comment]
@henri-hulski you should never mess with the system dependencies, but instead, install PDM in an **isolated** env. Look at the [installation guide](https://github.com/pdm-project/pdm#installation), we never recommend installing PDM into the global site-packages.

**Comment by henri-hulski** [comment]
@frostming I didn't. Actually I followed exactly the instructions and used the install-pdm.py installer.

**Comment by henri-hulski** [comment]
**My environment:**
```sh
$ pdm info && pdm info --env
PDM version:        1.10.0
Python Interpreter: /usr/bin/python3 (3.9)
Project Root:       ~/web/myproject/myproject-server
Project Packages:   ~/web/myproject/myproject-server/__pypackages__/3.9
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.2",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.14.0-0.bpo.2-amd64",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Debian 5.14.9-2~bpo11+1 (2021-10-10)",
  "python_full_version": "3.9.2",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

So the Python interpreter in use is the global one: `/usr/bin/python3`.
The same with the environment of @stepanselyuk (here `/bin/python3`).
So you cannot really say that it's isolated.

**Comment by frostming** [comment]
no, `pdm info` shows the project environment, not the environment where `pdm` lies

**Comment by henri-hulski** [comment]
Aa ok. is there a way to check which environment `pdm` is using?

**Comment by pawamoy** [comment]
`head -n1 $(type pdm | grep -o '/.*')` to show the interpreter used by PDM?

**Comment by henri-hulski** [comment]
This is my error, when trying to make an install:
```sh
$ pdm install --prod -vvv
Lock file does not exist or is incompatible, trying to generate one...
======== Start resolving requirements ========
  pytest-cov
  coverage[toml]
  more.cerberus
  more.jwtauth
  more.pony
  more.emit
  more.cors
  argon2-cffi
  gunicorn
  itsdangerous
  yagmail[all]
  keyrings.alt
  email-validator
  psycopg2
  pyyaml
  flake8
  black
  pytest>=2.9.1
  pytest-env
  pytest-localserver
  WebTest>=2.0.14
  python>=3.9
  Adding requirement pytest-cov
Traceback (most recent call last):
  File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 171, in _merge_into_criterion
KeyError: 'pytest-cov'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "~/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/core.py", line 200, in main
    return Core().main(args)
  File "~/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/core.py", line 153, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "~.local/share/pdm/venv/lib/python3.9/site-packages/pdm/core.py", line 148, in main
    f(options.project, options)
  File "~/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/cli/commands/install.py", line 39, in handle
    actions.do_lock(project, strategy="all", dry_run=options.dry_run)
  File "~/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/cli/actions.py", line 68, in do_lock
    mapping, dependencies = resolve(
  File "~/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/resolver/core.py", line 31, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 453, in resolve
  File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 318, in resolve
  File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 173, in _merge_into_criterion
  File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 79, in from_requirement
TypeError: find_matches() missing 2 required positional arguments: 'requirements' and 'incompatibilities'
```
So it seems that `~/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/resolver/core.py` is using the global `/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py´.

**Comment by henri-hulski** [comment]
So it seems that the Problem comes from the import of `Resolver`. 
https://github.com/pdm-project/pdm/blob/main/pdm/resolver/core.py#L9-L10

**Comment by frostming** [comment]
It turns out the redistributed `pip` has a special debundling process that adds the wheels path in front of `sys.path`.

**Comment by iharh** [comment]
Thank you very much. The proposed workaround (re-install the pip in the venv) has just helped me in the same situation, as described.
