### ISSUE TITLE
Checking for update is blocking and options are strings instead of boolean

### ISSUE THREAD

**Issue by armenzg** [pdm-project/pdm#689]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Checking for updates gets blocked. Last week this was working.
In order to disable checking for updates I had to patch `pdm/core.py` and run `pdm config check_updates False`
```diff
+ import distutils
# Line 165
- if options.project.config["check_update"]:
+ if bool(distutils.util.strtobool(options.project.config["check_update"])):
```

Any operation would take over 30 seconds.

Output
```
❯ pdm config check_update False
^CTraceback (most recent call last):
  File "/Users/armenzg/.local/bin/pdm", line 10, in <module>
    sys.exit(main())
  File "/Users/armenzg/Library/Application Support/pdm/venv/lib/python3.8/site-packages/pdm/core.py", line 200, in main
    return Core().main(args)
  File "/Users/armenzg/Library/Application Support/pdm/venv/lib/python3.8/site-packages/pdm/core.py", line 165, in main
    check_update(options.project)
  File "/Users/armenzg/Library/Application Support/pdm/venv/lib/python3.8/site-packages/pdm/cli/actions.py", line 737, in check_update
    candidate = get_finder([]).find_best_candidate("pdm")
  File "/Users/armenzg/Library/Application Support/pdm/venv/lib/python3.8/site-packages/pip/_internal/index/package_finder.py", line 879, in find_best_candidate
    candidates = self.find_all_candidates(project_name)
  File "/Users/armenzg/Library/Application Support/pdm/venv/lib/python3.8/site-packages/pip/_internal/index/package_finder.py", line 824, in find_all_candidates
    page_candidates = list(page_candidates_it)
  File "/Users/armenzg/Library/Application Support/pdm/venv/lib/python3.8/site-packages/pip/_internal/index/sources.py", line 134, in page_candidates
    yield from self._candidates_from_page(self._link)
  File "/Users/armenzg/Library/Application Support/pdm/venv/lib/python3.8/site-packages/pip/_internal/index/package_finder.py", line 783, in process_project_url
    html_page = self._link_collector.fetch_page(project_url)
  File "/Users/armenzg/Library/Application Support/pdm/venv/lib/python3.8/site-packages/pip/_internal/index/collector.py", line 512, in fetch_page
    return _get_html_page(location, session=self.session)
  File "/Users/armenzg/Library/Application Support/pdm/venv/lib/python3.8/site-packages/pip/_internal/index/collector.py", line 422, in _get_html_page
    resp = _get_html_response(url, session=session)
  File "/Users/armenzg/Library/Application Support/pdm/venv/lib/python3.8/site-packages/pip/_internal/index/collector.py", line 120, in _get_html_response
    resp = session.get(
  File "/Users/armenzg/Library/Application Support/pdm/venv/lib/python3.8/site-packages/pip/_vendor/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/Users/armenzg/Library/Application Support/pdm/venv/lib/python3.8/site-packages/pip/_internal/network/session.py", line 449, in request
    return super().request(method, url, *args, **kwargs)
  File "/Users/armenzg/Library/Application Support/pdm/venv/lib/python3.8/site-packages/pip/_vendor/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/armenzg/Library/Application Support/pdm/venv/lib/python3.8/site-packages/pip/_vendor/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/armenzg/Library/Application Support/pdm/venv/lib/python3.8/site-packages/pip/_vendor/cachecontrol/adapter.py", line 53, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/Users/armenzg/Library/Application Support/pdm/venv/lib/python3.8/site-packages/pip/_vendor/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/armenzg/Library/Application Support/pdm/venv/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Users/armenzg/Library/Application Support/pdm/venv/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/Users/armenzg/Library/Application Support/pdm/venv/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
from __future__ import annotations
```

## Actual behavior

Any command that checks for updates takes over 30 seconds.

## Expected behavior

Any command takes less than 5-10 seconds to execute

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
❯ pdm info && pdm info --env
PDM version:        1.9.0
Python Interpreter: /Users/armenzg/.pyenv/versions/3.8.12/bin/python (3.8)
Project Root:       /Users/armenzg/code/python-arm64-wheels
Project Packages:   /Users/armenzg/code/python-arm64-wheels/__pypackages__/3.8
```

**Comment by armenzg** [comment]
For the record, the root of the slow down is `pip`, however, pdm should handle this better or expose the root of the problem.

Filed as https://github.com/pypa/pip/issues/10602

**Comment by armenzg** [comment]
Thanks @frostming !
