### ISSUE TITLE
Error in git+https

### ISSUE THREAD

**Issue by abersheeran** [pdm-project/pdm#700]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Write `git+https://github.com/python/mypy` dependencies at pyproject.toml and use `pdm update`.

Run `pdm install` at other PC.

## Actual behavior

https://github.com/abersheeran/baize/runs/3984632518?check_suite_focus=true

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pdm/core.py", line 200, in main
    return Core().main(args)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pdm/core.py", line 153, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pdm/core.py", line 148, in main
    f(options.project, options)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pdm/cli/commands/install.py", line 45, in handle
    actions.do_sync(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pdm/cli/actions.py", line 154, in do_sync
    candidates = resolve_candidates_from_lockfile(project, requirements)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pdm/cli/actions.py", line 112, in resolve_candidates_from_lockfile
    mapping, *_ = resolve(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pdm/resolver/core.py", line 31, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/resolvelib/resolvers.py", line 472, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/resolvelib/resolvers.py", line 366, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/resolvelib/resolvers.py", line 212, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/resolvelib/resolvers.py", line 202, in _get_updated_criteria
    for requirement in self._p.get_dependencies(candidate=candidate):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pdm/resolver/providers.py", line 103, in get_dependencies
    deps, requires_python, _ = self.repository.get_dependencies(candidate)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pdm/models/repositories.py", line 394, in get_dependencies
    reqs, python, summary = super().get_dependencies(candidate)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pdm/models/repositories.py", line 79, in get_dependencies
    requirements, requires_python, summary = getter(candidate)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pdm/models/repositories.py", line 386, in _get_dependencies_from_lockfile
    return self.candidate_info[self._identify_candidate(candidate)]
KeyError: ('mypy', '0.920+dev.01d6eb82e146a37f2a9d873bdc6f1918e95e5308', None, False)
```

## Environment Information

pdm1.9.0 in ubuntu

**Comment by weilu** [comment]
In my case I removed pdm.lock and re-ran `pdm install` worked, granted I don't care about things getting upgraded in the process
