### ISSUE TITLE
pdm init throws KeyError

### ISSUE THREAD

**Issue by pillmuncher** [pdm-project/pdm#716]
When I run `pdm init -v` I get:

```
Creating a pyproject.toml for PDM...
Traceback (most recent call last):
  File "/home/mick/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/mick/.local/lib/python3.10/site-packages/pdm/core.py", line 200, in main
    return Core().main(args)
  File "/home/mick/.local/lib/python3.10/site-packages/pdm/core.py", line 153, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/home/mick/.local/lib/python3.10/site-packages/pdm/core.py", line 148, in main
    f(options.project, options)
  File "/home/mick/.local/lib/python3.10/site-packages/pdm/cli/commands/init.py", line 45, in handle
    actions.do_use(project)
  File "/home/mick/.local/lib/python3.10/site-packages/pdm/cli/actions.py", line 499, in do_use
    dict.fromkeys(filter(version_matcher, project.find_interpreters(python)))
  File "/home/mick/.local/lib/python3.10/site-packages/pdm/project/core.py", line 562, in find_interpreters
    config = self.config
  File "/home/mick/.local/lib/python3.10/site-packages/pdm/project/core.py", line 130, in config
    result = dict(self.global_config)
  File "/home/mick/.local/lib/python3.10/site-packages/pdm/project/config.py", line 192, in __getitem__
    env_var = self._config_map[key].env_var
KeyError: 'publish.password'
```

I'm using Python3.10 (installed from source under my home folder) on Solus Linux. I tried installing pdm both via pip and curl, but no joy.

Is it something that I'm doing wrong?

**Comment by frostming** [comment]
Did you re-installed PDM? It seems you have installed `pdm-publish` but it is no longer in use.

Try clearing the `publish.password` in `~/.pdm/config.toml`

**Comment by pillmuncher** [comment]
Yeah, removing the `password=...` entry from `[publish]` section fixed it. Thank you.
