### ISSUE TITLE
[TypeError]: find_matches()

### ISSUE THREAD

**Issue by jdhaines** [pdm-project/pdm#717]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

This looks like it's possibly a duplicate of #598, but that was closed for lack of input.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

`pip install pdm` 
> v 1.10.0 installed
`pdm init`
> follow init flow with no issues and defaults
`pdm add click`
>error shown

I actually first saw the error while trying to install from a more full `pyproject.toml` file from another project... but even the simplest use case causes the issue.

## Actual behavior

Error thrown on install from exisitng `pyproject.toml` or adding new dependencies to a new simple project.

## Expected behavior

Install dependencies found in `pyproject.toml` file.  Remove lock file had no effect.

## Environment Information

```bash
~/git/pdm ❯ pdm info && pdm info --env
PDM version:        1.10.0
Python Interpreter: /usr/bin/python (3.9)
Project Root:       /home/josh/git/pdm
Project Packages:   /home/josh/git/pdm/__pypackages__/3.9
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.5",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.13.0-7620-generic",
  "platform_system": "Linux",
  "platform_version": "#20~1634827117~21.04~874b071-Ubuntu SMP Fri Oct 29 15:06:55 UTC ",
  "python_full_version": "3.9.5",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

Error output appears to be the same for all types of usage.  Error output below.  This is a fresh install of popOS.  Pyhton 3.9 installed, pip installed, then pdm.  I cloned a project with a working python project (worked on windows and other colleagues' machines previously).  I'm not sure what the issue is.  The error message appeared in #598, but it wasn't sufficiently resolved so I'm creating a new issue.

Appreciate any help, really enjoy this package manager!

### Error
```bash
~/git/pdm ❯ pdm add click -v
Adding packages to default dependencies: click
======== Start resolving requirements ========
  click
  python>=3.9
  Adding requirement click
Traceback (most recent call last):
  File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 171, in _merge_into_criterion
KeyError: 'click'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/josh/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/josh/.local/lib/python3.9/site-packages/pdm/core.py", line 200, in main
    return Core().main(args)
  File "/home/josh/.local/lib/python3.9/site-packages/pdm/core.py", line 153, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/home/josh/.local/lib/python3.9/site-packages/pdm/core.py", line 148, in main
    f(options.project, options)
  File "/home/josh/.local/lib/python3.9/site-packages/pdm/cli/commands/add.py", line 64, in handle
    actions.do_add(
  File "/home/josh/.local/lib/python3.9/site-packages/pdm/cli/actions.py", line 211, in do_add
    resolved = do_lock(project, strategy, tracked_names, reqs, dry_run=dry_run)
  File "/home/josh/.local/lib/python3.9/site-packages/pdm/cli/actions.py", line 68, in do_lock
    mapping, dependencies = resolve(
  File "/home/josh/.local/lib/python3.9/site-packages/pdm/resolver/core.py", line 31, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 453, in resolve
  File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 318, in resolve
  File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 173, in _merge_into_criterion
  File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 79, in from_requirement
TypeError: find_matches() missing 2 required positional arguments: 'requirements' and 'incompatibilities'
```

**Comment by frostming** [comment]
See #685 , you should use our recommended installation method.
