### ISSUE TITLE
Cannot switch from pdm Python to system default interpreter

### ISSUE THREAD

**Issue by frafra** [pdm-project/pdm#777]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

1. Install pdm with Python 3.10
2.  Try to use Python 3.6

## Actual behavior

```
$ pdm use /usr/bin/python3.6 -v
WARNING: Dynamic `classifiers` is no longer supported, please supply all classifiers manually
Traceback (most recent call last):
  File "/home/francesco.frassinell/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/francesco.frassinell/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/core.py", line 200, in main
    return Core().main(args)
  File "/home/francesco.frassinell/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/core.py", line 153, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/home/francesco.frassinell/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/core.py", line 148, in main
    f(options.project, options)
  File "/home/francesco.frassinell/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/cli/commands/use.py", line 23, in handle
    actions.do_use(project, options.python, options.first)
  File "/home/francesco.frassinell/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/cli/actions.py", line 504, in do_use
    raise NoPythonVersion("Python interpreter is not found on the system.")
pdm.exceptions.NoPythonVersion: Python interpreter is not found on the system.
```

## Expected behavior

It should switch to the other interpreter.

## Environment Information

```bash
WARNING: Dynamic `classifiers` is no longer supported, please supply all classifiers manually
PDM version:        1.11.0
Python Interpreter: /home/francesco.frassinell/Software/bin/python3 (3.10)
Project Root:       /home/francesco.frassinell/Code/coat-tools
Project Packages:   /home/francesco.frassinell/Code/coat-tools/__pypackages__/3.10
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.0",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "4.15.0-162-generic",
  "platform_system": "Linux",
  "platform_version": "#170-Ubuntu SMP Mon Oct 18 11:38:05 UTC 2021",
  "python_full_version": "3.10.0",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
What is the value of `requires-python` in pyproject.toml? It must contain what Python version you want to use.

**Comment by frostming** [comment]
Yeah, improved: 7a1786a
