### ISSUE TITLE
Crash during pdm import

### ISSUE THREAD

**Issue by DanLipsitt** [pdm-project/pdm#807]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

Given
### pyproject.toml
```toml
[project]

[tool]
[tool.pdm]
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
```

And an arbitrary requirements.txt (even an empty one), run

### Failing command
```sh
pdm import -f requirements requirements.txt -v
```

The `pyproject.toml` is a minimized example. One with all the standard fields from `pdm init` will also trigger the bug.

## Actual behavior

```python
Traceback (most recent call last):
  File "/Users/dlipsitt/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/Users/dlipsitt/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/core.py", line 199, in main
    return Core().main(args)
  File "/Users/dlipsitt/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/core.py", line 152, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/Users/dlipsitt/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/core.py", line 147, in main
    f(options.project, options)
  File "/Users/dlipsitt/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/cli/commands/import_cmd.py", line 35, in handle
    do_import(project, options.filename, options.format, options)
  File "/Users/dlipsitt/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/cli/actions.py", line 592, in do_import
    merge_dictionary(pyproject["tool"]["pdm"], settings)  # type: ignore
  File "/Users/dlipsitt/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/cli/utils.py", line 632, in merge_dictionary
    target[key].extend(value)
  File "/opt/homebrew/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/_collections_abc.py", line 1141, in extend
    self.append(v)
  File "/opt/homebrew/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/_collections_abc.py", line 1120, in append
    self.insert(len(self), value)
  File "/Users/dlipsitt/.local/pipx/venvs/pdm/lib/python3.10/site-packages/atoml/items.py", line 1432, in insert
    raise ValueError(f"Unsupported insert value type: {type(value)}")
ValueError: Unsupported insert value type: <class 'dict'>
```

## Expected behavior

I expect the `project.dependencies` field to be added, replaced, or updated successfully.

## Environment Information

Command fails with both [asdf](https://github.com/asdf-vm/asdf) and homebrew-managed Python interpreters:

```bash
PDM version:        1.11.3
Python Interpreter: /Users/dlipsitt/.asdf/installs/python/3.9.7/bin/python3 (3.9)
Project Root:       /private/tmp/pdm-tmp
Project Packages:   /private/tmp/pdm-tmp/__pypackages__/3.9
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.7",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "20.3.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101",
  "python_full_version": "3.9.7",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "darwin"
}
```

```bash
PDM version:        1.11.3
Python Interpreter: /opt/homebrew/opt/python@3.9/bin/python3.9 (3.9)
Project Root:       /private/tmp/pdm-tmp
Project Packages:   /private/tmp/pdm-tmp/__pypackages__/3.9
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.9",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "20.3.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101",
  "python_full_version": "3.9.9",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
What is special with your requirements.txt?
