### ISSUE TITLE
Installation errors with PDM 1.12.0

### ISSUE THREAD

**Issue by pawamoy** [pdm-project/pdm#817]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

I'm getting lots of FileExistsError during both regular installs and retries:

```console
% pdm install -v
...
add semver failed:
Traceback (most recent call last):
  File "/home/user/.basher-packages/pyenv/pyenv/versions/3.8.11/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 190, in install_candidate
    self.manager.install(can)
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/installers/manager.py", line 38, in install
    installer(candidate.build(), self.environment, candidate.direct_url())
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/installers/installers.py", line 156, in install_wheel_with_cache
    dist_info_dir = _install_wheel(
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/installers/installers.py", line 255, in _install_wheel
    destination.finalize_installation(
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/installers/installers.py", line 79, in finalize_installation
    target.symlink_to(child)
  File "/home/user/.basher-packages/pyenv/pyenv/versions/3.8.11/lib/python3.8/pathlib.py", line 1384, in symlink_to
    self._accessor.symlink(target, self, target_is_directory)
  File "/home/user/.basher-packages/pyenv/pyenv/versions/3.8.11/lib/python3.8/pathlib.py", line 446, in symlink
    return os.symlink(a, b)
FileExistsError: [Errno 17] File exists: '/home/user/.cache/pdm/packages/semver-2.13.0-py2.py3-none-any/lib/__pycache__' -> '/home/user/project/__pypackages__/3.8/lib/__pycache__'
```

## Actual behavior

The symlink installs seem to try to symlink the `__pycache__` folder of every cached package into `__pypackages__/major.minor/lib`.

## Expected behavior

Only symlink actual packages, not `__pycache__` (nor dist-info, or other folders, or other files).

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.12.0
Python Interpreter: /home/user/.basher-packages/pyenv/pyenv/versions/3.8.11/bin/python3.8 (3.8)
Project Root:       /home/user/project
Project Packages:   /home/user/project/__pypackages__/3.8
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.11",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "3.10.0-862.6.3.el7.x86_64",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Fri Jun 15 17:57:37 EDT 2018",
  "python_full_version": "3.8.11",
  "platform_python_implementation": "CPython",
  "python_version": "3.8",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
> Only symlink actual packages, not __pycache__ (nor dist-info, or other folders, or other files).

I only skip `__pycaches__` and `.pyc` files, other files `.pth`, `.txt`... are meant to be installed to the lib path, any problem?
