### ISSUE TITLE
Issue installing from subdirectory

### ISSUE THREAD

**Issue by Indiana3714** [pdm-project/pdm#824]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce
This is made using a clean PDM folder etc. I tried using the syntax from this commit https://github.com/pdm-project/pdm/pull/509/commits/372fb6ad0738f13e4ecfede2b566fff3cdae219a (which works for selenium but not for this library I'm attempting for this issue)
```
pdm init
Creating a pyproject.toml for PDM...
Using Python interpreter: C:/Python39/python.EXE (3.9)
Is the project a library that will be uploaded to PyPI? [y/N]:
License(SPDX name) [MIT]:
Author name [XXX]:
Author email [XXX@XXX.com]:
Python requires('*' to allow any) [>=3.9]:
Changes are written to pyproject.toml.
```

```
pdm add cython
Adding packages to default dependencies: cython
✔ � Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
⠙ Resolving packages from lockfile...
Synchronizing working set with lock file: 1 to add, 0 to update, 0 to remove
  ✔ Install cython 0.29.26 successful
```

```
pdm add -e "git+https://github.com/CoolProp/CoolProp.git@master#egg=CoolProp&subdirectory=wrappers/Python" -v
Adding packages to default dependencies: coolprop
======== Start resolving requirements ========
  cython>=0.29.26
  -e git+https://github.com/CoolProp/CoolProp.git@master#egg=CoolProp&subdirectory=wrappers/Python
  python>=3.9
  Adding requirement cython>=0.29.26
        Found matching candidates:
          <Candidate cython 0.29.26 from https://pypi.org/simple/cython/>
  Adding requirement -e git+https://github.com/CoolProp/CoolProp.git@master#egg=CoolProp&subdirectory=wrappers/Python
Preparing isolated env for PEP 517 build...
Collecting wheel
  Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
Collecting setuptools>=40.8.0
  Using cached setuptools-60.2.0-py3-none-any.whl (953 kB)
Installing collected packages: wheel, setuptools
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pdm 1.12.1 requires click>=7, which is not installed.
fixit 0.1.4 requires flake8>=3.8.1, which is not installed.
Successfully installed setuptools-60.2.0 wheel-0.37.1
Collecting setuptools_pep660
  Using cached setuptools_pep660-0.1.2-py3-none-any.whl (4.1 kB)
Collecting setuptools>=42
  Using cached setuptools-60.2.0-py3-none-any.whl (953 kB)
Collecting wheel
  Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel, setuptools, setuptools-pep660
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pdm 1.12.1 requires click>=7, which is not installed.
fixit 0.1.4 requires flake8>=3.8.1, which is not installed.
Successfully installed setuptools-60.2.0 setuptools-pep660-0.1.2 wheel-0.37.1
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\pep517\in_process\_in_process.py", line 177, in prepare_metadata_for_build_editable
    hook = backend.prepare_metadata_for_build_editable
AttributeError: module 'setuptools_pep660' has no attribute 'prepare_metadata_for_build_editable'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 249, in <module>
    import Cython
ModuleNotFoundError: No module named 'Cython'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\pep517\in_process\_in_process.py", line 363, in <module>
    main()
  File "C:\Python39\lib\site-packages\pep517\in_process\_in_process.py", line 345, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "C:\Python39\lib\site-packages\pep517\in_process\_in_process.py", line 186, in prepare_metadata_for_build_editable
    whl_basename = build_hook(metadata_directory, config_settings)
  File "C:\Users\Administrator\AppData\Local\Temp\pdm-build-env-rw01k11a-shared\Lib\site-packages\setuptools_pep660\__init__.py", line 11, in build_editable
    return setuptools.build_meta._BACKEND._build_with_temp_dir(
  File "C:\Users\Administrator\AppData\Local\Temp\pdm-build-env-rw01k11a-shared\Lib\site-packages\setuptools\build_meta.py", line 215, in _build_with_temp_dir
    self.run_setup()
  File "C:\Users\Administrator\AppData\Local\Temp\pdm-build-env-rw01k11a-shared\Lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 251, in <module>
    raise ImportError("Cython not found, please install it.  You can do a pip install Cython")
ImportError: Cython not found, please install it.  You can do a pip install Cython
Failed to build package, try parsing project files.
  Adding requirement python>=3.9
======== Starting round 0 ========
Resolving: new pin python >=3.9
======== Ending round 0 ========
======== Starting round 1 ========
Traceback (most recent call last):
  File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\pdm.exe\__main__.py", line 7, in <module>
  File "C:\Python39\lib\site-packages\pdm\core.py", line 219, in main
    return Core().main(args)
  File "C:\Python39\lib\site-packages\pdm\core.py", line 161, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "C:\Python39\lib\site-packages\pdm\core.py", line 156, in main
    f(options.project, options)
  File "C:\Python39\lib\site-packages\pdm\cli\commands\add.py", line 53, in handle
    actions.do_add(
  File "C:\Python39\lib\site-packages\pdm\cli\actions.py", line 235, in do_add
    resolved = do_lock(project, strategy, tracked_names, reqs, dry_run=dry_run)
  File "C:\Python39\lib\site-packages\pdm\cli\actions.py", line 76, in do_lock
    mapping, dependencies = resolve(
  File "C:\Python39\lib\site-packages\pdm\resolver\core.py", line 31, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "C:\Python39\lib\site-packages\resolvelib\resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Python39\lib\site-packages\resolvelib\resolvers.py", line 373, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "C:\Python39\lib\site-packages\resolvelib\resolvers.py", line 213, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "C:\Python39\lib\site-packages\resolvelib\resolvers.py", line 203, in _get_updated_criteria
    for requirement in self._p.get_dependencies(candidate=candidate):
  File "C:\Python39\lib\site-packages\pdm\resolver\providers.py", line 169, in get_dependencies
    deps, requires_python, _ = self.repository.get_dependencies(candidate)
  File "C:\Python39\lib\site-packages\pdm\models\repositories.py", line 79, in get_dependencies
    requirements, requires_python, summary = getter(candidate)
  File "C:\Python39\lib\site-packages\pdm\models\repositories.py", line 47, in wrapper
    self._candidate_info_cache.set(candidate, result)
  File "C:\Python39\lib\site-packages\pdm\models\caches.py", line 58, in set
    key = self._get_key(candidate)
  File "C:\Python39\lib\site-packages\pdm\models\caches.py", line 45, in _get_key
    raise KeyError
KeyError
```

## Actual behavior
Unable to Install CoolProp library from source using setup.py install (even when Cython is installed just before, and not during the same 'add' command)

## Expected behavior

Expecting it to install correctly using 
```
python setup.py install
```

since that would work if you did it globally on the system Python

## Environment Information

```
pdm info && pdm info --env
PDM version:        1.12.1
Python Interpreter: C:/Python39/python.EXE (3.9)
Project Root:       C:/Users/Administrator/Desktop/TEST_COOLPROP/testcoolproppdm
Project Packages:   C:\Users\Administrator\Desktop\TEST_COOLPROP\testcoolproppdm\__pypackages__\3.9
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.7",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19044",
  "python_full_version": "3.9.7",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "win32"
}
```

**Comment by frostming** [comment]
The editable wheel is built in an isolated environment, so the pre-installed `Cython` can't be used. Try the solution below:

- add `--no-isolation` flag, or
- Specify the build requirements in `requires` under `[build-system]`, as standardized in [PEP 517](https://www.python.org/dev/peps/pep-0517/#id4)

**Comment by Indiana3714** [comment]
That seems to work thanks a lot. I have a couple of other teething problems with PDM that I hope to resolve as well, trying to move away from Poetry due to it not supporting subdirectory installs (where setup.py is in a nested folder as the above issue)

**Comment by Indiana3714** [comment]
> The editable wheel is built in an isolated environment, so the pre-installed `Cython` can't be used. Try the solution below:
> 
> * add `--no-isolation` flag, or
> * Specify the build requirements in `requires` under `[build-system]`, as standardized in [PEP 517](https://www.python.org/dev/peps/pep-0517/#id4)

Thank you! The --no-isolation flag seems to work. I'm trying to see if I can replace Poetry with PDM.
