### ISSUE TITLE
twisted fails to install if `install_cache = true`

### ISSUE THREAD

**Issue by SmileyChris** [pdm-project/pdm#832]
Doing a fresh install of my project, pdm chokes with the following exception:

```  Retry failed jobs
  ✖ Install twisted 21.7.0 failed

ERRORS:
add twisted failed:
Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/chris/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 190, in install_candidate
    self.manager.install(can)
  File "/home/chris/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/installers/manager.py", line 38, in install
    installer(candidate.build(), self.environment, candidate.direct_url())
  File "/home/chris/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/installers/installers.py", line 238, in install_wheel_with_cache
    dist_info_dir = _install_wheel(
  File "/home/chris/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/installers/installers.py", line 337, in _install_wheel
    destination.finalize_installation(
  File "/home/chris/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/installers/installers.py", line 155, in finalize_installation
    for relpath in _create_symlinks_recursively(
  File "/home/chris/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/installers/installers.py", line 89, in _create_symlinks_recursively
    os.remove(destination_root)
IsADirectoryError: [Errno 21] Is a directory: '/home/chris/dev/project/__pypackages__/3.10/lib/twisted'
```

Here's a simple toml file to reproduce:
```
[project]
dependencies = [
    "channels~=3.0",
]
requires-python = ">=3.7"
```
(this also actually fails on `zope.interface 4.4.3` too, my project uses other dependencies bumping this to `5.4.0` which installs fine for whatever reason)

**Comment by frostming** [comment]
Do you have any other package that shares the `twisted` namespace?

**Comment by SmileyChris** [comment]
The workaround works correctly.

I have `install_cache = true` on in my global pdm config, and setting `install_cache = false` in the local config also fixes it.

**Comment by frostming** [comment]
So I think this is no longer a problem, when symlink caching doesn't work sometimes, switch to `pth`.

**Comment by drewp** [comment]
This bit me just now: PDM 1.13.6.

Somehow I need to get from this error:
```
% pdm add cyclone
Adding packages to default dependencies: cyclone
✔ 🔒 Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
Synchronizing working set with lock file: 15 to add, 0 to update, 0 to remove

  ✔ Install setuptools 61.3.0 successful
  ✔ Install attrs 21.4.0 successful
  ✔ Install automat 20.2.0 successful
  ✔ Install cffi 1.15.0 successful
  ✔ Install constantly 15.1.0 successful
  ✔ Install cryptography 36.0.2 successful
  ✔ Install cyclone 1.3 successful
  ✔ Install hyperlink 21.0.0 successful
  ✔ Install idna 3.3 successful
  ✔ Install incremental 21.3.0 successful
  ✔ Install pycparser 2.21 successful
  ✔ Install pyhamcrest 2.0.3 successful
  ✔ Install pyopenssl 19.0.0 successful
  ✖ Install twisted 19.2.1 failed
  ✔ Install zope.interface 5.4.0 successful
  Retry failed jobs
  ✖ Install twisted 19.2.1 failed

ERRORS:
add twisted failed:
Traceback (most recent call last):
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/drewp/.local/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 185, in install_candidate
    self.manager.install(can)
  File "/home/drewp/.local/lib/python3.9/site-packages/pdm/installers/manager.py", line 39, in install
    installer(prepared.build(), self.environment, prepared.direct_url())
  File "/home/drewp/.local/lib/python3.9/site-packages/pdm/installers/installers.py", line 238, in install_wheel_with_cache
    dist_info_dir = _install_wheel(
  File "/home/drewp/.local/lib/python3.9/site-packages/pdm/installers/installers.py", line 337, in _install_wheel
    destination.finalize_installation(
  File "/home/drewp/.local/lib/python3.9/site-packages/pdm/installers/installers.py", line 155, in finalize_installation
    for relpath in _create_symlinks_recursively(
  File "/home/drewp/.local/lib/python3.9/site-packages/pdm/installers/installers.py", line 89, in _create_symlinks_recursively
    os.remove(destination_root)
IsADirectoryError: [Errno 21] Is a directory: '/my/serv/environment/__pypackages__/3.9/lib/twisted'

```
to the magic fix:
```
% pdm config -l feature.install_cache_method pth
DEPRECATED: the config has been renamed to install.cache_method
```
The fix works- can it just be default on? The workflow today involves searching github issues.
