### ISSUE TITLE
pdm import setup.py doesn't seem to like setup.py files with other Python code in it

### ISSUE THREAD

**Issue by warsaw** [pdm-project/pdm#840]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

```bash
$ git clone https://gitlab.com/warsaw/flufl.lock.git
$ cd flufl.lock
$ pdm import setup.py
```

## Actual behavior

The following verbose crash occurs:

```
% pdm import -v setup.py
Traceback (most recent call last):
  File "/usr/local/Cellar/pdm/1.12.2/libexec/lib/python3.10/site-packages/pip/_vendor/packaging/requirements.py", line 102, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/usr/local/Cellar/pdm/1.12.2/libexec/lib/python3.10/site-packages/pip/_vendor/pyparsing.py", line 1955, in parseString
    raise exc
  File "/usr/local/Cellar/pdm/1.12.2/libexec/lib/python3.10/site-packages/pip/_vendor/pyparsing.py", line 3250, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected W:(abcd...), found '"'  (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/pdm/1.12.2/libexec/lib/python3.10/site-packages/pip/_internal/req/constructors.py", line 315, in _parse_req_string
    req = get_requirement(req_as_string)
  File "/usr/local/Cellar/pdm/1.12.2/libexec/lib/python3.10/site-packages/pip/_internal/utils/packaging.py", line 84, in get_requirement
    return Requirement(req_string)
  File "/usr/local/Cellar/pdm/1.12.2/libexec/lib/python3.10/site-packages/pip/_vendor/packaging/requirements.py", line 104, in __init__
    raise InvalidRequirement(
pip._vendor.packaging.requirements.InvalidRequirement: Parse error at "'"""NFS-s'": Expected W:(abcd...)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/usr/local/Cellar/pdm/1.12.2/libexec/lib/python3.10/site-packages/pdm/core.py", line 219, in main
    return Core().main(args)
  File "/usr/local/Cellar/pdm/1.12.2/libexec/lib/python3.10/site-packages/pdm/core.py", line 161, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/usr/local/Cellar/pdm/1.12.2/libexec/lib/python3.10/site-packages/pdm/core.py", line 156, in main
    f(options.project, options)
  File "/usr/local/Cellar/pdm/1.12.2/libexec/lib/python3.10/site-packages/pdm/cli/commands/import_cmd.py", line 35, in handle
    do_import(project, options.filename, options.format, options)
  File "/usr/local/Cellar/pdm/1.12.2/libexec/lib/python3.10/site-packages/pdm/cli/actions.py", line 600, in do_import
    project_data, settings = FORMATS[key].convert(project, filename, options)
  File "/usr/local/Cellar/pdm/1.12.2/libexec/lib/python3.10/site-packages/pdm/formats/requirements.py", line 102, in convert
    ireqs, finder = parse_requirement_file(str(filename))
  File "/usr/local/Cellar/pdm/1.12.2/libexec/lib/python3.10/site-packages/pdm/formats/requirements.py", line 73, in parse_requirement_file
    ireqs = [
  File "/usr/local/Cellar/pdm/1.12.2/libexec/lib/python3.10/site-packages/pdm/formats/requirements.py", line 74, in <listcomp>
    install_req_from_parsed_requirement(pr)
  File "/usr/local/Cellar/pdm/1.12.2/libexec/lib/python3.10/site-packages/pip/_internal/req/constructors.py", line 439, in install_req_from_parsed_requirement
    req = install_req_from_line(
  File "/usr/local/Cellar/pdm/1.12.2/libexec/lib/python3.10/site-packages/pip/_internal/req/constructors.py", line 366, in install_req_from_line
    parts = parse_req_from_line(name, line_source)
  File "/usr/local/Cellar/pdm/1.12.2/libexec/lib/python3.10/site-packages/pip/_internal/req/constructors.py", line 343, in parse_req_from_line
    req: Optional[Requirement] = _parse_req_string(req_as_string)
  File "/usr/local/Cellar/pdm/1.12.2/libexec/lib/python3.10/site-packages/pip/_internal/req/constructors.py", line 329, in _parse_req_string
    raise InstallationError(msg)
pip._internal.exceptions.InstallationError: Invalid requirement: '"""NFS-safe file locking with timeouts for POSIX and Windows."""' (from line 1 of setup.py)
```

## Expected behavior

I've just started playing around with pdm so I'm not sure if this is intended to work, but it seems from the documentation that maybe it ought to.  Maybe pdm expects simpler `setup.py` files than I'm using in this package.  Note that I tried this both without running `pdm init` first and with running it first, and also with and without `-f setuppy` with no difference.

## Environment Information

```bash
$ pdm info
PDM version:        1.12.2
Python Interpreter: /usr/local/opt/python@3.9/bin/python3.9 (3.9)
Project Root:       /Users/barry/projects/flufl/lock
Project Packages:   /Users/barry/projects/flufl/lock/__pypackages__/3.9

$ {
  "implementation_name": "cpython",
  "implementation_version": "3.9.9",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "20.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:42 PDT 2021; root:xnu-7195.141.8~1/RELEASE_X86_64",
  "python_full_version": "3.9.9",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
PDM doesn't support importing from `setup.py` for now, it is a export-only format.

**Comment by warsaw** [comment]
Ah, okay thanks.  I think I assumed it worked because of the `-f setuppy` option.
