### ISSUE TITLE
[ResolutionImpossible] for adding gevent

### ISSUE THREAD

**Issue by shaozi** [pdm-project/pdm#853]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

1. `pdm init`
   1. Select python 3.10 
1. `pdm add gevent`

Create a new project and adding gevent does not work.

## Actual behavior

```sh
pdm add gevent
Adding packages to default dependencies: gevent
✔ 🔒 Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
See /var/folders/hh/0zdhqxvn0xx2v8fpgnjyjqp00000gn/T/pdm-install-resolve-kqgwj55v.log for detailed debug log.
[ResolutionImpossible]: [RequirementInformation(requirement=NamedRequirement(name='zope.event', marker=None, extras=(), specifier=<SpecifierSet('')>, editable=False, prerelease=False), parent=<Candidate gevent 21.12.0 from unknown>)]
Add '-v' to see the detailed traceback
Work/pdm-gevent-test ✅ pdm add gevent -v
Adding packages to default dependencies: gevent
======== Start resolving requirements ========
  gevent
  python>=3.10
  Adding requirement gevent
	Found matching candidates:
	  <Candidate gevent 21.12.0 from https://pypi.org/simple/gevent/>
	  <Candidate gevent 21.8.0 from https://pypi.org/simple/gevent/>
	  <Candidate gevent 21.1.2 from https://pypi.org/simple/gevent/>
	  <Candidate gevent 21.1.1 from https://pypi.org/simple/gevent/>
	  <Candidate gevent 21.1.0 from https://pypi.org/simple/gevent/>
	  <Candidate gevent 20.12.1 from https://pypi.org/simple/gevent/>
	  <Candidate gevent 20.12.0 from https://pypi.org/simple/gevent/>
	  <Candidate gevent 20.9.0 from https://pypi.org/simple/gevent/>
	  <Candidate gevent 20.6.2 from https://pypi.org/simple/gevent/>
	  <Candidate gevent 20.6.1 from https://pypi.org/simple/gevent/>
	  ... [739 more candidate(s)]
  Adding requirement python>=3.10
======== Starting round 0 ========
Resolving: new pin python >=3.10
======== Ending round 0 ========
======== Starting round 1 ========
  Adding requirement zope.event(from gevent 21.12.0)
	Found matching candidates:
	  <Candidate zope.event 4.5.0 from https://pypi.org/simple/zope-event/>
	  <Candidate zope.event 4.4 from https://pypi.org/simple/zope-event/>
	  <Candidate zope.event 4.3.0 from https://pypi.org/simple/zope-event/>
	  <Candidate zope.event 4.2.0 from https://pypi.org/simple/zope-event/>
	  <Candidate zope.event 4.1.0 from https://pypi.org/simple/zope-event/>
	  <Candidate zope.event 4.0.3 from https://pypi.org/simple/zope-event/>
	  <Candidate zope.event 4.0.2 from https://pypi.org/simple/zope-event/>
	  <Candidate zope.event 4.0.1 from https://pypi.org/simple/zope-event/>
	  <Candidate zope.event 4.0.0 from https://pypi.org/simple/zope-event/>
	  <Candidate zope.event 3.5.2 from https://pypi.org/simple/zope-event/>
	  ... [12 more candidate(s)]
  Adding requirement zope.interface(from gevent 21.12.0)
	Found matching candidates:
	  <Candidate zope.interface 5.4.0 from https://pypi.org/simple/zope-interface/>
	  <Candidate zope.interface 5.3.0 from https://pypi.org/simple/zope-interface/>
	  <Candidate zope.interface 5.2.0 from https://pypi.org/simple/zope-interface/>
	  <Candidate zope.interface 5.1.2 from https://pypi.org/simple/zope-interface/>
	  <Candidate zope.interface 5.1.1 from https://pypi.org/simple/zope-interface/>
	  <Candidate zope.interface 5.1.0 from https://pypi.org/simple/zope-interface/>
	  <Candidate zope.interface 5.0.2 from https://pypi.org/simple/zope-interface/>
	  <Candidate zope.interface 5.0.1 from https://pypi.org/simple/zope-interface/>
	  <Candidate zope.interface 5.0.0 from https://pypi.org/simple/zope-interface/>
	  <Candidate zope.interface 4.7.2 from https://pypi.org/simple/zope-interface/>
	  ... [738 more candidate(s)]
  Adding requirement setuptools(from gevent 21.12.0)
	Found matching candidates:
	  <Candidate setuptools 60.5.0 from https://pypi.org/simple/setuptools/>
	  <Candidate setuptools 60.4.0 from https://pypi.org/simple/setuptools/>
	  <Candidate setuptools 60.3.1 from https://pypi.org/simple/setuptools/>
	  <Candidate setuptools 60.3.0 from https://pypi.org/simple/setuptools/>
	  <Candidate setuptools 60.2.0 from https://pypi.org/simple/setuptools/>
	  <Candidate setuptools 60.1.1 from https://pypi.org/simple/setuptools/>
	  <Candidate setuptools 60.1.0 from https://pypi.org/simple/setuptools/>
	  <Candidate setuptools 60.0.5 from https://pypi.org/simple/setuptools/>
	  <Candidate setuptools 60.0.4 from https://pypi.org/simple/setuptools/>
	  <Candidate setuptools 60.0.3 from https://pypi.org/simple/setuptools/>
	  ... [1093 more candidate(s)]
  Adding requirement greenlet<2.0,>=1.1.0; platform_python_implementation == "CPython"(from gevent 21.12.0)
	Found matching candidates:
	  <Candidate greenlet 1.1.2 from https://pypi.org/simple/greenlet/>
	  <Candidate greenlet 1.1.1 from https://pypi.org/simple/greenlet/>
	  <Candidate greenlet 1.1.0 from https://pypi.org/simple/greenlet/>
  Adding requirement cffi>=1.12.2; platform_python_implementation == "CPython" and sys_platform == "win32"(from gevent 21.12.0)
	Found matching candidates:
	  <Candidate cffi 1.15.0 from https://pypi.org/simple/cffi/>
	  <Candidate cffi 1.14.6 from https://pypi.org/simple/cffi/>
	  <Candidate cffi 1.14.5 from https://pypi.org/simple/cffi/>
	  <Candidate cffi 1.14.4 from https://pypi.org/simple/cffi/>
	  <Candidate cffi 1.14.3 from https://pypi.org/simple/cffi/>
	  <Candidate cffi 1.14.2 from https://pypi.org/simple/cffi/>
	  <Candidate cffi 1.14.1 from https://pypi.org/simple/cffi/>
	  <Candidate cffi 1.14.0 from https://pypi.org/simple/cffi/>
	  <Candidate cffi 1.13.2 from https://pypi.org/simple/cffi/>
	  <Candidate cffi 1.13.1 from https://pypi.org/simple/cffi/>
	  ... [444 more candidate(s)]
Resolving: new pin gevent 21.12.0
======== Ending round 1 ========
======== Starting round 2 ========
Resolving: new pin setuptools 60.5.0
======== Ending round 2 ========
======== Starting round 3 ========
  Adding requirement setuptools(from zope.event 4.5.0)
	Found matching candidates:
	  <Candidate setuptools 60.5.0 from https://pypi.org/simple/setuptools/>
	  <Candidate setuptools 60.4.0 from https://pypi.org/simple/setuptools/>
	  <Candidate setuptools 60.3.1 from https://pypi.org/simple/setuptools/>
	  <Candidate setuptools 60.3.0 from https://pypi.org/simple/setuptools/>
	  <Candidate setuptools 60.2.0 from https://pypi.org/simple/setuptools/>
	  <Candidate setuptools 60.1.1 from https://pypi.org/simple/setuptools/>
	  <Candidate setuptools 60.1.0 from https://pypi.org/simple/setuptools/>
	  <Candidate setuptools 60.0.5 from https://pypi.org/simple/setuptools/>
	  <Candidate setuptools 60.0.4 from https://pypi.org/simple/setuptools/>
	  <Candidate setuptools 60.0.3 from https://pypi.org/simple/setuptools/>
	  ... [1093 more candidate(s)]
Resolving: new pin zope.event 4.5.0
======== Ending round 3 ========
======== Starting round 4 ========
  Adding requirement setuptools(from zope.interface 5.4.0)
	Found matching candidates:
	  <Candidate setuptools 60.5.0 from https://pypi.org/simple/setuptools/>
	  <Candidate setuptools 60.4.0 from https://pypi.org/simple/setuptools/>
	  <Candidate setuptools 60.3.1 from https://pypi.org/simple/setuptools/>
	  <Candidate setuptools 60.3.0 from https://pypi.org/simple/setuptools/>
	  <Candidate setuptools 60.2.0 from https://pypi.org/simple/setuptools/>
	  <Candidate setuptools 60.1.1 from https://pypi.org/simple/setuptools/>
	  <Candidate setuptools 60.1.0 from https://pypi.org/simple/setuptools/>
	  <Candidate setuptools 60.0.5 from https://pypi.org/simple/setuptools/>
	  <Candidate setuptools 60.0.4 from https://pypi.org/simple/setuptools/>
	  <Candidate setuptools 60.0.3 from https://pypi.org/simple/setuptools/>
	  ... [1093 more candidate(s)]
Resolving: new pin zope.interface 5.4.0
======== Ending round 4 ========
======== Starting round 5 ========
  Adding requirement pycparser(from cffi 1.15.0)
	Found matching candidates:
	  <Candidate pycparser 2.21 from https://pypi.org/simple/pycparser/>
	  <Candidate pycparser 2.20 from https://pypi.org/simple/pycparser/>
	  <Candidate pycparser 2.19 from https://pypi.org/simple/pycparser/>
	  <Candidate pycparser 2.18 from https://pypi.org/simple/pycparser/>
	  <Candidate pycparser 2.17 from https://pypi.org/simple/pycparser/>
	  <Candidate pycparser 2.16 from https://pypi.org/simple/pycparser/>
	  <Candidate pycparser 2.15 from https://pypi.org/simple/pycparser/>
	  <Candidate pycparser 2.14 from https://pypi.org/simple/pycparser/>
	  <Candidate pycparser 2.13 from https://pypi.org/simple/pycparser/>
	  <Candidate pycparser 2.12 from https://pypi.org/simple/pycparser/>
	  ... [13 more candidate(s)]
Resolving: new pin cffi 1.15.0
======== Ending round 5 ========
======== Starting round 6 ========
Resolving: new pin greenlet 1.1.2
======== Ending round 6 ========
======== Starting round 7 ========
Resolving: new pin pycparser 2.21
======== Ending round 7 ========
======== Starting round 8 ========
======== Resolution Result ========
Stable pins:
          python None
          gevent 21.12.0
      setuptools 60.5.0
      zope.event 4.5.0
  zope.interface 5.4.0
            cffi 1.15.0
        greenlet 1.1.2
       pycparser 2.21
	Found matching candidates:
	  <Candidate gevent 21.12.0 from https://pypi.org/simple/gevent/>
	Found matching candidates:
	  <Candidate setuptools 60.5.0 from https://pypi.org/simple/setuptools/>
	Found matching candidates:
	  <Candidate zope.event 4.5.0 from https://pypi.org/simple/zope-event/>
	Found matching candidates:
	  <Candidate zope.interface 5.4.0 from https://pypi.org/simple/zope-interface/>
	Found matching candidates:
	  <Candidate cffi 1.15.0 from https://pypi.org/simple/cffi/>
	Found matching candidates:
	  <Candidate greenlet 1.1.2 from https://pypi.org/simple/greenlet/>
	Found matching candidates:
	  <Candidate pycparser 2.21 from https://pypi.org/simple/pycparser/>
🔒 Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
Traceback (most recent call last):
  File "/usr/local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/usr/local/Cellar/pdm/1.12.3/libexec/lib/python3.10/site-packages/pdm/core.py", line 219, in main
    return Core().main(args)
  File "/usr/local/Cellar/pdm/1.12.3/libexec/lib/python3.10/site-packages/pdm/core.py", line 161, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/usr/local/Cellar/pdm/1.12.3/libexec/lib/python3.10/site-packages/pdm/core.py", line 156, in main
    f(options.project, options)
  File "/usr/local/Cellar/pdm/1.12.3/libexec/lib/python3.10/site-packages/pdm/cli/commands/add.py", line 53, in handle
    actions.do_add(
  File "/usr/local/Cellar/pdm/1.12.3/libexec/lib/python3.10/site-packages/pdm/cli/actions.py", line 246, in do_add
    do_sync(
  File "/usr/local/Cellar/pdm/1.12.3/libexec/lib/python3.10/site-packages/pdm/cli/actions.py", line 174, in do_sync
    candidates = resolve_candidates_from_lockfile(project, requirements)
  File "/usr/local/Cellar/pdm/1.12.3/libexec/lib/python3.10/site-packages/pdm/cli/actions.py", line 121, in resolve_candidates_from_lockfile
    mapping, *_ = resolve(
  File "/usr/local/Cellar/pdm/1.12.3/libexec/lib/python3.10/site-packages/pdm/resolver/core.py", line 31, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "/usr/local/Cellar/pdm/1.12.3/libexec/lib/python3.10/site-packages/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/local/Cellar/pdm/1.12.3/libexec/lib/python3.10/site-packages/resolvelib/resolvers.py", line 385, in resolve
    raise ResolutionImpossible(self.state.backtrack_causes)
resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=NamedRequirement(name='zope.event', marker=None, extras=(), specifier=<SpecifierSet('')>, editable=False, prerelease=False), parent=<Candidate gevent 21.12.0 from unknown>)]
```

## Expected behavior

Should add without error.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:

```sh
pdm info && pdm info --env
PDM version:        1.12.3
Python Interpreter: /usr/local/Cellar/pdm/1.12.3/libexec/bin/python3.10 (3.10)
Project Root:       /Users/xxx/Documents/Work/pdm-gevent-test
Project Packages:   /Users/xxx/Documents/Work/pdm-gevent-test/__pypackages__/3.10
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.1",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "20.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64",
  "python_full_version": "3.10.1",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
Sorry for that, it has been fixed in 1.12.5
