### ISSUE TITLE
pdm 1.12.6 fails to install catboost 1.0.0 - 1.0.4

### ISSUE THREAD

**Issue by marowu** [pdm-project/pdm#857]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

I've first noticed the issue trying to build the environment for my project with many dependencies, but it turns out the same issue arises when catboost is the only dependency.

## Steps to reproduce
It is enough to run `pdm init` in an empty directory and later `pdm add catboost`. I've tried specific versions of the catboost library (1.0.0 - 1.0.4) but the result is always the same.

## Actual behavior
PDM is able to install all the necessary dependencies of catboost, but fails to install catboost library.
```
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\user\AppData\Roaming\pdm\venv\lib\site-packages\pdm\installers\synchronizers.py", line 190, in install_candidate
    self.manager.install(can)
  File "C:\Users\user\AppData\Roaming\pdm\venv\lib\site-packages\pdm\installers\manager.py", line 38, in install
    installer(candidate.build(), self.environment, candidate.direct_url())
  File "C:\Users\user\AppData\Roaming\pdm\venv\lib\site-packages\pdm\installers\installers.py", line 176, in install_wheel
  File "C:\Users\user\AppData\Roaming\pdm\venv\lib\site-packages\pdm\installers\installers.py", line 280, in _install_wheel
  File "C:\Users\user\AppData\Roaming\pdm\venv\lib\site-packages\installer\sources.py", line 170, in get_contents
    assert record is not None, "In {}, {} is not mentioned in RECORD".format(
AssertionError: In C:\Users\user\AppData\Local\Temp\pip-unpack-a3gqvydj\catboost-1.0.4-cp39-none-win_amd64.whl, catboost/core.py is not mentioned in RECORD
```
## Expected behavior
PDM should successfully install catboost as it is the case with other tools such as pip or poetry.

## Environment Information
```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.12.6
Python Interpreter: C:/Users/user/AppData/Local/Programs/Python/Python39/python.EXE (3.9)
Project Root:       C:/Users/user/Documents/pdm
Project Packages:   C:\Users\user\Documents\pdm\__pypackages__\3.9

{
  "implementation_name": "cpython",
  "implementation_version": "3.9.9",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19042",
  "python_full_version": "3.9.9",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "win32"
}
```

**Comment by frostming** [comment]
Try `PYTHONOPTIMIZE=1 pdm install` to bypass the assertion errors
