### ISSUE TITLE
pdm 1.12.6 failed on `pmd add sshconf`, but `pip install` success (with `versiontag` in setup.py)

### ISSUE THREAD

**Issue by alingse** [pdm-project/pdm#860]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce
```
mkdir temp && cd temp
pdm init
pdm add sshconf -v
```
python3.8 / python3.10.2 all failed

## Actual behavior
```
  File "/var/folders/8v/j6mqk_2155d_1kk17ng2cnyh0000gn/T/pdm-build-env-41vgzgox-shared/lib/python3.10/site-packages/setuptools/build_meta.py", line 158, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 3, in <module>
    Distribution().fetch_build_eggs('versiontag')
  File "/var/folders/8v/j6mqk_2155d_1kk17ng2cnyh0000gn/T/pdm-build-env-41vgzgox-shared/lib/python3.10/site-packages/setuptools/dist.py", line 812, in fetch_build_eggs
    resolved_dists = pkg_resources.working_set.resolve(
  File "/var/folders/8v/j6mqk_2155d_1kk17ng2cnyh0000gn/T/pdm-build-env-41vgzgox-shared/lib/python3.10/site-packages/pkg_resources/__init__.py", line 771, in resolve
    dist = best[req.key] = env.best_match(
  File "/var/folders/8v/j6mqk_2155d_1kk17ng2cnyh0000gn/T/pdm-build-env-41vgzgox-shared/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1056, in best_match
    return self.obtain(req, installer)
  File "/var/folders/8v/j6mqk_2155d_1kk17ng2cnyh0000gn/T/pdm-build-env-41vgzgox-shared/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1068, in obtain
    return installer(requirement)
  File "/var/folders/8v/j6mqk_2155d_1kk17ng2cnyh0000gn/T/pdm-build-env-41vgzgox-shared/lib/python3.10/site-packages/setuptools/dist.py", line 883, in fetch_build_egg
    return fetch_build_egg(self, req)
  File "/var/folders/8v/j6mqk_2155d_1kk17ng2cnyh0000gn/T/pdm-build-env-41vgzgox-shared/lib/python3.10/site-packages/setuptools/installer.py", line 84, in fetch_build_egg
    raise DistutilsError(str(e)) from e
distutils.errors.DistutilsError: Command '['/usr/local/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/8v/j6mqk_2155d_1kk17ng2cnyh0000gn/T/tmphzc3o641', '--quiet', 'versiontag']' returned non-zero exit status 1.
```
## Environment Information

```bash
$ pdm info && pdm info --env                                                                                                1 ↵
PDM version:        1.12.6
Python Interpreter: /usr/local/bin/python3 (3.10)
Project Root:       /Users/xxx/output/temp
Project Packages:   /Users/xxx/output/temp/__pypackages__/3.10
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.2",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "20.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64",
  "python_full_version": "3.10.2",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "darwin"
}
```

## What I guess and what I do

the top 10 line code of sshconf [setup.py](https://github.com/sorend/sshconf/blob/master/setup.py) is
```python
from setuptools import setup, Distribution
Distribution().fetch_build_eggs('versiontag')
from versiontag import get_version, cache_git_tag

cache_git_tag()

MY_VERSION = get_version(pypi=True)
```
### 1
the error occurs in `fetch_build_eggs`, so I try run `pdm add versiontag` before run `pdm add sshconf`, but also failed.

### 2
And I run the command
```
/usr/local/bin/python3 -m pip --disable-pip-version-check wheel --no-deps -w ./abcd --quiet versiontag
```
got success with `versiontag-1.2.0-py2.py3-none-any.whl` in the new folder `./abcd`

so I don't know why it failed ?

**Comment by alingse** [comment]
```
Successfully installed setuptools-60.5.0 wheel-0.37.1
WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
/var/folders/8v/j6mqk_2155d_1kk17ng2cnyh0000gn/T/pdm-build-env-5y2cvw_0-shared/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
  warnings.warn(
/usr/local/bin/python3: No module named pip
Traceback (most recent call last):
  File "/var/folders/8v/j6mqk_2155d_1kk17ng2cnyh0000gn/T/pdm-build-env-5y2cvw_0-shared/lib/python3.10/site-packages/setuptools/installer.py", line 82, in fetch_build_egg
    subprocess.check_call(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/8v/j6mqk_2155d_1kk17ng2cnyh0000gn/T/tmp90tozco9', '--quiet', 'versiontag']' returned non-zero exit status 1.
```

Is this the root cause `/usr/local/bin/python3: No module named pip` ?

**Comment by frostming** [comment]
The setup.py shows it depends on `pytest-runner`.

Try this solution:
```bash
pdm add pytest-runner
pdm add --no-isolation sshconf -v
```

**Comment by alingse** [comment]
thx, solved, remove pytest-runner in setup.py  https://github.com/sorend/sshconf/pull/11 

it look like `setup_requires ` was deprecated

**Comment by alingse** [comment]
I use gdb to  debug `pdm add sshconf -v` install process, I think the root cause was `/usr/local/bin/python3: No module named pip`


pdm  download sshconf , compile  and run `setup.py`

this code:
```python
from setuptools import setup, Distribution
Distribution().fetch_build_eggs('versiontag')
```
and the sys.path was
```python
['/private/var/folders/8v/j6mqk_2155d_1kk17ng2cnyh0000gn/T/pdm-build-dcit6nti',
 '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pep517/in_process',
 '/var/folders/8v/j6mqk_2155d_1kk17ng2cnyh0000gn/T/pdm-build-env-hn_ahq9h-shared/site',
 '/Library/Frameworks/Python.framework/Versions/3.10/lib/python310.zip',
 '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10',
 '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/lib-dynload',
 '/var/folders/8v/j6mqk_2155d_1kk17ng2cnyh0000gn/T/pdm-build-env-x7byzht4-overlay/lib/python3.10/site-packages',
 '/var/folders/8v/j6mqk_2155d_1kk17ng2cnyh0000gn/T/pdm-build-env-x7byzht4-overlay/lib/python3.10/site-packages',
 '/var/folders/8v/j6mqk_2155d_1kk17ng2cnyh0000gn/T/pdm-build-env-hn_ahq9h-shared/lib/python3.10/site-packages']
```
there is no pip package in any sys.path

```
distutils.errors.DistutilsError: Command '['/usr/local/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/8v/j6mqk_2155d_1kk17ng2cnyh0000gn/T/tmp64l_16tj', '--quiet', 'versiontag']' returned non-zero exit status 1.
```

🤔  The big problem is that `setuptools` dependents on pip not pdm， can we mock it ？

**Comment by frostming** [comment]
PEP 517 recommends specifying any dependencies explicitly beforehand, and no new packages will be installed afterward.
If your install script really requires `pip`(I think you can get rid of it). you can include it in `pyproject.toml` / `[build-system]` / `requires` field.
