### ISSUE TITLE
Fail to run 'pdm init'

### ISSUE THREAD

**Issue by Green-li** [pdm-project/pdm#866]
- I have searched the issue tracker and believe that this is not a duplicate.

搜了一下并没有相关的报错，其他人的报错都是已经init之后，在安装包的时候。
但是我init的时候就失败了，一定要使用root权限吗？没有root的权限的用户如何安装呢？
>The problems which I found about `PermissionError` are all related with 'install packages.' But I get the errors when I run the command `pdm init`. Should I must have the root permission? How to init without root permission?

## Steps to reproduce
I used the following command to install `pdm`:
```curl -sSL https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py | python3 -```
The `python3` is the conda venv(python3.8)
But when  I run `pdm init`,I get the following errors:
```
(py38)➜ pdm init -v
Creating a pyproject.toml for PDM...
Traceback (most recent call last):
  File "/home/username/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/username/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/core.py", line 219, in main
    return Core().main(args)
  File "/home/username/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/core.py", line 161, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/home/username/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/core.py", line 156, in main
    f(options.project, options)
  File "/home/username/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/cli/commands/init.py", line 45, in handle
    actions.do_use(project)
  File "/home/username/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/cli/actions.py", line 551, in do_use
    found_interpreters = list(dict.fromkeys(project.find_interpreters(python)))
  File "/home/username/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/project/core.py", line 636, in find_interpreters
    for entry in finder.find_all_python_versions(*args):
  File "/home/username/.local/share/pdm/venv/lib/python3.8/site-packages/pythonfinder/pythonfinder.py", line 312, in find_all_python_versions
    python_version_dict = getattr(self.system_path, "python_version_dict", {})
  File "/home/username/.local/share/pdm/venv/lib/python3.8/site-packages/pythonfinder/pythonfinder.py", line 120, in system_path
    self._system_path = self.create_system_path()
  File "/home/username/.local/share/pdm/venv/lib/python3.8/site-packages/pythonfinder/pythonfinder.py", line 82, in create_system_path
    return pyfinder_path.SystemPath.create(
  File "/home/username/.local/share/pdm/venv/lib/python3.8/site-packages/pythonfinder/models/path.py", line 667, in create
    {
  File "/home/username/.local/share/pdm/venv/lib/python3.8/site-packages/pythonfinder/models/path.py", line 672, in <dictcomp>
    if p.exists()
  File "/home/username/venvs/py38/lib/python3.8/pathlib.py", line 1407, in exists
    self.stat()
  File "/home/username/venvs/py38/lib/python3.8/pathlib.py", line 1198, in stat
    return self._accessor.stat(self)
PermissionError: [Errno 13] Permission denied: '/root/bin'
```

## Actual behavior

above.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
(py38)➜  pdm info && pdm info --env
[ProjectError]: The pyproject.toml has not been initialized yet. You can do this by running 'pdm init'.
```

So why get this errors ?

**Comment by frostming** [comment]
`/root/bin` has no read permission, you need to remove it from `PATH` env var.

**Comment by Green-li** [comment]
> `/root/bin` has no read permission, you need to remove it from `PATH` env var.

Thanks. It works!
I think maybe It can skip all path dirs without permission and throw a warning instead of an errors.

**Comment by dingobar** [comment]
I faced this error, turns out a lot of paths on my Windows $PATH didn't exist. Don't see why that would stop pdm from working though.

**Comment by douglasstarnes** [comment]
I'm having this error inside of WSL2. For some reason `pdm init` is attempting to access this directory `/mnt/c/Windows/system32/config/systemprofile/AppData/Local/Microsoft/WindowsApps` but it doesn't exist. And I am showing hidden files and folders. Tried running with `-v` and didn't get anything outside of the error.

**Comment by dingobar** [comment]
> I'm having this error inside of WSL2. For some reason `pdm init` is attempting to access this directory `/mnt/c/Windows/system32/config/systemprofile/AppData/Local/Microsoft/WindowsApps` but it doesn't exist. And I am showing hidden files and folders. Tried running with `-v` and didn't get anything outside of the error.

Solution is to remove all nonexistent folders from your PATH
