### ISSUE TITLE
pdm plugin config is not cleaned up after removal

### ISSUE THREAD

**Issue by xanterx** [pdm-project/pdm#872]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

```bash
❯ pdm plugin add pdm-venv
✔ Installation succeeds.
❯ pdm config venv.in_project True
❯ pdm plugin remove pdm-venv -y
✔ Uninstallation succeeds.
❯ pdm config -v
...
  Traceback (most recent call last):
  File "/Users/*/Library/Python/3.10/bin/pdm", line 10, in <module>
    sys.exit(main())
  File "/Users/*/Library/Application Support/pdm/venv/lib/python3.10/site-packages/pdm/core.py", line 219, in main
    return Core().main(args)
  File "/Users/*/Library/Application Support/pdm/venv/lib/python3.10/site-packages/pdm/core.py", line 161, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/Users/*/Library/Application Support/pdm/venv/lib/python3.10/site-packages/pdm/core.py", line 156, in main
    f(options.project, options)
  File "/Users/*/Library/Application Support/pdm/venv/lib/python3.10/site-packages/pdm/cli/commands/config.py", line 32, in handle
    self._list_config(project, options)
  File "/Users/*/Library/Application Support/pdm/venv/lib/python3.10/site-packages/pdm/cli/commands/config.py", line 48, in _list_config
    "# " + project.global_config._config_map[key].description
KeyError: 'venv.in_project'
```

## Actual behavior

After executing `pdm plugin remove <plugin_name>`, if the plugin has added some configuration to pdm and user has updated any of those configurations, it creates an entry either in local or global **config.toml** based on the user flag used. These config entries stay persistent and then lead to this `KeyError`.

## Expected behavior

After executing `pdm plugin remove <plugin_name>` all the plugin config should also be cleaned up.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.12.6
Python Interpreter: /usr/local/opt/python@3.10/bin/python3.10 (3.10)
Project Root:       /Users/*/demo
Project Packages:   /Users/*/demo/__pypackages__/3.10
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.1",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "20.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 20.6.0: Wed Jan 12 22:22:42 PST 2022; root:xnu-7195.141.19~2/RELEASE_X86_64",
  "python_full_version": "3.10.1",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "darwin"
}
```

**Comment by xanterx** [comment]
A quick resolution is to remove these configurations manually from global or local config files, based on in whichever level you have modified the pdm config.

- Global : `~/.pdm/config.toml`
- Project Local: `./.pdm.toml`

**Comment by frostming** [comment]
Instead of cleaning up, IMO ignoring the redundant config items is just fine.

**Comment by xanterx** [comment]
That also make sense it will resolve the above error and will also keep the setting persistent across uninstall/installs.
