### ISSUE TITLE
Install PDM fails with macos system python3, PermissionError

### ISSUE THREAD

**Issue by acethical** [pdm-project/pdm#877]
- [ ] I have searched the issue tracker and believe that this is not a duplicate.

### python3 installed with Xcode Command Line Tools

\> `which python3`
`/usr/bin/python3`
\> `python3 --version`
`/Python 3.8.9`

### Install PDM failed, with PermissionError

\> `curl -sSL https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py | python3 -`
```python
Installing PDM (1.12.7): Creating virtual environment
Traceback (most recent call last):
  File "<stdin>", line 430, in <module>
  File "<stdin>", line 426, in main
  File "<stdin>", line 351, in install
  File "<stdin>", line 251, in _make_env
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/venv/__init__.py", line 391, in create
    builder.create(env_dir)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/venv/__init__.py", line 66, in create
    self.setup_python(context)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/venv/__init__.py", line 234, in setup_python
    copier(context.executable, path)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/venv/__init__.py", line 177, in symlink_or_copy
    shutil.copyfile(src, dst)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '~/Library/Application Support/pdm/venv/bin/python3'
```
### Tried solve 1, referenced with [#536](https://github.com/pdm-project/pdm/issues/536#issuecomment-877938811) 

\> `python3 -m venv temp_venv`
\> `curl -sSL https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py | python3 -`
-> same PermissionError issue as above

### Tried solve 2, use `sudo` before `curl`

\> `sudo curl -sSL https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py | python3 -`
-> same PermissionError issue as above

### Tried solve 3, use `sudo` before `python3`

This way broke python3, have to reinstall python3 with Xcode Command Line Tools

\> `curl -sSL https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py | sudo python3 -`
```python
Installing PDM (1.12.7): Creating virtual environment
An error occurred when executing ['/Library/Developer/CommandLineTools/usr/bin/python3', '/tmp/pdm-installer-jdi72a60/virtualenv.pyz', '~/Library/Application Support/pdm/venv']:
dyld[13853]: Library not loaded: @executable_path/../Python3
  Referenced from: /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/Resources/Python.app/Contents/MacOS/Python
  Reason: tried: '/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/Resources/Python.app/Contents/MacOS/../Python3' (no such file), '/usr/local/lib/Python3' (no such file), '/usr/lib/Python3' (no such file)
```

\> `python3`
```python
dyld[13867]: Library not loaded: @executable_path/../Python3
  Referenced from: /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/Resources/Python.app/Contents/MacOS/Python
  Reason: tried: '/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/Resources/Python.app/Contents/MacOS/../Python3' (no such file), '/usr/local/lib/Python3' (no such file), '/usr/lib/Python3' (no such file)
fish: Job 1, 'python3' terminated by signal SIGABRT (Abort)
```

## Actual behavior

Error

## Expected behavior

Install PDM successfully.

## Environment Information

macOS 12.2 Monterey
python 3.8.9
[fish shell](https://github.com/fish-shell/fish-shell/) 3.3.1

### Full verbose log

\> `curl -sSL https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py | python3 -v`
```python
...omitted...
import 'unicodedata' # <_frozen_importlib_external.ExtensionFileLoader object at 0x10f9fa520>
import 'stringprep' # <_frozen_importlib_external.SourceFileLoader object at 0x10f9e1c70>
import 'encodings.idna' # <_frozen_importlib_external.SourceFileLoader object at 0x10f9e16a0>
Installing PDM (1.12.7): Creating virtual environment
# ~/Library/Caches/com.apple.python/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/venv/__init__.cpython-38.pyc matches /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/venv/__init__.py
# code object from '~/Library/Caches/com.apple.python/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/venv/__init__.cpython-38.pyc'
# ~/Library/Caches/com.apple.python/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/logging/__init__.cpython-38.pyc matches /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/logging/__init__.py
# code object from '~/Library/Caches/com.apple.python/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/logging/__init__.cpython-38.pyc'
# ~/Library/Caches/com.apple.python/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/traceback.cpython-38.pyc matches /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/traceback.py
# code object from '~/Library/Caches/com.apple.python/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/traceback.cpython-38.pyc'
import 'traceback' # <_frozen_importlib_external.SourceFileLoader object at 0x10fa7cd60>
import 'atexit' # <class '_frozen_importlib.BuiltinImporter'>
import 'logging' # <_frozen_importlib_external.SourceFileLoader object at 0x10f9fa3a0>
# ~/Library/Caches/com.apple.python/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/sysconfig.cpython-38.pyc matches /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/sysconfig.py
# code object from '~/Library/Caches/com.apple.python/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/sysconfig.cpython-38.pyc'
import 'sysconfig' # <_frozen_importlib_external.SourceFileLoader object at 0x10f9faa90>
import 'venv' # <_frozen_importlib_external.SourceFileLoader object at 0x10ef420a0>
Traceback (most recent call last):
  File "<stdin>", line 430, in <module>
  File "<stdin>", line 426, in main
  File "<stdin>", line 351, in install
  File "<stdin>", line 251, in _make_env
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/venv/__init__.py", line 391, in create
    builder.create(env_dir)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/venv/__init__.py", line 66, in create
    self.setup_python(context)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/venv/__init__.py", line 234, in setup_python
    copier(context.executable, path)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/venv/__init__.py", line 177, in symlink_or_copy
    shutil.copyfile(src, dst)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '~/Library/Application Support/pdm/venv/bin/python3'
# clear builtins._
# clear sys.path
# clear sys.argv
...omitted...
```

**Comment by acethical** [comment]
I also referenced [#793](https://github.com/pdm-project/pdm/issues/793), thought it may be some kind of macos system python issue.
But due to different Error prompt and #793 has been reloved, I decided to open a new issue ticket.

**Comment by pawamoy** [comment]
- Retry 1: you created a venv but didn't activate it or use it when installing pdm
- Retry 2: there's no point in doing sudo curl :)
- Retry 3: you shouldn't need sudo. I'll let @frostming confirm but doing that possibly messed up some permissions in `~/Library/Application Support`.

Try fixing permissions on this directory with chown and chmod commands.
Or try again solution 1:

```bash
python3 -m venv .venv
. .venv/bin/activate
curl ... | python -
```

**Comment by acethical** [comment]
@pawamoy Thank you.

I tried solution 1, but still the same error
```python
(.venv) bash-3.2$ curl -sSL https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py | python3 -
Installing PDM (1.12.7): Creating virtual environment
Traceback (most recent call last):
  File "<stdin>", line 430, in <module>
  File "<stdin>", line 426, in main
  File "<stdin>", line 351, in install
  File "<stdin>", line 251, in _make_env
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/venv/__init__.py", line 391, in create
    builder.create(env_dir)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/venv/__init__.py", line 66, in create
    self.setup_python(context)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/venv/__init__.py", line 234, in setup_python
    copier(context.executable, path)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/venv/__init__.py", line 177, in symlink_or_copy
    shutil.copyfile(src, dst)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '~/Library/Application Support/pdm/venv/bin/python3'
```

About the solution 3, it seems I even can't change the owner nor permissions.
\> `sudo chown myusername /Library/Application\ Support/`
`chown: /Library/Application Support/: Operation not permitted`

\> `sudo chmod 777 /Library/Application\ Support/`
`chmod: Unable to change file mode on /Library/Application Support/: Operation not permitted`

**Comment by q0w** [comment]
@acethical Whats the pip version?

**Comment by acethical** [comment]
@q0w
`pip 20.2.3 from /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip (python 3.8)`

**Comment by acethical** [comment]
@frostming Thank you.
Sorry I mixed up `~/Library/Application Support/` with `/Library/Application Support/`.
I have deleted `'~/Library/Application Support/pdm/venv/bin/python3'`, and retry to install PDM.
But there seems another error, I didn't find out useful info from google, there is verbose log.
\> `curl -sSL https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py | python3 -v`
```python
import 'unicodedata' # <_frozen_importlib_external.ExtensionFileLoader object at 0x10daf24f0>
import 'stringprep' # <_frozen_importlib_external.SourceFileLoader object at 0x10dadcc40>
import 'encodings.idna' # <_frozen_importlib_external.SourceFileLoader object at 0x10dadc670>
Installing PDM (1.12.7): Creating virtual environment
# ~/Library/Caches/com.apple.python/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/venv/__init__.cpython-38.pyc matches /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/venv/__init__.py
# code object from '~/Library/Caches/com.apple.python/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/venv/__init__.cpython-38.pyc'
# ~/Library/Caches/com.apple.python/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/logging/__init__.cpython-38.pyc matches /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/logging/__init__.py
# code object from '~/Library/Caches/com.apple.python/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/logging/__init__.cpython-38.pyc'
# ~/Library/Caches/com.apple.python/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/traceback.cpython-38.pyc matches /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/traceback.py
# code object from '~/Library/Caches/com.apple.python/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/traceback.cpython-38.pyc'
import 'traceback' # <_frozen_importlib_external.SourceFileLoader object at 0x10db7ad30>
import 'atexit' # <class '_frozen_importlib.BuiltinImporter'>
import 'logging' # <_frozen_importlib_external.SourceFileLoader object at 0x10daf2370>
# ~/Library/Caches/com.apple.python/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/sysconfig.cpython-38.pyc matches /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/sysconfig.py
# code object from '~/Library/Caches/com.apple.python/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/sysconfig.cpython-38.pyc'
import 'sysconfig' # <_frozen_importlib_external.SourceFileLoader object at 0x10daf2a60>
import 'venv' # <_frozen_importlib_external.SourceFileLoader object at 0x10d03c0a0>
An error occurred when executing ['~/.venv/bin/python3', '/var/folders/dd/mtyvg5v96j39g596s_3kdzb40000gn/T/pdm-installer-5jzepvq6/virtualenv.pyz', '~/Library/Application Support/pdm/venv']:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/var/folders/dd/mtyvg5v96j39g596s_3kdzb40000gn/T/pdm-installer-5jzepvq6/virtualenv.pyz/__main__.py", line 167, in <module>
  File "/var/folders/dd/mtyvg5v96j39g596s_3kdzb40000gn/T/pdm-installer-5jzepvq6/virtualenv.pyz/__main__.py", line 163, in run
  File "/var/folders/dd/mtyvg5v96j39g596s_3kdzb40000gn/T/pdm-installer-5jzepvq6/virtualenv.pyz/virtualenv/__main__.py", line 18, in run
  File "/var/folders/dd/mtyvg5v96j39g596s_3kdzb40000gn/T/pdm-installer-5jzepvq6/virtualenv.pyz/virtualenv/run/__init__.py", line 30, in cli_run
  File "/var/folders/dd/mtyvg5v96j39g596s_3kdzb40000gn/T/pdm-installer-5jzepvq6/virtualenv.pyz/virtualenv/run/__init__.py", line 48, in session_via_cli
  File "/var/folders/dd/mtyvg5v96j39g596s_3kdzb40000gn/T/pdm-installer-5jzepvq6/virtualenv.pyz/virtualenv/run/__init__.py", line 70, in build_parser
  File "/var/folders/dd/mtyvg5v96j39g596s_3kdzb40000gn/T/pdm-installer-5jzepvq6/virtualenv.pyz/virtualenv/discovery/discover.py", line 45, in interpreter
  File "/var/folders/dd/mtyvg5v96j39g596s_3kdzb40000gn/T/pdm-installer-5jzepvq6/virtualenv.pyz/virtualenv/discovery/builtin.py", line 47, in run
  File "/var/folders/dd/mtyvg5v96j39g596s_3kdzb40000gn/T/pdm-installer-5jzepvq6/virtualenv.pyz/virtualenv/discovery/builtin.py", line 65, in get_interpreter
  File "/var/folders/dd/mtyvg5v96j39g596s_3kdzb40000gn/T/pdm-installer-5jzepvq6/virtualenv.pyz/virtualenv/discovery/builtin.py", line 96, in propose_interpreters
  File "/var/folders/dd/mtyvg5v96j39g596s_3kdzb40000gn/T/pdm-installer-5jzepvq6/virtualenv.pyz/virtualenv/discovery/py_info.py", line 355, in from_exe
  File "/var/folders/dd/mtyvg5v96j39g596s_3kdzb40000gn/T/pdm-installer-5jzepvq6/virtualenv.pyz/virtualenv/discovery/py_info.py", line 352, in from_exe
  File "/var/folders/dd/mtyvg5v96j39g596s_3kdzb40000gn/T/pdm-installer-5jzepvq6/virtualenv.pyz/virtualenv/discovery/py_info.py", line 390, in _resolve_to_system
  File "/var/folders/dd/mtyvg5v96j39g596s_3kdzb40000gn/T/pdm-installer-5jzepvq6/virtualenv.pyz/virtualenv/discovery/py_info.py", line 411, in discover_exe
  File "/var/folders/dd/mtyvg5v96j39g596s_3kdzb40000gn/T/pdm-installer-5jzepvq6/virtualenv.pyz/virtualenv/discovery/py_info.py", line 428, in _check_exe
  File "/var/folders/dd/mtyvg5v96j39g596s_3kdzb40000gn/T/pdm-installer-5jzepvq6/virtualenv.pyz/virtualenv/discovery/py_info.py", line 348, in from_exe
  File "/var/folders/dd/mtyvg5v96j39g596s_3kdzb40000gn/T/pdm-installer-5jzepvq6/virtualenv.pyz/virtualenv/discovery/cached_py_info.py", line 28, in from_exe
  File "/var/folders/dd/mtyvg5v96j39g596s_3kdzb40000gn/T/pdm-installer-5jzepvq6/virtualenv.pyz/virtualenv/discovery/cached_py_info.py", line 45, in _get_from_cache
  File "/var/folders/dd/mtyvg5v96j39g596s_3kdzb40000gn/T/pdm-installer-5jzepvq6/virtualenv.pyz/virtualenv/discovery/cached_py_info.py", line 75, in _get_via_file_cache
  File "/var/folders/dd/mtyvg5v96j39g596s_3kdzb40000gn/T/pdm-installer-5jzepvq6/virtualenv.pyz/virtualenv/discovery/cached_py_info.py", line 86, in _run_subprocess
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/var/folders/dd/mtyvg5v96j39g596s_3kdzb40000gn/T/pdm-installer-5jzepvq6/virtualenv.pyz/virtualenv/app_data/base.py", line 58, in ensure_extracted
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/var/folders/dd/mtyvg5v96j39g596s_3kdzb40000gn/T/pdm-installer-5jzepvq6/virtualenv.pyz/virtualenv/app_data/via_disk_folder.py", line 83, in extract
  File "/var/folders/dd/mtyvg5v96j39g596s_3kdzb40000gn/T/pdm-installer-5jzepvq6/virtualenv.pyz/virtualenv/util/zipapp.py", line 22, in extract
    
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/zipfile.py", line 1441, in getinfo
    raise KeyError(
KeyError: "There is no item named 'nv/discovery/py_info.py' in the archive"

# clear builtins._
# clear sys.path
# clear sys.argv
# clear sys.ps1
# clear sys.ps2
```

**Comment by frostming** [comment]
What about not creating a venv for the script, just use `python3` to execute it?

**Comment by acethical** [comment]
> What about not creating a venv for the script, just use `python3` to execute it? Also the command can be broken into two steps:
> 
> ```
> curl -sSLO https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py
> python3 install-pdm.py
> ```
It still finished with the `PermissionError` , likes the first issue.
After I delete '~/Library/Application Support/pdm/venv/bin/python3' as [replay](https://github.com/pdm-project/pdm/issues/877#issuecomment-1028005262) mentioned , it ended with `KeyError: "There is no item named 'nv/create/via_global_ref/_virtualenv.py' in the archive"`

And I noticed, if I run `python3 install-pdm.py` it always ended with `PermissionError`,
only if I delete '~/Library/Application Support/pdm/venv/bin/python3', the next `python3 install-pdm.py` will end with `KeyError`.

**Comment by frostming** [comment]
Well, let's break down the steps to see where the problem is, first ensure `~/Library/Application Support/pdm` is deleted.
```
mkdir ~/Library/Application Support/pdm
python3 -m venv ~/Library/Application Support/pdm/venv
```
Successful or failing?

**Comment by acethical** [comment]
It's ok, created `venv` folder successfully.
