### ISSUE TITLE
PDM init fails after reinstall

### ISSUE THREAD

**Issue by robml** [pdm-project/pdm#891]
- [ TRUE] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Reinstalled pdm while experimenting, afterwards every time I tried to init, the error would bring back an old project I had deleted previously, I couldn't find where to fix it in the traceback.

## Actual behavior

```
Traceback (most recent call last):
  File "/home/robmel/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/robmel/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/core.py", line 226, in main
    return Core().main(args)
  File "/home/robmel/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/core.py", line 161, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/home/robmel/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/core.py", line 156, in main
    f(options.project, options)
  File "/home/robmel/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/cli/commands/init.py", line 45, in handle
    actions.do_use(project)
  File "/home/robmel/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/cli/actions.py", line 551, in do_use
    found_interpreters = list(dict.fromkeys(project.find_interpreters(python)))
  File "/home/robmel/.local/share/pdm/venv/lib/python3.8/site-packages/pdm/project/core.py", line 601, in find_interpreters
    for entry in finder.find_all_python_versions(*args):
  File "/home/robmel/.local/share/pdm/venv/lib/python3.8/site-packages/pythonfinder/pythonfinder.py", line 312, in find_all_python_versions
    python_version_dict = getattr(self.system_path, "python_version_dict", {})
  File "/home/robmel/.local/share/pdm/venv/lib/python3.8/site-packages/pythonfinder/pythonfinder.py", line 120, in system_path
    self._system_path = self.create_system_path()
  File "/home/robmel/.local/share/pdm/venv/lib/python3.8/site-packages/pythonfinder/pythonfinder.py", line 82, in create_system_path
    return pyfinder_path.SystemPath.create(
  File "/home/robmel/.local/share/pdm/venv/lib/python3.8/site-packages/pythonfinder/models/path.py", line 683, in create
    instance = instance._run_setup()
  File "/home/robmel/.local/share/pdm/venv/lib/python3.8/site-packages/pythonfinder/models/path.py", line 251, in _run_setup
    paths[p] = new_instance.get_path(p.joinpath(bin_dir))
  File "/home/robmel/.local/share/pdm/venv/lib/python3.8/site-packages/pythonfinder/models/path.py", line 439, in get_path
    raise ValueError("Path not found or generated: {0!r}".format(path))
ValueError: Path not found or generated: PosixPath('/home/robmel/.local/share/pdm/venvs/HTMX-mswRHr3d-3.9/bin')
```

## Expected behavior

Expected to create a new pmd project.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
[ProjectError]: The pyproject.toml has not been initialized yet. You can do this by running 'pdm init'
```

**Comment by frostming** [comment]
Deactivate the venv please

**Comment by robml** [comment]
The thing was there was no environment to deactivate. I opted to `mkdir` empty directories in the same structure, then `pdm init` would work. I added the `pdm-venv` plugin, and since I had the directories it appeared in the `list` feature, after removing it removed it successfully. I tried again by uninstalling/reinstalling `pdm` and I still got the same error as if nothing has changed. I don't mind working like this however I fear there is some modification in a file I am unaware of that will hurt my project as it grows larger. Any ideas?

**Comment by frostming** [comment]
```
echo $PATH
rm .pdm.toml
pdm init
```

**Comment by robml** [comment]
@frostming it was the $PATH! Still had an entry to the deleted directory. That seemed to resolve it. Thank you!

**Comment by robml** [comment]
@frostming I am curious by the way, since I don't fully understand pdm, does `pdm add` install the packages much like pip would?

**Comment by robml** [comment]
Thanks! Love the project so far!
