### ISSUE TITLE
Errors when installing packages importing `torch` in their setup script

### ISSUE THREAD

**Issue by classner** [pdm-project/pdm#913]
I am unable to install PyTorch3D (https://github.com/facebookresearch/pytorch3d) using PDM on Linux. Following their instructions, using pip it is as simple as running `pip install "git+https://github.com/facebookresearch/pytorch3d.git@stable"`. For pdm add, currently one has to still provide the egg name, but even after that the installation fails trying to `import torch` in the setup step.

I have installed torch in the basic Python installation (that PDM is part of); torch is also already added to the project environment.

- [X] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Install torch; run `pdm add "git+https://github.com/facebookresearch/pytorch3d.git@stable#egg=pytorch3d" -v`

## Actual behavior

PDM fails with the following log:

```
❯ pdm add "git+https://github.com/facebookresearch/pytorch3d.git@stable#egg=pytorch3d" -v
Adding packages to default dependencies: pytorch3d
======== Start resolving requirements ========
  click>=8.0.3
  coloredlogs>=15.0.1
  torch==1.10.1+cu113
  torchaudio==0.10.1+cu113
  hydra-core>=1.1.1
  pytorch-lightning>=1.5.7
  hydra-colorlog>=1.1.0
  kornia>=0.6.2
  pdbpp>=0.10.3
  ray[tune]>=1.9.2
  opencv-python==4.5.5.62
  opencv-contrib-python==4.5.5.62
  natsort>=8.0.2
  reportlab>=3.6.6
  imageio>=2.14.1
  FrEIA @ git+https://github.com/VLL-HD/FrEIA.git
  panda3d==1.10.10
  pytorch3d @ git+https://github.com/facebookresearch/pytorch3d.git@stable
  python>=3.9
  Adding requirement click>=8.0.3
        Found matching candidates:
          <Candidate click 8.0.3 from https://pypi.org/simple/click/>
  Adding requirement coloredlogs>=15.0.1
        Found matching candidates:
          <Candidate coloredlogs 15.0.1 from https://pypi.org/simple/coloredlogs/>
  Adding requirement torch==1.10.1+cu113
        Found matching candidates:
          <Candidate torch 1.10.1+cu113 from https://download.pytorch.org/whl/cu113/torch_stable.html>
  Adding requirement torchaudio==0.10.1+cu113
        Found matching candidates:
          <Candidate torchaudio 0.10.1+cu113 from https://download.pytorch.org/whl/cu113/torch_stable.html>
  Adding requirement hydra-core>=1.1.1
        Found matching candidates:
          <Candidate hydra-core 1.1.1 from https://pypi.org/simple/hydra-core/>
  Adding requirement pytorch-lightning>=1.5.7
        Found matching candidates:
          <Candidate pytorch-lightning 1.5.10 from https://pypi.org/simple/pytorch-lightning/>
          <Candidate pytorch-lightning 1.5.9 from https://pypi.org/simple/pytorch-lightning/>
          <Candidate pytorch-lightning 1.5.8 from https://pypi.org/simple/pytorch-lightning/>
          <Candidate pytorch-lightning 1.5.7 from https://pypi.org/simple/pytorch-lightning/>
  Adding requirement hydra-colorlog>=1.1.0
        Found matching candidates:
          <Candidate hydra-colorlog 1.1.0 from https://pypi.org/simple/hydra-colorlog/>
  Adding requirement kornia>=0.6.2
        Found matching candidates:
          <Candidate kornia 0.6.3 from https://pypi.org/simple/kornia/>
          <Candidate kornia 0.6.2 from https://pypi.org/simple/kornia/>
  Adding requirement pdbpp>=0.10.3
        Found matching candidates:
          <Candidate pdbpp 0.10.3 from https://pypi.org/simple/pdbpp/>
  Adding requirement ray[tune]>=1.9.2
        Found matching candidates:
          <Candidate ray 1.10.0 from https://pypi.org/simple/ray/>
          <Candidate ray 1.9.2 from https://pypi.org/simple/ray/>
  Adding requirement opencv-python==4.5.5.62
        Found matching candidates:
          <Candidate opencv-python 4.5.5.62 from https://pypi.org/simple/opencv-python/>
  Adding requirement opencv-contrib-python==4.5.5.62
        Found matching candidates:
          <Candidate opencv-contrib-python 4.5.5.62 from https://pypi.org/simple/opencv-contrib-python/>
  Adding requirement natsort>=8.0.2
        Found matching candidates:
          <Candidate natsort 8.1.0 from https://pypi.org/simple/natsort/>
          <Candidate natsort 8.0.2 from https://pypi.org/simple/natsort/>
  Adding requirement reportlab>=3.6.6
        Found matching candidates:
          <Candidate reportlab 3.6.6 from https://pypi.org/simple/reportlab/>
  Adding requirement imageio>=2.14.1
        Found matching candidates:
          <Candidate imageio 2.16.0 from https://pypi.org/simple/imageio/>
          <Candidate imageio 2.15.0 from https://pypi.org/simple/imageio/>
          <Candidate imageio 2.14.1 from https://pypi.org/simple/imageio/>
  Adding requirement FrEIA @ git+https://github.com/VLL-HD/FrEIA.git
Preparing isolated env for PEP 517 build...
Looking in links: https://download.pytorch.org/whl/cu113/torch_stable.html
Collecting wheel
  Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
Collecting setuptools>=40.8.0
  Using cached setuptools-60.9.1-py3-none-any.whl (1.1 MB)
Installing collected packages: wheel, setuptools
Successfully installed setuptools-60.9.1 wheel-0.37.1
WARNING: You are using pip version 21.3.1; however, version 22.0.3 is available.
You should consider upgrading via the '/home/anonymous/.pyenv/versions/3.9.6/bin/python3 -m pip install --upgrade pip' command.
running egg_info
writing FrEIA.egg-info/PKG-INFO
writing dependency_links to FrEIA.egg-info/dependency_links.txt
writing requirements to FrEIA.egg-info/requires.txt
writing top-level names to FrEIA.egg-info/top_level.txt
reading manifest file 'FrEIA.egg-info/SOURCES.txt'
adding license file 'LICENSE'
running dist_info
writing /tmp/pdm-meta-swa7wafv/FrEIA.egg-info/PKG-INFO
writing dependency_links to /tmp/pdm-meta-swa7wafv/FrEIA.egg-info/dependency_links.txt
writing requirements to /tmp/pdm-meta-swa7wafv/FrEIA.egg-info/requires.txt
writing top-level names to /tmp/pdm-meta-swa7wafv/FrEIA.egg-info/top_level.txt
reading manifest file '/tmp/pdm-meta-swa7wafv/FrEIA.egg-info/SOURCES.txt'
adding license file 'LICENSE'
creating '/tmp/pdm-meta-swa7wafv/FrEIA.dist-info'
adding license file "LICENSE" (matched pattern "LICEN[CS]E*")
  Adding requirement panda3d==1.10.10
        Found matching candidates:
          <Candidate panda3d 1.10.10 from https://pypi.org/simple/panda3d/>
  Adding requirement pytorch3d @ git+https://github.com/facebookresearch/pytorch3d.git@stable
Preparing isolated env for PEP 517 build...
Reusing shared build env: /tmp/pdm-build-env-8ttuyime-shared
Traceback (most recent call last):
  File "/home/anonymous/.pyenv/versions/3.9.6/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 363, in <module>
    main()
  File "/home/anonymous/.pyenv/versions/3.9.6/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 345, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/home/anonymous/.pyenv/versions/3.9.6/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/tmp/pdm-build-env-8ttuyime-shared/lib/python3.9/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
    return self._get_build_requires(
  File "/tmp/pdm-build-env-8ttuyime-shared/lib/python3.9/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
    self.run_setup()
  File "/tmp/pdm-build-env-8ttuyime-shared/lib/python3.9/site-packages/setuptools/build_meta.py", line 281, in run_setup
    super(_BuildMetaLegacyBackend,
  File "/tmp/pdm-build-env-8ttuyime-shared/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 14, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
Failed to build package, try parsing project files.
  Adding requirement python>=3.9
======== Starting round 0 ========
Resolving: new pin python >=3.9
======== Ending round 0 ========
======== Starting round 1 ========
  Adding requirement numpy>=1.15.0(from freia 0.2)
        Found matching candidates:
          <Candidate numpy 1.22.2 from https://pypi.org/simple/numpy/>
          <Candidate numpy 1.22.1 from https://pypi.org/simple/numpy/>
          <Candidate numpy 1.22.0 from https://pypi.org/simple/numpy/>
          <Candidate numpy 1.21.1 from https://pypi.org/simple/numpy/>
          <Candidate numpy 1.21.0 from https://pypi.org/simple/numpy/>
          <Candidate numpy 1.20.3 from https://pypi.org/simple/numpy/>
          <Candidate numpy 1.20.2 from https://pypi.org/simple/numpy/>
          <Candidate numpy 1.20.1 from https://pypi.org/simple/numpy/>
          <Candidate numpy 1.20.0 from https://pypi.org/simple/numpy/>
          <Candidate numpy 1.19.5 from https://pypi.org/simple/numpy/>
          ... [923 more candidate(s)]
  Adding requirement scipy>=1.5(from freia 0.2)
        Found matching candidates:
          <Candidate scipy 1.6.1 from https://pypi.org/simple/scipy/>
          <Candidate scipy 1.6.0 from https://pypi.org/simple/scipy/>
          <Candidate scipy 1.5.4 from https://pypi.org/simple/scipy/>
          <Candidate scipy 1.5.3 from https://pypi.org/simple/scipy/>
          <Candidate scipy 1.5.2 from https://pypi.org/simple/scipy/>
          <Candidate scipy 1.5.1 from https://pypi.org/simple/scipy/>
          <Candidate scipy 1.5.0 from https://pypi.org/simple/scipy/>
  Adding requirement torch>=1.0.0(from freia 0.2)
        Found matching candidates:
          <Candidate torch 1.10.1+cu113 from https://download.pytorch.org/whl/cu113/torch_stable.html>
Resolving: new pin freia 0.2
======== Ending round 1 ========
======== Starting round 2 ========
Traceback (most recent call last):
  File "/home/anonymous/.pyenv/versions/3.9.6/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/anonymous/.pyenv/versions/3.9.6/lib/python3.9/site-packages/pdm/core.py", line 226, in main
    return Core().main(args)
  File "/home/anonymous/.pyenv/versions/3.9.6/lib/python3.9/site-packages/pdm/core.py", line 161, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/home/anonymous/.pyenv/versions/3.9.6/lib/python3.9/site-packages/pdm/core.py", line 156, in main
    f(options.project, options)
  File "/home/anonymous/.pyenv/versions/3.9.6/lib/python3.9/site-packages/pdm/cli/commands/add.py", line 53, in handle
    actions.do_add(
  File "/home/anonymous/.pyenv/versions/3.9.6/lib/python3.9/site-packages/pdm/cli/actions.py", line 236, in do_add
    resolved = do_lock(project, strategy, tracked_names, reqs, dry_run=dry_run)
  File "/home/anonymous/.pyenv/versions/3.9.6/lib/python3.9/site-packages/pdm/cli/actions.py", line 77, in do_lock
    mapping, dependencies = resolve(
  File "/home/anonymous/.pyenv/versions/3.9.6/lib/python3.9/site-packages/pdm/resolver/core.py", line 31, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "/home/anonymous/.pyenv/versions/3.9.6/lib/python3.9/site-packages/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/anonymous/.pyenv/versions/3.9.6/lib/python3.9/site-packages/resolvelib/resolvers.py", line 373, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/home/anonymous/.pyenv/versions/3.9.6/lib/python3.9/site-packages/resolvelib/resolvers.py", line 213, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "/home/anonymous/.pyenv/versions/3.9.6/lib/python3.9/site-packages/resolvelib/resolvers.py", line 203, in _get_updated_criteria
    for requirement in self._p.get_dependencies(candidate=candidate):
  File "/home/anonymous/.pyenv/versions/3.9.6/lib/python3.9/site-packages/pdm/resolver/providers.py", line 169, in get_dependencies
    deps, requires_python, _ = self.repository.get_dependencies(candidate)
  File "/home/anonymous/.pyenv/versions/3.9.6/lib/python3.9/site-packages/pdm/models/repositories.py", line 79, in get_dependencies
    requirements, requires_python, summary = getter(candidate)
  File "/home/anonymous/.pyenv/versions/3.9.6/lib/python3.9/site-packages/pdm/models/repositories.py", line 47, in wrapper
    self._candidate_info_cache.set(candidate, result)
  File "/home/anonymous/.pyenv/versions/3.9.6/lib/python3.9/site-packages/pdm/models/caches.py", line 55, in set
    key = self._get_key(obj)
  File "/home/anonymous/.pyenv/versions/3.9.6/lib/python3.9/site-packages/pdm/models/caches.py", line 81, in _get_key
    raise KeyError
KeyError
```

## Expected behavior

PyTorch3D is installed and added to the dependencies.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.12.8
Python Interpreter: /home/classner/.pyenv/versions/3.9.6/bin/python3 (3.9)
Project Root:       /home/classner/Dev/calibration
Project Packages:   /home/classner/Dev/calibration/__pypackages__/3.9
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.6",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.10.60.1-microsoft-standard-WSL2",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Wed Aug 25 23:20:18 UTC 2021",
  "python_full_version": "3.9.6",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
By default, the building process is **isolated**, all requirements must be specified via PEP 517's `build-system.requires` metadata. If the package doesn't support PEP 517 and you want it to use the added `torch` dependency, use `pdm add --no-isolation "git+https://github.com/facebookresearch/pytorch3d.git@stable#egg=pytorch3d"

**Comment by pawamoy** [comment]
Also, if pytorch3d does not declare Torch as a setup requirements (`setup_requires` in setup.py), that is an issue that should be reported on their bugtracker.
