### ISSUE TITLE
PDM AssertionError

### ISSUE THREAD

**Issue by liaoran** [pdm-project/pdm#922]
OS: Ubuntu 20.04.3 LTS
Python Version: 3.8.10
PDM Version: 1.13.0.post0
According to the official documentation, when using "pdm init" command in a new folder, the following error is reported:
```
Traceback (most recent call last):
  File "/home/programmer/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/programmer/.local/lib/python3.8/site-packages/pdm/core.py", line 233, in main
    return Core().main(args)
  File "/home/programmer/.local/lib/python3.8/site-packages/pdm/core.py", line 180, in main
    check_update(options.project)
  File "/home/programmer/.local/lib/python3.8/site-packages/pdm/cli/actions.py", line 790, in check_update
    latest_version = get_latest_version(project)
  File "/home/programmer/.local/lib/python3.8/site-packages/pdm/cli/actions.py", line 767, in get_latest_version
    candidate = get_finder([]).find_best_candidate("pdm")
  File "/home/programmer/.local/lib/python3.8/site-packages/pdm/utils.py", line 124, in get_finder
    finder = get_package_finder(
  File "/home/programmer/.local/lib/python3.8/site-packages/pdm/models/pip_shims.py", line 69, in get_package_finder
    session = install_cmd._build_session(options)
  File "/home/programmer/.local/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 88, in _build_session
    assert not options.cache_dir or os.path.isabs(options.cache_dir)
AssertionError
```

**Comment by frostming** [comment]
Do you set `PIP_CACHE` env or `pip.conf`?
