### ISSUE TITLE
'VcsRequirement' object has no attribute 'as_candidate' when add from git

### ISSUE THREAD

**Issue by shaozi** [pdm-project/pdm#928]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

When add package from git repository, it failed with error:

```sh
pdm add git+https://github.com/shaozi/python-package.git
Adding packages to default dependencies: python @ git+https://github.com/shaozi/python-package.git
See /var/folders/r7/z_rwb6xj75ncw5p5wrhrpbg80000gn/T/pdm-lock-u7egc_xv.log for detailed debug log.
[AttributeError]: 'VcsRequirement' object has no attribute 'as_candidate'
Add '-v' to see the detailed traceback
jingshaochen@Jingshaos-MacBook-Pro pdm-package-git % pdm add git+https://github.com/shaozi/python-package.git -v
Adding packages to default dependencies: python @ git+https://github.com/shaozi/python-package.git
======== Start resolving requirements ========
  python @ git+https://github.com/shaozi/python-package.git
  python>=3.10
  Adding requirement python @ git+https://github.com/shaozi/python-package.git
Traceback (most recent call last):
  File "/Users/jingshaochen/Library/Python/3.8/bin/pdm", line 10, in <module>
    sys.exit(main())
  File "/Users/jingshaochen/Library/Application Support/pdm/venv/lib/python3.8/site-packages/pdm/core.py", line 233, in main
    return Core().main(args)
  File "/Users/jingshaochen/Library/Application Support/pdm/venv/lib/python3.8/site-packages/pdm/core.py", line 168, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/Users/jingshaochen/Library/Application Support/pdm/venv/lib/python3.8/site-packages/pdm/core.py", line 163, in main
    f(options.project, options)
  File "/Users/jingshaochen/Library/Application Support/pdm/venv/lib/python3.8/site-packages/pdm/cli/commands/add.py", line 53, in handle
    actions.do_add(
  File "/Users/jingshaochen/Library/Application Support/pdm/venv/lib/python3.8/site-packages/pdm/cli/actions.py", line 236, in do_add
    resolved = do_lock(project, strategy, tracked_names, reqs, dry_run=dry_run)
  File "/Users/jingshaochen/Library/Application Support/pdm/venv/lib/python3.8/site-packages/pdm/cli/actions.py", line 77, in do_lock
    mapping, dependencies = resolve(
  File "/Users/jingshaochen/Library/Application Support/pdm/venv/lib/python3.8/site-packages/pdm/resolver/core.py", line 31, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "/Users/jingshaochen/Library/Application Support/pdm/venv/lib/python3.8/site-packages/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/Users/jingshaochen/Library/Application Support/pdm/venv/lib/python3.8/site-packages/resolvelib/resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/Users/jingshaochen/Library/Application Support/pdm/venv/lib/python3.8/site-packages/resolvelib/resolvers.py", line 168, in _add_to_criteria
    candidates=build_iter_view(matches),
  File "/Users/jingshaochen/Library/Application Support/pdm/venv/lib/python3.8/site-packages/resolvelib/structs.py", line 164, in build_iter_view
    matches = list(matches)
  File "/Users/jingshaochen/Library/Application Support/pdm/venv/lib/python3.8/site-packages/pdm/resolver/providers.py", line 234, in find_matches
    yield from super().find_matches(identifier, requirements, incompatibilities)
  File "/Users/jingshaochen/Library/Application Support/pdm/venv/lib/python3.8/site-packages/pdm/resolver/providers.py", line 140, in find_matches
    candidates = find_python_matches(identifier, requirements)
  File "/Users/jingshaochen/Library/Application Support/pdm/venv/lib/python3.8/site-packages/pdm/resolver/python.py", line 41, in find_python_matches
    return [project_req.as_candidate()]
AttributeError: 'VcsRequirement' object has no attribute 'as_candidate'
jingshaochen@Jingshaos-MacBook-Pro pdm-package-git % 

```

```bash
# Paste the output of `pdm info && pdm info --env` below:
jingshaochen@Jingshaos-MacBook-Pro pdm-package-git % pdm info && pdm info --env
PDM version:        1.13.1
Python Interpreter: /usr/local/bin/python3 (3.10)
Project Root:       /Users/jingshaochen/Documents/pgm/pdm-package-git
Project Packages:   /Users/jingshaochen/Documents/pgm/pdm-package-git/__pypackages__/3.10
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.2",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "21.3.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64",
  "python_full_version": "3.10.2",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
As a workaround, please give a name to the url like: `pdm add "mypackage @ git+https://github.com/shaozi/python-package.git`.
