### ISSUE TITLE
add nose-progressive failed

### ISSUE THREAD

**Issue by andriyor** [pdm-project/pdm#942]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

pdm add -v nose-progressive

## Actual behavior

```
Adding packages to default dependencies: nose-progressive
======== Start resolving requirements ========
  nose-progressive
  python>=3.9
  Adding requirement nose-progressive
	Found matching candidates:
	  <Candidate nose-progressive 1.5.2 from https://pypi.org/simple/nose-progressive/>
	  <Candidate nose-progressive 1.5.1 from https://pypi.org/simple/nose-progressive/>
	  <Candidate nose-progressive 1.5 from https://pypi.org/simple/nose-progressive/>
	  <Candidate nose-progressive 1.4.3 from https://pypi.org/simple/nose-progressive/>
	  <Candidate nose-progressive 1.4.2 from https://pypi.org/simple/nose-progressive/>
	  <Candidate nose-progressive 1.4.1 from https://pypi.org/simple/nose-progressive/>
	  <Candidate nose-progressive 1.4 from https://pypi.org/simple/nose-progressive/>
	  <Candidate nose-progressive 1.3 from https://pypi.org/simple/nose-progressive/>
	  <Candidate nose-progressive 1.2.1 from https://pypi.org/simple/nose-progressive/>
	  <Candidate nose-progressive 1.2 from https://pypi.org/simple/nose-progressive/>
	  ... [17 more candidate(s)]
  Adding requirement python>=3.9
======== Starting round 0 ========
Resolving: new pin python >=3.9
======== Ending round 0 ========
======== Starting round 1 ========
  Adding requirement nose>=1.2.1(from nose-progressive 1.5.2)
	Found matching candidates:
	  <Candidate nose 1.3.7 from https://pypi.org/simple/nose/>
	  <Candidate nose 1.3.6 from https://pypi.org/simple/nose/>
	  <Candidate nose 1.3.4 from https://pypi.org/simple/nose/>
	  <Candidate nose 1.3.3 from https://pypi.org/simple/nose/>
	  <Candidate nose 1.3.2 from https://pypi.org/simple/nose/>
	  <Candidate nose 1.3.1 from https://pypi.org/simple/nose/>
	  <Candidate nose 1.3.0 from https://pypi.org/simple/nose/>
	  <Candidate nose 1.2.1 from https://pypi.org/simple/nose/>
  Adding requirement blessings<2.0,>=1.3(from nose-progressive 1.5.2)
	Found matching candidates:
	  <Candidate blessings 1.7 from https://pypi.org/simple/blessings/>
	  <Candidate blessings 1.6.1 from https://pypi.org/simple/blessings/>
	  <Candidate blessings 1.6 from https://pypi.org/simple/blessings/>
	  <Candidate blessings 1.5.1 from https://pypi.org/simple/blessings/>
	  <Candidate blessings 1.5 from https://pypi.org/simple/blessings/>
	  <Candidate blessings 1.4 from https://pypi.org/simple/blessings/>
	  <Candidate blessings 1.3 from https://pypi.org/simple/blessings/>
Resolving: new pin nose-progressive 1.5.2
======== Ending round 1 ========
======== Starting round 2 ========
  Adding requirement six(from blessings 1.7)
	Found matching candidates:
	  <Candidate six 1.16.0 from https://pypi.org/simple/six/>
	  <Candidate six 1.15.0 from https://pypi.org/simple/six/>
	  <Candidate six 1.14.0 from https://pypi.org/simple/six/>
	  <Candidate six 1.13.0 from https://pypi.org/simple/six/>
	  <Candidate six 1.12.0 from https://pypi.org/simple/six/>
	  <Candidate six 1.11.0 from https://pypi.org/simple/six/>
	  <Candidate six 1.10.0 from https://pypi.org/simple/six/>
	  <Candidate six 1.9.0 from https://pypi.org/simple/six/>
	  <Candidate six 1.8.0 from https://pypi.org/simple/six/>
	  <Candidate six 1.7.3 from https://pypi.org/simple/six/>
	  ... [35 more candidate(s)]
Resolving: new pin blessings 1.7
======== Ending round 2 ========
======== Starting round 3 ========
Resolving: new pin nose 1.3.7
======== Ending round 3 ========
======== Starting round 4 ========
Resolving: new pin six 1.16.0
======== Ending round 4 ========
======== Starting round 5 ========
======== Resolution Result ========
Stable pins:
            python None
  nose-progressive 1.5.2
         blessings 1.7
              nose 1.3.7
               six 1.16.0
	Found matching candidates:
	  <Candidate nose-progressive 1.5.2 from https://pypi.org/simple/nose-progressive/>
	Found matching candidates:
	  <Candidate blessings 1.7 from https://pypi.org/simple/blessings/>
	Found matching candidates:
	  <Candidate nose 1.3.7 from https://pypi.org/simple/nose/>
	Found matching candidates:
	  <Candidate six 1.16.0 from https://pypi.org/simple/six/>
🔒 Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
Synchronizing working set with lock file: 1 to add, 0 to update, 0 to remove

Preparing isolated env for PEP 517 build...
Building wheel for https://files.pythonhosted.org/packages/dc/bc/0f55ba957109922c31ef22444c899004b1221eacff030300de74ad0e04fb/nose-progressive-1.5.2.tar.gz#sha256=3a6e2833e613c1c239baf05a19f66b5920915e62c07251d3ab3f3acb017ef5d7 (from https://pypi.org/simple/nose-progressive/)
Collecting setuptools>=40.8.0
  Using cached setuptools-60.9.3-py3-none-any.whl (1.1 MB)
Collecting wheel
  Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel, setuptools
Successfully installed setuptools-60.9.3 wheel-0.37.1
WARNING: You are using pip version 21.3.1; however, version 22.0.3 is available.
You should consider upgrading via the '/Users/andrejorehov/.pyenv/versions/3.9.6/bin/python3 -m pip install --upgrade pip' command.
error in nose-progressive setup command: use_2to3 is invalid.
Install nose-progressive 1.5.2 failed
Error occurs:
Traceback (most recent call last):
  File "/Users/andrejorehov/.pyenv/versions/3.9.6/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/andrejorehov/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 185, in install_candidate
    self.manager.install(can)
  File "/Users/andrejorehov/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/installers/manager.py", line 39, in install
    installer(prepared.build(), self.environment, prepared.direct_url())
  File "/Users/andrejorehov/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/models/candidates.py", line 332, in build
    self.wheel = builder.build(build_dir, metadata_directory=self._metadata_dir)
  File "/Users/andrejorehov/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/builders/wheel.py", line 26, in build
    requires = self._hook.get_requires_for_build_wheel(config_settings)
  File "/Users/andrejorehov/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pep517/wrappers.py", line 172, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "/Users/andrejorehov/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pep517/wrappers.py", line 322, in _call_hook
    self._subprocess_runner(
  File "/Users/andrejorehov/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/builders/base.py", line 238, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
  File "/Users/andrejorehov/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/builders/base.py", line 86, in log_subprocessor
    raise BuildError(
pdm.exceptions.BuildError: Call command ['/Users/andrejorehov/.pyenv/versions/3.9.6/bin/python3', '/Users/andrejorehov/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pep517/in_process/_in_process.py', 'get_requires_for_build_wheel', '/var/folders/f6/zsylckyj0sl6mv26gcdbr9lc0000gn/T/tmprcxxqnig'] return non-zero status(1).
  Retry failed jobs
Preparing isolated env for PEP 517 build...
Reusing shared build env: /var/folders/f6/zsylckyj0sl6mv26gcdbr9lc0000gn/T/pdm-build-env-_sxq1y4i-shared
Building wheel for https://files.pythonhosted.org/packages/dc/bc/0f55ba957109922c31ef22444c899004b1221eacff030300de74ad0e04fb/nose-progressive-1.5.2.tar.gz#sha256=3a6e2833e613c1c239baf05a19f66b5920915e62c07251d3ab3f3acb017ef5d7 (from https://pypi.org/simple/nose-progressive/)
error in nose-progressive setup command: use_2to3 is invalid.
Install nose-progressive 1.5.2 failed
Error occurs:
Traceback (most recent call last):
  File "/Users/andrejorehov/.pyenv/versions/3.9.6/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/andrejorehov/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 185, in install_candidate
    self.manager.install(can)
  File "/Users/andrejorehov/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/installers/manager.py", line 39, in install
    installer(prepared.build(), self.environment, prepared.direct_url())
  File "/Users/andrejorehov/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/models/candidates.py", line 332, in build
    self.wheel = builder.build(build_dir, metadata_directory=self._metadata_dir)
  File "/Users/andrejorehov/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/builders/wheel.py", line 26, in build
    requires = self._hook.get_requires_for_build_wheel(config_settings)
  File "/Users/andrejorehov/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pep517/wrappers.py", line 172, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "/Users/andrejorehov/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pep517/wrappers.py", line 322, in _call_hook
    self._subprocess_runner(
  File "/Users/andrejorehov/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/builders/base.py", line 238, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
  File "/Users/andrejorehov/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/builders/base.py", line 86, in log_subprocessor
    raise BuildError(
pdm.exceptions.BuildError: Call command ['/Users/andrejorehov/.pyenv/versions/3.9.6/bin/python3', '/Users/andrejorehov/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pep517/in_process/_in_process.py', 'get_requires_for_build_wheel', '/var/folders/f6/zsylckyj0sl6mv26gcdbr9lc0000gn/T/tmpbuy7c93t'] return non-zero status(1).

ERRORS:
add nose-progressive failed:
Traceback (most recent call last):
  File "/Users/andrejorehov/.pyenv/versions/3.9.6/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/andrejorehov/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 185, in install_candidate
    self.manager.install(can)
  File "/Users/andrejorehov/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/installers/manager.py", line 39, in install
    installer(prepared.build(), self.environment, prepared.direct_url())
  File "/Users/andrejorehov/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/models/candidates.py", line 332, in build
    self.wheel = builder.build(build_dir, metadata_directory=self._metadata_dir)
  File "/Users/andrejorehov/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/builders/wheel.py", line 26, in build
    requires = self._hook.get_requires_for_build_wheel(config_settings)
  File "/Users/andrejorehov/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pep517/wrappers.py", line 172, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "/Users/andrejorehov/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pep517/wrappers.py", line 322, in _call_hook
    self._subprocess_runner(
  File "/Users/andrejorehov/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/builders/base.py", line 238, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
  File "/Users/andrejorehov/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/builders/base.py", line 86, in log_subprocessor
    raise BuildError(
pdm.exceptions.BuildError: Call command ['/Users/andrejorehov/.pyenv/versions/3.9.6/bin/python3', '/Users/andrejorehov/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pep517/in_process/_in_process.py', 'get_requires_for_build_wheel', '/var/folders/f6/zsylckyj0sl6mv26gcdbr9lc0000gn/T/tmpbuy7c93t'] return non-zero status(1).

Traceback (most recent call last):
  File "/Users/andrejorehov/.local/bin/pdm", line 10, in <module>
    sys.exit(main())
  File "/Users/andrejorehov/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/core.py", line 233, in main
    return Core().main(args)
  File "/Users/andrejorehov/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/core.py", line 168, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/Users/andrejorehov/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/core.py", line 163, in main
    f(options.project, options)
  File "/Users/andrejorehov/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/cli/commands/add.py", line 53, in handle
    actions.do_add(
  File "/Users/andrejorehov/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/cli/actions.py", line 245, in do_add
    do_sync(
  File "/Users/andrejorehov/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/cli/actions.py", line 190, in do_sync
    handler.synchronize()
  File "/Users/andrejorehov/Library/Application Support/pdm/venv/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 352, in synchronize
    raise InstallationError("Some package operations are not complete yet")
pdm.exceptions.InstallationError: Some package operations are not complete yet
```

## Expected behavior

package installed

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
❯ pdm info && pdm info --env
PDM version:        1.13.3
Python Interpreter: /Users/andrejorehov/.pyenv/versions/3.9.6/bin/python3 (3.9)
Project Root:       /Users/andrejorehov/PycharmProjects/pdm-test
Project Packages:   /Users/andrejorehov/PycharmProjects/pdm-test/__pypackages__/3.9
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.6",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "21.3.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64",
  "python_full_version": "3.9.6",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "darwin"
}
```

**Comment by pawamoy** [comment]
This package adds `"use_2to3": True` to setuptools `setup` keyword arguments. It's probably not valid anymore on recent setuptools versions. https://github.com/erikrose/nose-progressive/blob/master/setup.py#L16

**Comment by frostming** [comment]
BTW the last release of `nose-progressive` is 4 years ago and `nose` itself stops development even earlier.
