### ISSUE TITLE
Invalid specifier: '&gt;=3.6'

### ISSUE THREAD

**Issue by XYenon** [pdm-project/pdm#944]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

pyproject.toml

```toml
[project]
requires-python = ">=3.7.1"
dependencies = [
    "authlib~=0.15.2",
]

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"
```

`pdm install -v`

## Actual behavior

```
Lock file does not exist
Updating the lock file...
======== Start resolving requirements ========
  authlib~=0.15.2
  python>=3.7.1
  Adding requirement authlib~=0.15.2
        Found matching candidates:
          <Candidate authlib 0.15.5 from https://pypi.org/simple/authlib/>
          <Candidate authlib 0.15.4 from https://pypi.org/simple/authlib/>
          <Candidate authlib 0.15.3 from https://pypi.org/simple/authlib/>
          <Candidate authlib 0.15.2 from https://pypi.org/simple/authlib/>
  Adding requirement python>=3.7.1
======== Starting round 0 ========
Resolving: new pin python >=3.7.1
======== Ending round 0 ========
======== Starting round 1 ========
  Adding requirement cryptography(from authlib 0.15.5)
        Found matching candidates:
          <Candidate cryptography 36.0.1 from https://pypi.org/simple/cryptography/>
          <Candidate cryptography 36.0.0 from https://pypi.org/simple/cryptography/>
          <Candidate cryptography 35.0.0 from https://pypi.org/simple/cryptography/>
          <Candidate cryptography 3.4.8 from https://pypi.org/simple/cryptography/>
          <Candidate cryptography 3.4.7 from https://pypi.org/simple/cryptography/>
          <Candidate cryptography 3.4.6 from https://pypi.org/simple/cryptography/>
          <Candidate cryptography 3.4.5 from https://pypi.org/simple/cryptography/>
          <Candidate cryptography 3.4.4 from https://pypi.org/simple/cryptography/>
          <Candidate cryptography 3.4.3 from https://pypi.org/simple/cryptography/>
          <Candidate cryptography 3.4.2 from https://pypi.org/simple/cryptography/>
          ... [1619 more candidate(s)]
Resolving: new pin authlib 0.15.5
======== Ending round 1 ========
======== Starting round 2 ========
Traceback (most recent call last):
  File "/usr/local/Cellar/pdm/1.13.3/libexec/lib/python3.10/site-packages/pip/_vendor/packaging/specifiers.py", line 635, in __init__
    parsed.add(Specifier(specifier))
  File "/usr/local/Cellar/pdm/1.13.3/libexec/lib/python3.10/site-packages/pip/_vendor/packaging/specifiers.py", line 99, in __init__
    raise InvalidSpecifier(f"Invalid specifier: '{spec}'")
pip._vendor.packaging.specifiers.InvalidSpecifier: Invalid specifier: '&gt;=3.6'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/usr/local/Cellar/pdm/1.13.3/libexec/lib/python3.10/site-packages/pdm/core.py", line 233, in main
    return Core().main(args)
  File "/usr/local/Cellar/pdm/1.13.3/libexec/lib/python3.10/site-packages/pdm/core.py", line 168, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/usr/local/Cellar/pdm/1.13.3/libexec/lib/python3.10/site-packages/pdm/core.py", line 163, in main
    f(options.project, options)
  File "/usr/local/Cellar/pdm/1.13.3/libexec/lib/python3.10/site-packages/pdm/cli/commands/install.py", line 47, in handle
    actions.do_lock(project, strategy=strategy, dry_run=options.dry_run)
  File "/usr/local/Cellar/pdm/1.13.3/libexec/lib/python3.10/site-packages/pdm/cli/actions.py", line 76, in do_lock
    mapping, dependencies = resolve(
  File "/usr/local/Cellar/pdm/1.13.3/libexec/lib/python3.10/site-packages/pdm/resolver/core.py", line 31, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "/usr/local/Cellar/pdm/1.13.3/libexec/lib/python3.10/site-packages/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/local/Cellar/pdm/1.13.3/libexec/lib/python3.10/site-packages/resolvelib/resolvers.py", line 373, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/usr/local/Cellar/pdm/1.13.3/libexec/lib/python3.10/site-packages/resolvelib/resolvers.py", line 213, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "/usr/local/Cellar/pdm/1.13.3/libexec/lib/python3.10/site-packages/resolvelib/resolvers.py", line 203, in _get_updated_criteria
    for requirement in self._p.get_dependencies(candidate=candidate):
  File "/usr/local/Cellar/pdm/1.13.3/libexec/lib/python3.10/site-packages/pdm/resolver/providers.py", line 172, in get_dependencies
    deps, requires_python, _ = self.repository.get_dependencies(candidate)
  File "/usr/local/Cellar/pdm/1.13.3/libexec/lib/python3.10/site-packages/pdm/models/repositories.py", line 90, in get_dependencies
    return reqs, PySpecSet(requires_python), summary
  File "/usr/local/Cellar/pdm/1.13.3/libexec/lib/python3.10/site-packages/pdm/models/specifiers.py", line 63, in __init__
    super().__init__(version_str)
  File "/usr/local/Cellar/pdm/1.13.3/libexec/lib/python3.10/site-packages/pip/_vendor/packaging/specifiers.py", line 637, in __init__
    parsed.add(LegacySpecifier(specifier))
  File "/usr/local/Cellar/pdm/1.13.3/libexec/lib/python3.10/site-packages/pip/_vendor/packaging/specifiers.py", line 254, in __init__
    super().__init__(spec, prereleases)
  File "/usr/local/Cellar/pdm/1.13.3/libexec/lib/python3.10/site-packages/pip/_vendor/packaging/specifiers.py", line 99, in __init__
    raise InvalidSpecifier(f"Invalid specifier: '{spec}'")
pip._vendor.packaging.specifiers.InvalidSpecifier: Invalid specifier: '&gt;=3.6'
```

## Expected behavior

No errors

## Environment Information

```bash
PDM version:        1.13.3
Python Interpreter: /run/current-system/sw/bin/python (3.9)
Project Root:       /Users/xyenon/Codes/test/pdm
Project Packages:   /Users/xyenon/Codes/test/pdm/__pypackages__/3.9
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.9",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "21.3.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64",
  "python_full_version": "3.9.9",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
Can't reproduce here, try clearing the cache by `pdm cache clear` and see if the issue persists.

**Comment by XYenon** [comment]
The problem disappeared after running `pdm cache clear`, it should be the bug of the mirror I used before.
