### ISSUE TITLE
Unable to add specific package

### ISSUE THREAD

**Issue by mimikun** [pdm-project/pdm#949]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

1. Run: `mkdir test && cd test`
1. Run: `pdm init -n`
2. Run: `pdm add selenium`

## Actual behavior

```shell
~
➜ mkdir /tmp/test && cd /tmp/test
/tmp/test
➜ pdm init -n
Creating a pyproject.toml for PDM...
Using Python interpreter: /home/mimikun/.asdf/installs/python/3.9.6/bin/python3.9 (3.9)
Changes are written to pyproject.toml.
/tmp/test via  v3.9.6 took 38s
➜ pdm add selenium -v
Adding packages to default dependencies: selenium
======== Start resolving requirements ========
  selenium
  python>=3.9
  Adding requirement selenium
        Found matching candidates:
          <Candidate selenium 4.1.2 from https://pypi.org/simple/selenium/>
          <Candidate selenium 4.1.1 from https://pypi.org/simple/selenium/>
          <Candidate selenium 4.1.0 from https://pypi.org/simple/selenium/>
          <Candidate selenium 4.0.0 from https://pypi.org/simple/selenium/>
          <Candidate selenium 3.141.0 from https://pypi.org/simple/selenium/>
          <Candidate selenium 3.14.1 from https://pypi.org/simple/selenium/>
          <Candidate selenium 3.14.0 from https://pypi.org/simple/selenium/>
          <Candidate selenium 3.13.0 from https://pypi.org/simple/selenium/>
          <Candidate selenium 3.12.0 from https://pypi.org/simple/selenium/>
          <Candidate selenium 3.11.0 from https://pypi.org/simple/selenium/>
          ... [147 more candidate(s)]
  Adding requirement python>=3.9
======== Starting round 0 ========
Resolving: new pin python >=3.9
======== Ending round 0 ========
======== Starting round 1 ========
  Adding requirement urllib3[secure,socks]~=1.26(from selenium 4.1.2)
        Found matching candidates:
          <Candidate urllib3 1.26.8 from https://pypi.org/simple/urllib3/>
          <Candidate urllib3 1.26.7 from https://pypi.org/simple/urllib3/>
          <Candidate urllib3 1.26.6 from https://pypi.org/simple/urllib3/>
          <Candidate urllib3 1.26.5 from https://pypi.org/simple/urllib3/>
          <Candidate urllib3 1.26.4 from https://pypi.org/simple/urllib3/>
          <Candidate urllib3 1.26.3 from https://pypi.org/simple/urllib3/>
          <Candidate urllib3 1.26.2 from https://pypi.org/simple/urllib3/>
          <Candidate urllib3 1.26.1 from https://pypi.org/simple/urllib3/>
          <Candidate urllib3 1.26.0 from https://pypi.org/simple/urllib3/>
  Adding requirement trio~=0.17(from selenium 4.1.2)
        Found matching candidates:
          <Candidate trio 0.20.0 from https://pypi.org/simple/trio/>
          <Candidate trio 0.19.0 from https://pypi.org/simple/trio/>
          <Candidate trio 0.18.0 from https://pypi.org/simple/trio/>
          <Candidate trio 0.17.0 from https://pypi.org/simple/trio/>
  Adding requirement trio-websocket~=0.9(from selenium 4.1.2)
        Found matching candidates:
          <Candidate trio-websocket 0.9.2 from https://pypi.org/simple/trio-websocket/>
          <Candidate trio-websocket 0.9.1 from https://pypi.org/simple/trio-websocket/>
          <Candidate trio-websocket 0.9.0 from https://pypi.org/simple/trio-websocket/>
Resolving: new pin selenium 4.1.2
======== Ending round 1 ========
======== Starting round 2 ========
  Adding requirement attrs>=19.2.0(from trio 0.20.0)
        Found matching candidates:
          <Candidate attrs 21.4.0 from https://pypi.org/simple/attrs/>
          <Candidate attrs 21.3.0 from https://pypi.org/simple/attrs/>
          <Candidate attrs 21.2.0 from https://pypi.org/simple/attrs/>
          <Candidate attrs 21.1.0 from https://pypi.org/simple/attrs/>
          <Candidate attrs 20.3.0 from https://pypi.org/simple/attrs/>
          <Candidate attrs 20.2.0 from https://pypi.org/simple/attrs/>
          <Candidate attrs 20.1.0 from https://pypi.org/simple/attrs/>
          <Candidate attrs 19.3.0 from https://pypi.org/simple/attrs/>
          <Candidate attrs 19.2.0 from https://pypi.org/simple/attrs/>
  Adding requirement sortedcontainers(from trio 0.20.0)
        Found matching candidates:
          <Candidate sortedcontainers 2.4.0 from https://pypi.org/simple/sortedcontainers/>
          <Candidate sortedcontainers 2.3.0 from https://pypi.org/simple/sortedcontainers/>
          <Candidate sortedcontainers 2.2.2 from https://pypi.org/simple/sortedcontainers/>
          <Candidate sortedcontainers 2.2.1 from https://pypi.org/simple/sortedcontainers/>
          <Candidate sortedcontainers 2.2.0 from https://pypi.org/simple/sortedcontainers/>
          <Candidate sortedcontainers 2.1.0 from https://pypi.org/simple/sortedcontainers/>
          <Candidate sortedcontainers 2.0.5 from https://pypi.org/simple/sortedcontainers/>
          <Candidate sortedcontainers 2.0.4 from https://pypi.org/simple/sortedcontainers/>
          <Candidate sortedcontainers 2.0.3 from https://pypi.org/simple/sortedcontainers/>
          <Candidate sortedcontainers 2.0.2 from https://pypi.org/simple/sortedcontainers/>
          ... [51 more candidate(s)]
  Adding requirement async-generator>=1.9(from trio 0.20.0)
        Found matching candidates:
          <Candidate async-generator 1.10 from https://pypi.org/simple/async-generator/>
          <Candidate async-generator 1.9 from https://pypi.org/simple/async-generator/>
  Adding requirement idna(from trio 0.20.0)
        Found matching candidates:
          <Candidate idna 3.3 from https://pypi.org/simple/idna/>
          <Candidate idna 3.2 from https://pypi.org/simple/idna/>
          <Candidate idna 3.1 from https://pypi.org/simple/idna/>
          <Candidate idna 3.0 from https://pypi.org/simple/idna/>
          <Candidate idna 2.10 from https://pypi.org/simple/idna/>
          <Candidate idna 2.9 from https://pypi.org/simple/idna/>
          <Candidate idna 2.8 from https://pypi.org/simple/idna/>
          <Candidate idna 2.7 from https://pypi.org/simple/idna/>
          <Candidate idna 2.6 from https://pypi.org/simple/idna/>
          <Candidate idna 2.5 from https://pypi.org/simple/idna/>
          ... [31 more candidate(s)]
  Adding requirement outcome(from trio 0.20.0)
        Found matching candidates:
          <Candidate outcome 1.1.0 from https://pypi.org/simple/outcome/>
          <Candidate outcome 1.0.1 from https://pypi.org/simple/outcome/>
          <Candidate outcome 1.0.0 from https://pypi.org/simple/outcome/>
          <Candidate outcome 0.1.0 from https://pypi.org/simple/outcome/>
  Adding requirement sniffio(from trio 0.20.0)
        Found matching candidates:
          <Candidate sniffio 1.2.0 from https://pypi.org/simple/sniffio/>
          <Candidate sniffio 1.1.0 from https://pypi.org/simple/sniffio/>
          <Candidate sniffio 1.0.0 from https://pypi.org/simple/sniffio/>
          <Candidate sniffio 0.0.0 from https://pypi.org/simple/sniffio/>
  Adding requirement cffi>=1.14; os_name == "nt" and implementation_name != "pypy"(from trio 0.20.0)
        Found matching candidates:
          <Candidate cffi 1.15.0 from https://pypi.org/simple/cffi/>
          <Candidate cffi 1.14.6 from https://pypi.org/simple/cffi/>
          <Candidate cffi 1.14.5 from https://pypi.org/simple/cffi/>
          <Candidate cffi 1.14.4 from https://pypi.org/simple/cffi/>
          <Candidate cffi 1.14.3 from https://pypi.org/simple/cffi/>
          <Candidate cffi 1.14.2 from https://pypi.org/simple/cffi/>
          <Candidate cffi 1.14.1 from https://pypi.org/simple/cffi/>
          <Candidate cffi 1.14.0 from https://pypi.org/simple/cffi/>
Resolving: new pin trio 0.20.0
======== Ending round 2 ========
======== Starting round 3 ========
  Adding requirement async-generator>=1.10(from trio-websocket 0.9.2)
        Found matching candidates:
          <Candidate async-generator 1.10 from https://pypi.org/simple/async-generator/>
          <Candidate async-generator 1.9 from https://pypi.org/simple/async-generator/>
  Adding requirement trio>=0.11(from trio-websocket 0.9.2)
        Found matching candidates:
          <Candidate trio 0.20.0 from https://pypi.org/simple/trio/>
          <Candidate trio 0.19.0 from https://pypi.org/simple/trio/>
          <Candidate trio 0.18.0 from https://pypi.org/simple/trio/>
          <Candidate trio 0.17.0 from https://pypi.org/simple/trio/>
  Adding requirement wsproto>=0.14(from trio-websocket 0.9.2)
        Found matching candidates:
          <Candidate wsproto 1.1.0 from https://pypi.org/simple/wsproto/>
          <Candidate wsproto 1.0.0 from https://pypi.org/simple/wsproto/>
          <Candidate wsproto 0.15.0 from https://pypi.org/simple/wsproto/>
          <Candidate wsproto 0.14.1 from https://pypi.org/simple/wsproto/>
          <Candidate wsproto 0.14.0 from https://pypi.org/simple/wsproto/>
Resolving: new pin trio-websocket 0.9.2
======== Ending round 3 ========
======== Starting round 4 ========
  Adding requirement pyOpenSSL>=0.14(from urllib3 1.26.8)
        Found matching candidates:
          <Candidate pyOpenSSL 22.0.0 from https://pypi.org/simple/pyopenssl/>
          <Candidate pyOpenSSL 21.0.0 from https://pypi.org/simple/pyopenssl/>
          <Candidate pyOpenSSL 20.0.1 from https://pypi.org/simple/pyopenssl/>
          <Candidate pyOpenSSL 20.0.0 from https://pypi.org/simple/pyopenssl/>
          <Candidate pyOpenSSL 19.1.0 from https://pypi.org/simple/pyopenssl/>
          <Candidate pyOpenSSL 19.0.0 from https://pypi.org/simple/pyopenssl/>
          <Candidate pyOpenSSL 18.0.0 from https://pypi.org/simple/pyopenssl/>
          <Candidate pyOpenSSL 17.5.0 from https://pypi.org/simple/pyopenssl/>
          <Candidate pyOpenSSL 17.4.0 from https://pypi.org/simple/pyopenssl/>
          <Candidate pyOpenSSL 17.3.0 from https://pypi.org/simple/pyopenssl/>
          ... [27 more candidate(s)]
  Adding requirement cryptography>=1.3.4(from urllib3 1.26.8)
        Found matching candidates:
          <Candidate cryptography 36.0.1 from https://pypi.org/simple/cryptography/>
          <Candidate cryptography 36.0.0 from https://pypi.org/simple/cryptography/>
          <Candidate cryptography 35.0.0 from https://pypi.org/simple/cryptography/>
          <Candidate cryptography 3.4.8 from https://pypi.org/simple/cryptography/>
          <Candidate cryptography 3.4.7 from https://pypi.org/simple/cryptography/>
          <Candidate cryptography 3.4.6 from https://pypi.org/simple/cryptography/>
          <Candidate cryptography 3.4.5 from https://pypi.org/simple/cryptography/>
          <Candidate cryptography 3.4.4 from https://pypi.org/simple/cryptography/>
          <Candidate cryptography 3.4.3 from https://pypi.org/simple/cryptography/>
          <Candidate cryptography 3.4.2 from https://pypi.org/simple/cryptography/>
          ... [1143 more candidate(s)]
  Adding requirement idna>=2.0.0(from urllib3 1.26.8)
        Found matching candidates:
          <Candidate idna 3.3 from https://pypi.org/simple/idna/>
          <Candidate idna 3.2 from https://pypi.org/simple/idna/>
          <Candidate idna 3.1 from https://pypi.org/simple/idna/>
          <Candidate idna 3.0 from https://pypi.org/simple/idna/>
          <Candidate idna 2.10 from https://pypi.org/simple/idna/>
          <Candidate idna 2.9 from https://pypi.org/simple/idna/>
          <Candidate idna 2.8 from https://pypi.org/simple/idna/>
          <Candidate idna 2.7 from https://pypi.org/simple/idna/>
          <Candidate idna 2.6 from https://pypi.org/simple/idna/>
          <Candidate idna 2.5 from https://pypi.org/simple/idna/>
          ... [21 more candidate(s)]
  Adding requirement certifi(from urllib3 1.26.8)
        Found matching candidates:
          <Candidate certifi 2021.10.8 from https://pypi.org/simple/certifi/>
          <Candidate certifi 2021.5.30 from https://pypi.org/simple/certifi/>
          <Candidate certifi 2020.12.5 from https://pypi.org/simple/certifi/>
          <Candidate certifi 2020.11.8 from https://pypi.org/simple/certifi/>
          <Candidate certifi 2020.6.20 from https://pypi.org/simple/certifi/>
          <Candidate certifi 2020.4.5.2 from https://pypi.org/simple/certifi/>
          <Candidate certifi 2020.4.5.1 from https://pypi.org/simple/certifi/>
          <Candidate certifi 2020.4.5 from https://pypi.org/simple/certifi/>
          <Candidate certifi 2019.11.28 from https://pypi.org/simple/certifi/>
          <Candidate certifi 2019.9.11 from https://pypi.org/simple/certifi/>
          ... [70 more candidate(s)]
  Adding requirement PySocks!=1.5.7,<2.0,>=1.5.6(from urllib3 1.26.8)
        Found matching candidates:
          <Candidate PySocks 1.7.1 from https://pypi.org/simple/pysocks/>
          <Candidate PySocks 1.7.0 from https://pypi.org/simple/pysocks/>
          <Candidate PySocks 1.6.8 from https://pypi.org/simple/pysocks/>
          <Candidate PySocks 1.6.7 from https://pypi.org/simple/pysocks/>
          <Candidate PySocks 1.6.6 from https://pypi.org/simple/pysocks/>
          <Candidate PySocks 1.6.5 from https://pypi.org/simple/pysocks/>
          <Candidate PySocks 1.6.4 from https://pypi.org/simple/pysocks/>
          <Candidate PySocks 1.6.3 from https://pypi.org/simple/pysocks/>
          <Candidate PySocks 1.6.2 from https://pypi.org/simple/pysocks/>
          <Candidate PySocks 1.6.1 from https://pypi.org/simple/pysocks/>
          ... [7 more candidate(s)]
  Adding requirement urllib3(from urllib3 1.26.8)
        Found matching candidates:
          <Candidate urllib3 1.26.8 from https://pypi.org/simple/urllib3/>
          <Candidate urllib3 1.26.7 from https://pypi.org/simple/urllib3/>
          <Candidate urllib3 1.26.6 from https://pypi.org/simple/urllib3/>
          <Candidate urllib3 1.26.5 from https://pypi.org/simple/urllib3/>
          <Candidate urllib3 1.26.4 from https://pypi.org/simple/urllib3/>
          <Candidate urllib3 1.26.3 from https://pypi.org/simple/urllib3/>
          <Candidate urllib3 1.26.2 from https://pypi.org/simple/urllib3/>
          <Candidate urllib3 1.26.1 from https://pypi.org/simple/urllib3/>
          <Candidate urllib3 1.26.0 from https://pypi.org/simple/urllib3/>
          <Candidate urllib3 1.25.11 from https://pypi.org/simple/urllib3/>
          ... [106 more candidate(s)]
Resolving: new pin urllib3 1.26.8
======== Ending round 4 ========
======== Starting round 5 ========
Resolving: new pin certifi 2021.10.8
======== Ending round 5 ========
======== Starting round 6 ========
  Adding requirement attrs>=19.2.0(from outcome 1.1.0)
        Found matching candidates:
          <Candidate attrs 21.4.0 from https://pypi.org/simple/attrs/>
          <Candidate attrs 21.3.0 from https://pypi.org/simple/attrs/>
          <Candidate attrs 21.2.0 from https://pypi.org/simple/attrs/>
          <Candidate attrs 21.1.0 from https://pypi.org/simple/attrs/>
          <Candidate attrs 20.3.0 from https://pypi.org/simple/attrs/>
          <Candidate attrs 20.2.0 from https://pypi.org/simple/attrs/>
          <Candidate attrs 20.1.0 from https://pypi.org/simple/attrs/>
          <Candidate attrs 19.3.0 from https://pypi.org/simple/attrs/>
          <Candidate attrs 19.2.0 from https://pypi.org/simple/attrs/>
Resolving: new pin outcome 1.1.0
======== Ending round 6 ========
======== Starting round 7 ========
Resolving: new pin sniffio 1.2.0
======== Ending round 7 ========
======== Starting round 8 ========
Resolving: new pin sortedcontainers 2.4.0
======== Ending round 8 ========
======== Starting round 9 ========
Resolving: new pin urllib3 1.26.8
======== Ending round 9 ========
======== Starting round 10 ========
Resolving: new pin async-generator 1.10
======== Ending round 10 ========
======== Starting round 11 ========
Resolving: new pin attrs 21.4.0
======== Ending round 11 ========
======== Starting round 12 ========
  Adding requirement pycparser(from cffi 1.15.0)
        Found matching candidates:
          <Candidate pycparser 2.21 from https://pypi.org/simple/pycparser/>
          <Candidate pycparser 2.20 from https://pypi.org/simple/pycparser/>
          <Candidate pycparser 2.19 from https://pypi.org/simple/pycparser/>
          <Candidate pycparser 2.18 from https://pypi.org/simple/pycparser/>
          <Candidate pycparser 2.17 from https://pypi.org/simple/pycparser/>
          <Candidate pycparser 2.16 from https://pypi.org/simple/pycparser/>
          <Candidate pycparser 2.15 from https://pypi.org/simple/pycparser/>
          <Candidate pycparser 2.14 from https://pypi.org/simple/pycparser/>
          <Candidate pycparser 2.13 from https://pypi.org/simple/pycparser/>
          <Candidate pycparser 2.12 from https://pypi.org/simple/pycparser/>
          ... [13 more candidate(s)]
Resolving: new pin cffi 1.15.0
======== Ending round 12 ========
======== Starting round 13 ========
  Adding requirement cffi>=1.12(from cryptography 36.0.1)
        Found matching candidates:
          <Candidate cffi 1.15.0 from https://pypi.org/simple/cffi/>
          <Candidate cffi 1.14.6 from https://pypi.org/simple/cffi/>
          <Candidate cffi 1.14.5 from https://pypi.org/simple/cffi/>
          <Candidate cffi 1.14.4 from https://pypi.org/simple/cffi/>
          <Candidate cffi 1.14.3 from https://pypi.org/simple/cffi/>
          <Candidate cffi 1.14.2 from https://pypi.org/simple/cffi/>
          <Candidate cffi 1.14.1 from https://pypi.org/simple/cffi/>
          <Candidate cffi 1.14.0 from https://pypi.org/simple/cffi/>
Resolving: new pin cryptography 36.0.1
======== Ending round 13 ========
======== Starting round 14 ========
Resolving: new pin idna 3.3
======== Ending round 14 ========
======== Starting round 15 ========
  Adding requirement cryptography>=35.0(from pyopenssl 22.0.0)
        Found matching candidates:
          <Candidate cryptography 36.0.1 from https://pypi.org/simple/cryptography/>
          <Candidate cryptography 36.0.0 from https://pypi.org/simple/cryptography/>
          <Candidate cryptography 35.0.0 from https://pypi.org/simple/cryptography/>
          <Candidate cryptography 3.4.8 from https://pypi.org/simple/cryptography/>
          <Candidate cryptography 3.4.7 from https://pypi.org/simple/cryptography/>
          <Candidate cryptography 3.4.6 from https://pypi.org/simple/cryptography/>
          <Candidate cryptography 3.4.5 from https://pypi.org/simple/cryptography/>
          <Candidate cryptography 3.4.4 from https://pypi.org/simple/cryptography/>
          <Candidate cryptography 3.4.3 from https://pypi.org/simple/cryptography/>
          <Candidate cryptography 3.4.2 from https://pypi.org/simple/cryptography/>
          ... [1143 more candidate(s)]
Resolving: new pin pyopenssl 22.0.0
======== Ending round 15 ========
======== Starting round 16 ========
Resolving: new pin pysocks 1.7.1
======== Ending round 16 ========
======== Starting round 17 ========
  Adding requirement h11<1,>=0.9.0(from wsproto 1.1.0)
        Found matching candidates:
          <Candidate h11 0.13.0 from https://pypi.org/simple/h11/>
          <Candidate h11 0.12.0 from https://pypi.org/simple/h11/>
          <Candidate h11 0.11.0 from https://pypi.org/simple/h11/>
          <Candidate h11 0.10.0 from https://pypi.org/simple/h11/>
          <Candidate h11 0.9.0 from https://pypi.org/simple/h11/>
Resolving: new pin wsproto 1.1.0
======== Ending round 17 ========
======== Starting round 18 ========
Resolving: new pin pycparser 2.21
======== Ending round 18 ========
======== Starting round 19 ========
Resolving: new pin h11 0.13.0
======== Ending round 19 ========
======== Starting round 20 ========
======== Resolution Result ========
Stable pins:
                 python None
               selenium 4.1.2
                   trio 0.20.0
         trio-websocket 0.9.2
  urllib3[secure,socks] 1.26.8
                certifi 2021.10.8
                outcome 1.1.0
                sniffio 1.2.0
       sortedcontainers 2.4.0
                urllib3 1.26.8
        async-generator 1.10
                  attrs 21.4.0
                   cffi 1.15.0
           cryptography 36.0.1
                   idna 3.3
              pyopenssl 22.0.0
                pysocks 1.7.1
                wsproto 1.1.0
              pycparser 2.21
                    h11 0.13.0
        Found matching candidates:
          <Candidate selenium 4.1.2 from https://pypi.org/simple/selenium/>
        Found matching candidates:
          <Candidate trio 0.20.0 from https://pypi.org/simple/trio/>
        Found matching candidates:
          <Candidate trio-websocket 0.9.2 from https://pypi.org/simple/trio-websocket/>
        Found matching candidates:
          <Candidate urllib3 1.26.8 from https://pypi.org/simple/urllib3/>
        Found matching candidates:
          <Candidate certifi 2021.10.8 from https://pypi.org/simple/certifi/>
        Found matching candidates:
          <Candidate outcome 1.1.0 from https://pypi.org/simple/outcome/>
        Found matching candidates:
          <Candidate sniffio 1.2.0 from https://pypi.org/simple/sniffio/>
        Found matching candidates:
          <Candidate sortedcontainers 2.4.0 from https://pypi.org/simple/sortedcontainers/>
        Found matching candidates:
          <Candidate urllib3 1.26.8 from https://pypi.org/simple/urllib3/>
        Found matching candidates:
          <Candidate async-generator 1.10 from https://pypi.org/simple/async-generator/>
        Found matching candidates:
          <Candidate attrs 21.4.0 from https://pypi.org/simple/attrs/>
        Found matching candidates:
          <Candidate cffi 1.15.0 from https://pypi.org/simple/cffi/>
        Found matching candidates:
          <Candidate cryptography 36.0.1 from https://pypi.org/simple/cryptography/>
        Found matching candidates:
          <Candidate idna 3.3 from https://pypi.org/simple/idna/>
        Found matching candidates:
          <Candidate pyopenssl 22.0.0 from https://pypi.org/simple/pyopenssl/>
        Found matching candidates:
          <Candidate pysocks 1.7.1 from https://pypi.org/simple/pysocks/>
        Found matching candidates:
          <Candidate wsproto 1.1.0 from https://pypi.org/simple/wsproto/>
        Found matching candidates:
          <Candidate pycparser 2.21 from https://pypi.org/simple/pycparser/>
        Found matching candidates:
          <Candidate h11 0.13.0 from https://pypi.org/simple/h11/>
🔒 Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
Synchronizing working set with lock file: 1 to add, 0 to update, 0 to remove

Install selenium 4.1.2 failed
Error occurs:
Traceback (most recent call last):
  File "/home/mimikun/.asdf/installs/python/3.9.6/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/mimikun/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 185, in install_candidate
    self.manager.install(can)
  File "/home/mimikun/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/manager.py", line 39, in install
    installer(prepared.build(), self.environment, prepared.direct_url())
  File "/home/mimikun/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/installers.py", line 176, in install_wheel
    _install_wheel(
  File "/home/mimikun/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/installers.py", line 280, in _install_wheel
    for record_elements, stream in source.get_contents():
  File "/home/mimikun/.local/share/pdm/venv/lib/python3.9/site-packages/installer/sources.py", line 170, in get_contents
    assert record is not None, "In {}, {} is not mentioned in RECORD".format(
AssertionError: In /tmp/pip-unpack-zk4v8x8c/selenium-4.1.2-py3-none-any.whl, selenium/__init__.py is not mentioned in RECORD
  Retry failed jobs
Install selenium 4.1.2 failed
Error occurs:
Traceback (most recent call last):
  File "/home/mimikun/.asdf/installs/python/3.9.6/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/mimikun/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 185, in install_candidate
    self.manager.install(can)
  File "/home/mimikun/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/manager.py", line 39, in install
    installer(prepared.build(), self.environment, prepared.direct_url())
  File "/home/mimikun/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/installers.py", line 176, in install_wheel
    _install_wheel(
  File "/home/mimikun/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/installers.py", line 280, in _install_wheel
    for record_elements, stream in source.get_contents():
  File "/home/mimikun/.local/share/pdm/venv/lib/python3.9/site-packages/installer/sources.py", line 170, in get_contents
    assert record is not None, "In {}, {} is not mentioned in RECORD".format(
AssertionError: In /tmp/pip-unpack-zk4v8x8c/selenium-4.1.2-py3-none-any.whl, selenium/__init__.py is not mentioned in RECORD

ERRORS:
add selenium failed:
Traceback (most recent call last):
  File "/home/mimikun/.asdf/installs/python/3.9.6/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/mimikun/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 185, in install_candidate
    self.manager.install(can)
  File "/home/mimikun/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/manager.py", line 39, in install
    installer(prepared.build(), self.environment, prepared.direct_url())
  File "/home/mimikun/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/installers.py", line 176, in install_wheel
    _install_wheel(
  File "/home/mimikun/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/installers.py", line 280, in _install_wheel
    for record_elements, stream in source.get_contents():
  File "/home/mimikun/.local/share/pdm/venv/lib/python3.9/site-packages/installer/sources.py", line 170, in get_contents
    assert record is not None, "In {}, {} is not mentioned in RECORD".format(
AssertionError: In /tmp/pip-unpack-zk4v8x8c/selenium-4.1.2-py3-none-any.whl, selenium/__init__.py is not mentioned in RECORD

Traceback (most recent call last):
  File "/home/mimikun/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/mimikun/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/core.py", line 233, in main
    return Core().main(args)
  File "/home/mimikun/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/core.py", line 168, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/home/mimikun/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/core.py", line 163, in main
    f(options.project, options)
  File "/home/mimikun/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/cli/commands/add.py", line 53, in handle
    actions.do_add(
  File "/home/mimikun/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/cli/actions.py", line 245, in do_add
    do_sync(
  File "/home/mimikun/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/cli/actions.py", line 190, in do_sync
    handler.synchronize()
  File "/home/mimikun/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 352, in synchronize
    raise InstallationError("Some package operations are not complete yet")
pdm.exceptions.InstallationError: Some package operations are not complete yet
```

## Expected behavior

Successfully add `selenium`

## Environment Information

```shell
/tmp/test via  v3.9.6 took 2s
➜ pdm info && pdm info --env
PDM version:        1.13.3
Python Interpreter: /home/mimikun/.asdf/installs/python/3.9.6/bin/python3.9 (3.9)
Project Root:       /tmp/test
Project Packages:   /tmp/test/__pypackages__/3.9
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.6",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.10.60.1-microsoft-standard-WSL2",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Wed Aug 25 23:20:18 UTC 2021",
  "python_full_version": "3.9.6",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
Duplicate #728

**Comment by ElijahSink** [comment]
This has been resolved by selenium.

https://github.com/SeleniumHQ/selenium/issues/10022#issuecomment-1063033886
