### ISSUE TITLE
Unable to init project in PyCharm Terminal or CMD, raise UnicodeDecodeError: 'gbk' codec

### ISSUE THREAD

**Issue by piscesvivian** [pdm-project/pdm#960]
- [ ] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

```cmd
(pulsar) D:\Project\scdi\scdi-simulator>pdm init -v
Creating a pyproject.toml for PDM...
Using Python interpreter: C:\ProgramData\Anaconda3\envs\pulsar\python.EXE (3.8)
Is the project a library that will be uploaded to PyPI? [y/N]:
License(SPDX name) [MIT]:
Traceback (most recent call last):
  File "c:\programdata\anaconda3\envs\pulsar\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\programdata\anaconda3\envs\pulsar\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\pulsar\Scripts\pdm.exe\__main__.py", line 7, in <module>
  File "c:\programdata\anaconda3\envs\pulsar\lib\site-packages\pdm\core.py", line 233, in main
    return Core().main(args)
  File "c:\programdata\anaconda3\envs\pulsar\lib\site-packages\pdm\core.py", line 168, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "c:\programdata\anaconda3\envs\pulsar\lib\site-packages\pdm\core.py", line 163, in main
    f(options.project, options)
  File "c:\programdata\anaconda3\envs\pulsar\lib\site-packages\pdm\cli\commands\init.py", line 61, in handle
    git_user, git_email = get_user_email_from_git()
  File "c:\programdata\anaconda3\envs\pulsar\lib\site-packages\pdm\utils.py", line 256, in get_user_email_from_git
    username = subprocess.check_output(
  File "c:\programdata\anaconda3\envs\pulsar\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "c:\programdata\anaconda3\envs\pulsar\lib\subprocess.py", line 491, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "c:\programdata\anaconda3\envs\pulsar\lib\subprocess.py", line 1011, in communicate
    stdout = self.stdout.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 4: illegal multibyte sequence
```
## Actual behavior

UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 4: illegal multibyte sequence

## Expected behavior

should init successful

## Environment Information

Git project username is english, email adress is like name123@company.com.cn

```bash
# Paste the output of `pdm info && pdm info --env` below:

```

**Comment by piscesvivian** [comment]
highly efficient :smile:
