### ISSUE TITLE
Cannot install selenium==4.1.2

### ISSUE THREAD

**Issue by ElijahSink** [pdm-project/pdm#963]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

```
❯ pdm add selenium~=4.1
```
## Actual behavior
```
Adding packages to default dependencies: selenium
<verbose locking omitted>
✔ 🔒 Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
Synchronizing working set with lock file: 1 to add, 0 to update, 0 to remove

Install selenium 4.1.2 failed
Error occurs:
Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ejsink/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 185, in install_candidate
    self.manager.install(can)
  File "/home/ejsink/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/installers/manager.py", line 38, in install
    installer(candidate.build(), self.environment, candidate.direct_url())
  File "/home/ejsink/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/installers/installers.py", line 176, in install_wheel
    _install_wheel(
  File "/home/ejsink/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/installers/installers.py", line 280, in _install_wheel
    for record_elements, stream in source.get_contents():
  File "/home/ejsink/.local/pipx/venvs/pdm/lib/python3.10/site-packages/installer/sources.py", line 170, in get_contents
    assert record is not None, "In {}, {} is not mentioned in RECORD".format(
AssertionError: In /tmp/pip-unpack-f5lsx6y8/selenium-4.1.2-py3-none-any.whl, selenium/__init__.py is not mentioned in RECORD
  Retry failed jobs
Install selenium 4.1.2 failed
Error occurs:
Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ejsink/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 185, in install_candidate
    self.manager.install(can)
  File "/home/ejsink/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/installers/manager.py", line 38, in install
    installer(candidate.build(), self.environment, candidate.direct_url())
  File "/home/ejsink/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/installers/installers.py", line 176, in install_wheel
    _install_wheel(
  File "/home/ejsink/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/installers/installers.py", line 280, in _install_wheel
    for record_elements, stream in source.get_contents():
  File "/home/ejsink/.local/pipx/venvs/pdm/lib/python3.10/site-packages/installer/sources.py", line 170, in get_contents
    assert record is not None, "In {}, {} is not mentioned in RECORD".format(
AssertionError: In /tmp/pip-unpack-f5lsx6y8/selenium-4.1.2-py3-none-any.whl, selenium/__init__.py is not mentioned in RECORD

ERRORS:
add selenium failed:
Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ejsink/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 185, in install_candidate
    self.manager.install(can)
  File "/home/ejsink/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/installers/manager.py", line 38, in install
    installer(candidate.build(), self.environment, candidate.direct_url())
  File "/home/ejsink/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/installers/installers.py", line 176, in install_wheel
    _install_wheel(
  File "/home/ejsink/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/installers/installers.py", line 280, in _install_wheel
    for record_elements, stream in source.get_contents():
  File "/home/ejsink/.local/pipx/venvs/pdm/lib/python3.10/site-packages/installer/sources.py", line 170, in get_contents
    assert record is not None, "In {}, {} is not mentioned in RECORD".format(
AssertionError: In /tmp/pip-unpack-f5lsx6y8/selenium-4.1.2-py3-none-any.whl, selenium/__init__.py is not mentioned in RECORD

Traceback (most recent call last):
  File "/home/ejsink/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/ejsink/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/core.py", line 226, in main
    return Core().main(args)
  File "/home/ejsink/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/core.py", line 161, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/home/ejsink/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/core.py", line 156, in main
    f(options.project, options)
  File "/home/ejsink/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/cli/commands/add.py", line 53, in handle
    actions.do_add(
  File "/home/ejsink/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/cli/actions.py", line 247, in do_add
    do_sync(
  File "/home/ejsink/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/cli/actions.py", line 191, in do_sync
    handler.synchronize()
  File "/home/ejsink/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 352, in synchronize
    raise InstallationError("Some package operations are not complete yet")
pdm.exceptions.InstallationError: Some package operations are not complete yet
```

## Expected behavior
PDM should install selenium correctly.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
❯ pdm info && pdm info --env
PDM version:        1.13.3
Python Interpreter: /usr/bin/python (3.10)
Project Root:       /home/ejsink/CFRL/test
Project Packages:   /home/ejsink/CFRL/test/__pypackages__/3.10
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.2",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "4.19.128-microsoft-standard",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Tue Jun 23 12:58:10 UTC 2020",
  "python_full_version": "3.10.2",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "linux"
}
```

Obviously the issue has something to do with malformed metadata in `selenium`'s wheel files, but pip is able to install it correctly. Perhaps this is actually something that should be fixed in `installer`?

**Comment by frostming** [comment]
Duplicate with #728

**Comment by ElijahSink** [comment]
This has been resolved by selenium.

https://github.com/SeleniumHQ/selenium/issues/10022#issuecomment-1063033886
