### ISSUE TITLE
pdm-pep517 breaking change released yesterday causing: pdm.pep517.exceptions.MetadataError: license-expression: ['Unknown license key(s): NA']

### ISSUE THREAD

**Issue by canopus1io** [pdm-project/pdm#964]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

If you are experiencing this error all of a sudden, see workaround at the end. This issue is mainly to help others experiencing this issue and to highlight it to pdm dev team

This was working 24 hours ago with no changes, but 14hrs ago there was a major release for pdm-pep517 that introduced apparently introduced some breaking changes. Also note that when you do `pdm init`, the version of pdm-pep517 is not even locked to the current major version

```zsh
> pdm sync -v
All packages are synced to date, nothing to do.

Installing the project as an editable package...
Preparing isolated env for PEP 517 build...
Building wheel for file:///home/can/projects/opus1io#egg=opus1io
Collecting pdm-pep517
  Using cached pdm_pep517-0.12.0-py3-none-any.whl (302 kB)
Installing collected packages: pdm-pep517
Successfully installed pdm-pep517-0.12.0
/tmp/pdm-build-env-sbgoyjyn-shared/lib/python3.8/site-packages/pdm/pep517/base.py:367: PDMWarning: 'license' field is deprecated in favor of 'license-expression'
  license=meta.license_expression or "UNKNOWN",
 - Adding opus1io.pth
 - Adding opus1io-0.1.dist-info/WHEEL
Traceback (most recent call last):
  File "/home/can/.local/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 349, in <module>
    main()
  File "/home/can/.local/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 331, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/home/can/.local/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 270, in build_editable
    return hook(wheel_directory, config_settings, metadata_directory)
  File "/tmp/pdm-build-env-sbgoyjyn-shared/lib/python3.8/site-packages/pdm/pep517/api.py", line 98, in build_editable
    return Path(builder.build(wheel_directory)).name
  File "/tmp/pdm-build-env-sbgoyjyn-shared/lib/python3.8/site-packages/pdm/pep517/wheel.py", line 76, in build
    self._write_metadata(zip_file)
  File "/tmp/pdm-build-env-sbgoyjyn-shared/lib/python3.8/site-packages/pdm/pep517/wheel.py", line 147, in _write_metadata
    self._write_metadata_file(f)
  File "/tmp/pdm-build-env-sbgoyjyn-shared/lib/python3.8/site-packages/pdm/pep517/editable.py", line 156, in _write_metadata_file
    return super()._write_metadata_file(fp)
  File "/tmp/pdm-build-env-sbgoyjyn-shared/lib/python3.8/site-packages/pdm/pep517/wheel.py", line 261, in _write_metadata_file
    fp.write(self.format_pkginfo())
  File "/tmp/pdm-build-env-sbgoyjyn-shared/lib/python3.8/site-packages/pdm/pep517/base.py", line 367, in format_pkginfo
    license=meta.license_expression or "UNKNOWN",
  File "/tmp/pdm-build-env-sbgoyjyn-shared/lib/python3.8/site-packages/pdm/pep517/metadata.py", line 247, in license_expression
    return normalize_expression(self._metadata["license"]["text"])
  File "/tmp/pdm-build-env-sbgoyjyn-shared/lib/python3.8/site-packages/pdm/pep517/license.py", line 29, in normalize_expression
    raise MetadataError("license-expression", validate_result.errors)
pdm.pep517.exceptions.MetadataError: license-expression: ['Unknown license key(s): NA']
Install opus1io 0.1 failed
Traceback (most recent call last):
  File "/home/can/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/can/.local/lib/python3.8/site-packages/pdm/core.py", line 233, in main
    return Core().main(args)
  File "/home/can/.local/lib/python3.8/site-packages/pdm/core.py", line 168, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/home/can/.local/lib/python3.8/site-packages/pdm/core.py", line 163, in main
    f(options.project, options)
  File "/home/can/.local/lib/python3.8/site-packages/pdm/cli/commands/sync.py", line 26, in handle
    actions.do_sync(
  File "/home/can/.local/lib/python3.8/site-packages/pdm/cli/actions.py", line 190, in do_sync
    handler.synchronize()
  File "/home/can/.local/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 367, in synchronize
    self.install_candidate(self_key)
  File "/home/can/.local/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 185, in install_candidate
    self.manager.install(can)
  File "/home/can/.local/lib/python3.8/site-packages/pdm/installers/manager.py", line 39, in install
    installer(prepared.build(), self.environment, prepared.direct_url())
  File "/home/can/.local/lib/python3.8/site-packages/pdm/models/candidates.py", line 332, in build
    self.wheel = builder.build(build_dir, metadata_directory=self._metadata_dir)
  File "/home/can/.local/lib/python3.8/site-packages/pdm/builders/editable.py", line 52, in build
    filename = self._hook.build_editable(
  File "/home/can/.local/lib/python3.8/site-packages/pep517/wrappers.py", line 257, in build_editable
    return self._call_hook('build_editable', {
  File "/home/can/.local/lib/python3.8/site-packages/pep517/wrappers.py", line 318, in _call_hook
    self._subprocess_runner(
  File "/home/can/.local/lib/python3.8/site-packages/pdm/builders/base.py", line 238, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
  File "/home/can/.local/lib/python3.8/site-packages/pdm/builders/base.py", line 86, in log_subprocessor
    raise BuildError(
pdm.exceptions.BuildError: Call command ['/usr/bin/python3.8', '/home/can/.local/lib/python3.8/site-packages/pep517/in_process/_in_process.py', 'build_editable', '/tmp/tmpav3pp2pq'] return non-zero status(1).
```

## Steps to reproduce

1) create a directory with this file:
pyproject.toml:
```
[project]
name = "min_repro"
version = "0.1"
description = "min reproduction"
authors = [
    {name = "Can Yildirim", email = "test@test.com"},
]
dependencies = [
    "ipython>=8.1.1",
]
requires-python = "~=3.8.10"
license = {text = "NA"}

[project.urls]
Homepage = ""

[tool]
[tool.pdm]

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

```
2) run `pdm install -v`
3) observe same error

## Actual behavior

get an error for something that worked 24 hrs ago

## Expected behavior

no error

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.13.3
Python Interpreter: /usr/bin/python3.8 (3.8)
Project Root:       /home/can/projects/pdm_min_repro
Project Packages:   /home/can/projects/pdm_min_repro/__pypackages__/3.8
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.10",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.4.0-104-generic",
  "platform_system": "Linux",
  "platform_version": "#118-Ubuntu SMP Wed Mar 2 19:02:41 UTC 2022",
  "python_full_version": "3.8.10",
  "platform_python_implementation": "CPython",
  "python_version": "3.8",
  "sys_platform": "linux"
}

```

## Workaround

lock version of pdm-pep517 by updating the following in your pyproject.toml
```
# ...
[build-system]
requires = ["pdm-pep517==0.11.2"] # added ==0.11.2
build-backend = "pdm.pep517.api"
```

**Comment by frostming** [comment]
Not a bug, from `pdm.pep517>=0.12.0` license identifiers are validated with the list https://spdx.org/licenses/
