### ISSUE TITLE
pdm add torchvision failed

### ISSUE THREAD

**Issue by extremety1989** [pdm-project/pdm#974]
i run " pdm add pytorch torchaudio torchvision "

Install torchvision 0.12.0 failed

windows 11 
python version 3.10

``` ERRORS:
add torchvision failed:
Traceback (most recent call last):
  File "C:\Users\andre\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\andre\AppData\Roaming\pdm\venv\lib\site-packages\pdm\installers\synchronizers.py", line 185, in install_candidate
    self.manager.install(can)
  File "C:\Users\andre\AppData\Roaming\pdm\venv\lib\site-packages\pdm\installers\manager.py", line 39, in install
    installer(prepared.build(), self.environment, prepared.direct_url())
  File "C:\Users\andre\AppData\Roaming\pdm\venv\lib\site-packages\pdm\installers\installers.py", line 176, in install_wheel
    _install_wheel(
  File "C:\Users\andre\AppData\Roaming\pdm\venv\lib\site-packages\pdm\installers\installers.py", line 280, in _install_wheel
    for record_elements, stream in source.get_contents():
  File "C:\Users\andre\AppData\Roaming\pdm\venv\lib\site-packages\installer\sources.py", line 170, in get_contents
    assert record is not None, "In {}, {} is not mentioned in RECORD".format(
AssertionError: In C:\Users\andre\AppData\Local\Temp\pip-unpack-p36mvq4_\torchvision-0.12.0-cp310-cp310-win_amd64.whl, torchvision-0.12.0.dist-info/LICENSE is not mentioned in RECORD
add pytorch failed:
Traceback (most recent call last):
  File "C:\Users\andre\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\andre\AppData\Roaming\pdm\venv\lib\site-packages\pdm\installers\synchronizers.py", line 185, in install_candidate
    self.manager.install(can)
  File "C:\Users\andre\AppData\Roaming\pdm\venv\lib\site-packages\pdm\installers\manager.py", line 39, in install
    installer(prepared.build(), self.environment, prepared.direct_url())
  File "C:\Users\andre\AppData\Roaming\pdm\venv\lib\site-packages\pdm\models\candidates.py", line 332, in build
    self.wheel = builder.build(build_dir, metadata_directory=self._metadata_dir)
  File "C:\Users\andre\AppData\Roaming\pdm\venv\lib\site-packages\pdm\builders\wheel.py", line 28, in build
    filename = self._hook.build_wheel(out_dir, config_settings, metadata_directory)
  File "C:\Users\andre\AppData\Roaming\pdm\venv\lib\site-packages\pep517\wrappers.py", line 208, in build_wheel
    return self._call_hook('build_wheel', {
  File "C:\Users\andre\AppData\Roaming\pdm\venv\lib\site-packages\pep517\wrappers.py", line 322, in _call_hook
    self._subprocess_runner(
  File "C:\Users\andre\AppData\Roaming\pdm\venv\lib\site-packages\pdm\builders\base.py", line 238, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
  File "C:\Users\andre\AppData\Roaming\pdm\venv\lib\site-packages\pdm\builders\base.py", line 86, in log_subprocessor
    raise BuildError(
pdm.exceptions.BuildError: Call command ['C:/Users/andre/AppData/Local/Programs/Python/Python310/python.EXE', 'C:\\Users\\andre\\AppData\\Roaming\\pdm\\venv\\lib\\site-packages\\pep517\\in_process\\_in_process.py', 'build_wheel', 'C:\\Users\\andre\\AppData\\Local\\Temp\\tmp5kx65olz'] return non-zero status(1).```

**Comment by frostming** [comment]
Same cause as #728

**Comment by extremety1989** [comment]
@frostming so i should install it with pip ?

**Comment by frostming** [comment]
@extremety1989 Use the workaround in the issue or report it to torch and wait for a fix.

**Comment by bingoct** [comment]
install torchvision 1.13.1 and 1.14.0 failed
pdm version 2.2.1
[https://github.com/pytorch/vision/issues/6869](https://github.com/pytorch/vision/issues/6869)
[https://github.com/pytorch/vision/issues/5371](https://github.com/pytorch/vision/issues/5371)
