### ISSUE TITLE
AttributionError: version when doing pdm init

### ISSUE THREAD

**Issue by KivenCkl** [pdm-project/pdm#979]
- [ x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

just type pdm init

## Actual behavior

```
$ pdm init -v
Creating a pyproject.toml for PDM...
Traceback (most recent call last):
  File "c:\users\kailunch\.pyenv\pyenv-win\versions\3.8.6\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\kailunch\.pyenv\pyenv-win\versions\3.8.6\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\users\kailunch\.local\bin\pdm.exe\__main__.py", line 7, in <module>
  File "C:\Users\kailunch\.local\pipx\venvs\pdm\lib\site-packages\pdm\core.py", line 233, in main
    return Core().main(args)
  File "C:\Users\kailunch\.local\pipx\venvs\pdm\lib\site-packages\pdm\core.py", line 168, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "C:\Users\kailunch\.local\pipx\venvs\pdm\lib\site-packages\pdm\core.py", line 163, in main
    f(options.project, options)
  File "C:\Users\kailunch\.local\pipx\venvs\pdm\lib\site-packages\pdm\cli\commands\init.py", line 46, in handle
    actions.do_use(project)
  File "C:\Users\kailunch\.local\pipx\venvs\pdm\lib\site-packages\pdm\cli\actions.py", line 560, in do_use
    found_interpreters = list(dict.fromkeys(project.find_interpreters(python)))
  File "C:\Users\kailunch\.local\pipx\venvs\pdm\lib\site-packages\pdm_venv\plugin.py", line 34, in find_interpreters
    yield from super().find_interpreters(python_spec)
  File "C:\Users\kailunch\.local\pipx\venvs\pdm\lib\site-packages\pdm\project\core.py", line 610, in find_interpreters
    for entry in finder.find_all(*args):
  File "C:\Users\kailunch\.local\pipx\venvs\pdm\lib\site-packages\findpython\finder.py", line 94, in find_all
    matched_python = set(self._find_all_python_versions())
  File "C:\Users\kailunch\.local\pipx\venvs\pdm\lib\site-packages\findpython\finder.py", line 127, in _find_all_python_versions
    yield from provider.find_pythons()
  File "C:\Users\kailunch\.local\pipx\venvs\pdm\lib\site-packages\findpython\providers\pep514.py", line 40, in find_pythons
    parse_version(version.info.version),
  File "C:\Users\kailunch\.local\pipx\venvs\pdm\lib\site-packages\findpython\_vendor\pep514tools\_registry.py", line 93, in __getattr__
    raise AttributeError(attr)
AttributeError: version
```

## Expected behavior

normal initialization

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
$ pdm --version
Python Development Master (PDM), version 1.13.4

```
os: win server 2016
pyenv-win
python 3.8.6

**Comment by KivenCkl** [comment]
I have solved it. The root cause is the conflict between `pdm-venv` and `Enable PEP 582 globally`. So when I disabled PEP 582, everything is ok.
