### ISSUE TITLE
ModuleNotFoundError: No module named 'pdm'

### ISSUE THREAD

**Issue by nihilox** [pdm-project/pdm#983]
## Steps to reproduce

```
> pdm add httpx
Adding packages to default dependencies: httpx
✔ 🔒 Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
Synchronizing working set with lock file: 9 to add, 0 to update, 0 to remove

  ✔ Install anyio 3.5.0 successful
  ✔ Install certifi 2021.10.8 successful
  ✔ Install charset-normalizer 2.0.12 successful
  ✔ Install h11 0.12.0 successful
  ✔ Install httpcore 0.14.7 successful
  ✔ Install httpx 0.22.0 successful
  ✔ Install idna 3.3 successful
  ✔ Install rfc3986 2.0.0 successful
  ✔ Install sniffio 1.2.0 successful
Installing the project as an editable package...
  ✖ Install demo 0.1.0 failed
  See /tmp/pdm-install-d1u386lb.log for detailed debug log.
  [BackendUnavailable]: Traceback (most recent call last):
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 89, in _build_backend
    obj = import_module(mod_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pdm'
```

```
> pdm run python
Python 3.10.3 (main, Mar 16 2022, 16:15:16) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/tmp/demo/__pypackages__/3.10/lib']
>>>
```

```
> pdm run python -m site
sys.path = [
    '/tmp/demo',
    '/usr/lib/python310.zip',
    '/usr/lib/python3.10',
    '/usr/lib/python3.10/lib-dynload',
    '/tmp/demo/__pypackages__/3.10/lib',
    '/home/ubuntu/.local/lib/python3.10/site-packages',
    '/usr/local/lib/python3.10/dist-packages',
    '/usr/lib/python3/dist-packages',
]
USER_BASE: '/home/ubuntu/.local' (exists)
USER_SITE: '/home/ubuntu/.local/lib/python3.10/site-packages' (exists)
ENABLE_USER_SITE: True
```

```
> python3.10
Python 3.10.3 (main, Mar 16 2022, 16:15:16) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/ubuntu/.local/lib/python3.10/site-packages', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages']
>>>
```

/tmp/pdm-install-d1u386lb.log
```
Preparing isolated env for PEP 517 build...
Building wheel for file:///tmp/demo#egg=demo
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting pdm-pep517>=0.12.0
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/af/af/c9007f9e8afccc45e986d044b9921c69e189427b818edb28f1149bad02e6/pdm_pep517-0.12.1-py3-none-any.whl (302 kB)
Installing collected packages: pdm-pep517
Successfully installed pdm-pep517-0.12.1
Error occurs
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/termui.py", line 200, in logging
    yield logger
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 367, in synchronize
    self.install_candidate(self_key)
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 185, in install_candidate
    self.manager.install(can)
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/installers/manager.py", line 39, in install
    installer(prepared.build(), self.environment, prepared.direct_url())
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/models/candidates.py", line 332, in build
    self.wheel = builder.build(build_dir, metadata_directory=self._metadata_dir)
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.10/site-packages/pdm/builders/editable.py", line 50, in build
    requires = self._hook.get_requires_for_build_editable(config_settings)
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.10/site-packages/pep517/wrappers.py", line 225, in get_requires_for_build_editable
    return self._call_hook('get_requires_for_build_editable', {
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.10/site-packages/pep517/wrappers.py", line 332, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/home/ubuntu/.local/share/pdm/venv/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 89, in _build_backend
    obj = import_module(mod_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pdm'
```

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:

```

**Comment by abersheeran** [comment]
Maybe https://github.com/deadsnakes/issues/issues/182 would be help you.

**Comment by frostming** [comment]
Does `/usr/bin/python3.10` has `pip` installed with it?

You can get it by `/usr/bin/python3.10 -Im pip --version`

**Comment by nihilox** [comment]
`pip 22.0.4 from /usr/local/lib/python3.10/dist-packages/pip (python 3.10)`

installed by `sudo python3.10 -m ensurepip`

**Comment by frostming** [comment]
`python` installed from debian packages or deadsnakes doesn't provide `ensurepip`.

**Comment by nihilox** [comment]
This fix seems to break brew's pdm package
