### ISSUE TITLE
Fail to use flake8 with pdm run

### ISSUE THREAD

**Issue by SirMartin** [pdm-project/pdm#990]
Hi, I am trying to test the usage of PDM for some projects, I made an example one. It works perfectly with _pip_ and also with _pipenv_, everything was painless with PDM too until I try to run the **flake8** linter.

If I run directly `flake8 myfile.py` it cannot find the flake8 command, that's ok, I got the same error with _pipenv_, but with _pipenv_ I was able to run it with `pipenv run flake8 myfile.py`, so I tried in the same way with PDM, using `pdm run`, but I got the error that cannot find _flake8_

```
root@ba68f6e2b3e6:/src# pdm run -v flake8 
Traceback (most recent call last):
  File "/usr/local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/pdm/core.py", line 233, in main
    return Core().main(args)
  File "/usr/local/lib/python3.9/site-packages/pdm/core.py", line 168, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/usr/local/lib/python3.9/site-packages/pdm/core.py", line 163, in main
    f(options.project, options)
  File "/usr/local/lib/python3.9/site-packages/pdm/cli/commands/run.py", line 281, in handle
    sys.exit(runner.run(options.command, options.args))
  File "/usr/local/lib/python3.9/site-packages/pdm/cli/commands/run.py", line 219, in run
    return self._run_process(
  File "/usr/local/lib/python3.9/site-packages/pdm/cli/commands/run.py", line 154, in _run_process
    process = subprocess.Popen(expanded_args, cwd=cwd, env=process_env, shell=shell)
  File "/usr/local/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/src/__pypackages__/3.9/bin/flake8'
root@ba68f6e2b3e6:/src# pdm run __pypackages__/3.9/bin/flake8 
[FileNotFoundError]: [Errno 2] No such file or directory: '__pypackages__/3.9/bin/flake8'

```

The file is correctly there placed, but pdm cannot find it.

What I am doing wrong?

**Comment by SirMartin** [comment]
Hi @frostming I published here the example, so you can test it, don't hesitate to ask me if you have any question. [](https://github.com/SirMartin/pdm_test)

**Comment by frostming** [comment]
Here is the output of `make run`, no errors
```
❯ make run
docker build -t pip-assembler-demo .
[+] Building 78.9s (13/13) FINISHED
 => [internal] load build definition from Dockerfile                                                                                 0.0s
 => => transferring dockerfile: 332B                                                                                                 0.0s
 => [internal] load .dockerignore                                                                                                    0.0s
 => => transferring context: 2B                                                                                                      0.0s
 => [internal] load metadata for docker.io/library/python:3.9.7-slim                                                                 4.4s
 => [1/8] FROM docker.io/library/python:3.9.7-slim@sha256:aef632387d994b410de020dfd08fb1d9b648fc8a5a44f332f7ee326c8e170dba          50.8s
 => => resolve docker.io/library/python:3.9.7-slim@sha256:aef632387d994b410de020dfd08fb1d9b648fc8a5a44f332f7ee326c8e170dba           0.0s
 => => sha256:aef632387d994b410de020dfd08fb1d9b648fc8a5a44f332f7ee326c8e170dba 1.86kB / 1.86kB                                       0.0s
 => => sha256:8dc561d82a4316e3800c1e6a87ac3efac8a04c49e03be7253f8026154d4de31c 1.37kB / 1.37kB                                       0.0s
 => => sha256:80c120ec5f295e9649ef4c0cff6ae8376e289c904747ba9970141adb2f91c1f0 7.89kB / 7.89kB                                       0.0s
 => => sha256:a9eb63951c1c2ee8efcc12b696928fee3741a2d4eae76f2da3e161a5d90548bf 30.04MB / 30.04MB                                    49.2s
 => => sha256:1667ee600553d3aa2346011cc4c152be900692f0ddf4d880b56faa92ba861743 1.06MB / 1.06MB                                       6.1s
 => => sha256:563732f71a51196d3c5de26851b70f9c00d82d28387f6e2139fda83ccae4550a 11.01MB / 11.01MB                                    26.0s
 => => sha256:df499e3a27b16cf540f7e244bdfe5790fc0010e177f7d6b9707435e52eda86f8 233B / 233B                                           6.7s
 => => sha256:8549f1c537844fca3793ebd527c61e31f5e7fe79e80deac25a8f5df9dbcd0898 2.43MB / 2.43MB                                      15.6s
 => => extracting sha256:a9eb63951c1c2ee8efcc12b696928fee3741a2d4eae76f2da3e161a5d90548bf                                            0.8s
 => => extracting sha256:1667ee600553d3aa2346011cc4c152be900692f0ddf4d880b56faa92ba861743                                            0.1s
 => => extracting sha256:563732f71a51196d3c5de26851b70f9c00d82d28387f6e2139fda83ccae4550a                                            0.3s
 => => extracting sha256:df499e3a27b16cf540f7e244bdfe5790fc0010e177f7d6b9707435e52eda86f8                                            0.0s
 => => extracting sha256:8549f1c537844fca3793ebd527c61e31f5e7fe79e80deac25a8f5df9dbcd0898                                            0.1s
 => [internal] load build context                                                                                                    0.0s
 => => transferring context: 86.92kB                                                                                                 0.0s
 => [2/8] RUN set -ex     && apt-get update     && pip3 install --no-cache --upgrade pdm                                            17.6s
 => [3/8] WORKDIR /src                                                                                                               0.0s
 => [4/8] COPY . ./                                                                                                                  0.0s
 => [5/8] RUN pdm install                                                                                                            4.8s
 => [6/8] RUN pdm run -v flake8 --ignore=E501,W503 assembler.py                                                                      0.7s
 => [7/8] RUN python assembler.py examples/code.txt                                                                                  0.1s
 => [8/8] RUN python assembler.py examples/test.txt                                                                                  0.3s
 => exporting to image                                                                                                               0.2s
 => => exporting layers                                                                                                              0.2s
 => => writing image sha256:dd27b6c0e1f7dc9de12175c3ac1b17e0253645079a180f6a058fbade0a28913d                                         0.0s
 => => naming to docker.io/library/pip-assembler-demo                                                                                0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
docker run pip-assembler-demo
```

**Comment by SirMartin** [comment]
Hi, thanks for the answer.

I found the reason for my errors. The problem it seem because I made the `pdm install` locally and later ran the docker, because of that the `__pypackages__` folder was copied to the container and failed when I run it.

Have this sense? I understand that has no meaning and it was my mistake.

Thanks

**Comment by pawamoy** [comment]
If you're working on Windows and copied `__pypackages__` into the image, then yes, it would never have worked. Try to only copy the relevant files into your image, not the whole repository. There's an example here: https://pdm.fming.dev/usage/advanced/#use-pdm-in-a-multi-stage-dockerfile

I believe this can be closed, thank you for reporting back @SirMartin 🙂
