### ISSUE TITLE
ModuleNotFoundError: No module named 'pdm'

### ISSUE THREAD

**Issue by nihilox** [pdm-project/pdm#996]
Seems due to the fix to #983

```
Installing the project as an editable package...
Preparing isolated env for PEP 517 build...
Building wheel for file:///private/tmp/demo#egg=demo
Looking in indexes: https://mirror.sjtu.edu.cn/pypi/web/simple
Collecting pdm-pep517>=0.12.0
  Using cached https://mirror.sjtu.edu.cn/pypi-packages/af/af/c9007f9e8afccc45e986d044b9921c69e189427b818edb28f1149bad02e6/pdm_pep517-0.12.1-py3-none-any.whl (302 kB)
Installing collected packages: pdm-pep517
Successfully installed pdm-pep517-0.12.1
WARNING: You are using pip version 22.0.2; however, version 22.0.4 is available.
You should consider upgrading via the '/opt/homebrew/opt/python@3.10/bin/python3.10 -m pip install --upgrade pip' command.
Install demo 0.1.0 failed
Traceback (most recent call last):
  File "/Users/.../Library/Python/3.10/bin/pdm", line 10, in <module>
    sys.exit(main())
  File "/Users/.../Library/Application Support/pdm/venv/lib/python3.10/site-packages/pdm/core.py", line 233, in main
    return Core().main(args)
  File "/Users/.../Library/Application Support/pdm/venv/lib/python3.10/site-packages/pdm/core.py", line 168, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/Users/.../Library/Application Support/pdm/venv/lib/python3.10/site-packages/pdm/core.py", line 163, in main
    f(options.project, options)
  File "/Users/.../Library/Application Support/pdm/venv/lib/python3.10/site-packages/pdm/cli/commands/add.py", line 53, in handle
    actions.do_add(
  File "/Users/.../Library/Application Support/pdm/venv/lib/python3.10/site-packages/pdm/cli/actions.py", line 245, in do_add
    do_sync(
  File "/Users/.../Library/Application Support/pdm/venv/lib/python3.10/site-packages/pdm/cli/actions.py", line 190, in do_sync
    handler.synchronize()
  File "/Users/.../Library/Application Support/pdm/venv/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 367, in synchronize
    self.install_candidate(self_key)
  File "/Users/.../Library/Application Support/pdm/venv/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 185, in install_candidate
    self.manager.install(can)
  File "/Users/.../Library/Application Support/pdm/venv/lib/python3.10/site-packages/pdm/installers/manager.py", line 39, in install
    installer(prepared.build(), self.environment, prepared.direct_url())
  File "/Users/.../Library/Application Support/pdm/venv/lib/python3.10/site-packages/pdm/models/candidates.py", line 332, in build
    self.wheel = builder.build(build_dir, metadata_directory=self._metadata_dir)
  File "/Users/.../Library/Application Support/pdm/venv/lib/python3.10/site-packages/pdm/builders/editable.py", line 50, in build
    requires = self._hook.get_requires_for_build_editable(config_settings)
  File "/Users/.../Library/Application Support/pdm/venv/lib/python3.10/site-packages/pep517/wrappers.py", line 225, in get_requires_for_build_editable
    return self._call_hook('get_requires_for_build_editable', {
  File "/Users/.../Library/Application Support/pdm/venv/lib/python3.10/site-packages/pep517/wrappers.py", line 332, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/Users/.../Library/Application Support/pdm/venv/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 90, in _build_backend
    obj = import_module(mod_path)
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pdm'
```

`sys.path`
```
['/Users/.../Library/Application Support/pdm/venv/lib/python3.10/site-packages/pep517/in_process', '/var/folders/92/lyb6xpz91cndl9jbdrbsl7200000gn/T/pdm-build-env-6tr5d4zl-shared/site', '/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python310.zip', '/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10', '/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/lib-dynload', '/opt/homebrew/lib/python3.10/site-packages']
```

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.13.5
Python Interpreter: /opt/homebrew/opt/python@3.10/bin/python3.10 (3.10)
Project Root:       /private/tmp/demo
Project Packages:   /private/tmp/demo/__pypackages__/3.10
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.2",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "21.2.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000",
  "python_full_version": "3.10.2",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
It is unclear what the output you pasted means and what is the problem.

**Comment by nihilox** [comment]
PDM>=1.13.5

**Comment by frostming** [comment]
Can't reproduce, the fix of #983 doesn't affect MacOS

**Comment by nihilox** [comment]
https://asciinema.org/a/kgJwQViDv6iCQ8N8Ow0fYMt0d

**Comment by frostming** [comment]
This doesn't help, I can also record a video of how it works. Something worth trying:

```python
>>> import sysconfig
>>> print(sysconfig.get_paths(vars={'base': 'abc', 'platbase': 'abc'}))
```
Try the above in both `/opt/homebrew/opt/python@3.10/bin/python3.10` and `/opt/homebrew/opt/pdm/libexec/bin/python`

**Comment by frostming** [comment]
Here is the thing:
`/opt/homebrew/opt/python@3.10/bin/python3.10`
```
'purelib': '/opt/homebrew/lib/python3.10/site-packages', 'platlib': '/opt/homebrew/lib/python3.10/site-packages'
```
they are not substituted with `abc` prefix.

**Comment by frostming** [comment]
Jeez! the python3.10 from homebrew seems to have been specially patched. I tried python3.9 from homebrew and all work fine.
