### ISSUE TITLE
Failed to install module "parallely" with python3.8

### ISSUE THREAD

**Issue by BigNuoLi** [pdm-project/pdm#998]
- [X ] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

```bash
❯ pdm add parallely -v
Adding packages to default dependencies: parallely
======== Start resolving requirements ========
  parallely
  python>=3.8
  Adding requirement parallely
        Found matching candidates:
          <Candidate parallely 0.2.6 from https://pypi.org/simple/parallely/>
          <Candidate parallely 0.2.4 from https://pypi.org/simple/parallely/>
          <Candidate parallely 0.2.3 from https://pypi.org/simple/parallely/>
          <Candidate parallely 0.2.2 from https://pypi.org/simple/parallely/>
          <Candidate parallely 0.2.1 from https://pypi.org/simple/parallely/>
          <Candidate parallely 0.2.0 from https://pypi.org/simple/parallely/>
          <Candidate parallely 0.1.0 from https://pypi.org/simple/parallely/>
  Adding requirement python>=3.8
======== Starting round 0 ========
Resolving: new pin python >=3.8
======== Ending round 0 ========
======== Starting round 1 ========
  Adding requirement asyncio<4.0.0,>=3.4.3(from parallely 0.2.6)
        Found matching candidates:
          <Candidate asyncio 3.4.3 from https://pypi.org/simple/asyncio/>
  Adding requirement nest-asyncio<2.0.0,>=1.5.1(from parallely 0.2.6)
        Found matching candidates:
          <Candidate nest-asyncio 1.5.4 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.3 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.2 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.1 from https://pypi.org/simple/nest-asyncio/>
  Adding requirement pathos<0.3.0,>=0.2.8(from parallely 0.2.6)
        Found matching candidates:
          <Candidate pathos 0.2.8 from https://pypi.org/simple/pathos/>
  Adding requirement python>=3.7,<3.11(from parallely 0.2.6)
  Adding requirement asyncio<4.0.0,>=3.4.3(from parallely 0.2.6)
        Found matching candidates:
          <Candidate asyncio 3.4.3 from https://pypi.org/simple/asyncio/>
  Adding requirement nest-asyncio<2.0.0,>=1.5.1(from parallely 0.2.6)
        Found matching candidates:
          <Candidate nest-asyncio 1.5.4 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.3 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.2 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.1 from https://pypi.org/simple/nest-asyncio/>
  Adding requirement pathos<0.3.0,>=0.2.8(from parallely 0.2.6)
        Found matching candidates:
          <Candidate pathos 0.2.8 from https://pypi.org/simple/pathos/>
  Adding requirement python>=3.7,<3.11(from parallely 0.2.6)
  Adding requirement asyncio<4.0.0,>=3.4.3(from parallely 0.2.4)
        Found matching candidates:
          <Candidate asyncio 3.4.3 from https://pypi.org/simple/asyncio/>
  Adding requirement nest-asyncio<2.0.0,>=1.5.1(from parallely 0.2.4)
        Found matching candidates:
          <Candidate nest-asyncio 1.5.4 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.3 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.2 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.1 from https://pypi.org/simple/nest-asyncio/>
  Adding requirement pathos<0.3.0,>=0.2.8(from parallely 0.2.4)
        Found matching candidates:
          <Candidate pathos 0.2.8 from https://pypi.org/simple/pathos/>
  Adding requirement python>=3.7,<3.11(from parallely 0.2.4)
  Adding requirement asyncio<4.0.0,>=3.4.3(from parallely 0.2.4)
        Found matching candidates:
          <Candidate asyncio 3.4.3 from https://pypi.org/simple/asyncio/>
  Adding requirement nest-asyncio<2.0.0,>=1.5.1(from parallely 0.2.4)
        Found matching candidates:
          <Candidate nest-asyncio 1.5.4 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.3 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.2 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.1 from https://pypi.org/simple/nest-asyncio/>
  Adding requirement pathos<0.3.0,>=0.2.8(from parallely 0.2.4)
        Found matching candidates:
          <Candidate pathos 0.2.8 from https://pypi.org/simple/pathos/>
  Adding requirement python>=3.7,<3.11(from parallely 0.2.4)
  Adding requirement asyncio<4.0.0,>=3.4.3(from parallely 0.2.3)
        Found matching candidates:
          <Candidate asyncio 3.4.3 from https://pypi.org/simple/asyncio/>
  Adding requirement nest-asyncio<2.0.0,>=1.5.1(from parallely 0.2.3)
        Found matching candidates:
          <Candidate nest-asyncio 1.5.4 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.3 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.2 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.1 from https://pypi.org/simple/nest-asyncio/>
  Adding requirement pathos<0.3.0,>=0.2.8(from parallely 0.2.3)
        Found matching candidates:
          <Candidate pathos 0.2.8 from https://pypi.org/simple/pathos/>
  Adding requirement python>=3.7,<3.11(from parallely 0.2.3)
  Adding requirement asyncio<4.0.0,>=3.4.3(from parallely 0.2.3)
        Found matching candidates:
          <Candidate asyncio 3.4.3 from https://pypi.org/simple/asyncio/>
  Adding requirement nest-asyncio<2.0.0,>=1.5.1(from parallely 0.2.3)
        Found matching candidates:
          <Candidate nest-asyncio 1.5.4 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.3 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.2 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.1 from https://pypi.org/simple/nest-asyncio/>
  Adding requirement pathos<0.3.0,>=0.2.8(from parallely 0.2.3)
        Found matching candidates:
          <Candidate pathos 0.2.8 from https://pypi.org/simple/pathos/>
  Adding requirement python>=3.7,<3.11(from parallely 0.2.3)
  Adding requirement asyncio<4.0.0,>=3.4.3(from parallely 0.2.2)
        Found matching candidates:
          <Candidate asyncio 3.4.3 from https://pypi.org/simple/asyncio/>
  Adding requirement nest-asyncio<2.0.0,>=1.5.1(from parallely 0.2.2)
        Found matching candidates:
          <Candidate nest-asyncio 1.5.4 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.3 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.2 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.1 from https://pypi.org/simple/nest-asyncio/>
  Adding requirement pathos<0.3.0,>=0.2.8(from parallely 0.2.2)
        Found matching candidates:
          <Candidate pathos 0.2.8 from https://pypi.org/simple/pathos/>
  Adding requirement python>=3.7,<3.11(from parallely 0.2.2)
  Adding requirement asyncio<4.0.0,>=3.4.3(from parallely 0.2.2)
        Found matching candidates:
          <Candidate asyncio 3.4.3 from https://pypi.org/simple/asyncio/>
  Adding requirement nest-asyncio<2.0.0,>=1.5.1(from parallely 0.2.2)
        Found matching candidates:
          <Candidate nest-asyncio 1.5.4 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.3 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.2 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.1 from https://pypi.org/simple/nest-asyncio/>
  Adding requirement pathos<0.3.0,>=0.2.8(from parallely 0.2.2)
        Found matching candidates:
          <Candidate pathos 0.2.8 from https://pypi.org/simple/pathos/>
  Adding requirement python>=3.7,<3.11(from parallely 0.2.2)
  Adding requirement asyncio<4.0.0,>=3.4.3(from parallely 0.2.1)
        Found matching candidates:
          <Candidate asyncio 3.4.3 from https://pypi.org/simple/asyncio/>
  Adding requirement nest-asyncio<2.0.0,>=1.5.1(from parallely 0.2.1)
        Found matching candidates:
          <Candidate nest-asyncio 1.5.4 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.3 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.2 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.1 from https://pypi.org/simple/nest-asyncio/>
  Adding requirement pathos<0.3.0,>=0.2.8(from parallely 0.2.1)
        Found matching candidates:
          <Candidate pathos 0.2.8 from https://pypi.org/simple/pathos/>
  Adding requirement python>=3.7,<3.11(from parallely 0.2.1)
  Adding requirement asyncio<4.0.0,>=3.4.3(from parallely 0.2.1)
        Found matching candidates:
          <Candidate asyncio 3.4.3 from https://pypi.org/simple/asyncio/>
  Adding requirement nest-asyncio<2.0.0,>=1.5.1(from parallely 0.2.1)
        Found matching candidates:
          <Candidate nest-asyncio 1.5.4 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.3 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.2 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.1 from https://pypi.org/simple/nest-asyncio/>
  Adding requirement pathos<0.3.0,>=0.2.8(from parallely 0.2.1)
        Found matching candidates:
          <Candidate pathos 0.2.8 from https://pypi.org/simple/pathos/>
  Adding requirement python>=3.7,<3.11(from parallely 0.2.1)
  Adding requirement asyncio<4.0.0,>=3.4.3(from parallely 0.2.0)
        Found matching candidates:
          <Candidate asyncio 3.4.3 from https://pypi.org/simple/asyncio/>
  Adding requirement nest-asyncio<2.0.0,>=1.5.1(from parallely 0.2.0)
        Found matching candidates:
          <Candidate nest-asyncio 1.5.4 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.3 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.2 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.1 from https://pypi.org/simple/nest-asyncio/>
  Adding requirement pathos<0.3.0,>=0.2.8(from parallely 0.2.0)
        Found matching candidates:
          <Candidate pathos 0.2.8 from https://pypi.org/simple/pathos/>
  Adding requirement python>=3.7.1,<3.11(from parallely 0.2.0)
  Adding requirement asyncio<4.0.0,>=3.4.3(from parallely 0.2.0)
        Found matching candidates:
          <Candidate asyncio 3.4.3 from https://pypi.org/simple/asyncio/>
  Adding requirement nest-asyncio<2.0.0,>=1.5.1(from parallely 0.2.0)
        Found matching candidates:
          <Candidate nest-asyncio 1.5.4 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.3 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.2 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.1 from https://pypi.org/simple/nest-asyncio/>
  Adding requirement pathos<0.3.0,>=0.2.8(from parallely 0.2.0)
        Found matching candidates:
          <Candidate pathos 0.2.8 from https://pypi.org/simple/pathos/>
  Adding requirement python>=3.7.1,<3.11(from parallely 0.2.0)
  Adding requirement asyncio<4.0.0,>=3.4.3(from parallely 0.1.0)
        Found matching candidates:
          <Candidate asyncio 3.4.3 from https://pypi.org/simple/asyncio/>
  Adding requirement nest-asyncio<2.0.0,>=1.5.1(from parallely 0.1.0)
        Found matching candidates:
          <Candidate nest-asyncio 1.5.4 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.3 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.2 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.1 from https://pypi.org/simple/nest-asyncio/>
  Adding requirement pathos<0.3.0,>=0.2.8(from parallely 0.1.0)
        Found matching candidates:
          <Candidate pathos 0.2.8 from https://pypi.org/simple/pathos/>
  Adding requirement python>=3.7.1,<3.11(from parallely 0.1.0)
  Adding requirement asyncio<4.0.0,>=3.4.3(from parallely 0.1.0)
        Found matching candidates:
          <Candidate asyncio 3.4.3 from https://pypi.org/simple/asyncio/>
  Adding requirement nest-asyncio<2.0.0,>=1.5.1(from parallely 0.1.0)
        Found matching candidates:
          <Candidate nest-asyncio 1.5.4 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.3 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.2 from https://pypi.org/simple/nest-asyncio/>
          <Candidate nest-asyncio 1.5.1 from https://pypi.org/simple/nest-asyncio/>
  Adding requirement pathos<0.3.0,>=0.2.8(from parallely 0.1.0)
        Found matching candidates:
          <Candidate pathos 0.2.8 from https://pypi.org/simple/pathos/>
  Adding requirement python>=3.7.1,<3.11(from parallely 0.1.0)
Conflicts detected:
  python>=3.8 (from project)
  python>=3.7,<3.11 (from <Candidate parallely 0.2.6 from https://pypi.org/simple/parallely/>)
  python>=3.8 (from project)
  python>=3.7,<3.11 (from <Candidate parallely 0.2.6 from https://pypi.org/simple/parallely/>)
  python>=3.8 (from project)
  python>=3.7,<3.11 (from <Candidate parallely 0.2.4 from https://pypi.org/simple/parallely/>)
  python>=3.8 (from project)
  python>=3.7,<3.11 (from <Candidate parallely 0.2.4 from https://pypi.org/simple/parallely/>)
  python>=3.8 (from project)
  python>=3.7,<3.11 (from <Candidate parallely 0.2.3 from https://pypi.org/simple/parallely/>)
  python>=3.8 (from project)
  python>=3.7,<3.11 (from <Candidate parallely 0.2.3 from https://pypi.org/simple/parallely/>)
  python>=3.8 (from project)
  python>=3.7,<3.11 (from <Candidate parallely 0.2.2 from https://pypi.org/simple/parallely/>)
  python>=3.8 (from project)
  python>=3.7,<3.11 (from <Candidate parallely 0.2.2 from https://pypi.org/simple/parallely/>)
  python>=3.8 (from project)
  python>=3.7,<3.11 (from <Candidate parallely 0.2.1 from https://pypi.org/simple/parallely/>)
  python>=3.8 (from project)
  python>=3.7,<3.11 (from <Candidate parallely 0.2.1 from https://pypi.org/simple/parallely/>)
  python>=3.8 (from project)
  python>=3.7.1,<3.11 (from <Candidate parallely 0.2.0 from https://pypi.org/simple/parallely/>)
  python>=3.8 (from project)
  python>=3.7.1,<3.11 (from <Candidate parallely 0.2.0 from https://pypi.org/simple/parallely/>)
  python>=3.8 (from project)
  python>=3.7.1,<3.11 (from <Candidate parallely 0.1.0 from https://pypi.org/simple/parallely/>)
  python>=3.8 (from project)
  python>=3.7.1,<3.11 (from <Candidate parallely 0.1.0 from https://pypi.org/simple/parallely/>)
Candidate rejected: python None
� Lock failed
Unable to find a resolution because the following dependencies don't work on all Python versions defined by the project's `requires-python`: >=3.8
  python>=3.7,<3.11 (from <Candidate parallely 0.2.1 from https://pypi.org/simple/parallely/>)
  python>=3.7,<3.11 (from <Candidate parallely 0.2.2 from https://pypi.org/simple/parallely/>)
  python>=3.7,<3.11 (from <Candidate parallely 0.2.3 from https://pypi.org/simple/parallely/>)
  python>=3.7,<3.11 (from <Candidate parallely 0.2.4 from https://pypi.org/simple/parallely/>)
  python>=3.7,<3.11 (from <Candidate parallely 0.2.6 from https://pypi.org/simple/parallely/>)
  python>=3.7.1,<3.11 (from <Candidate parallely 0.1.0 from https://pypi.org/simple/parallely/>)
  python>=3.7.1,<3.11 (from <Candidate parallely 0.2.0 from https://pypi.org/simple/parallely/>)
To fix this, you can change the value of `requires-python` in pyproject.toml.
Traceback (most recent call last):
  File "/home/tester/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/tester/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/core.py", line 233, in main
    return Core().main(args)
  File "/home/tester/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/core.py", line 168, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/home/tester/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/core.py", line 163, in main
    f(options.project, options)
  File "/home/tester/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/cli/commands/add.py", line 53, in handle
    actions.do_add(
  File "/home/tester/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/cli/actions.py", line 235, in do_add
    resolved = do_lock(project, strategy, tracked_names, reqs, dry_run=dry_run)
  File "/home/tester/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/cli/actions.py", line 95, in do_lock
    raise ResolutionImpossible("Unable to find a resolution") from None
resolvelib.resolvers.ResolutionImpossible: Unable to find a resolution

```

## Environment Information

```bash
❯ pdm info
PDM version:        1.13.5
Python Interpreter: /usr/bin/python (3.8)
Project Root:       /home/tester/test
Project Packages:   /home/tester/test/__pypackages__/3.8

❯ pdm info --env
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.10",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.10.16.3-microsoft-standard-WSL2",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Fri Apr 2 22:23:49 UTC 2021",
  "python_full_version": "3.8.10",
  "platform_python_implementation": "CPython",
  "python_version": "3.8",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
> `Unable to find a resolution because the following dependencies don't work on all Python versions defined by the project's `requires-python`: >=3.8`

As it says, some of the dependencies doesn't work on Python 3.11 while your project is supposed to work on Python `>=3.8`, which can't be satisfied.

Add `<3.11` to the project's `requires-python` can fix this.

**Comment by robogast** [comment]
I have the same issue; as a question: why is this not supported?
The developer _personally_ needs python >= 3.8 (for whatever reason), and the package requires <3.11.

Why doesn't PDM resolve to `python >=3.8,<3.11`?
