### ISSUE TITLE
Unable to build certain packages after setuptools recent upgrade

### ISSUE THREAD

**Issue by dqd** [pdm-project/pdm#999]
- [ x ] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce
I am trying to install [contrast-agent](https://pypi.org/project/contrast-agent/) using pdm. However, I am unable to build this package with [the recent release of setuptools](https://github.com/pypa/setuptools/releases/tag/v61.0.0). My idea was that I would like to use the previous version of setuptools for building the contrast-agent package.

```bash
$ pdm init -vn
Creating a pyproject.toml for PDM...
Using the last selection, add '-i' to ignore it.
Using Python interpreter: /usr/local/bin/python (3.8)
Changes are written to pyproject.toml
$ pdm add -v contrast-agent setuptools==60.10.0
Adding packages to default dependencies: contrast-agent, setuptools==60.10.0
======== Start resolving requirements ========
  contrast-agent
  setuptools==60.10.0
  python>=3.8
  Adding requirement contrast-agent
        Found matching candidates:
          <Candidate contrast-agent 5.5.0 from https://pypi.org/simple/contrast-agent/>
          <Candidate contrast-agent 5.4.0 from https://pypi.org/simple/contrast-agent/>
          <Candidate contrast-agent 5.3.0 from https://pypi.org/simple/contrast-agent/>
          <Candidate contrast-agent 5.2.0 from https://pypi.org/simple/contrast-agent/>
          <Candidate contrast-agent 5.1.0 from https://pypi.org/simple/contrast-agent/>
          <Candidate contrast-agent 5.0.2 from https://pypi.org/simple/contrast-agent/>
          <Candidate contrast-agent 5.0.1 from https://pypi.org/simple/contrast-agent/>
          <Candidate contrast-agent 5.0.0 from https://pypi.org/simple/contrast-agent/>
          <Candidate contrast-agent 4.14.3 from https://pypi.org/simple/contrast-agent/>
          <Candidate contrast-agent 4.14.2 from https://pypi.org/simple/contrast-agent/>
          ... [39 more candidate(s)]
  Adding requirement setuptools==60.10.0
        Found matching candidates:
          <Candidate setuptools 60.10.0 from https://pypi.org/simple/setuptools/>
  Adding requirement python>=3.8
======== Starting round 0 ========
Resolving: new pin python >=3.8
======== Ending round 0 ========
======== Starting round 1 ========
Resolving: new pin setuptools 60.10.0
======== Ending round 1 ========
======== Starting round 2 ========
  Adding requirement setuptools>=8.2.1(from contrast-agent 5.5.0)
        Found matching candidates:
          <Candidate setuptools 60.10.0 from https://pypi.org/simple/setuptools/>
  Adding requirement protobuf<4,>=3.12; python_version >= "3"(from contrast-agent 5.5.0)
        Found matching candidates:
          <Candidate protobuf 3.19.4 from https://pypi.org/simple/protobuf/>
          <Candidate protobuf 3.19.3 from https://pypi.org/simple/protobuf/>
          <Candidate protobuf 3.19.2 from https://pypi.org/simple/protobuf/>
          <Candidate protobuf 3.19.1 from https://pypi.org/simple/protobuf/>
          <Candidate protobuf 3.19.0 from https://pypi.org/simple/protobuf/>
          <Candidate protobuf 3.18.1 from https://pypi.org/simple/protobuf/>
          <Candidate protobuf 3.18.0 from https://pypi.org/simple/protobuf/>
          <Candidate protobuf 3.17.3 from https://pypi.org/simple/protobuf/>
          <Candidate protobuf 3.17.2 from https://pypi.org/simple/protobuf/>
          <Candidate protobuf 3.17.1 from https://pypi.org/simple/protobuf/>
          ... [556 more candidate(s)]
  Adding requirement psutil<6,>=5.7(from contrast-agent 5.5.0)
        Found matching candidates:
          <Candidate psutil 5.9.0 from https://pypi.org/simple/psutil/>
          <Candidate psutil 5.8.0 from https://pypi.org/simple/psutil/>
          <Candidate psutil 5.7.3 from https://pypi.org/simple/psutil/>
          <Candidate psutil 5.7.2 from https://pypi.org/simple/psutil/>
          <Candidate psutil 5.7.1 from https://pypi.org/simple/psutil/>
          <Candidate psutil 5.7.0 from https://pypi.org/simple/psutil/>
  Adding requirement requests<3,>=2.4.2(from contrast-agent 5.5.0)
        Found matching candidates:
          <Candidate requests 2.27.1 from https://pypi.org/simple/requests/>
          <Candidate requests 2.27.0 from https://pypi.org/simple/requests/>
          <Candidate requests 2.26.0 from https://pypi.org/simple/requests/>
          <Candidate requests 2.25.1 from https://pypi.org/simple/requests/>
          <Candidate requests 2.25.0 from https://pypi.org/simple/requests/>
          <Candidate requests 2.24.0 from https://pypi.org/simple/requests/>
          <Candidate requests 2.23.0 from https://pypi.org/simple/requests/>
          <Candidate requests 2.22.0 from https://pypi.org/simple/requests/>
          <Candidate requests 2.21.0 from https://pypi.org/simple/requests/>
          <Candidate requests 2.20.1 from https://pypi.org/simple/requests/>
          ... [104 more candidate(s)]
Resolving: new pin contrast-agent 5.5.0
======== Ending round 2 ========
======== Starting round 3 ========
Resolving: new pin protobuf 3.19.4
======== Ending round 3 ========
======== Starting round 4 ========
Resolving: new pin psutil 5.9.0
======== Ending round 4 ========
======== Starting round 5 ========
  Adding requirement urllib3<1.27,>=1.21.1(from requests 2.27.1)
        Found matching candidates:
          <Candidate urllib3 1.26.9 from https://pypi.org/simple/urllib3/>
          <Candidate urllib3 1.26.8 from https://pypi.org/simple/urllib3/>
          <Candidate urllib3 1.26.7 from https://pypi.org/simple/urllib3/>
          <Candidate urllib3 1.26.6 from https://pypi.org/simple/urllib3/>
          <Candidate urllib3 1.26.5 from https://pypi.org/simple/urllib3/>
          <Candidate urllib3 1.26.4 from https://pypi.org/simple/urllib3/>
          <Candidate urllib3 1.26.3 from https://pypi.org/simple/urllib3/>
          <Candidate urllib3 1.26.2 from https://pypi.org/simple/urllib3/>
          <Candidate urllib3 1.26.1 from https://pypi.org/simple/urllib3/>
          <Candidate urllib3 1.26.0 from https://pypi.org/simple/urllib3/>
          ... [48 more candidate(s)]
  Adding requirement certifi>=2017.4.17(from requests 2.27.1)
        Found matching candidates:
          <Candidate certifi 2021.10.8 from https://pypi.org/simple/certifi/>
          <Candidate certifi 2021.5.30 from https://pypi.org/simple/certifi/>
          <Candidate certifi 2020.12.5 from https://pypi.org/simple/certifi/>
          <Candidate certifi 2020.11.8 from https://pypi.org/simple/certifi/>
          <Candidate certifi 2020.6.20 from https://pypi.org/simple/certifi/>
          <Candidate certifi 2020.4.5.2 from https://pypi.org/simple/certifi/>
          <Candidate certifi 2020.4.5.1 from https://pypi.org/simple/certifi/>
          <Candidate certifi 2020.4.5 from https://pypi.org/simple/certifi/>
          <Candidate certifi 2019.11.28 from https://pypi.org/simple/certifi/>
          <Candidate certifi 2019.9.11 from https://pypi.org/simple/certifi/>
          ... [34 more candidate(s)]
  Adding requirement charset-normalizer~=2.0.0; python_version >= "3"(from requests 2.27.1)
        Found matching candidates:
          <Candidate charset-normalizer 2.0.12 from https://pypi.org/simple/charset-normalizer/>
          <Candidate charset-normalizer 2.0.11 from https://pypi.org/simple/charset-normalizer/>
          <Candidate charset-normalizer 2.0.10 from https://pypi.org/simple/charset-normalizer/>
          <Candidate charset-normalizer 2.0.9 from https://pypi.org/simple/charset-normalizer/>
          <Candidate charset-normalizer 2.0.8 from https://pypi.org/simple/charset-normalizer/>
          <Candidate charset-normalizer 2.0.7 from https://pypi.org/simple/charset-normalizer/>
          <Candidate charset-normalizer 2.0.6 from https://pypi.org/simple/charset-normalizer/>
          <Candidate charset-normalizer 2.0.5 from https://pypi.org/simple/charset-normalizer/>
          <Candidate charset-normalizer 2.0.4 from https://pypi.org/simple/charset-normalizer/>
          <Candidate charset-normalizer 2.0.3 from https://pypi.org/simple/charset-normalizer/>
          ... [16 more candidate(s)]
  Adding requirement idna<4,>=2.5; python_version >= "3"(from requests 2.27.1)
        Found matching candidates:
          <Candidate idna 3.3 from https://pypi.org/simple/idna/>
          <Candidate idna 3.2 from https://pypi.org/simple/idna/>
          <Candidate idna 3.1 from https://pypi.org/simple/idna/>
          <Candidate idna 3.0 from https://pypi.org/simple/idna/>
          <Candidate idna 2.10 from https://pypi.org/simple/idna/>
          <Candidate idna 2.9 from https://pypi.org/simple/idna/>
          <Candidate idna 2.8 from https://pypi.org/simple/idna/>
          <Candidate idna 2.7 from https://pypi.org/simple/idna/>
          <Candidate idna 2.6 from https://pypi.org/simple/idna/>
          <Candidate idna 2.5 from https://pypi.org/simple/idna/>
Resolving: new pin requests 2.27.1
======== Ending round 5 ========
======== Starting round 6 ========
Resolving: new pin certifi 2021.10.8
======== Ending round 6 ========
======== Starting round 7 ========
Resolving: new pin charset-normalizer 2.0.12
======== Ending round 7 ========
======== Starting round 8 ========
Resolving: new pin idna 3.3
======== Ending round 8 ========
======== Starting round 9 ========
Resolving: new pin urllib3 1.26.9
======== Ending round 9 ========
======== Starting round 10 ========
======== Resolution Result ========
Stable pins:
              python None
          setuptools 60.10.0
      contrast-agent 5.5.0
            protobuf 3.19.4
              psutil 5.9.0
            requests 2.27.1
             certifi 2021.10.8
  charset-normalizer 2.0.12
                idna 3.3
             urllib3 1.26.9
        Found matching candidates:
          <Candidate setuptools 60.10.0 from https://pypi.org/simple/setuptools/>
        Found matching candidates:
          <Candidate contrast-agent 5.5.0 from https://pypi.org/simple/contrast-agent/>
        Found matching candidates:
          <Candidate protobuf 3.19.4 from https://pypi.org/simple/protobuf/>
        Found matching candidates:
          <Candidate psutil 5.9.0 from https://pypi.org/simple/psutil/>
        Found matching candidates:
          <Candidate requests 2.27.1 from https://pypi.org/simple/requests/>
        Found matching candidates:
          <Candidate certifi 2021.10.8 from https://pypi.org/simple/certifi/>
        Found matching candidates:
          <Candidate charset-normalizer 2.0.12 from https://pypi.org/simple/charset-normalizer/>
        Found matching candidates:
          <Candidate idna 3.3 from https://pypi.org/simple/idna/>
        Found matching candidates:
          <Candidate urllib3 1.26.9 from https://pypi.org/simple/urllib3/>
🔒 Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
Synchronizing working set with lock file: 9 to add, 0 to update, 0 to remove

Install setuptools 60.10.0 successful
Install requests 2.27.1 successful
Install certifi 2021.10.8 successful
Install charset-normalizer 2.0.12 successful
Install idna 3.3 successful
Install psutil 5.9.0 successful
Install urllib3 1.26.9 successful
Install protobuf 3.19.4 successful
Preparing isolated env for PEP 517 build...
Building wheel for https://files.pythonhosted.org/packages/80/fe/f74526b67d39d1d1fd262c3d0f99524f32345af445d2e23b1b522a06e857/contrast-agent-5.5.0.tar.gz#sha256=4f1d8c49dce71398ff0caf1230900dfa28db95f067d84c12501ef842a62dffa2 (from https://pypi.org/simple/contrast-agent/) (requires-python:>=3.7)
Collecting setuptools>=40.8.0
  Using cached setuptools-61.0.0-py3-none-any.whl (1.1 MB)
Collecting wheel
  Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
Installing collected packages: setuptools, wheel
  WARNING: The script wheel is installed in '/tmp/pdm-build-env-5nk6ue94-shared/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed setuptools-61.0.0 wheel-0.37.1
Traceback (most recent call last):
  File "/home/dqd/.local/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 363, in <module>
    main()
  File "/home/dqd/.local/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 345, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/home/dqd/.local/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/tmp/pdm-build-env-5nk6ue94-shared/lib/python3.8/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
    return self._get_build_requires(
  File "/tmp/pdm-build-env-5nk6ue94-shared/lib/python3.8/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
    self.run_setup()
  File "/tmp/pdm-build-env-5nk6ue94-shared/lib/python3.8/site-packages/setuptools/build_meta.py", line 281, in run_setup
    super(_BuildMetaLegacyBackend,
  File "/tmp/pdm-build-env-5nk6ue94-shared/lib/python3.8/site-packages/setuptools/build_meta.py", line 174, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 13, in <module>
    from setuptools.errors import DistutilsError
ImportError: cannot import name 'DistutilsError' from 'setuptools.errors' (/tmp/pdm-build-env-5nk6ue94-shared/lib/python3.8/site-packages/setuptools/errors.py)
Install contrast-agent 5.5.0 failed
Error occurs: 
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/dqd/.local/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 185, in install_candidate
    self.manager.install(can)
  File "/home/dqd/.local/lib/python3.8/site-packages/pdm/installers/manager.py", line 39, in install
    installer(prepared.build(), self.environment, prepared.direct_url())
  File "/home/dqd/.local/lib/python3.8/site-packages/pdm/models/candidates.py", line 332, in build
    self.wheel = builder.build(build_dir, metadata_directory=self._metadata_dir)
  File "/home/dqd/.local/lib/python3.8/site-packages/pdm/builders/wheel.py", line 26, in build
    requires = self._hook.get_requires_for_build_wheel(config_settings)
  File "/home/dqd/.local/lib/python3.8/site-packages/pep517/wrappers.py", line 172, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "/home/dqd/.local/lib/python3.8/site-packages/pep517/wrappers.py", line 322, in _call_hook
    self._subprocess_runner(
  File "/home/dqd/.local/lib/python3.8/site-packages/pdm/builders/base.py", line 238, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
  File "/home/dqd/.local/lib/python3.8/site-packages/pdm/builders/base.py", line 86, in log_subprocessor
    raise BuildError(
pdm.exceptions.BuildError: Call command ['/usr/local/bin/python', '/home/dqd/.local/lib/python3.8/site-packages/pep517/in_process/_in_process.py', 'get_requires_for_build_wheel', '/tmp/tmpas_42jor'] return non-zero status(1).
  Retry failed jobs
Preparing isolated env for PEP 517 build...
Reusing shared build env: /tmp/pdm-build-env-5nk6ue94-shared
Building wheel for https://files.pythonhosted.org/packages/80/fe/f74526b67d39d1d1fd262c3d0f99524f32345af445d2e23b1b522a06e857/contrast-agent-5.5.0.tar.gz#sha256=4f1d8c49dce71398ff0caf1230900dfa28db95f067d84c12501ef842a62dffa2 (from https://pypi.org/simple/contrast-agent/) (requires-python:>=3.7)
Traceback (most recent call last):
  File "/home/dqd/.local/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 363, in <module>
    main()
  File "/home/dqd/.local/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 345, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/home/dqd/.local/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/tmp/pdm-build-env-5nk6ue94-shared/lib/python3.8/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
    return self._get_build_requires(
  File "/tmp/pdm-build-env-5nk6ue94-shared/lib/python3.8/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
    self.run_setup()
  File "/tmp/pdm-build-env-5nk6ue94-shared/lib/python3.8/site-packages/setuptools/build_meta.py", line 281, in run_setup
    super(_BuildMetaLegacyBackend,
  File "/tmp/pdm-build-env-5nk6ue94-shared/lib/python3.8/site-packages/setuptools/build_meta.py", line 174, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 13, in <module>
    from setuptools.errors import DistutilsError
ImportError: cannot import name 'DistutilsError' from 'setuptools.errors' (/tmp/pdm-build-env-5nk6ue94-shared/lib/python3.8/site-packages/setuptools/errors.py)
Install contrast-agent 5.5.0 failed
Error occurs: 
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/dqd/.local/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 185, in install_candidate
    self.manager.install(can)
  File "/home/dqd/.local/lib/python3.8/site-packages/pdm/installers/manager.py", line 39, in install
    installer(prepared.build(), self.environment, prepared.direct_url())
  File "/home/dqd/.local/lib/python3.8/site-packages/pdm/models/candidates.py", line 332, in build
    self.wheel = builder.build(build_dir, metadata_directory=self._metadata_dir)
  File "/home/dqd/.local/lib/python3.8/site-packages/pdm/builders/wheel.py", line 26, in build
    requires = self._hook.get_requires_for_build_wheel(config_settings)
  File "/home/dqd/.local/lib/python3.8/site-packages/pep517/wrappers.py", line 172, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "/home/dqd/.local/lib/python3.8/site-packages/pep517/wrappers.py", line 322, in _call_hook
    self._subprocess_runner(
  File "/home/dqd/.local/lib/python3.8/site-packages/pdm/builders/base.py", line 238, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
  File "/home/dqd/.local/lib/python3.8/site-packages/pdm/builders/base.py", line 86, in log_subprocessor
    raise BuildError(
pdm.exceptions.BuildError: Call command ['/usr/local/bin/python', '/home/dqd/.local/lib/python3.8/site-packages/pep517/in_process/_in_process.py', 'get_requires_for_build_wheel', '/tmp/tmp58hg6ony'] return non-zero status(1).

ERRORS:
add contrast-agent failed:
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/dqd/.local/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 185, in install_candidate
    self.manager.install(can)
  File "/home/dqd/.local/lib/python3.8/site-packages/pdm/installers/manager.py", line 39, in install
    installer(prepared.build(), self.environment, prepared.direct_url())
  File "/home/dqd/.local/lib/python3.8/site-packages/pdm/models/candidates.py", line 332, in build
    self.wheel = builder.build(build_dir, metadata_directory=self._metadata_dir)
  File "/home/dqd/.local/lib/python3.8/site-packages/pdm/builders/wheel.py", line 26, in build
    requires = self._hook.get_requires_for_build_wheel(config_settings)
  File "/home/dqd/.local/lib/python3.8/site-packages/pep517/wrappers.py", line 172, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "/home/dqd/.local/lib/python3.8/site-packages/pep517/wrappers.py", line 322, in _call_hook
    self._subprocess_runner(
  File "/home/dqd/.local/lib/python3.8/site-packages/pdm/builders/base.py", line 238, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
  File "/home/dqd/.local/lib/python3.8/site-packages/pdm/builders/base.py", line 86, in log_subprocessor
    raise BuildError(
pdm.exceptions.BuildError: Call command ['/usr/local/bin/python', '/home/dqd/.local/lib/python3.8/site-packages/pep517/in_process/_in_process.py', 'get_requires_for_build_wheel', '/tmp/tmp58hg6ony'] return non-zero status(1).

Traceback (most recent call last):
  File "/home/dqd/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/dqd/.local/lib/python3.8/site-packages/pdm/core.py", line 233, in main
    return Core().main(args)
  File "/home/dqd/.local/lib/python3.8/site-packages/pdm/core.py", line 168, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/home/dqd/.local/lib/python3.8/site-packages/pdm/core.py", line 163, in main
    f(options.project, options)
  File "/home/dqd/.local/lib/python3.8/site-packages/pdm/cli/commands/add.py", line 53, in handle
    actions.do_add(
  File "/home/dqd/.local/lib/python3.8/site-packages/pdm/cli/actions.py", line 245, in do_add
    do_sync(
  File "/home/dqd/.local/lib/python3.8/site-packages/pdm/cli/actions.py", line 190, in do_sync
    handler.synchronize()
  File "/home/dqd/.local/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 352, in synchronize
    raise InstallationError("Some package operations are not complete yet")
pdm.exceptions.InstallationError: Some package operations are not complete yet
```

## Actual behavior

As you can see above, the latest version of setuptools is used, which causes the build to fail:

```bash
Collecting setuptools>=40.8.0
  Using cached setuptools-61.0.0-py3-none-any.whl (1.1 MB)
```

## Expected behavior

I expected `setuptools==60.10.0` to be used, because this is what I specified in the command.

## Environment Information

```bash
PDM version:        1.13.5
Python Interpreter: /usr/local/bin/python (3.8)
Project Root:       /home/dqd/src/pdm-test
Project Packages:   /home/dqd/src/pdm-test/__pypackages__/3.8
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.10",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.13.0-30-generic",
  "platform_system": "Linux",
  "platform_version": "#33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022",
  "python_full_version": "3.8.10",
  "platform_python_implementation": "CPython",
  "python_version": "3.8",
  "sys_platform": "linux"
}
```

**Comment by dqd** [comment]
It is possible that I misunderstood the issue completely, as I am able to install the `contrast-package` using pip with the latest setuptools:
```
$ pip3 install --user --upgrade setuptools
Requirement already satisfied: setuptools in ./.local/lib/python3.8/site-packages (60.10.0)
Collecting setuptools
 Using cached setuptools-61.0.0-py3-none-any.whl (1.1 MB)
Installing collected packages: setuptools
 Attempting uninstall: setuptools
   Found existing installation: setuptools 60.10.0
   Uninstalling setuptools-60.10.0:
     Successfully uninstalled setuptools-60.10.0
Successfully installed setuptools-61.0.0
$ pip3 install --user --upgrade contrast-agent
Requirement already satisfied: contrast-agent in ./.local/lib/python3.8/site-packages (4.12.0)
Collecting contrast-agent
 Downloading contrast-agent-5.5.0.tar.gz (10.7 MB)
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 856.2 kB/s eta 0:00:00
 Installing build dependencies ... done
 Getting requirements to build wheel ... done
 Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: requests<3,>=2.4.2 in ./.local/lib/python3.8/site-packages (from contrast-agent) (2.26.0)
Requirement already satisfied: psutil<6,>=5.7 in ./.local/lib/python3.8/site-packages (from contrast-agent) (5.8.0)
Requirement already satisfied: setuptools>=8.2.1 in ./.local/lib/python3.8/site-packages (from contrast-agent) (61.0.0)
Requirement already satisfied: protobuf<4,>=3.12 in ./.local/lib/python3.8/site-packages (from contrast-agent) (3.17.3)
Requirement already satisfied: six>=1.9 in ./.local/lib/python3.8/site-packages (from protobuf<4,>=3.12->contrast-agent) (1.16.0)
Requirement already satisfied: idna<4,>=2.5 in ./.local/lib/python3.8/site-packages (from requests<3,>=2.4.2->contrast-agent) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in ./.local/lib/python3.8/site-packages (from requests<3,>=2.4.2->contrast-agent) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./.local/lib/python3.8/site-packages (from requests<3,>=2.4.2->contrast-agent) (1.26.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in ./.local/lib/python3.8/site-packages (from requests<3,>=2.4.2->contrast-agent) (2.0.7)
Building wheels for collected packages: contrast-agent
 Building wheel for contrast-agent (pyproject.toml) ... done
 Created wheel for contrast-agent: filename=contrast_agent-5.5.0-cp38-cp38-linux_x86_64.whl size=11259032 sha256=8cf9a990a430fecc605d06df56dff4ad4628831f02833d371b9f03a26b665171
 Stored in directory: /home/dqd/.cache/pip/wheels/70/cd/ff/e4633a67270cd98e0ffd8383a771c187b4e8bda5c71860cf48
Successfully built contrast-agent
Installing collected packages: contrast-agent
 Attempting uninstall: contrast-agent
   Found existing installation: contrast-agent 4.12.0
   Uninstalling contrast-agent-4.12.0:
     Successfully uninstalled contrast-agent-4.12.0
Successfully installed contrast-agent-5.5.0
```
Could it be actually a completely different problem in pdm? Honestly, I am not able to tell.

**Comment by frostming** [comment]
Using pip also fails:

```
❯ pip install -U pip setuptools
Requirement already satisfied: pip in ./abc/lib/python3.10/site-packages (21.2.3)
Collecting pip
  Using cached pip-22.0.4-py3-none-any.whl (2.1 MB)
Requirement already satisfied: setuptools in ./abc/lib/python3.10/site-packages (57.4.0)
Collecting setuptools
  Using cached setuptools-61.1.0-py3-none-any.whl (1.1 MB)
Installing collected packages: setuptools, pip
  Attempting uninstall: setuptools
    Found existing installation: setuptools 57.4.0
    Uninstalling setuptools-57.4.0:
      Successfully uninstalled setuptools-57.4.0
  Attempting uninstall: pip
    Found existing installation: pip 21.2.3
    Uninstalling pip-21.2.3:
      Successfully uninstalled pip-21.2.3
Successfully installed pip-22.0.4 setuptools-61.1.0
❯ pip install contrast-agent
Collecting contrast-agent
  Using cached contrast-agent-5.5.0.tar.gz (10.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/Users/fming/wkspace/github/test-pipenv/abc/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/fming/wkspace/github/test-pipenv/abc/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/fming/wkspace/github/test-pipenv/abc/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/4d/r05n15jx1yv7yd4z7qrtmdm00000gn/T/pip-build-env-x_sj_6ig/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/private/var/folders/4d/r05n15jx1yv7yd4z7qrtmdm00000gn/T/pip-build-env-x_sj_6ig/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/4d/r05n15jx1yv7yd4z7qrtmdm00000gn/T/pip-build-env-x_sj_6ig/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 281, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/4d/r05n15jx1yv7yd4z7qrtmdm00000gn/T/pip-build-env-x_sj_6ig/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 13, in <module>
          from setuptools.errors import DistutilsError
      ImportError: cannot import name 'DistutilsError' from 'setuptools.errors' (/private/var/folders/4d/r05n15jx1yv7yd4z7qrtmdm00000gn/T/pip-build-env-x_sj_6ig/overlay/lib/python3.10/site-packages/setuptools/errors.py)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

So it is a problem of `contrast-agent` not compatible with `setuptools>=61`.

If you want to restrict the version of `setuptools` by `pdm add`, you need to pass `--no-isolation` to install `contrast-agent`:

```
pdm add "setuptools<61"
pdm add --no-isolation contrast-agent
```
